- clouddriver-web/clouddriver-web.gradle
> reference /opt in startScripts

- clouddriver-web/clouddriver-web.gradle
See https://github.com/spinnaker/spinnaker/pull/571
> Consistent naming for packages

- clouddriver-aws/README.md
- clouddriver-aws/clouddriver-aws.gradle
Reverts spinnaker/clouddriver#185
> Revert "Without these dependencies, everything compiles, unit tests run, and …"

- oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/view/CatsApplicationProvider.groovy
- oort/oort-cf/src/main/groovy/com/netflix/spinnaker/oort/cf/model/CloudFoundryApplicationProvider.groovy
- oort/oort-core/src/main/groovy/com/netflix/spinnaker/oort/model/ApplicationProvider.groovy
- oort/oort-core/src/main/groovy/com/netflix/spinnaker/oort/model/NoopApplicationProvider.groovy
- oort/oort-gce/src/main/groovy/com/netflix/spinnaker/oort/gce/model/GoogleApplicationProvider.groovy
- oort/oort-gce/src/test/groovy/com/netflix/spinnaker/oort/gce/model/GoogleApplicationProviderSpec.groovy
- oort/oort-titan/src/main/groovy/com/netflix/spinnaker/oort/titan/caching/providers/TitanApplicationProvider.groovy
- oort/oort-web/src/main/groovy/com/netflix/spinnaker/oort/controllers/ApplicationsController.groovy
- oort/oort-web/src/test/groovy/com/netflix/spinnaker/oort/ApplicationControllerSpec.groovy
- Expanding the CLUSTERS relationship takes time and is unnecessary in a lot of situations (perhaps all)
> /applications now supports relationship expansion (?expand=true)

- build.gradle
- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/KubernetesCloudProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/KubernetesConfiguration.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/KubernetesOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/config/clouddriver.yml
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
- settings.gradle
> Introduce Kubernetes as a cloud provider in clouddriver

- kato/kato-cf/src/main/groovy/com/netflix/spinnaker/kato/cf/deploy/description/CloudFoundryDeployDescription.groovy
- kato/kato-cf/src/main/groovy/com/netflix/spinnaker/kato/cf/deploy/handlers/CloudFoundryDeployHandler.groovy
- oort/oort-cf/src/main/groovy/com/netflix/spinnaker/oort/cf/model/CloudFoundryApplicationInstance.groovy
- oort/oort-cf/src/main/groovy/com/netflix/spinnaker/oort/cf/model/CloudFoundryResourceRetriever.groovy
* Add ability to customize the buildpack for a CF deployment
* Add ability to customize memory settings for a CF deployment
* Polish up some details so one off deployments don't blow up under the assumption of a trigger when there is none
> Add buildpack and memory support to CF

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/DeployKubernetesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/KubernetesAtomicOperationConverterHelper.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/KubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/DeployKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/KubernetesContainerValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtilSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/DeployKubernetesAtomicOperationConverterSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/DeployKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
Added deploy server group operation to Kubernetes provider. All code is in Clouddriver, due to #225. Mock tests and validators for all operations are included.
@duftler @ttomsu @skim1420
> provider/kubernetes: deploy server group

- build.gradle
- gradle/buildViaTravis.sh
- gradle/installViaTravis.sh
shot in the dark at a bit more consistent Travis CI build result..
> explicit JVM and test memory sizing

- kato/kato-cf/src/main/groovy/com/netflix/spinnaker/kato/cf/deploy/converters/CloudFoundryDeployAtomicOperationConverter.groovy
- kato/kato-cf/src/main/groovy/com/netflix/spinnaker/kato/cf/deploy/handlers/CloudFoundryDeployHandler.groovy
- kato/kato-cf/src/test/groovy/com/netflix/spinnaker/kato/cf/deploy/converters/CloudFoundryDeployAtomicOperationConverterUnitSpec.groovy
* Properly support a list of options to swap
* Move the logic into the converter
> Fix CF templating for deployment

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetriever.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentials.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetrieverSpec.groovy
- clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtilsSpec.groovy
> Add support for indexing images from additional GCP projects.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/DefaultAWSAccountInfoLookup.java
Still requires there is an existing VPC in us-east-1 for accountId resolution, or the account is EC2 classic enabled
Fixes spinnaker/spinnaker#630
> Changes the way accountId is discovered so it does not fail if the default VPC has been removed

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeregisterInstancesFromLoadBalancerAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/RegisterInstancesWithLoadBalancerAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/DeregisterInstancesFromLoadBalancerDescriptionValidator.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/RegisterInstancesWithLoadBalancerDescriptionValidator.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeregisterInstancesFromGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/RegisterInstancesWithGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeregisterInstancesFromGoogleLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/RegisterInstancesWithGoogleLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/DeregisterInstancesFromGoogleLoadBalancerDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/RegisterInstancesWithGoogleLoadBalancerDescriptionValidator.groovy
> Adds register/deregister instances with LB AtomicOperation entry and annotations.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/ModifyAsgLaunchConfigurationOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/ModifyAsgLaunchConfigurationDescriptionValidator.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ModifyGoogleServerGroupInstanceTemplateAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/ModifyGoogleServerGroupInstanceTemplateDescriptionValidator.groovy
@duftler PTAL
@spinnaker/reviewers FYI
> Adds UpdateLaunchConfig Atomic operation.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
Handle case when most recently-created server group does not define sequential number segment in its name.
@skim1420 please review.
> Handle case when no server groups presently exist in cluster.

- clouddriver-aws/UserData.md
Initial cut of documentation on how to inject user data
> Documentation around customizing userdata for aws

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetriever.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperationUnitSpec.groovy
- clouddriver-web/config/clouddriver.yml
> Index GCE Windows images.

- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/model/CloudFoundryOnDemandCacheUpdater.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/NoopOnDemandCacheUpdater.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandAgent.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandCacheUpdater.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleOnDemandCacheUpdater.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy
- mort/mort-aws/src/main/groovy/com/netflix/spinnaker/mort/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
- oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/agent/ClusterCachingAgent.groovy
- oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/agent/LoadBalancerCachingAgent.groovy
- ClusterCachingAgent is the only Agent currently surfacing results
> An endpoint that provides a view into pending onDemand requests

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.groovy
I realized it is a bit of a pain to create namespaces with `kubectl`, so I allow clouddriver to create them. 
@duftler, this should be a quicky.
> provider/kubernetes: Create namespaces defined by credentials

- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/model/CloudFoundryOnDemandCacheUpdater.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/NoopOnDemandCacheUpdater.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandCacheUpdater.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleOnDemandCacheUpdater.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy
- 200 if the cache update has been applied immediately
- 202 if the cache update has been queued for application (with the expectation that a caller will poll for completion)
> CacheController will now return either 200 / 202 responses

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/AbstractEnableDisableInstanceDiscoveryAtomicOperation.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/EnableDisableInstancesInDiscoveryAtomicOperationUnitSpec.groovy
> Stop us trying to add terminating instances to discovery

- oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/agent/ClusterCachingAgent.groovy
- This will occur when an attempt is made to forceCache an ASG that no longer exists ... in such situations the record will never be processed.
> Avoid writing an empty OnDemand cache record

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy
> provider/kubernetes: On demand caching for server groups.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetriever.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
> Stuff GCE load balancers in Redis, step 1.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
> provider/kubernetes: Avoid adding on demand results for missing server groups.

- oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/agent/ClusterCachingAgent.groovy
- In these cases, `asg.status` will be non-null
> Avoid indexing server groups that are in the process of terminating

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealth.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstanceProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
Also introduces HEALTH namespace, which will be tackled next. 
@spinnaker/reviewers FYI
> Adds GoogleInstance caching agent + provider

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/DeployKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
Changes needed in clouddriver for incoming Deck PR, which allows you to deploy to images populated by your docker registry accounts.
@duftler
> provider/kubernetes: Touchups needed for deploys from docker registry.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/CloneKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/DeployKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/CloneKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/DeployKubernetesAtomicOperationValidatorSpec.groovy
…
Also fixed an agent caching typo
> provider/kubernetes: Image pull secrets are now populated automatically rather than by requirement.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoader.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoaderSpec.groovy
- Corresponding change in deck will show a warning
> Support marking a region (within an account) as deprecated

- build.gradle
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonSubnet.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProvider.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProviderSpec.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/subnet/view/AzureSubnetProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopSubnetProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Subnet.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/SubnetProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleSubnet.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSubnetProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SubnetController.groovy
Add cloudProvider attribute to Subnet interface.
Modify SubnetController list() entrypoint to return a map of cloudProvider -> list-of-subnets.
Add listByCloudProvider() entrypoint to SubnetController.
Update AmazonSubnetProvider to only retrieve 'aws' identifiers.
Update GoogleNetworkProvider to only retrieve 'gce' identifiers.
> Cache Google subnets via cats.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
> provider/kubernetes: Only load relevant onDemand data

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSubnetProvider.groovy
> Missed replacing cloudProvider with type.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
> provider/kubernetes: Touchups needed to display load balancers in Deck.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy
@duftler 
After this PR is merged, a user can deploy a functioning app (using only clouddriver). Deck still needs to add this functionality as well as surface a way to create load balancers (services).
> provider/kubernetes: Allow user to specify container ports

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
> provider/docker: Fixed loading of docker credentials

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
> provider/docker: Provide the container registry an image is coming from.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Cluster.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleCloudProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleCluster.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleCluster2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstanceProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/ImagesCallback.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/InstanceAggregatedListCallback.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleLoadBalancerHealth.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/search/GoogleSearchProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
- clouddriver-web/config/clouddriver.yml
Plus a few other cleanups and whatnot.
@duftler @lwander PTAQL
> Google ServerGroup and Cluster objects moved to Serialized + View model

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
@duftler, @skim1420 - fixes what you pointed out.
> provider/kubernetes: Fix omitted namespaces bug

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/BasicGoogleDeployAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleApplication.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleCluster.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleCluster2.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/BasicGoogleDeployAtomicOperationConverterUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/TerminateGoogleInstancesAtomicOperationConverterUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandlerSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/TerminateGoogleInstancesDescriptionValidatorSpec.groovy
Find All --> Replace FTW!
@duftler
> Netflix -> Google copyrights on clouddriver-google module

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
Also removed a few unused parameters and fixed a typo
> Fix for insufficiently unique storage account name

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleApplication.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleApplication2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleApplicationProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleCluster2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleApplicationProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-web/config/clouddriver.yml
Also alphabetizes the JSON output for easier comparison between the old and new implementations ( @anotherchrisberry - swanky, eh?)
@duftler @lwander
> GCE Cluster and Application Serialization +  View model

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
UI is no longer barfing on cluster and instance errors!
@duftler @lwander FYI
> Removes dynamicProperties from GoogleServerGroup2 and GoogleInstance2

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProvider.groovy
> Adds currentActions and securityGroups to instances.

- clouddriver-web/clouddriver-web.gradle
@spinnaker-ro @duftler PTAL. Simple fix to get swagger back.
> Swagger dependency fix

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstancePlacement.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstanceSpec.groovy
FYI @cfieber, I'm working on exposing this in deck next.
> add containerIp to titus instance placement

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/ResizeKubernetesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/ResizeKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/ResizeKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/ResizeKubernetesAtomicOperationValidator.groovy
> provider/kubernetes: Resize operation

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
Used groovy meta programming hack in test to compensate for original difficult to test design. (Not a good thing)
> Should not classic link LC when the ASG is in VPC.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/LaunchConfigurationBuilder.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyAsgLaunchConfigurationDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy
> Updates AWS create/clone server group and modify launch config to support explicitly specifying classicLinkSecurityGroups

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy
In non-default VPCs, the AWS SDK does not return the `groupName` attribute on ingress security group rules.
Currently, we have code in Deck that accommodates this by looking up the group name in an index of cached security groups if necessary, but this code is brittle and I'd like to remove it. This should allow us to do that.
@claymccoy please review
> add security group name if available to ingress permissions

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/DockerRegistryConfiguration.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/health/DockerRegistryHealthIndicator.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
- clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy
- clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy
This feeds into docker registry triggers coming later.
@duftler
> provider/docker: Cache content digests for triggers.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
> provider/kubernetes: Retrieve resource YAML.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerDescription.groovy
That keeps us from creating internal ELBs.
> isInternal should be a Boolean, otherwise "false" as a String is true

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
@spinnaker/netflix-reviewers @duftler Simple bug fix PTAL
> Fix for capitalization restrictions in Azure

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/config/DockerRegistryProviderConfig.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
> provider/docker: Optionally parallelize caching of images by repo

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AWSProxy.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
- clouddriver-web/config/clouddriver.yml
Created AWSProxy as springboot @configurationProperties
Updated AmazonClientProvider
Tested with and without proxy
> adding proxy support for aws v2

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
On writes and deletes, the both the type:members and type:members.2 sets are updated with the ids. As a reindexing operation we execute
````groovy
def expiredIdSet = UUID.randomUUID().toString()
jedis.eval("redis.call('rename', KEYS[1], KEYS[3]); redis.call('rename', KEYS[2], KEYS[1]); return 'OK'", ['type:members', 'type:members.2', expiredIdSet], [])
jedis.expire(expiredIdSet, 1)
````
This rotates the type:members.2 set to type:members and leaves type:members.2 empty to get freshly repopulated. This is an attempt to address leaking
keys from the caching agents.
Over-the-shoulder reviewed by @ajordens
> Adds a secondary index of ids to the cache to allow a flush and rebuild maintenance operation.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy
Last week, we fixed the case where non-default VPC security groups were not returning the group name for ingress security group rules.
This week, we'll fix the case where the security groups are both in VPCs but in different accounts, meaning they have different `vpcId`s in their cache keys, meaning they don't get picked up by the search, meaning they don't get returned in the response with a valid name.
@spinnaker/netflix-reviewers please review
> correctly attach names and vpcIds to cross-account security group rules

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy
This is the equivalent of a health checking mechanism for Kubernetes. More information is here: http://kubernetes.io/v1.1/docs/user-guide/liveness/README.html
@duftler
> provider/kubernetes: Liveness & readiness probes

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
Fixing default encoding issues in clouddriver.
> fixing default encoding issues

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
* Adds a key to disable hashing
* Pipelines evictions calls
* Writes the backup index before the main index so we can swap backup overtop of main
@ajordens PTAL
> Change the caching a bit they said. It will be easy they said.

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
@spinnaker/netflix-reviewers @duftler PTAL
> Add security group to subnet

- clouddriver-web/etc/init/clouddriver.conf
this change works together with PR by @ewiseblatt
https://github.com/spinnaker/spinnaker/pull/784
> auto start clouddriver service if clouddriver is installed standalone issue #762

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
> provider/docker: Support registries using only basic authentication

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
50% of the time my boolean logic works all of the time
> fix bug trying to short circuit hashing

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProvider.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
> provider/kubernetes: Provide deck with details needed for search results

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/instance/DeregisterKubernetesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/instance/RegisterKubernetesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/instance/AbstractRegistrationKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/instance/KubernetesInstanceDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/AbstractRegistrationKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/DeregisterKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/RegisterKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/AbstractRegistrationKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/DeregisterKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/RegisterKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
@duftler 
register/deregister instances by manipulating the labels that attach them to load balancers.
> provider/kubernetes: (De)register instances

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/HealthState.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy
> provider/kubernetes: Properly report health to Deck

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
**Please only review the second commit.** https://github.com/spinnaker/clouddriver/pull/419 needs to be merged first.
This PR pulls in the Autoscaling policy fetching into the server group caching agent. 
@duftler @lwander PTAL.
> Ports GCE Autoscaling policies to new impl

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/instance/AbstractRegistrationKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/instance/KubernetesInstanceDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/AbstractRegistrationKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/AbstractRegistrationKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesInstanceProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy
@duftler 
Changes made to enable/disable required changes to register/deregister. Also, there were a few assumptions that Deck was making about how to format the register/deregister operation that I didn't have in my original PR.
> provider/kubernetes: Register instance fixups

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/vmimage/model/AzureNamedImage.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/vmimage/view/AzureVMImageLookupController.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
- clouddriver-web/config/clouddriver.yml
Added the ability to specify a custom user image in a storage account to use for the server group.
@spinnaker/netflix-reviewers @spinnaker/google-reviewers PTAL
> Add custom image to create server group

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/FailureLogger.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
> Makes all callbacks implement FailureLogger

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/DestroyKubernetesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/EnableKubernetesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/KubernetesServerGroupDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DisableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/EnableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DestroyKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DisableKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/EnableKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesServerGroupDescriptionValidator.groovy
@duftler.
I moved the shared generic server group description from enable/disable into a `KubernetesServerGroupDescription`.
> provider/kubernetes: Destroy server group

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/DeleteKubernetesLoadBalancerAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/DeleteKubernetesLoadBalancerAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/DeleteKubernetesLoadBalancerAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/DeleteKubernetesLoadBalancerAtomicOperationValidator.groovy
> provider/kubernetes: Delete load balancer

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/instance/TerminateKubernetesInstancesAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/DeregisterKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/RegisterKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/instance/TerminateKubernetesInstancesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/AbstractKubernetesInstancesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/TerminateKubernetesInstancesAtomicOperationValidator.groovy
> provider/kubernetes: Delete instance operation

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureStorageClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/vmimage/view/AzureVMImageLookupController.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureNamedAccountCredentials.groovy
- clouddriver-web/config/clouddriver.yml
Fix unexpected exception thrown while attempting to retrieve the list of custom images from a specified storage account.
> Bug fix; custom image storage read

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/cache/AzureCachingAgent.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/cache/MutableCacheData.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/view/AzureInfrastructureProviderConfig.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/AzureResourceOpsDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/cache/Keys.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/model/AzureDeploymentOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/description/AzureServerGroupDescriptionUnitSpec.groovy
Added caching for Azure server groups. Includes some minor bug fixes
> initial implementation of server groups caching

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgentSpec.groovy
> Simplifies/cleans up constructors of GCE caching agents

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
When server groups are deleted from Deck, they must first be disabled. Already disabled server groups were showing up as healthy, making the disable operation a NoOp, causing the delete operation to hang indefinitely. 
@ewiseblatt @duftler
> provider/kubernetes: Mark disabled server groups w/o load balancers as unknown

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController2.groovy
Getting close to being able to disable `GoogleResourceRetriever`!
> New impl of GoogleLoadBalancerController

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleOnDemandCacheUpdater.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetriever.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
> Makes last GRR-dependent component conditional

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
Implements pod volumes http://kubernetes.io/docs/user-guide/volumes/ and environment variables. Note, this doesn't allow a user to create volumes that outlive a container, but if one exists (created by kubectl), the user can now attach it to their pod.
> provider/kubernetes: Pod volumes & env vars

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/securitygroups/HttpRule.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesSecurityGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesSecurityGroupSummary.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesSecurityGroupProvider.groovy
Dont merge yet - security groups aren't showing up in deck (I'm guessing I have to surface the relationships between load balancers and security groups). 
@duftler
> provider/kubernetes: Cache security groups

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
@lwander can you try this out locally to make sure it's working as expected?
> provide noop bean for cloudMetrics if no others configured

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/ResizeKubernetesAtomicOperation.groovy
@ttomsu 
When a destructive Kubernetes operation completes (excluding destroy), there is a chance that the state the user has requested has not propagated throughout the entire cluster yet. 
To see why this is dangerous, imagine a user does the following in a pipeline:
Resize RC to 0 -> Destroy RC
Meanwhile, the resize completes, however the RC's state is not reflected in the entire k8s cluster. When the destroy happens, it might destroy the RC while it still has some non-zero size in some part of the k8s cluster. The pods are orphaned, and resources are leaked.
To avoid this, I implemented an exponential backoff strategy waiting for the generation numbers of the requested and current kubernetes objects to match.
> provider/kubernetes: Block until kubernetes state is consistent

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
@ttomsu - addresses the TODO you left me after you cleaned up the load balancer providers.
> provider/kubernetes: Provide missing instances to kubernetes load balancers

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/exception/DockerRegistryOperationException.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
- clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy
> provider/docker: Paginage catalog results

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/securitygroup/DeleteKubernetesSecurityGroupAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/securitygroup/DeleteKubernetesSecurityGroupDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/securitygroup/DeleteKubernetesSecurityGroupAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/securitygroup/DeleteKubernetesSecurityGroupAtomicOperationValidator.groovy
> provider/kubernetes: Delete security group

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
Reports which security groups a load balancer is associated with to Deck
@ttomsu or @duftler
> provider/kubernetes: Report load balancer <-> security group

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/CacheResultBuilder.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/cache/CacheResultBuilderSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgentSpec.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
This was more complicated than I expected, and I still have to do it twice more :facepunch: (side note, they have a "facepunch" emoji? Github wins the day!)
@lwander PTAL - this was all based off of the `KubernetesServerGroupCachingAgent`
@duftler, @jtk54 FYI
> Adds OnDemand support to GoogleServerGroupCachingAgent

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
@lwander - note the comment in the code that includes your idea to make on demand caching simpler. These impls are good enough, IMO, until that's ready.
@duftler, @jtk54 FYI 
> GCE OnDemandAgents + GCE LB display issues

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/AzureCloudProvider.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/application/view/AzureApplicationProvider.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/cluster/model/AzureCluster.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/cluster/view/AzureClusterProvider.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/AzureResourceOpsDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/cache/Keys.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstance.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/cache/KeysSpec.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/description/AzureServerGroupDescriptionUnitSpec.groovy
Added functionality to retrieve cluseter and server group data from cache and pass back to the UI
> Implement server group/cluster providers

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
Originally, I was only recreating namespaces that were missing the cluster health mechanism. If a docker registry specifies a namespace it can deploy to that doesn't exist, the credential initialization fails.
> provider/kubernetes: Namespace create bug

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/securitygroup/UpsertKubernetesSecurityGroupAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesSecurityGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
Ingress backends were being created when they were omitted, deleted cache results would (somewhat silently) fail a force cache refresh, and http probe handlers weren't being created.
@duftler
> provider/kubernetes: Noticed a few bugs while testing this weekend

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertSecurityGroupAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/SecurityGroupLookupFactory.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertSecurityGroupAtomicOperationUnitSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/SecurityGroupLookupSpec.groovy
In the uncommon case that the security group we are upserting appears between the time that we look for it and create it, we will get an AWS error. We now look again skipping the cache.  We don't want to skip the cache here in the normal case because it usually isn't required and has throttled AWS when creating many security groups at once during a VPC migration in prod.
> get security group and skip cache if we need to on upsert

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleNamedImageLookupController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleInstanceHealth.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProvider.groovy
Includes pulling out a new View object out of the `GoogleInstanceHealth` class.
@duftler @lwander @jtk54 PTAL
> Odds and ends found during citest-ing.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
citest's Google server group, kato, and smoke tests all pass without any a stack traces after these changes. 
@duftler @lwander
> Fix NoSuchElementException from GCE on demand cache handler

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientInvocationHandler.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/EddaTimeoutConfig.java
@spinnaker/netflix-reviewers ptal
tested by unplugging the network cable while it was running...
> Adds retry support when calling edda for AWS resources

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroup.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroupResources.groovy
> Titus: surface instance logs and stdLive and servergroup allocateIpAddress

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
A user has noticed this code path failing due to a gstring conversion error that I can't seem to replicate. Hopefully this fixes it.
@duftler
> provider/kubernetes: Trying to catch a groovy string bug

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReport.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
- Each account will be loaded in parallel
> rx-ified the ReservationReportCachingAgent

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservedInstancesCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
- Updated ReservationReport caching agent to use the cached ReservedInstances data rather than calling AWS directly
- Adjusted ReservationReport caching agent to only run every minute
> Introduced a ReservedInstances caching agent (runs every 10 minutes)

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
> provider/docker: Defer loading _catalog until after initialization

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
> filter instance relationships for significant performance improvement on large server groups

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/cache/Keys.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
Fix bug in server group caching agent. Includes some refactoring.
> instance caching bug fix

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservedInstancesCachingAgent.groovy
- Additional logging in ReservationReport caching agent
> ReservedInstances caching agent only caches 'active' RIs

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesJobNameResolver.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesServerGroupNameResolver.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/job/RunKubernetesJobAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/KubernetesJobDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/KubernetesContainerValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/KubernetesVolumeSourceValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/job/RunKubernetesJobAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
@duftler 
Refactored common code shared by deploy server group and run job.
Models jobs as Kubernetes Jobs: http://kubernetes.io/docs/user-guide/jobs/
> provider/kubernetes: Run Job operation

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
Copied from Kubernetes impl.
@lwander @jtk54 PTAL
> Fix deserialization error when moving from on demand namespace.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
> Remove extraneous callback class.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
> Hopefully fixes conversion errors found in nightly tests.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgentSpec.groovy
- clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtilsSpec.groovy
> Hooks up requiredGroupMembership to Google credentials

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureNamedAccountCredentials.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/security/CloudFoundryAccountCredentials.groovy
- clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/security/CloudFoundryAccountCredentialsSpec.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AccountCredentials.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/credentials/NetflixTitusCredentials.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerSpec.groovy
(by removing the API)
@spinnaker/reviewers @lwander PTAL
> Fixes startup warnings of the use of a deprecated API 

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureStorageClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
Add logic to check resource provider status and, if necessary, register the provider for the subscription
> register required resource providers in Azure.

- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/CachingAgent.java
- cats/cats-redis/cats-redis.gradle
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy
- clouddriver-web/config/clouddriver.yml
@cfieber @duftler
For an explanation of how this scheduler works, see the top of the ClusteredSortAgentScheduler.java
> cats: New scheduler

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ProcessController.groovy
> core: Allow job/process controllers to be optional

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperationSpec.groovy
At some point around 9/26/2012, something changed in AWS's load balancers, and to deal with it, it seems they add a weird listener to any ELBs created before then. This listener has no protocol - internal or external - and maps port 0 to port 0. Also it wreaks havoc on upsert operations, since we expect a protocol, and Amazon doesn't allow you to delete it.
This PR just ignores it altogether.
@cfieber or @ajordens PTAL; fixes SPIN-1666
> provider/aws: disregard :0->:0 listener when upserting load balancers

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
> filter classic link security groups from source

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
> cats: Forgot `unschedule` in Sort scheduler

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
Suggested change by @jtk54 & @duftler 
@cfieber
> cats: Use redis rather than system for timestamp

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusConfiguration.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/credentials/NetflixTitusCredentials.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DestroyTitusServerGroupAtomicOperationSpec.groovy
this is for adding direct ssh to instance type links
> Titus: add a bastionHost field 

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeploymentResult.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJob.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.groovy
Correctly report Job failure, and forward created jobs name to Orca in DeploymentResults
@duftler
> provider/kubernetes: correctly report job failure state

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancer.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerController.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerProvider.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureLoadBalancerResourceTemplate.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/Resource.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/template/AzureAppGatewayResourceTemplateSpec.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/templates/AzureLoadBalancerResourceTemplateSpec.groovy
Implement Azure Application Gateway create template deployment (couple test cases included as well).
An Application Gateway resource provides an Azure-managed HTTP load-balancing solution based on layer-7 load balancing. These fit better in the Spinnaker load balancer model than the Azure Load Balancer resource that is currently used because it better suits transitioning from one active version of the server group to another. For more info about Azure application gateways and load balancer and how they compare see https://azure.microsoft.com/en-us/documentation/articles/application-gateway-introduction/
> Implement Azure Application Gateway create template deployment

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
> fix bug in server group caching when deleting

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureStorageClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstance.groovy
Handle when we get a timeout from Azure. Also handle when we get a HTTP response code of 429 - "Too many attempts" back from Azure
> Implement logic to handle retrying Azure operations

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.groovy
Not sure how this slipped past...
> provider/kubernetes: Single job lookups in wrong namespace

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/job/DestroyKubernetesJobAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/DestroyKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/job/DestroyKubernetesJobAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/job/KubernetesJobDescriptionValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/job/RunKubernetesJobAtomicOperationValidator.groovy
@ttomsu 
Analog is "Destroy server group".
> provider/kubernetes: Destroy job operation

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJob.groovy
> provider/kubernetes: Fix job count reporting

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/job/CloneKubernetesJobAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/CloneKubernetesJobAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/CloneKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/job/CloneKubernetesJobAtomicOperationValidator.groovy
@duftler 
Analog is clone server group.
> provider/kubernetes: Clone job

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/SubmitJobRequest.java
to get default security groups
> Titus: need to send in a null as securityGroups

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/SecurityGroupService.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/SecurityGroupServiceSpec.groovy
> filter SGs in describe requests

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJob.groovy
@duftler Needed in the pipeline job deploy for creating a dialog from a template.
> provider/kubernetes: Report deploy configuration for jobs

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
Updates the ARM template to set the backend address pool of the scale set accordingly
- Create backend address pool in Application Gateway for server group if it doesn't exist
- Move creation of internal load balancer associated with scale set into ARM template.
- Minor fixes
> Update Scale Set template to create a load balancer and associate AG 

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy
> if adding an app specific group would exceed the maximum number of groups, do nothing instead of failing the request

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroup.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroupSpec.groovy
in servergroups so it is independent of tasks
> Titus: change the way region and account are populated

- build.gradle
- cats/cats-redis/cats-redis/cats-redis.gradle
- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/etc/init/clouddriver.conf
- gradle/wrapper/gradle-wrapper.properties
Also updates upstart to use sudo instead of suid to support
older upstart version on Amazon Linux.
Also updates to Gradle 2.10
Fixes #266
Fixes #264
> Updates deb packaging to use project conventions from plugin.

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
> fix NPE if environment is not present

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/exception/KubernetesOperationException.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
Makes it easier to decipher errors in the logs with multiple accounts configured doing multiple operations.
@duftler
> provider/kubernetes: More descriptive error messages

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
I wound up returning the exception rather than throwing it in the method, because the intellij linter couldn't tell that calling a method that results in an exception will never return.
See https://github.com/spinnaker/clouddriver/pull/619 for context.
@duftler
> provider/kubernetes: Even better error messages

- AUTHORS
- clouddriver-openstack/clouddriver-openstack.gradle
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/OpenstackCloudProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/OpenstackConfiguration.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/OpenstackOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/config/OpenstackConfigurationProperties.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/health/OpenstackHealthIndicator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentials.java
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentialsInitializer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.java
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/OpenstackCloudProviderSpec.groovy
- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/config/clouddriver.yml
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
The beginnings of issue https://github.com/spinnaker/spinnaker/issues/890. Basic skeleton for openstack provider.
> Introduce Openstack as a provider in clouddriver

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Job.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/JobDescription.java
Also use the appName, jobGroupDetails, jobGroupName and jobGroupSequence to generate server group name if the label for name is not present.
> titus: JobGroupSequence

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/converters/DeleteAzureAppGatewayAtomicOperationConverter.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/converters/DeleteAzureLoadBalancerAtomicOperationConverter.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/cache/AzureSecurityGroupCachingAgent.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
Fixes for couple bugs in create server group and delete load balancer. Fix for a typo in the security group caching agent.
> Fixes for couple bugs in create server group and delete load balancer

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
Reverts spinnaker/clouddriver#529
> Revert "provider/kubernetes: Enable specifying image w/o dropdown"

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AssumeRoleAmazonCredentials.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/DefaultAWSAccountInfoLookup.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoader.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProviderSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/DefaultAWSAccountInfoLookupSpec.groovy
Some rework of #631
Closes #631
> Makes all AWS services interactions done via AmazonClientProvider

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java
> provider/google: Sync up jsonKey and non-jsonKey credentials handling.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
provider/google: Avoid NPE in load balancer controller when no matching load balancer is found.
> provider/google: Avoid NPE in load balancer caching agent.

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
@duftler PTAL,
@danielpeach FYI
> provider/docker: Limits number of images returned using `count`

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
> docker: fix tag lookup typo

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/LaunchConfigurationBuilder.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyAsgLaunchConfigurationDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/NullOpUserDataProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/UserDataProvider.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy
right now we don't have a great story for people looking to migrate from legacy udf to the newer style, this flag allows someone to deploy with the specific behaviour before flipping the flag at the application level
> expose per-deploy option to change udf generation behaviour

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
Cleaned up unused fields and imports. @duftler @ttomsu FYI
> Cleaned up unused fields and imports.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/instance/DeregisterOpenstackInstancesAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/instance/RebootOpenstackInstancesAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/instance/RegisterOpenstackInstancesAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/OpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/instance/OpenstackInstancesRegistrationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/exception/OpenstackProviderException.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/AbstractRegistrationOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/DeregisterOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/RegisterOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/instance/AbstractRegistrationOpenstackInstancesDescriptionValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/instance/DeregisterOpenstackInstancesDescriptionValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/instance/RegisterOpenstackInstancesDescriptionValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/AbstractRegistrationOpenstackInstancesAtomicOperationUnitSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/instance/AbstractRegistrationOpenstackInstancesDescriptionValidatorSpec.groovy
register and deregister instances with load balancer operations and unit tests.
> register and deregister instances with lb working fine

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/loadbalancer/DeleteOpenstackLoadbalancerAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/loadbalancer/DeleteOpenstackLoadBalancerDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/exception/OpenstackProviderException.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/DeleteOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/DeleteOpenstackLoadBalancerDescriptionValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/DeleteOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/DeleteOpenstackLoadBalancerDescriptionValidatorSpec.groovy
Implemented openstack delete load balancer operation.
> Delete load balancer operation.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/CloneOpenstackAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/securitygroup/UpsertOpenstackSecurityGroupAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/CloneOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/exception/OpenstackResourceNotFoundException.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/CloneOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
Following Kubernetes commit stream: lwander@a4772c4
Issue: spinnaker/spinnaker#923
Resubmission of PR https://github.com/spinnaker/clouddriver/pull/674 now that I've squashed into one commit
> openstack clone server groups

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/OpenstackServerGroupNameResolver.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/CloneOpenstackAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/DeployOpenstackAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/CloneOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/DeployOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/CloneOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DeployOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/DeployOpenstackAtomicOperationConverterSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperationSpec.groovy
Also, moved deploy operations to "servergroup" package to match the other operations.
> refactor openstack deploy to use region

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/loadbalancer/OpenstackLoadBalancerDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/exception/OpenstackOperationException.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerMethod.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerPool.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerProtocol.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerResolver.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/PoolHealthMonitor.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/PoolHealthMonitorType.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/VirtualIP.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/task/TaskStatusAware.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/UpsertOpenstackLoadBalancerDescriptionValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerResolverSpec.groovy
Implements issue (#915)[https://github.com/spinnaker/spinnaker/issues/915]
> Openstack upsert load balancer.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/DestroyOpenstackAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/DestroyOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DestroyOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DestroyOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DestroyOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DestroyOpenstackAtomicOperationValidatorSpec.groovy
Implements issue spinnaker/spinnaker#928
> destroy openstack server group operation

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/BasicGoogleDeployDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/CopyLastGoogleServerGroupDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/CreateGoogleInstanceDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/ModifyGoogleServerGroupInstanceTemplateDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy
(gce) verify custom machine types
@duftler PTAL
> (gce) verify custom machine types

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/UpdateInstancesAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyAsgLaunchConfigurationDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpdateInstancesDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpdateInstancesAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/UpdateInstancesDescriptionValidator.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpdateInstancesAtomicOperationSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
> provider/aws: update ASG security groups support

- clouddriver-openstack/README.md
- clouddriver-openstack/clouddriver-openstack.gradle
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/OpenstackCloudProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientV2Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientV3Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackProviderFactory.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/config/OpenstackConfigurationProperties.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/DeregisterOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/RegisterOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackInstance.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/OpenstackInfastructureProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/MutableCacheData.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentialsInitializer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/KeysSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientV2ProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientV3ProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerResolverSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentialsSpec.groovy
- clouddriver-web/config/clouddriver.yml
https://github.com/spinnaker/spinnaker/issues/896
> Added openstack instance operations getInstance and getConsoleOutput

- clouddriver-openstack/clouddriver-openstack.gradle
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/CloneOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/DeployOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/CloneOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DeployOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/ServerGroupParameters.groovy
- clouddriver-openstack/src/main/resources/asg.yaml
- clouddriver-openstack/src/main/resources/asg_resource.yaml
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DeployOpenstackAtomicOperationValidatorSpec.groovy
Closes spinnaker/spinnaker#937
> Feature refactor create servergroup and servergroup clone

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
- (gce) updated vcpu max list.
- also updated link to corresponding list in deck.
@duftler PTAL
> (gce) updated vcpu max list

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/CacheResultBuilder.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackApplication.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/AbstractOpenstackCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackApplicationProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/KeysSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackApplicationProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProviderSpec.groovy
https://github.com/spinnaker/spinnaker/issues/953
> provider/openstack: Added application caching and operations

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Job.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJob.groovy
> provider/kubernetes: s/launchTime/createdTime for consistency

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
AWS doesn't like these to be duplicated, so...let's not duplicate them.
> (aws) Do not allow duplicate suspended processes

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
Fixes https://github.com/spinnaker/spinnaker/issues/866
> provider/kubernetes: Bump kubernetes api version

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackApplication.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackInstance.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackSubnet.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/OpenstackInfrastructureProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/AbstractOpenstackCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackSubnetCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackApplicationProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackSubnetProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/KeysSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackSubnetCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackApplicationProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackSubnetProviderSpec.groovy
Addresses https://github.com/spinnaker/spinnaker/issues/958
> provider/openstack: Subnet operations and caching

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/loadbalancer/OpenstackLoadBalancerDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
Have the floating IP get pulled from the pool or allocated based on the network id used.
> Feature lb network

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
> provider/google: Log result of on-demand cache update

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/discovery/TitusEurekaSupport.groovy
for case where instances do not register in discovery
> titus - fix disable operation

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/SecurityGroup.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/securitygroups/Rule.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackSecurityGroup.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackSecurityGroupCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackSecurityGroupProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/KeysSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackSecurityGroupSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackSecurityGroupCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackSecurityGroupProviderSpec.groovy
Closes spinnaker/spinnaker#969
> Added Openstack security group caching.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackImageLookupController.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/Image.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackCluster.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackImage.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLaunchConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackServerGroup.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/ImageProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackImageCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackClusterProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackImageProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controller/OpenstackImageLookupControllerSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackImageCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackClusterProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackImageProviderSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
partially implements https://github.com/spinnaker/spinnaker/issues/972
closes https://github.com/spinnaker/spinnaker/issues/931
> provider/openstack: Cluster/Image operations and caching

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
Fact: `equals` is not a method on `null`
> (aws) handle cross-VPC ELB migrations

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy
Also fixing references in the results to correctly show the app group instead of potentially showing the app load balancer group twice.
@cfieber PTAL
> (aws) guard against missing app group when dryRun migrating ELB

- clouddriver-consul/clouddriver-consul.gradle
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulAgent.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/AgentDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/CheckDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/CheckResult.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/ServiceDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/ServiceResult.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/AgentApi.groovy
- settings.gradle
This is the core set of features needed to make consul usable as a health/service discovery provider in Spinnaker.
@duftler FYI,
@ttomsu PTAL
> provider/consul: API definition

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackInstanceType.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/OpenstackInfrastructureProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceTypeCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceTypeProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceTypeCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceTypeProviderSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SearchController.groovy
closes https://github.com/spinnaker/spinnaker/issues/990
> provider/openstack: Instance type operation and caching

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/AgentDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/CheckDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/CheckResult.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/ServiceDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/ServiceResult.groovy
@ttomsu you were right, this is neater
> provider/consul: JSONProperty to fix field names

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulCatalog.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/NodeDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/CatalogApi.groovy
> provider/consul: consul catalog API support

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulKeyValueStore.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/KeyValuePair.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/KeyValueApi.groovy
> provider/consul: KV api support

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/AgentApi.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/config/ConsulConfig.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/ops/EnableDisableConsulInstance.groovy
> provider/consul: enable/disable op

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleScalingPolicyAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/DeleteGoogleScalingPolicyDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleScalingPolicyAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/DeleteGoogleScalingPolicyDescriptionValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleScalingPolicyAtomicOperationConverterUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleScalingPolicyAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/DeleteGoogleScalingPolicyDescriptionValidatorSpec.groovy
(gce) added delete scaling policy atomic operation
@duftler PTAL
> (gce) added delete scaling policy atomic operation

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
> (aws) backfill vpcId on ingress rule conversion

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
See https://github.com/spinnaker/clouddriver/pull/775 for context
> provider/google: fix loading of lb tab

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/securitygroup/UpsertOpenstackSecurityGroupDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/securitygroup/UpsertOpenstackSecurityGroupAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/securitygroup/UpsertOpenstackSecurityGroupDescriptionValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/securitygroup/UpsertOpenstackSecurityGroupAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/securitygroup/UpsertOpenstackSecurityGroupDescriptionValidatorSpec.groovy
Adds support for referencing other security groups and for UDP and ICMP rules.
> Flesh out upsert Openstack Security groups 

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulCatalog.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/config/ConsulConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
> provider/consul: Provide a way to get default config

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/ServiceDefinition.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/KeyValueApi.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/description/ConsulLoadBalancerDescription.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/ops/UpsertConsulLoadBalancer.groovy
> provider/consul: Upsert load balancer operation

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/ServerGroupMigrator.groovy
> (aws) finish changing serverGroupName to serverGroupNames

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/AbstractServergroupOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/ServerGroupParameters.groovy
- clouddriver-openstack/src/main/resources/asg.yaml
- clouddriver-openstack/src/main/resources/asg_resource.yaml
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DeployOpenstackAtomicOperationValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/ResizeOpenstackAtomicOperationValidatorSpec.groovy
Network is looked up via subnet and both are provided to the heat template.
closes spinnaker/spinnaker#994
> Provide subnet instead of network to server group

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulHealth.groovy
- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/model/EurekaInstance.groovy
You can't implement an abstract method with a static method cc @lwander
> implement abstract method in DiscoveryHealth

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/ops/RegisterConsulInstance.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/ops/UpsertConsulLoadBalancer.groovy
> provider/consul: Register instance on startup

- clouddriver-eureka/README.md
> Add some documentation around setting up Eureka as a dicovery service/health provider

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleAutoscalingPolicyAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/DeleteGoogleAutoscalingPolicyDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/DeleteGoogleAutoscalingPolicyDescriptionValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleAutoscalingPolicyAtomicOperationConverterUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/DeleteGoogleAutoscalingPolicyDescriptionValidatorSpec.groovy
@duftler please review. I verified that the operation still works as expected.
> (gce) renamed delete autoscaler classes

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancerType.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
Added support for L7 LBs in clone SVG operation. Tested with regional and zonal MIGs. @duftler @ttomsu @lwander PTAL.
> Added support for L7 LBs in clone SVG operation.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
Added loadBalancerType to LoadBalancerSummary. FYI @danielpeach @duftler.
> Added loadBalancerType to LoadBalancerSummary.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackNetwork.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgent.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackLoadBalancerControllerSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgentSpec.groovy
> Add network attributes to load balancer requests

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/OpenstackOnDemandCacheIntgSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy
closes https://github.com/spinnaker/spinnaker/issues/983
> provider/openstack: server group on-demand caching

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DisableGoogleServerGroupAtomicOperationUnitSpec.groovy
Implemented support for L7 disable. @duftler @ttomsu PTAL.
> Implemented support for L7 disable.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
Added backend services to Google LB summary. @danielpeach PTAL. @duftler FYI.
> Added backend services to Google LB summary.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
> provider/google: added region to LoadBalancerServerGroup.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancedBackend.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GooglePathRule.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
@duftler PTAL. @danielpeach FYI.
> provider/google: added Backend caching and fixed isDisabled state for L7.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
> provider/kubernetes: Better error message on secret config

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancedBackend.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
> provider/google: cleaned up unnecessary enum conversion.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
Also made 'queryAllLoadBalancers' return all cached LBs, not just in application scope. @duftler PTAL.
> provider/google: fixed default service population in L7.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
if associated with a server group from our application. @duftler PTAL.
> provider/google: cross application LBs returned from LB provider

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
@duftler PTAL. Sorry for whitespace noise.
> provider/google: destroy/disable work even if L7 Lb is absent.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategySpec.groovy
We will currently create infrastructure security groups if they are explicitly declared on source server groups or load balancers. We want to skip them if they're not present in the target. We're currently doing that if they're associated as an ingress rule on a security group; this takes care of the other case (associated as a security group of the load balancer/server group).
@cfieber sorry, PTAL
> (aws) skip infrastructure groups when migrating if not present in target

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BasicGoogleDeployDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
> provider/google: L7 support in server group create.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
so the server groups will actually receive traffic. @duftler PTAL.
> provider/google: set named ports on clone/create.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
> provider/google: prevent NPE in clone stage.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
Nothing fancy, just retrying a few times before failing when creating an application security group.
@ajordens PTAL (best viewed without whitespace, i.e. adding `w=1` to the URL here)
> provider/amazon: retry app security group creation if it fails

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/Keys.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/OnDemandAware.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/UnresolvableKeyException.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackNetworkingProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackNetworkingV2Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/AbstractOpenstackCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/config/OpenstackInfrastructureProviderConfig.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/OnDemandAwareSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/OpenstackOnDemandCacheIntgSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackNetworkingV2ClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgentSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy
closes https://github.com/spinnaker/spinnaker/issues/1029
> provider/openstack: Load balancer onDemand Caching

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategySpec.groovy
As far as I know, this only happens sometimes, when migrating the elusive `amazon-elb` security group (which we should skip) because it's an ingress rule of the rule we're migrating. But, since we don't have a credentials object, when we try to set the group name, we throw an NPE and it halts migration. This gets around that.
> provider/amazon: avoid NPE when migrating unknown security groups

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
> provider/amazon: do not copy user data on migrate operation

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy
When migrating a load balancer, it may have custom policies on its listeners, which should be copied over. It's pretty uncommon that listeners do have custom policies, but we want to make sure they align, anyway.
> provider/amazon: apply listener policies when migrating load balancers

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
> Added L7 loadBalancingPolicy to server group view for clone.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
> Added backend support for L7 capacity scaler.

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
Equipare the docker cli behaviour and the clouddriver behavior 
When login to a docker registry, the official behaviour is defined here
https://docs.docker.com/registry/spec/auth/token/
1. So, the first think it is trying to do is a connection to /v2/ endpoint
2. The server respond with a 401 with the auth details in the response
3. Then, the client try to auth.
In this first request is very docker cli and clouddriver differs.
Docker:
Docker client sends this first request without Authorization Header, see line 65 of attached log.
[nginx.txt](https://github.com/spinnaker/clouddriver/files/370858/nginx.txt)
CloudDriver:
Sends the query with the Authorization Header
This slightly difference makes our clouddriver to be down, cause the Docker Health Check always fails.
So, this PR pretends to …
> Docker registry

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/EnableGoogleServerGroupAtomicOperationUnitSpec.groovy
@duftler PTAL. Added a metadata entry for load balancing policy, since enable should know about the server group's backend configuration. Used that to make the magic happen.
> provider/google: enable support for L7 load balancers.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.groovy
> default environment and account type without breaking OSS

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgent.java
starts with a describeInstances call to build the complete set of EC2 classic instances
> need to ensure we get instances that have never been classiclinked when reconciling classic link groups

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
Also fixed disabled state. @duftler PTAL.
> provider/google: fixed L7 clone of unassociated server group.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy
@duftler or @lwander or @ttomsu
> provider/google: avoid unnecessary target proxy calls.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
@duftler or @lwander or @danielpeach PTAL.
> provider/google: return L7 LB policy from metadata.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy
So... there are reserved policy names. And we can't create policies with some prefixes, which means I had to rewrite the load balancer policy handling.
We now match policies by their attributes, and create a new name if the source policy name is from one of the AWS presets (in the case that the preset is not available on the migrated load balancer).
@ajordens PTAL
> provider/amazon: prefix reserved policy names when migrating ELBs

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
@lwander and/or @duftler please review. This takes care of both the 400 and 412 retries, and covers the 404 acceptance in destroy.
> provider/google: Added retry function, applied it to L7 updates.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
@lwander please review @duftler FYI.
> provider/google: Log platform error if retry fails repeatedly.

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsController.groovy
Someone requested this field, which seems reasonable.
@ajordens PTAL
> include accountId in credentials summary response

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy
Also fixes disabled state for the same case. @duftler or @lwander please review.
> provider/google: Fix disable of SVGs with same name in different regions

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/DeleteGoogleHttpLoadBalancerDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/DeleteGoogleLoadBalancerDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
Also included safe delete for network load balancers and optionally not deleting GCP health checks. @duftler please review.
> provider/google: Support for deleting Http(s) load balancers.

- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandler.groovy
Looking up buildInfo for a deployment needs safe navigation.
> provider/cf: Find buildInfo information with safe navigation

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy
@duftler please review
- updated gceVCpuMaxList.
- defaults to 16 cpus if the provided location is not on the list.
> provider/google updated gceVCpuMaxList

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/CreateGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
Used to report one per LB (incorrectly), now reports per backend service. @duftler or @lwander please review.
> provider/google: Report L7 health check per backend service.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperation/SerializeApplicationAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperationUnitSpec.groovy
Added a front 50 service for saving a snapshot of infrastructure to a gcs or aws bucket. Also added project fields to gce resources and fixed access configs. PTAL @lwander @duftler
> provider/google: Serialize saves infrastructure to bucket using Front 50, fixed project and access config fields

- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/cache/CacheUtils.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/model/CloudFoundryServerGroup.groovy
Needed for https://github.com/spinnaker/deck/pull/2585
> provider/cf: Provide extra details to support deck resizing

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
> provider/google: collectEntries in urlMap resolution.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
when calling the authorize or revoke ingress API, the IpPermission UserIdGroupPair can only have one of a groupId or groupName
> fix for regression on aws UpsertSecurityGroup

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/InMemoryTaskRepository.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/TaskRepository.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskRepository.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/OrchestrationProcessor.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/InMemoryTaskRepositorySpec.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskRepositorySpec.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessorSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsControllerSpec.groovy
> de-dupe operations based on user-supplied key

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
Turns out this was simpler than I was afraid it might be, since all UI details are stored in that DeployDescription object. 
@duftler
> provider/kubernetes: Render replica sets

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/ResizeKubernetesAtomicOperation.groovy
> provider/kubernetes: Resize replica sets

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
> provider/kubernetes: Delete replica set

- clouddriver-openstack/clouddriver-openstack.gradle
- clouddriver-web/clouddriver-web.gradle
closes https://github.com/spinnaker/spinnaker/issues/1077
> provider/openstack: Update client to release version.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesServerGroupNameResolver.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
> provide/kubernetes: Deploy replica set

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/CreateGoogleHttpLoadBalancerDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/CreateGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/CreateGoogleHttpLoadBalancerDescriptionValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/CreateGoogleHttpLoadBalancerAtomicOperationConverterUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/CreateGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/CreateGoogleHttpLoadBalancerTestConstants.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/CreateGoogleHttpLoadBalancerDescriptionValidatorSpec.groovy
@duftler @lwander @ttomsu please review. Probably could/should be tag-teamed.
> provider/google: support for L7 creation.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesJobNameResolver.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/CloneKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/DestroyKubernetesJobAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
> provider/kubernetes: Replaces jobs with pods in the Job operations

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy
Handles an edge case where an ASG in Classic is using a VPC load balancer, but that load balancer belongs to (based on its name) a different application.
When we cache the ASG, we look at its launch config to determine the load balancers (based on `loadBalancerNames` to derive its load balancer relationships, and generate load balancer entries based on the location of the ASG. If the load balancer is in VPC, we end up generating an invalid key, which does end up in search results (we'll show that there's a load balancer in both VPC and Classic with the same name); however, when we retrieve the application load balancers, we currently only try to look up the invalid (e.g. Classic) key, which drops out of the result set.
@cfieber PTAL
> provider/amazon: handle VPC load balancers on Classic ASGs

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackLoadBalancerProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackLoadBalancerV2Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationV1Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/MemberData.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/StackPoolMemberAware.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/AbstractOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/DeleteOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractStackUpdateOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/task/TaskStatusAware.groovy
- clouddriver-openstack/src/main/resources/asg.yaml
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationV1ClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/AbstractOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/DeleteOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/ResizeOpenstackAtomicOperationSpec.groovy
closes https://github.com/spinnaker/spinnaker/issues/1075
> provider/openstack: Delete loadbalancer operation.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
@duftler or @lwander please review.
> provider/google: Fix L7 clones when L4 SSL LB exists in project.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
> provider/google: Retry backend service updates during deploy.

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/CheckResult.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulHealth.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/provider/ConsulProviderUtils.groovy
> (consul) fix health check reporting for disabled instances

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatus.groovy
> (kubernetes) Job completion details may be null

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackLoadBalancerProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackLoadBalancerControllerSpec.groovy
The field was named different between upsert and get.
> Renamed lb method to algorithm

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesEvent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesInstanceProvider.groovy
Capture pod events, cache them, and send to the UI.
@duftler PTAL, @danielpeach FYI
> (kubernetes) log pod events

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
> (docker): stop returning empty images for missing accounts

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonLoadBalancerController.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/LoadBalancerCachingAgent.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/data/KeysSpec.groovy
For existing classic load balancers, the key structure will not change.
This is an incremental step towards adding application loadbalancers
> add loadBalancerType attribute to load balancer key, defaulted to 'classic'

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
> (google & consul) enable/disable

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackComputeProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackComputeV2Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationV1Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/DisableOpenstackAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/EnableOpenstackAtomicOperationConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/CloneOpenstackAtomicOperationDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractEnableDisableOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DisableOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackComputeV2ProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DisableOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy
closes https://github.com/spinnaker/spinnaker/issues/1093
> provider/openstack: Refactor instance lookup by stack id.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/snapshot/RestoreSnapshotAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/snapshot/SaveSnapshotAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/snapshot/RestoreSnapshotDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/snapshot/SaveSnapshotDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/snapshot/RestoreSnapshotAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/snapshot/SaveSnapshotAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/SerializeApplicationAtomicOperationConverterUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperationUnitSpec.groovy
Changed the name of the operation from serializeApplication to saveSnapshot. Also added terraform dependency for health check. PTAL @lwander
> provider/google: Changed name from serialize application to save snapshot

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
> (docker) check account during image lookup by query

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
> (kubernetes) specify image pull policy

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
> provider/google: Remove L7 load balancer feature flag.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/KubernetesVolumeSourceValidator.groovy
> (kubernetes) fixup enum usage to reduce `switch` usage

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
@duftler @lwander please review. Instead of more reporting in specific cases, I made the final `OperationException` more verbose with the final encountered exception.
> provider/google: More detail in safeRetry reporting.

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/CheckResult.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/model/ServiceResult.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/AgentApi.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/ops/EnableDisableConsulInstance.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulHealth.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulService.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/provider/ConsulProviderUtils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
@duftler This pretty much ties up the consul integration into GCP, but I think we should discuss how health checks are surfaced in Spinnaker tomorrow. Those adjustments can be made in a separate PR.
> (consul & google) fix enable/disable behavior

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateLoadBalancerDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategy.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerMigrator.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy
I'm still doing some manual testing so don't merge
> prefer pulling zones from the source load balancer if migrating within the same account/region

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/loadbalancer/OpenstackLoadBalancerDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerResolver.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/loadbalancer/UpsertOpenstackLoadBalancerDescriptionValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/domain/LoadBalancerResolverSpec.groovy
> provider/openstack: remove internalProtocol from load balancer upsert

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
> provider/google: Added UUID in path matcher name.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackComputeProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackComputeV2Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/LoadBalancerStatusAware.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/AbstractRegistrationOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractEnableDisableOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DisableOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/resources/asg.yaml
- clouddriver-openstack/src/main/resources/asg_resource.yaml
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/AbstractRegistrationOpenstackInstancesAtomicOperationUnitSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DisableOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableOpenstackAtomicOperationSpec.groovy
fix ip resolution and wait for proper load balancer state during registration and enable/disable operations.
closes spinnaker/spinnaker#1111
> provider/openstack: fix server ip resolution and load balancer state checking algorithm

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/edda/InstanceLoadBalancerState.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/edda/InstanceLoadBalancers.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/edda/LoadBalancerInstanceState.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerV2InstanceStateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy
adds healthState attribute to the per-loadbalancer detail in the health payload
> adds caching agent for ELBv2 health state

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
> if the ancestorAsg has v2 load balancers attach them to the new ASG

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerV2InstanceStateCachingAgent.groovy
(aws) Add attribute names to constructor call.
> (aws) NPE guard for ALB.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
> (kubernetes) failed to set imagePullSecrets

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulHealth.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulNode.groovy
- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/provider/ConsulProviderUtils.groovy
> (consul) when disabled, only show system health checks

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DisableInstancesInDiscoveryAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/EnableInstancesInDiscoveryAtomicOperationConverter.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/discovery/DisableInstancesInDiscoveryConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/discovery/EnableInstancesInDiscoveryConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/GoogleInstanceListDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/discovery/AbstractEnableDisableInstancesInDiscoveryOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/discovery/DisableInstancesInDiscoveryOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/discovery/EnableInstancesInDiscoveryOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/discovery/AbstractEnableDisableInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/discovery/DisableInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/discovery/EnableInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/DisableTitusInstancesInDiscoveryAtomicOperationConverter.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/EnableTitusInstancesInDiscoveryAtomicOperationConverter.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/DisableTitusInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/EnableTitusInstancesInDiscoveryDescriptionValidator.groovy
> (consul & google) enable/disable instance

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackProviderFactory.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackSwiftProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackSwiftV1Provider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackSwiftV1ProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidatorSpec.groovy
Currently just reads a file saved in a Swift object.
> (openstack) Added the Openstack Swift Provider.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesAutoscalerStatus.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroupSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy
This is missing semantics for "resize" and "clone", those are up next.
@duftler
> (kubernetes) horizontal pod autoscaling

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEServerGroupNameResolver.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/SafeRetry.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleSecurityGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleNetwork.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleSubnet.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleNetworkProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSubnetProvider.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleSecurityGroupAtomicOperationUnitSpec.groovy
(google) Reduce number of live compute calls.
> (google) Add additional retry behavior around compute calls.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
Implements a `SearchResultHydrator` for `BackendServices`. We want to suggest backend services in L7 upsert and have the user be able to choose which health check is associated with the backend service. The results from `/search` contain only a `name` attribute by default, so this augments the result to include the health check. @duftler please review. @danielpeach FYI.
> provider/google: Cache search hydrator for backend services.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/autoscaler/UpsertKubernetesAutoscalerAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/autoscaler/KubernetesAutoscalerDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/ResizeKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/autoscaler/UpsertKubernetesAutoscalerDescriptionValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/instance/AbstractKubernetesInstancesAtomicOperationValidator.groovy
> (kubernetes) adds upsert scaling policy

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ApplicationSearchProvider.groovy
- Also pass `pageSize` down to Front50
> Migrate from v1 -> v2 Front50 API

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
Turns out there's nothing called a `healCheck`. @lwander or @duftler please review.
> provider/google: Fixed upsert healthCheck update.

- clouddriver-security/clouddriver-security.gradle
@duftler @jtk54 PTAL
Tag: https://github.com/spinnaker/spinnaker/issues/1166
> Bumps Fiat version to 0.8.0

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/AbstractTitusCredentialsDescription.groovy
A first step in making all descriptions easier to manipulate (and strongly typed) within common controllers.
This is the fourth in a stack of PRs. Please do not merge.
@ajordens @cfieber
tag: spinnaker/spinnaker#1164
> Titus descriptions common interface

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/KubernetesAtomicOperationDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/AbstractTitusCredentialsDescription.groovy
A first step in making all descriptions easier to manipulate (and strongly typed) within common controllers.
This is the third in a stack of PRs. Please **do not** merge.
@lwander PTAL
tag: spinnaker/spinnaker#1164
> Kubernetes descriptions common interface

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/AzureResourceOpsDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/AbstractCloudFoundryDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/CloudFoundryDeployDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/DeleteCloudFoundryLoadBalancerDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/DestroyCloudFoundryServerGroupDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/EnableDisableCloudFoundryServerGroupDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/UpsertCloudFoundryLoadBalancerDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/KubernetesAtomicOperationDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/AbstractTitusCredentialsDescription.groovy
A first step in making all descriptions easier to manipulate (and strongly typed) within common controllers.
This is the second in a stack of PRs. Please **do not** merge.
@gregturn PTAL
tag: spinnaker/spinnaker#1164
> CF descriptions common interface

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AbstractAmazonCredentialsDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/AbstractCloudFoundryDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/CloudFoundryDeployDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/DeleteCloudFoundryLoadBalancerDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/DestroyCloudFoundryServerGroupDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/EnableDisableCloudFoundryServerGroupDescription.groovy
- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/UpsertCloudFoundryLoadBalancerDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/KubernetesAtomicOperationDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/AbstractTitusCredentialsDescription.groovy
A first step in making all descriptions easier to manipulate (and strongly typed) within common controllers.
This is the first in a stack of PRs. Please **do not** merge.
@ajordens @cfieber
tag: https://github.com/spinnaker/spinnaker/issues/1164
> AWS descriptions common interface

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
Needed to add `urlMapName` to L7 LB view for frontend to receive it through Gate. @danielpeach please review.
> provider/google: Added urlMapName to L7 LB view.

- clouddriver-openstack/clouddriver-openstack.gradle
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/config/OpenstackConfigurationProperties.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/discovery/DisableInstancesInDiscoveryConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/discovery/EnableInstancesInDiscoveryConverter.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/discovery/AbstractEnableDisableInstancesInDiscoveryOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/discovery/DisableInstancesInDiscoveryOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/discovery/EnableInstancesInDiscoveryOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/discovery/AbstractEnableDisableInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/discovery/DisableInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/discovery/EnableInstancesInDiscoveryDescriptionValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentialsInitializer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackIdentityV3ProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/discovery/AbstractEnableDisableInstancesInDiscoveryAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/AbstractRegistrationOpenstackInstancesAtomicOperationUnitSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/AbstractOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableDisableOpenstackAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/discovery/AbstractEnableDisableInstancesInDiscoveryDescriptionValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentialsSpec.groovy
closes https://github.com/spinnaker/spinnaker/issues/1151
> provider/openstack - enable/disable instances in consul

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ProjectSearchProvider.groovy
- Added a temp try catch to handle the search to return Set<Map>
> Adapt cloud driver to handle front50 new project API

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
can't process allowMultipleEurekaPerAccount
> Titus - fix server groups and instances not showing because they 

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/InstanceController.groovy
> Turns out instance names don't always contain the application name

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
Also a few formatting fixes @duftler
> (kubernetes) fix bug squashing duplicate lb entries

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperation.groovy
If we have a shared health check between two LBs and attempt to delete one of the LBs, the operation will fail because the health check will still be "in use" by the other, but the rest of the LB will be successfully deleted. This PR warns that the hc can't be deleted, but allows the overall operation of deleting the LB to succeed. @duftler please review.
> provider/google: Prevent failure if LB health check is shared.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
@duftler @jtk54 
This is needed for grouping forwarding rules in Deck in the server group wizard.
> provider/google add urlMapName to load balancer summary

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
This is opposed to failing the L7 delete operation. Instead, the L7 being deleted is successfully deleted except for the backend service still in use by another component. @duftler @danielpeach please review.
> provider/google: Warn if a backend service is in use on L7 delete.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgent.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgentSpec.groovy
Adds a delay before reconciling an instance to allow the autoscaler to apply any groups from the launch configuration before we attempt to add any from our conventions.
> don't reconcile classic link until autoscaler has done so first.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/AbstractServergroupOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/ResizeOpenstackAtomicOperationValidator.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DeployOpenstackAtomicOperationValidatorSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/ResizeOpenstackAtomicOperationValidatorSpec.groovy
> allow server groups with zero instances in openstack

- clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/config/ConsulConfig.groovy
> (consul) There is no dependency on datacenters for consul startup

- build.gradle
- clouddriver-security/clouddriver-security.gradle
@duftler @jtk54 @cfieber @ajordens PTAL
> Clouddriver: Bumps spinnaker-dependencies version

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationControllerSpec.groovy
To be used in Fiat in order to get the _complete_ list of applications.
@jtk54 @duftler @ajordens @cfieber PTAL
/cc @gbougeard
> Adds unrestricted option to getAllApplications endpoint.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgent.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackLoadBalancerProvider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackLoadBalancerControllerSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgentSpec.groovy
closes https://github.com/spinnaker/spinnaker/issues/1205
closes https://github.com/spinnaker/spinnaker/issues/1189
> provider/openstack - Fix edit load balancer issues.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleInternalLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancedBackend.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancerView.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancingScheme.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy
@duftler please review. Provides the caching agent for ILBs, as well as a bit of refactoring for new types of health checks, load balancers, and load balancing policies.
> provider/google: Internal load balancer caching agent.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/BlockingStatusChecker.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationProvider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationV1Provider.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/instance/OpenstackInstancesDescription.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/LoadBalancerStatusAware.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/StackPoolMemberAware.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/TerminateOpenstackInstancesAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/AbstractOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractStackUpdateOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/ServerGroupConstants.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackInstance.groovy
- clouddriver-openstack/src/main/java/org/openstack4j/api/Builders.java
- clouddriver-openstack/src/main/java/org/openstack4j/api/heat/ResourcesService.java
- clouddriver-openstack/src/main/java/org/openstack4j/core/transport/ClientConstants.java
- clouddriver-openstack/src/main/java/org/openstack4j/model/heat/ResourceHealth.java
- clouddriver-openstack/src/main/java/org/openstack4j/model/heat/builder/OrchestrationBuilders.java
- clouddriver-openstack/src/main/java/org/openstack4j/model/heat/builder/ResourceHealthBuilder.java
- clouddriver-openstack/src/main/java/org/openstack4j/openstack/heat/builder/HeatBuilders.java
- clouddriver-openstack/src/main/java/org/openstack4j/openstack/heat/domain/HeatResourceHealth.java
- clouddriver-openstack/src/main/java/org/openstack4j/openstack/heat/internal/ResourcesServiceImpl.java
- clouddriver-openstack/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java
- clouddriver-openstack/src/main/resources/asg.yaml
- clouddriver-openstack/src/main/resources/asg_resource.yaml
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/TerminateOpenstackInstancesAtomicOperationUnitSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/AbstractOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractStackUpdateOpenstackAtomicOperationSpec.groovy
> (openstack) auto-heal server groups when an instance is terminated

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
Also adds ILB backend services to LB detail. ILBs are now included in server group -> load balancer disabled state calculations and vice versa. Note that for the load balancer view, the disabled state assumes that a server group shouldn't be associated with both `INTERNAL` and `EXTERNAL` load balancers at once -- this is a simplifying assumption and can change if a customer has a use case for this. @lwander @danielpeach please review.
> provider/google: Includes ILBs in disabled state calculations.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
- Exponential backoff around modifyImageAttribute
> Retry logic in ALLOW LAUNCH

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ProjectSearchProvider.groovy
- removed the try and catch to handle the new project API.
> Remove fallback for Project API

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
updates aws sdk
updates spectator
> latest spinnaker-dependencies/kork version

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackIdentityV3Provider.groovy
Was only skipping SSL verification on authentication. Now doing so on
all calls.
> (Openstack) Honor the insecure flag for all connections.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
@duftler PTAL
For https://github.com/spinnaker/spinnaker/issues/1215
> (kubernetes) support config maps as volume sources

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/ServerGroupParameters.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/ServerGroupConstants.groovy
- clouddriver-openstack/src/main/resources/servergroup_float.yaml
- clouddriver-openstack/src/main/resources/servergroup_resource_float.yaml
- clouddriver-openstack/src/main/resources/servergroup_server_float.yaml
Also fixes the naming for the member resource template.
@spinnaker/reviewers
> (openstack) allow floating ip allocation in auto scaling groups

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
To address the serverside of https://github.com/spinnaker/spinnaker/issues/1216
> (kubernetes) lifecycle hooks

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLaunchConfig.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
> (openstack) adding floating ip info to cache agent / provider

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
Closes https://github.com/spinnaker/spinnaker/issues/1236
@duftler PTAL
> (kubernetes) delete autoscaler if necessary during destroy

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy
> turns out infinite loops aren't the best

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/KubernetesLoadBalancerDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
@duftler PTAL
https://github.com/spinnaker/spinnaker/issues/1106
> (kubernetes) allow po, svc, & rs annotations to be set

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/SafeRetry.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleLoadBalancerDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleLoadBalancerDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
@duftler @danielpeach please review.
> provider/google: Implemented ILB upsert.

- build.gradle
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSubnetCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsInfrastructureProviderConfig.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonVpcProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgentSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSubnetCachingAgentSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProviderSpec.groovy
- clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/CloudFoundryOperationsSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
NOTE: Due to API changes in Tomcat 8.5 and Kork, Tomcat is pinned to 8.0
> Upgrade to Spring Boot 1.4.1.RELEASE

- build.gradle
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSubnetCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsInfrastructureProviderConfig.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonVpcProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgentSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSubnetCachingAgentSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProviderSpec.groovy
- clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/CloudFoundryOperationsSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
Reverts spinnaker/clouddriver#1112
> Revert "Upgrade to Spring Boot 1.4.1.RELEASE"

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancerType.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleSslLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
Also makes some compatibility changes in other LB caching agents. @duftler @danielpeach please review.
> provider/google: Implemented SSL LB caching agent.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
> provider/google: Prevent NPE in backend service caching agent.

- clouddriver-web/clouddriver-web.gradle
> Added stackdriver

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
Cleans up the cases of this calculation as well. @duftler @danielpeach please review.
> provider/google: Added SSL LB disabled state calculations.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperation.groovy
The LB protocol was being passed to the forwarding rule, but not the backend service, which caused an issue with UDP since the default is TCP. The rest of the LBs use TCP backend services, so nothing should change there. ILB is distinct in that it supports both UDP and TCP, so we need to propagate the protocol to the backend service. @duftler @danielpeach please review.
> provider/google: Fix ILB protocol in Upsert.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
Also added ability to return associations to SSL LBs in `GoogleClusterProvider`. @duftler please review.
> provider/google: Implemented SSL LB deploy and clone.

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
Also cleaned out some unused imports 
@duftler PTAL
> Errorconfig handles XSS vulnerabilites by removing requested paths

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleLoadBalancerDescriptionValidator.groovy
@duftler @danielpeach please review. Before this PR, these values were hardcoded. Now I make them required and allow users to specify/modify them in the forwarding rules.
> provider/google: Support custom networks/subnets in ILB upsert.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
The translation of the cache entries to server group objects went from ~11 seconds to ~.5 seconds for a single application with around 60 server groups.
This was done by batching up the request to load all instances associated with every server group in a given cluster, rather than make one call to the cache per server group.
@duftler  PTAL
> (kubernetes) ~20x faster application load

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/AzureConfigurationProperties.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/model/KeyVaultSecret.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentialsInitializer.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureNamedAccountCredentials.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/Resource.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/validators/UpsertAzureLoadBalancerDescriptionValidatorSpec.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/ops/DestroyAzureServerGroupAtomicOperationSpec.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
Access user name and password for VMs from KeyVault when deploying Azure Scale Set
> Add KeyVault support to Scale Set deployment

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
@duftler @danielpeach please review.
> provider/google: Support enable/disable/destroy for SSL LBs.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
> (kubernetes) these are needed for upsert lb

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
@spinnaker/netflix-reviewers @duftler PTAL
> Fix typo in variable name

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy
@duftler @danielpeach please review.
> provider/google: Implemented SSL LB delete.

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
https://github.com/spinnaker/spinnaker/issues/1265
> (docker) warn against trailing & leading whitespace in password

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/agent/CleanupPendingOnDemandCachesAgent.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/EntityRefIdBuilder.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/DeleteEntityTagsAtomicOperationConverter.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/DeleteEntityTagsDescription.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/EntityRefIdBuilderSpec.groovy
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AccountCredentials.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerSpec.groovy
- generated EntityTags.id should be lowercase
- generated EntityTags.id should favor using `accountId` where available (rather than accountName)
- support for deleting entity tags
- support index verification w/ nested tags (ie. tags that are maps of maps)
> Few tagging-related fixes/improvements

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsSupport.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy
> Improved CredentialsNotFoundException messaging

- clouddriver-appengine/clouddriver-appengine.gradle
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/AppEngineCloudProvider.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/AppEngineConfiguration.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/AppEngineOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppEngineConfigurationProperties.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/health/AppEngineHealthIndicator.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppEngineCredentials.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppEngineCredentialsInitializer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppEngineJsonCredentials.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppEngineNamedAccountCredentials.groovy
- clouddriver-google-common/clouddriver-google-common.gradle
- clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/config/GoogleCommonManagedAccount.groovy
- clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/security/GoogleCommonCredentialUtils.groovy
- clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/security/GoogleCommonCredentials.groovy
- clouddriver-google/clouddriver-google.gradle
- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/config/clouddriver.yml
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
- settings.gradle
@duftler @lwander please review
> provider/gae introduce Google App Engine as a cloud provider

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
@duftler 
Completes the work started in #1208
> (kubernetes) fix lb & sg caching behavior for dynamic namespace

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/Resource.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
Add additional logging during deployment. Only add custom data to template when provided.
> updated deployment logging

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
> provider/kubernetes: Set number of default cache threads.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
> provider/google: Fix enum conversion breaking template metadata.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleLoadBalancerDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/Constants.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleLoadBalancerDescriptionValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy
@duftler @danielpeach please review. Also moved some generic health check code into `GCEUtil`.
> provider/google: Implemented SSL L4 upsert.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
@jtk54 Thanks for catching this
> (kubernetes) fix typo in ingress loading

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
Adds a retry for creating application specific security groups
> titus - retry on default application security group creation

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
@duftler PTAL
this change is helping us investigate an issue with deployments. If everything looks good, could we get a new build dropped?
> improve deployment error details logging

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppEngineMutexRepository.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppEngineServerGroupNameResolver.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppEngineUtils.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/AppEngineAtomicOperationConverterHelper.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppEngineAtomicOperationConverter.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/AbstractAppEngineCredentialsDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppEngineDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppEngineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppEngineDescriptionValidator.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppEngineAttributeValidator.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppEngineCredentialsInitializer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppEngineNamedAccountCredentials.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppEngineAtomicOperationConverterSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppEngineDescriptionValidatorSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppEngineAttributeValidatorSpec.groovy
@duftler @lwander please review.
> (appengine) deploy operation

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/UpsertAzureSecurityGroupAtomicOperation.groovy
These updates should have been part of a previous PR.
@spinnaker/netflix-reviewers @duftler PTAL
> missed method signature update from a previous PR

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/controllers/KubernetesLoadBalancerController.groovy
@lwander PTAL
tag: https://github.com/spinnaker/fiat/issues/99
> Kubernetes temp shim impl

- clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/controllers/CloudFoundryLoadBalancerController.groovy
- clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/controllers/CloudFoundryLoadBalancerControllerSpec.groovy
> CF LoadBalancerController shim

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackLoadBalancerController.groovy
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackLoadBalancerControllerSpec.groovy
@varikin PTAL
tag: https://github.com/spinnaker/fiat/issues/99
> Openstack load balancer controller temp shim impl

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
@duftler PTAL
I bumped the API version & picked up some indentation fixes as well.
> (kubernetes) container securityContext

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/view/AzureAppGatewayController.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerController.groovy
> Convert to use LoadBalancer shim interface

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
> (kubernetes) terminate security context builder

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgent.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgentSpec.groovy
Also explicitly reads public images directly from AWS so we can stop caching them in Edda
@duftler PTAL
> use the is-public tag for filtering instead of executable users.

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
fixes bug where calls to titus show as already executed on retry
> titus - fix retry errors

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/cache/Keys.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineApplication.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineCluster.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineInstance.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineLoadBalancer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineModelUtil.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineServerGroup.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/AppEngineProvider.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AbstractAppEngineCachingAgent.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppEngineServerGroupCachingAgent.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/callbacks/AppEngineCallback.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/config/AppEngineProviderConfig.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppEngineApplicationProvider.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppEngineClusterProvider.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppEngineInstanceProvider.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppEngineProviderUtils.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/MutableCacheData.groovy
@duftler @lwander please review
> (appengine) cache applications, clusters, server groups, and instances.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
A case was noticed where a @dennismartensson where a delete never completed - my guess is there was a 1-off bad interaction between the existing autoscaler and the deleted server group.
@duftler PTAL
> (kubernetes) delete autoscaler before RS

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleConfiguration.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/SafeRetry.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GoogleOperationPollerSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy
@duftler please review. We previously used a static interval. Now we back off based on the number of tries.
> provider/google: Make SafeRetry exponentially back off retries.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
> provider/google: Fix the Ssl LB caching agent name.

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineLoadBalancer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppEngineServerGroupCachingAgent.groovy
> (appengine) include region on load balancer model

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
> (kubernetes) Pod container conditions may be empty

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
> (docker) paginate tag list

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperationSpec.groovy
- Added a guard against updating a load balancer containing no security groups
(AWS requires at least one security group per load balancer)
> Don't update a load balancer if it doesn't have at least one security group

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandler.groovy
- Added a check to make sure we have security groups before applying them to the load balancer
> Ensure there are security groups before a load balancer update

- clouddriver-web/config/clouddriver.yml
PTAL: @duftler @lwander @ajordens @cfieber @scotmoor
> Adding Azure regions to clouddriver

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy
@duftler PTAL - this only addresses deploy, delete & rollback haven't been completed yet.
> (kubernetes) support deployment API

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
> (kubernetes) delete deployment

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesDeploymentStatus.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesDeploymentCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
> (kubernetes) cache deployments

- clouddriver-web/config/clouddriver.yml
@spinnaker/netflix-reviewers @duftler PTAL
> add key vault and default resource group to config

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
This is a nearly O(N) speedup in enable/disable.
@duftler PTAL
> (kubernetes) parallelize enable/disable

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppEngineLoadBalancerCachingAgent.groovy
> provider/appengine s/Integer/int in load balancer caching agent

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineInstance.groovy
@lwander or @duftler please review
> provider/appengine include instance details from API

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
This includes a change in the label semantics, behavior of IntOrString, as well as the annotations keymap.
@duftler PTAL, @gardleopard FYI
> (kubernetes) fix issues discovered upgrading to 1.4.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/UpsertEntityTagsAtomicOperationConverter.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/UpsertEntityTagsDescription.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/converters/UpsertEntityTagsAtomicOperationConverterSpec.groovy
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperationSpec.groovy
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperationSpec.groovy
- Tags are now stored as List<Map> rather than Map
> Revised entity tags model

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
Reverts spinnaker/clouddriver#1288
> Revert "Ensuring that there are at most 5 security groups per instance (The max is configurable)"

- halconfig/clouddriver.yml
> Base clouddriver halconfig

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusRestAdapter.java
> Titus: use api/v2 endpoints

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
- This label will be used for discovery purposes
> (titus)  Setting interestingHealthProvider (if present) as a titus job label

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
- Changed the type of interestingHealthProviderNames from String to a List
> Fixes interestingHealthProviderNames regression

- clouddriver-security/clouddriver-security.gradle
@jtk54 PTAL
@cfieber @ajordens FYI
> Fiat bump to add LDAP role source.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/GoogleAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ResizeGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraitsSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ResizeGoogleServerGroupAtomicOperationUnitSpec.groovy
Instruments one operation as example of how it will be used.
@duftler 
This is independent of earlier PR, which I'm looking at now.
> Added traits to facilitate instrumentation of Google APIs

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DisableAppEngineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppEngineAttributeValidator.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineModelUtil.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppEngineAttributeValidatorSpec.groovy
@lwander or @jtk54 or @duftler please review.
> (appengine) better validation for traffic allocations

- halconfig/clouddriver.yml
@duftler or @jtk54 or @danielpeach PTAL
> (halconfig) update redis reference to use baseUrl

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppEngineLoadBalancer.groovy
@duftler or @lwander or @jtk54 please review.
I need this flag for UI validation of an upsert load balancer operation. It's a little ugly to tack on here, but the other option seems to be a rest call for each of a load balancer's server groups.
> (appengine) adds boolean to load balancer server group model

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/health/GoogleHealthIndicator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHealthCheckCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpHealthCheckCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslCertificateCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgentSpec.groovy
> Instrument google agents.

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/gitClient/AppengineGitCredentials.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineCredentialsInitializer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineNamedAccountCredentials.groovy
@lwander please review. This should now match the config that halyard writes.
> (appengine) s/sshPrivateKeyPassword/sshPrivateKeyPassphrase

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/KubernetesVolumeSourceValidator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
> (k8s) add validator for configMap volume source type

- Dockerfile.slim
- cloudbuild.yaml
> Google Cloud Builder optimizations

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
> Display target & address for failed docker auth attempts

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy
The original implementation was ignoring messages that were wrapped in SNS messages. I've added support to unwrap SNS (but also take direct SQS messages, in case someone doesn't want to use SNS fanout). Additionally added some more logging so it's more apparent what's going on internally to this agent.
> Updating termination lifecycle agent to unwrap sns messages

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
> (google) Fix typo.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
We need to ensure that unwanted (or unknown) messages are removed from the queue so they don't get reprocessed.
@spinnaker/netflix-reviewers ptal
> Delete ignored messages (like test notifications, etc)

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
@duftler 
I havent actually tested this yet.
> Fixed deleting regional GCE MIGs

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskRepository.groovy
previousRedis shouldn't be expected to be around permanently, but once the instance is terminated then a call to get a task will always try to hit it
when we are looking up by clientRequestId we would always end up triggering a lookup to the previous when there was a new client request id created
essentially taking the previousRedis offline would make any attempt to start a new Task blow up
> fixes an error on task lookup when previousRedis goes away

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroupSpec.groovy
> (k8s) SG is enabled when no LBs are attached

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperation.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployHandler.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/events/CreateServerGroupEvent.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/events/CreateServerGroupEventHandler.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/events/CreateServerGroupEventHandlerSpec.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
- Added a createServerGroupEventHandler to handle create server group events
- Deletes tags from servergroup name on deploy
> (aws & titus) Deleting tags from server group upon creation

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProvider.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LifecycleMessage.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LifecycleSubscriberConfiguration.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/NotificationMessageWrapper.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProviderSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy
Discovery is receiving the termination events, but I'd like to know how long it's actually taking for all of this to happen so we can continue the termination process as soon as possible without losing the benefits.
> Adding metrics for termination lifecycle lag

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
https://github.com/spinnaker/spinnaker/issues/1436
> (kubernetes) add node-selector

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
> Copies K8S load balancer lables over upon update

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidator.groovy
Adds the ability to include the contents of a config yaml file in the upsert description.
> (appengine) allow config files to be specified in deploy operation

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DestroyAppengineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DisableAppengineAtomicOperation.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DestroyAppengineAtomicOperationSpec.groovy
Adds safe retry to destroy operation.
> (appengine) destroy safe retry

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/AppengineAtomicOperationConverterHelper.groovy
@skim1420 or @lwander please review.
> (appengine) set account on operation descriptions

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchServerGroupTagger.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java
- reindex() will now do a `bulkIndex`
> Improved reindex behavior and support for filtering tags by namespace

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/UpsertAppengineLoadBalancerAtomicOperationConverter.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/UpsertAppengineLoadBalancerDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineLoadBalancer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineModelUtil.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/UpsertAppengineLoadBalancerAtomicOperationConverterSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/model/AppengineModelUtilSpec.groovy
> (appengine) change model for upsert load balancer description

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppengineLoadBalancerProvider.groovy
@lwander or @jtk54 please review.
> (appengine) remove thrown errors in load balancer provider

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusClientProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusConfiguration.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusJobCustomizer.java
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClientSpec.groovy
Extension point for customizing titus jobs
Note that this is based off of #1385 so only the 2nd commit is specific to the titus change
> Titus job customizer

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy
> (bugfix) change openstack credentials builder return type

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DetachInstancesAtomicOperation.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DetachTitusInstancesAtomicOperation.groovy
prevent detachInstances call from sending over negative mins when adjustMinIfNecessary is set
> bug(titus,aws): don't send negative mins on detach

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy
Sets direct SQS lifecycle event messages to only allow from the
configured lifecycle hook source ARNs, which is more correct
behavior than accepting anything from autoscaling.
Also added more info into the discovery log message in case we need to search lag for a specific server group, etc.
> fix(aws): Tightening direct SQS IAM perms in termination events

- build.gradle
- cats/cats-redis/cats-redis.gradle
- clouddriver-openstack/clouddriver-openstack.gradle
updates kork/jackson/spectator
> chore(dependencies) : update to latest spinnaker-dependencies

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsSpec.groovy
Closes https://github.com/spinnaker/spinnaker/issues/1320
> feat(kubernetes): Omit desired namespaces

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationCleanupAgent.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationCleanupAgentSpec.groovy
If a tag is entered for an account, and subsequently that account is removed or the name changes, the agent crashes trying to get credentials.
Now logs a warning and carries on instead.
> fix(aws) LaunchFailureNotifactionCleanupAgent skips tags for unknown accounts.

- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy
The new termination lifecycle worker is performing better, but there's odd behavior in our interactions with discovery, which leads to me to believe we may be getting throttled. These changes just add some more logging to help track down specifically what's going on so we have a better idea of what to tackle next.
> chore(eureka): enhancing logging on eureka service failures

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy
> Instrument kube

- Dockerfile
- Dockerfile.slim
Supercedes https://github.com/spinnaker/clouddriver/pull/1447
@danielpeach PTAL
> Danielpeach add gcloud to dockerfile

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReport.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
> support region-scoped amazon instance reservations

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy
> fix(groovy): Groovyc making the static property private to child classes

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy
> fix(google): Made instrumentation a little more consistent

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
Prevents the case where an incorrectly configured lifecycle blocks the progress of a deploy operation.
@cfieber PTAL
> fix(aws): Allow deploys to continue if lifecycles fail to create

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/DeleteGoogleAutoscalingPolicyDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
@duftler or @jtk54 or @lwander please review.
Manually tested for both regional and zonal MIGs.
> feat(gce) adds support for delete autohealing policy operation

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BasicGoogleDeployDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleAutoscalingPolicyDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleAutoscalingPolicyDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoHealingPolicy.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleAutoscalingPolicyDescriptionValidatorSpec.groovy
@jtk54 or @duftler or @lwander please review.
I've tested this manually:
- For both zonal and regional MIGs
- For upsert descriptions that include only some of the autohealing policy's properties.
- For upsert descriptions that also specify an autoscaling policy.
> feat(gce) adds support for upsert autoHealingPolicy operation

- halconfig/clouddriver-bootstrap.yml
> chore(halyard): Add boostrapping profile to clouddriver

- cloudbuild.yaml
@lwander FYI
Thanks @ImJasonH!
> fix(container): Extends timeout to 15m in cloudbuild.yaml file

- Dockerfile.slim
> fix(container): typo in apk command in slim container

- build.gradle
chore(dependencies): Update to spinnaker-dependencies 0.86.0
@ttomsu
> Update spinnaker-dependencies to 0.86.0

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/admin/EntityTagsAdminController.java
Reports on any differences between Front50 and Elasticsearch.
> feat(elasticsearch): EntityTags metadata endpoint

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProvider.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProviderSpec.groovy
One subnet with broken json in immutable_metadata tag can make the entire `subnets/aws` call to clouddriver fail with a 500 error.
This PR mitigates this by swallowing the exception and logging the message in the ERROR log.
```
curl http://clouddriver.url/subnets/aws
{
"error" : "Internal Server Error",
"exception" : "com.fasterxml.jackson.core.JsonParseException",
"message" : "Unexpected character ('=' (code 61)): was expecting a colon to separate field name and value\n at [Source: {\"purpose\": \"internal-foobar\",\"target\"=\"ec2\"}; line: 1, column: 48]",
"status" : 500,
"timestamp" : 1488549571234
}
```
> Swallow and log parsing exceptions on immutable_metadata in AWS

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
> feat(gce): surface instance type disk defaults on credentials

- clouddriver-security/clouddriver-security.gradle
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/config/SecurityConfig.groovy
@cfieber please take for a spin
> chore(fiat): Bump Fiat API, add @EnableFiatAutoConfig annotation

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
It turns out some docker registries (e.g. artifactory) will respond to a load tags call with an image name that doesn't fully qualify that docker image. To compensate for this we augment the load tags call with the real repository name.
> fix(docker): Prefer repository name over image name when loading tags

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
> fix(kubernetes): don't set postStart hook as preStop hook

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
> fix(provider/google): Removed static function keyword in L7 upsert.

- clouddriver-security/clouddriver-security.gradle
> chore(fiat): Bump Fiat API to start using UserPermission cache

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/cache/Keys.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppenginePlatformApplication.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppenginePlatformApplicationCachingAgent.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/config/AppengineProviderConfig.groovy
@duftler or @lwander please review.
> feat(appengine) adds platform application caching agent

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
> Fix for reservation report metrics w/o availabilityZone

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/cache/Keys.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSNetwork.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/OracleBMCSInfrastructureProvider.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/AbstractOracleBMCSCachingAgent.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSNetworkCachingAgent.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/config/OracleBMCSInfrastructureProviderConfig.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSNetworkProvider.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSNetworkCachingAgentSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSNetworkProviderSpec.groovy
This is a PR for our first caching agent and provider pair for Networks with supporting classes and tests.
> feat(provider/oraclebmcs): Network caching agent and provider

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/cache/Keys.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSSubnet.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/OracleBMCSInfrastructureProvider.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSSubnetCachingAgent.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/config/OracleBMCSInfrastructureProviderConfig.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSSubnetProvider.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSSubnetCachingAgentSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSSubnetProviderSpec.groovy
Subnet caching agent and provider pair with tests. Hoping the style is more on point this time :)
> feat(provider/oraclebmcs): Subnet caching agent and provider

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineLoadBalancer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineModelUtil.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppenginePlatformApplication.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppengineLoadBalancerProvider.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppenginePlatformApplicationProvider.groovy
@lwander or @jtk54 or @duftler please review.
> feat(appengine): surface dispatch rules on App Engine load balancers

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/cache/Keys.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/controller/OracleBMCSImageLookupController.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSImage.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/OracleBMCSInfrastructureProvider.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSImageCachingAgent.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/config/OracleBMCSInfrastructureProviderConfig.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSImageProvider.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/controller/OracleBMCSImageLookupControllerSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSImageCachingAgentSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSImageProviderSpec.groovy
Image caching agent, provider pair and controller with tests.
> feat(provider/oraclebmcs): Image caching agent, provider and controller with tests

- clouddriver-oracle-bmcs/clouddriver-oracle-bmcs.gradle
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/cache/Keys.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/controller/OracleBMCSImageLookupController.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSSecurityGroup.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSSecurityGroupSummary.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSSecurityGroupCachingAgent.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/config/OracleBMCSInfrastructureProviderConfig.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSSecurityGroupProvider.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/controller/OracleBMCSImageLookupControllerSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSSecurityGroupCachingAgentSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSSecurityGroupProviderSpec.groovy
Add security group cache agent, provider and tests.
This also contains a few whitespace/style fixes as mentioned in the previous Images PR (#1552).
A small tweak to the gradle build to set license headers on test source sets too.
> feat(provider/oraclebmcs): Add security group cache agent, provider and tests

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/cache/Keys.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSInstance.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSInstanceCachingAgent.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/config/OracleBMCSInfrastructureProviderConfig.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSInstanceProvider.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSInstanceCachingAgentSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSInstanceProviderSpec.groovy
Oracle BMCS Instance cache agent, provider and tests.
> feat(provider/oraclebmcs): Instance cache agent, provider and tests

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/converters/DeleteAzureAppGatewayAtomicOperationConverter.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/converters/UpsertAzureAppGatewayAtomicOperationConverter.groovy
After PR https://github.com/spinnaker/deck/pull/3439, the region is no longer being passed as an array
> refactor(provider/azure): Clean AppGateway descriptions

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy
Working on some changes to how we load server groups for very large (> 500 or so clusters) applications. This change adds an optional parameter to the `/serverGroups` endpoint for an application, allowing the user to specify a specific list of clusters to retrieve - while still returning the structure the UI expects.
Clusters are encoded as `account:clusterName`.
@cfieber or @ajordens what are your feelings on this, be honest
> feat(servergroups): allow filtering by clusters on /serverGroups

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupController.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupControllerSpec.groovy
It's been pointed out that we don't let folks search for images whose names start with "ami", e.g. "ami_base". This just expands the search restriction to match on the hyphen.
> fix(amazon): allow image lookup of AMIs prefixed with "ami"

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/UpsertAppengineAutoscalingPolicyAtomicOperationConverter.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/UpsertAppengineAutoscalingPolicyDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/UpsertAppengineAutoscalingPolicyAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppengineAttributeValidator.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/UpsertAppengineAutoscalingPolicyDescriptionValidator.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineServerGroup.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/UpsertAppengineAutoscalingPolicyAtomicOperationConverterSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/StartStopAppengineAtomicOperationSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/UpsertAppengineAutoscalingPolicyAtomicOperationSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StartAppengineDescriptionValidatorSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/UpsertAppengineAutoscalingPolicyDescriptionValidatorSpec.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/UpsertAppengineLoadBalancerDescriptionValidatorSpec.groovy
@lwander or @duftler or @jtk54 please review.
> feat(appengine): upsert autoscaling policy

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSInstanceProvider.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSInstanceProviderSpec.groovy
Fix handling when requested instance doesn't exist anymore. Groovy's .first() doesn't like empty collections, so i've added a check. Also added test case.
> fix(provider/oraclebmcs): Handle missing instances

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
Adds clouddriver support for https://github.com/spinnaker/spinnaker/issues/1107
@spinnaker/reviewers
> feat(provider/kubernetes): Specify termination grace period seconds

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy
instance code needs to be sanitized before use:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/InstanceState.html#getCode--
We have a perfectly healthy instance with code 272 in running state.
272 & 0xF0 == 16
Instead of using codes, use the state names for health check evaluation.
> fix(provider/aws) invalid use of health instance code

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/KubernetesLoadBalancerDescription.groovy
> fix(kubernetes): allow upsert load balancer as a pipeline stage

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/OracleBMCSServerGroupNameResolver.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/BasicOracleBMCSDeployAtomicOperationConverter.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/OracleBMCSAtomicOperationConverterHelper.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/AbstractOracleBMCSCredentialsDescription.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/BaseOracleBMCSInstanceDescription.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/BasicOracleBMCSDeployDescription.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/handler/BasicOracleBMCSDeployHandler.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/BasicOracleBMCSDeployAtomicOperationConverterUnitSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/handler/BasicOracleBMCSDeployHandlerSpec.groovy
A basic Oracle BMCS deploy handler and supporting classes.
> feat(provider/oraclebmcs): Add Oracle BMCS Deploy Handler

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/OracleBMCSAtomicOperationConverterHelper.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/ResizeOracleBMCSServerGroupAtomicOperationConverter.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/ResizeOracleBMCSServerGroupDescription.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/ResizeOracleBMCSServerGroupAtomicOperation.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/ResizeOracleBMCSServerGroupDescriptionValidator.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/StandardOracleBMCSAttributeValidator.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/service/servergroup/OracleBMCSPersistenceContext.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/service/servergroup/OracleBMCSServerGroupService.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/ResizeOracleBMCSServerGroupAtomicOperationConverterUnitSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/ResizeOracleBMCSServerGroupAtomicOperationSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/ResizeOracleBMCSServerGroupDescriptionValidatorSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/StandardOracleBMCSAttributeValidatorSpec.groovy
Resize server group operation and removal of author class comments from previous PR comments.
> feat(provider/oraclebmcs): Resize server group operation

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/DestroyOracleBMCSServerGroupAtomicOperationConverter.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/DestroyOracleBMCSServerGroupDescription.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/DestroyOracleBMCSServerGroupAtomicOperation.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/DestroyOracleBMCSServerGroupDescriptionValidator.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/DestroyOracleBMCSServerGroupAtomicOperationConverterUnitSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/DestroyOracleBMCSServerGroupAtomicOperationSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/DestroyOracleBMCSServerGroupDescriptionValidatorSpec.groovy
Destroy server group operation. Also a couple whitespace fixes from comments on last PR.
> feat(provider/oraclebmcs): Destroy server group operation

- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/DisableOracleBMCSServerGroupAtomicOperationConverter.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/EnableOracleBMCSServerGroupAtomicOperationConverter.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/EnableDisableOracleBMCSServerGroupDescription.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/DisableOracleBMCSServerGroupAtomicOperation.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/EnableOracleBMCSServerGroupAtomicOperation.groovy
- clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/EnableDisableOracleBMCSServerGroupDescriptionValidator.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/DisableOracleBMCSServerGroupAtomicOperationConverterUnitSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/EnableOracleBMCSServerGroupAtomicOperationConverterUnitSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/DisableOracleBMCSServerGroupAtomicOperationSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/EnableOracleBMCSServerGroupAtomicOperationSpec.groovy
- clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/validator/EnableDisableOracleBMCSServerGroupDescriptionValidatorSpec.groovy
Last major feature addition for Oracle BMCS provider: Enable/Disable server group operation.
> feat(provider/oraclebmcs): Enable/Disable server group operations

- build.gradle
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
includes frigga update supporting ~ in detail component of names
> chore(dependencies): update to latest spinnaker-dependencies.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
Adding null check for autoscaling type to fix NPE while caching.
> fix(provider/openstack): Add nullcheck for caching autoscalling type 

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
@lwander please review.
@ethanfrogers FYI
> fix(kubernetes): handle images without registry

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeregisterInstancesFromLoadBalancerAtomicOperationConverter.java
> fix(aws): Fix deregistering instances from load balancers

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackImageLookupController.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackImageLookupControllerSpec.groovy
Fixes images not loading when one of them has no name.
> fix(provider/openstack) adds name nullcheck to filtering images

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BasicGoogleDeployDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/GoogleUserDataProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/GoogleUserDataProviderSpec.groovy
Adding user data functionality to clouddriver-google. Custom user data provided per app will be appended to common user data.
>  feat(udf): Added user data file to use with every deploy

- clouddriver-security/clouddriver-security.gradle
> chore(fiat): Bump fiat version, fixes deserialization issue

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerDescription.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperation.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/1692
> fix(provider/amazon): Fix isInternal flag on load balancer description

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy
Globs are hard? Not really, but I wish I had an excuse for this one.
> fix(provider/amazon): Fix load balancer loading

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeregisterInstancesFromGoogleLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeregisterInstancesFromGoogleLoadBalancerAtomicOperationUnitSpec.groovy
We don't wait on the instances to be removed from the L4 LB, which might cause cache desync issues if the operation is slow.
> fix(provider/google): Wait for L4 LB instance deregister.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeregisterInstancesFromGoogleLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeregisterInstancesFromGoogleLoadBalancerAtomicOperationUnitSpec.groovy
Cherry pick of https://github.com/spinnaker/clouddriver/pull/1658 into `release-0.6.x`.
> fix(provider/google): Wait for L4 LB instance deregister. (#1658)

- AUTHORS
- clouddriver-dcos/clouddriver-dcos.gradle
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosClientCompositeKey.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosClientProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosCloudProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosConfiguration.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosConfigurationProperties.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosOperation.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/cache/Keys.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/id/DcosSpinnakerAppId.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/id/DcosSpinnakerLbId.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/id/MarathonPathId.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/health/DcosHealthIndicator.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/DcosProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/config/DcosProviderConfig.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/security/DcosAccountCredentials.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/security/DcosClusterCredentials.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/security/DcosCredentialMap.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/security/DcosCredentialsInitializer.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/BaseSpecification.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/id/DcosSpinnakerAppIdSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/id/DcosSpinnakerLbIdSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/id/MarathonPathIdSpec.groovy
- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/config/clouddriver.yml
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
- settings.gradle
> feat(provider/dcos): Add initial scaffolding for DC/OS provider

- clouddriver-loadtest/src/main/resources/clouddriver-simulation.json
- clouddriver-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/ClouddriverSimulation.scala
- clouddriver-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/ClouddriverSimulationConfig.scala
Only support `constantUsersPerSec` and `constantUsersDurationSec` for now
> fix(loadtest): Simplified load configuration

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/edda/EddaApiFactory.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/1723
> fix(provider/amazon): NullPointerException if Edda is not present

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
> fix(provider/kubernetes): Field refs were not loaded

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/LoggingInstrumentation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
* Changing log level to DEBUG for some logging
This is to reduce noise in the clouddriver logs.
> Sanitize logging in clouddriver

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/JobExecutor.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy
> fix(appengine): prevent flaky appengine deploy failures

- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/AbstractDcosCredentialsDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/AbstractDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/DeployDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/AppToDeployDcosServerGroupDescriptionMapper.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosInstance.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosServerGroup.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/DcosProviderUtils.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/MutableCacheData.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosInstanceCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosServerGroupCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/view/DcosInstanceProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/security/DcosAccountCredentials.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosServerGroupSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosInstanceCachingAgentSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosServerGroupCachingAgentSpec.groovy
This pull request adds the instance and server group caching agents for DC/OS along with some related classes and tests.
> feat(provider/dcos): Server group and instance caching agents

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerServerGroup.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/loadbalancer/UpsertDcosLoadBalancerAtomicOperationDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosLoadBalancer.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosLoadBalancerCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosSecretsCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/view/DcosLoadBalancerProvider.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosLoadBalancerSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosLoadBalancerCachingAgentSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosSecretsCachingAgentSpec.groovy
This pull request adds the loadbalancer and secret caching agents for DC/OS along with some related classes and tests.
> feat(provider/dcos): Load balancer and secret caching agents

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerCertificate.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCertificateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonServerCertificateProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/provider/agent/Namespace.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Certificate.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/CertificateProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CertificateController.groovy
Caching agent and provider for server certificates
> feat(provider/amazon): Add cachingagent and provider for server certificates

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- instance not found exception should not fail the entire operation
> fix(amazon): handle instance not found exception in describeinstances

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsSupport.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/DcosServerGroupNameResolver.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/DcosAtomicOperationConverterHelper.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/CloneDcosServerGroupAtomicOperationConverter.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/DeployDcosServerGroupAtomicOperationConverter.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/CloneDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/CloneDcosServerGroupAtomicOperation.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/DeployDcosServerGroupAtomicOperation.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/MarathonVolumeDeserializer.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/DeployDcosServerGroupDescriptionToAppMapper.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/AbstractDcosDescriptionValidatorSupport.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/DeployDcosServerGroupDescriptionValidator.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/exception/DcosOperationException.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosApplication.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosCluster.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosLoadBalancer.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosServerGroup.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosLoadBalancerCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosSecretsCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/view/DcosApplicationProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/view/DcosClusterProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/view/DcosLoadBalancerProvider.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/DeployDcosServerGroupAtomicOperationSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/AppToDeployDcosServerGroupDescriptionMapperSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/DeployDcosServerGroupDescriptionToAppMapperSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/DeployDcosServerGroupDescriptionValidatorSpec.groovy
Adds the deploy and clone server group operations for DC/OS.  Also adds the application and cluster providers that probably should have gone on the caching agent PR.
> feat(provider/dcos): Add deploy and clone server group operations

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
* the REST call for retrieving individual server groups was not adding
the `buildInfo` property to the `ServerGroup` object returned (but it
was still present in the `tags` array).  like the REST call for
retrieving all the server groups for an applications, this PR adds the
build information to the individual server group.
> fix(aws/serverGroup): add build info

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
Added resourceFieldRef Env Var support
Addresses spinnaker/spinnaker#1815
> feat(provider/kubernetes): Support resourceField env vars

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
* Properly convert resourceField, introduced in #1722
Addresses spinnaker/spinnaker#1815
@lwander
> fix(provider/kubernetes): Fix resourceField envVar

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
@tomaslin @anotherchrisberry FYI
> fix(aws): NPE when getting build info on unknown image

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleLoadBalancerAtomicOperationConverter.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleTcpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleTcpLoadBalancerAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleLoadBalancerDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancerType.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleTargetProxyType.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleTcpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DisableGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/EnableGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleTcpLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerTestConstants.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleTcpLoadBalancerAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleLoadBalancerDescriptionValidatorSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy
Mostly copy-paste from SSL Proxy code.
> feat(provider/google): Support TCP Proxy Load Balancing

- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/DestroyDcosServerGroupAtomicOperationConverter.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/DisableDcosServerGroupAtomicOperationConverter.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/ResizeDcosServerGroupAtomicOperationConverter.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/DestroyDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/DisableDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/ResizeDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/DestroyDcosServerGroupAtomicOperation.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/DisableDcosServerGroupAtomicOperation.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/ResizeDcosServerGroupAtomicOperation.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/monitor/DcosDeploymentMonitor.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/monitor/EventBasedDcosDeploymentMonitor.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/monitor/PollingDcosDeploymentMonitor.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/AbstractDcosServerGroupValidator.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/DestroyDcosServerGroupDescriptionValidator.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/DisableDcosServerGroupDescriptionValidator.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/ResizeDcosServerGroupDescriptionValidator.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/DeployDcosServerGroupAtomicOperationConverterSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/DestroyDcosServerGroupAtomicOperationConverterSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/converters/servergroup/ResizeDcosServerGroupAtomicOperationConverterSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/DestroyDcosServerGroupAtomicOperationSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/ResizeDcosServerGroupAtomicOperationSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/DestroyDcosServerGroupDescriptionValidatorSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/DisableDcosServerGroupDescriptionValidatorSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/validators/servergroup/ResizeDcosServerGroupDescriptionValidatorSpec.groovy
Adds the destroy, disable, and resize server group operations for DC/OS.
> feat(provider/dcos): Add destroy, disable, and resize server group

- build.gradle
- clouddriver-aws/clouddriver-aws.gradle
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupController.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupControllerSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidationException.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationException.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsSupport.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/InstanceController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ProjectController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SecurityGroupController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/TaskController.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationControllerSpec.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterControllerSpec.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ProjectControllerSpec.groovy
The generic exception handling from `kork-web` allows us to remove all
custom @ExceptionHandler's and simplify how error api responses are created.
> chore(dependencies): Bump spinnaker-dependencies to 0.103.0

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
Specifying which regions you want indexed reduces the number of calls the caching agents have to make to the API.
> feat(provider/google): Adding functionality for selecting certain regions for indexing.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy
Amazon recently introduced Target Tracking scaling policies; this adds backend support.
Separate PR for UI support in deck is forthcoming.
> feat(provider/amazon): add target tracking scaling policy support

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/UpsertTargetTrackingPolicyDescriptionConverter.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertTargetTrackingPolicyDescription.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertTargetTrackingPolicyAtomicOperation.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertTargetTrackingPolicyResult.java
Allows target tracking policy upserts
> feat(provider/amazon): allow upsert of target tracking policies

- build.gradle
- clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/CloudFoundryOperationsSpec.groovy
- clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/config/CloudFoundryConfigSpec.groovy
- clouddriver-security/clouddriver-security.gradle
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy
Merging into `boot-upgrade` branch
> chore(springBoot): Upgrade to Spring Boot 1.5.4

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/RedisTaskRepository.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/RedisTaskRepositorySpec.groovy
> fix(core): Fix JedisTask NPE during redis flip ops

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
> fix(aws): Assign EBS Optimized flag matching AWS-defined defaults

- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cluster/DynoClusteredAgentScheduler.java
I haven't been seeing some caching agents run, which would explain why we're seeing consistency issues w/ dyno running. Considering how many connection errors we were getting before yesterday, I suspect we've got some deadlocked agents.
> fix(dynomite): Self-heal deadlocked caching agents

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupAlarmsAgent.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupAlarmsAgentSpec.groovy
Spinnaker's AlarmCleanupAgent is a little too aggressive in cleaning up alarms and deletes them even if it did not create them.
This definitely did not cause any problems or result in any yelling recently.
We'll eventually move this code to Janitor Monkey as part of its rewrite (cc @jeyrschabu)
@ajordens we talked about this yesterday, PTAL if you have time.
> fix(amazon): only delete alarms auto-generated by Clouddriver

- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperationSpec.groovy
* add error handling around when the entity ref account name is not
found in the account credentials provider.
> fix(entityTags): gracefully handle missing account

- clouddriver-loadtest/README.md
So I don't need to remember the commands.
> docs(loadtest): Example commands to generate applications feeder

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/EcsCreateServerGroupAtomicOperationConverter.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/BasicEcsDeployDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/handlers/BasicEcsDeployHandler.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupAtomicOperationValidator.java
feat(provider/ecs): Create server group Atomic Operation stub
> feat(provider/ecs): Create server group Atomic Operation stub

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
- clouddriver-ecs/README.md
feat(provider/ecs): Added ECS SDK
> feat(provider/ecs): Added ECS SDK

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppengineClusterProvider.groovy
> fix(provider/appengine): fix server group endpoint

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/KubernetesDeployManifestConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesApiVersion.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestOperationDescription.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/MalformedManifestException.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/ops/KubernetesManifestDeployer.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpec.groovy
Continuation of https://github.com/spinnaker/clouddriver/pull/1820
spinnaker/spinnaker#1916
spinnaker/spinnaker#1922
> feat(provider/kubernetes): V2 operation init

- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/AgentIntervalAware.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/DefaultAgentScheduler.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/DefaultAgentIntervalProvider.java
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/config/DockerRegistryProviderConfig.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
> feat(provider/docker): Adds configuration of Docker image caching agent.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/KubernetesDeployManifestConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesAugmentedManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotater.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpinnakerRelationships.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeployer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetDeployer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesApiException.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy
Deploys & annotates the replica set
> feat(provider/kubernetes): V2 Deploy replica set

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonS3DataProvider.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonS3DataProviderSpec.groovy
- do not expect bucket key == id
- handle accounts w/o accountId (specifically docker registries)
> fix(amazon): Fix a couple of rather obvious s3 proxy issues

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesClientApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
Hi Lars
Deleted the forked branch and re-base the code again to resolve the indentation issue.
Please Review @lwander 
Regards
Prashant
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 …
> Re based the code again to resolve the Indentation issue

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesApiVersion.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesSelector.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesSelectorList.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KeysSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgentSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesSelectorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
This starts only with the replica set, but will make adding new caching agents much easier.
> feat(provider/kubernetes): Cache arbitrary resource

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ApplicationSearchProvider.groovy
* add ability to pass search filters down to application searching in
front50.
> feat(search): update application search

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ProjectSearchProvider.groovy
* ensures the filters specified for project searching are passed down to F50
> feat(search): add filters to project search

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPodCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPodCachingAgentSpec.groovy
Moves shared caching logic into super class KubernetesV2CachingAgent
> feat(provider/kubernetes): Cache pods

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotater.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpec.groovy
> feat(provider/kubernetes): Annotate templates as well

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperationUnitSpec.groovy
from #1846 now an instance that has been shared to the target account doesn't get tags replicated which breaks the functionality of the tag images stage
> fix(aws/tags): ensure tag sync is always performed during allow launch

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesClientApiAdapter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesControllersCachingAgent.groovy
Added below functionalities 
1)Pod Discovery Added 
2)Yaml Object to JSON conversion added 
3) Type :Kind information added (Its a workaround )
@lwander Please review.
FYI @chlung 
* Add a comment to @spinnaker/reviewers for review if your …
> feature(provider/kubernetes) : Pod Discovery

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesClientApiAdapter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesClientApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/KubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/exception/KubernetesClientOperationException.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesControllerConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesApiClientConfig.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesControllersCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesV1CachingAgentDispatcher.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java
About this PR,
Merge k8s-client-staging branch into master.
Thanks.
Note: second try to address previous rebasing problem.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that …
> fix(provider/kubernetes): merge k8s-client-staging branch into master.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
> fix(provider/kubernetes): Add missing credential props

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
Fully addresses: spinnaker/spinnaker#1657
Also accounts for the possibility that the user might want to set
their own targetSize while ignoring the source capacity.
Deck work is still needed to expose "useSourceCapacity" in the UI.
> feat(provider/kubernetes): Add proper support for leveraging source capacity

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerInstance.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerServerGroup.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesV1ClusterProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesCluster.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesInstance.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesLoadBalancer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesServerGroup.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/ManifestBasedModel.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/provider/KubernetesCacheUtils.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/provider/KubernetesV2ClusterProvider.java
> feat(provider/kubernetes): V2 cluster provider

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1Cluster.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1Instance.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1LoadBalancer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1ServerGroup.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesControllersCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesInstanceCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesInstanceProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesLoadBalancerProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesProviderUtils.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesV1ClusterProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2Cluster.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2Instance.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2LoadBalancer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2ServerGroup.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/provider/KubernetesV2ClusterProvider.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesInstanceSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesServerGroupSpec.groovy
> refactor(provider/kubernetes): Rename duplicate classes
