clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Cluster.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy

feat(moniker): Adds moniker to all clusters & server groups

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/names/NamerRegistry.java

chore(javadocs): Fix `<` usage

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy

Avoids the exception reported in spinnaker/spinnaker#1958

fix(web): Guard against not finding a ClusterProvider

---

.gitignore
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/cache/KeysSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/data/KeysSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/KeyParser.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/provider/agent/Namespace.groovy

* in an effort to speed up searching, this adds logic that attempts to
pick a "good" value to use as a search query string rather than just
using the empty string and pulling all the keys for a given type.

feat(search): add fallback query param to search

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle

@chlung this should unblock to you fix https://github.com/spinnaker/spinnaker/issues/1979

chore(provider/kubernetes): Use version 0.2.0 of client-java

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesAugmentedManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpinnakerRelationships.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/names/KubernetesManifestNamer.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPodCachingAgentSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgentSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

spinnaker/spinnaker#1914
spinnaker/spinnaker#1966

feat(provider/kubernetes): Integrate moniker into v2

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPodCachingAgentSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgentSpec.groovy

This will allow us to decide when to patch or redeploy a resource during a deploy operation.

feat(provider/kubernetes): Cache v2 resources as artifacts

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleTcpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy

feat(provider/google): Support connection draining for LBs

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy

fix(provider/gce): s/it/cacheData/ in zonal svg caching agent.

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/DockerUserAgent.java
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy

Looks like the clouddriver-level user agent isn't being autowired properly.

fix(provider/docker): Assign proper Spinnaker/<version> user agent

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AbstractRegionAsgInstanceIdsDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/EnableDisableAsgDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy

[AWS] Allow rollbacks to proceed when < 100% of instances in the rollback asg report healthy.

fix(rollbacks): support for tolerating some instance failures

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy

fix(appengine): Dont assume storage.gce.enabled=true

---

clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/storage/controllers/AppengineStorageController.java

feat(appengine): Add AppengineStorageController to list accounts

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiAdapter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

chore(provider/kubernetes): Bump client to 1.0.0-beta1

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy

fix(provider/aws): Return load balancers for all target groups associated with an application

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesAtomicOperationDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/converters/KubernetesAtomicOperationConverterHelper.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/KubernetesKindAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/instance/KubernetesInstanceDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/job/KubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/job/RunKubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/loadbalancer/DeleteKubernetesLoadBalancerAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/loadbalancer/KubernetesLoadBalancerDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/securitygroup/DeleteKubernetesSecurityGroupDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/securitygroup/KubernetesSecurityGroupDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/KubernetesServerGroupDescription.groovy

refactor(provider/kubernetes): Move ops w/ kind into v1 only

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerClassicDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy

- Autocreate elb security group if doesnt exist and ingress on application security group
- Will also autocreate the application security group if it doesnt exist

feat(provider/amazon): Create app elb specific security group for new ELBs

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesDeployManifestConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/servergroup/KubernetesResizeServerGroupConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourcePropertyRegistry.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/servergroup/KubernetesResizeServerGroupDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/servergroup/KubernetesServerGroupOperationDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CanResize.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesManifestDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/servergroup/KubernetesResizeServerGroupOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesDeployManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/servergroup/KubernetesResizeServerGroupValidator.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

Don't merge yet - pausing to work on fixing a bug elsewhere

feat(provider/kubernetes): Support resize operations

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1Health.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1Instance.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Health.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Instance.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesInstanceSpec.groovy

feat(provider/kubernetes): V2 instance state

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy

Do one upfront list call per server group caching cycle for instance templates as opposed to a get call per server group.

feat(provider/gce): Replace instanceTemplate get with list call.

---

clouddriver-core/clouddriver-core.gradle

Enables logback configuration such as:
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
<provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider"/>
</encoder>

feat(logging) compile logstashEncoder for json logging

---

clouddriver-appengine/clouddriver-appengine.gradle

Fixes batch request failures.
@ewiseblatt

fix(appengine): fix deploy failures

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

Noticed this bug while combing the logs for other problems.

fix(web): Fixing missing property exception

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesServiceCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy

feat(provider/kubernetes): cache non-obvious relationship

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerClassicDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy

- updated code that allows ingress from elb group to app security group

refactor(aws): Simplified ELB security group autocreation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/loadbalancer/KubernetesLoadBalancerDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy

fixes spinnaker/spinnaker#2035

feat(provider/kubernetes): Enable setting of labels on k8s Service objects spinnaker/spinnaker#2035

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy

- fixed NPE due to missing credentials in security group description request

fix(aws): Fix NPE in elb group autocreation

---

clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/GoogleExecutor.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GoogleOperationPoller.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy

feat(google): Instrument individual google API calls.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy

- Updated to only auto create <appname>-elb group for new ELBs

fix(aws): Only autocreate app elb security group on Create

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Manifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesServiceDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/UnsupportedVersionException.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ManifestController.java

feat(provider/kubernetes): moniker status

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java

@jtk54 this caused the last build failure

fix(startup): Kubernetes manifest provider autowired ambig bean

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java

fix(provider/kubernetes): v2 expire logical keys

---

cats/cats-dynomite/cats-dynomite.gradle

feat(cats): dynomite version bump to stable

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy

- made auto creation of <appname>-elb group for new ELBs configurable
- defaulting to off

fix(aws): Flagging elb security group autocreation (defaults to off)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesDeploymentCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java

Registers status & caching for deployments

feat(provider/kubernetes): register deployment caching agent

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesStatefulSetCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesStatefulSetHandler.java

Automatically shows up as a server group since it's registered as one

feat(provider/kubernetes): v2 statefulset support

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

When building a set of partial instances, only include those
that are not shutting down or terminated.

fix(provider/amazon): Only include non-terminating instances

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java

The issue here is that when a key with a ttl is hashed, the hash
persists forever, even after the key disappears. The obvious fix would
be to associate the hash with a ttl as well, but as far as I can tell,
there is no good way to ensure that the hash will always expire
when/before the key does without introducing some subtle race.
There's not a lot of keys that do have a ttl, so I don't see this having
a large performance impact. It feels like the cleanest/most contained
way to deal with the problem described above.

fix(cats/redis): Don't hash ttl'd keys

---

gradle/buildViaTravis.sh
gradle/installViaTravis.sh

chore(gradle): Avoid running tests on master/release branch

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesIngressCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesCoordinates.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressHandler.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy

feat(provider/kubernetes): v2 ingress support

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java

@edwinavalos fyi - I'll create a Halyard change too

feat(provider/kubernetes): allow users to skip creating pull secrets

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy

refs https://github.com/spinnaker/spinnaker/issues/2077

fix(provider/gce):Enable RPS when only RATE or UTILIZATION

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNamespaceCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesNamespaceHandler.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy

will be required to lookup security group relationships by namespace

feat(provider/kubernetes): v2 cache namespaces & relationship

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy

Deleting L4 LBs will fail if any server group instances are attached to the LB; however, GCP is sometimes flaky in reporting the state of deleted instances and leaves references in the L4 LB's target pool. As a workaround, we can list all project instances on an L4 delete and cross-reference to ensure that instances are still associated with the L4.

fix(provider/gce): Ensure referenced instances exist during L4 delete.

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopServerGroupManagerProvider.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupManager.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupManagerProvider.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupSummary.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroupManager.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroupSummary.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ServerGroupManagerProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentHandler.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupManagerController.java

feat(provider/kubernetes): v2 server group manager

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

It appears that list() can return partially-formed LB resources, specifically backend services and backends. It appears that backends may have empty `backend.group` references now under the list() commands, where we could depend on the references being non-null previously under the get() commands.

fix(provider/gce): Handle partially-formed L7 LB resources properly.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy

A few small fixes/guards to the L7 caching agent as well.

perf(provider/gce): s/get/list/ in ILB caching agent.

---

Dockerfile.slim

Alpine does not include curl. Need to use wget instead.

fix(docker): Use wget instead of curl

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/KubernetesServerGroupDescription.groovy

fix(provider/kubernetes): v1 read namespace as region

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java

closes https://github.com/spinnaker/spinnaker/issues/2094

feat(provider/kubernetes): default to frigga

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesV1InstanceProvider.groovy

support pod logs for v1 provider. going to be useful when working on run
job logs as well.
@lwander PTAL!

feat(provider/kubernetes): v1 pod logs

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy

This has become pretty chatty, and was really only helpful for development.

chore(jobs): turn down log-level for all jobs

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy

@duftler FYI
cherry pick for 1.5.1

fix(provider/gce): Break out labels.

---

build.gradle
cats/cats.gradle
gradle/wrapper/gradle-wrapper.properties

chore(dependencies): update to latest spinnaker-dependencies

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/helpers/AbstractServerGroupNameResolver.groovy

@duftler  
Could you review this?

refactor(clouddriver-core) Fixed to use const value

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineCredentialsInitializer.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineNamedAccountCredentials.groovy

https://github.com/spinnaker/spinnaker/issues/2130 
Needs Halyard support.

feat(provider/appengine): allow gcloud version to be configurable

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactDownloader.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/ArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gcs/GcsArtifactCredentials.java
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesDeployManifestConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeployManifestDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy

With this you can now deploy from manifest & docker changes in the same pipeline

feat(provider/kubernetes): deploy from artifact

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/cache/Keys.groovy

Fixes silent on demand caching error.

fix(provider/appengine): fix monikers for app engine server groups

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackImageLookupController.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/Image.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackImage.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackImageCachingAgent.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/controllers/OpenstackImageLookupControllerSpec.groovy

bug(provider/openstack) - filter images by region if provided.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeleteManifestDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesMultiManifestOperationDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/OperationResult.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CanDelete.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CanResize.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CanScale.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeleteManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesScaleManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy

https://github.com/spinnaker/spinnaker/issues/2170

feat(provider/kubernetes): return modified manifests

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesUndoRolloutManifestDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CanRollout.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesUndoRolloutManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesUndoRolloutManifestValidator.java

https://github.com/spinnaker/spinnaker/issues/2179

feat(provider/kubernetes): v2 make rollback dynamic

---

build.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java

chore(dependencies): bump spinnaker-dependencies to 0.131.0

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactProviderProperties.java

Add GitHub as a resource to download artifacts from.
@lwander

feat(artifacts): Download artifacts from GitHub

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterControllerSpec.groovy

cherry pick of https://github.com/spinnaker/clouddriver/pull/2249

fix(clusters): Return all matching server groups for a provider

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java

Also log an error when edda retries have been exhausted.

fix(provider/aws): Ensure that `HttpEntity` is closed on edda failure

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java

would have helped: https://github.com/spinnaker/clouddriver/pull/2261

chore(provider/kubernetes): log malformed cache entries

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesCachingProperties.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java

https://github.com/spinnaker/spinnaker/issues/2214

feat(provider/kubernetes): v2 ignore caching flag

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/ManifestBasedModel.java

feat(provider/kubernetes): return resource create time

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java

feat(provider/kubernetes): fail deploy if artifacts don't bind

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeployManifestDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java

https://github.com/spinnaker/spinnaker/issues/2225

feat(provider/kubernetes): split out required & optional artifacts

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java

https://github.com/spinnaker/spinnaker/issues/2225

fix(provider/kubernetes): annotate artifacts with reference

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy

The `startJob` method submits your request to a threadpool, which it
immediately starts polling. This isn't useful, and limits the number of
jobs that can be started to the number of threads supported by your
scheduler. As a result, submitting a lot of jobs at once causes
(needlessly) a lot of these jobs to timeout.
There is still a `sleep(500)` which doesn't seem to add anything in the
function, but didn't feel confident removing since other spots in
clouddriver make use of it.
@danielpeach I added you to that todo because I think appengine is 
the only other big consumer of this
https://github.com/spinnaker/spinnaker/issues/2232

fix(jobs): Fix bottleneck around JobLocalExecutor.startJob

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesDeployManifestConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy

https://github.com/spinnaker/orca/pull/1888
spinnaker/spinnaker#2235

refactor(provider/kubernetes): remove obsolete source check

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/LoadBalancerController.groovy

https://github.com/spinnaker/spinnaker/issues/2219

fix(core): Allow for versioned providers in lb controller

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/LoadBalancerController.groovy

Cherry pick of https://github.com/spinnaker/clouddriver/pull/2284

fix(core): Allow for versioned providers in lb controller (#2284)

---

clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchClient.kt
clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/aws/ElasticSearchAmazonCachingAgentProvider.kt
clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/aws/ElasticSearchAmazonInstanceCachingAgent.kt
clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/aws/ElasticSearchAmazonServerGroupCachingAgent.kt
clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchModels.kt

Support searching for instances by ip address (and a handful of other
attributes).
Specifically this PR introduces a brand new agent that fetches all
instances in each aws account / region.

poc(provider/aws): Index a subset of instance details (#2204)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy

https://github.com/spinnaker/spinnaker/issues/2082

feat(provider/kubernetes): v1 volume mount subpath support

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy

Was wondering why my numbers were looking strange...

fix(provider/gce): Fix typo in metric tag.

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationService.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationServiceSpec.groovy

Adds a `ContainerInformationService` which is responsible for providing ECS container-centric information to other providers.

feat(provider/ecs): ECS Container Information Service

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

https://github.com/spinnaker/spinnaker/issues/2286

feat(provider/kubernetes): make kubectl configurable per-account

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java

feat(provider/kubernetes): v2 image buildinfo

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/RoleController.java

fyi @dkirillov (Also please stick to [commit message conventions](https://www.spinnaker.io/community/contributing/submitting/#commit-message-conventions))

fix(roles): Fix startup on unsatisfied dependency

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppengineAtomicOperationConverter.groovy

using just the artifact name leaves out the `:tag` portion and incorrectly defaults all deployments to `:latest`

fix(provider/appengine): deploy with artifact reference when available

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy

It's possible that a launch configuration can be created but subsequently
fail due to a network blip.
When this happens, AWS will reject any subsequent requests with an
`AlreadyExistsException` exception.
In such situations, it makes sense to continue (launch configurations
are timestamped down to the second) rather than fail the task.

fix(aws): Continue if launch configuration already exists

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPersistentVolumeCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPersistentVolumeClaimCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeClaimHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeHandler.java

https://github.com/spinnaker/spinnaker/issues/2307

feat(provider/kubernetes): v2 support pv & pvc deploys

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesJobCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java

@lwander could you review this, please? Jobs are useful to run smoke tests as part of pipelines, and many other things.

feat(provider/kubernetes): v2 Add support for Kubernetes jobs

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesJobCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java

feat(provider/kubernetes): v2 Add support for Kubernetes jobs (#2380)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy

UpsertKubernetesAutoscalerAtomicOperation will now update existing HPA instead of deleting&creating it again.

fix(provider/kubernetes): upsertScalingPolicy will patch existing autoscaler instead of re-creating

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy

fix(provider/aws): Fix groovyism in call to elbv2 region scoped provider call

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java

Closes https://github.com/spinnaker/spinnaker/issues/2468

fix(artifacts): version is not required to load an artifact

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java

fix(artifacts): version is not required to load an artifact (#2396)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ApplicationProvider.java

fix(provider/kubernetes): don't return empty apps in app list (#2400)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorker.java

Decided I could use some small wins. Aiming to cleanup noise in our logs.

chore(provider/aws): Reduce common not found exceptions

---

cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cluster/DynoClusteredSortAgentScheduler.java

fix(dynomite): Cant use evalsha

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/embedded/EmbeddedArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/embedded/EmbeddedArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/embedded/EmbeddedArtifactCredentials.java

https://github.com/spinnaker/spinnaker/issues/2526

feat(artifacts): base64 embedded artifact downloader

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactConfiguration.java

feat(artifacts): Add a "no auth" http artifact account where needed

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/RedisTaskRepository.java

Little optimization for Redis users, bug fix for the Dynomite crowd.

fix(core): Switch task IDs to be UUIDs

---

gradle.properties

chore(build): Parallel gradle

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java

In particular, the previous pattern had issues with dashes in image names. Replace it with a pattern based on the Docker source code.

fix(artifacts): Make Docker image name matching more accurate

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy

This will fix https://github.com/spinnaker/spinnaker/issues/2249 , I tested this in kubernetes 1.8.8 and 1.93 in GKE.

fix(provider/kuberentes): v1 fix scaleTargetRef apiVersion in HPA

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java

@wjoel 
Sorry was being sloppy getting a demo ready...

fix(provider/kubernetes): tolerate null service account

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperationSpec.groovy

The EntityTags for an entity will only be persisted (to s3 and elastic
search) if at least one tag has been modified.

fix(entitytags): Filter out any entity tags that have not been modified

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy

First of probably quite a few PRs of this flavor this week.

chore(aws): Increasing logs for scaling policies in case of AWS failure

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesEventCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Manifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesEventHandler.java

https://github.com/spinnaker/spinnaker/issues/2587

feat(provider/kubernetes): v2 cache & surface events per-resource

---

build.gradle
cats/cats-dynomite/src/test/groovy/com/netflix/spinnaker/cat/dynomite/cache/DynomiteCacheSpec.groovy
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/DefaultNodeIdentity.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/DynomiteConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy

- also fixes DefaultNodeIdentitySpec when running on a host
that disallows connections between en* and lo0

fix(mdc): fix propagation of exection id

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Manifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandler.java

feat(provider/kubernetes): allow jobs & pods to "fail"

---

gradle/buildViaTravis.sh
gradle/installViaTravis.sh

hoping for less/no cases of builds timing out with no output which may be
to too many things happening in parallel that none is making progress
fast enough

chore(build) single-thread ci builds

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java

BREAKING CHANGE: The request verb had to be changed to PUT to support
placing the artifact into the payload body. Spring doesn't allow request
bodies for GET requests, and the ?reference= parameter was too long with
large base64 artifacts

refactor(artifacts): change fetch verb type

---

build.gradle

Includes better jedis instrumentation.

chore(*): Bump spinnaker-dependencies to 1.151.0

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/agent/CleanupPendingOnDemandCachesAgent.java

Switched to using `exists` vs `get` with smaller partitions.

fix(core): Optimize `CleanupPendingOnDemandCachesAgent`

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusLoadBalancerClient.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java

In testing, we found that increasing page size dramatically reduced the titus caching time.

perf(titus): increasing page size for titus requests

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java

cherry-pick of https://github.com/spinnaker/clouddriver/pull/2500

fix(provider/ecs) Changes to allow ECS to work with AWS provider.

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusLoadBalancerClient.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java

Not sure if this is causing a memory problem. Reverting to investigate.

fix(titus): revert page size for investigation

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java

Reverting to try and narrow down the performance impact on titus.

revert(titus): reverting #2534

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/AbstractEnableDisableAtomicOperation.groovy

handle attach and detach of load balancers during disable / enable operations

fix(titus): fix load balancing

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java

Retry less with a correct time in between

fix(titus): correct retry interval

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java

secret.name should be secret.secretName

fix(provider/kubernetesv2): fix secretVolumeReplacer

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java

secret.name should be secret.secretName
cherrypick 1.7

fix(provider/kubernetesv2): fix secretVolumeReplacer (#2565)

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandMetricsSupport.groovy
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsOnDemandAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskCachingAgent.java

Using Supplier to make this more java friendly.
Fixing where ECS was using those methods.

fix(cache): make OnDemandMetricsSupport java-friendly

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java

Would have at least prevented https://github.com/spinnaker/clouddriver/pull/2576 from taking out the whole cluster in the cache

fix(provider/kubernetes): v2 make cache more tolerant of failures

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java

Closes https://github.com/spinnaker/spinnaker/issues/2730

fix(provider/kubernetes): fix automatically assigned moniker cluster

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java

Fixes https://github.com/spinnaker/spinnaker/issues/2732

fix(provider/kubernetes): remove sticky pods from large cache

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestStrategy.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java

Closes https://github.com/spinnaker/spinnaker/issues/2351

feat(provider/kubernetes): allow user to set versioning behavior in annotations

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy

The new `minimalOnDemand` feature flag has been active for a week or so
and looks good.
This removes the legacy behavior.

chore(titus): Remove `legacyOnDemand` from `TitusClusterCachingAgent`

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy

Given that the cardinality of ON_DEMAND is quite small, it is _possibly_
more efficient to fetch the ON_DEMAND records for a given account +
region and perform an in-memory filter.
Previously we were doing an mget with many thousands of keys (one per
server group) when only a small number (dozens?) would ever exist in the
set.

perf(aws): Optimize how ON_DEMAND records are fetched during caching cycles

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy

cherry-pick of https://github.com/spinnaker/clouddriver/pull/2605 in preparation for 1.7.3 release

fix(provider/google): remove json key from logs during init

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy

A port of spinnaker/clouddriver#2599 to `titus`.

perf(titus): Optimize how ON_DEMAND records are fetched during caching cycles

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java

Previously we were only checking one of the failure modes (if it takes too long to complete) but others exist. Checking for the "Failure" condition type covers this.
Fixes https://github.com/spinnaker/spinnaker/issues/2696

fix(provider/kubernetes): v2 check job failed

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java

fix(provider/kubernetes): v2 check job failed (#2608)

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy

persists the decision to not create an applicationDefaultSecurityGroup in titus attribute

fix(titus): respect applicationDefaultSecurityGroup when cloning

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy

fixes: https://github.com/spinnaker/spinnaker/issues/2747

fix(cache): metrics support may be null

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy

fix(cache): metrics support may be null (#2622)

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy

chore(cache): debug logging for handle

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/AccountForClient.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/GoogleApiTestUtils.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraitsSpec.groovy

feat(google): Add account label for google.api metrics.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy

This was broken in recent change.
@lwander

fix(google): Fixed call to timeExecute

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ManifestController.java

closes: https://github.com/spinnaker/spinnaker/issues/2796

fix(provider/kubernetes): fix looking up non-namespaced manis

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Health.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Instance.java

Closes: https://github.com/spinnaker/spinnaker/issues/2801

feat(provider/kubernetes): include container status in health

---

clouddriver-dcos/clouddriver-dcos.gradle
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosConfigurationProperties.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/AbstractDcosServerGroupDescription.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/DeployDcosServerGroupDescription.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/AppToDeployDcosServerGroupDescriptionMapper.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/DeployDcosServerGroupDescriptionToAppMapper.groovy
clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/loadbalancer/UpsertDcosLoadBalancerAtomicOperationSpec.groovy
clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/AppToDeployDcosServerGroupDescriptionMapperSpec.groovy
clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/DeployDcosServerGroupDescriptionToAppMapperSpec.groovy
clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosServerGroupCachingAgentSpec.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy

This includes support for Marathon 1.5, Marathon on Marathon, and a fix necessary for our JFrog artifactory to work with the docker registry catalog paging (that should be passive).

feat(provider/dcos) Adding various features for upstream

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java

@dibyom this will be relevant to your patch manifest work. We'll need to use the `namespace` supplied to the patch command rather than read it from the manifest.

fix(provider/kubernetes): substitute k8s artifacts by namespace

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java

fix(provider/kubernetes): sub manifests by namespace (#2641)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/edda/EddaApi.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy

From ~39-40s to 800ms for our larger accounts.

perf(aws): Optimize ALB indexing when edda is enabled

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java

closes: https://github.com/spinnaker/spinnaker/issues/2832

fix(provider/kubernetes): be tolerant of k8s < v1.7

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/provider/DefaultProviderCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java

Seeing a couple oddities and want to ensure they're unrelated
(or related) to this change.

revert(cats): Reverting the `List` -> `Set` change

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy

This appears to have made some difference locally.

perf(aws): Batch up a few cases of `objectMapper.convertValue()`

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineInstance.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineLoadBalancer.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Instance.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerInstance.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsTask.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationService.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/view/EcsInstanceProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesModelUtil.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Health.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Instance.java
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSInstance.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusInstanceProvider.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy

Changing the health type to `List<Map<String, Object>>` across the board to allow for what the actual type is.

fix(Instance): change health type to conatin Object

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfig.groovy

`delegated.internalPool` vs `internalPool`
All instances of `JedisPool` should be `InstrumentedJedisPool` so should
be no need to worry about the status of `internalPool`.

fix(redis): Extract `JedisPool` metrics from delegate

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy

Adds support for NFS volumes to Kubernetes provider. A NFS is one possible type of volumes for Kubernetes.
(Note: Simular to #1729 )

feat(provider/kubernetes): Support NFS Volumes

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

Closes https://github.com/spinnaker/spinnaker/issues/2879
Halyard support incoming.

perf(provider/kubernetes): caching agent restrictions by kind

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApplicationProperties.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestLabeler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/names/KubernetesManifestNamer.java
clouddriver-web/config/clouddriver.yml

feat(provider/kubernetes): manifest labeler

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanDelete.java

fix(provider/kubernetes): v2 tolerate empty delete options

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java

fix(provider/kubernetes): handle empty repsonse

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java

fix(provider/kubernetes): handle empty repsonse (#2710)

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoscalingPolicy.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy

Also adds mode handling for enable disable operations. Still needs a bit of work in Orca for capacity pinning on GCE deploys.

feat(provider/gce): Adds support for autoscaling policy mode in upsert.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy

Make it obvious that the image doesn't exist in a particular region to help with debugging.

fix(provider/amazon): improve image not found error message

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperation.groovy

If we get this exception when it's already deleted, we should ignore it. That way pipelines don't fail because of this.

fix(provider/amazon): ignore not found when already deleted

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy

Fixes latest integration test failure.

fix(provider/gce): Guard against null autoscaler in enable/disable.

---

clouddriver-web/pkg_scripts/postInstall.sh

fix(install): install kubectl if missing

---

clouddriver-web/pkg_scripts/postInstall.sh

fix(install): install kubectl if missing (#2728)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java

fix(provider/kubernetes): fix v2 error message (#2726)

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/utils/AwsLookupUtil.groovy

Need to refresh vpcs in account refresh.

fix(titus): refresh vpcs in addition to aws accounts

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerSpec.groovy

fix(provider/kubernetes): fix regex perf bug when parsing images (#2736)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

same as https://github.com/spinnaker/clouddriver/pull/2746, but for `release-1.8.x`

fix(aws): don't respecifiy encryption if the snapshotId is provided

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactTypes.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandler.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandlerSpec.groovy

closes: https://github.com/spinnaker/spinnaker/issues/2976

feat(provider/kubernetes): support HPA binding

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java

fix(provider/kubernetes): be more tolerant of failing health checks (#2750)

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Instance.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/ManifestBasedModel.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

@sbwsg pushed in case it helps you with https://github.com/spinnaker/spinnaker/issues/2979

feat(provider/kubernetes): add ID field to k8s manifest objects

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy

fix(provider/titus): only fetch tasks if includeDetails is requested

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java

Trying again to actually ignore 404 on terminate and shrink.

fix(titus): really ignore not found on terminate

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesAutoscalerStatus.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesControllersCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy

fix(provider/openstack): tolerate null stack. (#2769)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/BlockDeviceConfig.groovy

(provider/aws): r5 and z1d instance types

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy

when providing explicit subnetIds don't restrict by tags
for some advanced deployment cases we want to allow use of
a subnet that isn't otherwise intended for Spinnaker use

feat(aws/subnets): allow all specific subnetIds

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusJobStatus.groovy

A job can have no tasks. Let's not freak out when that happens.

fix(titus): null check for titusJobStatus

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactProviderProperties.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactProviderProperties.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactProviderProperties.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactProviderProperties.java

when enabling multiple http based artifact providers (http + gitlab +
github) clouddriver filed to start stating that multiple beans were
found.

fix(artifacts): fixes multiple http base providers

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeleteAmazonImageAtomicOperationConverter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteAmazonImageDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonImageAtomicOperation.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonImageAtomicOperationSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java

- added operation for deleting an AMI in account/region

feat(aws): Adding a delete ami operation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

fix(provider/kubernetes): be permissive of unreachable clusters on startup (#2840)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

caching pods for server group one time and handle them locally.
Cherry pick into 1.9 of #2834
@abcsnowwolf fyi

fix(provider/kubernetes): Speed up caching server group (#2834)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java

Fixes https://github.com/spinnaker/spinnaker/issues/3148

fix(provider/kubernetes): deployment w/ 0 replicas is 'stable'

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java

fix(provider/kubernetes): deployment w/ 0 replicas is 'stable' (#2848)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeleteAmazonImageAtomicOperationConverter.java

fix(aws): Adding missing `@Component` to `deregister image` converter

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java

Cuts down cache time by ~1% -- not a huge improvement but was discovered
making other improvements

fix(provider/kubernetes): speed up stratifying cache elements

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java

fix(provider/kubernetes): reduce allocations during cache merge (#2863)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java

Cherry pick of @ezimanyi's fix into 1.9

fix(provider/kubernetes): Services have a cluster relationship (#2865)

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupManager.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ClusterProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/data/KubernetesV2ServerGroupCacheData.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

As seen on the /applications/{app}/serverGroups endpoint:

feat(provider/kubernetes): add server group managers to sg endpoint

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/StackChecker.java

Detail in issue 3174
https://github.com/spinnaker/spinnaker/issues/3174

fix(openstack): error exception message while deleting server group

---

Dockerfile.slim

This was changed in master and causing issues in 1.8.

fix(core): Fix dependency in Dockerfile

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotatorSpec.groovy

Other half of fix for https://github.com/spinnaker/spinnaker/issues/3165

fix(provider/kubernetes): deployment sequence only applies to rs

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesPodMetric.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

feat(provider/kubernetes): cache pod metrics

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Manifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java

```json
"metrics" : [
{
"metrics" : {
"MEMORY(bytes)" : "33Mi",
"CPU(cores)" : "4m"
},
"containerName" : "istio-proxy"
},
{
"containerName" : "nginx",
"metrics" : {
"CPU(cores)" : "0m",
"MEMORY(bytes)" : "2Mi"
}
}
],
```

feat(provider/kubernetes): surface metrics

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsSecurityGroup.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsSecurityGroupSummary.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsSubnet.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/AmazonPrimitiveConverter.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsAccountMapper.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsSecurityGroupProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsSubnetProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsInitializer.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/NetflixAssumeRoleEcsCredentials.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/SubnetSelector.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsAccountMapperSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/SubnetSelectorSpec.groovy

feat(provider/ecs): Support for Elastic Network Interfaces (AWSVPC networking mode)
@robzienert @dkirillov 
Couldn't have made the PR shorter as it wouldn't have been a full feature then

feat(provider/ecs): Support for Elastic Network Interfaces (AWSVPC networking mode)

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/ComputeVersion.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentials.groovy

fix(provider/google): batch & service path must match

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/ComputeVersion.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentials.groovy

* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …

fix(provider/google): batch & service path must match (#2925)

---

Dockerfile.slim

fix(core): Fix dependency in Dockerfile (#2883) (#2884)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/exception/KubernetesOperationException.groovy

The changes allow for better debugging of failed kubernetes requests. Besides the error message, more parameters like response code, reason, etc.

fix(provider/kubernetes): Improved log output from KubernetesOperationException

---

.github/PULL_REQUEST_TEMPLATE.md

This reverts commit 3752a1b93f1e3981b46984c84d7f182492bd10ad.

chore(*): REVERT Update PULL_REQUEST_TEMPLATE.md - put reviewers mention in (#2974)

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy

This error was not correctly showing the load balancers that couldn't be
found.

fix(google): Fix error to include missing load balancers.

---

clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/deploy/GoogleCommonSafeRetry.groovy
clouddriver-google-common/src/test/groovy/com/netflix/spinnaker/clouddriver/googlecommon/deploy/GoogleCommonSafeRetrySpec.groovy

fix(google): Stop retrying if allowable error encountered.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java

the change to camel-case is by convention

fix(provider/kubernetes): fix admission kind scopes

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java

closes https://github.com/spinnaker/spinnaker/issues/3374

feat(provider/kubernetes): allow custom resource scope config

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy

Creation of a security group is eventually consistent yet we were
immediately tagging a newly created security group.
This PR introduces retries _and_ treats a failure to tag as non-fatal.

fix(aws): Retries around security group tagging

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestTraffic.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanLoadBalance.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java

https://github.com/spinnaker/spinnaker/issues/3377

feat(provider/kubernetes): attach lb during deploy

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactClient.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactProviderProperties.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/config/ArtifactConfiguration.java

Added oracle type artifact.  The related haylard PR is https://github.com/spinnaker/halyard/pull/1041.

feat(artifact/oracle): Added oracle artifact.

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesDisableManifestConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDisableManifestDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDisableManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesSelector.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesSelectorList.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/MatchExpression.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesSelectorListSpec.groovy

Does not implement disable yet, but sets up needed scaffolding for
operation, as well ability to build queries for finding pods.

feat(provider/kubernetes): first pass at disable

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesDeleteManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesDeployManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesPatchManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesPauseRolloutManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesResumeRolloutManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesScaleManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesUndoRolloutManifestValidator.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/servergroup/KubernetesResizeServerGroupValidator.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtilSpec.groovy

closes https://github.com/spinnaker/spinnaker/issues/3398

fix(provider/kubernetes): validate kind on edit operation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

feat(provider/kubernetes): make checking permissions optional on startup

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy

HTTP health checks for TCP does not support custom matchers and timeouts. Also, unhealthy and healthy values need to be the same

fix(provider/amazon): support setting a http health check on a tcp target group

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAmiTagsAtomicOperation.groovy

Slightly reworking the `upsertImageTags` atomic operation for AWS to use Edda. This should speed up our current tag image stage for regions that are super big. The task is already retryable in Orca, so if Edda returns a 404, we should continue to retry until its caches are updated.
Seems zippy locally.

fix(aws): Use Edda during upsert AMI tags operations

---

build.gradle
cats/cats.gradle
clouddriver-oracle/clouddriver-oracle.gradle
clouddriver-web/clouddriver-web.gradle
gradle/buildViaTravis.sh
gradle/init-publish.gradle
gradle/installViaTravis.sh

Based off @cfieber's work in https://github.com/spinnaker/clouddriver/pull/2667
Ref: https://github.com/spinnaker/spinnaker/issues/2844
Supercedes https://github.com/spinnaker/clouddriver/pull/2667

Pulls in unopinionated spinnaker-gradle-project plugin

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateApplication.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java

Co-authored-by: Jon Schneider <jschneider@pivotal.io>

fix(provider/cf): fix route definition for CF manifest deployment

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java

https://github.com/spinnaker/spinnaker/issues/3470

fix(provider/kubernetes): fix sticky lb & pod relationship

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ManifestProvider.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopManifestProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ManifestController.java

https://github.com/spinnaker/spinnaker/issues/3470

feat(provider/kubernetes): dynamic target selection

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java

https://github.com/spinnaker/spinnaker/issues/3470

feat(provider/kubernetes): set disabled flag when no lbs attached

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java

https://github.com/spinnaker/spinnaker/issues/3470

fix(provider/kubernetes): only disable pods owned by controller

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java

fix(provider/kubernetes): associate ingress w/ app

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Instance.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancer.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/SecurityGroup.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupManager.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/ManifestBasedModel.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

https://github.com/spinnaker/spinnaker/issues/3238
implemented for k8s v2 here as well

feat(core): add labels to objects for grouping in UI

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy

fix(provider/gce): Fix autoscaling mode parsing.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/CreateServiceInstance.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServiceDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperation.java

Co-Authored-By: Joris Melchior <joris.melchior@gmail.com>
Co-Authored-By: Stu Pollock <spollock@pivotal.io>

fix(provider/cf): handling of service parameters

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/HelmArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/HelmArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/HelmArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/HelmArtifactProviderProperties.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/IndexParser.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/config/ArtifactConfiguration.java

issue: https://github.com/spinnaker/spinnaker/issues/3284

feat(artifacts): Add support for helm/charts artifacts

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java

fix(provider/kubernetes): consult kind list for crd caching (#3144)

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AbstractAppengineCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineLoadBalancerCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineServerGroupCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineCredentialsInitializer.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineNamedAccountCredentials.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/3539

feat(provider/appengine): allow limiting the set of indexed services and versions

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppengineUtils.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineServerGroupCachingAgent.groovy
clouddriver-google-common/clouddriver-google-common.gradle
clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/GoogleExecutor.groovy
clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/batch/GoogleBatchRequest.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleGlobalAddressCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHealthCheckCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/util/PaginatedRequest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleImageTagsAtomicOperationUnitSpec.groovy

Second commit is the new stuff, first is the re-revert.

fix(provider/gce): Avoid blackholing Exceptions from CachingAgents.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/ApplicationService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/UpdateProcess.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

Refs pivotal-cf/cf-spinnaker-clouddriver#167

feat(provider/cf): apply health check attributes when deploying

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java

Now emits a `pooledRequestQueue.enabled` gauge indicating whether or
not the request queue is enabled on a particular instance.
1 == enabled
0 == disabled

feat(web): Support disabling request queue by dynamic property

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsInitializer.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsTest.java

feat(provider/cf): add apps manager uri to server group

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiExceptionTest.java

fix(provider/cf): stop NPE on empty error response

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/PackageData.java

fix(provider/cf): avoid NPE on incomplete package

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

@gorebala on slack did a lot of research into the k8s force cache
refresh times and found that each thread was updating the list of CRDs
using a live call. This change moves the refresh logic into a shared
parent thread (where the credentials are created), meaning the list is
shared by call caching agents, which was the original intent behind
using a memoizing supplier.

perf(provider/kubernetes): share CRD list between threads

---

build.gradle

https://nvd.nist.gov/vuln/detail/CVE-2017-5929
QOS.ch Logback before 1.2.0 has a serialization vulnerability affecting the SocketServer and ServerSocketReceiver components. 
The RemoteStreamAppenderClient class in logback-classic and the SocketNode classes in logback-classic and logback-access allow data to be deserialized over a Java Socket, via an ObjectInputStream, without validating the data beforehand. When data is received from the Socket, to be logged, it is deserialized into Java objects. An attacker can exploit this vulnerability by sending malicious, serialized Java objects over the connection to the Socket, which may result in execution of arbitrary code when those objects are deserialized.Note that although logback-core is implicated by the Logback project here, the Sonatype …

fix(security): Fix CVE-2017-5929 security issue threat level 9

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-oracle/clouddriver-oracle.gradle

related PR https://github.com/spinnaker/front50/pull/405

chore(oracle/dependency): upgrade oracle oci sdk version to 1.3.2

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsInitializer.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsTest.java

Add the option to provide the pcf metrics url for the server group
spinnaker/spinnaker#3664

feat(provider/cf): add metrics links to SG

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CloneCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java

Co-Authored-By: Joris Melchior <joris.melchior@gmail.com>
Co-Authored-By: Stu Pollock <spollock@pivotal.io>
spinnaker/spinnaker#3656

feat(provider/cf): add SG clone action

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactDownloader.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/config/ArtifactConfiguration.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverter.java

Also change constructor in CloudFoundry provider to use SafeConstructor to prevent code injection.

fix(core): Make uses of snakeyaml threadsafe

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy

Adding logs to try and figure out when this situation happens so we don't NPE.

chore(titus): add log when job is null

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java

fix(provider/cf): cloning across CF foundations fails

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateApplication.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateApplicationTest.java

Paving for changes to UI. Ensure that nullability is maintained in constructor and added test to verify.
spinnaker/spinnaker#3713

feat(provider/cf): multi buildpack push support

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java

This also simplifies the update logic so that now snapshots and deltas go through the same write to cache cycle.

fix(provider/titus): reworks streaming provider so it uses a buffer

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy

Solves https://github.com/spinnaker/spinnaker/issues/3724
@clareliguori @BrunoCarrier 
Happy to add a test case for this, but will need a bit of direction there.

fix(ecs): support multiple network binds for non-network-interfaced containers

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepository.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java

fix(provider/cf): show SG and Instance info with LoadBalancers

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

fix(provider/cf): handle error when route exists in other org/space

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java

https://github.com/spinnaker/spinnaker/issues/3804

fix(provider/kubernetes): v2 handle 0 replica scale-down

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy

fix(provider/gce): Decorate XPN resources when upserting instance

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactCredentialsRepository.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactProviderProperties.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java

* Simplified ArtifactCredentialsRepository to keep a list rather than a map
* Set account name when generating IvyArtifactAccount from MavenArtifactAccount

fix(artifacts): fixed property prefix for maven artifacts

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/ScaleCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperationTest.java

If the request is to scale down to zero, then we should treat the DOWN status as a success.
spinnaker/spinnaker#3670

fix(cf): repair scale-to-zero issue

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleAutoscalingPolicyDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy

fix(provider/gce): Adds flexibility to autoscaler upsert for scaleDown

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourcePropertyRegistry.java

This likely doesn't fix the issue where an otherwise healthy clouddriver
node stops being able to deploy registered CRDs, but does potentially
address a startup bug. However, unless spring boot is doing something
unexpected, access to the now syncronized method should never happen across
more than a single thread.
https://github.com/spinnaker/spinnaker/issues/3439

fix(provider/kubernetes): sync updates to account properties

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppengineClusterProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy

This is the same as #3244 but for 1.10.x: https://github.com/spinnaker/clouddriver/pull/3244

fix(core): cherry-pick commit #3244 into 1.10

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Cluster.java

This is the same as #3247 but for 1.10.x

fix(kubernetes): cherry-pick #3247 into 1.10.x

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java

This is the same as #3293 but for 1.10.x

fix(kubernetes): cherry-pick #3286 into 1.10.x

---

clouddriver-web/clouddriver-web.gradle

Cherry-pick the fix (https://github.com/spinnaker/clouddriver/pull/3160) into Spinnaker 1.11 release.
Related PR for front50 is https://github.com/spinnaker/front50/pull/426.

Fix missing jars release 1.11.x

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Routes.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/RouteService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/MapLoadBalancersAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/UnmapLoadBalancersAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/LoadBalancersDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/AbstractCloudFoundryLoadBalancerMappingOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/MapLoadBalancersAtomicOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/UnmapLoadBalancersAtomicOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryInstance.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/RoutesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DestroyCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/AbstractCloudFoundryAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/AbstractCloudFoundryLoadBalancerMappingOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/UnmapLoadBalancersAtomicOperationTest.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java

feat(cf): Map/Unmap SGs and LBs

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java

feat(cf): Add CF provider support to Halyard

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

For users with a lot of Kubernetes V2 accounts configured, the check of which kinds are readable takes a lot of time on startup. Parallelize this check so that clouddriver starts up faster.

fix(kubernetes/v2): Parallelize checking for omitKinds

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy

There has been some back and forth around the method used to determine
instances to enable/disable.
This PR introduces a fallback lookup based on instances tagged with the
asg name in the event that the original lookup failed.
Historically we looked images up this way but moved away due to slowness
in larger account/regions. It seems reasonable to at least try it as a
fallback rather than letting the operation fail.

fix(aws): Fallback if asg instances cannot be described

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

feat(cf): add clone SG pipeline stage

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureStorageClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureNamedAccountCredentials.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureLoadBalancerResourceTemplate.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureSecurityGroupResourceTemplate.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/validators/UpsertAzureLoadBalancerDescriptionValidatorSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/ops/DestroyAzureServerGroupAtomicOperationSpec.groovy

Issue Link: https://github.com/spinnaker/spinnaker/issues/4006

fix(provider/azure): add support for Azure US Government environment

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/ServiceInstanceService.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java

feat(cf): do not update service if unnecessary

---

build.gradle
clouddriver-azure/clouddriver-azure.gradle
clouddriver-web/clouddriver-web.gradle
gradle/init-publish.gradle
gradle/spek.gradle

https://github.com/spinnaker/spinnaker/issues/3997

fix(build): make gradle use https

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEServerGroupNameResolver.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/names/GoogleLabeledResourceNamer.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/names/GoogleLabeledResourceNamerSpec.groovy

Also fixes an NPE when applying monikers. @jervi PTAL.

fix(provider/gce): Fix seqence generation for server groups.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy

fix(provider/gce): Fix moniker recording in instance metadata.

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AbstractAppengineCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineCredentialsInitializer.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineNamedAccountCredentials.groovy

fix(appengine): add configurable caching agent interval

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverter.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverterTest.java

fix(cf): Provide error message for region case mismatch

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeployCloudFormationDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperation.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeployCloudFormationAtomicOperationConverterSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperationSpec.groovy

adds support for passing cloudformation capabilities to stack
create/update. needed if you want to create IAM roles with
as part of your stack.

feat(cloudformation): support capabilities

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

spinnaker/clouddriver#3442 inverted the check in isValidKind; fix this

fix(provider/kubernetes): Fix isValidKind

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/jenkins/JenkinsArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/jenkins/JenkinsArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/jenkins/JenkinsArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/jenkins/JenkinsProperties.java

feat(core): add jenkins artifact type

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/UpsertAzureSecurityGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy

feat(provider/azure): Enable user agent

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeleteAmazonSnapshotAtomicOperationConverter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteAmazonSnapshotDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonSnapshotAtomicOperation.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/DeleteAmazonSnapshotDescriptionValidator.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonSnapshotAtomicOperationSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java

Support for deleting snapshots that swabbie will use.

feat(amazon): delete snapshot atomic operation

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/AbstractCreateServiceInstance.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/CreateServiceInstance.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/CreateUserProvidedServiceInstance.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServiceDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperationTest.java

- Supersedes functionality whereby versioning of services
provided via tags was used to determine whether a service
should be updated
spinnaker/spinnaker#4084

feat(cf): Add Updatable flag for services

---

Dockerfile

buildDeb needs the publishing opinions from gradle/init-publish.gradle

fix(docker): fix gradle build step

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java

fix(cf): Destroy service should be idempotent

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

* Add property `instanceTags` for user defined tags
* Remove unnecessary pre-defined tags since the upper limit of tag number is 15

feat(provider/azure): Add instance tags in AzureServerGroupDescription

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryLoadBalancer.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryLoadBalancerTest.java

fix(cf): Remove "//" from routes

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java

We have to handle form-based manifest input differently for clone operations because they pass through clone logic in Orca that is common to all providers.

fix(provider/cf): Form-based manifest input for clone server group

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java

fix(cf): Clone server group sets environment variables in new server group

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy

Someone asked for this, it's perfectly reasonable to assume we'd return it.

feat(amazon): return launch config name on modify operation

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy

It appears cherry-picking can't figure out how to properly resolve imports.

fix(provider/gce): Wait on LB backend service updates. (#3532)

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/DisruptionBudget.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RatePerInterval.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RatePercentagePerInterval.java

* Support additional relocation description for disruption budget

fix(titus): Support additional relocation description for disruption budget

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Spaces.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/ServiceInstanceService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/ServiceKeyResponse.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/CreateServiceKey.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/LastOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/ServiceCredentials.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/SummaryServiceInstance.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/CreateCloudFoundryServiceKeyDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/CreateCloudFoundryServiceKeyAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/SpacesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/CreateCloudFoundryServiceKeyAtomicOperationTest.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java

feat(cf): Create Service Key

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java

Previous logic returned the last response if an exception was thrown. We should check that last response is not null before returning it, null does more harm than good. If it is a problem that we are not expecting, just throw the error up the chain. Let’s also expect timeouts and treat that as a retryable situation.

fix(cf): handle timeouts in CF api calls better

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/FunctionProvider.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/FunctionController.java

Current implemenation of /getfunctions returns a list of all the lambda functions,
but it doesn't take any request parameters to get individual functions.
I've implemented the feature by making some changes.

feat(lambda): Ability to get details of an individual function #4214

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/Keys.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/ResourceCacheData.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Organizations.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/OrganizationService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/CloudFoundryProvider.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/config/CloudFoundryProviderConfig.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/OrganizationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryCachingAgentTest.java

- for performance reasons, we introduced the caching of individual
CloudFoundryServerGroup objects
spinnaker/spinnaker#4083

feat(cf): Implement on-demand caching

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java

When clouddriver is deployed in HA mode, on-demand cache refresh request are sent to the RW clouddriver, but requests for the list of currently-pending requests are sent to the RO clouddriver.
In principle, this should not be a problem, as the pending refresh requests are stored in Redis (which both query). The problem is that each caching agent keeps a list of namespaces it should keep track of, and only returns pending results for those namespaces.
If you don't have an explicit list of namespaces to cache, clouddriver periodically calls reloadNamespaces() on each agent to update its list of namespaces. This call happens when either processing an on-demand request or as part of a regular caching cycle, so that the list of namespaces in each agent stays up-to-date and all namespaces are …

fix(provider/kubernetes): Fix cache refresh timeout for HA clouddriver

---

clouddriver-web/clouddriver-web.gradle

Prereq for spinnaker/kork#273 merge

chore(dependencies): ensure direct dependency on kork-secrets-aws

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Job.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/AvailabilityPercentageLimit.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/ContainerHealthProvider.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/HourlyTimeWindow.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RatePerInterval.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RatePercentagePerHour.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RatePercentagePerInterval.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RateUnlimited.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/RelocationLimit.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/SelfManaged.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/TimeWindow.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/disruption/UnhealthyTasksLimit.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroup.groovy

Lombok-ing, plus marshaling from gRPC to our internal domain classes

feat(titus): enable reads of job disruption budgets

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java

Fixes spinnaker/spinnaker#4371

fix(ecs): Retry on ECS service eventual consistency

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy

If there's no disruption budget specified, and no migration policy, send a default disruption budget to Titus.

feat(titus): use default disruption budget if none supplied

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java

fix(cf): previously unhandled exception from bad application state

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy

We want to ignore the "systemDefault".

fix(titus): ignore migration policy if set to "systemDefault"

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy

fix(docker): Added missing insecureRegistry property

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationService.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServergroupDescriptionValidatorSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationServiceSpec.groovy

Also fixes issues related to ECS task platform health information
Fixes spinnaker/spinnaker#2912
Fixes spinnaker/spinnaker#3507

feat(ecs): Support non-load-balanced services

---

clouddriver-core/clouddriver-core.gradle

boot2 regression, adding the library back to facilitate logging

fix(logging): add logstash-logback-encoder to runtimeClasspath

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-oracle/clouddriver-oracle.gradle
clouddriver-web/clouddriver-web.gradle

cc @ezimanyi @shihchang @guoyongzhang

chore(clouddriver/oracle): Get the Oracle API jar from Maven.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java

Now that Igor can properly construct an Artifactory link, we put it on the server group for use later in Deck.

fix(cf): use the artifactory link now that we construct it correctly

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/ServerGroupMetaDataEnvVar.java

Also include pipeline ID on server group and remove backwards compatibility for version on older existing server groups.

feature(cf): use trigger for build metadata

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java

The default interval function for resilience4j is a fixed 500ms per attempt.

fix(cf): Exponentially back off when Cloud Foundry is unavailable

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizer.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizerTest.java

Otherwise, the addition of a CF account deletes all other accounts.

fix(cf): Filter by provider type when deciding which accounts to delete

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Also improve unit tests around CreateService calls
This will need to be cherry-picked into 1.14
Fixes spinnaker/spinnaker#4475

fix(ecs): Don't specify load balancer role for non-load-balanced service

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonSnapshotAtomicOperation.java

- Update error message with region and account details

fix(misc): Update error message with region and account details

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/DestroyTitusJobAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DestroyTitusJobDescription.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DestroyTitusJobAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/DestroyTitusJobDescriptionValidator.groovy

we should be able to cancel a titus job with just the id

feat(titus): delete job with just id

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleNamedImageLookupController.java

Addresses spinnaker/spinnaker#4510
Per the above issue and comments on [this Slack conversation](https://spinnakerteam.slack.com/archives/C091CCWRJ/p1560262702208300), some Spinnaker users have tens of thousands of images per account. This currently results in a nearly unusable Deploy modal UI, and failing Find Image stages.
Before:
- Fetch all images from all accounts from the cache, even if the `account` param is specified.
- Call `matchesTagFilter` and `getTagFilter` for every image fetched from the cache, even if no tag filters are specified.
After:
- If `account` param is specified, fetch only images of that account from the cache.
- Call `getTagFilter` once per request. Only call `matchesTagFilter` once per image if there is a tag filter on the request.

perf(google): improve performance of gce image fetching

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

Background:
Add a new feature to mount data disk to server group. Please also help to review the related deck PR(https://github.com/spinnaker/deck/pull/7116).

feat(provider/azure): Enable data disk for server group

---

build.gradle
clouddriver-bom/clouddriver-bom.gradle
settings.gradle

This simplifies dependency resolution downstream

feat(clouddriver-bom): publish clouddriver-bom

---

gradle.properties

- Includes commits listed [here](https://github.com/spinnaker/fiat/releases/tag/v1.4.0).

chore(deps): bump fiat to 1.4.0

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java

based on feedback from titus team, adjust page size for titus job/tasks
requests to 1k

fix(titus): adjust page size for titus queries

---

clouddriver-alicloud/README.md
clouddriver-alicloud/clouddriver-alicloud.gradle
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/AliCloudConfigurationProperties.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/AliCloudOperation.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/AliCloudProvider.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudCluster.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudInstance.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudKeyPair.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudLoadBalancer.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudLoadBalancerType.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudSecurityGroup.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudSecurityGroupRule.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudSecurityGroupSummary.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudServerGroup.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/AliCloudSubnet.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/Listener.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/model/alienum/ListenerType.java
clouddriver-alicloud/src/main/java/com/netflix/spinnaker/config/AliCloudConfiguration.java
settings.gradle

This is the core set of features needed to make alibaba cloud usable as a server group and load balancer provider in Spinnaker.

feat(alibabacloud): add a new provider's model definition

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServergroupDescriptionValidatorSpec.groovy

Addresses https://github.com/spinnaker/spinnaker/issues/4635
NOTE: The intention is to cherry-pick this onto `1.15.x` as it addresses a problem encountered by a user of that release branch.
(CC @clareliguori )

fix(ecs): Add validation for loadBalancedContainer when using artifact

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/AgentDataType.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.java

just a tiny semi-pointless cleanup

refactor(cats): Make the AgentDataType constructor private

---

clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaService.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/events.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/models/Saga.kt

- additional events & adding behavior to the Saga model

chore(events): Adding internal events

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/job/KubernetesRunJobOperationDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobOperation.java

adds support for artifacts in the v2 run job implementation

feat(provider/k8s): support artifacts in v2 runjob

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/cache/DefaultCacheDataBuilder.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy

Reverts spinnaker/clouddriver#3926

fix(docker): REVERT - Use parallel streams for caching docker images

---

clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaService.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/controllers/SagaController.kt

Somehow forgot to add logs to `SagaService`...

chore(saga): Adding more visibility to Sagas

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReport.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReportBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy

per https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/apply_ri.html

fix(aws): Reservation API support for `metal` instance types

---

clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/persistence/InMemoryEventRepository.kt

Changing internal event map to `ConcurrentHashMap` to get around some concurrent modification issues. Also refactored a bit of the save method to get rid of some `!!`s.

fix(event): Fixing some concurrency issues in event store

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java

Artifact metadata was missing from the new server group when it was created via a clone stage. We now query the source server group (if there is one) and add the metadata to the new server group (stored as env vars).

fix(cf): fix artifact metadata for clone stage

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/BatchComputeRequest.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/BatchComputeRequestImpl.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/BatchPaginatedComputeRequestImpl.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/GetFirstBatchComputeRequest.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/GoogleComputeApiFactory.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/PaginatedComputeRequestImpl.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/StatefullyUpdateBootImageAtomicOperation.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstances.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/BatchComputeRequestImplTest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/BatchPaginatedComputeRequestImplTest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/FakeBatchComputeRequest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/FakeGoogleComputeRequest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/GetFirstBatchComputeRequestTest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/PaginatedComputeRequestImplTest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/StatefullyUpdateBootImageAtomicOperationTest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgentTest.java

I think this is everything needed, now just one big PR to convert GoogleZonalServerGroupCachingAgent in one fell swoop.

refactor(gce): More plumbing work for the caching code

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessorSpec.groovy

Re-opening with use of the kork lib.

fix(core): Create better task exception summaries

---

clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindSpec.groovy

Test that we properly serialize and deserialize kubernetes kinds to/from their string representation.

test(kubernetes): Add tests of KubernetesKind serialization

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java

We're now logging the KubernetesKindProperties which doesn't have a nice string representation, so is not helpful in the logs.
While fixing the log, it's actually easier if canReadKind just takes in the KubernetesKind and looks up the properties in the registry itself.

fix(kubernetes): Fix log message when checking readable kinds

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/AbstractEcsAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DisableServiceAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/EnableServiceAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/ResizeServiceAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CommonAtomicOperation.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DisableServiceAtomicOperationSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/EnableServiceAtomicOperationSpec.groovy

Fixes spinnaker/spinnaker#4707
Depends on spinnaker/kork#371 before this can be merged

feat(ecs): suspend/resume autoscaling during disable/enable service operations

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTask.kt

fix(sql): Remove accidental exception throw

---

clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/seekers/SagaCommandEventSeeker.kt

fix(saga): Fix off-by-one error in sagaflow seeker

---

clouddriver-titus/clouddriver-titus.gradle
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/actions/PrepareTitusDeployActionSpec.groovy
clouddriver-titus/src/test/resources/mimicker-titus.yml

I wanted to have a concrete example to show for the https://github.com/spinnaker/kork/pull/373 work. Surprisingly, there weren't any changes I needed to make as a result. The tests do likely need to get more coverage regardless.

feat(titus): Mimicker property testing

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java

What happens when you try to fix a Lombok / Jackson interop issue "the right way" multiple times and fail each time? Get rid of Lombok and call it a day.

fix(titus): Scorched earth removing Lombok for Jackson compat

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/CloneTitusServerGroupAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/RunTitusJobAtomicOperation.groovy

fix(saga-npe): Set sagaContext on DeployDescription object where atomic operations operate on TitusDeployHandler

---

automerge.yml

Testing the waters with an automerge capability provided by https://github.com/marketplace/actions/merge-pull-requests
To try it out, add the `ready to merge` label and your PR will be merged automatically after checks pass.

chore(build): Update and rename .github/workflows/main.yml to automerge.yml

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/ExceptionClassifier.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessorSpec.groovy

~~No tests exist for this class, maybe I should write a test before we merge this.~~
Wrote a test.

feat(dynamicRetry): Pull comma-delimited list of non-retryable exceptions from dynamic config store

---

clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerSpec.groovy
gradle.properties

Fixes serialization issue in fiat-api version mismatch with new values in Authorizations enum

fix(fiat-api): fiatVersion 1.7.1

---

.github/workflows/pr.yml

feat(*): Try removing gradle-command-action

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtils.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiExceptionTest.java

Additional logging when making outgoing calls to cf

feat(cf): increase logging for cf to better detect fails

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/Keys.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtils.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java

general clean up.
* remove unused code
* fix spelling mistake
* add an additional constructor to `CloudFoundryApiException`

refactor(cf): removed unused code, fix spelling and etc

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CloneCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServiceDescription.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java

refactor the code to support SpEL evaluations

feat(cf): add SpEL support for cf manifests

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonSecurityGroup.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy

- Add `tags` field to `AmazonSecurityGroup` model

fix(securityGroup): Add tags field to AmazonSecurityGroup model

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy

Reverts part of spinnaker/clouddriver#4184

fix(revert): Fixes method signature issue

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java

Fixes https://github.com/spinnaker/spinnaker/issues/5203
cc @allisaurus

fix(ecs): reject task def artifact if it contains unknown properties

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentSchedulerSpec.groovy
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/AbstractCloudFoundryCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/agent/CleanupPendingOnDemandCachesAgent.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgentTest.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgentTest.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgentTest.java
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/TaskMapper.kt
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
gradle.properties

See https://github.com/spinnaker/spinnaker/issues/5134
Dependent on https://github.com/spinnaker/kork/pull/419 for a Spring Boot dependency upgrade

chore(dependencies): Upgrade Spring Boot to 2.2.1

---

clouddriver-sql/clouddriver-sql.gradle
clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepositoryTest.kt

See https://github.com/spinnaker/kork/pull/442

chore(testfix): liquibase/jackson incompatibility

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/securitygroups/IpRangeRule.groovy

- Description for IPRangeRules

feat(IPRangeRuleDescription): Description for IPRangeRules

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationService.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServergroupDescriptionValidatorSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCacheSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationServiceSpec.groovy

Fixes: https://github.com/spinnaker/spinnaker/issues/4788
Should be merged in with: https://github.com/spinnaker/deck/pull/7692/

feat(provider/ecs): add support for services with multiple target groups

---

.github/workflows/pr.yml

notes: https://github.com/actions/checkout/blob/master/README.md

chore(build): upgrade to GitHub Actions checkout@v2

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiAdapter.groovy
clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy

You know what they say about those who forget history: https://github.com/spinnaker/clouddriver/pull/3805

fix(kubernetes): update api adaptor signatures to match java client v7

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java

Until now the artifact.version value, which contains the git reference,
was required to be a branch name. These changes no longer assume version
is a branch and allow the caller to pass in commit SHA as well.

feat(artifacts/gitRepo): Allow version value to be branch or commit SHA

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Routes.java

fix(cf): reduce results per page requests to lower timeout frequency

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Routes.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizer.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/RoutesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizerTest.java

This was an ask from a current spinnaker user to help with performance

fix(cf): allow results per page to be configurable

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy

- Revert to old logic , partial revert of #4270

fix(aws): Revert the IP Rule diff logic changes

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperation.groovy

We noticed that there are is a small percentage of DeleteASG operations that fail because they fail to delete the launch config
due to amazon returning `Cannot delete launch configuration foo-quaz` because it is attached to AutoScalingGroup foo-quax`
This adds a retry in hopes that we can retry out of this situation.

fix(AWS): Add retries around deleting launch configs

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesDeploymentCachingAgent.groovy

* Fix typo `deployemnts` to `deployments`.

Fix typo in Kubernetes Deployment load message

---

.github/workflows/pr.yml

chore(builds): Do GitHub Actions CI builds on master and release branches

---

clouddriver-tencentcloud/clouddriver-tencentcloud.gradle
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/TencentCloudOperation.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/TencentCloudProvider.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/cache/Keys.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/config/TencentCloudConfigurationProperties.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/model/TencentCloudBasicResource.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/names/TencentCloudBasicResourceNamer.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/security/TencentCloudCredentials.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/security/TencentCloudCredentialsInitializer.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/security/TencentCloudNamedAccountCredentials.java
clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/config/TencentCloudConfiguration.java
clouddriver-tencentcloud/src/test/java/com/netflix/spinnaker/clouddriver/tencentcloud/cache/KeysTest.java
settings.gradle

Add initial implementation for TencentCloud provider
Tencent Cloud Provider Proposal:
spinnaker/governance#79

feat(provider/tencentcloud): Add initial implementation for TencentCloud provider

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/PrepareTitusDeploy.java

- Adding conditional logic to skip security group validation when a label is set , used as a workaround when cross account resource needs to be used

fix(titus): Relax titus security group validation

---

clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/DeployConfiguration.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessorSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusClientAuthenticationUtil.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/DataControllerSpec.groovy
gradle.properties

Fix the breaking changes and use the new context access pattern that does not involve direct MDC access

fix(context): update to latest kork

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Should fix IAM roles which include path names.  See
https://github.com/spinnaker/spinnaker/issues/5430

fix(ecs): ECS handling of IAM Roles with a path

---

clouddriver-huaweicloud/clouddriver-huaweicloud.gradle
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/HuaweiCloudUtils.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/exception/HuaweiCloudException.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSecurityGroup.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSecurityGroupCacheData.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSecurityGroupSummary.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/AbstractHuaweiCloudCachingAgent.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/AbstractOnDemandCachingAgent.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudSecurityGroupCachingAgent.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSecurityGroupProvider.java
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudSecurityGroupCachingAgentSpec.groovy
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSecurityGroupProviderSpec.groovy

This pr implements the cache agent of security group. The cloud provider proposal is spinnaker/community#17

feat(huaweicloud): implement cache agent of security group

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerClassicDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy

- Added ability to define session stickiness for listeners

feat(aws): Adding support for session stickiness for clbs upsert op

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeleteAmazonLaunchConfigurationAtomicOperationConverter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteAmazonLaunchConfigurationDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonLaunchConfigurationAtomicOperation.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java

- added launch config delete operation

feat(provider/aws): Adding delete launch config operation

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java

* Added more of `Applications.all()` code in the ForkJoinPool task to enable more parallel processing with a configurable thread count.
* Added some more debug logging.

fix(cf): More parallel processing in the caching agent

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy

No one outside of Netflix uses reservation reports, and it apparently causes a lot of errors / noise in OSS deployments.

chore(reservations): Disable reservation reports by default

---

clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/CacheResultBuilder.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudNetwork.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/HuaweiCloudInfrastructureProvider.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudNetworkCachingAgent.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/config/HuaweiCloudInfrastructureProviderConfig.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudNetworkProvider.java
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudNetworkCachingAgentSpec.groovy
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudNetworkProviderSpec.groovy

This pr implements the cache agent of netwok. The cloud provider proposal is spinnaker/governance#17

feat(huaweicloud): implement cache agent of network

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/EcsServerGroupNameResolver.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/EcsServerGroupNameResolverSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/5476

feat(ecs): Check for draining services for new server group names

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/SubnetSelector.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServergroupDescriptionValidatorSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/SubnetSelectorSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/5467

feat(ecs): Filter subnets by availability zone

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/5430 for 1.17 
due to not being able to cherry pick https://github.com/spinnaker/clouddriver/pull/4321#issuecomment-585415781
@clareliguori pretty please ;)

fix(ecs): ECS IAM Path role fix for 1.17

---

clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudInstanceType.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/HuaweiCloudInfrastructureProvider.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudInstanceTypeCachingAgent.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/config/HuaweiCloudInfrastructureProviderConfig.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudInstanceTypeProvider.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/security/HuaweiCloudNamedAccountCredentials.java
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudInstanceTypeCachingAgentSpec.groovy
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudInstanceTypeProviderSpec.groovy

This pr implements the cache agent of instance type. The cloud provider proposal is spinnaker/governance#17

feat(huaweicloud): implement cache agent of instance type

---

.gitignore
clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
clouddriver-web/clouddriver-web.gradle
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/MainSpec.java

this allows loading of plugins like other spin services

feat(plugins): add plugin dep and config

---

clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/config/EurekaProviderConfiguration.groovy

fix(config): Fix OkHttpClientConfiguration instantiation

---

clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/controller/HuaweiCloudImageController.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/controller/ImageProvider.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudImage.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/HuaweiCloudInfrastructureProvider.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudImageCachingAgent.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/config/HuaweiCloudInfrastructureProviderConfig.java
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudImageProvider.java
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudImageCachingAgentSpec.groovy
clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudImageProviderSpec.groovy

This pr implements the cache agent of image. The cloud provider proposal is spinnaker/governance#17

feat(huaweicloud): implement cache agent of image

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepository.kt

Log separate metric on event save failures

fix(sagas): Fix SqlEventRepository metrics

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java

potential fix or remediation for https://github.com/spinnaker/spinnaker/issues/5551
Prior to 1.19.x, `TaskHealthCachingAgent` was calling AWS ELB to describe target (task) health, and evicting services and task definitions when an associated target health was not found. 
However, now this agent is no longer calling AWS ELB directly, so it's not an authority on the staleness of these resources.
Deployed this change locally, deployed successfully.

fix(ecs): Remove extra evictions from TaskHealthCachingAgent

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java

fix(elasticsearch): Fixing entity type case

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java

Not a 'fix' per se, but added to help troubleshoot issues with "waiting for up instance" like those reported in https://github.com/spinnaker/spinnaker/issues/5528 and https://github.com/spinnaker/spinnaker/issues/5551

fix(ecs): Improve debug messaging for task health

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java

I somehow missed that keyword when adding that field...

refactor(kubernetes): Add final to immutable field

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java

A call to `/credentials` (even without `?expand=true`) currently results in a potentially expensive call to get spaces in the CF account. This uses the same strategy that `KubernetesV2Credentials`  uses for namespaces.

fix(provider/cf): Don't get spaces on every call to /credentials

---

build.gradle
gradle.properties

Resolves the build failure here -- https://github.com/spinnaker/clouddriver/pull/4445

chore(dependencies): bump korkVersion and kotlinVersion

---

cats/cats-sql/cats-sql.gradle
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNames.kt
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlCacheSpec.groovy
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskCleanupAgent.kt

Merge sql fixes from master into 1.17

fix(sql): Cherry pick jooq changes 

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Task.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy

- revert this change in #4513 , to unblock

fix(titus): Revert ipv6 changes

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerGroup.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLaunchTemplateCachingAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/data/KeysSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLaunchTemplateCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProviderSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/provider/agent/Namespace.groovy

- Added new Launch template caching agent (feature flagged)
- Updated cluster provider & agent to handle server groups with templates

feat(aws): Adding support for caching ec2 launch templates

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

- fixed a bug where the launch config/template was not read correctly
- also added null checks on setting build info and image

fix(aws): fix bug in setting launch config/template on cluster

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

fix(aws): Fixing npe on setting launch settings & build info

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProvider.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProviderSpec.groovy

chore(ecs): add unit test, debug msgs to application load balancers

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProviderSpec.groovy

- fixed setting build info and image while translating cluster details
- added test
additional: including launch templates images. (accidentally left out)

fix(aws): Fixing missing build info on cluster

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy

* use e.toString() instead of e.errorMessage. The message can be null and then we don't even know what the exception was.
* when we get an exception, log it

chore(error-handling): log errors in LoadBalancerV2UpsertHandler

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/DeleteTitusScalingPolicy.java

- Fix Titus Scaling policy delete action NPE

fix(titus): Fix Titus Scaling policy delete action

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java

Prior to this change, CF server group caching agent was updating its internal cache in a `ForkJoinPool` without waiting for the result. The agent was then saving stale data in the cache. Similarly, force cache refresh was not doing an actual refresh if the server group had already been loaded. This could lead to stale data overriding good data in the case of force cache running on a different instance of Clouddriver.
This is the first in a series of changes to fix CF provider caching. This one is limited so it can be back-ported.

fix(provider/cf): Ensure up-to-date data in server group caching agent and force cache

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy

A manual cherry-pick of #4559.

fix(provider/google): Fix support for newer custom VM types

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/RetrofitConfig.groovy
clouddriver-web/src/test/resources/application.properties

- Remove OkHttp2 client and move to the new provider impl.

fix(misc): Moving to the new client provider implementation.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

- adds support for creating an asg using a launch template

feat(aws): Support launch templates in createServerGroup operation

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/JobDescription.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java

Set cmd when not empty for titus jobs

fix(titus): Set cmd when not empty for titus jobs

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy

- swap application and subnetType typo

fix(aws): Fixing parameters for setting security groups for launch templates

---

clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java

The recent change to the artifact handling in cloudfoundry deploy may have caused a regression. It's still not clear to me exactly what the change is, but adding this (currently passing) unit test as a start so that hopefully we can make it fail and track the bug.

test(provider/cf): Add test on cf deploy converter

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java

chore(ecs): Clarify network check in task health agent

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/UserDataProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy

- properly set user data during create/clone server group for launch templates

feat(aws): Handling userData for launch template backed ASGs

---

clouddriver-ecs/README.md

Update role information with current requirements and add docs link

chore(ecs): Update role info in README

---

clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy

The elasticsearch tests are failing intermittently because there are numerous race conditions between when index refreshes cause a mutating operation to be visible, and when we assert that the operation is visible.
Currently the test cluster is set up to reindex every 1s, and we are using sleep statements and retries to ensure we wait that long before failing a test. In addition to making these tests slow, there are intermittent failures (particularly under high load) when we fail before the re-index has occurred.
Let's make this deterministic as follows:
(1) Manually refresh the index before verifying the status of an operation.
(2) Set the refresh_interval to -1, which means never automatically refresh. This ensures that tests will always fail if we forget to invoke the manual refresh …

fix(elasticsearch): Fix race conditions in elasticsearch tests

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/UserDataProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

chore(aws): Adding iamRole and imageId to userData request for launch templates

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationCachingAgent.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationCachingAgentSpec.groovy

We recently faced an issue where Clouddriver wasn't retrieving all the stacks
for an account.
Going though all the pages returned by describeStacks fixed our problem. I did
it for listChangeSets too.

fix(aws/cloudformation): Paginate through stacks and changesets

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusExceptionHandler.java

fix(saga): Retry INVALID_ARGUMENT exception when message is Titus assume IAM role error

---

clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueTest.java

This reverts commit 22feb2a866f96606ebe19be61369bd7a4a155eb6.
I think this might be breaking the build?

fix(test): reverts (#4777) Fix intermittent timeout in PooledRequestQueueTest

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/UpsertTitusScalingPolicyDescription.groovy

Additional logging around Titus SP upsert operation

fix(titus): Additional logging around Titus SP upsert operation

---

.github/workflows/gradle-wrapper-validation.yml

enable Gradle wrapper validation
https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action

chore: enable Gradle wrapper validation

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DefaultDeployHandlerRegistry.java

I'm not sure what is causing an NPE in the integration tests, so I just null-checked everything. 😬

fix(core): Brute-force fix NPE in DeployHandlerRegistry

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/DeployConfiguration.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DefaultDeployHandlerRegistry.java

We'll get there one of these days.

fix(core): Fix autowiring of DefaultDeployHandlerRegistry

---

clouddriver-elasticsearch-aws/clouddriver-elasticsearch-aws.gradle
clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
clouddriver-web/clouddriver-web.gradle

In my haste (in https://github.com/spinnaker/clouddriver/pull/4842) I missed a few spots.

fix(build): Remove constraints on elasticsearch and jest in clouddriver-web

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2SearchProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestLabeler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesIngressHandler.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverterTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java

refactor(kubernetes): Fix unused variable error prone warnings and enable unused variable warnings moving forward.

refactor(kubernetes): Fix unused variable error prone warnings and enable unused variable warnings moving forward.

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesModelUtil.java

refactor(kubernetes): Fix unnecessary parentheses error prone warnings and enable unnecessary parentheses warnings moving forward

refactor(kubernetes): Fix unnecessary parentheses error prone warnings and enable unnecessary parentheses warnings moving forward

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt

- Updated to use the same objectMapper used elsewhere

chore(sql): Injecting objectMapper instead of creating a new instance

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy

fix(cache): fix the CacheController

---

clouddriver-aws/clouddriver-aws.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/ModifyServerGroupLaunchTemplateAtomicOperationConverter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AbstractAmazonCredentialsDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyServerGroupLaunchTemplateDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyServerGroupLaunchTemplateAtomicOperation.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/ModifyServerGroupLaunchTemplate.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareModifyServerGroupLaunchTemplate.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/UpdateAutoScalingGroup.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/ModifyServerGroupLaunchTemplateValidator.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/config/AwsConfiguration.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareModifyServerGroupLaunchTemplateSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java
clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/config/EventConfiguration.kt

- modify server group launch template saga support
- this operation will be used by rollingpush and the editing of asg's security groups

feat(aws): Adding support for update asg launch template

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/converters/PublishLambdaFunctionVersionAtomicOperationConverter.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/PublishLambdaFunctionVersionDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/PublishLambdaAtomicOperation.java

(fix/aws) : add missing atomic operation for lambda publish version

(fix/aws) : add missing atomic operation for lambda publish version

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/cache/client/LambdaCacheClient.java

fix (aws/lambda):  patch broken translation of uuid fields by object mapper

fix (aws/lambda):  patch broken translation of uuid fields by object mapper

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/FunctionController.java

fix (aws): Filter out null values in list of lambda providers

fix (aws): Filter out null values in list of lambda providers

---

clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-core/clouddriver-core.gradle
clouddriver-google/clouddriver-google.gradle
clouddriver-kubernetes/clouddriver-kubernetes.gradle
gradle.properties

-- Adding dependencies required for config server.

fix(misc): add deps required for config server lib

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeleteAmazonLaunchTemplateAtomicOperationConverter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteAmazonLaunchTemplateDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteLaunchTemplateAtomicOperation.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperation.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java

- adding support for lt deletion
- updated to delete lt on asg deletion

feat(aws): Adding delete launch template operation

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/config/AwsConfiguration.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy

- added a method to help with lt rollout
- supports application and account-region allow lists
- overridable per request

chore(aws): Adding launch template flag for rollout

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy

- handle empty list of allowed accounts/regions

fix(aws): Fixing launch template flag

---

clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgentTest.kt
clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepositoryTest.kt

Tests were failing on repeat runs.

fix(sql): Test pollution

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/AbstractEnableDisableAtomicOperation.groovy

- Adding details to the kato task to surface better error message to user.

fix(titus): Update Kato task status to surface better error message

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgent.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlEventCleanupAgentConfigProperties.kt
clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgentTest.kt

feat(sql): Add additional dynamic config for event cleanup agent

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/DeployConfiguration.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessorSpec.groovy
gradle.properties

Depends on: https://github.com/spinnaker/kork/pull/788

feat(extensibility): Use ExceptionSummaryService in DefaultOrchestrationProcessor to provide custom user messages on exceptions

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/CreateLambdaFunctionConfigurationDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/CreateLambdaFunctionDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/CreateLambdaAtomicOperation.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/UpdateLambdaConfigurationAtomicOperation.java

fix (aws/lambda) : add support for adding layers to lambda functions

fix (aws/lambda): add support for adding layers to lambda functions

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/converters/PutLambdaProvisionedConcurrencyAtomicOperationConverter.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/converters/PutLambdaReservedConcurrencyAtomicOperationConverter.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/PutLambdaProvisionedConcurrencyDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/PutLambdaReservedConcurrencyDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/PutLambdaProvisionedConcurrencyAtomicOperation.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/PutLambdaReservedConcurrencyAtomicOperation.java

fix (aws/lambda) : add atomic operations for updating lambda function concurrency

fix(aws/lambda): add atomic operations for updating lambda function concurrency

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/UpsertLambdaFunctionEventMappingDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/UpsertLambdaEventSourceAtomicOperation.java

fix(aws/lambda): Support upsert of  event source configurations in lambda aliases

fix(aws/lambda): Support upsert of  event source configurations in lambda aliases

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy

- made flag to consider app:account:test
- added an exclude list for apps

refactor(aws): Updating launch template rollout flag

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/SubmitTitusJob.java

* avoid the (probably accidental) bitwise xor in Thread.sleep
* in fact, don't call Thread.sleep at all, this is in a retry block
* we don't need no retryCount, retries are handled by RetrySupport
* rely on SpinnakerException with setRetryable(false) to stop retries

fix(titus): simplify retry logic in SubmitTitusJob

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/InvokeLambdaFunctionOutputDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/InvokeLambdaAtomicOperation.java

fix (aws/lambda) : Send back results from invoke lambda atomic operation

fix (aws/lambda) : Send back results from invoke lambda atomic operation

---

clouddriver-lambda/clouddriver-lambda.gradle
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/InvokeLambdaAtomicOperationTest.java

fix (aws/lambda) : Start a dummy test class for lambda.

test(aws/lambda) : Start a dummy test class for lambda.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java

Reusing existing methods to build server group names.

fix(cf): Build sg names using existing methods

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/DetachTitusTasks.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/ResizeTitusJob.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/TerminateTitusTasks.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/DetachTitusInstancesAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/ResizeTitusServerGroupAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/TerminateTitusInstancesAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DetachTitusInstancesDescription.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DetachTitusInstancesAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/ResizeTitusServerGroupAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/TerminateTitusInstancesAtomicOperation.groovy

* `detachInstances`
* `resizeServerGroup`
* `terminateInstances`
I opted to use Titus terminology when naming the actions (Tasks vs Instances and
Job vs Server Group).

feat(titus): Converted a few more Titus operations to sagas

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

Refactored LaunchTemplateService
- extracted redundant code into private methods
- made private methods private
- made the 2 methods of building launch template uniform
Kind of a prerequisite for addressing comments in https://github.com/spinnaker/clouddriver/pull/5016/files

refactor(aws): Refactored LaunchTemplateService

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgent.java

When lambda was being read in from aws, event configurations attached to the lambda function were being added to the local cache, but event configurations for individual aliases within that lambda were not being added. This PR fixes that.

 fix(aws/lambda): Load event configurations for all aliases when reading in lambda

---

clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProviderSpec.groovy

This is a follow up to https://github.com/spinnaker/clouddriver/pull/5051 to add unit tests

chore(aws lbs): Add unit test for AmazonLoadBalancerProvider

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLaunchTemplateCachingAgent.java

A debug message will be logged but the caching agent will otherwise complete.

fix(aws): Not finding a latest version is no longer considered fatal

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperation.groovy

Fixing `deleteLaunchSetting` to catch not found errors for launch configs and launch templates separately.

fix(aws): Catch not found errors in destroyASGAtomicOperation

---

clouddriver-ecs/src/integration/README.md

chore(test/ecs): Update integration README

---

clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepositoryTest.kt

fix import to use the actual Jackson annotation

fix(sql/test): Use Jackson's real annotation

---

clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/config/EurekaProviderConfiguration.groovy

- OkHttpMetricsInterceptor constructor changed in a kork bump - this makes things work

fix(*): Pass OkHttpMetricsInterceptorProperties to OkHttpMetricsInterceptor constructor

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy

Also added a `describeSecurityGroups()` to try and ensure we're able to get a consistent
read after write.
We're battling a bit of eventual consistency around security groups.

fix(aws): Corrected the retry behavior in `createSecurityGroup`

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/config/CloudFoundryProviderConfig.java

Use credentials type configuration to use strict typing on credentials sources.

refactor(cloudfoundry): use CredentialsType

---

CODEOWNERS

I'll be moving to work on different projects, so remove me as a code owner of these two modules.

chore(core): Remove ezimanyi from CODEOWNERS

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlTableMetricsAgent.kt
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlCacheSpec.groovy
cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgentTest.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskCleanupAgent.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepository.kt
gradle.properties

Some minor code changes are required for JOOQ 3.14.x
Fixes #5162

Fix JOOQ upgrade in Kork

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/SubnetSelector.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServergroupDescriptionValidatorSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/SubnetSelectorSpec.groovy

Add support for multiple subnet types in the ECS Provider. 
This change needs to be merged in prior to https://github.com/spinnaker/deck/pull/8724
Closes: https://github.com/spinnaker/spinnaker/issues/6097

feat(ecs): support selecting multiple subnet types

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.java

fixes https://github.com/spinnaker/spinnaker/issues/6064

fix(aws): Support china and rest-of-world pricing hosts

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactCredentialsRepository.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactDownloader.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactDownloaderTest.java

Fix the credentials type vs artifact type.

fix(artifacts): Get credentials supporting artifact type

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

The API is effectively a pass through.

feat(titus): Preliminary support for configuring placement and license details on launch templates

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DisableServiceAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DisableServiceAtomicOperationSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/6222
Previously, "DisableServiceAtomicOperation" would always call `RegisterScalableTarget` to suspend app autoscaling on the service. However, if the server group is already disabled, this call re-registers the scalable target which prompts the ECS service to be updated with the existing `MinCapacity` as the `DesiredCount` - which then causes a scale-out action (ECS tries to launch that number of tasks).
Since disabling the server group is done prior to deletion, destroying a disabled server group means Spinnaker will try to "re-disable" it before deletion and this seemed to be causing the problem. This change adds a check in the "disable" operation which skips re-registering the scalable target if scaling is already suspended. 
**1. …

fix(ecs): check for already suspended autoscaling on disable service op

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

Fixed bug to use spotMaxPrice conditionally

fix(aws): Fixed bug to use spotMaxPrice conditionally

---

clouddriver-web/config/clouddriver.yml

adding commented config to indicate format for launch-templates

config(aws): adding commented config to indicate format for launch-templates

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/BasicAmazonDeployDescriptionValidator.groovy

adding validation warnings for recently added launch template features

fix(aws): adding validation warnings for recently added launch template features

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Routes.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/RoutesTest.java

fix(cloudfoundry): Fixes issue with URI not being recognized.
The URL not being picked by the regex has a `/v1.0` path. These changes handle it.

fix(cloudfoundry): Fixes issue with URI not being recognized.

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

resolves https://github.com/spinnaker/spinnaker/issues/6137

feat(provider/azure): Support doNotRunExtensionsOnOverprovisionedVMs

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelper.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgBuilder.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

* Adding missed legacyUdf parameter in LaunchTemplateService 
* Fixing comparison of health check type in AsgBuilder
* Additional logging to indicate security groups resolution
Discovered these while writing integ tests (PR will be out after this is merged in)

fix(aws): minor bug fixes and logging additions

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/FeaturesController.groovy

We should be able to support beans that are created in `@Configuration` classes and are not
an `@AtomicOperation`.

fix(web): Fix NPE in `FeaturesController` for operations that are not an `@AtomicOperation` or `@Component`

---

Dockerfile.slim
clouddriver-artifacts/src/integration/java/com/netflix/spinnaker/clouddriver/artifacts/GitRepoTest.java
clouddriver-artifacts/src/integration/java/com/netflix/spinnaker/clouddriver/artifacts/utils/GiteaContainer.java
clouddriver-artifacts/src/integration/resources/git-wrapper.sh
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitJobExecutor.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java

Manual backport of https://github.com/spinnaker/clouddriver/pull/5291 solving merge conflicts.

fix(gitrepo): Support for SHA references (#5291)

---

clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationConverter.java
clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/OperationDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AllowLaunchDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/AzureResourceOpsDescription.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/NoopAtomicOperationConverter.groovy
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DefaultDescriptionAuthorizer.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DeployDescription.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationDescriptionPreProcessor.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/OperationsService.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/AnnotationsBasedAtomicOperationsRegistrySpec.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsServiceSpec.groovy
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/DeleteEntityTagsDescription.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/converter/NoOpOracleAtomicOperationConverter.groovy
clouddriver-security/src/main/java/com/netflix/spinnaker/clouddriver/security/resources/AccountNameable.java
clouddriver-security/src/main/java/com/netflix/spinnaker/clouddriver/security/resources/ApplicationNameable.java
clouddriver-security/src/main/java/com/netflix/spinnaker/clouddriver/security/resources/NonCredentialed.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/FeaturesControllerSpec.groovy
clouddriver-yandex/src/test/java/com/netflix/spinnaker/clouddriver/yandex/deploy/TestCredentialSupport.java

Also, add some stronger generics.

refactor(api): Add a marker interface that could be expanded eventually for AtomicOperation inputs

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/model/view/ClusterViewModelPostProcessor.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/model/view/ModelObjectViewModelPostProcessor.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/model/view/ServerGroupViewModelPostProcessor.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

In the future full java conversion can be done but it will require additional changes so I want to break it up into more commits.

refactor(servergroups): Add typing and convert to java syntax.

---

clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java

chore(cloudfoundry): Adds tests for cloudfoundry client timeout.

chore(cloudfoundry): Adds tests for cloudfoundry client timeout.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/retry/RetryInterceptor.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/config/CloudFoundryProviderConfig.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsTest.java

chore(cloudfoundry): Extracts configuration variables for retries.
Related PR: https://github.com/spinnaker/halyard/pull/1862

chore(cloudfoundry): Extracts configuration variables for retries.

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

resolves https://github.com/spinnaker/spinnaker/issues/6318
This will break when other changes are pushed to azure-clouddriver since the test will need to support those features as well.

feat(provider/azure): Support enableIpForwading in networkProfile

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cluster/SqlClusteredAgentScheduler.kt

Add cleanup mechanism for zombie caching agents. 
Add `sql.agent.zombie-threshold-ms` with a default of 1h -- after 1 hour consider the agent is zombie and remove it from activeAgents
Issue: https://github.com/spinnaker/spinnaker/issues/6405

fix(cats/sql): Zombie agents cleanup

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

- Adds support for health Extensions as well as enables the ability to add more extensions in the future using new interfaces.
- Unit tested
- Verified in Azure environment
- Backwards compatible

feat(provider/azure): Support health extension for extensions profile

---

clouddriver-yandex/clouddriver-yandex.gradle
clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/controller/YandexImageController.java
clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/provider/agent/YandexServerGroupCachingAgent.java
clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/security/YandexCloudCredentialsInitializer.java
clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/security/config/YandexConfigurationProperties.java
clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/service/YandexCloudFacade.java
clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/service/converter/YandexInstanceGroupConverter.java
clouddriver-yandex/src/test/java/com/netflix/spinnaker/clouddriver/yandex/deploy/AbstractYandexDeployTest.java

Fixes for Yandex.Cloud provider

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoFileSystem.java

* Deletion of clones should also be protected by the lock, so that no threads try to access the clone while it's being deleted
* Synchronize creation of lock instances to avoid having multiple locks for the same coordinates
* Don't delete lock instances after unlocking, to prevent threads waiting on a deleted lock to timeout
* Added debug logging

fix(git/repo): Fixed concurrency issues

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesIngressHandler.java

Closes https://github.com/spinnaker/spinnaker/issues/6420
Largely a copy, paste, edit of the existing `networking.k8s.io/v1*` apiVersion handling.
Tested with `clouddriver-caching` no longer throwing exception:
```
com.netflix.spinnaker.clouddriver.kubernetes.op.handler.UnsupportedVersionException: No ingress is supported at api version extensions/v1beta1   
```
I'm not sure why the Groovy test for Ingress `extensions/v1beta1` is not working.

fix(kubernetes): Restore support for extensions/v1beta1 Ingress

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperationUnitSpec.groovy

Summary
Adding support to delete ASGs with mixed instances policy
Issue
spinnaker/spinnaker#5989

feat(aws): Adding support to delete ASGs with mixed instances policy

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelper.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/BasicAmazonDeployAtomicOperationConverterUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

- minor refactors
- simplified unit tests

refactor(aws): minor refactors and changes to existing features

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy

adding support for multiple instance types, mixed instances policy to CloneServerGroup op
https://github.com/spinnaker/spinnaker/issues/5989
Manual testing - create and clone server groups with various launch settings:
- Launch configuration -> launch template
- Launch template -> launch template
- Launch template -> Mixed Instances Policy

feat(aws): adding support for multiple instance types, mixed instances policy to CloneServerGroup op

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithMixedInstancesPolicyBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateServiceSpec.groovy

* test(aws): Add/ modify unit tests
* refactor(aws): misc refactor

AWS provider: Miscellaneous changes (refactor / tests) 

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

fixing merge fix for https://github.com/spinnaker/clouddriver/pull/5371 
1.26 backport release

chore(ci): fix merge fix 

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

fixing merge fix for https://github.com/spinnaker/clouddriver/pull/5372  
1.25 backport release

chore(ci): fix merge fix

---

clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/test/ModifyServerGroupLaunchTemplateSpec.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelper.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithMixedInstancesPolicyBuilder.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareModifyServerGroupLaunchTemplate.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareUpdateAutoScalingGroup.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/UpdateAutoScalingGroup.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelperSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareModifyServerGroupLaunchTemplateSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareUpdateAutoScalingGroupSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/UpdateAutoScalingGroupSpec.groovy

* Add priority to launch template overrides for explicit ordering and related changes
Add validation to modify op
* Make MIP fields in desc take precedence in clone op
Refactor in modify op and accommodate overrides priority
* added / modified unit tests
* integ tests

Adding priority to overrides for explicit ordering, adding validation to modify op and related refactor

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/LastOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServiceInstance.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java

feat(cloudfoundry): Adds last operation description to have a better context of service instance status.
This info will be used in orca, related PR: https://github.com/spinnaker/orca/pull/4138

feat(cloudfoundry): Adds last operation description 

---

build.gradle
gradle/spek.gradle

Check maven central for libs first

chore(build): prefere mavenCentral

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyAsgDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonAsgLifecycleHook.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgBuilder.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithMixedInstancesPolicyBuilder.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithLaunchConfigurationBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithLaunchTemplateBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithMixedInstancesPolicyBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy

* Adding support for capacity rebalance
* CreateServerGroup op
* ModifyAsg op
* Clone op 
* Refactor of Clone op unit tests
https://github.com/spinnaker/spinnaker/issues/6457
Deck Impl: https://github.com/spinnaker/deck/pull/9369
* all supported ops tested

feat(aws): Adding support for capacity rebalance

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaService.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgentTest.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaServiceTest.java

chore(lambda): Adds tests.

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/UpsertLambdaFunctionEventMappingDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/UpsertLambdaEventSourceAtomicOperation.java

Adds additional properties used in stream-based lambda event source mappings (i.e. kinesis)

feat(lambda): additional properties for stream event source mappings

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaService.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaServiceTest.java

chore(lambda): Adds more tests for LambdaService.

chore(lambda): Adds more tests for LambdaService.

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgent.java

Replacing parallelStream by the sequential stream on KubernetesCachingAgent for processing namespace caching. 
This is because using parallelStream will use the ForkJoin common pool, which has very few threads (only one thread confirmed when running in EKS). This is causing contention because all the agents try to use this single thread from the common pool. Using the regular stream, caching time is improved because now the agents are using their respective AgentExecutionAction threads for caching.
Agent execution duration before (100 k8s accounts)
After

fix(k8s/perf): Don't use ForkJoin commonPool in caching agents

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cluster/SqlClusteredAgentScheduler.kt

The caching agent cleanup mechanism introduced in https://github.com/spinnaker/clouddriver/pull/5332 removes executions that have not finished in a configurable amount of time (1 hour default). Even though the execution object is removed from the running list, its `AgentExecutionAction-x` thread is still left running. These threads hold in memory the list of `KubernetesManifest` loaded by the caching agents, which may eventually lead to `OutOfMemory` errors.
This PR introduces these changes:
* Cancel the futures removed by the cleanup zombie logic, passing `interrupt=true` to interrupt the running thread.

fix(sql): Cancel futures of sql scheduler executions

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgent.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgentTest.java

chore(lambda): Adds more tests for LambdaCachingAgentTest.

chore(lambda): Adds more tests for LambdaCachingAgentTest.

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/config/LambdaServiceConfig.java

Added default config to LambdaServiceConfig to avoid breaking without it.

fix(lambda): add default config

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java

This commit introduces a timeout value for streaming job to prevent the agent thread to stuck indefinitely when something goes wrong with the job.
Fixes: https://github.com/spinnaker/spinnaker/issues/6288

fix(core): Fix job executor stuck indefinitely

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesKind.java

Add two core kubernetes kind (csidriver, csinode).

feat(kubernetes): Adding csidriver and csinode kubernetes kinds

---

clouddriver-elasticsearch/clouddriver-elasticsearch.gradle

chore(dependencies): use kork's version of testcontainers

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/ArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactConfiguration.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactValidator.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentialsTest.java

This PR adds optional validation for s3 artifacts in clouddriver.

S3 artifact validation

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy
clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperationSpec.groovy
gradle.properties

Goes together with https://github.com/spinnaker/kork/pull/911

Use spinnaker http exception for 404

---

.github/workflows/build.yml
.github/workflows/integration_tests.yml
.github/workflows/pr.yml
.github/workflows/release.yml

GitHub Actions:  setup-java v1 to v2

chore(build): setup-java v2

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsTest.java

backport of https://github.com/spinnaker/clouddriver/pull/5615
mergifyio seems to be having issues

fix(cloudfoundry): Remove lombok generated getter

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-web/clouddriver-web.gradle
clouddriver-web/src/test/java/com/netflix/spinnaker/clouddriver/config/ObjectMapperTest.java
gradle.properties

When you run a [Custom Job Stage for Kubernetes](https://spinnaker.io/docs/guides/operator/custom-job-stages/) you will get the following error
after this fix

fix(kubernetes): added joda module to jackson mapper

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java

We've seen a couple of places where the operation description converter would throw a NullPointerException, resulting in an error message in Deck that just says "null". Hopefully catching them here so a useful error message can be displayed.

fix(cf): handle potential nulls in deploy stage

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeleteManifestOperation.java

We this change we are making sure to set and pass the received gracePeriod from the operation delete request 
on the operation itself

fix(deleteOp): Set received GracePeriod value to the operation itself

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeleteManifestIT.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/utils/KubeTestUtils.java
clouddriver-kubernetes/src/integration/resources/requests/delete_manifest.json

Add the test cases : 
- Delete static target
- Delete dynamic target
- Delete without cascading
- No target found

chore(it): Add delete manifest integration tests

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitJobExecutor.java

Cloning Bitbucket is failing for git repo artifact using username and token
After this change we tested different scenarios including Github

fix(gitrepo): Support to authenticate with user and token

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/cache/LoggingInstrumentation.java

Fixes an issue with the log message format, introduced during refactoring

fix(logging): Fix log message format

---

clouddriver-google/clouddriver-google.gradle
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/snapshot/SaveSnapshotAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoscalingPolicy.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgent.java
clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalHttpLoadBalancerCachingAgent.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleAutoscalingPolicyDescriptionValidatorSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgentTest.java

This is part of https://github.com/spinnaker/spinnaker/issues/6684
Autoscaling policy with the following options are now supported with this PR
Scaling Scheduling
CPU Utilizations
Load Balancing Utilization
Custom Metric Utilizations

feat(provider/google): GCE Autoscaler Support for Clouddriver.

---

clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-titus/clouddriver-titus.gradle

See https://github.com/spinnaker/clouddriver/pull/5752#issuecomment-1214587680 for background.

Protobuf for m1

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionSecretManagerTest.java

Refer https://github.com/spinnaker/spinnaker/issues/6666
added a test to make sure the GoogleSecretManager secret engine implementation doesn't break with changes to any of the dependent libraries.

test(GoogleSecretManager): add a test to make sure the right versions of libraries are built

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureStorageClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/model/AzureDeploymentOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureVirtualNetworkDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/UpsertAzureSecurityGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstance.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/subnet/model/AzureSubnetDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation.java
clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupWithoutLoadBalancersAtomicOperation.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureVirtualNetworkDescriptionSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstanceSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/description/AzureServerGroupDescriptionUnitSpec.groovy

com.microsoft.azure:azure is deprecated and Microsoft's recommendation is to use the new SDK com.azure.resourcemanager:azure-resourcemanager
I followed the following migration guides:
- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/MIGRATION_GUIDE.md
- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/migrationGuides/V8_V12.md
Most of the changes are only imports

feat(azure): Upgrade azure sdk to the latest one

---

clouddriver-google/clouddriver-google.gradle
clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/config/GoogleCredentialsConfiguration.java
clouddriver-google/src/test/java/com/netflix/spinnaker/clouddriver/google/config/GoogleCredentialsConfigurationTest.java

This fix addresses the issue - https://github.com/spinnaker/spinnaker/issues/6733

fix(google): Fix for the missing CredentialsRepository issue

---

clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/config/AppengineCredentialsConfiguration.java
clouddriver-appengine/src/test/java/com/netflix/spinnaker/clouddriver/appengine/config/AppEngineAccountCredentialsRepoTest.java

Similar to https://github.com/spinnaker/clouddriver/commit/b33f23aa99143b88fbd28ddb0afbb70151f243a8 but for AppEngine

fix(appengine): Fixes app engine credentials repo

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesDeployManifestDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java

Introduce blue/green strategy as this is a terminology used more often in the industry compared to the Neflix-specific phrasing
Relates to: 
https://github.com/spinnaker/orca/pull/4332
https://github.com/spinnaker/deck/pull/9911
https://github.com/spinnaker/front50/pull/1176

feat(kubernetes): Introduce blue/green traffic management strategy

---

clouddriver-core-tck/src/main/java/com/netflix/spinnaker/clouddriver/core/test/TaskRepositoryTck.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/data/task/DefaultTask.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/data/task/Task.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTask.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskTest.java
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTask.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

This paves the way for some orca changes to retry failed k8s tasks.

feat(kubernetes): add endpoints to allow k8s tasks to be retried by orca

---

Dockerfile.slim
Dockerfile.ubuntu

Also bumps the SDK to the latest release.

feat(gke): Enables gcloud auth plugin for 1.26+ GKE clusters

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequest.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueTest.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsControllerSpec.groovy

With some cleanup in ApplicationController::get along the way.

feat(core): copy the MDC into work done by PooledRequests

---

clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-titus/clouddriver-titus.gradle

See also https://github.com/spinnaker/kork/pull/1018.

chore(dependencies): use version 3.21.12 of com.google.protobuf

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/cache/MetricInstrumentation.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/cache/MetricInstrumentationTest.java

closing spinnaker/spinnaker#6821

fix(metrics): revert metric names to pre-Java

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy

and include the exception from front50 as the cause of the resulting IllegalStateException if something goes wrong.

fix(aws): standardize retry logic in LocalFileUserDataProvider.isLegacyUdf

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/KubernetesValidationUtil.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesDeleteManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesDisableManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesEnableManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesPatchManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesPauseRolloutManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesResumeRolloutManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesRollingRestartManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesScaleManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/manifest/KubernetesUndoRolloutManifestValidator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/servergroup/KubernetesResizeServerGroupValidator.java

See https://github.com/spinnaker/spinnaker/issues/6833

feat(kubernetes): allow operations on all kinds

---

Dockerfile.slim

Manual backport with JUST the build fix

fix(builds): Backport flag for installing aws cli

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

See https://github.com/actions/runner-images/issues/2840#issuecomment-790492173

fix: Fix docker build in GHA by removing some of the GHA tools

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/docker/DockerArtifactConfiguration.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/deploy/CloudrunUtils.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/deploy/ops/DeployCloudrunAtomicOperation.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/description/manifest/CloudrunDeployManifestDescription.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunMetaData.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunMetadataAnnotations.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunMetadataLabels.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpec.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecContainer.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecContainerPort.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecContainerResources.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecResourceLimits.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecTemplate.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecTemplateAnnotations.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecTemplateLabels.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecTemplateMetadata.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunSpecTraffic.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunTemplateSpec.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/model/CloudrunYmlData.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/op/manifest/ArtifactKey.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/op/manifest/CloudrunDeployManifestOperation.java
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/provider/agent/CloudrunServerGroupCachingAgent.java
clouddriver-cloudrun/src/test/java/com/netflix/spinnaker/clouddriver/cloudrun/deploy/converters/CloudrunDeployManifestDescriptionTest.java

This is part of https://github.com/spinnaker/governance/issues/302
Added cloudrun manifest functionality in clouddriver.

feat(provider/google): Added cloudrun manifest functionality in clouddriver

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonBlockDevice.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelper.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelperSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/DefaultLaunchConfigurationBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateServiceSpec.groovy

in both launch configurations and templates

feat(aws): support throughput property of block devices

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/controllers/PodController.java
clouddriver-web/clouddriver-web.gradle
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy
gradle.properties

Depends on https://github.com/spinnaker/kork/pull/1198

fix(openapi): Rewrite Swagger to OpenAPI annotations

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/config/RetrofitConfig.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/safety/TrafficGuardTest.java

add a test to verify the error handling provided by `ErrorHandlingExecutorCallAdapterFactory`.

test(retrofit2): add test to verify retrofit2 error handling
