clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
oort/oort-core/src/main/groovy/com/netflix/spinnaker/oort/model/ServerGroup.groovy
oort/oort-web/src/main/groovy/com/netflix/spinnaker/oort/controllers/ProjectController.groovy
oort/oort-web/src/test/groovy/com/netflix/spinnaker/oort/ProjectControllerSpec.groovy

Returns all the data needed to render project clusters in a single call.
I don't write a lot of Java or Groovy these days - any suggestions are welcome.
This will require a big refactor in Deck, which I have in flight; however, I'd like to get this deployed to test out performance and make sure it's not a dog.
Test coverage could be more comprehensive, but if we're being honest, this is a lot more testing than we have done in the past on controllers - even ones with this much logic.
@ajordens @robfletcher or anyone else, please review when you have time.

add endpoint to get cluster data for a project

---

kato/kato-aws/src/main/groovy/com/netflix/spinnaker/kato/aws/deploy/userdata/LocalFileUserDataProvider.groovy
kato/kato-aws/src/test/groovy/com/netflix/spinnaker/kato/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy

It is useful to be able to inject additional Frigga fields in user data. This adds support for:
* revision
* countries
* devPhase
* hardware
* zone

Allow extra fields in user data

---

build.gradle
kato/kato-aws/kato-aws.gradle
kato/kato-aws/src/main/groovy/com/netflix/spinnaker/kato/aws/services/RegionScopedProviderFactory.groovy

fixes an error caused by kubernetes-client transitively upgrading okhttp to a version that errors on an empty body PUT with the default client

dependency update to fix empty body PUT to eureka for status change

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy

The legacy UDF mechanism supports assembling a UserData script customized by account/application/
environment. We are migrating away from this (it is generally not a good idea in the spirit of
immutable infrastructure to have logic in UserData), to a single UserData template file in which
we just token replace environment variables. The logic to customize behaviour based on those
values is baked into the image.
An application can explicitly opt in or out of the legacyUdf format by setting a legacyUdf flag
in the application metadata in front50. Additionally there is a global default when the preference
is unspecified for the application is configured via udf.defaultLegacyUdf property
@dstengle @AMeng I know you both have looked at UserData configuration - are you guys taking advantage at …

Adds a migration path from legacy UDF to newer UDF for AWS UserData generation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/KubernetesConfiguration.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/CloneKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/CloneKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/exception/KubernetesOperationException.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/exception/KubernetesResourceNotFoundException.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/CloneKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/CloneKubernetesAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/CloneKubernetesAtomicOperationValidatorSpec.groovy

Kubernetes clone server group operation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/KubernetesConfiguration.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtilSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperationSpec.groovy

@spinnaker/google 
1. Updates k8s deploy & clone ops to return DeploymentResult type rather than Void.
2. Changes kubeutil to make API wrapper methods non-static, and autowired into deploy. Updates the deploy spec accordingly.

k8s deploy & clone return DeploymentResult. Autowire kubeutil

---

oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/AwsProvider.groovy
oort/oort-aws/src/test/groovy/com/netflix/spinnaker/oort/aws/provider/AwsProviderSpec.groovy

Not proud of this, but we need to support these nice new long instance ids from Amazon (https://aws.amazon.com/ec2/faqs/#longer-ids)
@cfieber or anyone else who loves regex ~~and untested code~~ please review

allow targeted instance search on longer AWS instance ids

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/LaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy

Reasoning:
We would like to pass User Data from an earlier stage in the pipeline to the deploy stage. This adds the ability to edit the pipeline json and add `"base64UserData": "${userdata}"` as a key value pair. The base64 user data is appended after the UserDataProviders sets up any default user data so it can be used to override these values.
It is base64 encoded because it is easier to handle as a serialized format when passing through json. Later on, a fancy UI could be built to add User Data as a text field. For now, advanced users can pass through the pipeline stages editing the json.

Add base64 encoded user data passed from amazon deploy description

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/CloneKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/CloneKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/DeployKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy

Turns out you can submit requests/limits that omit either CPU or memory, and don't supply a `m/Mi/Gi` suffix. @duftler @skim1420

provider/kubernetes: Allow for more flexible resource requests/limits.

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureResourceRetriever.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/DeleteAzureLoadBalancerDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/DeleteAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/converters/UpsertAzureLoadBalancerAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerController.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureLoadBalancerResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/templates/AzureLoadBalancerResourceTemplateSpec.groovy

- change the deployment method of a given template to be more generic
- create an azure virtual network per given resource group that will be later associated with the rest of the resources
- retrieve the dns associated with to a load balancer (via a public IP)
- retrieve the tags property of a given azure load balancer
- bug fix corresponding to the deck changes when deleting a given azure load balancer
- change the internal naming convention for the azure resources associated with a given load balancer

Azure load balancer bug fixes

---

oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/model/discovery/DataCenterMetadata.groovy
oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/model/discovery/DiscoveryInstance.groovy
oort/oort-aws/src/main/groovy/com/netflix/spinnaker/oort/aws/provider/agent/DiscoveryCachingAgent.groovy

previously, the DiscoveryCachingAgent didn't try to figure out which account an instance was in, for all accounts that shared a discovery server
this change looks at the metadata to get the accountId and compares that against the known credentials, and only if that matches caches a single health entry in the appropriate account
@ajordens ptal

updates DiscoveryCachingAgent to only add one Health entry in the appropriate account

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesApplication.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesCluster.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesImageSummary.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesModelUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesApplicationProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesInstanceProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/MutableCacheData.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/DeployKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroupSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

This PR caches server groups (replication controllers), instances (pods), clusters (spinnaker concept) and applications (spinnaker concept). It collects all replication controllers and their pods by namespace in `KubernetesServerGroupCaching` agent, determines what clusters and applications they are associated with, and stores them and their relationships using `cats`. `KubernetesClusterProvider`, `KubernetesInstanceProvider`, and `KubernetesApplicationProvider` then provide an interface to retrieve these cached objects. This saturates the endpoints hit by Deck to display clusters.

provider/kubernetes: Cache applications, server groups, clusters and instances

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/DockerRegistryCloudProvider.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/cache/DefaultCacheDataBuilder.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/cache/Keys.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/DockerRegistryProvider.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/DockerRegistryProviderUtils.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/config/DockerRegistryProviderConfig.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy

This PR caches every image tag in Redis (using cats) for each repository configured with an account of type `dockerRegistry`. These images are then accessible via `/docker/registry/{account}/images`. The goal is to allow Deck to query every docker account that a container deployment solution has configured to present user with a searchable list of images.

provider/docker: Cache & expose docker images

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/CloneKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/DeployKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/CloneKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/CloneKubernetesAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/DeployKubernetesAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy

Implements upsert load balancer for kubernetes.
Load balancers are represented as kuberentes services (and can optionally be backed by a cloud provider's load balancer, when possible). 
Relationships between load balancers and instances (pods) are maintained using labels & selectors.
@duftler

provider/kubernetes: Upsert load balancer

---

clouddriver-kubernetes/log
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy

Implements & adds a load balancer `CachingAgent`, well as a load balancer `Provider`.
This PR is most useful in conjunction with #307.

provider/kubernetes: Cache & expose kubernetes services as load balancers.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperationSpec.groovy

1. Maintains bwc based of subnetType for existing pipelines
2. if isInternal flag is set, then it drives the scheme of the elb
3. updated unit tests

Adding support for internet-elb v2 clouddriver.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/controllers/KubernetesLoadBalancerController.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy

Exposes load balancers through `kubernetes/loadBalancers` endpoint (this should be cleaned up between providers), and implements remaining features needed for full kubernetes service support.
@duftler.

provider/kubernetes: Load Balancer controller & full kubernetes service support

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java

@ewiseblatt @duftler 
Frequent socket timeout exceptions are causing clouddriver to fail. Increasing the timeout will hopefully fix this.

provider/google: Increase socket timeout to 3 minutes.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesConfigParser.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java

The user can now point to a kube config file, default is `~./kube/config` to authenticate with the kubernetes endpoint.
@duftler

provider/kubernetes: Use credentials from ~/.kube/config

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancerProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleInstanceHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleLoadBalancerHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
clouddriver-web/config/clouddriver.yml

This PR includes numerous changes:
1. Introduces model objects to represent instance health and load balancer health (see `c.n.s.c.google.model.health` package)
1. Updates the LoadBalancerCachingAgent and InstanceCachingAgent to use these models 
1. Wires them together in the GoogleInstanceProvider to actually be presented to client users
1. Removes the HEALTH namespace, as it's no longer used.
1. Introduces a new providerImpl property to allow easy switching between old and new providers to help speed development.
@duftler @lwander PTAL. It's kind of a mishmash of changes (and changes in my mind) that have accumulated over the week.

Weaves together instance and load balancer healths

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancerProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleInstanceHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleLoadBalancerHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgentSpec.groovy
clouddriver-web/config/clouddriver.yml

Based off of https://github.com/spinnaker/clouddriver/pull/332 - Please only review 2nd commit.
1. Makes GoogleSecurityGroupCachingAgent extend and use the niceties of AbstractGoogleCachingAgent.
1. Also makes use of CacheResultBuilder
1. Fill in the list of security groups a server group is a member of from the cluster provider's view. Work still needs to be done to hook up security groups within individual instances.

Hooks up Security groups to cluster provider

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesConfigParser.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java

@duftler, @skim1420 
When defining a kubernetes clouddriver provider, all details are taken from `~/.kube/config`'s current context field, but can be overridden.

provider/kubernetes: Make user and cluster optional

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy

Add additional attributes to parsed Kubernetes cats keys to allow them to be used in search results.

More work on avoiding naming collisions between aws and other providers.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy

Creates autoscaling groups with `tags` defined from a key-value map. Not sure
how y`all want to handle exceptions here, but if the user passes in more than
allowed the AWS API throws a LimitExceededException. Could handle it at a
validator side, but would rather not hard-code to a limit that might change.

Adding support for AWS AutoScaling Group Tags

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/KubernetesAtomicOperationConverterHelper.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/KubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/CloneKubernetesAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/DeployKubernetesAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroupSpec.groovy

The `credentials` field is needed for clone server group operations to resolve valid images for the given namespace. 
@duftler

provider/kubernetes: Retrieve credentials for server group

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/LoggingExceptionHandler.groovy

Also usefully (and finally) prints all request exceptions to the logs in Clouddriver.
@duftler @lwander FYI

Fix getServerGroup TODO that was causing a busted UI with new GCE Redis Impl

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerGroup.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/model/CloudFoundryServerGroup.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup2.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroup.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ProjectControllerSpec.groovy

I deprecated `ServerGroup.getImageSummary` in favor of `ServerGroup.getImagesSummary`. Providers supporting only a single image per server group will return a singleton image in the  `ServerGroup.ImageSummary` type. For now, the `/{account:.+}/{clusterName:.+}/{cloudProvider}/{scope}/serverGroups/target/{target:.+}/{summaryType:.+}` clouddriver endpoint still supports searching for a single image (`summaryType == Image`), which will return the first image in `ServerGroup.ImagesSummary` to avoid changing Clouddriver's behavior.
The motivation is the allow find images to pick among multiple Kubernetes Images.
@duftler, @cfieber PTAL

core: Make `ImagesSummary` endpoint alongside `ImageSummary`

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy

Currently the defaults are hardcoded and unable to be bypassed. This commit
allows for passing down custom block devices if they are specified in the pipeline json description.

Cherry-pick: Allow for customizing block devices

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/config/DockerRegistryProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesConfigParser.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/KubernetesUtilSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy

The purpose of this is to always display the registry an image came from in Deck.
@duftler

provider/kubernetes: Split imageId into registry, repository and tag.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy

Turns out `type` was already a field in use by Orca.

provider/kubernetes: Correctly assign load balancer type

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/KubernetesAtomicOperationConverterHelper.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/ResizeKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy

When `.convert(input, ...)` is called multiple times on the same request, and `input` only provides `credentials`, and not the `account` field, the second call to `convert` will fail since the first call deletes `credentials`. This fixes that.
Also, I added a namespace field to the Kubernetes server group model to make it easier to lookup.
@duftler

provider/kubernetes: Reassign missing credentials field

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/DisableKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/EnableKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/EnableDisableKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DisableKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/EnableKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/AbstractEnableDisableKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DisableKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/EnableKubernetesAtomicOperationValidator.groovy

provider/kubernetes: Enable/disable operation.

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/health/AzureHealthIndicator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/model/AzureDeploymentOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/cache/AzureLoadBalancerCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/DeleteAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/cache/AzureNetworkCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/cache/AzureSecurityGroupCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/DeleteAzureSecurityGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/subnet/cache/AzureSubnetCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/vmimage/cache/AzureVMImageCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureNamedAccountCredentials.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilitiesSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/validators/UpsertAzureLoadBalancerDescriptionValidatorSpec.groovy

Migrate Clouddriver-azure to use the 1.0 version of the Azure SDK for Java.
The SDK introduces dependencies on the squareup.retrofit2:2.0.0-beta4, squareup.okhttp3:3.1.2, and fasterxml.jackson:2.7.0  libraries (we are forcing the dependency to 2.7.1 due to a known compatibility issue between the 2.7.0 version and earlier versions of the Spring framework)
@spinnaker/netflix-reviewers @duftler @ajordens  PTAL

Initial migration to Azure SDK for Java 1.0.

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/exception/DockerRegistryConfigException.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

@duftler 
Just for you, @tomaslin :wink: 
When a user omits the `repositories` field of a `dockerRegistry` config in `clouddriver.yml`, clouddriver will now try to populate the list of repositories by calling the `/_catalog` endpoint of the docker registry.

provider/docker: Replace empty repository list with _catalog results.

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactory.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactorySpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy

I went with the approach of keeping the hashing logic all contained inside RedisCache - it has the advantage of being nicely behind the black box, but the disadvantage that a client of the cache can't take advantage of the hash info to figure out if it can avoid doing work.
This change is mostly backwards compatible with an older clouddriver running in parallel - the one edge case I could see is
1. new code caches something + computes the value
2. value changes, old code caches it and doesn't update the hashes
3. value changes back to original
4. new code runs and doesn't update the value because the hash matches
it seems pretty edge-casey but I would still delete the `*:hashes` keys after rolling this in 
@ajordens @duftler PTAL

updates RedisCache to use hashing to eliminate writes

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-web/config/clouddriver.yml

- change manifest endpoint to @HEAD from @GET
- allow configurable timeout for docker registry client calls
- add docker endpoint to swagger

Make docker registry integration great again

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/AgentIntervalProvider.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/DefaultAgentIntervalProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CustomSchedulableAgentIntervalProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CustomScheduledAgent.groovy

Updates AmazonInstanceTypeCachingAgent to use the system schedule if the account is reading through an Edda cache.

Allows a CustomScheduledAgent to indicate it should use the system schedule.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AmiIdResolver.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AmiIdResolverSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperationUnitSpec.groovy

Currently AMI lookups happen in three different places. Two of them have duplicated logic, and the third looks up the AMI in a different way. This consolidates them all to lookup the AMI the same way by using a new method.
The important fix here is to allow the deploy pipeline stage to lookup AMIs that are accessible to the account, but not necessarily owned by the account. This was previously not possible and would give an error:
This happens even though the account is able to view the AMI in the AWS console, as it is shared with the account.

Consolidate AWS AMI lookup logic.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy

@duftler - this makes it easier to keep the data model between Deck and Clouddriver the same, since deck needs to keep track of which handler the user has submitted.

provider/kubernetes: Segregate probe by probe type

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-web/clouddriver-web.gradle

Use specific version of Azure SDK client-runtime library from SNAPSHOT repo. This version contains fix for bug in template deployment operations.
This is a temporary solution until the bug fix is released as part of the upcoming beta2 release.

Bug fix for Azure SDK deployment operations

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonLoadBalancer.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/CatsLoadBalancerProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancer.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/cache/CacheUtils.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/model/CloudFoundryLoadBalancer.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/provider/view/CloudFoundryLoadBalancerProviderSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancer.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerInstance.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerServerGroup.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetriever.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetrieverSpec.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy

Replaces two maps with LoadBalancerServerGroup and LoadBalancerInstance POGOs across all providers.
Tested against GCE, K8S, and AWS. 
@duftler @lwander @gregturn @rguthriemsft @ajordens FYI

Makes LoadBalancer interface use proper objects.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleLoadBalancerHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy

Fixes a handful of other issues found during testing, like when relationship keys are missing.
For convenience, I'm caching the instance name AND instance zone. Zone is only required to support filtering in the UI.
@duftler @lwander PTAL.

Adds proper server group list to GCE load balancer's new provider impl.

---

.travis.yml

based on a recommendation from travis-ci support to deal with build timeouts

use trusty VM for travis build instead of container infrastructure

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

Needed for instances that are detached from any server group. Will be useful for operations like abandon, and searching for pods not managed by replication controllers.
@duftler

provider/kubernetes: Instance caching agent

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy

Includes Network & Subnet caching agents.
Enables WRITE_DATES_AS_TIMESTAMP serialization feature only once, instead of within each caching agent.
tag:  https://github.com/spinnaker/spinnaker/issues/712

Makes two Google caching agents extend the common abstract class

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactory.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactorySpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy

* reduce redis operation size (time to execute the op on the redis size)
* reduce the computed redis operation memory footprint (on the client side)
@ajordens PTAL
This probably eliminates the need to also paginate msets but I left that in there

When merging items into the cache, perform the operation in batches

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleNamedImageLookupController.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleResourceRetriever.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/ImagesCallback.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleImageProvider.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgentSpec.groovy

There is no `ImageProvider` interface, so I created one and made the old `GoogleResourceRetriever` implement it. The `@Primary` annotation on the new impl (`GoogleImageProvider`) tells spring to use it as the ImageProvider when both it and the GRR are available.

Adds GoogleImageCachingAgent, Provider & test.

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

This makes authenticating with gcr.io easier, since it requires your full GCP json key.

provider/docker: Allow user to specify password file

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleConfiguration.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance2.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/search/GoogleSearchProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java

I needed to add `region` back into the instance key because it's needed to form the target URL.
@duftler @lwander PTAL.

Make CatsSearchProvider work with cached GCE data in Redis

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleApplicationProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleImageProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleNetworkProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSubnetProvider.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgentSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProviderSpec.groovy

*Review second commit only*: This PR is based off of https://github.com/spinnaker/clouddriver/pull/434
This one has been on my list for a long time to clean up. @duftler @lwander PTAL.

Massive removal of 'GoogleCloudProvider' instance object. Replaced with static call.

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCacheOptions.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactory.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactorySpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy

This partitions all the batch operations (partitioning at the `Collection<CacheData>` level), partitions all the redis multi-key operations (`mset`, `mget`, `sadd`, `hmset`), and removes all `smembers` calls and replaces them with `sscans`
Reworks redis caching configuration into a bindable bean and config prop's it under caching.redis.
Don't merge yet, still doing some manual validation.
cc: @ajordens @anotherchrisberry

Configurable partitioning for caching redis interactions.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy

There were attempts being made against aws accounts to query load balancers in one region that actually existed in another (api throttling came into play as well).
Adding a `printStackTrace()` in the `catch` block will show the exceptions being thrown prior to this change.

Filter keyset by account and region.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/SecurityGroupLookupFactory.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/SecurityGroupLookupSpec.groovy

@cfieber 
I skipped edda just because I reused the client to modify the ingress. It appears that that was merely superstition. I think this will fix the rate limiting that we sometimes see when migrating certain ASGs in prod.
This is small and should really go to prod ASAP if it makes sense.

don't skip edda just because we make modify call to AWS

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonApplicationProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonReservationReportProvider.groovy

To differentiate between these and CATS infrastructure pieces like `CatsSearchProvider` and `CatsOnDemandCacheUpdater`
@cfieber @ajordens

Renames all CatsSomethingProvider -> AmazonSomethingProvider

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/SecurityGroupService.groovy

also fixes a clone across regions or accounts (resolves groupIds to names, then re-looks up those names in the destination account's classic link vpc)
@ajordens PTAL

add an option to attach app, stack, and cluster scoped vpc security groups to the classic link interface if they exist during deployment

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/LoadBalancerCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/cache/AzureCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/cache/AzureLoadBalancerCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/cache/AzureSecurityGroupCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/provider/agent/ClusterCachingAgent.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/provider/agent/ClusterCachingAgentSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/NoopOnDemandCacheUpdater.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandAgent.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandCacheUpdater.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleOnDemandCacheUpdater.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy

Considering the `type` of each OnDemandAgent is limited in scope to either ServerGroups, SecurityGroups, or LoadBalancers, having a free form String felt extraneous, so I made it a proper Enum.
Based on the OortService/MortService interfaces in Orca, the deprecated/legacy stuff is just dead code and has been dropped in this PR. 
@duftler @lwander @cfieber @ajordens @JargoonPard @gregturn - This change touches all providers. PTAL.
tag:  https://github.com/spinnaker/spinnaker/issues/712

Made 'type' a proper Enum in OnDemandAgent/CacheUpdater interfaces

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonMetricDatapoint.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonMetricDescriptor.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonMetricStatistics.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonCloudMetricProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonMetricStatisticsSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonCloudMetricProviderSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/CloudMetricDatapoint.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/CloudMetricDescriptor.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/CloudMetricProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/CloudMetricStatistics.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopCloudMetricProvider.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CloudMetricController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CloudMetricControllerSpec.groovy

Introducing a new controller, `/cloudMetrics`, to support retrieval of metrics and sets of metric statistics.
New model interfaces:
* `CloudMetric`
* `CloudMetricProvider`
* `CloudMetricStatistics`
I tried to write these interfaces and controller methods as generically as possible, since I do not know what GCP or Azure metrics might look like, and wanted to keep it flexible. I assume it'll be easier to provide more shape to the `CloudMetric`, and then the other interfaces, once they've been implemented.
I wrote this all in Groovy but was told by @ajordens the interfaces and implementations should be in Java, so would love feedback on how to convert some of the groovy bits.
@spinnaker/reviewers PTAL. I would especially like feedback on the right way to handle errors and the shapes of these …

provide cloud metrics endpoints, interfaces for providers

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupDetachedInstancesAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/UpsertAmazonLoadBalancerDescriptionValidatorSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/health/AmazonHealthIndicatorSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonAllowedAccountsValidatorSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProviderSpec.groovy
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtils.groovy

Right now we index the same public images in every account clouddriver manages.
This change updates it to only index them once per region - they will still show up in the search dropdown but in our case this eliminates on the order of 1.5 million keys in redis.
This is a step towards image caching cleanup that will only index the images actually owned by an account, in each account, but that is a bit more invasive as the Key structure for IMAGES and NAMED_IMAGES has to change to remove the account name component.
The three commits in this change all stand alone so I wasn't intending to squash this except to address any feedback towards the last commit into that commit

Reduce aws image caching

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/loadbalancer/KubernetesLoadBalancerDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy

The idea is to retrieve the operation that would have created this load balancer, making it easier to edit a load balancer in deck, and unifying the data models within the kubernetes provider. 
@ttomsu or @duftler

provider/kubernetes: Load balancer description attribute

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeleteScalingPolicyDescriptionAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/UpsertScalingPolicyDescriptionAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteScalingPolicyDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAlarmDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertScalingPolicyDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteScalingPolicyAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAlarmAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertScalingPolicyAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertScalingPolicyResult.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/DeleteScalingPolicyDescriptionValidator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/UpsertScalingPolicyDescriptionValidator.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteScalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertScalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy

Basically three types of changes mashed together in one PR:
1. Including support for the `AtomicOperations` so the changes via https://github.com/spinnaker/orca/pull/772 will be passthrough, and future providers will only need to touch Clouddriver (fine, and Deck) to get the same functionality in place
2. tweaking the names of some of the `*name` fields: `asgName` is deprecated in favor of `serverGroupName` (more closely aligned with recent changes elsewhere), changed `name` to `policyName` in the `DeleteScalingPolicyAtomicOperation` (it's closer to the AWS API)
3. Adding alarm support to the upsert and delete operations: when deleting a scaling policy, if there are no other policies using the alarm, we'll delete it; when upserting a policy, the client can include an `alarm` field, which …

enhancements to scaling policy upsert operations

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/KubernetesContainerValidator.groovy

These additions allow Spinnaker to be deployed on Kubernetes using Spinnaker 
Most important was the addition of secrets as volume sources, which is how we will be deploying configuration.
@duftler or @ttomsu

provider/kubernetes: Prepare for deploying spinnaker with spinnaker

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancer.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureLoadBalancerResourceTemplate.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/description/AzureServerGroupDescriptionUnitSpec.groovy

Track various relationships between server group and its resources via the tag map.
Bug fix: retrieving load balancers with the same name across different locations/regions was only returning one instance.

Track relationships between an Azure server group and its resources

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/helpers/AbstractServerGroupNameResolver.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/helpers/AbstractServerGroupNameResolverSpec.groovy

This handles the scenario where an API user would like to bulk create (or clone) multiple ASGs

Support for specifying an explicit ASG sequence number

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/exception/KubernetesOperationException.groovy

Previously, exceptions from the client library were being suppressed in the logging, and were too verbose in the UI. This fixes that by logging the exceptions, and only propagating the "message" field of the client exception forward.
@duftler @ttomsu

provider/kubernetes: Fix up error reporting

---

clouddriver-web/config/clouddriver.yml

The day is finally here! This turns on the new Redis based caching implementation for GCE. 
Obviously if you're having troubles, flip this value back to "old" and file a bug report, assigning @ttomsu. 
@spinnaker/google-reviewers FYI

Turn on GCE Redis-based provider impl

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureBaseClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureStorageClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/application/view/AzureApplicationProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/DeleteAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/DeleteAzureSecurityGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/UpsertAzureSecurityGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstance.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/DestroyAzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/DestroyAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/DestroyAzureServerGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/validators/DestroyAzureServerGroupDescriptionValidator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/ops/DestroyAzureServerGroupAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy

Add destroy server group ops. 
Cleanup resources that are created as part of the create server group in case of a failure during the creation.
Add retries support when deleting a resource in Azure (work around for random timeouts when accessing Azure resources in the Azure Cloud).
Fix an exception in clouddriver console when the application has no clusters.
Add type as part of the deployment name.

Add destroy server group ops and other minor bug fixes

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/DefaultNodeStatusProvider.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/NodeStatusProvider.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentSchedulerSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/EurekaStatusNodeStatusProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy

ClusteredAgentScheduler will only run agents if the node is enabled.
Adds EurekaStatusNodeStatusProvider to determine node status from eureka status.

Adds NodeStatusProvider for ClusteredAgentScheduler.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java

Using the full v2 endpoint was preventing Kubernetes from correctly authenticating with some private registries
@duftler

provider/kubernetes: Fix image pull secret address

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTask.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskRepository.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskRepositorySpec.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/TaskController.groovy

To enable a redis update without clouddriver downtime, this adds the ability to read task data from a previous redis instance. An update looks like:
* deploy a new redis
* deploy a new clouddriver to populate the cache data in the redis
* the redis.connection.previous points at the original redis
* swap traffic to the new clouddriver
* let any tasks in the old clouddriver complete (they will be pollable via the /task endpoint)
* destroy old clouddriver
* destroy old redis
`redis.connection.previous` is optional, and only used in `JedisTaskRepository`
also fixes the `/task/:id` endpoint which would previously return an empty http 200 if an unknown
task was requested (now returns 404)

Adds previousJedisPool to allow a rolling redis update.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleServerGroupCachingAgent.groovy

I goofed a few places where zone and region are used to generate the server group key in the Redis impl. This, understandably caused some issues - some nuanced and some pretty obvious.
@duftler discovered the region/zone key issue, but there was also a more nefarious issue lurking. TL;DR: don't have your On Demand handler say it's authoritative. When you do this, and your cache update only includes 1 entry, the infrastructure takes this as a sign to delete the rest of the keys in that namespace. This caused server group flapping in the UI and general instability in any stage that included `ServerGroupForceCacheRefresh`
@duftler @jtk54 PTAL

Fixes server group key issue and on demand caching issue

---

cats/cats-core/cats-core.gradle
cats/cats.gradle
clouddriver-core/clouddriver-core.gradle

for some reason frigga was added in cats-core but never used and not added in clouddriver-core...
turns findbugs back on with newer toolVersion

dependency cleanup

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy

Step 1 to allow users to specify images without relying on the dropdowns.

provider/kubernetes: Enable specifying image w/o dropdown

---

clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/converters/CloudFoundryDeployAtomicOperationConverter.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/converters/CloudFoundryDeployAtomicOperationConverterSpec.groovy
clouddriver-web/clouddriver-web.gradle

Deploying clouddriver to Cloud Foundry requires an uber jar. This adds a flag "springBoot.repackage" that can be used on the command line to build an uber jar.
Cherry-picks #465.

Add flag to build uber jar

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/AzureResourceOpsDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancerDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerController.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/model/AzureSecurityGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstance.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/EnableDisableDestroyAzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/DestroyAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/DisableAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/EnableAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/DisableAzureServerGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/EnableAzureServerGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/validators/DisableAzureServerGroupDescriptionValidator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/validators/EnableAzureServerGroupDescriptionValidator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureLoadBalancerResourceTemplate.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureSecurityGroupResourceTemplate.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/templates/AzureLoadBalancerResourceTemplateSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/deploy/templates/AzureSecurityGroupResourceTemplateSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/ops/DestroyAzureServerGroupAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy

Add initial implementation for disable/enable ops; we will revisit these when moving to use AppGateway; for the time being we will power down/restart the instances only.
Return proper create time and image name when querying server group details.
Other minor fixes.

Add initial implementation for disable/enable Azure ops and other fixes

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy

Dockerhub sometimes leaves deleted tags around without allowing them to be pulled (the manifest is gone). To avoid crashing the caching agent when this happens, we simply avoid putting tags with missing manifests into the cache.

provider/docker: Ignore tags missing their manifest.

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Job.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/JobProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/JobState.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Process.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ProcessProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJob.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesModelUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesProcess.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesJobCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProcessProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
clouddriver-web/config/clouddriver.yml
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ProcessController.groovy

This complements https://github.com/spinnaker/clouddriver/pull/513, allowing jobs to be queried. I'm representing jobs as composed of "processes", borrowing language from https://github.com/spinnaker/spinnaker/issues/818. Since "processes" are effectively containers, they share the same `HealthState` enum with VMs and containers running in server groups. Jobs have a separate notion of success/failure depending on the state of the processes they manage. 
I'll likely be adding to this as in separate PRs as I decide what needs to be forwarded to Deck to visualize Jobs and Processes. 
@tomaslin @duftler could you PTAL?

core: Add process & job providers & models

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/AgentLock.java
cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/AgentScheduler.java
cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/DefaultAgentScheduler.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentLock.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
cats/cats-test/src/main/groovy/com/netflix/spinnaker/cats/test/TestScheduler.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy

@cfieber @duftler 
OnDemand cache updates (for agents that implement AgentSchedulerAware) using the new Sort scheduler no longer need the OnDemand namespace. This make these force cache refreshes much faster: 
To make sure that the Kubernetes provider keeps working regardles of the scheduler, I left the OnDemand namespace code in for now.

cats & kubernetes: on-demand locking

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy

When `CLUSTER` wasn't authoritative, it would persist cached relationships (for deleted server groups/load balancers), causing the application controller to return old clusters. Since this is only surfaced when summary application details are loaded, it went unnoticed until those details were used by orca to determine if an app can be deleted. This fixes that.
@duftler

provider/kubernetes: Allow empty apps to be deleted

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/view/AzureInfrastructureProviderConfig.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/cache/AzureAppGatewayCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/DeleteAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/converters/DeleteAzureAppGatewayAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/converters/UpsertAzureAppGatewayAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/validators/DeleteAzureAppGatewayAtomicOperationValidator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/validators/UpsertAzureAppGatewayAtomicOperationValidator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/view/AzureAppGatewayController.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/view/AzureAppGatewayProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/cache/Keys.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/model/AzureLoadBalancer.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/converters/UpsertAzureAppGatewayAtomicOperationConverterSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/ops/DeleteAzureAppGatewayAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/ops/UpsertAzureAppGatewayAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/template/AzureAppGatewayResourceTemplateSpec.groovy

Add Application Gateway ops (create, delete).
Add Application Gateway caching.
Add Application gateway viewing via new HTTP request mapping (see localhost:7002/azure/appgateways). Expect this to change once we have all the pieces in place to switch over to using application gateways instead of load balancers.
Fix regression: we were failing to create the vnet associated with a new resource group (app).
Various minor bug fixes: some operations can be expected to return null rather then an object that has a valid "body".

Azure Application Gateway related ops and others

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy

To enable (disabled by default):
````yaml
aws:
defaults:
addAppGroupToServerGroup: true
````
This will add an existing security group or create a new empty security group matching the application name during a deploy operation to AWS.

Adds option to attach application security group to server group on deploy.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesConfigParser.groovy

This only fixes the error message "Cannot cast gstring to string" when toggling pod labels on for Kubernetes installations on AWS. The root cause is that the default credentials provided in kube/config don't seem to allow you to edit pods with the REST API, or there is a bug with the client library (since kubectl with the provided credentials work fine). I'm filing a bug with the client library to see where to go next.

provider/kubernetes: Fix error message for k8s on AWS toggle pods operation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesJobCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

Since both jobs & server groups belong to (mutually exclusive) sets of clusters, the cache needs to reflect this. By making the cluster cache key in redis aware of whether the cluster owns server groups or jobs, both the server group and job caching agents can be authoritative for clusters in the same namespace.
@ttomsu PTAL.

provider/kubernetes: Cache clusters for both jobs & servergroups

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesModelUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesInstanceProvider.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy

Correctly report `KubernetesContainer` type health checks for jobs (including succeeding & failing instances).
@duftler

provider/kubernetes: Job instance health reporting

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/SecurityGroupService.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy

if any specified group name contains the application name, consider that acceptable for addAppGroupToServerGroup
if adding an app group is necessary, but doing so would exceed the maximum number of groups, fail the request

(aws) relax app security group lookup

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.groovy

@duftler 
`loadBalancerToSecurityGroupMap` was made static to be shared with `KubernetesJobProvider`, while relying on non-static attribute.

provider/kubernetes: Fixes a bug introduced by job provider

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesCluster.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

When returning a single cluster from the cluster endpoint, we should merge the jobs & server groups inside that cluster rather than arbitrarily return one of the two clusters.
@duftler

provider/kubernetes: merge server group & job cluster

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/LoggingExceptionHandler.groovy

This highlighted a few items which are all addressed in separate commits.
The root cause of this is that the id set for an AWS instance still contains an entry where the actual item has been deleted. The hydrator would load the underlying item and NPE. The LoggingExceptionHandler would swallow the exception.
@anotherchrisberry PTAL

Fix for AWS instance search where a partial key was matched

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/view/AzureInfrastructureProviderConfig.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/converters/UpsertAzureAppGatewayAtomicOperationConverterSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/ops/DeleteAzureAppGatewayAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/ops/UpsertAzureAppGatewayAtomicOperationSpec.groovy

Fix an issue while editing an existing load balancer (aka Azure Application Gateway); the public Ip resources was not handled properly in the deployment template.
Also part of this change I've disabled the caching for Azure Market Store VM images and Azure L4 Load Balancers (it reduces the redis cache footprint too); none of these resources are not exposed to the "deck" at the moment.

Fix an issue while editing an existing load balancer

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/DestroyAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy

- attaching a security group to a server group during create server group fails (typo in the load balancer settings)
- destroying server group fails to remove the app gateway BAP (typo in the destroy server group implementation)

Azure server group related bug fixes

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesConfigParser.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java

If your kubeconfig has a context
```
contexts:
- context:
user: cafe_user
cluster: cafe_cluster
name: cafe_context
```
You can now specify
```
kubernetes:
enabled: true
accounts:
- name: cafe_account
context: cafe_context
```
rather than
```
kubernetes:
enabled: true
accounts:
- name: cafe_account
user: cafe_user
cluster: cafe_cluster
```
for the sake of simplicity.

provider/kubernetes: Specify auth with context

---

build.gradle

fixes NPE in aws retry/backoff handlers when generating metrics tags

update spinnaker-dependencies to 0.35.0

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/SharedMutex.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java

@duftler 
See https://github.com/fabric8io/kubernetes-client/issues/408 for context.
Recreating the client re-registers the adaptors in the above issue, temporarily fixing the problem.

provider/kubernetes: Extensions API bug workaround

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/DestroyAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/DisableAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/EnableAzureServerGroupAtomicOperation.groovy

Fix for a bug in disable server group; during destroy SG we call disableop and if a different SG is active, that gets disabled as well.
Added couple more logging lines to keep track of the "orchestration" progress when creating or disabling SGs.
Implemented isDisabled for a server group; also changed enable and disable ops to take advantage of this check and fast track the op if no updates are needed.

Azure bug fix for disableSG and isDisable implementation

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

@tomaslin, @duftler PTAL
This defers catalog loading until after app startup and truncates the list of repositories if an error is encountered while paginating catalog.

docker: assorted catalog improvements

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientV3Provider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/OpenstackAtomicOperationConverterHelper.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/instance/TerminateOpenstackInstancesAtomicOperationConverter.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/OpenstackAtomicOperationDescription.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/instance/OpenstackInstancesDescription.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/exception/OpenstackOperationException.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/TerminateOpenstackInstancesAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidator.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/instance/TerminateOpenstackInstancesDescriptionValidator.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentials.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/TerminateOpenstackInstancesAtomicOperationUnitSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/OpenstackAttributeValidatorSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/instance/TerminateOpenstackInstancesDescriptionValidatorSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentialsSpec.groovy

This is just a noop with all the framework to get the operation invoked.
terminate instance changes
Successfully deleted instance
adding specs for delete operations
Tests for OpenstackClientProvider handle request.
checkpoint
undo changes to kubernetes validation, some validation logic duplicated in openstack

Operation to terminate Openstack instance.

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

@duftler 
@tomaslin FYI
By default tracking digest changes is now disabled. The end goal is to trigger pipelines only from tags being added to a specific repository. Once this is finished (changes to igor inbound), this will be the only place this behavior needs to be configured.
When enabled, there is a slight change. If the registry responds with a 404 during the digest lookup the tag is removed from the cache as before. If any other error is encountered, the tag is left in the cache but without a digest. This will be handled gracefully in igor (digests flipping between null & some value won't trigger pipelines).

provider/docker: Make tracking digests optional

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidationException.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

The minimum requred payload becomes `credentials` + `source` to make a copy of an existing server group, and then any additional fields to make changes from the `source`'s configuration. `credentials` is required because asserting that exists is baked pretty far up the operation handling stack (could theoretically have pulled that from `source.account`)
Normalizes security groups to names when filling defaults that cross an account or zone
Resets keypair to the defaultKeyPair when crossing account or region and the keyPair wasn't explicitly passed
Also runs the validation after the final `BasicAmazonDeployDescription` has been constructed.
It is possible to issue a cloneServerGroup and the source not be found - so long as it is a fully formed deploy it will succeed, otherwise it will fail …

Updates CopyLastAsgAtomicOperation to pull more from the source field.

---

clouddriver-web/config/clouddriver.yml

`google-containers` is no longer included in the list of images `gcloud images list` returns, so we stop supplying it in the default list of images.
@duftler

provider/google: Remove google-containers image source

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy

sometimes the docker registry will have incorrect indexing of repositories. Seeing that it currently terminates the poling process whereas it should just be ignored.

Docker registry: prevent errors from getTags terminating polling agent

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AmazonCloudProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsInfrastructureProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonElasticIpCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonKeyPairCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSubnetCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonVpcCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsInfrastructureProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonElasticIpProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonKeyPairProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonVpcProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonElasticIpCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonKeyPairCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSubnetCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonElasticIpProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceTypeProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonKeyPairProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSubnetProviderSpec.groovy

This introduces a constant on AmazonCloudProvider instead of injecting it as a component all over the place to reference its id attribute.

Eliminates injection of AmazonCloudProvider for cache key handling

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/UpsertSecurityGroupDescriptionValidator.groovy

We don't try to update the description so it's kind of silly to require users to send one in.
@spinnaker/netflix-reviewers fyi

(aws) do not require description on security group update

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/view/AzureInfrastructureProviderConfig.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureVirtualNetworkDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/view/AzureNetworkProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/subnet/model/AzureSubnetDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilitiesSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureVirtualNetworkDescriptionSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy

Moved Azure Subnet and VirtualNetwork description creation from AzureNetworkClient into the respective description classes and disabled the Azure Subnet caching agent for now; we already get the subnets through the Azure network caching agents.
Default to premium storage.
Added ipv4 representation for the subnet address prefix which will be used to calculate next subnet address prefix using a randomly selected seed.
Compute and select the next subnet using the cached virtual network and using a randomly generated seed.
Added test cases for AzureVirtualNetworkDescription class and methods and the new methods in the AzureUtilities.

Azure create subnet fixes and other small tweaks

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupController.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgent.groovy

Considering using this when sorting images in the UI. Currently, we sort by reverse alphabetical order, which is not great.

(aws) cache image creation timestamp

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

A call to the credentials endpoint was fetching all repositories for dockerRegistry type credentials. Making the repositories and credential fields jsonIgnore avoids this potentially costly call ( specially when scanning an entire catalog )

Skip loading of repositories and credentials for credentials endpoint

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProvider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/exception/OpenstackResourceNotFoundException.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/securitygroup/UpsertOpenstackSecurityGroupAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/securitygroup/UpsertOpenstackSecurityGroupDescriptionValidator.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackClientProviderSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/securitygroup/UpsertOpenstackSecurityGroupAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/securitygroup/UpsertOpenstackSecurityGroupDescriptionValidatorSpec.groovy

Making the client more of a pass through to the Openstack4j API and letting the operations figure out the business logic. This gives better logging at the operation level.

Move security group logic to operation instead of client

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

Add ability to skip repositories
```
- name: testregistry
address: http://xxxyyy.com
cacheThreads: 25
paginateSize: 500
clientTimeoutMillis: 360000
trackDigests: false
skip:
- tonsoftags
- smellsbad
- org/skippy```

add the ability to skip repositories when indexing a docker registry

---

clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandler.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandlerSpec.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/ops/DisableCloudFoundryServerGroupAtomicOperationSpec.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/ops/EnableCloudFoundryServerGroupAtomicOperationSpec.groovy

To support canary testing, Cloud Foundry-based server groups need a version-specific route ALSO mapped during deployment. This is also handled during enable/disable server group operations.

provider/cloudfoundry: Add version specific route for canary testing

---

clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/model/CloudFoundryServerGroup.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/provider/view/CloudFoundryClusterProviderSpec.groovy

When cloudfoundry fetches createdTime for a server group running multiple instances, it simply grabs the first one. It should actually look at all instances and grab the oldest.

provider/cloudfoundry: Fix createdTime for out of order instances

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy

@lwander @duftler 
Added a name field to the GoogleHealthCheck class and updated the agent to provide this field. I need the name of the health check in order to properly serialize it. Terraform uses the name to determine if it needs to create a new resource or edit an existing one. The name of a health check is determined in part by the time it was created, so it is not possible to reconstruct this name from the current fields in the model. Adding the name field fixes this issue.

provider/google: added name field to GoogleHealthCheck

---

clouddriver-web/config/clouddriver.yml

clouddriver.yml, the default settings for using CF, needs to have repository username/password fields set.

provider/cloudfoundry: Set default repository details

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupAlarmsAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupDetachedInstancesAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupAlarmsAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupDetachedInstancesAgentSpec.groovy

It turns out AWS doesn't let you have an infinite number of alarms. At some point (5000? 20000? it depends!), it just stops letting you create them.
When deleting an auto scaling group, AWS will delete its associated scaling policies and any alarms that are no longer part of an action. However, if a user has deleted scaling policies through the AWS console or CLI, it's possible the alarms are not deleted, and they can stack up.
@ajordens or @cfieber PTAL. Not sure about the configuration bits.

(aws) clean up old unused CloudWatch alarms

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy

@duftler 
When the container is running, but `ready := false`, the probe is failing, and the container should be marked as down.

provider/kubernetes: respond to readiness probe failures

---

clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/api/Eureka.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/api/EurekaApi.groovy

As discussed with @cfieber via Slack, this change removes the Eureka API version from the URI and let that be configured as part of the DiscoveryURL in the clouddriver.yml instead so we can support Spring Cloud Eureka.

Removed version from URIs to support Spring Cloud Eureka. Fixed #956

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgent.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgentSpec.groovy

During a deploy the classiclink and app specific groups can be attached.
This agent looks for instances that do not conform and adds the security groups.

Adds an agent to reconcile the classic link security groups.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsSpec.groovy

There are two large changes here.
1. The KubernetesProvider now reconfigures its caching agents every 30 seconds
to add new agents for new namespaces
2. Every time namespaces are requested, the clouddriver checks if the namespace
is new, and if so, adds imagePullSecretes for the new namespace
@duftler PTAL

provider/kubernetes: Dynamically load namespaces

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

Part of a series of PR adding build info support for travis integration on AWS
by adding new build_info_url tag to the images in order to be able to full fill the build info correctly for travis.
This PR retrieves the build_info_url tag of the ami added by rosco as a ec2 tag.
This is the final result
Related PRs
https://github.com/spinnaker/orca/pull/856
spinnaker/rosco#102
https://github.com/spinnaker/deck/pull/2304

Travis support for clouddriver

---

clouddriver-aws/README.md

I believe this is accurate from my testing. Rosco bakes will have an ownership of `providers.aws.primaryCredentials.name` when the default account doesn't exist.
There was also some weird whitespacing changes in this PR making it longer than I had intended, but it doesn't have any effect on rendering, let me know if I should fix it to minimize the changes to what I touched.

Documentation to include notes about primaryCredentials

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy

@danielpeach FYI
@duftler PTAL
This was missing from the fabric8 API when I first added probes (so it's in the deploy description, but previously couldn't be used). Now it'll actually create probes with HTTP headers attached.

provider/kubernetes: Probe HTTP headers

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy

If create server group fails there are some cases where the backend address pool entry that links the server group to an application gateway (load balancer) is not properly cleared. This leaves the application gateway in a corrupted state.

Bug fix: properly handle failing to create a new SG

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesJobCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesInstanceProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

The idea is to allow custom user-defined RC -> Pod labels to render correctly in spinnaker. This loosens my arbitrary naming-convention requirements to get infrastructure to show up correctly in Deck. For example, `kube-system` components now have their pods rendered correctly: 
@duftler PTAL

provider/kubernetes: Looser coupling of labels

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/FailureLogger.groovy

Logging the whole error JSON body is overkill, since 90% of the body is noise. For example, every instance that doesn't have a health check produces about 3600+ bytes of useless info.
```
2016-07-07 12:13:37.897 ERROR 51313 --- [  AgentWorker-4] ngAgent$TargetPoolInstanceHealthCallback : {
"code" : 404,
"errors" : [ {
"domain" : "global",
"message" : "The resource 'projects/nits-1132/zones/us-central1-f/instances/gke-cafe-5-c1c9c9b6-node-ct2b' was not found",
"reason" : "notFound",
"debugInfo" : "com.google.api.server.core.Fault: ImmutableErrorDefinition{base=NOT_FOUND, category=USER_ERROR, cause=null, debugInfo=null, domain=global, extendedHelp=null, httpHeaders={}, httpStatus=notFound, internalReason=Reason{arguments={}, cause=null, …
```

provider/google: FailureLogger is producing too much noise

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy

We are seeing timeouts during large numbers of MIG deletes. To avoid
inappropriate failures we retry the delete operation once. If this works at
scale we can extend this logic to other operations prone to timeouts.
@duftler, @ttomsu PTAL

provider/google: Retry delete SG on timeout

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy

@ttomsu PTAL
@duftler FYI
This change prevents loading every cluster from Redis on a single-cluster lookup.

provider/google: Targeted cluster load

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupController.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/UpsertAmiTagsAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmiTagsDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAmiTagsAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupControllerSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy

This PR introduces the ability to both tag images and search for images by 1..* tags.
The current implementation is AWS-specific, but it is an AtomicOperation and open to implementation by other cloud providers.
Relates to https://github.com/spinnaker/gate/pull/255.
There will be `orca` changes forthcoming that provide an UpsertMachineImageTagsStage.

Surface a view of image tags that exist across all AMIs

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateLoadBalancerDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateSecurityGroupDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateServerGroupDescription.groovy

Turns out the credentials are needed when authentication is enabled.
@cfieber or @ajordens PTAL

(aws) derive migration operation credentials from target

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/SerializeApplicationAtomicOperationConverter/SerializeApplicationAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/SerializeApplicationDescription/SerializeApplicationDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/exception/GoogleResourceIllegalStateException.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperation/SerializeApplicationAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/SerializeApplicationAtomicOperationConverterUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperationUnitSpec.groovy

This commit has logic to serialize the server groups, autoscalers, and load balancers of an application. It also serializes all of the security groups. I have tested this with several example applications and Terraform is able to correctly interpret the output and apply the serialized infrastructure to GCE. I still need to serialize the static ip addresses and make it so only the security groups within the relevant scope are serialized. After this, I plan to store the output in a GCS bucket with versioning enabled so that the serialized infrastructure is easily accessible and documented for the user. Next I will work on surfacing this functionality to deck as a pipeline stage. Then I will focus on deserializing the infrastructure.
@lwander  @duftler

provider/google: serialized server groups, load balancers, security groups

---

clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/config/ConsulConfig.groovy
clouddriver-google/clouddriver-google.gradle
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy

I've made a different choice here w.r.t. configuring consul for a specific provider when compared to the eureka support. The idea here is that consul is added/configured once per account per provider, because it's easy to imagine a multi-cloud situation where either 
1. each cloud is running a separate consul installation
2. the cloud's consul installations are connected into one consul installation (multi [datacenter](https://www.consul.io/docs/guides/datacenters.html)).
If we make the ability to configure consul a top level option like it is for eureka, we can't have separate consul installations for each clouddriver account. This is an issue for consul, since it's intended to be cloud-agnostic. 
Ultimately, the `clouddriver-consul` package will provide all the utility for caching, …

provider/consul: Config options

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertSecurityGroupDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy

If it's present, it should be used when performing security group upserts.
@ajordens this seems to solve SPIN-1893 (along with a corresponding change in Deck)

(aws) include and consider accountId when updating security groups

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy

(k8s) prevent container hostPort from defaulting to zero (instead of null)
@lwander PTAL

(k8s) prevent container hostPort from defaulting to zero

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesLoadBalancerProvider.groovy

The cause was that when load balancers were cached and loaded before the
first server group cache cycle, we would pass `null` server group objects into
the load balancer view. These would then be sent to Deck, causing the unrolling
of server groups to fail.
@duftler

provider/kubernetes: Fix loading of LBs

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BasicGoogleDeployDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleAutoscalingPolicyDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/BasicGoogleDeployDescriptionValidator.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleAutoscalingPolicyDescriptionValidator.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoscalingPolicy.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverterUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleAutoscalingPolicyDescriptionValidatorSpec.groovy

(gce) added upsert google scaling policy atomic operation
to be followed by delete operation.

(gce) added upsert google scaling policy atomic operation

---

clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulHealth.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/DiscoveryHealth.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/model/EurekaInstance.groovy

@duftler 
Now there is a shared `DiscoveryHealth` that `Health` objects for discovery services implement.

provider/consul: Refactored discovery health

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateServerGroupResult.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategySpec.groovy

For `forceCacheRefresh`ing to work, we need to send back an array of `serverGroupNames`.
Also removing some unnecessary `stream()` calls that IntelliJ is now shaming me for originally including.

(aws) change serverGroupName to serverGroupNames on migrate result

---

clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/Consul.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulCatalog.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulKeyValueStore.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/AgentApi.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/CatalogApi.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/ConsulApi.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/services/KeyValueApi.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/config/ConsulConfig.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/deploy/ops/UpsertConsulLoadBalancer.groovy

This allows us to instantiate each consul API with the `config` object stored in the provider credentials.

provider/consul: cleanup API usage

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/config/GoogleConfigurationProperties.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy

Added L7 feature flag in configuration. @duftler or @lwander or @ttomsu PTAL.
The yaml configuration to enable L7 LB (in clouddriver-local.yml) looks like:
```yml
google:
enabled: true
- name: my-account
project: my-gcp-project
jsonPath: /path/to/service/account/json/key.json
httpLoadBalancingEnabled: true
```

provider/google: added L7 LB feature flag in configuration.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperation/SerializeApplicationAtomicOperation.groovy

Removed a line that was causing an error when trying to serialize server groups. PTAL @duftler  @lwander

provider/google: removed line causing error in serialize atomic operation

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy

(gce) fixed validation for autoscaler custom metrics
Utilization target for custom metrics just needs to be greater than zero.
@duftler PTAL

(gce) fixed validation for autoscaler custom metrics

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationProvider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationV1Provider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/DeployOpenstackAtomicOperationDescription.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/ResizeOpenstackAtomicOperationDescription.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/ServerGroupParameters.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/ResizeOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/AbstractServergroupOpenstackAtomicOperationValidator.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/ResizeOpenstackAtomicOperationValidator.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
clouddriver-openstack/src/main/resources/asg.yaml
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackOrchestrationV1ClientProviderSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/ResizeOpenstackAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/CloneOpenstackAtomicOperationValidatorSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DeployOpenstackAtomicOperationValidatorSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/ResizeOpenstackAtomicOperationValidatorSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy

Added desiredSize attribute to payload. 
Create server group example:
```
curl -X POST -H "Content-Type: application/json" -d '[{"createServerGroup":{"stack":"teststack","application":"myapp","serverGroupParameters":{"instanceType":"m1.medium","image":"4e0d0b4b-8089-4703-af99-b6a0c90fbbc7","maxSize":5,"minSize":3, "desiredSize":4, "subnetId":"77bb3aeb-c1e2-4ce5-8d8f-b8e9128af651","poolId":"87077f97-83e7-4ea1-9ca9-40dc691846db","securityGroups":["sg-heat-test-1"]},"region":"REGION1","disableRollback":false,"timeoutMins":5,"account":"test"}}]' localhost:7002/openstack/ops
```
Resize example:
```
curl -X POST -H "Content-Type: application/json" -d '[ { "resizeServerGroup": { "serverGroupName": "myapp-teststack-v000", "capacity": { "min": 1, "desired": 2, "max": 3 }, "account": "test", …
```

Add in desired capacity to server group operations

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusConfiguration.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClientSpec.groovy

@tomaslin PTAL
not super happy with putting the requestName strings on all those calls but the alternatives seemed worse (mining the stack trace) or maybe not possible ( inspecting the Retrofit annotations when creating the call object)

quick stab at request times for titus API calls

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy

Need to verify the migration changes still work as expected.
Partially addresses https://github.com/spinnaker/spinnaker/issues/1020
PR for UI changes: https://github.com/spinnaker/deck/pull/2480

(aws) remove vpcId insertion code on security group ingress conversion

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/MigrateClusterConfigurationsAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateClusterConfigurationsDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/DefaultMigrateClusterConfigurationStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerMigrator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupMigrator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/ClusterConfigurationMigrator.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateClusterConfigurationResult.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateClusterConfigurationsAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/MigrateClusterConfigurationsAtomicOperationConverterSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/MigrateClusterConfigurationsAtomicOperationSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy

The idea here is for Orca to send in the cluster as a big dumb map and let Clouddriver send back an updated version.
This may change a little as I work on the Orca implementation but would like to get this in place so I don't have to run it locally while testing.
@cfieber Sorry again, PTAL

(aws) support migration of pipeline cluster configurations

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateClusterConfigurationsDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateLoadBalancerDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateServerGroupDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateStrategySupport.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerMigrator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/ClusterConfigurationMigrator.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateClusterConfigurationsAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateServerGroupAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/ServerGroupMigrator.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateStrategySupportSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/MigrateClusterConfigurationsAtomicOperationSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy

Two things happening:
1. Letting producers declare whether the application security group should allow ingress from EC2-Classic
2. Refactoring the migrator method signatures to not require a bunch of common fields, which can just become protected fields on the migrator. They weren't originally because I'm not a good programmer.

provider/amazon: refactor migrators; include classic ingress flag

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy

We still want to report them - we just don't want to include them in the output load balancer/cluster/server group

provider/amazon: omit skipped security groups when migrating items

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerMigrator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupMigrator.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategySpec.groovy

Tracking down an issue where the migration is failing because it is trying to create a security group in a VPC that somehow does not exist, but we don't have visibility into what it's trying to create. Hopefully this provides that visibility.

provider/amazon: update status with dependent group creation info

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategySpec.groovy

If an ingress rule is in a different account, it should be left in that account.

provider/amazon: generate dependent ingress rules in correct account

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateClusterConfigurationsDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/MigrateServerGroupDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerResult.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/ClusterConfigurationMigrator.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateClusterConfigurationsAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateServerGroupAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/ServerGroupMigrator.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategySpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/MigrateClusterConfigurationsAtomicOperationSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy

Some enhancements around migrating load balancers here:
* if migrating to VPC and the target name already exists in non-VPC, warn the user if it's a dry run, fail the migration if it's not
* allow users to send in a mapping of load balancer names and use that (if present) when building new load balancers
Both these changes will involve some UI work to make them really usable, but should make for a slightly better experience in migrations, especially if folks want to clean up the names of their old load balancers.

provider/amazon: handle load balancer name issues in migrations to VPC

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy

Cleanup/followup to https://github.com/spinnaker/clouddriver/pull/838. Mostly @lwander's comments.

Cleaned up SVG load balancing policy function.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

First PR for [#1047](https://github.com/spinnaker/spinnaker/issues/1047)
Sends the image information back so that it can be displayed on cluster and project page.

Kubernetes : Return image list back in buildInfo

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/config/CloudFoundryConfigSpec.groovy

Turns out I should have tested normal load balancer policies, not just custom ones, since normal, pre-defined ones have a "Reference-Security-Policy" attribute, which is the only thing that should be present on the create operation. Otherwise, an exception is thrown.

provider/amazon: correctly apply reference policies when migrating ELBs

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/MigrateLoadBalancerStrategySpec.groovy

Connection draining, idle timeout, access logs, and other fancy configuration settings that need to come along for the ride on a migration.
@cfieber PTAL

provider/amazon: send attributes when migrating load balancers

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ProjectController.groovy

This is to return images for the project clusters call so that the projects cluster directive can be updated with images from Kubernetes.  Please see [#1047](https://github.com/spinnaker/spinnaker/issues/1047).

Kubernetes : Return images for project clusters

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

provider/google: handle null backend list in L7 caching agent.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy

@cfieber we're caching an invalid value for ingress rules in accounts not managed by spinnaker

provider/amazon: apply correct vpcId to ingress rules

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy

- Protects against "Invalid IamInstanceProfile" errors when the IAM was recently created

`createLaunchConfiguration` should retry on failure

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateClusterConfigurationStrategySpec.groovy

@ajordens there's a fair amount of duplicated code between cluster and server group migrators, but it's just different enough that I'm reluctant to refactor it.

provider/amazon: always ensure classicLinkIngress is set on migration

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/OpenstackAtomicOperationConverterHelper.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/OpenstackAtomicOperationConverterHelperSpec.groovy

Deck wants to send the account name as 'credentials' which has to be
overriden for every openstack operation done in deck. Switching to the
standard pattern.

Added credentials alias on openstack operations.

---

clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/description/CloudFoundryDeployDescription.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandler.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandlerSpec.groovy

Setting 'disk limit' when deploying to Cloud Foundry apps is also a critically needed feature.

provider/cf: Add 'disk limit' as an option for deployment

---

clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/cache/CacheUtils.groovy

PCF and PWS sort routes in opposite orders. When searching for a matching load balancer, it's important to search ALL routes instead of just the first, to avoid a miss.

provider/cf: Scan all load balancers when looking for a match

---

clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandler.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandlerSpec.groovy

Files are pulled down and copied into temp files. Unfortunately, temp files aren't cleaned up until the JVM shuts down, something that doesn't happen often when run on a platform. This patch deletes the temp files after they've been uploaded.

provider/cf: Clean up artifact downloads after upload

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

Update images by removing registry based on conversation in [deck #2530](https://github.com/spinnaker/deck/pull/2530).

Kubernetes : Return only image:tag for clusters and projects

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy

handles some potential edge cases in how an API request can come in, particularly around dealing with ingress from an unknown
account. reworks equality comparison on IpPermission to not depend on object level equality

reworks ingress rule matching for UpsertSecurityGroupAtomicOperation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy

Written to address https://github.com/spinnaker/spinnaker/issues/1049
Unscheduled pods are now considered down, causing pipelines/stages depending on the deployment to hang until the pods are scheduled. Unfortunately the API doesn't seem to list the reason why a container couldn't be scheduled, but at least this behavior is now more correct.
@duftler

provider/kubernetes: Unscheduled pods are "Down"

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy

Revert "when calling the authorize or revoke ingress API, the IpPermission UserIdGroupPair can only have one of a groupId or groupName"
This reverts commit 37dee7a1ae8c04e897d9bf1257b3ebb6199579ab.
Revert "reworks ingress rule matching for UpsertSecurityGroupAtomicOperation"
This reverts commit 7e800cb49e44fff1c5e6b37a300f30b47554683e.
@spinnaker/netflix-reviewers FYI

Reverts changes to Amazon UpsertSecurityGroup pending regression investigation

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperation/SerializeApplicationAtomicOperation.groovy

When putting the snapshot in a bucket save the infrastructure as a map rather than a string. This makes it easier for deck to parse the infrastructure into the proper format for diff view. PTAL @lwander  @danielpeach

provider/google: Store infrastructure as map rather than string for snapshot

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy

Resolves a bug that Spinnaker has had since forever, in which only show IP range rules for one protocol if there are multiple rules on the same range with different protocols.
@cfieber PTAL

provider/amazon: consider protocol when build ip range rules

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy

@duftler I realize I've broken replication controller enable/disable at head by removing the wait on replication controller state function. This fixes that, as well as adds support for enable/disable replica sets. To avoid leaving it broken I'm going to merge now.

provider/kubernetes: Enable/disable replica sets

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperation/SerializeApplicationAtomicOperation.groovy

GStrings are stored in an odd format when put in a GCS bucket, converting them to strings solves this problem. @lwander @duftler

provider/google: Added toString for GStrings when serializing

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationControllerSpec.groovy

If there are multiple cloud providers configured, we currently don't indicate which cloud providers are used for synthetic applications. This change makes the create / clone dialogs work correctly based on the clusters that caused the synthetic application to be created

return cloud provider types for synthetically generated applications

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy

Now env vars can come from both secrets and config maps (which will be configurable in the "properties" stage) @duftler

provider/kubernetes: Allow envvars to come from k8s sources

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/UpsertGoogleLoadBalancerDescriptionValidator.groovy

@duftler @danielpeach  @ewiseblatt  FYI. Addressing integration test failures. Currently the upsert/delete L4 calls don't have the `loadBalancerType` enum.

provider/google: Allow empty loadBalancerType in upsert/delete.

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy

When the user deletes the server group through the Azure Portal web site, it causes the Redis entries to be in a corrupted state. One side effect of it is Spinnaker continues to render "ghost" server groups that can become confusing.
Also fixed an issue with how deck is expecting load balancers and security groups associated with a server group to be passed (some core functionality is expecting a list rather than a string).

Azure server group caching bug fixes

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractInstanceLoadBalancerRegistrationAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerLookupHelper.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeregisterInstancesFromLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/EnableDisableAtomicOperationUnitSpecSupport.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/InstanceLoadBalancerRegistrationUnitSpecSupport.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/RegisterInstancesWithLoadBalancerAtomicOperationUnitSpec.groovy

Right now it is treating the ALB the same as we treat an ELB - you request it by the name of the load balancer, and your server group is attached to all the target groups for that load balancer.
LoadBalancer names are not unique across classic and application load balancers, so currently this will attach both the classic and the application load balancer that match the requested name - not really sure that is the best strategy. We could fail the deploy if this was the case, we could just use the classic LB if it matches on name (I guess more backwards compatible?)
I could also see us having to evolve the deploy description if we want to support fancier ALB use cases (only attach my server group to a specific target group, not to every target group in the ALB). I'm sure at some point that …

Initial support for AWS Application Load Balancers

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/job/RunKubernetesJobAtomicOperationValidator.groovy

@danielpeach FYI (in fact, they shouldn't ever need to be specified from the UI).

(kubernetes) Job pod container names can be empty

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/cache/Keys.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/DockerRegistryProviderUtils.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/config/DockerRegistryProviderConfig.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy

@danielpeach @duftler PTAL
Since large lists of images slow down the UI, we added a `count` parameter to shrink the returned list of images. This meant that the `q` parameter needed to be used to find images that weren't immediately returned in the first `count` results; however, since the `q` parameter only searched by image and tag it was confusing to use. This fixes that by make `q` search for the full image ID.

(docker) Improve lookup semantics

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy

@duftler. The goal is to better explain why certain kubernetes-level events fail (scheduling decisions, probe failures, etc...) but it looks like this information isn't exposed at the resource level, so I will have to dig a little deeper.

(kubernetes) slight improvments to health widget contents

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatus.groovy

So this is pretty bizarre - 
```
[]?.get(0)
```
will fail with an `IndexOutOfBounds` exception, which you wouldn't expect, since `[]` is groovy-false.

(kubernetes) [] is groovy true in null-safe check

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy

This is an artifact of having a job and servergroup caching agent adding applications at the same time. Changing the agent to authoritative now allows applications to be deleted again (since jobs are no longer cached).

(kubernetes) fix application delete

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatus.groovy

There are error conditions surfaced when a container is set to "waiting" that will cause a pipeline to hang indefinitely that depends on a job. These surface those errors: https://github.com/kubernetes/kubernetes/blob/de92db35206c986c8313400910e87773df3144a2/pkg/kubelet/images/types.go

(kubernetes) handle kubernetes-level errors when running jobs

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesEvent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroupSpec.groovy

I also dropped the `Reason` enum because there were too many undocumented reasons for it to make sense to keep around, when all we were interested in was the string.
@duftler

(kubernetes) report server group events

---

build.gradle

use with `-PslowTest` or `-PslowTest=<threshold millis>` (if unspecified the threshold is 250ms)
any test that runs for longer than the provided threshold will be logged with its execution timing
if the flag is not supplied, test timing is not logged

adds slowTest build flag to log slow tests

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractInstanceLoadBalancerRegistrationAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DetachInstancesAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerLookupHelper.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeregisterInstancesFromLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/RegisterInstancesWithLoadBalancerAtomicOperationUnitSpec.groovy

also addresses some slow tests that went in related to use of a RateLimiter on load balancer lookup

prevent lookup attempts for elbv2 loadbalancers containing '--' in the name for now

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

- Currently only handles {[application}}

Support rudimentary templating in default IAM roles

---

clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/model/ConsulNode.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/provider/ConsulProviderUtils.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInstanceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy

Whenever consul is running for any instance in a server group, we start taking consul health into account.

(consul & google) report if server group is disabled

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

@duftler I saw the servergroup & pod refresh cycles taking abnormally long (1 minute +), and realized it was due to the events being loaded for each resource individually. This approach loads the events all at once, greatly speeding up the refresh cycles.

(kubernetes) batch & frontload event lookup

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy

@duftler please review. When a backend service has a backend associated, `unique()` equality check doesn't work properly because of the backend list. This `unique` checks everything but the backends, which aren't managed by L7 upsert.

provider/google: Properly dedupe backend services in upsert.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GoogleOperationPoller.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/SafeRetry.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GoogleOperationPollerSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy

@duftler @lwander please review. Refactored `safeRetry` into a generic, type-safe class since `getOperation` actually returns something instead of `void`. Added socket timeout handling instead of `GoogleOperationTimedOutException` since the latter is not something the platform throws.

provider/google: Refactor safeRetry and handle socket timeout.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgentSpec.groovy

for an eddaEnabled amazon account, only use the edda data if the lastModified time is newer than the last time a force cache refresh happened
we only have to track lastModified time since an on_demand and a read from edda are otherwise the same - they load the full data set for the account/region
@spinnaker/netflix-reviewers

updates amazon security group caching for better interaction of on demand and edda caching

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy

@duftler @danielpeach please review. I used a prefix to keep health checks and backend services unique for L7 so that no accidental updates happen. This causes the presentation to the user to be inconsistent though, since what they were seeing in the UI doesn't match the Cloud Console. Instead, I'll remove the prefixes and we'll warn users in the UI when they are updating health checks and backend services during upsert.

provider/google: Remove backendService and healthCheck prefixes.

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/subnet/model/AzureSubnetDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy

Bug fix; we end-up overwriting the user's selection for vnet/subnet with default values after the validation check. This causes the deployment to fail later on if the resources corresponding to those default values do not exist.

Bug fix; don't overwrite the user's selection for vnet/subnet

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy

When a new application is created via Deck (to Gate -> Orca -> Front50), a GET
request for the application is made to Clouddriver and it fails because
clouddriver doesn't know about this application yet. Clouddriver only
learns about applications through having a server group in that
application. So, keeping the logging, not the stacktrace.

Don't print stacktrace when no application is found.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AmiIdResolver.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ResolvedAmiResult.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperationUnitSpec.groovy

If the AMI is baked with a different account that the one being used to
deploy, that owner account needs to be used to update the permissions on
that AMI.

Lookup owner of AMI in AllowLaunch operation.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesEvent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstance.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesInstanceProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesProviderUtils.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroupSpec.groovy

In an effort to make the clusters tab more responsive I do the translation of kubernetes resource -> spinnaker resource before the instance and server group object enters the cache. This is at the expense of more overall CPU usage.

(kubernetes) Translate objects before loading them into the cache

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/cache/Keys.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/cache/AzureNetworkCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureNetwork.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureVirtualNetworkDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/view/AzureNetworkProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/converters/UpsertAzureAppGatewayAtomicOperationConverterSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/ops/DeleteAzureAppGatewayAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/ops/UpsertAzureAppGatewayAtomicOperationSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/template/AzureAppGatewayResourceTemplateSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/network/model/AzureVirtualNetworkDescriptionSpec.groovy

When creating an azure load balancer and server group, the selected virtual network can be from a different resource group then the one corresponding to the application.

Bug fix - failed to select vnet in arbitrary resource group

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/utils/DateUtils.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgentSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/utils/DateUtilsSpec.groovy

Since Kilo isn't supported anymore, we don't need to try parsing the
time with a timezone and fallback to without the timezone anymore.

Removed time parsing workaround for old Openstack version.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslCertificateCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy

@duftler please review. @danielpeach FYI. This caches `sslCertificates` so we can suggest them in L7 upsert.

provider/google: Implemented ssl cert caching agent.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperationUnitSpec.groovy

(google) Drop securityGroups attribute from Create/Clone description in favor of relying entirely on tags attribute.

(google) Drop securityGroups attribute from Create/Clone description in favor of relying entirely on tags attribute.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy

Also modified SSL cert agent to cache name only. This also enables both objects to be queried via `/search` now. @duftler please review. @danielpeach FYI.

provider/google: Added backend service caching agent.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy

We should suggest `HttpHealthCheck`s in L7 upsert (among other operations). This adds the JSON serialized object to the `/search` result for health checks. @duftler please review. @danielpeach FYI.

provider/google: Cache search result hydrator for health checks.

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

@duftler 
I also found a bug (see the ClusterProvider) where accounts with the same cluster names would show the same server group more than once.

(kubernetes) remove synch around api access

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleSessionAffinity.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

Also surface session affinity in '/search' details for backend services. In order to support L7 session affinity in upsert, we need to cache and surface that piece of information properly.  @duftler please review. @danielpeach FYI.

provider/google: Include session affinity in backend service caching.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleLoadBalancerView.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy

There were some nasty comparisons casting `Enum`s to `String`s, in some of the load balancing code, so I cleaned that up a bit. I tested this with all permutations of L4/L7 with all the operations. @duftler please review.

provider/google: Replaced String LB type with Enum in View.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy

Makes it so you can modify a backend services' session affinity through upsert. All the Clouddriver backend changes are in place for this, just need to surface it in the UI. @duftler please review. @danielpeach FYI.

provider/google: Support session affinity in L7 upsert.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy

L4/L7 port ranges were represented previously as a "range" of the same port, e.g. 8080-8080. This PR expresses that string as a single port. Additionally fixes the `instancePort` detail for Https to be the named port 'http'. @duftler @danielpeach please review.

provider/google: Represent L4/L7 single port range as a single port.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesHealth.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesInstanceSpec.groovy

@duftler 
I was incorrectly considering non-ready pods as "Starting" causing pipelines to succeed when health checks were failing.

(kubernetes) register non-ready pods as down to stall pipelines

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy

Currently instance monitoring is only set if the value is explicitly true, however the default is also to enable instance monitoring so there is currently no way to disable instance monitoring in a deployment.
cc @ndcampbell

Allow instance monitoring to be disabled on a launch configuration.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

We want to be able to group the L7 LBs by `urlMapName` in the UI, so we cache it with this PR. I'll follow up soon with another PR that requires a `urlMapName` in L7 upsert. @duftler @danielpeach please review.

provider/google: Cached urlMapName for L7 LBs.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleLoadBalancerDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy

To wire up more than one listener to a urlMap, we need an explicit `urlMapName` in the L7 upsert description. I tested this PR with create, upsert with one listener, and then another upsert that adds a listener to the same urlMap. We'll need to change L7 delete to deal with all the possible cases this enables. @duftler or @lwander or @danielpeach please review.

provider/google: Support urlMapName in L7 upsert description.

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/DefaultCacheData.java
cats/cats-core/src/test/groovy/com/netflix/spinnaker/cats/cache/DefaultCacheDataSpec.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackFloatingIPCachingAgentSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackImageCachingAgentSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceCachingAgentSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackLoadBalancerCachingAgentSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackNetworkCachingAgentSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackSubnetCachingAgentSpec.groovy

Previously the OnDemand records were loaded, incremented and re-saved w/o a TTL.

Ensure that the regular caching cycle sets a ttl for OnDemand records

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProviderSpec.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/EurekaProviderConfiguration.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/config/EurekaAccountConfigurationProperties.groovy

Spinnaker allows you to configure multiple credentials/accounts in clouddriver that correspond to the same AWS account. However, if you use Eureka discovery to determine their health, instances will only show up as healthy in one credential/account because clouddriver uses only the AWS account ID to determine the credential name. This pull request will try to use the AWS account ID and eureka host URL in order to determine the credential name when possible--defaulting to simply matching AWS account ID when no such AWS & Eureka match can be found. This will allow users to successfully deploy to multiple 'environments' or accounts even when they only have one AWS account ID.
**Update: this merge request now uses attempts to match AWS account ID and account name, instead of eureka host URL, …

Support multiple Eureka hosts using the same AWS account ID

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

We added support earlier for setting session affinity for an L7 backend service, but not the cookie TTL in the case of `GENERATED_COOKIE` session affinity. @danielpeach @duftler please review.

provider/google: Added support for L7 session affinity cookie ttl.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsInfrastructureProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProvider.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/cache/provider/AzureInfrastructureProvider.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/provider/CloudFoundryProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/SearchableProvider.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/DockerRegistryProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProvider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/OpenstackInfrastructureProvider.groovy

Not just resource type. This was causing collisions where hydrators for one provider's resource type would try to hydrate another's cache entries, which caused some havoc. Fixes https://github.com/spinnaker/spinnaker/issues/1175. @ttomsu @duftler @cfieber @ajordens please review.

Makes searchResultHydrators keyed by provider and resource type.

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SearchController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/SearchControllerSpec.groovy

- Added an exception handler for a provider search that returns an empty result set in case of a failure

Failure of a single SearchProvider should not fail all searches

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleLoadBalancerDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy

We added the ability to add multiple listeners to one url map earlier this week - this is the symmetric 'delete' operation for listeners in upsert. This also adds a utility function to delete global listeners. I'm planning on using that in a future PR changing L7 delete. @duftler @danielpeach please review.

provider/google: Added ability to remove listeners in L7 upsert.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy

L7 delete looks up and deletes all listeners attached to the url map associated with the L7 load balancer we're deleting. @duftler @danielpeach please review.

provider/google: L7 Delete deletes all listeners.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy

Adds this to be able to modify a backend service's cookie TTL in L7 upsert. @duftler @danielpeach please review.

provider/google: Adds cookie ttl sec to backend service in search.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy

@duftler @danielpeach please review. If we allow the user to add multiple listeners and specify the names manually, we need to guard against reusing a listener to try and point to two different url maps. There should be a symmetric frontend change preventing this type of situation also.

provider/google: Guard against reusing listeners for different url maps.

---

clouddriver-aws/README.md

Warn to use quotes when `accountId` starts by `0`

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/MigrateSecurityGroupReference.groovy

We don't always set the `credentials` when migrating a security group, so we can get a NPE on migration (especially if the reference is to an unknown account).
@ajordens PTAL

provider/amazon: guard against missing credentials when serializing AACD

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/resources/asg_resource.yaml

Somewhere between Mitaka and cloud-init on the base image doesn't like
the base64 encoded userdata. It may be a configuration issue with
Mitaka or cloud-init (tested with v0.7.3) in the base image. We may need
to rethink this if there are problems in other environments.
Fixes spinnaker/spinnaker#1193

(Openstack) Do not base64 encode userdata.

---

clouddriver-eureka/README.md

When I introduced this property, I forgot to update the documentation so that people know it exists. That's my bad.
This merge requests adds a short description of the situation when you would use the property 'eureka.provider.allowMultipleEurekaPerAccount' to the clouddriver-eureka README.

Add documentation for 'eureka.provider.allowMultipleEurekaPerAccount'

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/AllowLaunchAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/DefaultMigrateServerGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/servergroup/MigrateServerGroupResult.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateServerGroupStrategySpec.groovy

If the source AMI has not been deployed in the target account yet, the migration will fail. This gets around that by adding launch permissions to the source AMI in the target account.
@cfieber or @ajordens PTAL. This is the least gross way I could find to do this. I tried to do it in Orca but it was even grosser.

provider/amazon: allow launch on cross-account migration

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy

@duftler please review. Implements support for associating created and cloned server groups with internal load balancers. This reports health correctly, but doesn't report the server groups as enabled correctly -- I'll follow up shortly with another PR addressing that as well as load balancer associations in the server group caching agents.

provider/google: Implemented deploy support for ILBs.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AssumeRoleAmazonCredentials.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixSTSAssumeRoleSessionCredentialsProvider.java

This supports using the `accountId` in metrics generated by the
`InstrumentedRetryPolicy` in `kork`.

Add the assume role'd `accountId` to an AmazonServiceException

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeregisterInstancesFromGoogleLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/RegisterInstancesWithGoogleLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/EnableGoogleServerGroupAtomicOperationUnitSpec.groovy

Implemented destroy SVG for ILB as well. This follows quite closely with the patterns put in place with Http(s) LBs for manipulating server groups and backend services, but simpler since there is one backend service per ILB. @duftler or @danielpeach or @lwander please review.

provider/google: Implemented SVG enable/disable for ILB.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleLoadBalancerAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/DeleteGoogleLoadBalancerDescriptionValidator.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy

Also factored out a few 'delete if not in use' operations. @duftler or @danielpeach or @lwander please review. The refactoring replaces explicit GCP `delete` operations with a `Closure` - much cleaner.

provider/google: Implemented ILB delete.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgentSpec.groovy

Instance types will now be alphabetically sorted by family, then by largest to smallest size within a family. I added it to the caching agent, rather than the view so we don't need to repeat sorting.
@ajordens PTAL

Sorting AWS instance types by family and class size

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgentSpec.groovy

Cache didn't persist sort order, so I've moved this work into deck: https://github.com/spinnaker/deck/pull/2858
Reverts spinnaker/clouddriver#1128

Revert "Sorting AWS instance types by family and class size"

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/SafeRetry.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperationUnitSpec.groovy

@duftler @lwander please review. Previously, we made no retry attempts if an operation during an LB delete failed. This PR makes those operations much more resilient to failures in GCP. We should probably include retry behavior in upsert as well -- that will be twice as fun since there's twice the code (4x for L7). I'll look into that once I implement upsert for ILB.

provider/google: Made all LB delete ops resilient with SafeRetry.

---

build.gradle
clouddriver-aws/clouddriver-aws.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AmazonCloudProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/bastion/BastionCredentialsProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerGroup.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureNamedAccountCredentials.groovy
clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/CloudFoundryOperationsSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DefaultTask.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/Task.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTask.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/cache/OnDemandAware.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/discovery/AbstractEnableDisableInstancesInDiscoveryAtomicOperationSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DisableTitusServerGroupAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/EnableTitusServerGroupAtomicOperation.groovy

* includes a change to request less instances per describeInstances request when crawling the entire region ( d640704 )
* adds an option to enable gzip compression for AWS SDK requests ( eb1f70b )
enabling gzip had a measurable improvement in time to read the full instance collection - looking at the docs it looks like gzip is off by default. If that is the case this may do quite a bit to address spinnaker/spinnaker#1099

update dependencies for groovy 2.4

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy

@duftler please review. Turns out I calculated disabled state incorrectly for unassociated server groups in #1122. Now I check to see that the ILBs and L7s are non-empty before altering the disabled state.

provider/google: Fix disabled state for unassociated SVGs.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleLoadBalancerController.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleInternalLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy

@duftler @danielpeach please review. ILBs don't use `portRange` like everyone else does, they have a list of port (strings) as `ports`. I changed the details to serialize the ports as a comma-delimited list for ILBs, since Google Cloud Console reports the port list this way as well.

provider/google: Fixed ILB ports in LB details.

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

I was originally going to allow docker credentials to be initialized from the dockerconfigFile (see it's a new property) in this PR, but realized the current docker credentials initializer is a bit of a mess.
@duftler @tomaslin PTAL

(docker) create builder for credentials object

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHealthCheckCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy

Provides support for '/search' as well. The new agent caches all types of GCP load balancers. I left the old agent for backwards-compatibility purposes, and will remove when the frontend cuts over. @duftler @danielpeach please review.

provider/google: Implemented new health check caching agent.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleSessionAffinity.groovy

ILBs have more options for session affinities in backend services than external load balancers, so I added them. @duftler @danielpeach please review.

provider/google: Adds session affinities for ILBs.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHealthCheckCachingAgent.groovy

Also provide context which health check 'family' a health check belongs to. There are three health check 'families': `compute#healthCheck`, `compute#httpHealthCheck`, and `compute#httpsHealthCheck`. Each has its own set of endpoints. @duftler @danielpeach please review -- also Dan we should think about how to cut the frontend over to use this new search provider.

provider/google: Prevent name/key collisions in health check agent.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java

@duftler PTAL
When a namespace was explicitly added, the [`reconfigureRegistries`](https://github.com/spinnaker/clouddriver/compare/master...lwander:kubernetes-fix-dup-ips?expand=1#diff-e169d12eda01040d78999295b331c8d4R86) function would store every secret again with the kubernetes credentials whenever the credentials object was loaded [here](https://github.com/spinnaker/clouddriver/compare/master...lwander:kubernetes-fix-dup-ips?expand=1#diff-e169d12eda01040d78999295b331c8d4R149). By disallowing duplicate entries we solve this.

(kubernetes) fix duplicate IPSs in RS spec

---

clouddriver-cf/src/test/groovy/com/netflix/spinnaker/clouddriver/cf/utils/DefaultCloudFoundryClientFactorySpec.groovy

TravisCI was failing to resolve 'api.run.pivotal.io' as a host, so we are ignoring this test for the time being. I'll file a bug against TravisCI to investigate what was going on. @gregturn @duftler FYI.

provider/cf: Ignore test with live calls until TravisCI issue corrected.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/UpsertGoogleLoadBalancerDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy

@duftler @lwander @danielpeach please review. If a new L7 re-uses a backend service that contains instances, the metadata on the instances will be stale. This PR handles updating the metadata in the 'constructive' case, where we point a new L7 to an old BS. There is another 'desctructive' case, where an existing L7 changes the backend service it points to. I'll handle this in another PR once I level with Dan to get the necessary changes in the frontend.

provider/google: Update instance metadata on L7 upsert.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy

By frontloading most of the instance & security group loading, I was able to significantly cut down application load times. Here are the benchmarks (where `load(N) = s` means `N` server groups, `s` milliseconds)
**Before**
```
load(17) = 8240
load(17) = 8619
load(17) = 8412
load(17) = 8428
```
**After**
```
load(17) = 1310
load(17) = 1211
load(17) = 1214
load(17) = 1198
```
I've also captured diffs before & after with multiple server groups, load balancers & security groups w/o any differences.

(google) ~6x faster application loads

---

clouddriver-security/clouddriver-security.gradle

This pulls in the changes to propagate anonymous users as "anonymous" rather than "ignored2" when Fiat is enabled.
@jtk54 @cfieber @ajordens FYI

Update to latest Fiat release

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy

@duftler @danielpeach please review. The [docs](https://cloud.google.com/compute/docs/load-balancing/tcp-ssl/) say that only TCP and SSL health checks are supported, but I guess not... This adds the ability to cache all health check types for SSL LBs. This is a symmetrical fix to https://github.com/spinnaker/deck/pull/2933.

provider/google: Cache all types of health checks for SSL LBs.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy

This is to enable the use case of creating a hot standby server group by copying from the source (don't want it autoscaling)

add flag to suppress copying forward of scheduled actions and scalingpolicies on aws deployment

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleTargetProxyType.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DisableGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/EnableGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/UtilsSpec.groovy

Since none of the load balancer caching agents handle on-demand caching properly, there's a race condition that can cause load balancers to disappear from the cache for one cycle (30s) after an upsert. This only occurrs if we delete and recreate the forwarding rule (since there's no update). Instead of looking only in the cache, if there's a cache miss, we'll make a live call to GCP to get the load balancer.
A few caveats:
* The cases we can address with this method check the existence of the LB only, hence we can check _just_ the forwarding rules.
* This doesn't cover deploys, since we need the full cached LB to properly set up the state.
* This is only a problem if you start operating on the LBs < 30s after creating them. If you let the cache cycle again, you most likely will be fine. …

provider/google: Make provider calls when cache fails to find LBs.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/CloneKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy

@duflter, I found this bug while refactoring the kubernetes caching agents. Orca strips the namespace field, and clones out of the default namespace fail in clouddriver.

(kubernetes) fix clone from non-default namespace

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/config/OpenstackConfigurationProperties.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/OpenstackUserDataProvider.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentials.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackCredentialsInitializer.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackIdentityV3ProviderSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/OpenstackUserDataProviderSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/discovery/AbstractEnableDisableInstancesInDiscoveryAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/instance/AbstractRegistrationOpenstackInstancesAtomicOperationUnitSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/AbstractOpenstackLoadBalancerAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/loadbalancer/UpsertOpenstackLoadBalancerAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DeployOpenstackAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableDisableOpenstackAtomicOperationSpec.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentialsSpec.groovy

Provides common user data that every Openstack deployment will use. The
user data provided per app will be appended to this userdata.
Ideally, this will be replaced/moved into a core location where it is
available for all providers. See spinnaker/spinnaker#1274

(Openstack) Added user data file to use with every deploy.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy

Some recent changes to the credential initializer were preventing the provider from starting.
@duftler PTAL
@cfieber FYI

(google) fixed spring bean loading

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

This only fixes the problem for instances & server groups. Load balancers & security groups will be done next. 
What used to happen was each periodically the list of caching agents would be repopulated so there would always be one per account per namespace for each resource. There was a window where if a namespace was deleted, and before the entries in the namespace disappeared, some the members of that namespace (instances, server groups, etc...) could be orphaned in the cache, and never deleted. 
Now, the caching agents aren't repopulated, and instead come from a fixed pool specified by the `kubernetes.accounts.cacheThreads` parameter. Namespaces are assigned to agents based on the hash of their name for a (hopefully) even distribution of work. 
@duftler PTAL

(kubernetes) cleanup cache entries for old namespaces

---

clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy

EurekaSupportConfigurationProperties is only initialized if the EurekaProviderConfiguration is loaded, which is
Conditional on the eureka.provider.enabled property.
AbstractEurekaSupport is always initialized and only conditionally called if an account has the discoveryEnabled flag set on it

make EurekaSupportConfigurationProperties optional in AbstractEurekaSupport

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgentSpec.groovy

This is meant to address https://github.com/spinnaker/spinnaker/issues/1099
There was work done in https://github.com/spinnaker/clouddriver/pull/1093 but it was closed.
Cache private and public AMIs separately. This allows us to cache public images for much longer.

Cache public AMIs longer than private

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy

@duftler @danielpeach please review. `target` was not rendering properly for load balancers not using the `GoogleHealthCheckView` object and using the raw `GoogleHealthCheck` object (i.e. LBs where the health check is reported through a `BackendService`).  I moved the `target` calculation into the actual model object rather than in the `View`, so that it's present regardless if you use the `View` or not.

provider/google: Health check 'target' display fix.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgLifecycleHookWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/UpsertAsgLifecycleHookDescriptionAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAsgLifecycleHookDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAsgLifecycleHookAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/UpsertAsgLifecycleHookDescriptionValidator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonAsgLifecycleHook.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AssumeRoleAmazonCredentials.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixAmazonCredentials.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixAssumeRoleAmazonCredentials.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoader.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgLifecycleHookWorkerSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAsgLifecycleHookAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoaderSpec.groovy
clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtilsSpec.groovy

Allows templated addition of account-wide autoscaling lifecycle hooks. If `defaultLifecycleHooks` are defined, or account-level `lifecycleHooks` is defined, any server group created within that account will have lifecycle hooks created and applied to it.
There's currently no way to delete lifecycle hooks from server groups outside of the deletion of the ASG.

Initial support for AWS autoscaling lifecycle hooks

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancingPolicy.groovy

@duftler @danielpeach please review. From the [docs](https://cloud.google.com/compute/docs/load-balancing/tcp-ssl/), SSL LBs can support `UTILIZATION` and `CONNECTION` balancing modes. We had `UTILIZATION`, so this adds `CONNECTION`. We'll have to add support to the server group wizard on the frontend as well.

provider/google: Support CONNECTION balancing mode in SSL LB.

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperation.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/CloneOpenstackAtomicOperationSpec.groovy

When cloning a stack, a null floatingNetworkId means don't set a fip on
each instance, so can't clone the previous setting if not set in the new
one.

(Openstack) Allow overriding floatingNetworkId when cloning.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy

@jtk54 PTAL
@duftler FYI
Most stages depending on "on demand" cache refreshes would succeed silently since the requested change would show up in time for the stage to continue. However, in the cases where they didn't show up on time, this failure to update the cache would cause the stage to fail.

(kubernetes) fix on demand cache refresh

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/exception/KubernetesOperationException.groovy

I've been failing to set the "cause" for the Operation exceptions thrown by the Kubernetes operations. This is just meant to make debugging a bit more helpful.
@jtk54 PTAL

(kubernetes) set cause for kubernetes exceptions

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/UpsertEntityTagsAtomicOperationConverter.java
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/DefaultAllowedAccountsValidator.groovy
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/NonCredentialed.java
clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/DefaultAllowedAccountsValidatorSpec.groovy

- Supports the case where EntityTags may target all accounts (ie. `account: "*"`)

Allow for Descriptions that do not contain `credentials`

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

My recent cache refactor left the list of instances as [null] rather than []
for a server group without instances attached. This caused stages that shrink
server groups to no instances to fail
@jtk54 PTAL, @skim1420 FYI

(kubernetes) correctly handle empty list of instances

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy

@skim1420, @tomaslin FYI
Steven noticed this morning that unauthenticated calls to the /v2/ endpoint of quay were returning a 401. I'm guessing this is a recent change since the Kubernetes-Spinnaker deployment has relied on quay working without authentication for some time to display the Spinnaker quay images. This is OK according to the spec I realize now: https://docs.docker.com/registry/spec/api/#/api-version-check, but frustrating, since unauthenticated clients can't properly check if their registry supports the v2 endpoint. This endpoint is only used to determine if the docker provider is healthy in clouddriver, and only affects (helps) users who don't authenticate against their registry.

(docker) ignore 401 on docker health check when unauthenticated

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DisableAsgAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/EnableAsgAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/EnableDisableAtomicOperationUnitSpecSupport.groovy

- Updated to get current instance state by looking instances up by tag (In this case the asg name)
- This fixes an issue where an error would occur because we tried to register a terminated instance in the load balancer

Avoid attempting to register terminated instances in load balancer

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/cache/Keys.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy

We ran into an issue over the weekend where we somehow cached an image with an empty tag. Later, when trying to read the image, we got an `ArrayIndexOutOfBoundsException` because splitting the key on `:` only gave us four `String`s.
This PR adds two guards: one on the caching, one on the read.
@tomaslin @lwander PTAL

provider/docker: do not cache images without tags

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy

@duftler please review. This adds some logging to the LB cache retrieval since there seems to be a few intermittent scenarios where the LB cache data is corrupted. This will give us a bit more insight into what is going wrong.

provider/google: Added logging to LB cache retrieval.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy

@duftler please review. The LB cache call [here](https://www.google.com/url?q=https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy%23L48&sa=D&usg=AFQjCNGxYKGnvVXnp4-FgSiHCw2HX4xT3A) loops over all the cached LBs, which can be malformed in funky timing cases (e.g. if one of the GCP calls in the caching agent hangs, etc). This seems to be the only place this isn't handled properly.
We have been experiencing very intermittent issues where the load balancer we are operating on is well-formed, but another in the cache occasionally seems to be malformed, causing failures. This will give us some resiliency to these timing issues so completely unrelated operations don't fail …

provider/google: Handle partial LB cache data in fetch calls.

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/DockerRegistryCloudProvider.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy

We are hitting the `/find` endpoint a lot more these days, but it's frequently slow (15-40s), as it fetches > 40k images and their attributes.
We don't have trackDigests enabled, so there's no sense in fetching all the data for each key in this scenario - all the info is available in the key itself, so we can just parse it to get the data.
This change is tactical, performing the "find to get a list of all images" function in a lighter way when appropriate, i.e. when all Docker credentials are configured with trackDigests disabled.
@lwander @tomaslin PTAL - running this locally, I am getting the same results back in ~1s

provider/docker: handle find via key parsing if trackDigests disabled

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy

If the flag `useApplicationDefaultSecurityGroup` is set, don't create application default security group or attach it to the job

titus - allow suppression of application default security group

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy

@duftler FYI
This missing label would cause server groups created before the recent deployment patch to no longer be affected by disable/enable ops

(kubernetes) labeling bug fix

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesSecurityGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

* autoscalers weren't showing up
* buildInfo now shows what created a replicaset
* hashcode implementation for load balancers, server groups, & security groups were incorrect, leading to omitted results.
@duftler PTAL

(kubernetes) assorted cache fixes

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleBackendService.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleBackendServiceCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

@duftler @danielpeach please review. This PR caches `enableCDN` in the L7 and `backendService` caching agents and surfaces it for modification in L7 upsert.

provider/google: Support 'enableCDN' flag in L7 upsert.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/EnableDisableAsgDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/EnableDisableDestroyAzureServerGroupDescription.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/description/EnableDisableDescriptionTrait.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/helpers/EnableDisablePercentCategorizer.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/helpers/EnableDisablePercentageCategorizer.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/helpers/EnableDisablePercentageCategorizerSpec.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/EnableDisableGoogleServerGroupDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/DisableKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/EnableKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/EnableDisableKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/DisableKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/EnableDisableKubernetesAtomicOperationValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/servergroup/EnableKubernetesAtomicOperationValidator.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/DisableOpenstackAtomicOperationConverter.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/converters/servergroup/EnableOpenstackAtomicOperationConverter.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/description/servergroup/EnableDisableAtomicOperationDescription.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractEnableDisableOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/DisableOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/DisableOpenstackAtomicOperationValidator.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/validators/servergroup/EnableOpenstackAtomicOperationValidator.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/EnableDisableOpenstackAtomicOperationSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DisableTitusServerGroupDescription.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/EnableDisableServerGroupDescription.groovy

@duftler @cfieber PTAL
@spinnaker/reviewers FYI
As per @duftler's suggestion I made sure that any enable/disable that's been passed a "desiredPercentage" that doesn't implement this yet fails immediately. This was a fairly trivial change for all cloud providers, except for Openstack, so could @varikin or @derekolk or @drmaas PTAL?

(kubernetes) desiredPercentage enable/disable

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DetachInstancesAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpdateInstancesAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerLookupHelper.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerV2InstanceStateCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AwsSdkClientSupplier.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/ProxyHandlerBuilder.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/RateLimiterSupplier.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/RateLimitingRequestHandler.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeregisterInstancesFromLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/RegisterInstancesWithLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ImplementationLimits.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimitConfiguration.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimitConfigurationBuilder.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimits.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimitConfigurationSpec.groovy

a service limit is a key to Double value pair, for example a rateLimit against an API.
limits can be configured at a fine grained level (implementation and account) and fall back through
several levels of defaults (implementation default, account default, cloud provider default, global default).
configuration looks like:
````yaml
serviceLimits:
defaults:
rateLimit: 10
cloudProviderOverrides:
aws:
rateLimit: 15
accountOverrides:
test:
rateLimit: 5
prod:
rateLimit: 100
implementationLimits:
AmazonEC2:
defaults:
rateLimit: 200
accountOverrides:
prod:
rateLimit: 500
AmazonElasticLoadBalancing:
defaults:
rateLimit: 10
````
In this example:
* requesting the rateLimit for AmazonElasticLoadBalancing for any account would return 10
* requesting the rateLimit for AmazonEC2 for the prod account …

adds support for fine grained service limits.

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/DeleteEntityTagsDescription.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/UpsertEntityTagsDescription.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperationSpec.groovy
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperationSpec.groovy

* allow delete operation to specific a list of keys to delete, or `deleteAll` to remove a tag altogether
* allow partial update of entity tags, e.g. upsert operations against only specified tag members
@ajordens PTAL

provider/core: include tag metadata, allow partial upsert/deletes

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/admin/EntityTagsAdminController.java

Also added an EntityTagsAdminController that exposes `reindex` behavior.
The `reindex` is destructive in that it:
- Deletes the current active index
- Creates a new active index
- Indexes all entity tags (from `Front50`) into the new index
It's highly suggested to have an index template configured on the elasticsearch cluster:
```
{
"order": 0,
"template": "tags_v*",
"settings": {
"index": {
"number_of_shards": "6",
"number_of_replicas": "2",
"refresh_interval": "1s"
}
},
"mappings": {
"_default_": {
"properties": {
"entityRef": {
"properties": {
"entityId": {
"type": "string",
"index": "not_analyzed"
}
}
}
}
}
},
"aliases": {}
}
```

Support for querying by `entityRef.entityId` (both single and multiple)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DetachInstancesAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpdateInstancesAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/LoadBalancerLookupHelper.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerV2InstanceStateCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/DefaultAWSAccountInfoLookup.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AwsSdkClientSupplier.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/LoadingCacheMetrics.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/ProxyHandlerBuilder.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/RateLimiterSupplier.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/RateLimitingRequestHandler.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/SpinnakerAwsRegionProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeregisterInstancesFromLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/RegisterInstancesWithLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ImplementationLimits.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimitConfiguration.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimitConfigurationBuilder.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimits.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/core/limits/ServiceLimitConfigurationSpec.groovy

Yo dog, I heard you like reverts.
This reverts commit 251798241ee340239e04b43481fbb69f1e5a47ac.
Includes a fix for describing regions/zones at startup time.
Includes some extra instrumentation around the cached SDK clients.
Includes updates to how the SDK clients are constructed to support the standard AWS resolver chain for determining the current regional endpoint

Revert "Revert "adds support for fine grained service limits.""

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/PlatformErrorPropagator.groovy

There are calls in a few caching agents that are failing and only logging the failure, not throwing an exception. This is causing the agents to return and cache partially-complete objects that cause NPE trouble when we read them. We should just cause the caching agent to fail in these cases (agents don't write anything to the cache if they fail) so the cache isn't corrupted.

provider/google: Make LB caching agents fail if GCP call fails.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AwsSdkClientSupplier.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/RateLimitingRequestHandler.java

request handler was missing equals/hashcode so always resulting in a cache miss/new SDK client

fix loading cache key in AwsSdkClientSupplier.

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/DeleteEntityTagsAtomicOperationConverter.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/DeleteEntityTagsDescription.java

We will likely need to revisit this as some tags have credentials and some do not.

Convert `DeleteEntityTagsDescription` to NonCredentialed

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy

There is a valid case where an L7 LB can contain a backend bucket. This looks the same in the url map (it's a url string), but causes the backend service lookup callback to fail in the caching agent. In #1336 we made the caching agent fail for a cycle if one of the callbacks fails. If a user has a backend bucket in an L7, this will fail for _all_ cache cycles, which isn't desirable.
This PR filters out LBs that contain backend buckets in the caching agent so we don't write them to the cache.

provider/google: Exclude caching L7 LBs containing backend buckets.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy

- added a check to guard against deploying a server group with more than 5 SGs per instance in VPC

Ensuring that there are at most 5 security groups per instance (The max is configurable)

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ProjectSearchProvider.groovy

- Going to cover the current usage of the search endpoint in front50 (searches against name & apps)

Updating to use pagination-enabled project search endpoint from front50

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy

We had namespaces without replicaSets. This caused an NPE in caching the server groups.
```
2016-12-30 12:51:41.397  WARN 3277 --- [ecutionAction-6] .k.p.a.KubernetesServerGroupCachingAgent : Failure fetching autoscalers for all server groups in [list of namespaces]                                                                                                                                                       
java.lang.NullPointerException: Cannot invoke method collectEntries() on null object                                                                                       
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)                                                                                         
at …
```

Prevent NPE if a namespace doesn't have any replicaSets.

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppEngineSafeRetry.groovy
clouddriver-google-common/clouddriver-google-common.gradle
clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/deploy/GoogleCommonSafeRetry.groovy

@jtk54 or @duftler please review.
Moves `SafeRetry` logic to a base class in `google-common` so that https://github.com/spinnaker/clouddriver/pull/1351 can be rewritten.

(google-common) move safe retry to google-common

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/health/AmazonHealthIndicator.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/health/AmazonHealthIndicatorSpec.groovy

Fixes spinnaker/spinnaker#1357
Prefers SDK current region determination methods from the AmazonClientProvider to
work around issues where connectivity to us-east-1 is not available.

For AWS health indicator, don't explicitly set a region.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceTypeProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceTypeProviderConfiguration.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceTypeProviderSpec.groovy

example configuration:
````yaml
aws:
instanceTypes:
excluded:
- name: m1.large
- name: x1.32xlarge
regions:
- us-east-1
````

enable filtering out of specific instance types from the instanceTypes endpoint

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy

Kubernetes provider is failing on my juju charmed instance of kubernetes (the canonical distribution of kubernetes) because of missing null checks. This seems to fix my problem.
@lwander @varikin  take a look?

Adding null checks in kubernetes provider for caching.

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesConfigParser.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsInitializer.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.groovy

The service account's cert is always placed in `KUBERNETES_SERVICE_ACCOUNT_CA_CRT_PATH`, and the token in `KUBERNETES_SERVICE_ACCOUNT_TOKEN_PATH` by Kubernetes in every pod. If the user specifies `serviceAccount: true` in their clouddriver config, Spinnaker will read the cert & token out of those paths for authentication.
@duftler @danielpeach  PTAL

Allow Spinnaker to authenticate with k8s service accounts

---

clouddriver-aws/clouddriver-aws.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/bastion/BastionConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/bastion/BastionCredentialsProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/bastion/BastionProperties.groovy

This whole class is really Netflix specific and should probably just be removed from the project, but right now it is used also by front50 (via clouddriver-aws dependency).
I'll look at options to kill this off from this repo that don't also impact our ability to do local dev, but for now this makes it so that the BastionCredentialsProvider requires a running ssh-agent with valid identities added.
@spinnaker/netflix-reviewers FYI

use ssh-agent for bastion identity

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/AgentProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgLifecycleHookWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAsgLifecycleHookDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgentProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LifecycleSubscriberConfiguration.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/NotificationMessage.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/NotificationMessageWrapper.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonAsgLifecycleHook.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgLifecycleHookWorkerSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgentProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgentSpec.groovy

This also includes a subscriber capable of handling launch failure
notifications (subsequent PR will see this subscriber tag the ASG upon
failure).
This is <optional> and not enabled by default.

Support for registering notification hooks when an ASG is launched

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java

- Current sleep = 1000 * 2 ^ 3 => 1000 * 8, Changing to: sleep = 100 * 2 ^ 8 => 100 * 256
- First step at better handling of titus failures
- This is the current standard for most of our aws calls

(titus) Adjusting the retry settings for Titus calls

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DestroyAsgAtomicOperation.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperation.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/events/DeleteServerGroupEvent.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/events/OperationEvent.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/events/OperationEventHandler.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchServerGroupTagger.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/EntityRefIdBuilder.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/DeleteEntityTagsDescription.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/events/DeleteServerGroupEventHandler.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchServerGroupTaggerSpec.groovy
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/events/DeleteServerGroupEventHandlerSpec.groovy

The `DeleteServerGroupEventHandler` will delete all tags associated with
a deleted server group (if ElasticSearch is enabled).

An AtomicOperation can now return an <optional> set of OperationEvents

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy

This fix is important, because if we prematurely switch a replica set's
behavior to spawn disabled pods when owned by an autoscaler, the autoscaler
becomes useless, since it cannot create pods to reduce load on the pods still
serving traffic.
@duftler or @jtk54 or @danielpeach PTAL

(kubernetes) Update percent enable disable semantics

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy

Dockerhub doesn't implement /v2/_catalog, adding a lot of noise to the logs.
@duftler PTAL

(docker) Don't log stacktrace when catalog is empty

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppEngineUtils.groovy

Fixes bug where a query for services fails if an App Engine application has no services.
@jtk54 
I think this is a relic from an earlier refactor, since it is really, egregiously wrong.

provider/appengine fixes NPE when project has no services

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/utils/DateUtils.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/utils/DateUtilsSpec.groovy

OpenStack has another time format it uses.
So, we have:
2011-12-03T10:15:30 (local time)
2011-12-03T10:15:30Z (UTC time)
2011-12-03T10:15:30+01:00 (With time zone offset)
The last possibly not supported in OpenStack anymore, but why take a
chance. Also, it is parsed by the same formatter as the UTC time. There
must be a config option in OpenStack controlling this.

(Openstack) Support another time format.

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProvider.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusInstanceProvider.groovy

Given that instanceId is is the value needed to enable / disable via discovery API, it makes sense to link via this value instead of the titusTaskId in the metadata. This change will surface issues in discovery payload better at deploy time rather than at destroy time of the titus job.

Titus: link titus task to discovery instance with the instanceId

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GoogleOperationPoller.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GoogleOperationPollerSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleServerGroupTagsAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/DeleteGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperationUnitSpec.groovy

Measures how long each of the polling requests takes to complete.
This change is encapsulated within GoogleOperationPoller however every operation test is affected because they need to provide Spring with an auto-wireable Spectator Registry.
@duftler

Added instrumentation into GoogleOperationPoller.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesClusterProvider.groovy

It seems that groovy can't infer the type of a null `Set` object, and then crashes during dispatch. @leelasharma I think this fixes what you saw. @duftler PTAL

(kubernetes) handle lack of load balancer relationship in cluster cache

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

Default behaviour is to carry forward custom configured block devices mappings and spot prices from an ancestor ASG. Now supports `copySourceCustomBlockDeviceMappings` and `copySourceSpotPrice` to disable those behaviours (along with existing flag `copySourceScalingPoliciesAndActions` this allows the payload of a deploy operation to be entirely explicit about the resulting ASG).

(aws) adds flags on deployment to control propagating ancestor ASG settings

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/ARN.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LifecycleMessage.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LifecycleSubscriberConfiguration.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/ARNSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgentSpec.groovy

Porting the code that I added into Eureka to update application service states on termination faster. The agent will create an SQS queue in a single account and every region that spinnaker knows about.

Adding instance termination lifecycle to pull apps out of Eureka faster

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy

Altering the autoscaling lifecycle agent to have AutoScaling publish messages to SNS for fanout, rather than directly to a single queue.

Changing autoscaling lifecycle agent to publish to sns instead of sqs

---

Dockerfile
Dockerfile.slim
build.gradle
cloudbuild.yaml

This PR bumps the gradle project version (to get it working on Google Cloud Builder), and is the same process as https://github.com/spinnaker/fiat/pull/146
Currently, the built Docker container clocks in at a whopping 1GB. After this PR, Quay images should be ~427MB, and if built on GCB with the included `cloudbuild.yaml`, it is further reduced to a svelte 300MB.
@cfieber @tomaslin @duftler @lwander 
Tested by booting up in a K8 cluster.
cc: @leelasharma

Slims container by deleting compile-time requirements.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgLifecycleHookWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAsgLifecycleHookAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgLifecycleHookWorkerSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAsgLifecycleHookAtomicOperationUnitSpec.groovy

Amazon doesn't like dots in lifecycle hook names.
@robzienert or @cfieber PTAL

provider/amazon: clean lifecycle hook names

---

build.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateLoadBalancerStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategy.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/MigrateSecurityGroupStrategySpec.groovy

newer SDK version included ipv6 rules on ingress permissions. surely
hope this covers all the spots where those matter..

update to latest AWS SDK

---

clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/deploy/GoogleCommonSafeRetry.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy

`SafeRetry` used to retry once even if the initial HTTP status code was in the "don't retry" list. Now it doesn't.

fix(provider/google): Don't retry on 'successful' codes in SafeRetry.

---

build.gradle

@duftler @cfieber @ewiseblatt FYI. Updating just Clouddriver overnight in case something goes wrong -- it's 10x faster to roll back 1 thing instead of 10 :)

chore(gradle): Bump spinnaker-gradle-project version.

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/BulkUpsertEntityTagsAtomicOperationConverter.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/UpsertEntityTagsAtomicOperationConverter.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/BulkUpsertEntityTagsDescription.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/validators/BulkUpsertEntityTagsDescriptionValidator.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperationSpec.groovy

Trying to do a bunch of concurrent operations against a single entity does not work, as you can easily get into a race condition (since the tagging operation could take up to a second).
This allows users to create multiple entity tags at once, using the same structure as they're using to create a single tag.
I tried to get fancy and parallelize operations, but that just re-introduced the same race condition, so...I just limited it to 100 tags at a time.
@cfieber PTAL

(entityTags) allow bulk update of entity tags

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/SpectatorRedisCacheMetrics.groovy

redis cache was wired for metrics but the concrete implementation was lost along the way, adding one back

Implement redisCache.cacheMetrics interface

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy

@duftler 
In Kubernetes 1.5 pods are returned as a null object rather than an empty array.

(kubernetes) Complete enable/disable early when there are no pods to operate on

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy

The idea being that tag name's could be re-used across namespaces, either
intentionally or accidentally.
Permissions / restrictions could also be applied to namespaces vs. individual
tag names.
Will need to sort out re-indexing and assign a proper namespace to all
existing tags.
Depends on spinnaker/front50#203

Introduce a new `namespace` attribute to `EntityTag`

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperationSpec.groovy

While it's great that we're allowing users to submit batches of 1000 tags in the bulk upsert operation, it doesn't actually work unless Front50 is configured to handle GET requests for URLs that have 1000 tag ids in them, which...it almost certainly won't.
So: let's perform the upserts in batches of 50. I considered removing the 1000 tag limit because of this, but, considering we're storing the results and returning them to Orca, I'm a little concerned about the payload size and the pain Orca will feel when marshalling/unmarshalling the JSON of, e.g. 25,000 tags.
If any @spinnaker/reviewers know anything about Rx, I'd appreciate some eyes on this.

EntityTags: batch bulk operations in groups of 50

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidator.groovy
clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppengineAtomicOperationConverterSpec.groovy
clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidatorSpec.groovy

Allows you to update top-level application config during a deploy operation. There seem to be good reasons for doing so, and I can't see any reason to stop people from doing it.

(appengine) switched from app.yaml path to general config filepaths

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperation.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployHandler.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/events/CreateServerGroupEvent.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/events/CreateServerGroupEventHandler.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/events/CreateServerGroupEventHandlerSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy

This PR has already been reviewed. had to revert to fix a javadoc compilation error
- Added a createServerGroupEventHandler to handle create server group events
- Deletes tags from servergroup name on deploy

(aws & titus) Deleting tags from server group upon creation

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandlerSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperationSpec.groovy

Addresses SPIN-2354, where an ELB update that has an invalid new listener won't revert any removed listeners, causing an ELB to potentially lose traffic.

Rollback deleted ELB listeners on add failure

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy

With this update, people will be able to choose between sending to SNS and fanning out to SQS queues (current behavior) or sending lifecycle events directly to an SQS queue. I'm hoping that cutting out SNS from the equation will allow us to squeeze out more performance.

feat(aws): Allow termination lifecycle hooks to target SQS directly

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy

Adding a builder so that it is easy to instantiate credentials from Halyard without having to specify the arguments in the proper order.
@lwander @varikin @drmaas please take a look.

(openstack) add accound credentials builder

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy

There are two cases where a DockerRegistryAuthenticationException stating "Docker registry must support 'Bearer' authentication." was propagated instead of a 401, causing issues:
1. checkV2Availability always fails for a registry that only supports basic auth
2. If user specifies an incorrect password, the error thrown is the DockerRegistryAuthenticationException instead of the more accurate "401 Unauthorized" error

Propagate 401 error for basic auth docker registry

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentials.groovy

Fixing accidental private method. @lwander PTAL

(openstack) bugfix: make credential build method public

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/NullOpUserDataProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/UserDataProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy

Assuming someone had actually implemented a UserDataProvider in their own codebase, this change would be compatible (introduced new preferred method with a default impl that delegates to the deprecated method)

refactors UserDataProvider interface to accept full LaunchConfigurationSettings

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsInfrastructureProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/EddaTimeoutConfig.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/ProxyHandlerBuilder.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgentSpec.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy

This is a bit messier than I hoped, having to wire EddaTimeoutConfig into a few spots where behaviour changes if edda is enabled. It didn't feel like sticking that right into the credentials object would be right either..
There are a few ignored checks for eddaEnabled in caching agents where there is already a reasonable fallback if we don't get a lastModified timestamp back from edda

Adds configuration option to regionally disable edda

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/health/AmazonHealthIndicator.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java

This undoes some changes that were introduced in #1239 
The DEFAULT_REGION constant in AmazonClientProvider is there as an indicator that the region should be resolved to the current region, and that happens in AwsClientSupplier via SpinnakerAwsRegionProvider.
@qqshfox Can you confirm that this still works for you, provided you are running on an EC2 instance within cn-north-1 (to get the region from instance metadata) or you have set the AWS_REGION environment variable to cn-north-1 ?

fix(aws) : region default resolution does not have to be statically initialized

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonClusterController.groovy

We've always returned the first 200 activities because (a) the describe call returns 100 results at a time and (b) writing `while` loops is hard. Might as well bring back the next 300.
@cfieber PTAL WCGW

feat(provider/aws): retrieve 500 scaling activities instead of 30

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleAgentSpec.groovy

Allows users to adjust the termination lifecycle agent poll time. We should see a huge gain in performance for our average hooks reducing this from the default.

perf(aws): configurable termination lifecycle agent poll time

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorker.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerSpec.groovy

Two changes:
1. Add configuration for message retention period for SQS queues. The default value is 4 days, which is way too long for the purposes of this worker. New default is 2 minutes.
2. Cleaned up the SQS permission IAM based on feedback from cloud sec. The policy it generates is now a lot simpler.

feat(aws): termination lifecycle worker config; cleaner SQS IAM

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy

Some components in Netflix code need to conditionally filter out scaling policies that are copied to a new ASG. For OSS, this has no effect.

feat(aws): Adding conditional scaling policy copy method

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java

Encountered an issue in test where entity tags was returning a value with a null value type. Filtering out these values.
@ajordens FYI

fix(elasticsearch): Fix NPE generated when an entity tag type is null

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorker.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerSpec.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy

A couple items in here:
1. Allow setting specific eureka maximum retry settings when calling from termination lifecycle worker (reducing defaults from 10 retries to 3).
2. Updating worker to only run on caching instances
3. Short-circuit eureka calls if the application name cannot be found from an ASG and if the ASG/instance no longer exists. This can happen when processing stale messages. Rather than waste cycles attempting to remove it from discovery, move on with life.
@ajordens PTAL

perf(aws): termination lifecycle eureka perf improvements

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusRestAdapter.java
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClientSpec.groovy

It seems that OkHttp3 doesn’t think that the ^ needs to be escaped as part of the query string.
```
@Grapes(
@Grab(group='com.squareup.okhttp3', module='okhttp', version='3.6.0')
)
import okhttp3.HttpUrl
println new HttpUrl.Builder()
.scheme("http")
.host("www.google.com")
.addQueryParameter("q", " titustestapp-clony-^1.0.0-v000")
.build()
```
gives `http://www.google.com/?q=%20titustestapp-clony-^1.0.0-v000`
Looking at the code, it looks like they don't consider ^ to be something that needs to be encoded
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/HttpUrl.java#L292
The titus API requires this values to be encoded, this fix changes that behavior so that query components are encoded according to the Titus API

fix(titus): okhttp doesn't properly url encode the ^ in the query string

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/view/ServerGroupViewModelPostProcessor.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

Allows extension of mutating ServerGroup API response data. This is
needed to prevent Deck incorrectly rendering some internal features.

feat(web): ServerGroup view model post processor interface

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorker.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureConfigurationProperties.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerSpec.groovy

After talking to cloudperf, we're mostly interested in processing messages
as quick as possible. We don't really care if discovery knows about the
application or instance, so we'll only retry on network errors, otherwise,
we'll just move onto the next message.

perf(aws): Simplifying termination lifecyle to not lookup app info first

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy

Fixed missing hostNetwork filed for job which caused missing property exception during "Run a Job" deployment.

fix(kubenetesjob): Fixed missing updated hostNetwork option for job.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/cache/Keys.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/GoogleInfrastructureProvider.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleGlobalAddressCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalAddressCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/config/GoogleInfrastructureProviderConfig.groovy

Caching IP addresses to suggest for forwarding rule IPs in LB upserts. The support for setting IPs exists in the LB upsert operations, but there is some frontend work to actually invoke that path. Currently we leave the IPs blank and use dynamic ephemeral IPs.
@varikin This is the first bit of https://github.com/spinnaker/spinnaker/issues/1519.

feat(provider/google): Added caching for external IP addresses.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesLoadBalancer.groovy

If not set, account of loadBalancerDescription will be blank. That will be used in situations like updating load balancers.

fix(kubernetes): Set account in loaderBalancerDescription

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackImageV1Provider.groovy
clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackImageV1ClientProviderSpec.groovy

This fix changes the behavior of the OpenstackImageV1Provider to return all images from Openstack rather than just the first page.
This is necessary for Openstack environments with greater than 25 images.

fix(openstack): Fix to have the OpenstackImageV1Provider return all images when requested.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java

Previously when new clouddriver instances would startup, they would delete & recreate every docker registry secret. If this coincided with a deploy, it would fail because it wouldn't have the necessary image pull secrets. This fixes this by 
1. using edit rather than destroy + recreate to update.
2. not replacing secrets that don't have changes.

fix(kubernetes): Fix multi-instance clouddriver secret churn

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyAsgDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy

Add clouddriver support for spinnaker/spinnaker#1548.
This introduces two new fields for the ASG server groups: `disabledGroupMetrics` and `enabledGroupMetrics`.
Each list is sent as the `metrics` flag to the appropriate `disable-metrics-collection`/`enable-metrics-collection` API.
These API calls can be made idempotently. For example `disable-metrics-collection` against previously disabled metric(s) will return in success.
If a user specifies a metric in both groups then the `enable` call will take precedence.

feat(aws) Support enabling/disabling Auto Scaling Group metrics

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/ResizeKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy

Before this fix, all scaling activities were applied to replica sets, even when a corresponding deployment existed. This caused the replica set & deployments to fight over the number of pods.

fix(provider/kubernetes): Deployment scaling

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineServerGroup.groovy

A change in https://github.com/spinnaker/clouddriver/pull/1564 caused the capacity values to sometimes be `null`, which caused an NPE in Orca, which broke several operations. This fixes that.

fix(appengine): capacity values for automatic scaling

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy

Seems the dashboard expects resource refs to have capitalized [kinds](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#types-kinds) even when the kubelet doesn't seem to mind

fix(provider/kubernetes): Kinds should be capitalized for k8s dashboard

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleLoadBalancerCachingAgent.groovy

New features for GCP causing issues with out caching agents: https://cloud.google.com/compute/docs/protocol-forwarding/.

fix(L4 caching): Ignore 'targetInstances' in regional forwarding rules.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

This was causing a bug when loading autoscaler details

fix(kubernetes): Use 'kind' constants rather than strings

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancerHealth.groovy

The current enumeration does not support the offline state. This results in an exception when the openstack provider is attempting to read the current status.
Fixed issue spinnaker/spinnaker#1556

fix(provider/openstack): Added OFFLINE status in LB Health enum

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperationSpec.groovy

ElasticSearchServerGroupTagger supplies a singletonList(entityTag) which
causes an issue when updated tags are merged over existing tags.
Opt'd for a generic fix in `EntityTags.setTags()` rather than a point
fix in `ElasticSearchServerGroupTagger` to prevent a future recurrence.

Ensure that `EntityTags.tags` is always a modifiable list

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AmiIdResolver.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ResolvedAmiResult.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperationUnitSpec.groovy

We don't really need (and probably can't?) tag or modify launch permissions on a public AMI when performing an AllowLaunchOperation.
@cfieber PTAL

fix(amazon): do not tag/share public images on AllowLaunch

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy

The current error message is pretty unhelpful in the case of private third-party AMIs. This error doesn't cover all of the cases of this error, but it's certainly one of the most likely cases.
cc @spinnaker/netflix-reviewers PTAL

chore(aws): Make missing AMI error more actionable

---

clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/provider/ConsulProviderUtils.groovy

@lwander PTAL
It'll be helpful to not swallow this error when debugging. It will print for every instance that spinnaker manages that doesn't have consul running.

chore(consul) add debug log for consul checks

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupControllerSpec.groovy

This PR makes clouddriver return decorated docker containers when using dockerRegistry/images/find.
This is done so that we can start moving the handling of docker containers in spinnaker over to decorated artifacts.

feat(artifact/decoration): Artifact decoration spinnaker/spinnaker#1348

---

clouddriver-oracle-bmcs/clouddriver-oracle-bmcs.gradle

moves logic out of inline gradle script and into tasks wired into the task graph
The previous config suffered from an evaluation order problem where the SDK unzipping would happen as the build script was interpreted while the clean task would happen during task execution so doing a `./gradlew clean build` would extract the SDK then clean it up then try to do the build
@simonlord PTAL

chore(build): fix build config for oracle bmcs cloudprovider

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java

This affects the `/admin/tags/metadata` and `/admin/tags/reindex` endpoints.
A subsequent PR will introduce a `/repair` that will reindex _only_ the deltas
detected between Front50 and Elasticsearch.
These deltas can occur during a full flush + reindex operation as tags will
still arrive while the elastic search index is being re-created.

refactor(entitytags): Switch to using `refresh=false` when retrieving all entity tags from Front50

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentialsInitializer.groovy

I was testing out some account behavior in deck (primary vs. secondary accounts) when I noticed Azure behaved differently than all other providers. Now the primary Azure credential will show up as a primary account by default.

fix(provider/azure): Default environment and accountType to accountName

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonAsgLifecycleHook.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

With this PR, failure to attach lifecycle hooks will not fail the task.
`catch (Exception) vs catch (AmazonServiceException)`

fix(aws): Raise an exception when a lifecycle hook specifies an invalid transition

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy

This pull request adds the capability to specify the server group sequence during a kubernetes deployment. This matches the functionality in `clouddriver-aws`.

feature(kubernetes): add ability to specify sequence number when deploying kubernetes server group

---

clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/provider/ConsulProviderUtils.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/deploy/ops/servergroup/AbstractEnableDisableOpenstackAtomicOperation.groovy
clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackInstanceCachingAgent.groovy

Adding consul enable/disable for openstack provider modeled after the google implementation (https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/AbstractEnableDisableAtomicOperation.groovy#L83).
Adding try/catch for getHealths in OpenStack caching.
@lwander PTAL

feat(provider/openstack): consul enable/disable

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceProvider.groovy

We have a feature request to include server group and cluster names in AWS instance details so these fields can be made available in insight links.
@cfieber or @ajordens  or other @spinnaker/netflix-reviewers PTAL - not the best groovy, probably

feat(amazon): include cluster, server group in instance details

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalLoadBalancerAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleLoadBalancerAtomicOperationUnitSpec.groovy

Orca's orchestration for upserting a Google load balancer does not contain a task to wait for the state of the platform to show that a load balancer was created (for good reason, that would be a complicated operation). Instead, Orca waits for Clouddriver to execute this operation and do a force cache refresh. We should wait for the whole load balancer to be created in the platform before we exit this upsert operation, so we wait for the forwarding rule to be created before continuing so we _know_ the state of the platform when we do a force cache refresh.

fix(provider/google): Wait for forwarding rule creation in LB upserts.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy

`description.namespace` is null for the default namespace. `validateNamespace` sanitizes the description's namespace in this case, so we should use the sanitized namespace later on in this operation.

fix(provider/kubernetes): Use sanitized namespace in enable/disable.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AddSpinnakerUserToUserAgentRequestHandler.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java

Adds `aws.client.addSpinnakerUserToUserAgent` configuration option that, if enabled, will include the currently authenticated Spinnaker user in the user agent string that is sent with all AWS requests.  This string is present in CloudTrail logs and can be used to correlate end user actions to AWS modifications.
This is off by default.

feat(aws/auth): optionally include spinnaker authenticated user in aws requests

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/KubernetesUtil.groovy

StatefulSet model is not available in the fabric8 client currently used.  This upgrades fabric8 to the latest client.  Also had to import the Job model class from a different location.

refactor(kubernetes): Update fabric8 client to 2.3.1 for StatefulSet

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperationUnitSpec.groovy

This is a proposed fix for [https://github.com/spinnaker/spinnaker/issues/1632](url)
During the allow atomic launch step, it was only looking for AMI using the source account. Normally it works fine as the AMIs can be shared between accounts. However, when using EBS backed AMI, AWS doesn't allow sharing. The proposed fix is to also make an attempt to look for the AMI in the target account where we are doing the deployment (as in the EBS case, the AMI will have to be in the same account where the deployment happens anyway, due to the limitation of not allowing sharing). If the AMI is found there, we can return with it as the rest is no-op.

Fix issue 1632: not able to find AMI in target account during deploy

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/ArnUtils.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/ARN.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/DefaultAWSAccountInfoLookup.java

GovCloud ARNs don't fit the standard model, much in the same way that the china region does.
This PR adds support for GovCloud Style Arns to fix spinnaker/spinnaker/issues/1698

fix(provider/amazon):  add gov-cloud special case to arn patterns

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DisableAsgAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/EnableAsgAtomicOperationUnitSpec.groovy

Reworks instance lookup logic in #1255 to prefer a query against known instance ids instead of a query with a tag filter.
The current implementation can time out with large instance counts in a region

fix(aws: enable/disable) faster instance lookup for enable/disable

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/RequestQueue.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/RequestQueueConfiguration.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PollCoordinator.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequest.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/Promise.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/RequestDistributor.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationControllerSpec.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterControllerSpec.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueSpec.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/RequestDistributorSpec.groovy

When enabled submitted API requests are first queued by application. Requests are popped
one at a time from each application queue and submitted for execution. This should mitigate
one particular application user hammering the API and degrading service for others.
In addition the requests are executed on a fixed size thread pool so no matter how many requests
are submitted only a bounded number will be executed at any time.
The request thread is blocked until the request is serviced from the threadpool or times out.

feat(request buffer): optional buffer to distribute api requests

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/edda/EddaApi.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/edda/TargetGroupAttributes.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/edda/TargetGroupHealth.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonTargetGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy

When available, use edda for TargetGroupAttributes, TargetHealth, and Listeners.

feat(provider/amazon): Use edda views if available for TargetGroup* and Listener caching

---

clouddriver-loadtest/src/main/resources/logback.xml

Observed a higher percentage of failures when the default DEBUG logging
was enabled.

fix(loadtest): Adjust logging configuration

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequest.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/Promise.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PromiseTimeoutException.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueSpec.groovy

* renames pooledRequest.execute.time to pooledRequestQueue.enqueueTime to reflect the time spent waiting for a thread to run on
* adds pooledRequestQueue.totalTime to capture the total time from submission to completion (either result, exception or timeout)
* adds a specific exception with the request times out to differentiate between timeout in the queue vs a timeout as part of normal processing.

fix(requestqueue): adds additional instrumentation.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy

Provide a way to define a set of labels on a Run Job pod. Useful for
being able to pin point specific pods for logging purposes. Adds a Map
for labels in the Run Job description and applies them if they're set.
Does not impact current without a `labels` field.
Part of [#1683](https://github.com/spinnaker/spinnaker/issues/1683). Deck PR coming soon.
@lwander PTAL

feat(provider/kubernetes): Run Job Pod Labels

---

clouddriver-oracle-bmcs/clouddriver-oracle-bmcs.gradle
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/cache/Keys.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/OracleBMCSWorkRequestPoller.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/CreateOracleBMCSLoadBalancerAtomicOperationConverter.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/description/CreateLoadBalancerDescription.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/handler/BasicOracleBMCSDeployHandler.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/AbstractEnableDisableAtomicOperation.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/CreateOracleBMCSLoadBalancerAtomicOperation.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/DestroyOracleBMCSServerGroupAtomicOperation.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/ResizeOracleBMCSServerGroupAtomicOperation.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/model/OracleBMCSServerGroup.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/OracleBMCSInfrastructureProvider.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSLoadBalancerCachingAgent.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/config/OracleBMCSInfrastructureProviderConfig.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/view/OracleBMCSLoadBalancerProvider.groovy
clouddriver-oracle-bmcs/src/main/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/security/OracleBMCSNamedAccountCredentials.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/converter/CreateOracleBMCSLoadBalancerAtomicOperationConverterUnitSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/handler/BasicOracleBMCSDeployHandlerSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/CreateOracleBMCSLoadBalancerAtomicOperationSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/DisableOracleBMCSServerGroupAtomicOperationSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/EnableOracleBMCSServerGroupAtomicOperationSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/deploy/op/ResizeOracleBMCSServerGroupAtomicOperationSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSNetworkCachingAgentSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSSecurityGroupCachingAgentSpec.groovy
clouddriver-oracle-bmcs/src/test/groovy/com/netflix/spinnaker/clouddriver/oraclebmcs/provider/agent/OracleBMCSSubnetCachingAgentSpec.groovy

You can create an LB with health check and listener.
You can deploy a servergroup and have it attach to the loadbalancer.
Integrates with:
- Deploy
- Disable
- Enabled
- Resize

feat(provider/oraclebmcs): Adding initial loadbalancer support

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy

Adds the ability to configure Pod annotations on the pod created by the
Run Job stage. Similar to #1683, this is useful for pin pointing pods
for logging purposes. There is a Deck PR which adds support for both
Labels and Pods.
@lwander very similar to the last one. PTAL.

feat(provider/kubernetes): Annotation config

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/QueuedRequestException.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/RequestQueue.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/RequestQueueConfiguration.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequest.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/Promise.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PromiseNotStartedException.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueSpec.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/RequestDistributorSpec.groovy

Allows a separate (shorter) timeout for how long a message can queue up before being rejected.
Requests that time out from the request queue fail with HTTP 429

fix(requestQueue): differentiate timeout in queue vs in processing.

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java

I wanted a way for a single Fiat instance to come up (and resync) shortly after a previous one is taken down. Because Fiat's default timeout is significantly longer than Clouddrivers (10min vs 30s), I was having to wait for the whole timeout to elapse before a resync would occur. Deleting the lock key is the proper way to get around this.  I plan on using this within a shutdown hook in Fiat.
As for Clouddriver, `unschedule` is used when accounts are deleted, which should probably cleanup its keys during deletion anyway.

fix(cats): Remove lock key from Redis when agent is unscheduled.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/callbacks/Utils.groovy

Avoids parsing xpn resources that are missing or empty. The immediate use case where this arises is cloning a server group that has `network = default`, and hence no `subnet` defined. The child deploy description will not have a `subnet` present, which we can't parse even though the description is valid.

fix(provider/google): Handle empty xpn resources.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/KubernetesVolumeSourceValidator.groovy

Having a configMap volume source with zero key/path pairs is allowed by kubernetes, but is rejected by the clouddriver pipeline validator. Having no items in a configMap already works fine if you manually create a server group, presumably b/c server group validation is implemented separately. However if you take this manually created server group and import it as your server group template in a pipeline, the resulting pipeline does not execute b/c of the strict validation that is loosened by this PR.
Addresses https://github.com/spinnaker/spinnaker/issues/1622

fix(kubernetes): allow configMaps to have no items

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy

Fixes an issue when cloning an ASG across regions - we're currently trying to look up scaling policies from the target region instead of the source, which will cause the operation to either a) fail when it can't find the source ASG or b) copy potentially incorrect scaling policies if there is an ASG in the target region with the same name as the ASG in the source region.

fix(amazon): send correct source region when copying scaling policies

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy

Allows Service Account to be configured for both Server Group and Run
Job Pipeline stage. I also added it to the `fromReplicationController`
in the event that someone is using ReplicationControllers pre-Spinnaker.
@danielpeach PTAL
@lwander FYI

feat(provider/kubernetes): Configure Service Acct

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/cache/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesConfigMapCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesSecretCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServiceAccountCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy

Makes ConfigMaps,Secrets & ServiceAccounts cacheable and searchable.
This will be used to populate dropdowns in Deck in the appropriate
places. Lots of repetative code throughout and I'm not sure I totally
understand the relationship between hydrators and keys, though there
probably isn't much of one in this case.
@lwander @danielpeach hopefully this isn't too cringe inducing.

feat(kubernetes): cache additional resources

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiAdaptor.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesAutoscalerStatus.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesServerGroup.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesServerGroupCachingAgent.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/1651
This updates kubernentes-client with this fix: https://github.com/fabric8io/kubernetes-client/pull/780
Changes between the two APIs:
> * Field CPUUtilization which was a nested structure CPUTargetUtilization in HorizontalPodAutoscalerSpec was replaced by TargetCPUUtilizationPercentage which is an integer.
> * ScaleRef of type SubresourceReference in HorizontalPodAutoscalerSpec which referred to scale subresource of the resource being scaled was replaced by ScaleTargetRef which points just to the resource being scaled.
This is necessary for supporting Kubernetes 1.6, but breaks support for Kubernetes 1.1. I'm not sure what the officially supported versions are.

fix(provider/kubernetes): Update HPA endpoint for k8s 1.6

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy

Adds support for AWS Elastic Block Store volumes. Can serve as a good
example for further supporting other volume source types.
Note: EBS Volumes cannot be mounted ReadOnly even though the client library says it can be. When I attempted to add support for ReadOnly, Kubernetes failed to mount the volume with an error saying as much. Thus, it was left out.
Partially addresses spinnaker/spinnaker#1826
@lwander PTAL

feat(provider/kubernetes): Support EBS Volumes

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy

This addresses the following issue found in review [1]:
> If I have both a TCP and SSL load balancer, this endpoint fails:
> {clouddriver}/gce/loadBalancers.
[1] https://github.com/spinnaker/deck/pull/3894#pullrequestreview-49475804

fix(provider/google): Add missing break when listing load balancers

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleSslLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleTcpLoadBalancerAtomicOperation.groovy

This addresses the following issue found in review [1]:
> Changing the port on an SSL load balancer in the UI has no effect
[1] https://github.com/spinnaker/deck/pull/3894#pullrequestreview-49475804

fix(provider/google): Use port from frontend when upserting SSL Proxy

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidator.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/gcsClient/AppengineGcsRepositoryClient.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/gitClient/AppengineGitRepositoryClient.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineRepositoryClient.groovy

@danielpeach 
I refactored the old gitClient into an interface that can update a "version".
The gist is you specifiy the repositoryUrl as a gcs path rather than an github HTTP url.
I dont do anything with the "branch".

feat(appengine): Permit deployments from gs:// repositories

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

- Takes a list of applications and return an aggregated summary

feat(servergroups): Add endpoint to retrieve server groups by applications

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy

Kubernetes allows creation of "headless" services by setting
`spec.clusterIP` to `None`. This allows `None` as the only non-ip value
that could be accepted.
Addresses spinnaker/spinnaker#1836
@lwander PTAL

fix(provider/kubernetes): Allow None Cluster IP

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PromiseNotStartedException.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PromiseTimeoutException.java

quick workaround for GenericExceptionHandler

fix(request_queue): explicitly add http annotations to exception subclasses

---

clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueSpec.groovy

@cfieber 
A speculative change explained in the offline email.
I'm not sure this will fix the problem but due to flakiness and circumstances in which the test fails, it is difficult to test on its own. I dont see a downside in this unless the test is intended to verify a time constraint.

fix(test): Mitigate timeout due to compile load

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/CloneKubernetesAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/CloneKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/converters/servergroup/CloneKubernetesAtomicOperationConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy

Fixes cloning Server Groups across accounts. The previous implementation
was relying on the credentials of the target account which meant
cloning server groups that didn't exist in the target account failed.
This adds a `sourceCredentials` field to the Clone description that is
used to verify the source server group against the correct account.
Fixes spinnaker/spinnaker#1829
@lwander PTAL

fix(provider/kubernetes): Cross Account Clone

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/BlockDeviceConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/BlockDeviceConfigSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy

**For review only - should not be merged yet**
`gp2` is going to be the default volume type at some point in the very near future, which will cause us grief at Netflix when we update our AWS client version.

fix(amazon): explicitly declare volumeType for default block devices

---

clouddriver-web/clouddriver-web.gradle
clouddriver-web/config/clouddriver.yml

Fighting this one sucked. Dunno why the `resolutionStrategy` way didn't work. Allegedly the spring boot gradle plugin for boot 2.0 won't automatically apply this dependency management plugin.

chore(jedis): Downgrade Jedis version because of runtime error

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy

Helpful to include the actual target tracking config when copying.
(Missed this line when moving code over from our internal repo)

fix(amazon): include targetTrackingConfiguration in scaling policy copy

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy

This doesn't actually fix the root cause of the error, but does prevent this section of code from an infinite loop if the condition is encountered. Error condition is: A disabled server group, which has an instance terminated, will not have its list of instances refreshed; causing the EC2 describe instances call to permanently fail since the instance no longer exists.
I want to get this short-circuit in prior to figuring out a long-term fix for the actual behavior. Correct behavior was in tagged server groups, but was too slow for something. I suspect we can get everything we need from `DescribeAutoScalingGroupInstances`'s `HealthStatus` field:
```
// The last reported health status of this instance. "Healthy" means that the
// instance is healthy and should remain in service. "Unhealthy" …
```

fix(aws): Short-circuit failed describe instances if repeated

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AWSServerGroupNameResolver.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AWSServerGroupNameResolverSpec.groovy

Right now, we end up throwing a NPE trying to parse the keys, which is understandably cryptic to users.
Happy to move this validation further up the stack, but this should be sufficient to get a cleaner error message to folks in the UI.

fix(provider/amazon): throw better exception on invalid cluster name

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgentSpec.groovy

This PR provides the ability to control the CATS cache TTL of a `KubernetesInstance` by adding a metadata annotation, `cache.spinnaker.io/ttl`, to the `Pod`.

feat(kubernetes): Provides ability to drive pod cache TTL via metadata attribute

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy

Older versions of k8s have null annotations by default.

fix(provider/kubernetes): Fix instance annotation

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/agent/KubernetesInstanceCachingAgent.groovy

Older versions of k8s have null annotations by default.

fix(provider/kubernetes): Fix instance annotation (#1782)

---

cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cluster/DynoClusteredAgentScheduler.java

Finally got local dyno working again, fixing self-heal logic that heals itself a lot too aggressively.

fix(dynomite): Correctly handle lock TTLs while checking to self-heal

---

cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java

I noticed that the cache drift that was occurring in Dynomite is due to stale hashes. This PR tries to tackle the problem in two parts:
1. try/catch blocks around setting cache data. Any errors raised by Redis or Dyno will cause the batch to be removed from updated hashes.
2. Hashes are refactored from a single map to individual keys and then TTL'ed. This is a fail-safe in case part 1 doesn't cover all of the conditions correctly.

fix(dynomite): Error-corrected cache hashing, TTLed individual hash keys

---

cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
cats/cats-dynomite/src/test/groovy/com/netflix/spinnaker/cat/dynomite/cache/DynomiteCacheSpec.groovy
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/SpectatorRedisCacheMetrics.groovy

Refactored `DynomiteCache` to handle merge ops more naturally instead of reusing the `RedisCache` batching logic. This also affords us much better control with hashes invalidation. Lastly, jittering hash TTLs to avoid the write spikes we were seeing.

refactor(dynomite): Merge now caches a single item at a time

---

cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
cats/cats-dynomite/src/test/groovy/com/netflix/spinnaker/cat/dynomite/cache/DynomiteCacheSpec.groovy

Would explain why writes shot through the roof with the latest refactor.
🤦‍♂️

fix(dynomite): Skip cache op if no keys need to be set

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/job/RunKubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy

adds support for dns policy on server group definition. 
https://kubernetes.io/docs/api-reference/v1.7/#pod-v1-core
@lwander PTAL.

feat(provider/kubernetes): add dns policy

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/DeleteSecurityGroupAtomicOperation.groovy

fix(provider/aws): Force delete security groups would accidentally delete ip range rules that existed next to SG ingress rules

---

cats/cats-dynomite/cats-dynomite.gradle
cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java

The transient errors in check preconditions appears to be related to cache invalidation. I've added some retry logic to both `merge` and `evict` options, hopefully that'll ensure a higher rate of success (although I'm not seeing many / any errors over a 12 hour period).
I've also re-ordered `merge` a little bit, so that hashes are set as the very last step, and then demoted updating the members index just before the hashes. This should reduce the risk of having a members index that is stale / inaccurate. Similarly, I moved updating the sets in `evict` to be the first operation.
@cfieber PTAL / WDYT?

fix(dynomite): Retries and moving index ops to last step

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy

Spinnaker fails when copying ASG alarms if any existing alarms (created outside Spinnaker) are using percentile values.

fix(amazon): Support `ExtendedStatistic` parameter when copying ASG alarm

---

cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteNamedCacheFactory.java
cats/cats-dynomite/src/test/groovy/com/netflix/spinnaker/cat/dynomite/cache/DynomiteCacheSpec.groovy
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactory.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/JedisCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/SpectatorDynomiteCacheMetrics.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/SpectatorRedisCacheMetrics.groovy

Now that we're running Dynomite in staging and performing loadtests,
we've been seeing dramatically reduced performance due, in part, to
the aggregate overhead of performing individual network calls for
each key, whereas in vanilla Redis, we were able to multi-key op and
pipeline requests.
This is a swing back in the direction of larger keys, in an effort
to reduce the overhead of network call volume.
@spinnaker/netflix-reviewers PTAL / FYI

refactor(dynomite): Consolidating cache & hash structs into hashsets

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy

Reported in Slack (from multiple users) that userdata will transiently get a newline inserted at the beginning, causing cloud-init to fail.

fix(userdata): Ensure whitespace is trimmed from userdata

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/KeyParser.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/provider/agent/Namespace.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SearchController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/SearchControllerSpec.groovy

* initial step at allowing more advanced searching by letting the
cloudproviders define their own key parsing implementations.  e.g., for
AWS, allows the ability to query by account and region:
`http://clouddriver/search?account=prod&region=us-east-1` (note that
`account` and `region` are valid namespace parts for certain keys.

feat(search): enhance searching capabilities

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidator.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AnnotationsBasedAtomicOperationsRegistry.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/ApplicationContextAtomicOperationsRegistry.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationConverter.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationsRegistry.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/VersionedCloudProviderOperation.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/VersionedOperationHelper.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/AnnotationsBasedAtomicOperationsRegistrySpec.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/config/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AccountCredentials.java
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/ProviderVersion.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy
lombok.config

This is intended for the v2 k8s provider.
The idea is that accounts can expose a "version" which converters,
validators, and (in the future) caching agents will use to determine
when to be run. This is also useful if we want to start moving features
into release tracks, as we can flag operations with a "beta" version
that requires accounts to be marked with that version.
Sorry for the half-finished k8s work, I wanted to submit this before the
PR got too big

feat(core): Version provider accounts/operations

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonS3DataProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonS3StaticDataProviderConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonS3DataProviderSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/DataProvider.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/DataController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/DataControllerSpec.groovy

In the short-term. this will allow a custom `deck` component to display
data that has been placed in an s3 bucket (in our case, by another team).
The proxy supports both static and adhoc configurations:
- `static`: A single bucket/object will be proxied (and temporarily cached)
-  `adhoc`: Any bucket/object will be proxied provided it matches a whitelist.
The whitelist allows restriction on both bucket names and object keys.
Only buckets that Spinnaker has read access to are eligible for proxying.
The requesting user _must_ have access to the account containing the bucket/object
being proxied.

feat(amazon): Support a generic proxy for static content stored in S3

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/AwsEurekaSupport.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy

When enabling & scaling up a disabled ASG - if instances are no longer running when trying to mark them up in discovery, log and ignore instead of failing the operation.

fix(discovery): skip terminated instances when enabling a disabled asg

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineLoadBalancerCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppenginePlatformApplicationCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineServerGroupCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/MutableCacheData.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesConfigMapCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesDeploymentCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesSecretCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServiceAccountCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesApplicationProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesInstanceProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesJobProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesLoadBalancerProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesProviderUtils.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesSecurityGroupProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/MutableCacheData.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesInstanceCachingAgentSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

No real changes here, just didn't want to pollute the next PR with this.

refactor(provider/kubernetes): Move v1 cache code into v1 package

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesCachingAgentDispatcher.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesCluster.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/caching/Keys.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesConfigMapCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesDeploymentCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesInstanceCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesSecretCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServiceAccountCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesV1CachingAgentDispatcher.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesApplicationProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesClusterProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesInstanceProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesLoadBalancerProvider.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesProviderUtils.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesSecurityGroupProvider.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesInstanceCachingAgentSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy

Some of the loops being broken from .each to for() is due to groovy weirdness (language bugs)

refactor(provider/kubernetes): Pull v1 cache code into separate class

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

This property is no longer needed and was causing Spinnaker to deploy
serverGroups with spotPrices even though the spot price had been removed
(because a previous deployment had the spot price set)
Related to https://github.com/spinnaker/deck/pull/4043 and https://github.com/spinnaker/orca/pull/1572

fix(provider/aws): Remove copySourceSpotPrice property

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy

(perf): Explicitly sets maximum page size call to reduce requests to AWS API
The default for these APIs calls are 50, by making them 100 it should reduce the number of times clouddriver has to call the AWS API

(perf): Explicitly sets maximum page size call to reduce requests to AWS API

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesInstanceCachingAgentSpec.groovy

Looks like this also broke a number of other providers... The caching agents were moved out of the package where a package-private reference to kubernetesCloudProvider existed.

feat(provider/kubernetes): Fix on demand caching

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesServiceDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

1st example of a manifest deploy that triggers a patch op

feat(provider/kuberenetes): V2 deployments

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesApiVersion.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KeysSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgentSpec.groovy

The `ownerReferences` are a list of version/kind/name resources that created a particular resource. An example would be a replica set reference within a pod. This simplifies manually constructing relationships in the cache.

feat(provider/kubernetes): Infer relationships from ownerReference

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteSecurityGroupDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/DeleteSecurityGroupAtomicOperation.groovy

The `removeDependencies` flag is a little too powerful, especially when trying to run automated cleanup.
FYI @ajordens

feat(provider/aws): Remove ability to automatically remove dependencies when deleting a security group

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/GoogleApiTestUtils.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraitsSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DisableGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/EnableGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/TerminateGoogleInstancesAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy

@duftler 
Turns out that getLastStatusCode on a response is only set for successful responses, not on errors. So this was always populating statusCode with -1 on errors.

fix(google): Add statusCode tag to google API metrics

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java

In the de-groovification these two were lost. Will also merge into 1.3 once closed.

fix(provider/kubernetes): Add missing credential props

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

Since in many cases these identifiers will be our only way to lookup objects, we need to disambiguate across api versions.

refactor(provider/kubernetes): v2 include api version in resource id

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy

adds the `catalogFile` option to the Docker Registry provider. This is
an attempt to make it easier to use registries that don't support
`v2/_catalog` (which happens to be a lot). This file can be managed by
an external process. Each caching cycle, Clouddriver reads this file to
determine the list of repositories it should cache tags for.
the format of the `configFile` is:
```
{
"repositories":[
"library/nginx",
"library/busybox"
]
}
```
@lwander PTAL. This is the first iteration/POC for spinnaker/spinnaker#1909. We can implement more remote options (S3/GCS) when there's more precedence for it in Clouddriver.

feat(provider/docker): add catalogFile option

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy

Bug introduced in `f70d6ea`. I updated the constructor to include
`catalogFile` but didn't update the constructor for those using
`password` and `passwordFile` configurations. This fixes that potential
issue.
@lwander PTAL.

fix(provider/docker): fix client constructor

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpinnakerRelationships.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy

Caching load balancer and security group relationships like this allows us to support multiple kinds of each spinnaker resource (service vs ingress for example).

feat(provider/kubernetes): v2 Cache lb & scg relationships

---

build.gradle
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ManifestToArtifact.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ManifestToUnversionedArtifact.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ManifestToVersionedArtifact.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesServiceDeployer.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotatorSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

What's happening here is that every k8s resource is either "versioned" or "unversioned" which determines  how Spinnaker should create it. If it's versioned (e.g. replica set, configmap, secret, etc...) Spinnaker will get a new versioned name (`my-app-vasdf84` - will be suffixed with `vNNN` in the future) and deploy that. If it's unversioned (e.g. deployment, statefulset, service) it will be created as-is w/o modification to the name, forcing Spinnaker to patch the resource.

feat(provider/kubernetes): v2 version deployed manifests as resources

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesProviderConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AccountCredentials.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

Having the account property named 'version' was confusing the concept of
the version the provider was at, with the version the cloud environment
was at.
Should be a quicky

refactor(core): s/version/providerVersion

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2Cluster.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2Instance.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2LoadBalancer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/view/model/ManifestBasedModel.java

Continuation of https://github.com/spinnaker/clouddriver/pull/1915

feat(provider/kubernetes): Attach k8s annotation monikers to v2 resources

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy

When not explicitly specified, instance monitoring would default to true due to groovy truth casting a non
null object to true instead of traversing into its enabled attribute

fix(aws): CopyLastAsgAtomicOperation instance monitoring.

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy

The elvis operator before was not evaluating truthiness correctly for a value
of 0. A User could and may want to deploy an update ReplicaSet of 0 and Scale
it later. Or perhaps it's bundled in a Spinnaker Pipeline with multiple Server
Groups and one of the Server Groups is scaled to 0. If the User is implementing
'useSourceCapacity' we would want that 0 value respected and not overwritten
with a value of 1.
The proposal is that the desired capacity trumps targetSize.  It's
reasonable to assume that someone who wants a targetSize of 0 would also
have a desired capacity of 0.  However, we shouldn't use the targetSize
if the desired capacity is greater than its value.

fix(provider/kubernetes): Advanced targetSize use case.

---

build.gradle
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ClusterProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesCoordinates.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifest.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourcePropertyRegistry.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetDeployer.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesServiceDeployer.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

Will roll up into a coming PR that uses prior "versions" of a resource, e.g. replicaSet to determine what to deploy. This enables version numbers like vNNN on versioned resources (replicaSet, configMap, ...)

refactor(provider/kubernetes): refactor artifact/deployment boundary

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineLoadBalancerCachingAgent.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineServerGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/provider/agent/ClusterCachingAgent.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandAgent.java
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosLoadBalancerCachingAgent.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesLoadBalancerCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesSecurityGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNetworkPolicyCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java

See https://github.com/spinnaker/clouddriver/compare/master...lwander:moniker-on-demand?expand=1#diff-793a249c0692198d2557378d889e7285 for the "correct" long-term implementation, the "deriveMoniker" is more of a patch to get this working without proper support in each cloud provider.
@andrewbackes

feat(moniker): Adds moniker to pendingOnDemandResults

---

clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/gcsClient/AppengineGcsRepositoryClient.groovy
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/storage/GcsStorageService.java
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/storage/StorageConfiguration.java
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/storage/StorageUtils.java
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/storage/config/StorageConfigurationProperties.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy

@danielpeach please review
@duftler FYI
This works with the existing citest for gcs buckets (without passing a storage account).
I have another change for the test which does pass a storage account in with the deployment request.
I havent yet tested the tar file thing, but did test the extraction of tar files from buckets so believe it will work.
My only technical concern is that I do not preserve any file properties other than timestamps from GCS (e.g. mode bits, owner/group, etc). I dont think this matters for appengine, and that's the only scope at this time.
Note also that I load credentials on demand rather than on startup like other places seem to. It seems simpler this way. I dont think performance is a concenr, but for better or worse it means that a misconfiguration will be …

feat(appengine): Deploy from Google Cloud Storage [accounts].

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ArtifactProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ArtifactProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployerSpec.groovy

Now any resource that's flagged as versioned in k8s will be given a `-vN` suffix

feat(provider/kubernetes): Properly version all versioned resources

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiAdapter.groovy

@lwander 
Regarding issue spinnaker/spinnaker#1989
It was because of using the older version of Kubernates (1.4) that’s why that error coming , as we have written new cashing agent which is a part of framework that’s why its started automatically and try to fetch the StatefulSets list from Kubernates. Which older version does not supports.
We have surrounded the call with exception framework that’s why its printing the exception
So i have handled the exception and Printed the message " Cannot fetch Statefulsets [Required Kubernates VERSION>=1.6"
Please review it.
CC @chlung 
* Follow the …

fix(provider/kubernetes): handle exception to reduce noise for user(Issue no: 1989)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/search/ServerGroupKeyProcessor.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/KeyParser.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/KeyProcessor.java

* removes ASGs that show up in the search results from the redis cache
but don't actually exist.

feat(search): cull missing ASGs before returning

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiAdapter.groovy

Fixes breakage I introduced by bumping the client library (and of course groovy can't catch)

fix(provider/kubernetes): v1 client call to list pods

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesManifestDeployer.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy

Improper handling of artifacts (wrong versions being assigned) prevented the same versioned manfiest from being deployed more than once in the UI

fix(provider/kubernetes): Don't store-unowned artifacts

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgentSpec.groovy

fix(provider/aws): fix issue if VPCZoneIdentifier contains deleted subnet

---

build.gradle
cats/cats-dynomite/cats-dynomite.gradle
cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/DynomiteClientDelegate.java
cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/JedisClientDelegate.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/RedisClientDelegate.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteConfigurationProperties.groovy

The latest round of dyno changes dramatically improved perf across the board, but it's still slow enough to rustle up some race conditions.
The dyno client currently doesn't support hashtags, but I wanted to put this out here so I don't forget about the work. This will further cut down the RTT dynomite latency. All keys for a provider's caching agent will get pinned to a single node, allowing most ops to get pipelined in `DynomiteCache`.

feat(dynomite): hashtags & dynomite pipelines

---

cats/cats-core/cats-core.gradle
cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/CachingAgent.java
cats/cats-core/src/test/groovy/com/netflix/spinnaker/cats/agent/CacheExecutionSpec.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy

This PR attempts to clean up situations where the `:members` set for a
given cached type contains keys that no longer exist.
In particular, a `CachingAgent` can optionally return a pattern glob for
each authoritative type.
Any `:members` key matching the pattern glob BUT not included in the
most recent caching cycle will be evicted.

fix(core): Support the eviction of stale cache key identifiers

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy

Seeing some mixed results when application/network and classic load
balancers are being used.

fix(aws): Do not do stale key evictions of amazon load balancers

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNetworkPolicyCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java

Since manifest deployments have their own semantics, they are getting their own caching behavior too

feat(provider/kubernetes): v2 on-demand manifest caching

---

build.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AddSpinnakerUserToUserAgentRequestHandler.java

Verified aws cloudtrail logs contained i.e. "spinnaker-user/afeldman@netflix.com spinnaker-executionId/f17d557a-818f-459b-9ef0-97f53035810e"

feat(provider/aws): add executionId to user-agent for cloudtrail

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/CachingAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy

Key structures vary between classic and application/networking load
balancers.

fix(aws): Enable stale key evictions for amazon load balancers

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/compression/CompressionStrategy.java
cats/cats-core/src/main/java/com/netflix/spinnaker/cats/compression/GZipCompression.java
cats/cats-core/src/main/java/com/netflix/spinnaker/cats/compression/NoopCompression.java
cats/cats-core/src/test/groovy/com/netflix/spinnaker/cats/compression/GZipCompressionStrategySpec.groovy
cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteNamedCacheFactory.java
cats/cats-dynomite/src/test/groovy/com/netflix/spinnaker/cat/dynomite/cache/DynomiteCacheSpec.groovy
cats/cats-redis/cats-redis.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/GZipCompressionStrategyProperties.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/DynomiteConfig.groovy

There's currently a bug in 1.6.0-rc.2 of dyno that doesn't handle dynomite threshold caches correctly in hashset values. This gets some basic level of compression in place, and could also be put in place for Redis later on as well.
The gzip strategy will auto-disable compression if dynomite compression is enabled, but will continue checking values for decompression. Ideally, we won't have to run this forever.

feat(cats): Adding cache gzip compression

---

cats/cats-core/src/main/java/com/netflix/spinnaker/cats/compression/GZipCompression.java

The migration to compression from uncompressed values failed in some cases due to charset issues.

fix(cats): Get bytes in consistent chatset during decompress

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/KubernetesVolumeSourceValidator.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/StandardKubernetesAttributeValidator.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy

We have some secrets in our cluster that have dots in the name and have deployed manually using them as volume sources. The next logical step was to set up a spinnaker pipeline but doing so resulted in:
deployKubernetesAtomicOperationDescription.volumeSources[1].secret.secretName.invalid (Must match ^[a-z0-9]+([-a-z0-9]*[a-z0-9])?$)
Upon further investigation, the kubernetes api allows dots in secret names:
https://github.com/kubernetes/kubernetes/blob/e5ac41331119bb8c67004b8efaa0c3d942b31d3a/pkg/api/validation/validation.go#L160-L162
https://github.com/kubernetes/kubernetes/blob/8d7d7a5e0d4d7e75f5a860574346944b8cc0fc43/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L126-L142
https://github.com/kubernetes/kubernetes/blob/e5ac41331119bb8c67004b8efaa0c3d942b31d3a/pkg/api/v …

fix(provider/kubernetes): allows dots in secretNames

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy

This is an optimization for fetching target server groups by `CURRENT`,
`PREVIOUS`, `OLDEST` and `FAIL`.
For these strategies, the unexpanded server group is sufficient to
narrow down to a match.
Once a match is found, _only_ that server group will be expanded.
This only works for cluster providers that support loading both
expanded and unexpanded server groups (ie. aws). The behavior for other
providers should be unchanged.

perf(cluster): Avoid prematurely fetching full server groups

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/securitygroup/KubernetesSecurityGroupDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/securitygroup/UpsertKubernetesSecurityGroupAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesSecurityGroup.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/securitygroup/UpsertKubernetesSecurityGroupAtomicOperationSpec.groovy

Enable the k8s Clouddriver to set annotations, labels and TLS config on Security Groups (aka ingress resources).
This, along with the Deck pull request (spinnaker/deck#4235), fixes spinnaker/spinnaker#2000

feat(provider/kubernetes): Enable annotations, labels and secrets for security groups (aka ingress resources) (spinnaker/spinnaker#2000)

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

Expectation is that a `subnetType` will still be provided and that
`subnetIds` will be a subnet of those valid for `subnetType`.
When explicit subnet ids are provided (or inherited), the newly created
server group will be tagged with:
`SPINNAKER_SUBNET_ID_OVERRIDE`: `"comma-separated list of subnet ids"`

feat(provider/aws): Support specifying explicit subnet ids for deploy

---

clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/model/EurekaInstance.groovy

The instanceId was intended to be the value in dataCenterInfo.metadata but due to some
Jackson behaviour the top level instanceId from the discovery registration was written
over the dataCenterInfo.metadata during deserialization.
This changes to explicitly handle the top level instanceId value in the JsonCreator factory
method to prevent the unhandled property behaviour from kicking in.

fix(eureka): fix instanceId on eureka caching

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/servergroup/KubernetesResizeServerGroupValidator.java

Deployed the latest clouddriver to test out and some of our existing pipelines failed on resize operations. Did some poking around and if I'm reading things right, In what appears to be the absence of another v1 resize validator,
KubernetesResizeServerGroupValidator was being picked up which wasn't correctly
declaring its support for v2 only.
This resulted in stack traces like this in the log:
java.lang.ClassCastException: com.netflix.spinnaker.clouddriver.kubernetes.v1.deploy.description.servergroup.ResizeKubernetesAtomicOperationDescription cannot be cast to com.netflix.spinnaker.clouddriver.kubernetes.v2.description.servergroup.KubernetesResizeServerGroupDescription
at com.netflix.spinnaker.clouddriver.kubernetes.v2.validator.servergroup.KubernetesResizeServerGroupValidator.validate(Kub …

fix(provider/kubernetes): fixes ClassCastException on resize operations

---

build.gradle

chore(dependencies): Bump spinnaker-dependencies version and pin google

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAmiTagsAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAmiTagsAtomicOperationSpec.groovy

The AWS `createTags` API requires at least one tag to be provided.
Rather than error out, let's just skip the update entirely and return
success.

fix(provider/aws): No-op ami tag update when no tags provided

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesJobProvider.groovy

I have operation spinnaker with kubernetes provider,but there throw expection:
```
Exception ( Wait On Job Completion )
Cannot cast object 'com.netflix.spinnaker.clouddriver.kubernetes.v1.security.KubernetesV1Credentials@45ff365d' 
with class 'com.netflix.spinnaker.clouddriver.kubernetes.v1.security.KubernetesV1Credentials' 
to class 'com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials'
```
then , I found the question on the code at `com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.view.KubernetesJobProvider` . In this `collectJob()` method ,the `if (!credentials instanceof KubernetesNamedAccountCredentials)` always is false.  and `accountCredentialsProvider.getCredentials(account).credentials` is can not cast to …

[FIX]kubernetes collectJob status  ClassCastException

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesApiClientConfig.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java

About this PR,
The V1 new client does not support service account configuration.  Use fabric8 client as a model for service account implementation. Refer issue - https://github.com/spinnaker/spinnaker/issues/2069
Thanks.
* Add a comment to …

fix(provider/kubernetes): allow to configure with service account.

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DestroyGoogleServerGroupAtomicOperationUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DisableGoogleServerGroupAtomicOperationUnitSpec.groovy

The GCE calls on cache misses were passing incorrectly typed arguments to the 'delete backends' closure, causing havoc.

fix(provider/gce): Fix GCE destroy backend calls on LB cache misses.

---

clouddriver-web/config/clouddriver.yml

I noticed that in the defaults there is both `instanceType` and `instance-type`. PR is for making them consistent. Unless there's a specific reason for the difference.

fix(gce/defaults): instanceType vs. instance-type

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ClusterProvider.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy

If `ClusterProvider.supportsMinimalClusters()` is true, we can now sort and
filter on the set of unexpanded server groups.
Only the actual LARGEST server group will be expanded.
This offers significant savings for target/LARGEST lookups on
clusters with > 1 server group, particularly those containing _many_
instances.
A target/LARGEST lookup commonly occurs when doing a clone operation
with `useSourceCapacity` set to `true`.

perf(cluster): Optimize target/LARGEST lookups

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesServiceCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesDeployManifestConverter.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourcePropertyRegistry.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesServiceHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeleteManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/servergroup/KubernetesResizeServerGroupOperation.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy

This allows us to not hard-code a list of caching agent types, and have them be discovered based on the "Handler" for the resource that owns them.

feat(provider/kubernetes): automatically configure caching agents

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesPodHandler.java

Since the pod caching agent already exists this isn't a complete example, but it's a partial one of how resources are registered (can be used for custom resources too).

feat(provider/kubernetes): v2 register pod handler

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackLoadBalancerProvider.groovy

Fixes the `Exception: upsertLoadBalancer failed: Unable to process request` error when creating a LoadBalancer even though the LB is created in Openstack.

fix(provider/openstack): Fix type error in LoadBalancerSummary

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java

Realized this bug when instances were being loaded from the cache twice since the PodHandler had just been registered.

fix(provider/kubernetes): Dedup kind map

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/Keys.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/AbstractCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/EcsProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/config/EcsProviderConfig.java

feat(provider/ecs): ECS Cache base classes
Added base classes that will be used for the `CachingAgent`s classes that are to come.

feat(provider/ecs): ECS Cache base classes

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixAmazonCredentials.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixAssumeRoleAmazonCredentials.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperationSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProviderSpec.groovy
clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtilsSpec.groovy

We only want to enable protection on newly created, external ELBs & ALBs. By default, shield protection is disabled and can be enabled per-account, additionally exposed an opt-out field on the create ELB description in case we want to expose via the UI explicitly not attaching Shield protection.

feat(provider/aws): Enable optional AWS Shield protection on ELB & ALBs

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

Set `aws.defaults.addAppStackDetailTags: true` to enable.
When enabled, all created server groups will be tagged with:
- `spinnaker:application`
- `spinnaker:stack`
- `spinnaker:details`
The tag will only be created if the value is non-null.
By default, these tags will be propagated to launched instances.

feat(provider/amazon): Optionally tag server groups w/ app/stack/details

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesV1SecurityGroup.groovy

add yaml field to KubernetesV1SecurityGroup so that the
"Show YAML" modal works in deck.

fix(provider/kubernetes): security group yaml

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourcePropertyRegistry.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeployManifestDescription.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java

Needed for operations that are strictly interpreted as an "edit", or explicit calls to avoid versioning things like configMaps

feat(provider/kubernetes): Allow op to override versioning

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2SearchProvider.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2SecurityGroup.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesIngressHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesPodHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesServiceHandler.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesStatefulSetHandler.java

feat(provider/kubernetes): v2 search result hydrators

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/job/RunKubernetesJobDescription.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/job/RunKubernetesJobAtomicOperation.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/job/RunKubernetesJobAtomicOperationValidator.groovy

support multiple containers in the run job description. we have to
support both `container` and `containers` until we can deprecate the
`container` field since the current defs are all using `container`.
@lwander PTAL. I'm not sure the validator changes are correct.
spinnaker/spinnaker#1961

feat(provider/kubernetes): runJob multi-container

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchServerGroupTagger.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperation.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java

If `entityRef.application` is not explicitly provided, it will be
parsed from `entityRef.entityId` using frigga conventions.
Searching by application can be accomplished by
`/tags?application=my_application`

feat(entitytags): Support indexing / searching by application

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/BasicGoogleDeployAtomicOperationConverter.groovy

Pipelines are being persisted with 'port' values of NamedPorts as
Doubles. This is an issue. This change tolerates that behavior in deploys
since users will have pipelines with Double ports in the wild.
This is an issue in 1.5.0, so we should cherry-pick and cut a patch release.
https://github.com/spinnaker/spinnaker/issues/2096

fix(provider/gce): Tolerate named port values as Doubles.

---

clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosSpectatorHandler.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/ops/servergroup/DeployDcosServerGroupAtomicOperation.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/util/mapper/DeployDcosServerGroupDescriptionToAppMapper.groovy
clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/security/DcosCredentialsInitializer.groovy

Uses the correct DC/OS API call for creating a new marathon application, due to "Bad Request" issues with certain marathon application definitions when using updateApp.
Also corrects a small issue with the exceptions being thrown out of the spectator proxy for the DC/OS client, such that now the correct exception flows are hit.

fix(provider/dcos): Use createApp instead of updateApp for deploy

---

clouddriver-elasticsearch/elasticsearch_index_template.json
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java

`elasticsearch_index_template.json` is the index template that
should be applied in elastic search.

fix(elasticsearch): Force refresh when fetching entity tags from Front50

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/BasicGoogleDeployAtomicOperationConverter.groovy

Pipelines are being persisted with 'port' values of NamedPorts as
Doubles. This is an issue. This change tolerates that behavior in deploys
since users will have pipelines with Double ports in the wild.

fix(provider/gce): Tolerate named port values as Doubles. (#2137)

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/KubernetesServerGroupDescription.groovy

Patch for 1.5.x - will likely need https://github.com/spinnaker/orca/pull/1805/ merged & patched into 1.5.x as well

fix(provider/kubernetes): read namespace as region (#2123)

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy

Currently, if the backend service getHealth() calls fail, we fail to cache the whole load balancer. This was fine using backend service get()s, since the platform seemed to always return fully-formed and ready backend services. Since we are using one backend service list() at the beginning of the cache cycle, it seems like resources _can be partially-formed_.
Rather than fail the whole LB if a getHealth() fails, we should be tolerant of that failure, mark the health state as unknown, log it, and retry next cycle. The health states are the leaves of the LB configuration, and an unknown health state is an acceptable configuration to Spinnaker (blue health check).

fix(provider/gce): Tolerate failed backend service getHealth() calls.

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

Remove any `spinnaker:*` tags that are no longer valid (ie. cloning
across stacks and `spinnaker:stack` no longer points at the correct
stack).
This is necessary as `deck` will _now_ supply existing tags when cloning.

fix(provider/aws): Remove invalid `spinnaker:` tags

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesJobStatus.groovy
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesJobProvider.groovy

add support for capturing logs as part of `collectJob`. logs are added
to the job status. i'm not sure how well this scales as log size grows
so this may not be the best implementation, but it may work for the
short term. since execution details are persisted to volitile storage
storing them with the jobs status is best since the reference to the job
pod is also stored there.
spinnaker/spinnaker#1961
spinnaker/spinnaker#1832
@lwander PTAL. I'll submit a Deck PR once we settle on an implementation.

feat(provider/kubernetes): runJob logs

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SecurityGroupController.groovy

If the collection is empty, a `.first()` will cause an exception.

fix(web): Do not throw exception when sg not found

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentSchedulerSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/JedisCacheConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfigurationProperties.groovy

This is an assist to local development when you do not want _all_
agents to run by default.
```
redis:
agent:
enabledPattern: .*reservation.*
```
By default `enabledPattern` is `.*` and all agents will be scheduled.

feat(cats): Support for selectively enabling agents

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesApiClientConfig.groovy

This fixes the use of service accounts for getting credentials when Spinnaker is deployed inside a Kubernetes cluster.
Fix found via https://github.com/kubernetes-client/java/issues/74.
Issue found when testing https://github.com/kubernetes/charts/pull/2616

fix(provider/kubernetes): Use setApiKey when using token from service account

---

clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/model/OpenstackLoadBalancer.groovy

Currently displays `null` instead.

bug(provider/openstack) - Display VIP for LBs that do not have FIP

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ResizeAsgDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/preprocessors/ResizeAsgDescriptionPreProcessor.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperationUnitSpec.groovy

Support a constraint wherein the server groups' current capacity must
match expected prior to a resize.
There are scenarios wherein a user initiates a resize via the UI at the
same time that an autoscaling event is happening behind the scenes. In
such a scenario, the resize via UI != autoscaling and some churn will
occur.
`deck` will be changed to supply the capacity constraint.

feat(provider/aws): Support expected capacity constraint when resizing

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesControllerRevisionCachingAgent.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesControllerRevisionHandler.java

This is how k8s surfaces what you can rollback to.

feat(provider/kubernetes): cache controller revisions

---

clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java

if using the `namespaces` key for kubernetes accounts, reconfigure
registries using those namespaces.
@lwander PTAL

fix(provider/kubernetes): fix registry init
