- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
the bump in client library broke the API for configMap and secret envvar
sources. adds an extra property for optional. defaults to true to
preserve backwards compatibility. shoutout major version bumps.
@lwander PTAL.
> fix(provider/kubernetes): fix envvar source

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BasicGoogleDeployDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleDistributionPolicy.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
fyi @duftler as well.
Added a metadata entry to handle the case where users just want to use the default zones in a region since there is no flag indicating that in the platform. Removed the (possibly) brittle logic calculating default zones since the platform reports the zones it will use regardless of whether or not a user chose specific zones.
> feat(provider/gce): Support for RMIG zone selection.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java
for real this time. the previous fix caused registry namespaces to get
set to an empty list the second time the initialization occurred. moving
it down into this method allows us to still use the full list of
namespaces (`allNamespaces`) and setup the affected ones to be
initialized. This would occur if a new namespace was added, for
instance.
@lwander PTAL.
> fix(provider/kubernetes): registry init fix

- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosSpectatorHandler.groovy
Correctly catches the exceptions from the metrics proxy method invocation, to allow the correct exception to be propagated.
> fix(provider/dcos) Catch the correct exception for the proxy.

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/search/ServerGroupKeyProcessor.groovy
Certain cache keys were failing due to `Keys.parse()` returning null.
Turns out there is no need to parse the cache key and then reconstruct it so stop doing that.
> fix(core/search): Fix search query which matches non-conforming cache keys

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
adds support for envFrom for the v1 provider. envFrom can be either a
secret or config map reference and will be injected into the pod as
environment variables.
@lwander PTAL
spinnaker/spinnaker#2120
> feat(provider/kubernetes): support envFrom

- build.gradle
Picks up the new compute library versions.
> chore(dependencies): Bump spinnaker-dependencies version.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
adds support for initContainer property of the Pod spec
@lwander can i get some feedback on this? I went with a separate `KubernetesInitContainerDescription` because they don't support readiness/liveness probes or lifecycle hooks. i'm also not totally stoked on the `toInitContainer` method creating a new container and passing it on. I'd rather cast to a container if possible. Any thoughts?
> feat(provider/kubernetes): init containers

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/health/AmazonHealthIndicator.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/health/AmazonHealthIndicatorSpec.groovy
Avoid being marked unhealthy should there be a temporary blip
in connectivity to one or more accounts.
This frequently occurs as a result of an AWS rate limit being hit.
The `health.amazon.errors` metric can be used to alert on possible
errors that would have previously caused an instance to go unhealthy.
> fix(provider/aws): Avoid being marked unhealthy after initialization

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidator.groovy
Allow App Engine deployments with a built container image URL and app.yaml.
> feat(provider/appengine): enable flex deployments

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
Currently we set `-l=` when `labelSelectors` is null or is not empty, causing all commands that pass a null value for `labelSelectors` to fail.
The `-l=somelabel` flag should be set if `labelSelectors` is not null and is not empty.
* Add a …
> fix(provider/kubernetes): v2 Fix kubectl label selector flag

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
Correctly handling spotPrice in a rollingpush strategy. @duftler is there any reason why you left out validation logic in this class? Want to make sure I'm not breaking anything around spotPrice!
> fix(provider/aws): handle spotPrice ==  in rollingpush

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
Attempting to track down an issue wherein the reservation report caching
agents _stop_ and are never rescheduled after some period of time.
Will revisit and remove the thread pool configuration if this change
happens to improve the stop/reschedule situation.
> debug(provider/aws): Avoid thread pool when building reservation report

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/EddaTimeoutConfig.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java
Establishes an upper bounds on the amount of time to spend waiting on
an available connection from the `edda` connection pool.
Previously, a caching agent could wait _indefinitely_ for an available
connection.
The default is now 10000 (milliseconds) and can be overridden with
`aws.edda.connectionRequestTimeout`.
> fix(provider/aws): Specify `connectionRequestTimeout` for edda

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
Per http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions, Spinnaker should not be copying tags over that have the `aws:` prefix, as they are generated by Amazon and an exception will be thrown when trying to create them. This can be a problem when a user tries to clone a server group that was created by Cloud Formation.
There are probably other scenarios where these tags could be present; this one was just pointed out by a user in Slack.
This is likely fallout from recent fixes to tag copying in the UI.
@ajordens or @cfieber PTAL
> fix(provider/amazon): do not try to create reserved tags

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/BlockDeviceConfig.groovy
This should provide coverage for all currently available instance types.
Will look for better ways to manage this moving forward.
> fix(provider/aws): block device config for missing instance types

- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AccountCredentials.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/DefaultAllowedAccountsValidator.groovy
- clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/DefaultAllowedAccountsValidatorSpec.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerSpec.groovy
update AllowedAccountsValidator to use permissions config in addition to requiredGroupMemberships
goes along with spinnaker/gate#494
> feat(authz): requiredGroupMemberships to permissions migration

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesDeploymentHandlerSpec.groovy
Do not attempt artifact replacement if no target was found. Reading a non-existing path can return an empty `ArrayNode` object, in which case we should not attempt any replacement.
Add checks for bound artifacts in artifact replacement tests. …
> fix(provider/kubernetes): v2 Replace artifact only if target found

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerToken.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
Per https://docs.docker.com/registry/spec/auth/token/#requesting-a-token, the token response fields will either contain `token` or `access_token`.
In ACR, for example, only access_token is sent back as a response, meaning that the response from Spinnaker will fail to authenticate.
> fix(provider/docker): update bearer_token to access_token

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerToken.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
Per https://docs.docker.com/registry/spec/auth/token/#requesting-a-token, the token response fields will either contain `token` or `access_token`.
In ACR, for example, only access_token is sent back as a response, meaning that the response from Spinnaker will fail to authenticate.
> fix(provider/docker): update bearer_token to access_token (#2274)

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Set the default namespace according to the `kubectl` rules defined in
https://github.com/kubernetes/kubernetes/blob/bd4d511a40e142ee65edff3b286e57de502aa790/pkg/kubectl/cmd/util/factory_client_access.go#L127
In short, the default namespace is set in this way:
- If `/var/run/secrets/kubernetes.io/serviceaccount/namespace` exists,
assume we are running in a Kubernetes container, and set the default
namespace to the contents of this file.
- Set the default namespace to the namespace of current `kubectl`
config context, if it exists. `kubectl config view` is used to get
this namespace, which takes care of the complicated merges and
overrides.
- Otherwise, set the default namespace to "default".
This fixes the issue of manifests without a namespace specification
being deployed in the namespace …
> fix(provider/kubernetes): v2 Set default namespace dynamically

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/Keys.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsCloudWatchAlarmCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/model/EcsMetricAlarm.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgent.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsCloudWatchAlarmCacheClientSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgentSpec.groovy
Adds an EcsCloudMetricAlarmCachingAgent which is responsible for caching cloud metric alarm information - used for scaling -, along with EcsCloudWatchAlarmCacheClient.
The client allows providers/services to interface more easily with the cache.
> feat(provider/ecs): ECS Metric Alarm caching classes and tests

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/TaskCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/TaskHealthCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/model/TaskHealth.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/TaskHealthCacheClientSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCacheSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy
Adds an TaskHealthCachingAgent which is responsible for caching ECS Task health information, along with TaskHealthCacheClient.
The client allows providers/services to interface more easily with the cache.
> feat(provider/ecs): ECS Task Health caching classes and tests.

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsLoadbalancerCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/model/EcsLoadBalancerCache.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsLoadbalancerCacheClientSpec.groovy
Adds an EcsLoadbalancerCacheClient which  allows providers/services to interface more easily with the already existing AWS loadbalancer cache.
> feat(provider/ecs): ECS Loadbalancer cache client and tests.

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsTargetGroupCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsTargetGroup.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsTargetGroupCacheClientSpec.groovy
Adds an EcsTargetGroupCacheClient which  allows providers/services to interface more easily with the already existing AWS target group cache.
> feat(provider/ecs): ECS Target Group cache client and tests.

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java
https://github.com/spinnaker/spinnaker/issues/2235
> feat(artifacts): add artifact download endpoint

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/util/GroupHealthRequest.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/util/LoadBalancerHealthResolution.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/util/TargetPoolHealthRequest.java
Refactors LB caching agents so that only one get health call is made per backendService -> serverGroup and targetPool -> instance pair per caching cycle.
> perf(provider/gce): De-dupe getHealth() calls in LB caching agents.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesDaemonSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesDeploymentCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPodCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesStatefulSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ApplicationProvider.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
This ensures that only workload based resources are associated with a
spinnaker cluster, reducing 'application' screen clutter
> fix(provider/kubernetes): v2 cache clusters for workloads only

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
Stack, Detail & Sequence are often parsed incorrectly because of the cruft introduced by randomly generated names.
> fix(provider/kubernetes): only include app & cluster frigga details

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesReplicaSetHandler.java
This adds support for replacing configMaps from artifacts in replicaset manifest deployments.
> feat(provider/kubernetes) - V2 Adds configMap replacer support for replicasets

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesDaemonSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesDeploymentCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesStatefulSetCachingAgent.java
Let workload deployments have full control over (generated) applications coming and going.
This is in line with https://github.com/spinnaker/clouddriver/pull/2303 and fixes https://github.com/spinnaker/spinnaker/issues/2259
In particular, applications will not be shown in the deck "Applications" view if the daemonset/deployment/statefulset of the application has the `caching.spinnaker.io/ignore="true"` annotation, and will be removed from the list if the annotation added to an existing workload.
* Follow the commit message conventions [found …
> fix(provider/kubernetes): v2 Make workloads authoritative for apps

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppengineAtomicOperationConverter.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/exception/AppengineDescriptionConversionException.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidator.groovy
- clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppengineAtomicOperationConverterSpec.groovy
Moves responsibility for artifact hydration during appengine deploys from orca into clouddriver.
This commit doesn't include any smarts around artifact typing, it's still just a `switch` statement on the artifact.type.  That is planned for a follow-up commit.
> refactor(provider/appengine): artifact logic from orca

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiAdaptor.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
It turns out it was possible that we would
1. apply an annotation
2. toggle replica set labels
3. fail to wait for the label change to be applied
Part 3. could happen because the generation of the replica set returned
from the "toggle label" operation was that of the "apply annotation"
operation. The "wait for consistency" step we usually do here was then
skipped causing us to edit pod labels before the replica set owning them
was finised updating.
This doesn't happen often, but enough to be a real problem.
> fix(provider/kubernetes): v1 eventual consistency bug in disable

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/controllers/EcsCloudMetricController.java
Based on the discussion in the gate pull request - https://github.com/spinnaker/gate/pull/500 - updated the corresponding endpoint for clouddriver.
> fix(provider/ecs): ECS Cloud Metric endpoint camel-cased

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/controllers/EcsClusterController.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/controllers/EcsClusterControllerSpec.groovy
Adds an `EcsClusterController` which is responsible for providing ECS clusters on a certain endpoint.
> feat(provider/ecs): ECS Cluster Controller

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/Keys.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsLoadbalancerCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ContainerInstanceCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsClusterCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ScalableTargetsCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskDefinitionCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCacheSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy
`getClusters(...)` method in `AbstractEcsCachingAgent` was returning back clusters for all regions and accounts - which caused issues for caching agents extend that calls and calling that method.
When registering with the scheduler, caching agents were imporperly named. This caused only one instance of each caching agent to be registered, even if there were several caching agents for different regions.
This PR fixes the above.
Issue was brought up by a member of the Spinnaker community - on slack, in the ecs channel - when he tried to use clouddriver, having an account with multiple regions. 
> fix(provider/ecs): ECS Caching Agents - Account/Region awareness

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsInitializer.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/NetflixAssumeRoleEcsCredentials.java
`EcsCredentialsInitializer` now initializes `NetflixAssumeRoleEcsCredentials`. This is needed for the up coming `CreateServerGroupAtomicOperation`, where the assumed role is used during service and autoscaling creation.
> refactor(provider/ecs): ECS Accounts - AssumeRoleEcsCredentials

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/helpers/EnableDisablePercentageCategorizer.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/helpers/EnableDisablePercentageCategorizerSpec.groovy
This aligns the calculation with what is also happening within `orca`.
> fix(rrb): Disable percentage calculation should use Math.ceil()

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/controllers/EcsImagesController.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/controllers/EcsImagesControllerSpec.groovy
Added `EcsImagesController` which is responsible for providing AWS/ECR docker images on the `/ecs/images/find` endpoint. Used during `Find Image from Tags` stage.
> feat(provider/ecs): ECS Images Controller

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/ContainerInstanceCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/model/ContainerInstance.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsTask.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/view/EcsInstanceProvider.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/view/EcsInstanceProviderSpec.groovy
Added `EcsInstanceProvider` which is responsible for providing an "instance" representation of an ECS Task - used for displaying the instances in server groups.
Updated `ContainerInstance` and `ContainerInstanceCacheClient` to have an `availabilityZone`.
> feat(provider/ecs): ECS Instance Provider

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/EcsCloudMetricService.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/EcsCloudMetricServiceSpec.groovy
Added `EcsCloudMetricService` which is responsible for registering and deregistering `MetricAlarms` and the associated `ScalableTargets`.
Used by the upcoming Atomic Operations.
> feat(provider/ecs): ECS Cloud Metric Service

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsServerCluster.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsServerGroup.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsTask.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/TaskDefinition.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProviderSpec.groovy
Added `EcsServerClusterProvider` which is responsible for providing the Spinnaker Cluster version of ECS Tasks and Services - used for displaying the clusters/server groups in the Cluster tab.
> feat(provider/ecs): ECS Server Cluster Provider

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsLoadBalancerDetail.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsLoadBalancerSummary.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsLoadBalancerSummaryByAccount.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsLoadBalancerSummaryByRegion.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProvider.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProviderSpec.groovy
Added `EcsLoadBalancerProvider` currently responsible only for providing a list of `LoadBalancers` - used in a by Deck in the deploy stage configuration wizard.
> feat(provider/ecs): ECS Load Balancer Provider

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/DestroyServiceAtomicOperationConverter.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/AbstractECSDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/DestroyServiceDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/ModifyServiceDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/AbstractEcsAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DestroyServiceAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DisableServiceAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/EnableServiceAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/StopServiceAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/UpsertScalingPolicyAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/CommonValidator.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/DestroyServiceAtomicOperationValidator.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/ServerGroupDescriptionValidator.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/DestroyServiceAtomicOperationConverterSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/ModifyServiceAtomicOperationConverterSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CommonAtomicOperation.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DestroyServiceAtomicOperationSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/AbstractValidatorSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/ServerGroupDescriptionValidatorSpec.groovy
Implemented `DestroyServiceAtomicOperation` responsible for performing `DESTROY_SERVER_GROUP` operation - when called during a stage or directly through UI dropdown on Deck.
Added base `deploy` classes in `description`/`ops`/`validators` packages.
> feat(provider/ecs): Destroy Service Atomic Operation

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppengineAtomicOperationConverter.groovy
Incorrectly assumes that repositoryUrl always refers to a GS repo when it could be a git one instead.
Likely source of the integration test failures.
> fix(provider/appengine): dont prepend "gs" to all repository URLs

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/TerminateInstancesAtomicOperationConverter.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/TerminateInstancesDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/TerminateInstancesAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/TerminateInstancesDescriptionValidator.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/TerminateInstanceAtomicOperationConverterSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/TerminateInstanceAtomicOperationSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/TerminateInstanceDescriptionValidatorSpec.groovy
Implemented `TerminateInstancesAtomicOperation` responsible for performing `TERMINATE_INSTANCES` operation, when called during a stage or through the drop down UI on Deck.
Terminates the given ECS Tasks of an ECS Service. The ECS Task is represented as a Spinnaker Instance.
> feat(provider/ecs): Terminate Instances Atomic Operation

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/AppengineJobExecutor.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy
Previously when an appengine deploy took longer than 10 minutes, an error was captured in deck that read `Cannot get property 'state' on null object`.  This PR modifies the message that gets surfaced to read `job timed out or was cancelled`.
Error Before:
Error After:
> fix(provider/appengine): surface timeouts to frontend during job execution

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderConfig.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2SearchProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/CustomKubernetesCachingAgentFactory.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourcePropertyRegistry.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CanDeploy.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/CustomKubernetesHandlerFactory.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deployer/KubernetesHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeleteManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPauseRolloutManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesResumeRolloutManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesScaleManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesUndoRolloutManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/servergroup/KubernetesResizeServerGroupOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
This allows you to register (for now, only rudimentary) support for
custom resources, or resources not handled by Spinnaker.
So far, I haven't made `ReplicationControllers` explicitly deployable
using Spinnaker. With this patch, and the following config in my
clouddriver.yml, they could be deployed:
```yaml
kubernetes:
accounts:
- name: my-k8s-v2-account
customResources:
- kubernetesKind: ReplicationController
spinnakerKind: ServerGroups
versioned: true
```
> feat(provider/kubernetes): v2 per-account, custom resources

- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy
- clouddriver-eureka/src/test/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupportSpec.groovy
`getInstanceToModify()` is currently passed a set of instances that have
been fetched directly from AWS.
In the event of autoscaling, it's highly likely that some number of
these instances have not yet been cached by `clouddriver`.
This PR ignores any instances that have not been cached and excludes
them in the `desiredPercentage` calculation.
Previously this failed with:
```
NullPointerException; Message: Cannot invoke method flatten() on null object
```
> fix(eureka): Handle missing instances when determining what to disable

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/RoleController.java
Added `RoleController` responsible for listening on `/roles/{cloudProvider}` endpoint. Uses `RoleProvider` to provide back the information. An implementation of a `RoleProvider` that already exists is `EcsRoleProvider`.
> feature(provider/ecs) Added Role Controller.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Not sure if this addresses https://github.com/spinnaker/spinnaker/issues/2334, but it does cut down the number of kubectl calls to roughly 1/3 by reducing redundant namespace calls.
> perf(provider/kubernetes): v2 small perf improvements

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCertificateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
Clouddriver will crash if the spinnaker role is missing permission for `ListServerCertificates`. This fix will log a warning with the affected account ID to make it easier to fix.
The warning will only be logged once every ~~hour~~ ten minutes for each affected account.
> fix(provider/amazon): Handle missing IAM permissions in caching agent

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
This allows `orca` to make a more informed decision when verifying that
a specific percentage of a server group has been disabled.
> feat(aws): Track the instanceIds being disabled

- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy
- clouddriver-eureka/src/test/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupportSpec.groovy
Previously it was iterating through each `health` and double counting
instances that had both eureka and non-eureka health statuses.
> fix(eureka): `getInstanceToModify` calculation was incorrect with multiple health statuses

- build.gradle
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/security/TestDefaults.groovy
@duftler @lwander Trying to update to spinnaker-dependencies to 0.142.1, but one test is failing. I thrashed on it all day and I couldn't really figure out why the ObjectMapper started failing. My initially inclination was going to be to refactor `TestDefaults` to not use maps, but the actual objects, but don't want to go down this path if there's something simpler. Would any of you Googlers be able to pull this down and give it a pair of eyes?
> chore(*): Bump spinnaker-dependencies to 0.142.1

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupController.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupControllerSpec.groovy
AWS is moving to a 17-character resource ID for images (among other resources).
Thanks to @benjaminws for pointing this out and looking at the code to find the affected paths.
Closes https://github.com/spinnaker/spinnaker/issues/2356
> fix(amazon): support long AMI ID patterns in image lookup

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactProviderProperties.java
Basic auth is supported just like for GitHub artifact accounts. I used "http/file" to match "github/file", but I can of course change it to "http/text" if that's preferred.
> feat(artifacts): Add support for HTTP artifacts

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Closes https://github.com/spinnaker/spinnaker/issues/2283
Sample:
```yaml
kubernetes:
accounts:
- name: k8s-v2
providerVersion: v2
omitKinds: 
- ConfigMap
- Secret
```
will stop caching secrets & configmaps in that account.
> feat(provider/kuberentes): v2 restrict caching by kind

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy
Performs an upsert in a two-phase operation if the security group has self-referencing rules and does not already exist.
> feat(aws): Allow self-referencing security group clone ops

- build.gradle
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/CachingAgent.java
- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/DynomiteUtils.java
- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/ExcessiveDynoFailureRetries.java
- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cluster/DynoClusteredSortAgentScheduler.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentLock.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteCacheConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
Now that Dynomite supports lua scripting, I've pulled forward @lwander's `ClusteredSortAgentScheduler`. Commands `evalsha` and `loadscript` are still missing from Dynomite, so I copied / refactored it a little bit. Once those commands are available and we've vetted this, I'll upstream the improvements.
Also supports the generic `AgentExecution`, which the other scheduler does not, and is required for AWS.
> feat(cats): Dynomite-friendly ClusteredSortAgentScheduler

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/NotificationMessage.java
LifecycleNotifications now have nested objects (`InvokingAlarms`).
Stumbled around for some AWS docs to no immediate avail, but a snippet:
```
{'Message': {'Description': 'Launching a new EC2 instance: REDACTED',
'Details': {'Availability Zone': 'us-east-1d',
'InvokingAlarms': [{'AWSAccountId': 'REDACTED',
'AlarmDescription': None,
'AlarmName': 'awsec2-REDACTED-High-CPU-Utilization',
'NewStateReason': 'Threshold Crossed: 1 datapoint (5.984999999999999) was less than or equal to the threshold (40.0).',
'NewStateValue': 'ALARM',
'OldStateValue': 'ALARM',
'Region': 'US - N. Virginia',
'StateChangeTime': 1402188328924L,
'Trigger': {'ComparisonOperator': 'LessThanOrEqualToThreshold',
'Dimensions': [{'name': 'AutoScalingGroupName',
'value': 'REDACTED'}],
'EvaluationPeriods': 1,
'MetricName': …
```
> fix(provider/aws): LifecycleNotification JsonMappingException

- clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/aws/ElasticSearchAmazonInstanceCachingAgent.kt
- clouddriver-elasticsearch-aws/src/main/kotlin/com/netflix/spinnaker/clouddriver/elasticsearch/aws/ElasticSearchAmazonServerGroupCachingAgent.kt
If the indexer fails, we find ourselves creating new indexes and
never deleting the old ones.
This PR will proactively cleanup excess indexes.
> fix(elasticsearch): Proactively cleanup indexes when in a bad state

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesDeleteManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesDeployManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesPauseRolloutManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesResumeRolloutManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesScaleManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesUndoRolloutManifestValidator.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/servergroup/KubernetesResizeServerGroupValidator.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtilSpec.groovy
Solves https://github.com/spinnaker/spinnaker/issues/2325
Depends on #2409
> feat(provider/kubernetes): v2 restrict namespaces for uploading manifests

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
Colons are allowed in Kubernetes resource names, and used by default for several RBAC roles like "system:masters".
Replace ";" with ";" when storing the key, and do the opposite when retrieving the key.
> fix(provider/kubernetes): v2 Allow ":" in keys

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtilSpec.groovy
Access to resources that do not belong to any namespace should be permitted, since there is no namespace to use for restricting access.
> fix(provider/kubernetes): v2 Fix validation to not require namespace

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesClusterRoleBindingCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesClusterRoleCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesRoleBindingCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesRoleCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesServiceAccountCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesClusterRoleBindingHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesClusterRoleHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesRoleBindingHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesRoleHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceAccountHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ManifestController.java
Adds support for ClusterRole, ClusterRoleBinding, Role, RoleBinding and ServiceAccount resource kinds.
Cluster-level resources like Role, ClusterRoleBinding, PersistentVolume, etc. do belong to any namespace, so we also add support for resource kinds without namespaces. Previously the "namespace" resource kind was the only kind which did not belong to a namespace.
While this PR adds a lot of lines, most of it is boilerplate code in the new caching agents and handlers.
> feat(provider/kubernetes): v2 Add support for RBAC resource kinds

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
"status.getUpdatedNumberScheduled" may be null for DaemonSets that have not been updated.
Deployments of new DaemonSet get stuck without this, and DaemonSets that have not been updated but are discovered by clouddriver are stuck in "Transitioning" state in the UI.
> fix(provider/kubernetes): v2 Fix stability check for DaemonSet

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReport.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReportBuilder.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonReservationReportProvider.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonReservationReportBuilderV4Spec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopReservationReportProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ReservationReportProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ReservationReportController.groovy
The V3 reservation report uses regional reservations in a very specific
order to cover shortfalls.
It is problematic if the consumer does not look at all instance types in
a family when determining availability.
This PR uses a proportional approach to cover shortfalls. Each instance
type is allocated a portion of regional reservations in proportion to
how much of the overall shortfall it contributed.
ex)
m4.4xlarge has a shortfall equivalent to 20 fxlarge
m4.* has a total shortfall equivalent to 40 fxlarge
Total regional reservations equivalent to 30 fxlarge
m4.4xlarge would cover shortfall with 50% of the regional reservations
(20/40 * 30 == 15)
> feat(reservations): V4 reservation report that proportionally covers shortfalls

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ResizeAsgDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperation.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperationUnitSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/ResizeAsgDescriptionValidatorSpec.groovy
We need to replace ResizeAsgDescription.Capacity with something that has
optional (i.e. nullable) fields. ServerGroup.Capacity happens to have
exactly that.
> feat(aws): add support for resizing ASGs with optional min/max/desired

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonImage.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonImageProvider.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonImageProviderSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/CloudDriverConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ImageProvider.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopImageProvider.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ImageController.java
This PR adds functionality to get an image based on the id of the image. Currently, only AWS provider is implemented.
Based on an image id (`ami-123321`), it would be possible to call `images/aws/ami-123321` and retrieve the information about such image - including the server groups and instances where the image might be used.
Usefulness of such endpoint:
- Cleaning up images. After using spinnaker for some time and baking a lot of images, these images start to pile up and increase costs and resource usage. Being able to know if a certain image is being used or not, is useful to make a decision on either delete it or not.
- Security. At some point, a certain image can be discovered to have been compromised - having a quick way to identify which server groups/instances are using such image …
> feat(provider/aws) Fetch image information based on image id

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
Logs out the address of the docker registry when a tag cannot be found. This is useful when there are multiple docker registries configured with similar tag names
> fix(docker): logs the registry address when a tag cannot be loaded

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
Currently logs are being littered with warnings in regions that are
otherwise empty.
> fix(aws): Only log warrning if `lastModified` not present and non-empty

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CacheConfig.groovy
An attempt to cut down on some useless redis calls being made for every
search.
I do not believe there is a need for a default `SearchableProvider`
implementation, there will almost certainly be a concrete `Bean`.
> fix(cache): Remove anonymous noop `SearchableProvider`

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
The handler for statefulsets was essentially using a hard-coded `ArtifactReplacerFactory.dockerImageReplacer()`, and was missing replacers for configmaps, secrets, etc.
> fix(provider/kubernetes): v2 Fix artifact replacers for StatefulSets

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerSpec.groovy
The changes in https://github.com/spinnaker/clouddriver/pull/2412 used the wrong pattern, and didn't match the beginning and end of the string, so it allowed partial matches in invalid strings.
Adding some tests to make it less likely that this happens again.
> fix(artifacts): Fix broken Docker image name matching and add tests

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
Artifacts were not replaced in DaemonSet manifests.
> fix(provider/kubernetes): v2 Use artifact replacers for DaemonSets

- README.md
- build.gradle
Starting clouddriver with /gradlew -DDEBUG=true now causes the JVM to
listen for a remote debugger on port 7102.
> chore(build): add debug flag to clouddriver build

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy
It would be useful in `deck` to have the server group capacity
available for all server groups by default.
> feat(web): Include `capacity` in `ServerGroupViewModel`

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandAgent.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamPolicyReader.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SecurityGroupController.groovy
Only schedule this agent for accounts where it is explicitly enabled.
This PR also cleans up some unnecessary usage of `e.printStackTrace()`.
> cleanup(aws): Avoid scheduling `ReconcileClassicLinkSecurityGroupsAgent`

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiVersion.java
Note, this isn't totally necessary since once you have jobs in your k8s
cluster, Spinnaker will register this. But since we do it for other APIs
that we support "out of the box", we may as well be consistent.
> feat(provider/kubernetes): register batchv1 api

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactUtils.java
- clouddriver-google/clouddriver-google.gradle
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BaseGoogleInstanceDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
With this change, a BaseGoogleInstanceDescription can now
optionally contain a reference to an artifact, containing
a gce/image artifact that should be deployed to that image.
> feat(artifacts): GCE deploy can consume image artifacts

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/BasicGoogleDeployDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/CreateGoogleInstanceDescriptionValidator.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy
Now that an instance's image can be either a string or an artifact, update the validation to allow either of these cases.
> feat(artifacts): Update google deploy validator to handle artifacts

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperation.groovy
Provided a server group is not attached to a load balancer, we can
greatly increase the speed at which a resize to zero can occur _if_ we
explicitly terminate instances alongside the min/max/desired adjustment.
> fix(aws): Explicitly terminate instances when resizing to zero

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgReferenceCopier.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
* Adds some more logging
* Will attempt to continue deploy operation if the server group already exists and matches desired state
> fix(aws): Make deploy atomic operation more resilient to AWS failure

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfiguration.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerClassicDescription.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/CreateAmazonLoadBalancerDescriptionValidator.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperationSpec.groovy
Adds configurable connection draining support and defaults for classic loadbalancers.
Moves the default for cross zone balancing into a configurable option.
When modifying an existing load balancer, load balancer attributes are
not modified unless explicitly included in the request.
> feat(aws/loadbalancing) connection draining support

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy
We're getting an NPE here while running build integration tests which are obscuring the actual failure.
> fix(caching): caching agent metricsSupport being null obscures original exception

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CustomKubernetesHandlerFactory.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesClusterRoleBindingHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesClusterRoleHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesConfigMapHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesControllerRevisionHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesEventHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesIngressHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesNamespaceHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesNetworkPolicyHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeClaimHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesRoleBindingHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesRoleHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesSecretHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceAccountHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/HandlerPrioritySpec.groovy
There were two ways to do this,
1. Infer a dependency graph from the manifests, and walk the graph to deploy
2. Manually assign deployment priorities
While 1 seems cleaner, it has a few problems:
a) All relationships (e.g. a pod can mount a config map) need to be declared ahead of time
b) Not all relationships are as easily inferrable as "resource A references B by name"
For example, we want a network policy governing pods' access to exist before the pods do, but this requires matching the pod labels, or knowing both exist in the same namespace
c) It's difficult to express in config how to determine what relationships to look for (dependencies to walk) for user-defined CRDs/TPRs
Closes https://github.com/spinnaker/spinnaker/issues/2304
> feat(provider/kuberntes): deploy priority

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleNamedImageLookupController.groovy
When listing the images for a Google account, we don't use any of the returned cache relationships, so skip fetching these from the cache entirely.
> fix(google): Don't fetch image relationships

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProviderConfig.groovy
Now that the `TitusClusterCachingAgent` supports on-demand cache
refreshes, it seems unnecessary to have the agent run every 10s.
This PR aligns the caching interval with that of AWS (30s).
> fix(titus): Align default caching agent timeout with AWS (every 30s)

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesEventCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesIngressCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNamespaceCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesServiceCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesStatefulSetCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesPodCachingAgentSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesReplicaSetCachingAgentSpec.groovy
https://github.com/spinnaker/spinnaker/issues/2644
By default we currently register 23 agents per account, each making several kubectl calls per cycle. Adding agents is increasingly expensive.
All this does is allow us to register caching agents that cache multiple kinds -- no caching agents take advantage of that yet though.
@wjoel FYI
> refactor(provider/kubernetes): lay groundwork for "multi-kind" caching agents

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/SimpleGrpcChannelFactory.groovy
Using NettyChannelBuilder allows us to set the maxInboundMessageSize to support increased page size, addressing comments on https://github.com/spinnaker/clouddriver/pull/2519
> refactor(titus): use NettyChannelBuilder for maxInboundMsgSize

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/ResizeTitusServerGroupAtomicOperation.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java
We got a little confused with our verbs and are setting `disableDecreaseDesired` and `disableIncreaseDesired` to the opposite of what we should be setting them to.
Also, when resizing a disabled job, we need to ensure the flags are set correctly.
There is no plan to expose these flags at the level of granularity AWS exposes them at, so we are not going to try to track them and reset them any more than this when doing a resize.
> fix(titus): properly set scaling flags when enabling/disabling/resizing

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/AlwaysUpHealthIndicator.java
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/DockerRegistryConfiguration.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/health/DockerRegistryHealthIndicator.groovy
Making docker health indicator act like the AmazonHealthIndicator in that once it's healthy, it's always healthy. This will allow us to still gate the deployment of a clouddriver instance based on whether or not it can communicate with a docker registry, but not take clouddriver down if the docker registry goes unhealthy sometime afterwards.
Made the logic generic, so other health indicators can get the same sort of behavior.
> fix(docker): Do not cascade docker registry failures to health indicator

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/SecurityGroupProvider.groovy
When `includeRules` is `false`, the cache key for a security group
actually includes all relevant information.
We _do not_ need to retrieve all objects and can instead just parse
keys and manually construct an `AmazonSecurityGroup`.
There is _some_ chance that the set of identifiers includes some
security groups that do not actually exist. I believe this to be of
minimal risk and the performance benefits outweigh the potential for
issue.
The return types in `SecurityGroupProvider` were changed from `Set` to
`List`. It turns out that converting a list of 20k items to a set takes
a non-zero amount of time.
> perf(aws): Optimize the retrieval of all security groups

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/SimpleGrpcChannelFactory.groovy
Reverting netty channel builder but keeping the property change of `.url`
> fix(titus): revert netty but keep titusRegion.url change

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusJobProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusClient.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClientSpec.groovy
getJob in titus can be very expensive if there are a lot of terminated tasks in services. This method is really intended to be used with the run job stage, so making it clearer in the api that this is the case
> fix(titus): change titus api to make intent of getJob more explicit

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusRegion.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/config/TitusConfiguration.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DestroyTitusServerGroupAtomicOperationSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClientSpec.groovy
Titus Region Client can now behave differently in different Titus regions, so we can slowly roll out new client features.
Config option is at the region level, just like `apiVersion`, and is controlled with Boolean flag `experimentalFeaturesEnabled`
> feat(titus): adding feature flag in region scoped titus client

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusClientProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusException.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/config/TitusConfiguration.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/v3client/RegionScopedV3TitusClient.java
We're seeing occasional failures when a titus task cannot be found, and causes the operation to fail. If the task is terminate and shrink it's ok to ignore NOT_FOUND, but otherwise we should retry in case of transient failures.
> fix(titus): add retry to kill task, ignore NOT_FOUND

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProviderConfig.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy
When enabled, the titus cluster caching agent will only write a minimal
ON_DEMAND record.
It will take longer for a change to become visible (until the next
cache cycle completes) but should have much less overhead.
> perf(titus): A feature flagged alternative OnDemand implementation

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2SearchProvider.java
Happens only when you have stale cache entries & no v2 accounts registered anymore, but still frustrating since it breaks all of search
> fix(provider/kubernetes): v2 search omit null

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2SearchProvider.java
> fix(provider/kubernetes): v2 search omit null (#2568)

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
This isn't ideal, since what's really happening is we are querying each
cloud provider (even ones not in use, in this case k8s v2) if it
supports 'minimal clusters'. v1 doesn't, v2 does. This winds up loading
the same cache entry twice, once with and once without a timestamp. As a
result, some cache entries show up twice, at the end of the list of
returned server groups.
> fix(provider/kubernetes): lookup of oldest server group

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
This isn't ideal, since what's really happening is we are querying each
cloud provider (even ones not in use, in this case k8s v2) if it
supports 'minimal clusters'. v1 doesn't, v2 does. This winds up loading
the same cache entry twice, once with and once without a timestamp. As a
result, some cache entries show up twice, at the end of the list of
returned server groups.
> fix(provider/kubernetes): lookup of oldest server group (#2573)

- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/BulkUpsertEntityTagsAtomicOperation.java
Avoid the resulting `UnsupportedOperationException` stemming from
`entityTags.removeAll()` when `entityTags` is an empty unmodifiable
list.
> fix(entitytags): Avoid an `UnsupportedOperationException`

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java
Currently the S3 client does not support custom API endpoints. This PR adds `apiEndpoint` and `apiRegion` fields to `artifacts.s3.accounts`, and adds them to the S3 client.
> feat(artifacts): Add custom API endpoint for S3 client

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
This prints each entire manifest during a deploy, and is rather noisy.
> chore(provider/kubernetes): reduce log level for artifact swapping

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
A small regression of this https://github.com/spinnaker/clouddriver/pull/2539
Using this `cacheView.getIdentifiers(SECURITY_GROUPS.ns)` fetches all security groups (including from providers other than AWS) which will then result in NPE.
The fix will fetch keys for all security groups but only from AWS.
> fix(aws) Security group retrieval fix

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsTargetGroupCacheClient.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsLoadbalancerCacheClientSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsTargetGroupCacheClientSpec.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy
Incremental update to the `/{cloudProvider}/loadBalancers` endpoint for AWS. By adding the target type to the target group key, we can fetch them all once and parse them instead of going to Redis once for each ALB and fetching the full target group details.
This is not going to be a major performance improvement on its own, I don't think: it seems like we're cutting the number of entries we get from Redis by about 33% (although that number would grow larger as ALBs supplant CLBs). The structure of the response to the call is much more complex than the comparable one to fetch all security groups - in addition to target groups, we include security group IDs associate with the load balancer for some reason, and I'm not sure who is using that data.
There are additional improvements we're …
> perf(amazon): optimize target group loading for /loadBalancers

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
Effectively this PR will publish `v4` as `v3`.
> feat(reservations): Backport changes from v4 to v3

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ClusterProvider.java
Getting this out of the way as I may have a subsequent need to make use
of a `default` interface method.
> chore(groovy): Convert ClusterProvider from groovy -> java

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsReconciler.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/config/ElasticSearchConfig.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/config/ElasticSearchConfigProperties.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsReconcilerSpec.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/admin/EntityTagsAdminController.java
This PR introduces a new administrative api supporting reconcilation of
entity tags against the current cached set of server groups.
Entity Tags that reference a non-existent server group will be removed
from elastic search.
A subsequent effort will provide a means to perform reconciliation
against `front50`.
The API is exposed directly on `clouddriver`:
```
curl -X POST localhost:8101/admin/tags/reconcile?cloudProvider=aws&account=test&region=us-west-2
```
> fix(entitytags): Reconciliation API for Entity Tags

- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
Avoid a circular dependency between `ElasticSearchEntityTagsProvider`
and `ElasticSearchEntityTagsReconciler`.
The latter has a dependency on `CacheView` which breaks when the
`launchFailureNotificationAgentProvider` is enabled.
> fix(entitytags): break circular dependency

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
removes the existingIdentifiers call on the in-memory instance cache
as this cache is loaded per clouddriver instance it can balloon out to a
large number of exists calls
> fix(search) less redis interaction on instance cache

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactProviderProperties.java
adds a gitlab artifact provider. follows most of the same logic in the
github provider. relies on the gitlab raw file api.
@lwander PTAL
> feat(artifacts): add gitlab artifact provider

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java
this commit fixes two issues with the s3 artifact provider. 1, it adds
support for configuring an s3 region. this is inline with how we already
handle it in front50, allowing for usage of buckets in separate regions.
also, when using `apiEndpoint` we not set `pathStyleAccessEnabled` which
enables support for things like Minio to act as a provider.
@lwander @benjaminws PTAL!
> fix(artifacts): s3 improvements

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandler.java
When deploying updates to a HorizontalPodAutoscaler, versioning them
will create multiple instances of the HPA, all of which still try to
target/autoscale the scaleTargetRef. Since I don't believe there are
other resource types that refer to a HPA, it is not clear that this
needs to be versioned like ConfigMaps or Secrets.
> provider/kubernetes: remove versioning of HorizontalPodAutoscalers

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperation.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperationUnitSpec.groovy
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/events/CreateServerGroupEventHandler.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/events/DeleteServerGroupEventHandler.java
Silly logic error was preventing this from happening previously.
> fix(core): Correctly track any OperationalEvents generated by a deploy

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DestroyKubernetesAtomicOperation.groovy
Got the following error when attempting to shrink a cluster.
No such property: log for class: com.netflix.spinnaker.clouddriver.kubernetes.v1.deploy.ops.servergroup.DestroyKubernetesAtomicOperation
> fix(provider/kubernetes): Adding missing log definition.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
closes: https://github.com/spinnaker/spinnaker/issues/2830
The reason this worked for stack & detail was because the `moniker` field in the op description likely didn't have them specified.
> fix(provider/kubernetes): don't override annotations

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeClaimHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeHandler.java
These are typically provisioned with a separate lifecycle, and are often used to persist data beyond the length of a pod's lifespan. They can still be versioned using the `strategy.spinnaker.io/versioned`
annotation, but it arguably is confusing as a default behavior
@imosquera @wjoel PTAL
> fix(provider/kubernetes): default behavior shouldn't version volumes

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.groovy
When multiple caching agents handle an on-demand refresh, the return
status is currently based only on the result of the last agent.  Instead
we should return a PENDING result if *any* of the caching agents find
results, rather than only if that last one does.
> fix(caching): Fix on-demand cache result return status

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentSchedulerSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/JedisCacheConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfigurationProperties.groovy
(Please view with ["ignore whitespace"](https://blog.github.com/2011-10-21-github-secrets/#whitespace)).
We just saw clouddriver try and acquire all the locks, then die. This makes the max number of caching agents to schedule at once and the interval at which we schedule configurable. It defaults to the current behavior.
Set with:
```
redis:
agent:
maxConcurrentAgents: 100
agentLockAcquisitionIntervalSeconds: 5
```
> fix(caching): add config for number of concurrent scheduled agents

- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCacheOptions.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/core/agent/CleanupPendingOnDemandCachesAgentSpec.groovy
Similar to spinnaker/clouddriver#2666 but this time behind a
`caching.redis.treatRelationshipsAsSet` flag.
> perf(cats): Support `List` -> `Set` relationship deserialization

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/OnDemandMetricsSupport.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/provider/agent/Namespace.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusCloudProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/Keys.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProviderConfig.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusClusterCachingAgent.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusInstanceCachingAgent.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusV2ClusterCachingAgent.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusInstanceProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/utils/AwsLookupUtil.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/utils/CachingSchema.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/utils/CachingSchemaUtil.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusClient.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/TitusLoadBalancerClient.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Job.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Task.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/config/TitusConfiguration.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/credentials/NetflixTitusCredentials.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusJobStatus.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClientSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DestroyTitusServerGroupAtomicOperationSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstanceSpec.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroupSpec.groovy
(I'll update this PR with performance numbers, opening for feedback)
Only controller API call that produces different responses is this set:
```
https://localhost:8081/applications/emburnstest/clusters/titustestvpc/emburnstest-responses?expand=false
https://localhost:8081/applications/emburnstest/clusters/titustestvpc/emburnstest-responses?expand=true
```
In the current implementation, both return instance details. This PR changes the response so that when `expand=false` the `instances : []` list is empty. It is populated when `expand=true`.
Also, this PR fixes titus instance searching (it is broken in the current Titus implementation due to incorrect Key parsing)
> feat(titus): split caching into two agents

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
Adding more logs to help track down some clouddriver shenanigans.
> fix(logs): add more caching info

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfig.groovy
Also updated the `ClusteredAgentScheduler` to compare `getAgentType()`
rather than `agent.class.simpleName` when determining whether the
agent should be scheduled.
> chore(redis): `JedisPool` metrics (numActive, numIdle, numWaiters)

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
LUA call was returning a Long not an Integer, deleteLock
was always returning false.
Previously we ignored the value, now we use it to drive
a logging message.
> fix(cats): ClusteredAgentScheduler.deleteLock

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusV2ClusterCachingAgent.java
Load Balancing can be toggled on and off for Titus. Handle that.
> fix(titus): handle load balancing not enabled in account

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/tags/EntityTagger.groovy
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchEntityTagger.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/DeleteEntityTagsAtomicOperationConverter.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/converters/UpsertEntityTagsAtomicOperationConverter.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/config/ElasticSearchConfig.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ElasticSearchEntityTaggerSpec.groovy
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/converters/UpsertEntityTagsAtomicOperationConverterSpec.groovy
Same thing as @cfieber's pull request, but with comments addressed and changed the interface method to expect `namespace` instead of `category`, since `category` is really only specific to alerts & notices at this point.
Also added a wee bit of docs around a few properties that were confusing me.
Prior art: https://github.com/spinnaker/clouddriver/pull/2540
> feat(entity_tagger): Support generic tag interface

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandlerSpec.groovy
Deploy operations explode if container attributes are received as non-strings.
> fix(titus): Ensure containerAttributes values are strings

- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosServerGroup.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosClusterAware.java
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosLoadBalancerCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosSecretsCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosServerGroupCachingAgent.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/config/DcosProviderConfig.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/BaseSpecification.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/model/DcosServerGroupSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosLoadBalancerCachingAgentSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosSecretsCachingAgentSpec.groovy
- clouddriver-dcos/src/test/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/agent/DcosServerGroupCachingAgentSpec.groovy
Caches DC/OS data at the cluster level instead of account level for DC/OS accounts. This prevents duplicate caching and API calls when multiple Spinnaker accounts exist for the same DC/OS cluster.
> fix(provider/dcos): Cache per cluster/service account pair.

- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/DcosSpectatorHandler.groovy
Removes the full failure message from the reason for dc/os exceptions in spectator metrics labels, since having the full failure message is not the point of a label.
> fix(provider/dcos): less verbose spectator metrics labels for dc/os exceptions

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ClusterProvider.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterControllerSpec.groovy
When getting clusters by account we don't want the instances. In the titusClusterProvider we were returning instances and then throwing them away. Now, we can optionally not ask for instances.
> fix(titus): don't ask for instances when they're not wanted

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/admin/EntityTagsAdminController.java
Remove two warnings on startup about optional constructors being effectively required due to the lack of a default constructor.
> fix(startup): Fix startup warnings

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java
Expose the map from k8s resource kinds to Spinnaker kinds.  E.g. ReplicaSet -> ServerGroup; Deployment -> ServerGroupManager
This will be consumed by the UI to correctly route the user from a resource deployed during an execution to its details view.
Fixes https://github.com/spinnaker/spinnaker/issues/2496
> feat(kubernetes): surface kind mapping to credentials API

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerSpec.groovy
Tests checking for the validity of an image were removed, since they are
only exercised on already deployed manifest objects. If kubernetes
accepts a docker image, we don't provide any value in refusing to parse
it. Also, parsing it turned out to be very expensive for certain image
configurations.
> fix(provider/kubernetes): fix regex perf bug when parsing images

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AwsSdkClientSupplier.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/RateLimitingRequestHandler.java
There is no guarantee that a `Counter` will be re-used across requests.
At Netflix, we're seeing an issue wherein the `AwsSdkClientSupplier`
has a zero hit rate due to the `Counter` reference changing between
requests to the same account/region.
This PR also introduces a TTL on the sdk clients cache (10min after access)
to offer future protection against poor hash/equals performance.
> fix(aws): Equality of `RateLimitingRequestHandler` should not depend on counter

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java
When clouddriver starts and an account is unhealthy due to an
unreachable cluster, it will remain unhealthy until restarted. When
running, it will set the entire pod as unhealthy (even if other accounts
are useable). These changes allow clouddriver to start normally, and
keep other accounts reachable.
Closes: https://github.com/spinnaker/spinnaker/issues/2961
@mdirkse FYI
> fix(provider/kubernetes): be more tolerant of failing health checks

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerInstance.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Instance.java
As with https://github.com/spinnaker/clouddriver/pull/2751 this is to get unique IDs into Deck for Kubernetes instances.
> feat(provider/kubernetes): add UID field to LoadBalancerInstance

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesConfigParser.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesConfigParserSpec.groovy
Always use the server property of a cluster in the kubeconfig file as the master URL.
Fixes spinnaker/spinnaker#3005
> Always honor the server property of a kubeconfig cluster block

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Instance.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerInstance.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Instance.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/ManifestBasedModel.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy
DONT MERGE until a parallel PR in Deck has been approved (https://github.com/spinnaker/deck/pull/5506).
The `Instance` interface has an implicit constraint on it that the `name` field should return a globally unique ID for the resources it fronts.  This constraint is relied upon by Deck to disambiguate between instances in various UI contexts.  A non-unique string name can cause some strange UI behaviour.  See here for an example: https://github.com/spinnaker/spinnaker/issues/2979
Previously, a k8s v2 resource returned its "fullResourceName" as its `Instance.name` but this could lead to non-unique IDs being serialized by an InstanceViewModel or LoadBalancerInstance.  This PR makes the k8s v2 provider return a resource's uuid in place of its name when responding to requests for ServerGroup …
> feat(provider/kubernetes): make id field unique, add name field for full resource name

- Dockerfile.slim
This enables the App Engine provider to deploy Standard Java App Engine apps. This change only modifies the container, changing:
* The base image from JRE to JDK. `gcloud app deploy` always does inspection/compilation when deploying Java apps.
* The Google Cloud SDK install to include the Java App Engine components (also removing a deprecated flag in the install command).
* The current working directory. An issue with the Google Cloud SDK breaks Java App Engine deployments if the cwd is '/'.
This was tested against the App Engine Standard Java 8 "getting started" app "helloworld" from https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/helloworld
Approach was discussed with @danielpeach offline.
> feat(provider/appengine): Enables App Engine Standard Java 8.

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy
We spotted NullPointerExceptions in the logs our production spinnaker at Target, coming from this line. Given that the previous line does a null check on `stack`, it only makes sense that this line would, too.
> fix(provider/openstack): tolerate null stack, for real this time.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/KubernetesUtilSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
In order to support deploying a container injected into a pipeline as an artifact, allow the Kubernetes provider to deploy images specified using a digest.
> feat(provider/kubernetes): Allow image selection by digest

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/KubernetesUtil.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
Allow Orca to send just the container URI to clouddriver, so that the parsing logic in Clouddriver can be used to parse this into registry, repository, and tag, avoiding the need to re-implement this in Orca.
> feat(provider/kubernetes): Parse container URI in clouddriver

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesAutoscalerStatus.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesControllersCachingAgent.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy
Here are another couple cases where we've seen `NullPointerException`s in our production spinnakers. The exceptions were causing some entire clusters not to load, and thus not to show up in the Clusters page for a given app.
This fix has already been deployed and validated in both our test and prod environments. Since deploying it, all NPE's have disappeared from the logs, and several cases of missing clusters have resolved.
> fix(provider/kubernetes): tolerate null selectors and statuses.

- cats/cats-dynomite/src/main/java/com/netflix/spinnaker/cats/dynomite/cache/DynomiteCache.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
Removes unnecessary double writes of allOfTypeId sets.
> fix(cats): remove obsolete reindex code

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusTargetGroupServerGroupProvider.java
The NPE was caused by traversing a map-of-maps without actually being certain the data is there. Seems like the actual usage here is reasonable, but the cache data was corrupted / inconsistent in Redis. In this case, we'll just not report health data.
I took this as an opportunity to clean up the class a little as well, but the changes are in separate commits.
> fix(titus): Handle/report incomplete target group cache data

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerFactory.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacerSpec.groovy
adds support for binding initContainer images in the
`dockerImageReplacer`.
fixes spinnaker/spinnaker#2535
> fix(provider/kubernetes): bind initContainers

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandlerSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandlerSpec.groovy
When two artifacts with the same name & namespace are deployed to
different clusters, Spinnaker previously couldn't tell them apart when
deciding which to match & replace in a deployed manifest
https://github.com/spinnaker/spinnaker/issues/3071
> fix(provider/kubernetes): v2 check that artifact & cluster account match

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandlerSpec.groovy
cherry pick (#2799) into 1.8
When two artifacts with the same name & namespace are deployed to
different clusters, Spinnaker previously couldn't tell them apart when
deciding which to match & replace in a deployed manifest
> fix(provider/kubernetes): v2 check that artifact & cluster account match 

- cats/cats-core/cats-core.gradle
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/module/CatsModule.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/module/DefaultCatsModule.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/provider/DefaultProviderCache.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/provider/DefaultProviderRegistry.java
- cats/cats-core/src/test/groovy/com/netflix/spinnaker/cats/provider/DefaultProviderCacheSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CacheConfig.groovy
- clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtilsSpec.groovy
Adds logging and metrics on putCacheResult capturing rate of change on a type from a specific agent.
Context: We had an issue where one of our data sources was periodically flopping between current and a very old result set, causing significant churn in the data set against redis and corresponding significant uptick in replication traffic
> feat(cache): metrics on putCacheResult.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
When caching resources used by HTTPS load balancers, we don't pass along the list of failed load balancers, to a failure is not recorded and we can end up storing an incomplete load balancer to the cache.
> fix(google): Properly handle failures caching HTTPS load balancers

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
If a 401 is received from the Docker registry, the cached token is
cleared so it isn't reused if a new token isn't acquired. Subsequent
requests will then get a new token, if necessary.
fixes spinnaker/spinnaker#2039
> fix(provider/docker): Clear docker token cache after 401

- cats/cats-core/cats-core.gradle
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/module/CatsModule.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/module/DefaultCatsModule.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/provider/DefaultProviderCache.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/provider/DefaultProviderRegistry.java
- cats/cats-core/src/test/groovy/com/netflix/spinnaker/cats/provider/DefaultProviderCacheSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CacheConfig.groovy
- clouddriver-security/src/test/groovy/com/netflix/spinnaker/clouddriver/security/ProviderUtilsSpec.groovy
Revert "fix(perf): fix performance regression due to default provider cache metrics causing extra redis reads. (#2816)"
This reverts commit 45642482c98d670df82b9853c63a9222f5aa5a65.
Revert "feat(cache): metrics on putCacheResult. (#2790)"
This reverts commit e78a1aebc28d3afadf358e7e69ed739c299e88dd.
> fix(perf): reverts DefaultProviderCache metric changes

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactProviderProperties.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactProviderProperties.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactProviderProperties.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactProviderProperties.java
when enabling multiple http based artifact providers (http + gitlab +
github) clouddriver filed to start stating that multiple beans were
found.
> fix(artifacts): fixes multiple http base providers - 1.8

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
Newer versions of spinnaker-dependencies do not include FindBugs.
clouddriver fails to build since upgrading spinnaker-dependencies to 0.158.0: https://github.com/spinnaker/clouddriver/pull/2732
https://github.com/spinnaker/clouddriver/pull/2825 fixed this for the 1.8 branch, and the discussion suggests dropping the annotations, so that's what this commit does.
> fix(cats): Remove unsupported annotations

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Cluster.java
Return cluster type "kubernetes.v2" instead null
bug: https://github.com/spinnaker/spinnaker/issues/3056
> fix(provider/kubernetes): set cluster type in k8s v2 provider

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCacheOptions.java
- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
- Updating redis scan and multi-key operation batch size defaults based on Netflix's production configuration.
> fix(cats): saner redis defaults

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java
Check the actual code instead of the status object.
Verified locally by submitting a terminate task for two instances I'd already terminated, and the task succeeded.
> fix(titus): actually ignore NOT_FOUND

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
- clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy
Allows users to use passwordCommand instead of password or passwordFile if their setup isn't conducive to the latter two options. This refreshes the credentials anytime the docker creds are used (every time it caches images), so an agent wasn't needed to re-initialize credentials constantly.
Completes https://github.com/spinnaker/spinnaker/issues/2941
> feat(provider/docker): adding passwordCommand option for retrieving docker credentials

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestMetadata.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/artifact/KubernetesCleanupArtifactsOperation.java
This is a fairly significant CPU improvement when caching large
clusters. We're seeing ~5-10% reduction in CPU usage during cache data
construction by not creating & passing around empty artifacts for every
resource deployed to a given cluster.
> fix(provider/kubernetes): avoid caching empty artifacts

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestMetadata.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/artifact/KubernetesCleanupArtifactsOperation.java
This is a fairly significant CPU improvement when caching large
clusters. We're seeing ~5-10% reduction in CPU usage during cache data
construction by not creating & passing around empty artifacts for every
resource deployed to a given cluster.
Cherry pick into 1.9
> fix(provider/kubernetes): avoid caching empty artifacts (#2841)

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
This was generating a lot of incorrect log warnings about kinds missing namespaces during caching
> fix(provider/kubernetes): record if a crd is namespace-scoped

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
This was generating a lot of incorrect log warnings about kinds missing
namespaces during caching
Cherrypick into 1.9
> fix(provider/kubernetes): record if a crd is namespace-scoped (#2849)

- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperationSpec.groovy
Might as well delete any entity tags from elastic search if we determine
they don't exist in front50.
> feat(entitytags): Reconcile elastic search if entity tags don't exist

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
This greatly speeds up (testings shows reduction of ~25% time spent) caching
runs for large agents.
> fix(provider/kubernetes): only load relevant on demand keys

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
This was generating very large (1 per resource) numbers of duplicate
cache entries that both ate up memory, and required expensive
relationship merging & deduping later. We don't actually make use of
this relationship anywhere, and it can be infered from a resource's key
in the cache, making it redundant.
> fix(provider/kubernetes): don't record namespace relationship in cache

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
This was generating very large (1 per resource) numbers of duplicate
cache entries that both ate up memory, and required expensive
relationship merging & deduping later. We don't actually make use of
this relationship anywhere, and it can be infered from a resource's key
in the cache, making it redundant.
Cherry pick into 1.9
> fix(provider/kubernetes): don't record namespace relationship in cache (#2859)

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
Another effort at reducing the number of cache objects being deduped and
stored in memory during cache cycles.
> fix(provider/kubernetes): only record app relationships for clusters

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
Cuts time spent in method by ~50%, currently dominating roughly 20% of a load cache cycle.
> fix(provider/kubernetes): reduce allocations during cache merge

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
> fix(provider/kubernetes): skip redundant check of kinds already omitted (#2866)

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/ArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/embedded/EmbeddedArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gcs/GcsArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java
I initially planned to return only a single artifact type for a given credential but I think there are realistic potential use cases for a credential supporting multiple types: a github or gitlab commit object, an embedded artifact that isn't base64-encoded, gcs or s3 object metadata.
> feat(artifacts): expose types supported by a given artifact credential

- clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/CloudFoundryCloudProvider.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/CloudFoundryConfiguration.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/CloudFoundryOperation.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClient.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/CloudFoundryProvider.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryCachingAgent.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/config/CloudFoundryProviderConfig.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsInitializer.java
- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
- settings.gradle
Based on a conversation with @duftler, we're splitting up the Cloud Foundry provider submission into individual PRs that can be reviewed in smaller chunks.
This initial PR contains the skeleton of the provider, up to and including credentials.
```yml
cloudfoundry:
enabled: true
accounts:
- name: pivotalwebservices
user: MYUSER
password: MYPASSWORD
api: api.run.pivotal.io
```
cc / @ethanfrogers
> feat(provider/cf): add provider skeleton with credentials management

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Prevents caching agents from stacking up while failing to ever complete
when indexing unavailable clusters. Will need to be set by a
user/operator.
FYI @benjaminws
> fix(provider/kubernetes): make request timeout configurable

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Prevents caching agents from stacking up while failing to ever complete
when indexing unavailable clusters. Will need to be set by a
user/operator.
Cherry pick into 1.9
> fix(provider/kubernetes): make request timeout configurable (#2869)

- clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/Keys.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/ResourceCacheData.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryApplication.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryBuildpack.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryCluster.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryDomain.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryDroplet.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryImage.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryInstance.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryLoadBalancer.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryModel.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryOrganization.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryPackage.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryRegion.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServiceInstance.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundrySpace.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryApplicationTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryClusterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryLoadBalancerTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundrySpaceTest.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Cluster.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
Adds Cloud Foundry implementation of Spinnaker model objects.
Previous PRs in this sequence: #2838, #2828.
> feat(provider/cf): add model and cache keys

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ClouddriverHostname.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DefaultTask.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/InMemoryTaskRepository.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/Task.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/TaskRepository.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTask.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/RedisTaskRepository.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/TaskController.groovy
- halconfig/clouddriver.yml
We have some tasks in GCP that take several minutes to finish. If clouddriver dies while the task is in progress the pipeline task can never complete. In the cases where we can safely shutdown clouddriver nodes (e.g. during update), giving it the option to drain work prevents this.
This is only enabled for halyard installations right now.
> feat(core): give clouddriver the option to shutdown gracefully

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
If the call fails, the memoizer can't record the success time, voiding
the use of an expiring memoizer. When a lot of deployments happen at
once, we check all our caching agent's kinds very frequently generating
a lot of calls to the "crd" kind, which are now all memoized.
> fix(provider/kubernetes): reduce crd lookups when none exist

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2SearchProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
We recently pruned the resources that are related to applications to speed up the caching by shrinking how tightly connected the graph of resources -> logical groupings was. By removing network policies, they became unsearchable by removing the edge from apps -> security policies.
> fix(provider/kubernetes): security groups are related to apps

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/TaskCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskCachingAgent.java
ECS tasks can have a null startedAt field for a short period -- this handles that gracefully
> fix(provider/ecs): Handle null startedAt field for tasks

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
If the call fails, the memoizer can't record the success time, voiding
the use of an expiring memoizer. When a lot of deployments happen at
once, we check all our caching agent's kinds very frequently generating
a lot of calls to the "crd" kind, which are now all memoized.
Cherry pick into 1.9
> fix(provider/kubernetes): reduce crd lookups when none exist (#2886)

- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/config/ElasticSearchConfigProperties.java
Storing multiple mapping types in the same index is deprecated in Elasticsearch 6 and will be removed in Elasticsearch 7. Add a config parameter indicating that only one mapping type per index is supported (defaulting to false, for backwards compatibility). If that parameter is set, all documents will their type set to the config parameter mappingTypeName, which defaults to Elasticsearch's recommended value of _doc.
> fix(entitytags): Don't set _type field on Elasticsearch documents

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AnnotationsBasedAtomicOperationsRegistry.groovy
The inclusion of version is a red-herring here, as this error means no
account was registered to handle the operation for the given provider
Cherry pick 1.9
> fix(core): fix error when no matching converter is found (#2915)

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
Support associating public IP addresses with ECS tasks when using VPC networking mode
> feat(provider/ecs): Add server group setting for public IP address

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
Adds support for the Fargate launch type for ECS provider
Notes:
* Uses the Spinnaker-managed role for the ECS account as the ECS execution role (same as how it used for the ECS service role)
* Sets the task's hard limits for CPU/memory to the same as the CPU/memory setting of the single container
* Explicitly setting the launch type to 'EC2' is supported, as well as null launch type value
> feat(provider/ecs): Add support for Fargate launch type

- clouddriver-artifacts/clouddriver-artifacts.gradle
For a modular cloud driver build, with say only the kubernetes provider, this reduces the number of JARs in `lib` from 326 to 185
Part of spinnaker/spinnaker#3114
> refactor(build): Depend on aws-sdk-s3 instead of the entire sdk

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/event/AfterResizeEvent.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/event/AfterResizeEventHandler.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/event/DefaultAfterResizeEventHandler.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/config/AwsConfiguration.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/event/DefaultAfterResizeEventHandlerSpec.groovy
This PR introduces an extension point allowing for custom behavior to
happen during a resize asg operation.
The default behavior has been modified such that instances will not be
explicitly terminated during a resize _if_ a terminating lifecycle hook
is present on the asg.
replaces spinnaker/clouddriver#2900
fixes spinnaker/spinnaker#3229
> fix(aws): avoid terminating instances when lifecycle hooks are present

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/ServiceCacheClient.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/model/Service.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceCachingAgent.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProviderSpec.groovy
- clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/cache/ServiceCacheClientTest.java
- clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/CommonCachingAgent.java
- clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceCacheTest.java
Since Fargate tasks don't have an EC2 instance, we need to display their VPC and security groups based on the service's network configuration.  Also applicable to ECS tasks on EC2 capacity, as their ENI security groups can be different from the underlying instance's security groups.
> fix(provider/ecs): Display VPC & security groups based on network config

- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackImageV2Provider.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackImageV2ClientProviderSpec.groovy
workaround for issue in Openstack4j library, locations cannot be
used without fix https://github.com/ContainX/openstack4j/pull/1096
Spinnaker issue: https://github.com/spinnaker/spinnaker/issues/3018
> fix(provider/openstack): Use directUrl property for image location

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsAccountMapper.java
ECS subnet and security group selection is currently broken on master, because EcsAccountMapper is initialized with zero accounts.  EcsAccountMapper is Autowired with AccountCredentialsProvider already, but it also depends on EcsCredentialsInitializer to have populated the accounts in that bean.
I think that previously (maybe before change #2905?), EcsAccountMapper just happened to be always initialized after EcsCredentialsInitializer, so the ECS and AWS accounts were always already populated.  I'm seeing that EcsCredentialsInitializer is now always initialized after EcsAccountMapper, so the accounts list is empty at the time that EcsAccountMapper is initialized.  This PR makes the dependency explicit.
I'm open to suggestions if there's a better way in Spring to wire up this dependency …
> fix(provider/ecs): EcsAccountMapper depends on EcsCredentialsInitializer

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
In the reverse order, autoscaling policy params are set _after_
we use them to set the target size of the instance. This was
causing GCE clones to clone the new server group at the source
server group's size regardless of the value of 'useSourceCapacity'.
> fix(provider/gce): set autoscaling cap before target size in deploys.

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/agent/ProjectClustersCachingAgent.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/config/CloudDriverConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/config/ProjectClustersCachingAgentProperties.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersServiceSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ProjectController.groovy
Turns out trying to cache all project clusters takes forever in larger deployments.
Rather than try to cache everything, this change makes caching opt-in project-by-project.
> fix(core): Make project clusters caching optional

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/agent/ProjectClustersCachingAgent.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/config/CloudDriverConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/config/ProjectClustersCachingAgentProperties.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersServiceSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ProjectController.groovy
* Moved to calling front50 for each individual project rather than everything, since we only cache a handful of projects.
* I didn't test the caching agent after normalizing the project names to lowercase, which broke things because I'm bad.
> fix(core): Front50 perf; separate normalized allow list method

- clouddriver-oracle/clouddriver-oracle.gradle
Fix the clouddriver startup problem due to the oci-java-sdk-full-shaded in the classpath.
> fix(provider/oracle): remove oci-java-sdk-full-shaded from classpath

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
The prior approach of always consulting the service account namespace
was causing confusion, especially when no service account was in use
@psalaberria002 fyi
> fix(provider/kubernetes): sane namespace lookup

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
Cherry pick of https://github.com/spinnaker/clouddriver/pull/2936 into 1.9
> fix(appengine): defer to configured project when using ADC

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppengineSafeRetry.groovy
- clouddriver-google-common/clouddriver-google-common.gradle
- clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/deploy/GoogleCommonSafeRetry.groovy
- clouddriver-google-common/src/test/groovy/com/netflix/spinnaker/clouddriver/googlecommon/deploy/GoogleCommonSafeRetrySpec.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/SafeRetry.groovy
Allows use to remove the dependency on `clouddriver-core`. This is mainly useful because Front50 also depends on `clouddriver-google-common` and thereby indirectly on all of clouddriver-core and every dependency it brings in. 
The only class from `clouddriver-core` that is used here is the `data.task.Task` class. I've moved the only usage of the Task class from the abstract class that is shared with Front50 to the 2 classes that implement the abstract `GoogleCommonSafeRetry` class in clouddriver. Currently, in Front50 we simply pass in `null` for the task parameter.
> refactor(google): Remove Task as a paramter for Retry

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
Previously we were including all instances in all locations of a given
server group in each server group written to the cache.
Needs cherry picked into last few releases.
> fix(provider/gce): Filter instance caching by location.

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
Previously we were including all instances in all locations of a given
server group in each server group written to the cache.
Cherry pick of https://github.com/spinnaker/clouddriver/pull/2991.
> fix(provider/gce): Filter instance caching by location. (#2991)

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersServiceSpec.groovy
The current approach to fetching clusters for a Project is quite
inefficient, particular for large applications wherein only a subset
of clusters are included in the project config.
This PR initially fetches cluster summaries and then applies a filter
to determine applicability. The applicable clusters are then fetched in
detail.
> perf(core): Attempted move away from fetching _every_ possible Project cluster

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/Application.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/LinkTest.java
We originally intended to support PCF 2.0+, but this minor change allows us to support PCF 1.12 as well.
> feat(provider/cf): caching agent backwards compatibility to CAPI 2.94.0/3.29.0

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/RequestQueue.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueSpec.groovy
```
Most typically, core and maximum pool sizes are set only upon
construction, but they may also be changed dynamically using
setCorePoolSize(int) and setMaximumPoolSize(int).
If the new value is smaller than the current value, excess existing
threads will be terminated when they next become idle. If larger, new
threads will, if needed, be started to execute any queued tasks.
```
^^ from JDK documentation
> feat(web): Allow for request queue size to be overridden dynamically

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gcs/GcsArtifactCredentials.java
We were finding the index in one string, and taking a substring in another
> fix(artifacts/gcs): fix version resolution

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/view/AppengineInstanceProvider.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonInstanceProvider.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/view/AzureInstanceProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ContainerLog.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/InstanceProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopInstanceProvider.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/provider/view/DcosInstanceProvider.groovy
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/view/EcsInstanceProvider.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesV1InstanceProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProvider.java
- clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/view/OpenstackInstanceProvider.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/provider/view/OracleInstanceProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusInstanceProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/InstanceController.groovy
Closes [issue #3360](https://github.com/spinnaker/spinnaker/issues/3360)
Updates `{account}/{region}/{id}/console` endpoint to return list of container logs for Kubernetes v1 and v2 providers rather than a string concatenation of each container log.
cc @danielpeach @lwander
> feat(provider/kubernetes): split kubernetes pod logs by container #3360

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy
Some existing code is using an auto-generated constructor for KubernetesImageDescription, which is fragile as added fields can change the meaning of the constructor. Add a Builder annotation so this code can use the more robust builder pattern.
> feat(provider/kubernetes): Add Builder to KubernetesImageDescription

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/SearchQueryCommand.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/executor/SearchExecutor.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/executor/SearchExecutorConfig.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/executor/SearchExecutorConfigProperties.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SearchController.groovy
Previously the search providers ran sequentially. If one provider
took far too long, the upstream service would disconnect before
any results were returned from the other providers. This adds a
circuitbreaker to cap the seach processing time and parallelize
the providers so that one provider's failure won't affect other
providers' results. The new circuitbreaker is configurable; by
default the previous behavior is preserved.
> feat(search): Adds parallell executor to search providers.

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactClient.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactCredentials.java
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/config/OracleConfigurationProperties.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/security/OracleCredentialsInitializer.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/security/OracleNamedAccountCredentials.groovy
Allow oracle provider and oracle artifact to use private key file with passphrase.
Related halyard PR is https://github.com/spinnaker/halyard/pull/1070.
> fix(provider/oracle): add private key passphrase

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAmiTagsAtomicOperation.groovy
This reverts commit 8d2df55250f31ccaa1ca4b8269bebf2a1de526c8.
Unfortunately, this didn't really move the needle in the direction I was anticipating.
> fix(aws): Revert "Use Edda during upsert AMI tags operations (#3034)"

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/converters/DeployAppengineAtomicOperationConverter.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/DeployAppengineDescriptionValidator.groovy
Allow artifacts to be used as config files when deploying to AppEngine. The artifacts are downloaded and supplied to the `gcloud app deploy` command alongside any other config files specified as file paths or provided as text. Accompanying changes in Orca, Gate, and Deck incoming.
Contributes to https://github.com/spinnaker/spinnaker/issues/3476
> feat(provider/appengine): config files from artifacts

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/converters/ResizeServiceAtomicOperationConverter.java
Fixes https://github.com/spinnaker/spinnaker/issues/2746
This is a good candidate for cherry-picking into 1.10.x
Rename ResizeServiceAtomicOperationConverter component name so it doesn't conflict with resizeServerGroup atomic operation
As best I can tell, this is a fun Spring config problem.  Because the atomic operation name is "resizeServerGroup" and the ECS component name is also "resizeServerGroup", the application context starts always returning the ECS component, instead of the right resize converter for the given cloud provider.
https://github.com/spinnaker/clouddriver/blob/29c5c1435ab0c750c4b491208f600647a3e98901/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/ApplicationContextAtomicOperationsRegistry.groovy#L36
> fix(provider/ecs): Rename ResizeServiceAtomicOperationConverter component

- clouddriver-openstack/src/main/java/org/openstack4j/model/image/v2/Image.java
- clouddriver-openstack/src/main/java/org/openstack4j/openstack/image/v2/domain/GlanceImage.java
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackImageV2ClientProviderSpec.groovy
A [bug fix in the openstack4j library](https://github.com/ContainX/openstack4j/commit/bb78146aa914b855c2d77e2b4d42e455190fb8eb) has not been added to a release
yet. This bug prevents Spinnaker from caching openstack images when their location is populated.
Until openstack4j makes a new release, we need to vendor the fix within clouddriver.
We've been running with this patch in Production for several weeks now at Target.
> fix(provider/openstack): Vendor upstream opstack4j fixes.

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java
We need to get better at cleaning up entity tags but I've spot checked
a couple of large applications and the load time is reasonable.
> fix(web): Increase default page size for entity tags from 2000 -> 5000

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/ResizeAsgDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/TerminateInstanceAndDecrementAsgDescription.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidator.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidatorSpec.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/AbstractDcosServerGroupDescription.groovy
- clouddriver-dcos/src/main/groovy/com/netflix/spinnaker/clouddriver/dcos/deploy/description/servergroup/DeployDcosServerGroupDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BasicGoogleDeployDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/EnableDisableGoogleServerGroupDescription.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/description/BasicOracleDeployDescription.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/description/CreateLoadBalancerDescription.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/description/DeleteLoadBalancerDescription.java
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/description/EnableDisableOracleServerGroupDescription.groovy
- clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/op/AbstractEnableDisableAtomicOperation.groovy
- clouddriver-oracle/src/test/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/op/DisableOracleServerGroupAtomicOperationSpec.groovy
- clouddriver-oracle/src/test/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/op/EnableOracleServerGroupAtomicOperationSpec.groovy
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/ApplicationNameable.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/ResourcesNameable.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/ServerGroupNameable.java
Allow an implementation of `ApplicationNameable` to support authorization
checks against _multiple_ applications.
This handles scenarios where a particular operation may target multiple
server groups that may or may not exist in the same application.
> feat(security): Support multiple applications in `ApplicationNameable`

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy
This populates loadBalancerNameToAttributes when edda is not enabled
> fix(provider/aws): populate loadbalancer attributes

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleInternalLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleNetworkLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleSslLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleTcpLoadBalancer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy
Quote from one of commit message : 
```
fix(provider/google): Do not add duplicate instance healths (NLB)  …
Changes:
- Skip health status for a different address
- Only add one health resolution per load balancer, by using a set
- Revert the de-duplication workaround in bc4ed8f
A NLB setup involves a target pool, along with:
- X addresses
- Y forwarding rules ("load balancers") per address
- Z instances
There are X * Y load balancers. Before this change, within each load
balancer, there would be X * Z * Z instance healths, when it should
be just Z.
With 8 addresses, 3 forwarding rules per address, and 60 instances,
there would be 8 * 3 * 8 * 60 * 60 = 691200 instance healths. G1GC, on
a powerful machine with a 32GB heap, will not be able to keep up with
such load, and will repeatedly …
```
> Fix duplication instance health (NLB) [GCP]

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidator.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizerSpec.groovy
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/ResourcesNameable.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/ServerGroupNameable.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsControllerSpec.groovy
Ported the `authorize()` method from `DescriptionValidator` and added
a metric in the event that a description presents an account _but_ no
application(s).
This metric will emit some false positives but still prove useful in the
short-term to highlight descriptions that might not implement
`ApplicationNameable` (or not implement it properly).
The previous behavior expected a `Description` to implement
`DescriptionValidator` in order to have authorization applied, however
this is not a requirement and missed some legitimate scenarios.
> feat(core): General purpose `DescriptionAuthorizer`

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/description/EnableDisableDescriptionTrait.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/AbstractRegionAsgInstanceIdsDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DestroyTitusServerGroupDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DetachTitusInstancesDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/ResizeTitusServerGroupDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.groovy
The majority of Titus operations were not implementing one of:
- `ApplicationNameable`
- `ServerGroupNameable`
- `ResourcesNameable`
In these cases, there was no check being performed that a particular
operation had access to the application owning the particular resource
being modified.
> fix(titus): Ensure that Titus operations enforce WRITE access to applications

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/RebootInstancesAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AllowLaunchDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/InstanceTargetGroupRegistrationDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/RebootInstancesDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmiTagsDescription.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/AccountNameable.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/UpsertTitusScalingPolicyAtomicOperationConverter.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DeregisterTitusInstanceFromLoadBalancerDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/ModifyTitusAsgLaunchConfigurationDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/UpsertTitusScalingPolicyDescription.groovy
A few `Description` classes legitimately do not need to be further
restricted by application.
Some `Description` classes need to determine applications by
fetching cached data (or looking directly at a cloud provider).
> fix(security): Override `requiresApplicationRestriction` as needed

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/RebootInstancesAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/TerminateInstancesAtomicOperationConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/RebootInstancesDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/TerminateInstancesDescription.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/TerminateTitusInstancesAtomicOperationConverter.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TerminateTitusInstancesDescription.groovy
This PR will lookup previously cached AWS/Titus instances to determine
their owning application.
> fix(security): Correctly determine application when terminating instances

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TerminateTitusInstancesDescription.groovy
Suppress an unnecessary `WARN` when a terminate description does not
specify any `instanceIds`.
(noticed this internally)
> fix(security): Handle empty `TerminateTitusInstancesDescription`

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
`/search?type=instances&cloudProvider=aws` is a surefire way to
unhappiness.
Looking through our logs, I do not see any legitimate searches w/o
a query string.
> fix(cats): Avoid searching without query string

- clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/batch/GoogleBatchRequest.java
We currently send GCE batch requests to a thread pool for execution but don't wait for execution to finish. This leads to race conditions where cache refresh requests can return success before the cache is actually updated.
> fix(provider/gce): Wait for batch requests to finish before returning

- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/PassThroughOperationPoller.java
Added test for CF server group deploy operation execution.
Introduced PassThroughOperationPoller to execute logic without polling in tests.
Also added an attribute to the converter test.
> test(provider/cf): added test for deploy operation

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BaseGoogleInstanceDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleDisk.groovy
This solves an issue where deleting MIGs with multiple disks would not delete the additional disks, leaving them orphaned.
> fix(provider/gce): Set device name on attached disks.

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateApplication.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java
“buildpack” will continue to work, but it is deprecated. So we should use “buildpacks” when available
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html
fixes pivotal-cf/cf-spinnaker-clouddriver#247
> feat(provider/cf): prefer "buildpacks" manifest attribute

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/TerminateGoogleInstancesDescription.groovy
@ttomsu 
Not sure if this is right or not, however this fixes google_kato_test terminate_instances.
Since https://github.com/spinnaker/clouddriver/commit/85a4901008322c9fba47065437b056d8cee2b0d2 the test was failing from a null pointer error. Note that test is deleting instances that are not bound to a server group.
It could be the bug is somewhere in the interface assuming that in fact there is a server group (i.e. server group is optional for this operation). I am not familiar with the semantics or implications here so am speculating with this and counting on your review.
See out of band email for more information about the failure details.
> fix(gce): TerminateGoogleInstancesDescription is not ServerGroupNameable

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
The implementation of manifest parsing had previously assumed a list of single-entry hashmaps instead of a single hashmap.
- spinnaker/spinnaker#3609
> fix(provider/cf): correct manifest for env vars

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtils.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtilsTest.java
Pagination logic was not iterating over the last page when retrieving results.
spinnaker/spinnaker#3625
> fix(provider/cf): correct pagination logic when iterating over multiple pages

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/Process.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/UpdateProcess.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
Also changed the handling of a crashed instance to be down rather than out of service.
> feat(provider/cf): display cf health check details for app

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
Fix for an edge case where a server group in CF could return a 404 when trying to retrieve the process stats. When no process stats are found we should consider the status to be `DOWN` so that the app can be deleted otherwise the app will fail to be deleted.
spinnaker/spinnaker#3653
> fix(provider/cf): set the status to DOWN when no process stats returned

- cats/cats-core/cats-core.gradle
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/CacheResult.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/CachingAgent.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/DefaultCacheResult.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/AgentIntrospection.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/CacheIntrospectionStore.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/DefaultAgentIntrospection.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/DefaultCacheData.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy
Now by default, all recent caching agent run are displayed per-node
under `/cache/introspection`. Providers (shown in k8s v2 here) can
supply additional details such as namespaces & kinds cached, time spent
in kubectl, etc...
https://github.com/spinnaker/spinnaker/issues/3668
> chore(cache): adds introspection to caching agents

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtils.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtilsTest.java
Fix issue when collecting results from a single page and add a test for the scenario of a single page of results.
spinnaker/spinnaker#3662
> fix(provider/cf): correct pagination logic when iterating

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/ScaleCloudFoundryServerGroupDescription.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperation.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperationTest.java
Now CF uses the Capacity struct in clouddriver to handle the case of
scaling-down ASGs to 0 instances.
spinnaker/spinnaker#3670
Co-Authored-By: Joris Melchior <joris.melchior@gmail.com>
> fix(provider/cf): Rectify scaling ASGs

- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/AgentIntrospection.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CacheController.groovy
This makes the results a lot easier to read, as agents that are executed infrequently/on different nodes get pushed to the bottom
> fix(cache/introspection): sort by descending execution

- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
- cats/cats-test/src/main/groovy/com/netflix/spinnaker/cats/cache/CacheSpec.groovy
The RedisCache implementation indexes entities and stores
their attributes and relationships in distinct keys, updated
non-atomically. Enforcing that entities are not returned
with null attributes assists with data consistency in the
redis implementation.
This PR moves the test for this behavior to RedisCacheSpec so
that atomic implementations can support key storage without
attributes for relationship resolution or other use cases.
> chore(cats): update test for future logic change

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesCronJobHandler.java
Currently Kubernetes only reports if a job scheduled by a cronjob has
completed without a success status. By checking if a job was running we
were only preventing potentially functioning cronjob specs from becoming
"stable", without correctly filtering out "unstable" cronjobs.
> fix(provider/kubernetes): fix v2 cronjob status

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/utils/AwsLookupUtil.groovy
Improve lookup of titus security groups from aws by not loading the entire security group object when not needed
> fix(provider/titus): improve lookup of security group details

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AwsSdkClientSupplier.java
This is to have less coupling to constants in the aws sdk.
Clouddriver will support new regions without updating the aws sdk.
https://github.com/aws/aws-sdk-java/pull/1839
> fix(aws/region support): Use RegionUtils instead of Regions

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy
Building on @njflowers's work in https://github.com/spinnaker/clouddriver/pull/3036 to specify the correct port in calls to DescribeTargetHealth for Fargate tasks
Fixes spinnaker/spinnaker#3458
> fix(provider/ecs): Include port in Fargate health checks

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2AbstractManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Been meaning to submit this for us to try out:
This is in service of faster pipeline executions, which ignore force
cache refreshes, and only serve manifest status from live calls.
Need to find a cleaner top-level way to distinguish between object
providers that query the cache vs. live data.
Important to note: this leaves caching (& the clusters tab) intact for
now, those can be disabled separately in a future PR.
> feat(provider/kubernetes): 'liveManifestCall' mode

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/UpsertEntityTagsAtomicOperation.java
- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/admin/EntityTagsAdminController.java
Dry run (default):
```
curl -X POST 'https://localhost:8081/admin/tags/deleteByNamespace/{namespace}'
```
Remove from elasticsearch only:
```
curl -X POST 'https://localhost:8081/admin/tags/deleteByNamespace/{namespace}?dryRun=false'
```
Remove from elasticsearch and front50:
```
curl -X POST 'https://localhost:8081/admin/tags/deleteByNamespace/{namespace}?dryRun=false&deleteFromSource=true'
```
> feat(entitytags): a simple `deleteByNamespace` admin api

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
This cuts down on the time spent looking up a resource in the wrong account
> perf(provider/kubernetes): ignore ondemand requests for other accounts

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/EcsServerGroupNameResolver.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/EcsServerGroupNameResolverSpec.groovy
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
This makes it slightly easier to implement https://github.com/spinnaker/spinnaker/issues/3733, by standardizing on the same logic that determines the 'next' and 'current' server groups.
This does change the format of the server group names, from basename-v0001 to basename-v001.  It's not a breaking change because the sequence number parses the same in both formats.
> feat(ecs): Migrate to standard server group name resolver

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
Fixes https://github.com/spinnaker/spinnaker/issues/3749
@clareliguori
> fix(provider/ecs): check for null service before getTaskDefinition

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
By returning `null` we were deleting valid (but stale) cache entries
instead of forcing the caching agent to retry later.
> fix(provider/kubernetes): bail out of caching on error

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/CustomKubernetesCachingAgentFactory.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNamespaceCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CustomKubernetesHandlerFactory.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
This property is configurable on each k8s v2 account, e.g.
```yaml
kubernetes:
accounts:
- name: k8s-v2
providerVersion: v2
cacheIntervalSeconds: 60
```
> feat(provider/kubernetes): allow v2 to set a cacheIntervalSeconds

- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
- clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy
Should fix #3772
Depending on the structure of the service URIs, there may be no Service in
the Authentication (see https://tools.ietf.org/html/rfc6750#section-3).
This is actually true for OpenShift OKR structure.
As such, ignore missing `service` and ensure that it gets ignored later on
as query parameter.
> fix(provider/docker): No longer depend on service in authentication

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/AgentSchedulerConfig.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/DynomiteCacheConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/JedisCacheConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfig.groovy
Some spring config refactoring, this allows us to have different backends for the cache scheduler and cache. While the SQL backend does support a SQL-based scheduler, it's not nearly as resource efficient as the Redis schedulers.
> chore(core): Decouple scheduler backend from cache backend

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
There is a race condition on startup where it is possible that a CRD is first encountered during a deployment, before a the CRD supplier (called in the code change) can register the CRDs with the correct flags. This prevents Spinnaker from correctly looking up which deployment handler to use, which is important for any kind that has custom logic during deployment (e.g. the `ReplicaSet` handler declares how images are substituted).
There is an outstanding issue (which I haven't been able to reproduce/encounter) where a similar bug manifests itself after clouddriver has been running for a while. This bug isn't fixed here, but the overall prevalence of this bug (esp when clouddriver pods are restarted/rescheduled) should be reduced.
> fix(provider/kubernetes): ensure crds are registered before using creds

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProviderConfig.groovy
This thing makes things more better when you disable Redis... such as not breaking all REST endpoints.
> fix(*): Consolidate default ObjectMapper mutations

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestLabeler.java
Remember, as with other app-level labels this can be disabled by setting
`kubernetes.v2.applyAppLabels: false`
This is required to identify pods uniquely by deployed version for
grouping into Istio subsets
> feat(provider/kubernetes): apply sequence label

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoHealingPolicy.groovy
Previously when querying for a health check, we returned the first health check found by name when querying the following kinds in order: healthCheck --> httpHealthCheck --> httpsHealthCheck. However, it is possible to have up to three health checks with the same name (one of each kind), so we should specify `healthCheckKind` and only query for the specified kind, leaving the default querying logic in place if `healthCheckKind` is unspecified.
> fix(google): differentiate among autohealing health check kinds

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/DualTaskRepositoryConfiguration.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DualTaskRepository.java
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/DualTaskRepositorySpec.groovy
Simple little class to migrate task backends without interruption. 
I opted for not doing any special logic treatment around `clientRequestId`. I think this behavior will be fine?
> feat(core): Add DualTaskRepository

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java
As noted in comments on this issue (https://github.com/spinnaker/spinnaker/issues/3490), image names were not being resolved for Kubernetes v2 clusters. `KubernetesV2ServerGroup` was missing a `getImagesSummary` method, and the `ProjectClustersService.ApplicationClusterModel` was assuming only one image per cluster.
Before:
After:
> fix(kubernetes): fix image resolution for project clusters view

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
Now all caching entries start with:
```
$account/$agentClass[$index/$threads]: ...
```
closes https://github.com/spinnaker/spinnaker/issues/3877
> chore(provider/kubernetes): add agent type to caching logs

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
Defaults to `false` to avoid an AWS permission error when your
clouddriver instance profile has minimal grants.
> fix(aws): Support disabling cloud formation via `aws.features.cloudFormation`

- clouddriver-google-common/clouddriver-google-common.gradle
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutor.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/GoogleExecutorTraits.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/batch/GoogleBatchRequest.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleImageCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleNetworkLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleRegionalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSslLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleTcpLoadBalancerCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/util/PaginatedRequest.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializer.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleImageTagsAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleCredentialsInitializerSpec.groovy
Looks like the intent of this package was to contain utilities useful across google providers (appengine/gce) but there's some GCE-specific logic in there that would be better to have in the GCE provider itself.  This also allows us to remove a dependency on the compute API from this common package.
>  refactor(google): Clean up clouddriver-google-common dependencies

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/CloudFormationController.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/Keys.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonCloudFormationStack.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/CloudFormationProvider.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/CloudFormationStack.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationCachingAgent.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonCloudFormationProvider.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/CloudFormationControllerSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonCloudFormationStackSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationCachingAgentSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonCloudFormationProviderSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/provider/agent/Namespace.groovy
This patch renames the cloud formation model to CloudFormationStack to better reflect its meaning. This change also uses the aws account name instead of the account id on the controller and cloud formation caching agent as suggested in https://github.com/spinnaker/clouddriver/pull/3320#issuecomment-458314739. It also makes the cloud formation caching agent resilient to permission errors, so it doesn't fail if the role assumed by spinnaker cannot list cloud formation stacks.
> refactor(cloudformation): rename cf model and use accountName instead of accountId

- build.gradle
Cherry-pick an update to spinnaker-dependencies into 1.12 to roll back the fabric8 library update, which was causing issues due to a breaking change in the library.
> chore(dependencies): Bump spinnaker-dependencies

- clouddriver-google/clouddriver-google.gradle
The clouddriver-google module doesn't actually need the whole 'google' group (which includes storage); it only needs the compute API.
> refactor(google): Clean up clouddriver-google dependencies

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/EntityTags.groovy
- clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
Specifically situations where a tag identifies itself as an object but
is actually a `String`.
> fix(entitytags): Handle non-deserializable entity tags

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AssumeRoleAmazonCredentials.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixSTSAssumeRoleSessionCredentialsProvider.java
Issue link: https://github.com/spinnaker/spinnaker/issues/3941
As detailed in https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.html, STS has special endpoints for GovCloud and China regions.
At credential creation time, we don't have a way to easily check what region we are in, so I have it relying on the `arn` string being passed in. Clouddriver allows for a full arn, so we can check it for `aws-us-gov` or `aws-cn`.
I will also update the documentation as to point it passing in a full ARN is allowed.
> fix(provider/aws): change STS endpoints for GovCloud and China regions

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperation.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeploymentResult.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperationUnitSpec.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DeploymentResultSpec.groovy
AWS deployments are somewhat special in that they create an initial
asg of size 0/0/0 and then subsequently resize it to the target
capacity.
This causes problems if the `ForceCacheRefresh` task as part of a deploy
were to ever be removed from `orca` as it's possible for the 0/0/0 asg
to be cached and the `WaitForUpInstances` task to prematurely complete.
I'd like to remove the `ForceCacheRefresh` task as part of a deploy,
hence this PR and a follow-up in `orca` that makes it aware of the
capacity being passed back from `clouddriver`.
> feat(core): `DeploymentResult` support for returning target capacity

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverter.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServiceDescription.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DestroyCloudFoundryServiceDescription.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperation.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DestroyCloudFoundryServiceAtomicOperation.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServiceInstance.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperationTest.java
renaming `serviceName` to `serviceInstanceName` so it is clear that `serviceInstanceName` represents the new service instance and not the name of the Service
> chore(cf): rename serviceName to serviceInstanceName

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/snapshot/RestoreSnapshotAtomicOperation.groovy
The new JobExecutorLocal is in Java, and fails when passed an array containing a mixture of Strings and GStrings.  As a GString is not a subclass of String (which is final) it is incorrect to create a collection containing a mixture (and generates a warning). Fix this at the source by not creating arrays that mix String and Gstring.
> fix(appengine): Fix appengine deployments

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/templates/AzureServerGroupResourceTemplateSpec.groovy
Currently Azure Application Gateway is already playing the role of Spinnaker Load Balancer, so it means the App Gateway can directly point to Server Groups (Azure VM Scale Set). While currently within the VMSS there is still Azure Load Balancer created, which we believe is redundant so we remove it.
> fix(provider/azure): Remove Azure Load Balancer from Azure VM Scale Set

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesIngressHandler.java
The http field is optional on v1beta1.IngressRule, but the caching logic currently throws an NPE when this is the case.
> fix(provider/kubernetes): Fix NPE on ingress with no http

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/front50/Front50ArtifactCredentials.java
We need to mark front50Service and objectMapper JsonIgnore so we don't try to serialize them when returning the accounts via /artifacts/credentials.
> fix(artifacts/front50): Fix serialization of artifacts

- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy
- with a relational cache provider, storing instance -> health relationships (as is already done by other HealthProvidingCachingAgent's) allows loading serverGroups with instance and health data without having to predetermine instance or health keys.
> feat(eureka): store instance to eureka health relationships

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactCredentials.java
- clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/github/GithubArtifactCredentialsTest.java
GithubArtifactCredentials is storing a Request.Builder in an instance variable. This means that when multiple threads are concurrently downloading Github artifacts, it's possible for one thread to download an artifact from another thread's URL.
>  fix(artifacts/github): Fix threading bug in github artifact resolver

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactCredentialsRepository.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactDownloader.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/embedded/EmbeddedArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/front50/Front50ArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gcs/GcsArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitlab/GitlabArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/HelmArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/http/HttpArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ivy/IvyArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/config/ArtifactConfiguration.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java
Each artifact type creates its own okHttpClient; just create a single one that is autowired into each.
Instead of having the individual types depend on the repository and modify it, have the repository depend on the individual artifact types. It can then just create a list from these injected types.
Improve the interface of artifactCredentialsRepository. Most calls to getAllCredentials filter based on name and/or type; add this filtering as a supported function in the interface and clean up the calling code.
> refactor(artifacts): Clean up Spring dependency injection

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
Avoids a bad path where cats tries to optimize the search q by looking for things in the filters. If filters are empty this always short-circuits and returns an empty result list.
> fix(search/cats): Avoid short-circuiting when filters are empty.

- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/client/OpenstackIdentityV3ProviderSpec.groovy
- clouddriver-openstack/src/test/groovy/com/netflix/spinnaker/clouddriver/openstack/security/OpenstackNamedAccountCredentialsSpec.groovy
The openstack unit tests fail when run locally using gradle; the root cause is that the tests are not independent, as there is a test that does metaprogramming to change the behavior of a class.
> fix(openstack): Fix openstack unit tests

- clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy
The elasticsearch tests spin up a new local node agains which to run the tests; this node defaults to port 9200, but will pick another port if that port is not available. The tests currently always send requests to port 9200 (which could be an unrelated node); update them to send requests to the node created by the tests.
> fix(elasticsearch): Fix connection string for elasticsearch tests

- cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisNamedCacheFactorySpec.groovy
- clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/RedisTaskRepositorySpec.groovy
These tests are leaking a total of three embedded redis instances, which build up over time on a machine used to run the tests frequently.
> fix(redis): Clean up embedded redis in tests

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServiceBrokerController.java
Clouddriver no longer starts unless cloudfoundry is enabled as a core module added a dependency on a cloud-foundry-specific bean.
> fix(core): Fix clouddriver startup

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ApplicationsController.groovy
- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/MainSpec.groovy
It's very common for one of our microservices to fail to start because of a missing autowire dependency. Often this is because someone changes autowiring such that it only works with a particular feature enabled, but fails with it disabled.
To prevent these issues, add an extremely simple integration test that just checks that clouddriver starts up with the default spring profile. This won't catch everything, but should catch most of the common cases I've seen. (We can always add test for other common profiles later if desired.)
> test(core): Simple startup integration test

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
Search is currently broken for the Google provider because it does not implement a key parser, and the search logic returns and empty list for any provider that does not.
Closes spinnaker/spinnaker#4050
> fix(google): Fix search for Google provider

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureAtomicOperationConverterHelper.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/model/AzureSecurityGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/UpsertAzureSecurityGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureSecurityGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/deploy/templates/AzureSecurityGroupResourceTemplateSpec.groovy
Azure network security group (NSG) needs to be applied to subnets within a virtual network or to Network Interface Controller (NIC) of VMs, otherwise it won't take effects.
ARM nested template is used here to implement above, which serves defining the template of binding the NSG to an existing subnet.
> feat(provider/azure): Apply network security group to a custom subnet

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AbstractAppengineCachingAgent.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineCredentialsInitializer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineNamedAccountCredentials.groovy
Allows a user to configure Spinnaker to hit the AppEngine Admin API less often, thereby reducing the risk of hitting quotas.
See halyard PR where the flag to configure this is exposed: https://github.com/spinnaker/halyard/pull/1235
> feat(appengine): add configurable caching agent interval

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/model/AzureSecurityGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureSecurityGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/deploy/templates/AzureSecurityGroupResourceTemplateSpec.groovy
Add the source IP/CIDR filtering to Azure Network Security Group (NSG) that plays the role of Spinnaker firewall. There is a feature link PR on Deck: https://github.com/spinnaker/deck/pull/6657
> chore(provider/azure): Enable NSG source IP/CIDR filtering

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/description/DeployAppengineDescription.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
There are some specific use cases that require an appengine version's URL remain completely stable between deployments. Spinnaker normally adds sequence strings to names, which changes the URL that appengine exposes with each deployment. This fixes that.
> fix(appengine): Allow suppression of sequence in deployed servergroup names

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEServerGroupNameResolver.groovy
IntstanceProperties subclasses Map, which Groovy interpolates as a LinkedHashMap when you chain calls and don't provide specific concrete types. When a key (e.g. 'labels') is missing in the interpolated LinkedHashMap, Groovy can't synthesize a getter and fails with a missing method exception.
> fix(provider/gce): Use a concrete type for InstanceProperties.

- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
There are currently no tests validating the logic for determining valid kinds (via kinds, omitKinds, and checking what is readable); add some.
> test(provider/kubernetes): Add tests to valid kind checking

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
Background:
Currently it throws exception "Async operation failed with provisioning state: Failed" after clicked update button for editing load balancer.
Fix:
After investigated, the root cause is the 'vnetResourceGroup' field in tags to be passed to azure is null while updating. So bind the vnetResourceGroup value before pass to azure. After tested, it edits load balancer successfully.
> fix(provider/azure): Failed to edit load balancer

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
If a deployment reports its "Available" deployment condition as false, we currently mark the manifest as unavailable but don't mark it as unstable, which means that downstream stages will continue before it stabilizes.
In most cases the logic below for comparing replica sets will end up marking the deployment as unstable as well as unavailable, but there are edge cases were Kubernetes (correctly) marks the deployment as unavailable but the Spinnaker logic does not.
One example is if the new replicas have not been created yet (such as if we poll quickly). In that case the replica counts will all match in the below logic and we'll mark the deployment stable.
It might make sense to just remove the logic below as it just duplicates what Kubernetes is doing to determine the status (though as …
> fix(provider/kubernetes): Properly set unstable flag for deployment

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiGroup.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
* fix(kubernetes): Infer API version when missing on patch manifest 
The patch manifest stage is currently failing, because we're fetching the apiGroup as a required field. If there is no apiGroup specified, we should try to match the supplied kind against native groups.
* refactor(kubernetes): Add optional apiGroup to KubernetesKind 
As I was working on the last commit, I found it a bit confusing knowing whether a given 'kind' string I was dealing with was a fully-qualified kind (with API group) or just the kind string.
To make this less ambiguous, include 'apiGroup' as a field on the KubernetesKind object, and handle scoping as part of toString and fromString so this happens in one place.
This adds the default api group for built-in kinds, but explicitly considers two built-in kinds as …
> fix(kubernetes): Infer API version when missing on patch manifest

- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/Cache.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/CompositeCache.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/UnsupportedCacheMethodException.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/mem/InMemoryCache.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/EddaLoadBalancerCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/LaunchConfigCachingAgent.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy
The upcoming sql backed cache implementation adds support for indexing
and retrieving resources by application. This can provide significant
performance improvements for Spinnaker's application clusters view when
application contain >thousands of instances and associated health
objects.
The new CacheData.attributes.application value is used by SqlCache for
this purpose. This PR selectively implements this in several of the AWS
caching agents. AmazonClusterProvider will take advantage when serving
/applications/{application}/serverGroups requests when the SqlCache
implementation is in use.
> feat(cats): initial support for indexing resource by application

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/UpsertAzureLoadBalancerAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/UpsertAzureSecurityGroupAtomicOperation.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
This PR is to partially revert a previous [PR](https://github.com/spinnaker/clouddriver/pull/3473) covering the logic of removing unnecessary info in the name of the resource deployment. While we find those removed info could be useful in tracking deployment, so I add it back.
> fix(provider/azure): re-add resource names to the deployment name

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/UpsertTitusScalingPolicyDescription.groovy
Apparently AWS will default this to "add", so we should probably set it to whatever the old value was.
> fix(titus): set adjustmentType when copying scaling policies on clone

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/UnmapLoadBalancersAtomicOperation.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/UnmapLoadBalancersAtomicOperationTest.java
Attempting to unmap a load balancer from a single server group would remove it universally.  It should be limited to a single version of an application.
spinnaker/spinnaker#4164
> fix(cf): Unmap LBs too aggressive

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/Keys.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProvider.groovy
Titus tasks (i.e. instances) show up in search results in an unclickable way right now because they're not hydrated. This hydrates them so we can show valid links in the UI
> fix(titus): fix and hydrate titus instance search results

- clouddriver-artifacts/clouddriver-artifacts.gradle
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentials.java
- clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentialsTest.java
* Using the highest level of abstraction in aether possible such that resolving and downloading a Maven artifact does not require any disk access (for local cache).
* This rewrite relaxes the constraint that Maven artifact accounts be pointed at virtual repositories containing resolvable references to parent POMs and dependency management sections required previously by virtue of the way Ivy resolves artifacts. The aether approach is to look exclusively at `maven-metadata.xml`, which does not contain such references.
* The rewrite was caused by a need for [revision placeholders](https://maven.apache.org/maven-ci-friendly.html), which Ivy's Maven resolver does not support.
In some ways this is a move back to an implementation closer to what was originally proposed for the JAR artifact …
> refactor(artifacts): Rewrite Maven artifact account with aether

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
This fixes writing onDemand cache records for ALB's as requested by Orca's `UpsertLoadBalancersStage`. Orca still needs logic to monitor onDemand processing however, without which these onDemand keys are no-ops.
> fix(aws): fix ALB onDemand caching

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesModelUtil.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesJobProvider.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/job/KubernetesRunJobOperationConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/job/KubernetesRunJobOperationDescription.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/model/KubernetesV2JobStatus.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
adds support for run job in kubernetes v2 provider. very similar to the
Deploy (Manifest) stage but only supports the Job kind. satisifies the
methods that are needed by the Run Job stage to start, monitor and
collect jobs.
> feat(kuberenetes): v2 run job stage

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/JobDescription.java
- Follow up to #3535 , Adding support for additional fields in JobDescription convert method
- fix a NPE when `selfManaged` description was passed
> fix(titus): Additional fields for job disruption budget

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/ApplicationService.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/Page.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/CloudFoundryServerGroupNameResolver.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
The previous criteria selected server groups lexicographically less than `clusterName-v9999`, but this  selected `clusterName-prod-v046` because `p` < `v`.
We're now doing `<clusterName-v9999` and `>=clusterName`, selecting more than one result, filtering on matching cluster names, and returning all the taken server groups in the cluster.
Additionally, now filtering on `space_guid`.
cc / @ciberkleid
> fix(cf): Fix server group name resolver

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
- clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy
Background:
Enable Azure Load Balancer which supports inbound NAT port-forwarding rules to connect to azure vm instances.
There is one another related PR (https://github.com/spinnaker/deck/pull/6829) in deck. Please also help to review.
>  fix(provider/azure): Enable Azure Load Balancer from Azure VM Scale Set

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeployManifestDescription.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestTraffic.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestAnnotatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
* refactor(provider/kubernetes): Improve some encapsulation 
KubernetesDeployManifestDescription is a Data class, so the member variables can be private.
KubernetesManifestTraffic is simple enough that using a builder is less clear; give it a single-arg constructor and remove setters.
Also lightly refactor KubernetesDeployManifestOperationSpec to make it easier to add tests in the next commit.
* feat(provider/kubernetes): Add traffic options to deploy description 
In order to support better first-class deployment strategies in the Kubernetes V2 provider, add functionality to the deploy manifest stage.  In particular:
* Allow the services to be specified on the deploy description, rather than only as an annotation on the manifest.
* Add a boolean to control whether to send traffic to the …
>  feat(provider/kubernetes): Add traffic options to deploy description

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/UpsertTitusScalingPolicyAtomicOperationConverter.groovy
Turns out that `applicationName` on a titus job is the container name.
For authorization purposes, we need to be looking at `appName`.
> fix(auth): s/applicationName/appName when determining application name

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
I was tired of seeing error messages like the following for a failed deploy stage.
“Exception ( Monitor Deploy ) Cloud Foundry API returned with error(s):”
It is missing anything useful, like the actual error info. That is because in some cases CloudFoundryApiException is only sent a throwable which is ignored even though it has useful information about the failure.
> fix(cf): cf exception should display message from throwable

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
- We use to copy the `migrationPolicy` from source even when it was not specified in the payload and `jobDisruptionBudget` was set as part of the payload, this fix it to ignore the source `migrationPolicy` when `jobDisruptioBuget` is set and copy only when its not specified.
> fix(titus): Don't copy migrationPolicy from source during job creation

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderConfig.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
There are currently two mechanisms for Spinnaker to cache CRDs:
* Registered CRDs that are included in clouddriver's config and can set CRD-specific properties (such as a handler class)
* Unregistered CRDs that are discovered at startup by asking the cluster for all CRDs. These use default properties that are not overriden.
We are currently polling for CRDs in the cluster and configuring all found CRDs as unregistered before we register configured CRDs. Registration of a CRD is a no-op if the CRD has already been registered, so this means the user-configured registered CRD properties are being ignored.
We should instead wait until we've registered all configured CRDs before having the caching agent try to auto-discover CRDs.
> fix(kubernetes): Initialize credentials after CRDs are registered

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BaseGoogleInstanceDescription.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CreateGoogleInstanceAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/ModifyGoogleServerGroupInstanceTemplateAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/snapshot/SaveSnapshotAtomicOperation.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/CopyLastGoogleServerGroupAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SerializeApplicationAtomicOperationUnitSpec.groovy
Shielded VMs are virtual machines (VMs) on Google Cloud Platform hardened by a set of security controls that help defend against rootkits and bootkits. Using Shielded VMs helps protect enterprise workloads from threats like remote attacks, privilege escalation, and malicious insiders. Shielded VMs leverage advanced platform security capabilities such as secure and measured boot, a virtual trusted platform module (vTPM), UEFI firmware, and integrity monitoring. Please see more details and screenshots using the link below.
https://github.com/spinnaker/spinnaker/issues/4281
> feat(provider/google): Support Shielded VM policies

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstanceSpec.groovy
Context : For titus instance we currently have only `containerIp` and this means we have to use something like this for links in application config `https://{{containerIp}}:port/link`. 
This change introduces the `privateIpAddress` field to titus instance so that there can be parity with AWS provider type applications and titus and we can use `https://{{privateIpAddress}}:port/link` across the board
> fix(titus): Map titus containerIp to privateIpAddress

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentials.java
- clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentialsTest.java
In order to fetch a maven artifact with coordinates `com.example:example-app:0.0.1-build.10` the version resolving logic should not fetch the metadata by version instead it should fetch the metadata for the artifact and the resolve the version released version from the `maven-metadata.xml`.
```
2019-04-17 02:55:30.974 ERROR 1 --- [ool-4-thread-10] c.n.s.c.o.DefaultOrchestrationProcessor  : java.lang.IllegalStateException: Unable to download artifact with reference 'com.example:example-app:[com.example:example-app:0.0.1-build.17]'
at com.netflix.spinnaker.clouddriver.artifacts.maven.MavenArtifactCredentials.download(MavenArtifactCredentials.java:108)
at com.netflix.spinnaker.clouddriver.cloudfoundry.deploy.ops.DeployCloudFoundryServerGroupAtomicOperation.downloadPackageArtifact(DeployCloudF …
```
> fix(artifacts): Maven release artifact resolution by version results in 404

- clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/UpsertLambdaAliasAtomicOperation.java
The null pointer exception was because of the way below logic was implemented. I've cleaned it up and tested to see it works.
> fix(lambda): Current implementation of upsert lambda function does not work #4304

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperation.groovy
supports finding an already resolved image when the deploy was supplying AMI id rather than AMI name
> fix(aws/deploy): support image lookup when deploying by imageId rather than name

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleSecurityGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProvider.groovy
service accounts.
GCE firewalls can target network tags or service accounts. We were
incorrectly returning all firewalls targeting service accounts.
> fix(provider/google): Prevent returning all security groups targeting

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleSecurityGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleSecurityGroupSummary.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleZonalServerGroupCachingAgent.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProvider.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProviderSpec.groovy
This PR adds support for existing serviceAccount based firewall rules. 
For any rules that exist, the `application/appname/serverGroups` endpoint will now successfully return the service account of the instance that is running, in addition to the `/securityGroups` endpoint now properly returning firewall rules that DO NOT have tags (`targetTags` or `sourceTags`) but instead use serviceAccounts.
For example, if a firewall rule already exists using a service account, you will see the object in `/securityGroups`:
```
{
id: "host/sampleapp-internal-test",
moniker: {
app: "sampleapp",
cluster: "sampleapp-internal-test",
detail: "internal-test",
stack: "app"
},
name: "sampleapp-internal-test",
network: "host/host-network",
selfLink: "https://www.googleapis.com/compute/beta/projects/host/global/f …
```
> feat(provider/google): Support service account security groups

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/BuildEnvVar.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryBuildInfo.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
Every cloud provider will have a different way to put metadata on their server group. Here we use app environment variables because we don’t have resource tagging yet.
The builds are not cloud provider specific so it makes sense to have more consistency here. The CFBuildInfo could be more general purpose than just CF. It could be moved to the core model as part of a server group and a consistent way to represent ci build reference info. It is basic build metadata that is produced by Artifactory build info and relevant attributes to just about any CI system.
> feat(cf): add build info to server group

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
This is the beginning of some work to redo how logs are handled for Jobs
in the V2 provider. In order to implement the new approach we need to
prevent Jobs from being cleaned up by Spinnaker and defer to Kubernetes
to do that work. Versions >= 1.12 implement a `ttlSecondsAfterFinished`
field for Jobs that will tell Kubernetes to cleanup the Job after that
TTL has expired. We'll communicate this to customers via documentation.
> fix(runJob/kubernetes): defer cleanup to k8s

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/DisruptionBudget.java
This field is a marker, so it has no body (consistent with the gRPC model). 
I'm debating whether we should stay true to the gRPC model, or make it a boolean to avoid this weirdness. For now, I'd like to leave it as an empty Object, unless that's against any other conventions in our codebase.
I didn't catch this in my testing because I was hitting the serverGroups endpoint with the browser and getting XML instead of JSON.
> fix(titus): serialize empty RateUnlimited field in DisruptionBudget

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
removes logs from the job status (which gets stored in the execution
context) since the frontend has been moved to pull the live logs from
kubernetes (similar to how deploy manifest works).
> refactor(runJob/kubernetes): don't record logs

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsInitializer.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/securitygroup/UpsertKubernetesV1SecurityGroupAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesNamedAccountCredentialsInitializerSpec.groovy
The code to translate Kubernetes account properties into accounts uses multiple levels of `Builder` classes, each of which do a bit of defaulting/initialization.  This makes it difficult to understand where configured account properties are defaulted, and where they are actually used.
As a first pass to simplifying this, clean up the interface between `KubernetesNamedAccountInitializer` and `KubernetesNamedAccountCredentials`.  Remove the builder class and have defaulting either occur directly on the `KubernetesConfigurationProperties.ManagedAccount` class (for simple defaults) or in the constructor (for more complex cases that aren't just setting a single default value.)
* test(kubernetes): Add tests to credentials initializing 
There are currently no tests on initializing credentials; …
> refactor(kubernetes): Simplify account creation code

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
Background:
update the error message when it failed to destroy load balancer.
> fix(provider/azure): update the error message when it failed to destroy load balancer

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
Background:
It failed to destroy server group at "WaitForDestroyedServerGroup" task when there is only one server group.
Root cause:
"WaitForDestroyedServerGroup" task will check whether the target server group is removed from redis. However, the target server group isn't removed from redis so that the task failed. The root cause is that "loaddata" function in "AzureServerGroupCachingAgent" only cache the data according by the server group in Azure side. When the last one server group is deleted from Azure side, the "loaddata" function doesn't get the target server group and cache it to redis so that this server group in redis becomes dead data. So it's a bug.
Fix:
Update code to remove dead data in each refresh task.
> fix(provider/azure): fail to destroy server group when there is only one server group.

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesNamedAccountCredentialsInitializerSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
As a follow-up to #3630, do the same kind of simplification in `KubernetesV2Credentials`.  Now it should be much easier to see how each of the fields are defaulted, and to understand where they are used.
* refactor(kubernetes): Use a builder in KubernetesV2Credentials 
KubernetesV2Credentials implements its own builder that does a bit of defaulting; push this defaulting into the constructor and use a @Builder annotation to get a builder that does not do any defaulting itself.
* refactor(kubernetes): Pass ManagedAccount to constructor 
Rather than use a builder, we can just use the existing ManagedAccount object that we already have and pass it to the constructor for KubernetesV2Credentials.
* refactor(kubernetes): Move defaulting to ManagedAccount 
Some of the defaulting and null checks …
> refactor(kubernetes): Simplify v2 account creation code

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtilSpec.groovy
Before deploying a manifest, we check whether the namespace is one that the account is configured for. We do this by checking namespaces and omitNamespaces, but this fails in the case where an account is mis-configured and doesn't have any namespaces.
Instead, just use getDeclaredNamespaces which returns a fully resolved list of namespaces the account knows about (whether because of config or dynamically discovered).
Fixes spinnaker/spinnaker#4319
> fix(kubernetes): Fail validation if account has no namespaces

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
We pin our elasticsearch and jest libraries to versions much older than Spring pulls in. This is currently breaking the Elasticsearch health check, so disable it by exluding autoconf of ElasticSearchJestHealthIndicatorAutoConfiguration.
Given that we configure elasticsearch ourselves, we should also disable ElasticsearchAutoConfiguration and JestAutoConfiguration. These aren't currently broken, but they are liable to break given the huge version skew between what we have on the classpath and what Spring expects.
> fix(elasticsearch): Don't autoconfigure elasticsearch/jest

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
Background:
We cannot delete firewall associated with subnets.
Fix:
Remove links between firewall and subnet while deleting firewall.
> fix(provider/azure): delink associated firewall from subnet while deleting firewall

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Manifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2AbstractManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesPodMetric.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
Fixes spinnaker/spinnaker#4243
* test(kubernetes): Add tests to pod metrics caching 
* refactor(kubernetes): Improve typing of pod metrics 
The pod metrics code converts the metrics to Maps before using them, which makes it more difficult to use these metrics. Simplify this code by using the KubernetesPodMetric class that already exists.
In order to preserve the serialized version stored in the cache, rename some fields to match what we're currently using to serialize. Then serialize/deserialize to/from that object when we write/read from the cache.
* feat(kubernetes): Add metrics support to live manifest mode 
The live manifest supplier does not currently support returning metrics, so users with it enabled can't see metrics on the clusters tab. Add support for this.
>  feat(kubernetes): Add metrics support to live manifest mode

- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleImageTagsAtomicOperationUnitSpec.groovy
Some of the upgrades that came with boot2 made these tests have invalid syntax, so they were commented out to unblock the upgrade. Fixing the tests now here.
> test(gce): Fix GCE upsert image tags test

- clouddriver-web/clouddriver-web.gradle
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
In the Spring Boot 2 upgrade, spring.config.location overrides all other config locations. The equivalent property is now called spring.config.additional-location.
This fix allows the app the to run without additional config files.
> fix(core): Spring does not override default configuration files

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
CI build info can sit under here with the droplet build info. It isn’t ideal because it is not typed or shared more widely than CF, but it tags along for the ride everywhere that buildinfo goes.
> fix(cf): add ci build info under build info

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcrImageProvider.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/view/EcrImageProviderSpec.groovy
The current regex match does not catch names like the following:
* `111111111111.dkr.ecr.us-east-1.amazonaws.com/sub-org/my-app-image:v0.0.0`
> fix(ecs): allow sub-org ecr repos

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.groovy
60s is too aggressive; should be 600s
> fix(titus): set default disruption interval to 10m

- clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/MainSpec.java
It seems that the startup test is no longer running after then boot2 upgrade. I'm not sure that Spring Boot tests work well with spock; convert it to JUnit.
> test(*): Fix startup test

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineAtomicOperation.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineCredentialsInitializer.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/security/AppengineNamedAccountCredentials.groovy
Fixes spinnaker/spinnaker#3349
Clouddriver searches the the PATH for the gcloud executible; in some cases it is easier to provide a direct path to the executable than to fully control the environment of clouddriver.
(One example is running it on Ubuntu 18.04 on GCE; gcloud is installed in /snap/bin, which is added to the path for login shells but is not in the path for systemd.)
> fix(appengine): Allow gcloud path to be configured

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
because of the way `JobController` implements collecting jobs, returning
null is the way to signal that a job provider does not apply to a given
request. prior to this fix, jobs run with a v1 account would error out
because the job controller would attempt to gather the status of the job
against the incorrect job provider.
> fix(runJob): fix v1 job collection

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Compatibility with autobump.
Updates kork to 5.3.4
Updates spinnaker-gradle-plugin to 6.5.0
> chore(dependencies): externalize versions to gradle.properties

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeployManifestDescription.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
adds a `namespaceOverride` option to deployManifest which will set a
desired namespace on all manifests being deployed. this is the
equivilent of doing `kubectl apply --namespace {namespace}`. this
feature was primarily requested because it makes deploying stable helm
charts possible.
Closes spinnaker/spinnaker#2831
> feat(provider/kubernetes): namespace deployManifest

- clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverter.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
* Added support for ServiceManifest `parameters` field and UserProvidedServiceManifest `credentials` field to be deserialized from a JSON document, a YAML document or noop if already a Map.
* Removed the snakeyaml Gradle dependency as the jackson-dataformat-yaml already includes it.
> feat(cf): Improved flexibility of Map deserialization for Service manifest fields

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
Fixes spinnaker/spinnaker#3571
The error message when a required artifact is not bound in a Kubernetes deploy or patch stage is confusing. Make this clearer so that users get more actionable feedback when they misconfigure a stage.
> fix(kubernetes): Improve error message on unbound artifact

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentials.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
All artifacts don’t use the Artifact fields consistently. For example, the Jenkins artifact uses the build number in the version field. It then looks incorrect when it is later displayed as a version.
> fix(cf): only create artifact metadata for Maven artifacts

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
I've been doing some investigation of how to improve how we keep track of kinds (including CRDs) so that we can better scale to large numbers of accounts.  This PR is just a few small changes to `KubernetesKind` to make it more clear. 
* refactor(kubernetes): Consolidate constructors 
The multiple constructors in KubernetesKind with various parameters make it complex to understand which constructor is being called and what parameters are being defaulted.
Consolidate down to two constructors: one that defaults isDynamic and isRegistared and is used when we create all the static member instances, and another that accepts these parameters and is used for dynamic registration.
If we were creating a lot of these outside of the class it might make sense to use a builder, but given that this is …
> refactor(kubernetes): Consolidate constructors 

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Application.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Manifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2AbstractManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ApplicationProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesPodMetric.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/artifact/KubernetesCleanupArtifactsDescription.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/OperationResult.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProviderSpec.groovy
There are a few compiler warnings in clouddriver-kubernetes; fix these.
* Defaulting a field on a class that uses a `@Builder`, as `@Builder` ignores the default.  For these I either added `@Builder.Default` to tell the builder to use the default, or removed `@Builder` if it was not necessary (unused or for a simple class where all builders passed the same parameters).
* EqualsAndHashCode without calling the super class
* Passing an array instead of a list to a log call
Also, for some of the modified classes, took the opportunity to remove un-needed lombok annotations and clean up the interface (as well as make some fields final where possible).
> fix(kubernetes): Fix compiler warnings

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/model/KubernetesV2JobStatus.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
In order for the Deck to display logs in a reliable manner we need
access to any Pod names created by the Job. When collecting the status
of the Job, collect the names and statuses of any Pods owned by the Job.
When displaying logs, Deck will determine the Pod name use when fetching
console output.
> fix(runJob/kubernetes): collect pods and status

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryCachingAgent.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryCachingAgentTest.java
This will avoid exceptions this:
"Cannot compare java.lang.String with value '2019-05-22T03:51:57.222+0000' and java.lang.Long with value '1,558,496,930,016'"
That happen here:
https://github.com/spinnaker/orca/blob/fdc5f6a53affddc56051171accd97493fdc7b660/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy#L181
because cacheTime is expected to be a long.
> fix(cf): cacheTime should be stored as a long

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/ArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentials.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
Sometimes Artifacts don’t have the version populated. For example, a default Maven artifact in a pipeline may have a reference with a ‘latest.release’ suffix. This allows us a way to look up the actual version used. Name is often unpopulated along with version.
This also finds specific snapshot versions.
Artifact Url was purposefully left out of the CF server group env vars because we don’t actually have enough information to construct it and put it in artifact.location upstream.
> fix(artifacts): resolve version of artifacts

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/TaskState.java
These are reason codes that can happen, and we should not consider a job that ends with them successful.
> fix(titus): handle additional task states

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/RegionalOperation.java
I tested this locally with a ZonalOperation and fixed it there. I'm not
sure why it didn't occur to me to also make the same fix in
RegionalOperation.
> fix(gce): fix waiting on regional operations from the new MIG compute wrapper

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Job.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroup.groovy
- follow up to #3690, return `constraints` map as part for `TitusServerGroup` to keep it consistent.
> fix(titus): Return job constraints with serverGroup details

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
A previous refactor moved the field initialization in the getter to make it lazy but `getRegions()` wasn't using the getter.
> fix(cf): CloudFoundryCredentials#getRegions NPE on using an uninitialized field

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/HealthState.groovy
- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/model/EurekaInstance.groovy
- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy
- clouddriver-eureka/src/test/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgentSpec.groovy
This adds deterministic handling when we get multiple records for the
same instance id. Previously we would potentially generate two cache
data objects, however since they both had the same id only one would be
written (last wins style most likely).
This now prefers a record in a 'worse' state (based on ordering the
HealthState enum from worst to best) to ensure that an instance showing
as Down is not accidentally considered ready for traffic during a
deploy.
If all records agree on health state then takes the most recently
updated.
> fix(eureka): Handles duplicate eureka records

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
If kubectl throws an error, it will generaly return a nonzero status, an empty stdout, and the error in stderr. The streaming manifest parsing logic fails when the output stream is empty, so we're propagating the error parsing the empty input stream instead of the actual error message.
If the output of kubectl is empty, just return an empty list of manifests. The calling code will the properly look at the return code and stderr to determine whether the call succeeded and what message to show the user.
> fix(kubernetes): Properly handle empty kubectl input stream

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
* test(kubernetes): Add tests to getClusterRelationships 
Also simplify the logic in the invertRelationships test
* perf(kubernetes): Reduce memory allocation during caching cycles 
The caching logic for the kubernetes v2 provider allocates a lot of short-term memory during each caching cycle, putting pressure on the garbage collector, in some cases exceeding the garbage collection overhead.
A significant contributor is the logic to compute relationships between kubernetes objects. We currently create a CacheData object to hold each relationship and rely on downstream (and inefficient) logic to merge these into one CacheData per object, containing all of its relationships.
Improve this by having invertRelationships return one CacheData per object (containing all of its relationships) …
> perf(kubernetes): Reduce memory allocation during caching cycles

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KeysSpec.groovy
* test(kubernetes): Add tests to Keys 
An upcoming commit will make some performance improvements to the Keys.Kind and Keys.LogicalKind enums, so add some tests to these.
Also add some tests to validate the parsing of cache keys containing semicolons. This is currently broken, but add the test now validating the incorrect behavior and update the test in the commit that fixes it.
* fix(kubernetes): Properly substitute characters in key parts 
As kubernetes objects can contain the character ':' which conflicts with our default cache key separator, the caching logic replaces ':' with ';' before generating a cache key and then inverts this by replacing ';' with ':' when splitting a cache key into its component parts.
The current logic that runs when reading cache keys is an expensive no-op; …
> perf(kubernetes): Improve performance of cache kind lookup

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryClientUtils.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizer.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizerTest.java
The HTTPS endpoint for a CloudFoundry account's apiHost field now has its server certificate validated by default.
BREAKING CHANGE: The previous default behaviour used to be skipping the certificate validation. The change might break environments where the certificate or the certificate of its issuers are not in the JVM's trust store.
Skipping the certificate validation for CloudFoundry accounts can be enabled with this `hal` command: `hal config provider cloudfoundry account edit ACCOUNT_NAME --skip-ssl-validation=true`
> feat(cf): Cloudfoundry API endpoint server certificate now validated by default

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
* perf(kubernetes): Reduce memory allocation during caching cycles
The caching logic for the kubernetes v2 provider allocates a
lot of short-term memory during each caching cycle, putting
pressure on the garbage collector, in some cases exceeding
the garbage collection overhead.
A significant contributor is the logic to compute relationships
between kubernetes objects. We currently create a CacheData object
to hold each relationship and rely on downstream (and inefficient)
logic to merge these into one CacheData per object, containing all
of its relationships.
Improve this by having invertRelationships return one CacheData
per object (containing all of its relationships) rather than on
CacheData per relationship. Likewise, have getClusterRelationships
return a single CacheData for each …
> perf(kubernetes): Reduce memory allocation during caching cycles (#3736)

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/DriftMetric.java
Registry.gauge(Id, Number) is deprecated and is for continuously polled
metrics, when what we want is an active gauge that is only published
when available.
> fix(metrics): fix caching agent drift gauge usage

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtilSpec.groovy
Fixes spinnaker/spinnaker#4482
In 1.14, we tried to improve the failure mode for users with misconfigured accounts by using the actual live list of namespaces while validating accounts.
This fails when users are creating a namespace and deploying something to the namespace as part of the same operation; in that case the live list does not know about the namespace (but will by the time the deployment completes).
This reverts spinnaker/clouddriver#3639 (and adds a comment and test to make sure this subtle bug is not re-introduced).
> fix(kubernetes): Allow namespaces that don't exist in validation

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/cache/AzureSecurityGroupCachingAgent.groovy
Background:
Currently, the cache data of firewall hasn't been removed after deleting firewall successfully so that user still can see the firewall in UI.
Fix:
After investigated, it seems that the id isn't specified in eviction list so that the firewall can not be found in cache.
> fix(provider/azure): The cache data of firewall hasn't been removed after deleting firewall successfully

- clouddriver-artifacts/clouddriver-artifacts.gradle
- clouddriver-oracle/clouddriver-oracle.gradle
- clouddriver-web/clouddriver-web.gradle
Reverts spinnaker/clouddriver#3695
https://github.com/spinnaker/spinnaker/issues/4488
https://github.com/spinnaker/spinnaker/issues/4484
This will get Clouddriver as it exists today back to a working runtime state (albeit a painful dev / build experience thanks to Oracle). The @spinnaker/toc will add to the agenda to more clearly define what it takes to:
1. Requirements for adding a new core cloud provider.
2. Requirements for continued core cloud provider support.
3. Process for removal of cloud providers.
It's my opinion that Oracle should be responsible for maintaining their cloud provider and if they're unable to do so, their cloud provider should be deprecated and removed.
cc @andrewbackes @plumpy @shihchang @guoyongzhang
> Revert "chore(clouddriver/oracle): Get the Oracle API jar from Maven."

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java
If a call to kubectl fails to parse the output, we'll return a parsing failure directly to the user. Instead, return a
failed job with the error message and let the caller handle the exception as it would any other failed job.
> fix(kubernetes): Improve error message on kubectl failure

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
Pods are currently set as having a cluster relationship; this means that we create a cluster (and associated relationship to the pod) for every pod in a kubernetes deployment.
This is not necessary, and doesn't match the definition of cluster used by other providers.  These clusters and relationships are also not used when we construct the server group model for
a Kubernetes application; we end up ignoring any cluster that does not map to a server group (which pods do not).
This change will significantly improve the efficiency of both the caching logic, and the logic to return server groups for kubernetes (which now will not need to process each pod individually).
> perf(kubernetes): Remove cluster relationship from pod kind

- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/view/AzureAppGatewayProvider.groovy
- clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerProvider.groovy
Background:
Currently, the status of server group in load balancer tab is with default value "false" so that the status of all server groups under load balancer are enabled. So we add logic to check whether the status of server group is enabled.
> feat(provider/azure): Enable highlight effect for server group in load balancer section

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Clouddriver starts by checking if it can read various K8s types on each K8s account it is configured for, but without specifying which account it's checking, it's hard to identify any accounts that may be timing out or causing issues if Clouddriver is slow to start and you have multiple accounts configured.
This simply adds `accountName` to a few logs to make it easier to see what Clouddriver is doing on startup, especially WRT https://github.com/spinnaker/spinnaker/issues/4407.
> Add accountName to several startup logs

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
* fix(kubernetes): Improve failure mode for unreachable cluster 
We currently cache any call to get the namespaces for an account with an expiry time of 30 s using a memoized supplier.
When a cluster is unreachable, the call to get the cluster's namespaces will hang and eventually time out; we then log a warning and return an empty array of namesapces.
If the call to kubectl returns an error, we don't cache the empty list return value, so every call to get namespaces will call kubectl.  This leads to a bad failure mode where a slow/unresponsive cluster leads to more calls than a fast/responsive cluster.
To address this, when a call to get namespaces returns an error, cache the empty list we're returning for the same amount of time as a successful call.
* fix(kubernetes): Use custom …
>  fix(kubernetes): Improve failure mode for unreachable cluster

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
The Jenkins buildInfo is also populated on a manual trigger of a pipeline with a Jenkins trigger. We should use it.
> fix(cf): capture build info for a manual trigger

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/TargetGroupLookupHelper.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/EddaException.java
Previously, when edda lookup for a loadbalancer/target group would fail we would get
a useless stack trace with `UndeclaredThrowableException` at the top. This exception
would show up in deck causing lots of user confusion (and fail execution).
When in fact, such errors are often benign (we already ignore similar failures of direct AWS lookups)
This change plumbs through the 404 from edda so that it can be dealt with appropriately
(all other failure remain unchanged and re-throw the exception)
> fix(edda): Better error message on edda lookup failures

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy
Handle container instances no longer being cached, but showing up in stopped ECS tasks in the account.  This seems to happen when there is a high rate of change among container instances, for example when using a Spot fleet.
This can be cherry-picked into 1.14.
Fixes spinnaker/spinnaker#4466
> fix(ecs): Handle container instances no longer being cached

- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java
- clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProviderSpec.groovy
Fix incorrect de-duping of clusters with same name, but different accounts
Fixes spinnaker/spinnaker#4448
Can be cherry-picked into 1.14
> fix(ecs): Fix incorrect de-duping of clusters

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusJobProvider.groovy
- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy
When we fail to find the props file specified for a titus task we get a cryptic
error message "cannot access first() element of empty list"
Propagate the actual error when the properties file can't be found
> fix(jobcontroller): better error message if property file not found on job

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- Upgrades fabric8 to 4.1.1 for the same reasons detailed on [this PR](https://github.com/spinnaker/halyard/pull/1350).
- The fabric8 upgrade has some breaking changes for the HPA API, so we need to address these before cutting 1.15 so we don't break the Kubernetes V1 provider.
> fix(deps): bump fabric8 to 4.1.1

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/TitusDeployDescriptionValidator.groovy
when Titus isn't available in a region instead of giving the appropriate error messge we get:
```
No signature of method: com.netflix.spinnaker.clouddriver.deploy.DescriptionValidationErrors.rejectValue() is applicable for argument types: (String, String, String, String) values: [region, titusDeployDescription.region.not.configured, us-east-1 , ...] Possible solutions: rejectValue(java.lang.String, java.lang.String, java.lang.String), rejectValue(java.lang.String, java.lang.String, [Ljava.lang.Object;, java.lang.String), rejectValue(java.lang.String, java.lang.String)
```
> fix(titus): calling non-existant method

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerV2Description.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy
The AWSJavaSDK defines the LBv2 `Rule.priority` property as a `String` and when unset (as is the case when an ALB is created via deck with only 1 routing rule), it is assigned the value `default`. This changes clouddriver's model to match the SDK's so that ALB's containing the default `Rule.priority` value can be actuated via Keel without converting all priorities to ints.
> fix(aws): lbv2 listener rule priorty should be a string

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
- [This fabric8 commit](https://github.com/fabric8io/kubernetes-client/pull/1288/files) updated the Kubernetes HPA version from v1 to v2beta1, which includes a breaking change in the CPU Utilization model detailed in the docs [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/): `Notice that the targetCPUUtilizationPercentage field has been replaced with an array called metrics`.
> fix(kubernetes): update fabric HPA model in v1 provider

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/gcsClient/AppengineGcsRepositoryClient.groovy
- clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/artifacts/GcsStorageService.java
Fixes spinnaker/spinnaker#4530
The appengine deploy stage does not account for the fact that GCS objects can have a version (such as gs://bucket/file.tar#123). Currently sending a file such as the preceding breaks as the provider doesn't recognize it as a tar file (and also includes 123 as part of the file name rather than as an object generation).
Fix this so that the version is parsed out of the file path and is properly sent to the GCS API.
> fix(appengine): Properly account for GCS object version in deploy

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2SecurityGroup.java
V1HTTPGetAction.getPort() now returns an IntOrString. This supports .toString() to always convert to a string, but does not support .toInt() so we need to handle parsing as an int if desired.
The logic to serialize an IntOrString needs to know that it should only dump either getString() or getInt() depending if it's a string or integer, which our ObjectMapper doesn't know about. The Yaml object that comes with the kubernetes API is configured to handle this, so just use that instead to handle serializing.
> fix(kubernetes): Fix a few other bugs from client library upgrade

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2Instance.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ClusterProvider.java
These are all small changes I had on local branches while I was doing performance profiling.  The refactor commits have no performance effect, but I made them while trying to split up the code into smaller pieces that I could understand better so I think they're worth commiting for that reason.
* perf(kubernetes): Reduce deserialization of kubernetes pods 
We're currently deserializing the entire kubernetes pod object when we actually only need the status. Given that pods are very common objects, it's worth only deserializing the status to speed up the server groups endpoint.
* refactor(kubernetes): Remove unused variable isNamespaced 
* refactor(kubernetes): Pull some logic from translateClusters 
The translateCluster function gets both server groups and load balancers; it would be more …
> refactor(kubernetes): A few minor refactors and perf fixes

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
Previously the environment variables that are actually metadata tags were removed from the cached server group because they aren’t really environment variables and they are stored in the build info. But they don’t get copied into a new server group unless the env vars exist.
Also extracted some common env var access code.
> fix(cf): removing tags hiding as env vars kept clone from working

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
* fix(kubernetes): Improve failure mode for unreachable cluster
We currently cache any call to get the namespaces for an account
with an expiry time of 30 s using a memoized supplier.
When a cluster is unreachable, the call to get the cluster's
namespaces will hang and eventually time out; we then log a
warning and return an empty array of namesapces.
If the call to kubectl returns an error, we don't cache the empty
list return value, so every call to get namespaces will call
kubectl.  This leads to a bad failure mode where a slow/unresponsive
cluster leads to more calls than a fast/responsive cluster.
To address this, when a call to get namespaces returns an error,
cache the empty list we're returning for the same amount of time
as a successful call.
* fix(kubernetes): Use custom …
> fix(kubernetes): Improve failure mode for unreachable cluster (#3770)

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ApplicationProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ArtifactProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ClusterProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LoadBalancerProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2SecurityGroupProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ServerGroupManagerProvider.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KeysSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
* refactor(kubernetes): Make cache keys immutable 
We don't ever change cache keys after construction, but they still support (unused) setters.  Make these keys immutable so we can safely use them as keys in sets/maps.
* fix(kubernetes): Fix serialization of cache keys 
Some cache key types don't have symmetry between serialization and deserialization logic.  Fix them so that they do so we can create a key and call toString() and get the same result as if we directly created the string key.
* refactor(kubernetes): Move key constructors into inner classes 
The top-level Keys class supports a number of methods for creating a String representation of various key types. Move these methods into the relevant inner classes and rename them createKey.
* perf(kubernetes): Short-circuit string …
> refactor(kubernetes): Make cache keys immutable

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheData.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesPodMetric.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataSpec.groovy
This is a follow-up to #3829, using the newly created class in a few more places and deleting a lot of now-obsolete code.
* refactor(kubernetes): Process pod metrics outside of parallel loop 
We currently fetch pod metrics in a parallel stream because most of the time is spent in IO waiting for kubectl to return the metrics. We're also processing the metrics in parallel, which blocks moving to the new KubernetesCacheData object as it is not threadsafe.
Rather than make it threadsafe (which would add some overhead and complexity) just move the processing of the received metrics out of the parallel stream and into a sequential stream. We'll still fetch the metrics in a parallel stream, it's just the relatively fast post-processing that will now be sequential.
* refactor(kubernetes): Move …
> refactor(kubernetes): Move pod metrics to use KubernetesCacheData

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiGroup.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiVersion.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesApiGroupSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesApiVersionSpec.groovy
* fix(kubernetes): Fix equality check in KubernetesKind 
We're incorrectly comparing two objects using == instead of
.equals(). This is working currently because the we only ever have one KubernetesApiGroup object for each class, but the next commit will change that.
* perf(kubernetes): Improve performance of API group and version 
These two classes each use a static variable to hold all instances of the class that are ever created. Before creating a new instance of the class, they check to see if there is already a matching instance and if so return that instance instead of creating a new one.
While this might be a reasonable pattern for objects that are expensive to create, here the cost of keeping this object pool is extremely high vs. the cost of just creating an object each time we …
> perf(kubernetes): Improve performance of API group and version

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2SecurityGroup.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindSpec.groovy
* test(kubernetes): Add tests to KubernetesKind 
Add some tests to KubernetesKind before doing some refactoring of that class for performance reasons.
* refactor(kubernetes): A few improvements to KubernetesKind 
In preparation for some more subtle changes, make a few improvements to the KubernetesKind class:
* Make the public static fields also final
* Make it more clear what is nullable and what isn't
* Add equals and hash code methods that allow comparing to kinds via
.equals()
* refactor(kubernetes): Change from == to equals for KubernetesKind 
Most comparisons of KubernetesKind use == instead of equals(), which works because we currently keep a static pool of all KubernetesKinds and never create duplicates.
The cost of keeping this static pool is much higher than the benefit, so move …
> refactor(kubernetes): A few improvements to KubernetesKind

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java
When caching large Kubernetes clusters, ~25% of allocated objects per caching cycle are from calling String.format on cache keys.
String.format is significantly more expensive than String.join as it parses the input as a regular expression. In this case, we can replace the calls to .format() with calls to .join() while keeping exactly the same functionality.
> perf(redis): Replace String.format with String.join

- cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java
When caching values in redis, we compare the hash of the value we're about to write against the value already in the cache to avoid writing unchanged values again.
The hash function we're using is expensive as it encodes the string to bytes before hashing it. Per the documentation of the putString function, it is only useful for cross-language compatibility and we should instead use putUnencodedChars for much better performance when this is not needed.
Link to header block:
https://github.com/google/guava/blob/af57f19e99110695d2b1329ae313aa5158580417/guava/src/com/google/common/hash/Hasher.java#L110
> perf(redis): Don't re-encode string when computing hash

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
Currently every time we deserialize a KubernetesKind we attempt to register that kind. In addition to affecting performance, this is not what we actually want. We should not be registering every kind encountered by clouddriver (including mis-spelled kinds on manifests, etc.) into the static list of kinds.
If the kind we're deserializing *is* registered, we do want to return that kind as the registered kind will have more information than we have available from just the string, such as if the kind is namespaced or if the kind has a cluster relationship. But if it's not registered we don't want to register this kind (and in fact we have no additional information to provide when registering the kind as just the string doesn't tell us the other attributes anyway).
Clean up the public …
> fix(kubernetes): Don't register kinds on deserialization

- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
- cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlCacheSpec.groovy
Fixes: https://github.com/spinnaker/spinnaker/issues/4591
Previously the type sanitization only had a limited set of matching characters, this creates bugs when encountering a cache type which included non-permitted mysql identifier characters. Change the regex to include the ASCII set of permitted chars outlined here: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
Added a test which previously failed to prove this fixes the problem.
> fix(SqlCache): modify typeSanitization regex to match unpermitted chars

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindRegistry.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindRegistrySpec.groovy
The KubernetesKind class is responsible for both providing information about a given KubernetesKind and for keeping a registry of all registered kinds.  The registry of all kinds is stored as a list which is very inefficient to search.
In preparation for making this logic more efficient, create a KubernetesKindRegistry that supports registering kind or getting registered kinds. The implementation will be the exact same (inefficient) one that is currently directly in KubernetesKind but we have now defined an API and can write tests against it, and in a future commit replace it with a more efficient implementation.
> refactor(kubernetes): Create KubernetesKindRegistry

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindRegistry.java
* refactor(kubernetes): Pull kind identifying information to ScopedKind 
I created ScopedKind as a helper class in KubernetesKind but it really represents the "key" for a given Kind (ie, the unique information that determines what kind we're talking about as opposed to other attributes).
Move the name and apiGroup information to live in ScopedKind to encapsulate this.
* perf(kubernetes): Use a more efficient kind registry 
We're always looking up kinds by either name or alias; instead of storing the kinds as an array and looping on every request, create a HashMap mapping the name -> KubernetesKind and another mapping alias -> KubernetesKind so it's easy to look up a kind by name or alias.
> perf(kubernetes): Use a more efficient kind registry

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy
By default, most browsers will not specify `application/json` in the accept header, but will specify `application/xml`
clouddriver will gladly oblige and return `xml`. XML is so 2001... force responses to be `json`
> fix(web-config): force spring to always return json

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/custom/CustomArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/custom/CustomArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/custom/CustomArtifactCredentials.java
Add support for custom artifacts which was not supported previously in the expected artifacts rewrite. The GCE deploy server group was using custom artifacts.
> feat(core): add custom artifact type for new artifacts refactor

- build.gradle
- clouddriver-bom/clouddriver-bom.gradle
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa
> fix(bom): Fix generated pom.xml to omit invalid lombok declaration

- build.gradle
Updates version of Fiat consumed to 1.0.9 (really a patch of 1.0.4), which includes [these commits](https://github.com/spinnaker/fiat/releases/tag/v1.0.9).
> fix(deps): bump fiat to 1.0.4-patch

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpec.groovy
* perf(kubernetes): Use null instead of optional 
We create a lot of ScopedKind objects to look up kinds, so the cost of creating an Optional each time is non-negligible.
In general using Optional can be more readable than null but in this case we'd rather the performance of null (and it's just as easy to read here).
* perf(kubernetes): Store Kind on the KubernetesManifest object 
In processing manifests, we call getKind() multiple times per manifest. It's not a cheap accessor as it needs to look up kinds in the kind registry.
While recent changes have made looking up kinds a lot more efficient, it still doesn't make sense to re-do this work multiple times per manifest.
Compute the kind on-demand and store it on the object; clear the cached value if we change either the kind or api group …
> perf(kubernetes): Store Kind on the KubernetesManifest object

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2SearchProvider.java
* perf(kubernetes): Filter unclassified kinds from search query 
When performing searches, we attempt to interpret the input type as a Spinnaker kind and to search the corresponding Kubernetes kinds. For example, if a user inputs serverGroups, we'll translate that to add replicaSets and daemonSets to the types to search.
If the input type is *not* a Spinnaker kind, it gets mapped to KubernetesSpinnakerKindMap.SpinnakerKind.UNCLASSIFIED. Currently this is causing the search logic to search *every* Kubernetes kind that is also unclassified which is expensive and not what we want.
If the input string is not a Spinnaker kind, just skip adding any extra kubernetes kinds to search.
* refactor(kubernetes): Simplify relationship code 
The code to look up keys related to an application/cluster …
> perf(kubernetes): Improve performance of kubernetes search

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
Fixes spinnaker/spinnaker#4571.
Currently we'll consider a daemonset stable if it has the correct number of replicas, even if they are of the wrong generation. Fix this by adding a check for the generation, just as we do for replica sets.
Also, fix a bug in the replica set implementation where we are comparing Integers using == instead of using .equals.
> fix(kubernetes): Fix daemonset stability condition

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppengineMutexRepository.groovy
- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/AppengineMutexRepository.java
I found these bugs while looking into spinnaker/spinnaker#4574.  I'm not sure if this is the root cause of those issues, but it certainly could be and is worth fixing.
* refactor(appengine): Remove unnecessary catch block 
There's no need to catch an exception only to re-throw it in the finally block. Replace with an idiomatic try/finally.
Also add some public/private modifiers that will make conversion to java in the next commit easier.
* refactor(appengine): Convert mutex repository to java 
* fix(appengine): Fix threading bugs in AppengineMutexRepository 
There are a couple of threading bugs here:
(1) We do an unsyncronized containsKey + put to generate the mutex for a given String, which can lead to two threads holding different Mutexes for the same String.
(2) The Mutex itself has a …
> fix(appengine): Fix threading bugs in AppengineMutexRepository

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
Closes https://github.com/spinnaker/spinnaker/issues/4446
- Removes validation preventing multi-manifests to be deployed as part of a Spinnaker-coordinated rollout strategy. Still expects exactly one ReplicaSet, but now permits other resources to be deployed alongside the ReplicaSet. (Also, the designated Service must still be deployed prior to the rollout.)
Related PRs:
Deck: spinnaker/deck#7219
Orca: https://github.com/spinnaker/orca/pull/3034
> feat(kubernetes): allow multi-manifest with rollout strategies

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineServerGroupCachingAgent.groovy
Appengine always requires that a service have at least 1 version, except for the `default` version which is not deletable. This causes an NPE when the caching agent attempts to cache a `default` service with 0 versions. Put the removeIf inside of the version check to fix this NPE
> fix(appengine): check for null versions in servergroup caching agent

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/Images.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/StatefullyUpdateBootImageAtomicOperation.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/FakeComputeBatchRequest.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/FakeGoogleComputeOperationRequest.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/FakeGoogleComputeRequest.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/ImagesTest.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/SetStatefulDiskAtomicOperationUnitSpec.groovy
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/StatefullyUpdateBootImageAtomicOperationTest.java
I found this while looking for calls that needed pagination support. I
started to add pagination to the List call before I realized there was
really no point since we were applying a filter so that it would only
ever return a single image (or none).
I'm not sure why this didn't occur to me when I originally wrote the
code.
> refactor(google): use Get instead of List to find a specific image

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleLoadBalancerProvider.groovy
- Some GCE users have reported that it can take about ten seconds to open the clone server group modal. The slowest request that must complete before the model loads is to `/loadBalancers?provider=gce`. Based on profiling, `GoogleLoadBalancerProvider.getApplicationLoadBalancers` seems to be the main culprit in terms of allocations.
- This method first retrieves every LB ID associated with the given application. Then, since you can attach other applications' LBs to a SG, it grabs every single server group in the given application and grabs every associated LB's ID. Then it dedupes all the LB IDs.
- This gets really bad because we are calling this method from `GoogleLoadBalancerProvider.list` with _no_ application specified, so we were grabbing _every_ load balancer from the cache, and then …
> perf(google): when fetching lbs, only load every sg if needed

- clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
add `/opt/spinnaker/config/` to `spring.cloud.bootstrap.location` since it's the default configuration path for standard installs.
> fix(configServer): add /opt/spinnaker/config/ as default

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/PropertyParser.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/PropertyParserSpec.groovy
when the property parser exountered a malformed it would throw an out of
bounds exception and fail. we should just skip properties with empty
values.
> fix(kubernetes): fix property parser exception

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesAutoscalerStatus.groovy
@maggieneterval -- just realized I stripped out currentCpuUtilization from the class and forgot to add it back with my final commit on Friday.
Embarrassing -- but here's the fix!
> fix(kubernetes/v1): re-add currentCpuUtilization

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/MetricInstrumentation.groovy
Long tag values can cause issues for some time series systems. The
caching agents in particular are a bit too generous, as the provider
name often includes the full package path (typically 50-60 chars that
don't provide much value)
> fix(metrics): strip the provider's package name in agent metrics

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleApplicationProvider.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleInstanceProvider.groovy
As the number of GCE resources increases, the `/serverGroups` request becomes unacceptably slow. Because I would like to cherry-pick this into 1.15, this is intended to be the least invasive refactor possible. Changes by class:
`GoogleApplicationProvider`
- Abstracts retrieving application cache data, and the identifiers of clusters and instances associated with an application, into reusable methods (to be used by `GoogleClusterProvider`).
`GoogleClusterProvider`
- Previously, `GoogleClusterProvider.getClusters` called `GoogleApplicationProvider.getApplication`, which retrieves the application cache data, maps it to a `GoogleApplication` object, transforms the related clusters into an account-to-cluster map, and transforms the related instances into a list of maps created by calling …
> perf(google): improve performance of /serverGroups endpoint

- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleApplicationProvider.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleClusterProvider.groovy
My bad! :see_no_evil: :sob: 
`GoogleApplicationProvider.getApplication` can be called with non-GCE application names, so we cannot assume 1) That we can build an instance of `ApplicationCacheData` (should default to null) or 2) That we will have a non-null instance of `ApplicationCacheData` downstream.
> fix(google): return null guards to GoogleApplicationProvider

- build.gradle
- clouddriver-event/clouddriver-event.gradle
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/Aggregate.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/EventListener.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/EventMetadata.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/EventPublisher.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/SpinnakerEvent.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/config/EventSourceAutoConfiguration.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/config/MemoryEventRepositoryConfig.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/exceptions/AggregateChangeRejectedException.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/persistence/EventRepository.kt
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/persistence/InMemoryEventRepository.kt
- clouddriver-event/src/test/kotlin/com/netflix/spinnaker/clouddriver/event/EventSourceSystemTest.kt
- clouddriver-event/src/test/kotlin/com/netflix/spinnaker/clouddriver/event/persistence/InMemoryEventRepositoryTest.kt
- gradle.properties
- gradle/spek.gradle
- settings.gradle
This is PR 1 of N for some new idempotency functionality in River. The implementation will be confined to the Titus provider only while we iterate ergonomics of the various components.
The idempotency functionality implements a Saga pattern that is backed by an immutable event log. While not strictly required for the design pattern, backing operations by an eventing system will make it more palatable for debugging and auditing functionality later on, as well as new interaction possibilities between clouddriver & orca in the future.
Current implementation targets an in-memory store only. Future contributions will add a SQL backend so that operations can be retried by Orca in the face of downstream cloud provider failures.
It is possible that this functionality could be lifted into kork at …
> feat(event): Adding eventing lib

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobDeploymentResult.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobOperation.java
return the operation result data alongside the data required by the run
job task. the operation result data will be used when refreshing the
cached manifests in downstream refresh tasks
> fix(provider/k8s): return operation result data

- build.gradle
- gradle.properties
Upgrading Guava in Kork also upgraded errorprone which caused a build
error, so this forces error-prone back to a version that works with our
build.
> chore(dependencies): manually bump korkVersion

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
This is the third time I've had to untangle weird circular dep issues in the Titus provider. Will need to take a closer look at the whole provider after this deploy operation refactor is done and over with.
> fix(titus): "Fix" circular dependency with Provider

- clouddriver-saga/clouddriver-saga.gradle
clouddriver-saga requires spring-web which it is currently inheriting transitively
> chore(dependencies): add missing dependency

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/JobType.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/PrepareTitusDeploy.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/actions/PrepareTitusDeployActionSpec.groovy
A bit of a refactor to make the Titus deployment code related to security groups a little simpler / consolidated to a single area. Also added a couple tests to validate the rough behavior.
> fix(titus): Consolidate & verify security group assignment behavior

- .circleci/config.yml
Apparently changing the parallelism via the UI doesn't work.
> chore(build): Increase parallelism of circle builds

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KeysSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindSpec.groovy
* fix(kubernetes): Revert consistent casing for kind 
The prior commit to always serialize kinds as lowercase is still something we should do longer-term to reduce the fragility of code that is depending on particular casings
(ex: replicaSet).
That being said, it turns out there are more places depending on the current casing than I initially thought. In particular, the logic to substitute parts of a kubernetes manifest (ex: to replace a config map with the fully-qualified config map with a version) depends on the kind being camelCased.
As we're approaching 1.16, I think that this is a more invasive change that I'd like to do right now, and would also like to decouple that change from the more important work to refactor Kubernetes kinds.  So this commit rolls back the change that always …
> fix(kubernetes): Use consistent casing for built-in kinds

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
These annotations were dropped in converting KubernetesKind; this means that we're serializing a KubernetesKind as a full object rather than just as a string. This slightly changes the result of calls to /serverGroups and /loadBalancers as now the 'kind' field is an object not a string. This could cause issues with consumers that expect a specific format; our integration tests expect to see just a string there which is how I found this.
> fix(kubernetes): Add Json annotations

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsSpec.groovy
This PR fixes dynamic account reloading when configured via `git`. I'm not entirely sure but it seems that when `configserver:` is used on `kubeconfigfile`, a new file is created at each polling. Since the file is different, the account is considered new and reinitialized.
The fix is to remove the test on `kubeconfigfile`. We already test on `kubeconfigFileHash`.
This may potentially be a problem if the operator deletes the old file and decide to add a new account with the exact same parameter since `kubeconfigFileHash` is computed once.
Would appreciate some review from @ethanfrogers and @scottfrederick
> fix(kubernetes): Dynamic accounts reload when kubeconfig content changed

- clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineLoadBalancer.groovy
RANDOM is a missing shardBy method causing errors to be logged during CloudDriver boot. This adds RANDOM as a supported enum as seen in the appengine docs: https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services#ShardBy
> fix(appengine): add RANDOM as a supported ShardBy

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizableSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
* refactor(kubernetes): Rename InvalidKindReason and avoid nulls 
Instead of having an enum InvalidKindReason, and returning null when a kind is valid, jsut call it KindStatus and use an enum value VALID to represent a valid kind. This avoids the need to use null as a sentinel value.
* refactor(kubernetes): Change lists to immutable sets 
We store a list of kinds and kinds to omit on each account; these lists are never modified after they are created, and we only ever do set-like operations on them (contains, size).
In order to make lookups more efficient, and prevent bugs (and make the following refactor easier), change the lists to immutable sets.
* perf(kubernetes): Defer checking valid kinds until after startup 
Instead of blocking the startup of clouddriver while we check whether we …
> perf(kubernetes): Defer checking valid kinds until after startup

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesV1CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNamespaceCachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
The goal here is to avoid blocking startup while waiting to read namespaces from an unreachable/down cluster.  Just as we did with checking readable kinds, this defers reading namespaces until first use, where waiting for the call to timeout will not block caching other clusters.
* refactor(kubernetes): Push namespace logic down to V1 and V2 
A following commit will simplify the logic for handling namespaces in the kubernetes caching agents. There is a lot of legacy V1 code in groovy that depends on the particular implementation that I don't want to refactor and test as part of this change. In order to restrict the change to V2, push this logic down from the base caching agent to the V1 and V2 caching agents, where it is for now duplicated but will soon be changed in V2.
This also makes …
> perf(kubernetes): Defer loading namespaces until first use

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
kubectl auth can-i returns 'yes' for kinds that you have permission for, even if they don't exist on the cluster. The change to defer kind checking removed filtering on the result of kubectl api-resources (mistakenly thinking this filtering was only for performance).
This means that clouddriver is trying to cache unreadable kinds if they are unreadable because they don't exist. Fix this by reverting to the old behavior of just trying to call 'list' on a resource to determine if it's readable. (This is probably not any more expensive than doing an api-resources call every time we check if a kind is readable and is simpler.  It also reproduces exactly what the caching agent is doing so should avoid edge cases like the bug here.)
> fix(kubernetes): Fix handling of kinds not available on the server

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AbstractAmazonCredentialsDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/preprocessors/CredentialsAccountNormalizationPreProcessor.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/AbstractEcsAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DisableServiceAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/EnableServiceAtomicOperation.java
- clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/TerminateInstancesAtomicOperation.java
- clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy
- clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/AbstractLambdaAtomicOperation.java
- clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/CredentialsNameable.java
What could possibly go wrong with this? Really. What could possibly go wrong with this? I know we have duplication for `credentials` vs `account`, this is standardizing on `credentials`, since like... I don't even know why `credentialAccount` ever existed to begin with.
It looks to me like most of the code for descriptions expects `credentials`, whereas `account` isn't really referenced directly anyhow? (Looking at `AtomicOperationConverter`s for the AWS-derived cloud providers).
> refactor(*): Remove credentialAccount from all AWS-derived cloud providers

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AllowLaunchDescription.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperation.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/preprocessors/AllowLaunchPreProcessor.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/AllowLaunchDescriptionValidator.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/AllowLaunchAtomicOperationUnitSpec.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/AllowLaunchDescriptionValidatorSpec.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsSupport.groovy
We asked, "What could possibly go wrong?" with #4017. It turns out `AllowLaunchDescription` overloaded `account`, which broke any deploy from a newly baked image. That's what can go wrong.
This PR fixes that, making the description use a new field and fix-forward whatever Orca sends us.
> fix(aws): Alter AllowLaunchDescription to not overload account

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesCachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialFactory.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/KubernetesV1ProviderSynchronizable.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizable.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgentDispatcher.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/config/KubernetesConfiguration.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/securitygroup/UpsertKubernetesV1SecurityGroupAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/CloneKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperationSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/StandardKubernetesAttributeValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/servergroup/CloneKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/validators/servergroup/DeployKubernetesAtomicOperationValidatorSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/KubernetesV1ProviderSynchronizableSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesLoadBalancerCachingAgentSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgentSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesV1SecurityGroupCachingAgentSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1CredentialsSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizableSpec.groovy
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
The motivation here is to fix a number of unsafe casts in the creation of credentials, and to clean up that code a bit.  I ran into this while working on my next performance change (in an upcoming PR) to fix a few endpoints that hang when a cluster is unreachable (now that startup is fixed in that case). 
* refactor(kubernetes): Split CredentialFactory to V1 and V2 
A lot of the unecessary casts that we do when creating credentials stem from the fact that we have a single CredentialFactory with different methods for creating V1 and V2 credentials.
Instead, make a generic interface KubernetesCredentialFactory that pulls out the common logic to default methods.  (These default methods should probably both eventually live somewhere else, but I think having them on the interface is a …
> refactor(kubernetes): Fix some unsafe casts in credential creation

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/GlobalKubernetesKindRegistry.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindRegistry.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/GlobalKubernetesKindRegistrySpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindPropertiesSpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindRegistrySpec.groovy
* refactor(kubernetes): Reduce API surface of KubernetesKindProperties 
Only the statically-defined kinds are allowed to set isDynamic to false, or hasClusterRelationship to true. In order to make this statically true, make the full constructor private and expose a factory method that doesn't allow those properties to be set for use outside the class.
(Some of the usages of the constructor in tests *did* set isDynamic and hasClusterRelationship, but these were just testing the API that was available; now that these are not exposed outside the class the tests can just use the factory method.)
* refactor(kubernetes): Simplify getRegisteredKinds 
The only time we ever use the getRegisteredKinds method in KubernetesKindRegistry, what we actually want is a list of the global kinds (so we can …
> refactor(kubernetes): Reduce API surface of KubernetesKindProperties

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/GlobalKubernetesKindRegistry.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindRegistry.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/GlobalKubernetesKindRegistrySpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesAccountResolverSpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindRegistrySpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindPropertiesSpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindSpec.groovy
* refactor(kubernetes): Remove useless call to register kind 
On account creation, we iterate over all kinds in the account and call registerKind. Since we only have the name of the kind and no other information, we just assume the kind is namespaced and pass true.
Since the kind registry will return a set of default properties
(including isNamespaced set to true) for something not in the registry, skip the needless call to register these kinds with default properties.
* refactor(kubernetes): Pass custom resources to registry constructor 
Each account has a set of custom resources that are statically defined in the account config. We register each of these into the KubernetesKindRegistry, but currently do so in a somewhat opaque way, by depending on a side-effect of the …
> refactor(kubernetes): Look up CRD details on-demand

- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaService.kt
Having a wrapped exception was making `ExceptionSummary` expose a less useful exception to end users. It would _probably_ be a good idea longer-term to add some smarts around automatically unwrapping, but... nah.
> fix(saga): Unwrap exception coming from a saga action

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
The call to primaryKinds() on a caching agent can be expensive, as it may (depending on the caching agent) need to look up available CRDs and/or available namespaces. We make this call in a tight loop in a few places; pull the call out of the loop.
Also replace the lambda in liveNamespaceSupplier with an actual private function for readability (and to make later refactoring easier).
Finally, we make a redundant call to credentials::isValidKind in the CRD caching agent; primaryKinds() already filters on this before returning.
> perf(kubernetes): Reduce namespace lookups in a loop

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtilSpec.groovy
Fixes spinnaker/spinnaker#4407.  See #3770 for prior work on this.
* refactor(kubernetes): Make namespaces immutable 
The namespaces and omitNamespaces fields on KubernetesV2Credentials never change; let's enforce that by making them immutable.
* fix(kubernetes): Fix credentials endpoint with unreachable cluster 
Calling the endpoint to list credentials currently calls getNamespaces on KubernetesNamedAccountCredentials, which in turn calls getDeclaredNamespaces on the account.
Because of the caching logic, this sometimes results in a live call (if the current entry is expired) which can cause the entire endpoint to hang. We should always serve this call out of the cache (and handle any refreshes asynchronously) so that we never hang on this call. I think a slight increase in stale reads …
> fix(kubernetes): Fix credentials endpoint with unreachable cluster

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/InstanceTargetGroupState.groovy
An instance in a draining state still has open connections, wait until draining
completes before marking the instance out of service.
This is consistent with CLB behaviour where an instance remains InService during
its draining period, and we still consider it to be UP as a result.
> fix(aws/loadbalancing): don't mark an instance out of service until draining completes.

- clouddriver-sql-mysql/clouddriver-sql-mysql.gradle
- clouddriver-web/clouddriver-web.gradle
This change allows a custom build of Spinnaker to exclude the `mysql-connector-java` driver from the generated distribution with a build command like:
`./gradlew clouddriver-web:installDist -x test -PexcludeSqlDrivers`
The driver is included in the build by default, so the build results are not changed for existing open-source and custom builds. 
The Gradle dependency types were changed from `implementation` to `runtimeOnly` to reflect the fact that `mysql-connector-java` is not needed for compilation.
> feat(sql): Conditionally allow MySQL Connector to be excluded from the build

- clouddriver-artifacts/clouddriver-artifacts.gradle
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactConfiguration.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactProviderProperties.java
adds support for a git repo artifact type which will clone a given git
repo, package it up as a tar.gz and return the value. callers of this
artifact type should expect a .tar.gz and act accordingly, decompressing
if necessary. this impl. doesn't include support for cloning the
repository at a particular history depth as jgit doesn't support that
option. the alternative is to perform git operations by shelling out to
git but i opted not to do that because it makes authentication much more
difficult than it is _with_ jgit.
> feat(artifacts/gitRepo): add support for git repo

- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlAgentProperties.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlTaskCleanupAgentProperties.kt
- This fixes an issue preventing users of open source releases of clouddriver from using the sql backed caching agent scheduler.
> fix(kotlin): spring config classes shouldn't use constructors

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiVersion.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
This PR implements support kubernetes 'apps/v1' ApiVersions for deployments/replicaset, deployed to Kubernetes clusters >1.16.0 and solves issue [#4946](https://github.com/spinnaker/spinnaker/issues/4946)
> fix(kubernetes): add support 'apps/v1' for deployments/replicaset

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2SecurityGroup.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesIngressHandler.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
* refactor(kubernetes): Pull api versions to a set 
A number of different places check the API version of a manifest against a set of supported ones using a log if condition. Replace these with a statically-defined set of supported versions and a check of whether the manifest's API version is in the set.
This commit doesn't change any of the supported versions.
* fix(kubernetes): Add networking.k8s.io/v1beta1 ingress versions 
In Kubernetes 1.20, Ingress will stop being served from the extensions/v1beta1 API group and will only be served from the networking.k8s.io/v1beta1 API group (which has been available since 1.14).
> fix(kubernetes): Add networking.k8s.io/v1beta1 ingress versions

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
- It turns out titus instances where not getting cached in the `instances` in memory cache , this was due to the fact that `TitusStreamingUpdateAgent` was not implementing `getProvidedDataTypes` method 
Refer here for more context : https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/SearchableProvider.java#L91
> fix(titus): Fixing titus instance id search

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiVersion.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesIngressHandler.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
This change cherry-picks the safe parts of #4055 and #4056 into the 1.16 branch. In particular, it pulls just the additive changes that admit new API versions: we now accept v1 Deployments and ReplicaSets, as well as networking.k8s.io/v1beta1 Ingresses.
This change does *not* update the code to start deserializing all existing objects as these new types, as that does have the potential to break existing functionality. It also does not cherry-pick the minor refactoring to pull the supported versions into sets and avoid the long chain of or conditions.
The interest of cherry-picking this is that these new API versions have been supported since Kubernetes 1.9 so even users who have not fully upgraded may still run into errors using them (and the erorrs are not necessarily easy to debug, …
> fix(kubernetes): Fix missing API versions

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindSpec.groovy
* refactor(kubernetes): Remove getters from KubernetesKind 
Once a KubernetesKind has been created, external classes should
(and do) only care about its string representation, not the individual fields. Remove the unused getters from the name and apiGroup fields (and update one test that was relying on them).
* chore(kubernetes): Update API group of NetworkPolicy and PodSecurityPolicy 
The NetworkPolicy and PodSecurityPolicy kinds have been moved from extensions/v1beta1 to networking.k8s.io/v1 and policy/v1beta1 respectively. Update the API group for these kinds in KubernetesKind.
Given how the V2 provider queries kinds, this change actually has no functional effect as kinds from built-in API groups are serialized as the kind name alone (wihtout api group) leaving kubectl to resolve the …
> chore(kubernetes): Update API group of NetworkPolicy and PodSecurityPolicy

- clouddriver-kubernetes-v1/clouddriver-kubernetes-v1.gradle
- clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
- clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesAutoscalerStatus.groovy
These upgrades get us [compatibility](https://github.com/fabric8io/kubernetes-client#compatibility-matrix) with kubernetes 1.15 without losing compatibility with any older versions.
* chore(kubernetes): Bump fabric8 library to 4.3.1 
This commit also updates the code in response to a couple of breaking changes in the upgrade. Notably, the cpu utilization target of a replicaset is now a top-level field rather than being nested in a metrics object. Likewise, the current utilization is a top-level field of the status, rather than nested in a metrics object.
* chore(kubernetes): Bump fabric8 library to 4.6.0
> chore(kubernetes): Bump fabric8 library to 4.6.0

- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactAccount.java
- clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java
adds support for SSH authentication and also improves UX around what
happens if the users supplies a reference that isn't supported by the
auth type.
> feat(artifacts/gitRepo): support SSH auth

- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/Cache.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/cache/CompositeCache.java
- cats/cats-core/src/main/java/com/netflix/spinnaker/cats/mem/InMemoryCache.java
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderCache.kt
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
We don't need to leak this information to clients. They don't care what
the storage type is; they care whether or not getAllByApplication works,
so just let them ask that.
> refactor(cats-core): Remove Cache.StoreType

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/JsonPatch.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandler.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandlerSpec.groovy
Fixes spinnaker/spinnaker#4893.
Implements escaping of '~' and '/' characters when used in labels as defined in RFC 6901.
https://tools.ietf.org/html/rfc6901#section-3
Allows for the use of labels such as "app.kubernetes.io/name" and "app.kubernetes.io/instance" in the service selector.
> Escape label names when attaching/detaching a replicaset from a service

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/SagaId.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/SagaAtomicOperationBridge.java
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTask.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
Tasks are created prior to the atomic operation processor operation.  In order to bridge atomic operations and sagas, we store the saga IDs when added to the SqlTask during the bridge process.
@robzienert
> fix(saga): Update sql task with saga IDs

- Dockerfile.slim
reading from `stable.txt` causes builds to be non-deterministic which could lead to problems in the future. we should be explicit about the version of `kubectl` that we ship. `v1.16.0` was the latest version as of this PR.
> fix(dockerfile): use deterministic version for kubectl

- clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperation.java
- clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ScaleCloudFoundryServerGroupAtomicOperationTest.java
When scaling a disabled server group in cloud foundry we should use the "max" value because a disabled stated in CF would be a stopped state which would result in 0 instances running but we should still adjust the number instances to the target number if the server group is enabled/started.
fix for spinnaker/spinnaker#4786
> fix(cf): when scaling cf disabled SG we should use max capacity

- gradle/buildViaTravis.sh
An attempt at cutting down some of the (unnecessary) gradle tasks that are run during a release.
> fix(travis): Skip 'check' when doing release builds

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperation.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationConverter.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsService.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/TitusDeployAtomicOperationConverter.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.java
It turns out that TitusDeployHandler (and other DeployHandler classes) are singleton components
that get injected into prototype AtomicOperation components, which I didn't realize until now.
The issue with this is that I was setting request-scoped context into a singleton bean, which
could lead to some neat concurrency bugs. This change modifies things for DeployAtomicOperation
specifically to inject the SagaContext into the description (which is actually request-scoped)
rather than passing through to the TitusDeployHandler object.
There's also this neat feature I discovered while working through this where we convert the raw request input into an atomic operation description twice, throwing away the first conversion after we've validated the input. Not sure why we do this, but it seems …
> fix(titus): Fix SagaContext wiring in DeployHandler cases

- clouddriver-kubernetes-v2/clouddriver-kubernetes-v2.gradle
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/ArtifactKey.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/ArtifactKeyTest.java
Fixes spinnaker/spinnaker#4956
When determining whether the deploy and patch manifest stages bound all required artifacts, the artifacts in the list of required artifacts have an artifact account set while those in the list we're trying to bind don't.
As the .equals function of Artifact includes the account in its comparison, this means that we don't recognize the replaced artifacts as the ones we expected to replace and fail the stage.
Trying to fix this more generally is riskier than I'd like to cherry pick, so as a temporary fix, define a class ArtifactKey that contains the fields we'd like to use when comparing artifacts and use that class for the comparison.
> fix(kubernetes): Fix matching of artifacts in deploy/patch stages

- clouddriver-kubernetes/clouddriver-kubernetes.gradle
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/ArtifactKey.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
- clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/ArtifactKeyTest.java
Manual cherry pick of #4078; had to manually update the `.gradle` files due to split of `clouddriver-kubernetes` into v1 and v2 code.
* fix(kubernetes): Fix matching of artifacts in deploy/patch stages
When determining whether the deploy and patch manifest stages bound
all required artifacts, the artifacts in the list of required artifacts
have an artifact account set while those in the list we're trying to
bind don't.
As the .equals function of Artifact includes the account in its
comparison, this means that we don't recognize the replaced artifacts
as the ones we expected to replace and fail the stage.
Trying to fix this more generally is riskier than I'd like to cherry
pick, so as a temporary fix, define a class ArtifactKey that contains
the fields we'd like to use when comparing …
> fix(kubernetes): Fix matching of artifacts in deploy/patch stages (#4078)

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeployCloudFormationDescription.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperation.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperationSpec.groovy
see https://github.com/spinnaker/spinnaker/issues/5004
Add the ability to specify the roleARN permission in the 'deploy cloudformation' stage.
> feat(provider/aws): Add roleARN to cloudformation deployments

- clouddriver-sql/clouddriver-sql.gradle
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskCleanupAgent.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepository.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/sql.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
- clouddriver-sql/src/test/java/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepositoryTest.java
- clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepositoryTest.kt
- clouddriver-web/config/clouddriver.yml
If we go this route, I would like to see the work to back Spectator with a Micrometer registry get resurrected, so we can surface some of these Resilience4j metrics easily (example PR: https://github.com/spinnaker/kork/pull/268)
> feat(retry): Resilience4j Spring Boot2 implementation in clouddriver-sql

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescriptionSpec.groovy
> fix(titus): Serde fix for SagaContext

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/5001
Below you can find some Deploy stage logs, which proves that lifecycle hooks are created before scaling out the server group:
```
{ 
"phase":"AWS_DEPLOY",
"status":"Beginning Amazon deployment."
},
{ 
"phase":"AWS_DEPLOY",
"status":"Beginning ASG deployment."
},
{ 
"phase":"AWS_DEPLOY",
"status":"Found ancestor server group, parsing details (name: testaws-stage-v009)"
},
{ 
"phase":"AWS_DEPLOY",
"status":"Deploying ASG: testaws-stage-v010"
},
{ 
"phase":"AWS_DEPLOY",
"status":" > Deploying to subnetIds: subnet-3d7dd13b,subnet-28b24012,subnet-5bc30543"
},
{ 
"phase":"AWS_DEPLOY",
"status":"Creating lifecycle hooks for: testaws-stage-v010"
},
{ 
"phase":"AWS_DEPLOY",
"status":"Creating lifecycle hook ({LifecycleHookName: …
```
> feat(provider/aws): Fix lifecycle hooks racing condition

- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/autoscaler/UpsertKubernetesAutoscalerAtomicOperation.groovy
- clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/KubernetesAutoscalerStatus.groovy
We are throwing an NPE if the resource field on a metric is null.
This PR is directly against the 1.16 branch as this has already been fixed by bumping the fabric8 library and changing how we look up metrics on master in #4060
> fix(kubernetes/v1): Fix NPE in autoscaler caching

- Dockerfile.slim
- Dockerfile.ubuntu
Bump awscli to a more recent version (https://github.com/aws/aws-cli/releases/tag/1.16.258 release on October 11th)
This allows using the recently added `aws eks get-token` command (added in 1.16.232) for kubernetes auth instead of `aws-iam-authenticator` command. 
see https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html
> feat(aws): upgrade awscli

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
fixes a bug where you couldn't fetch output on jobs with multiple
containers. this was because we weren't specifying the exact container
name to fetch. update the method to take the container name.
> fix(runJob): fix output on multi container

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesRollingRestartManifestConverter.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestOperationDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesRollingRestartManifestDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanRollingRestart.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesRollingRestartManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/manifest/KubernetesRollingRestartManifestValidator.java
- clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesAtomicOperationDescription.java
Closes https://github.com/spinnaker/spinnaker/issues/4757
As the many comments/emojis on this [Kubernetes feature request](https://github.com/kubernetes/kubernetes/issues/13488) indicate, there are several valid user stories around issuing a rolling restart of a Deployment. The `kubectl rollout restart` command was released with kubectl version 1.15, and we currently use kubectl version 1.16 in Clouddriver. Like the other `kubectl rollout` commands, it is valid for Deployments, StatefulSets, and DaemonSets. We currently only expose the ad-hoc rollout commands for Deployments in Deck, but could at a later date expose them for StatefulSets and DaemonSets if there is evidence from users that it would be useful.
Related PRs:
Orca: https://github.com/spinnaker/orca/pull/3233
Deck: …
> feat(kubernetes): support rolling restart operation for deployments

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/UpsertTitusScalingPolicyAtomicOperation.groovy
- wrap a retry on scaling policy create call for good measure
- fix retry count/timeout for checking if the scaling policy was applied
- make retry to be exponential
> fix(titus): Adjust retries on upsert scaling policy operation

- clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/KubernetesKindAtomicOperationDescription.groovy
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/artifact/KubernetesCleanupArtifactsDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/job/KubernetesRunJobOperationDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesDeployManifestDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesMultiManifestOperationDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesPatchManifestDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/servergroup/KubernetesServerGroupOperationDescription.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/artifact/KubernetesCleanupArtifactsOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/AbstractKubernetesEnableDisableManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeleteManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPauseRolloutManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesResumeRolloutManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesScaleManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesUndoRolloutManifestOperation.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/servergroup/KubernetesResizeServerGroupOperation.java
- Per the wisdom of @ezimanyi, [this PR](https://github.com/spinnaker/clouddriver/pull/4100) parameterized `KubernetesAtomicOperationDescription` so we would not have to cast the credentials object to either V1 or V2. This PR explicitly parameterizes the other extensions of `KubernetesAtomicOperationDescription` and removes casting wherever possible.
- P.S. This was so much more straightforward now that all the V1-only and V2-only code is in separate modules! :house_with_garden: :nail_care: :bento:
> refactor(kubernetes): remove unnecessary casts to credentials classes

- clouddriver-kubernetes-v2/clouddriver-kubernetes-v2.gradle
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
- clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgentTest.java
* test(kubernetes): Add tests to KubernetesCoreCachingAgent 
The next commit will fix a bug in the Kubernetes caching agents; there are currently no tests validating these agents. Add some tests on the KubernetesCoreCachingAgent.
* perf(kubernetes): Fix all agents handling on-demand requests 
Currently sending an on-demand cache update for a resource that is not namespaced will cause all caching agents to try to handle the update. This can cause a very high load on redis if there are a lot of agents (as might be expected in a large installation of Spinnaker).
Designate one agent to handle requests that are not namespaced instead of having them handled by all agents.
> perf(kubernetes): Fix all agents handling on-demand requests

- clouddriver-google/clouddriver-google.gradle
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgentTest.java
- gradle.properties
I don't know why we I was using these deprecated (and now deleted)
classes in the tests; we don't use them in the actual stateful disk
code. (The test is just making sure we copy statefulPolicy over, so
doesn't really care what is in it.)
> chore(dependencies): upgrade kork

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/refresh/CloudConfigRefreshScheduler.java
When refresh fails, the exception is not logged.  This causes hard to debug issues and more importantly Clouddriver no longer runs the scheduler afterwards.
> fix(cloudconfig): Log errors and continue

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/ReaderConsumer.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
- clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgentTest.java
* refactor(kubernetes): Minor refactor of core caching agent test 
Pull some common logic out of ProcessOnDemandResult so that it can be reused when we need to process the results of a loadData request in an upcoming commit.
* test(kubernetes): Add tests to loadData in core caching agent 
There are no tests of loadData() in the KubernetesCoreCachingAgent; add a simple test that validates a namespaced and cluster-scoped kind can be succesfully cached (ie, is returned from loadData and is persisted to the cache).
* refactor(kubernetes): Immutable collections and nonnull annotations 
Make a few collections returned by the kubernetes caching agent immutable, and add some nonnull annotations that simplify the work of calling code.
* refactor(kubernetes): Split caching of resources by scope …
> fix(kubernetes): Fix all agents caching cluster-scoped resources

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
- clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
- clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
Closes https://github.com/spinnaker/spinnaker/issues/5048
Deck expects Kubernetes V1 accounts to include `dockerRegistries`, so that when it searches for images, it can [filter by the registry configured on that account](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/src/v1/serverGroup/configure/configuration.service.js#L271). I think in one of the account refactors we lost `dockerRegistries` as a `KubernetesNamedAccountCredentials` property so it wasn't being exposed to the `/credentials` endpoint anymore. I handled it the same way we're handling `spinnakerKindMap` (which I think similarly is a property we need exposed as a top level property so it's returned with `/credentials` but is only relevant to one provider version?) but LMK if you see a better way!
> fix(kubernetes): surface dockerRegistries to credentials endpoint

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2SecurityGroup.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesApiVersion.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesApiVersionSpec.groovy
The networking.k8s.io API group is mis-spelled as network.k8s.io; fix this. This bug is preventing security groups from being cached by clouddriver.
We also should accept extensions/v1beta1 as the API group, which can still be returned from clusters running Kubernetes < 1.16.
> fix(kubernetes): Fix mis-spelled API group

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
- Fixes https://github.com/spinnaker/spinnaker/issues/5061
> fix(aws): support for cross-application CLBs with the sql backend

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
We had an upsert security group operation that changed enough rules in a single security group that the generated status was longer than 65,365 characters, lol.
1. Changed the specific status message to truncate to a count after an arbitrary count of ip rule changes.
2. Added protections in the SQL repository (much below the text column max) that will truncate the status before it hits the database, just in case there are other places where this may happen.
> fix(aws): Protect against huge upsert security group operations

- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaService.kt
- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/CompensatingSagaAction.kt
- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaAction.kt
- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaCompletionHandler.kt
- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaExceptionHandler.kt
- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaFlow.kt
- clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/models/Saga.kt
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/TitusException.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.java
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusExceptionHandler.java
- clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/TitusExceptionHandlerSpec.groovy
Rather than scattering the exception catching logic (for determining if something is retryable) all throughout the cloudprovider code, this pattern should help keep things simple.
> feat(saga): Saga exception handler and TitusExceptionHandler implementation

- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNamedCacheFactory.kt
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlCacheConfiguration.kt
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConstraints.kt
- cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlCacheSpec.groovy
- cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlProviderCacheSpec.groovy
This should fix table with names > `sql.constraints.max-table-name-length:64` characters. It works by hashing part of the name. It will hash the `type` first, then if not enough the `type` and the suffix (`_rel`). It will throw an exception if it cannot shorten the name while preserving `cats_v1_<table namespace>`.
Also exposed `MAX_ID_LENGTH` in the configuration class (`sql.constraints.max-id-length:352`).
```
cats_v1_foo => cats_v1_foo
cats_v1_superduper....longname => cats_v1_superduper<hash>
cats_v1_superduper....longname_rel => cats_v1_superduper<hash>_rel
```
Fix for https://github.com/spinnaker/spinnaker/issues/4809
> fix(cats/sql): fix table names with long type names

- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cluster/SqlClusteredAgentScheduler.kt
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlAgentProperties.kt
- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlAgentSchedulerConfiguration.kt
This works in conjunction with the pattern matcher to enable caching agents (which I think is still useful, just not something we should have available to dynamic configuration)
> fix(caching): Config to disable fully qualified caching agents

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesLimitRangeHandler.java
Fixes spinnaker/spinnaker#5139
Deployments containing a limitrange time out waiting for the manifest to appear, as clouddriver is missing the entry for this kind.
Ideally there would be a better way of auto-detecting kinds like this (particularly ones that don't need any custom logic) but for now just adding another Handler to handle this.
> fix(kubernetes): Add missing limitrange kind

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindProperties.java
- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesLimitRangeHandler.java
Manual :cherries: :pick: of #4170 because @spinnakerbot is ghosting me. This applied cleanly so I'm not sure why @spinnakerbot is ignoring me.
Deployments containing a limitrange time out waiting for the manifest to appear, as clouddriver is missing the entry for this kind.
Ideally there would be a better way of auto-detecting kinds like this (particularly ones that don't need any custom logic) but for now just adding another Handler to handle this.
> fix(kubernetes): Add missing limitrange kind (#4170)

- clouddriver-docker/clouddriver-docker.gradle
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
- clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/KeyBasedSorter.java
- clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentialsTest.java
- clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/security/KeyBasedSorterTest.java
Fixes spinnaker/spinnaker#5002.  The second commit is what actually fixes the bug, but I wanted to clean up some of the unsafe groovy and add tests, so this PR is a bit bigger than just that commit.
* test(docker): Add tests on docker registry tag fetching 
There are currently no tests that the fetching of docker registry tags and the sorting of these tags by creation date works properly; add some tests before touching that code.
* fix(docker): Fix sorting array of non-comparable types 
getCreationDate returns an Instant; when the call fails, we're returning a default value as a Date. This means we can end up with an array with a mix of Instant and Date objects, which don't together obey the general Comparable contract.
Fix this by returning an Instant from the catch block; also pull the …
> fix(docker): Fix sorting array of non-comparable types

- clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/artifacts/GcsStorageService.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerProvider.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DualTaskRepository.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/executor/SearchExecutor.java
- clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/ComputeConfiguration.java
- clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/AbstractEnableDisableKubernetesAtomicOperation.groovy
- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
It's a good practice to name all the threads/executors so that it's easy to see what threads are running away (if any).
Add NamedThreadFactory to all places we create a new executor
> fix(thread): make sure to provide NamedThreadFactory to all executors

- clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
We are leaking an executor (with a single thread in) from the TitusStreamingAgent because it's not shutdown properly
I think it would be better to refactor this code to not create the executor (at least not all the time), but I want to make a minimal change to address the immediate problem first.
There is also some unnamed thread pool that appears to be leaking that I can't track down. Perhaps it's some API that the streaming agent calls, will debug it more after this change goes in
> fix(titus): shutdown the executor for titus streaming agent

- .mergify.yml
We can click the button to merge anyway, so this just makes maintenance life a bit easier. Thoughts?
> feat(mergify): Allow OSS approvers to auto-submit without review

- cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
Currently agent tables are only created when there are resources to insert
however these tables are queried regardless which results in a large number
of 'Table doesnt exist' errors.  This change creates the table even if
there are no corresponding resources to cache.
> fix(cats/sql): ensure cache agent tables exist when using sql backend

- clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/ivy/IvyArtifactCredentialsTest.java
- clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/maven/MavenArtifactCredentialsTest.java
- clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtilSpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
The all-arg and no-arg constructors for Artifact were deprecated in spinnaker/kork#429. Replace their usages with a builder.
> refactor(artifacts): Use builder to create artifacts

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/provider/view/KubernetesV2JobProvider.java
Noticed this misspelling today, couldn't pass up the opportunity to contribute.
> fix(kubernetes): correct spelling in error message

- clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
- clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesManifestSpec.groovy
- clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/crd-manifest-spec.json
- clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/crd-manifest.json
Currently a CRDs from Istio kind expect a string as value of spec.template instead of a map, this cause an error in clouddriver at the moment to cast from object to map to get the annotations inside spec.template.
Issue: https://github.com/spinnaker/spinnaker/issues/4664
Example manifest: https://github.com/signalfx/signalfx-istio-adapter/blob/master/resources/metric-instances.yaml
Reference: https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Instance
> fix(provider/kubernetes): validate spec.template is a map before cast

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DefaultTask.groovy
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/Task.java
- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTask.groovy
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTask.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/TaskMapper.kt
So we don't add duplicate SagaIds to tasks (and thereby double the number of atomic operations we retry), use a Set instead of a List.
> fix(sagas): Use a Set instead of List to avoid duplicate Task SagaIds

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperation.java
- clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperationSpec.groovy
If no RoleARN is provided via Deck or in a templated pipeline, the
creation/updating of stacks fails, as en empty value is not allowed by
the AWS API. This patch handles this case by including this field
into the API call only when it's a non-empty string.
> fix(cfn): do not add roleARN if empty or null

- clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.java
Adding a null check for Kubernetes provider health check.
There's a case during startup when the `warningMessages` map has not been initialized and health endpoint is called, leading to a `NullPointerException`.
Since `warningMessages` is an AtomicReference being changed every 5 minutes, it makes sense to put the null check where the map is being retrieved.
> fix(kubernetes): Null check in health endpoint to avoid NPE

- clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
- clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/exceptions/DuplicateEventAggregateException.kt
- clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventRepository.kt
We experienced an issue with sagas where Orca submitted the same operation into clouddriver at the same time (separated by a few milliseconds). The second request returned a 500 due to the SQL integrity constraint violation, but the work was already being handled successfully by the other clouddriver instance.
What _should_ happen is that the second instance returns a pointer to the original task so that Orca doesn't have to reason about its mistake and just carry on monitoring the operation that's being performed.
Also changed the duration that Kato Tasks are kept around. 1 hour is too short to be able to get notified of an error and to diagnose. 4 days seems a reasonable default so that if an error occurs EOW or on the weekend, there's still sufficient time to get information the …
> fix(saga): Handle concurrency issue when same op is sent more than once

- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
- clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoader.java
This is a fix for the issue - [#5155](https://github.com/spinnaker/spinnaker/issues/5155)
Updated CredentialConfig class to include the accessKeyId and secretAccessKey when the aws configuration is provided via external sources like Git.
Updated CredentialsLoader class to set the above credentials as system properties.
> fix(provider/aws): updated clouddriver to accept aws credentials from external sources.
