spinnaker/clouddriver

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/model/ContainerLog.java
clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesV1InstanceProvider.groovy
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProvider.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProviderTest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/model/ContainerLog.java

@maggieneterval @ethanfrogers I've gone ahead and made the changes @maggieneterval  and I discussed yesterday. Let me know what you think.
This is the first step that partially implements https://github.com/spinnaker/spinnaker/issues/4869 by adding initContainer logs to the existing logs being returned. We add all the initContainer logs before the current container logs so they'll show up in deck with initContainers to the left of the existing ones (screenshot in issue). Differentiating the different types of containers in the gui will come in a later PR for clouddriver and deck.
This also handles the refactoring mentioned by @maggieneterval on the issue. I ended up leaving the current ContainerLogs where it was in core and deprecating since the v1 provider was using it, and I opted to …

feat(kubernetes): add initContainer logs to kubernetes v2 provider container logs

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandlerSpec.groovy
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandlerTest.java
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/daemonsetbase.json

Fixes spinnaker/spinnaker#5283.
* test(kubernetes): Add tests to stateful/daemon set stability 
The next commit will fix bugs in the stateful set and daemon set stability conditions. Add tests to cover the cases that will be fixed; in the case of the daemon set handler, there were no existing tests so this commit adds some basic tests in addition to tests of the bug that will be fixed.
This commit also does some minor cleanup on the stateful set tests, removing some unused variables and referring to member variables by their name instead of via their groovy-generated accessors.
* fix(kubernetes): Fix stability for stateful/daemon set 
When scaling a stateful set down to zero replicas, we never consider the stateful set stable. This is because the status field for a stateful set with no …

fix(kubernetes): Fix stability for stateful/daemon set

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/LoadFront50App.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/SnapshotAtomicOperationInput.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/StatefullyUpdateBootImageAtomicOperation.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/AttachTitusServiceLoadBalancers.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/CopyTitusServiceScalingPolicies.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/PrepareTitusDeploy.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/SubmitTitusJob.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployCompletionHandler.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusExceptionHandler.java

While working with @sgarlick987 on https://github.com/spinnaker/clouddriver/pull/4235, he pointed out that there is a mix of `javax` and `jetbrains` `Nonnull` and `Nullable` annotations in Clouddriver, so it's unclear which is preferred. This change removes all `jetbrains.annotations` in favor of `javax`.

chore(core): standardize on javax nonnull and nullable annotations

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/AppengineJobExecutor.groovy

Without this change, executions that fail while emitting only stderr output, but not stdout output, would be considered successes and the stderr output would be squashed.

fix(appengine): Propagate gcloud failures from job executor to task.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java

fix(cf): remove cf secondary cache expiry to prevent expensive api calls

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2SecurityGroup.java

Closes https://github.com/spinnaker/spinnaker/issues/5284
It is valid to submit a `NetworkPolicy` manifest whose ingress or egress port objects (`V1NetworkPolicyPort` as described by the Kubernetes Java client) have a null `protocol` or `port`. This change prevents NPEs when `port` is null.
When we [upgrade the Java client library](https://github.com/spinnaker/spinnaker/issues/5291), we will be able to audit our other non-null assumptions because it appears that the maintainers have added `Nullable`s to Kubernetes resource properties.

fix(kubernetes): permit null properties of NetworkPolicy PortRules

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgent.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgentTest.java

Fixes spinnaker/spinnaker#5274.
There is currently no caching agent that is authoritative for kubernetes artifacts; this is causing them to fail to be cached by the SQL provider (which strictly enforces that only caching agents can only write types for which they are authoritative).
The KubernetesCoreCachingAgent should be authoritative for artifacts, just as it is for other logical kinds (clusters and applications).

fix(kubernetes): Core caching agent is authoritative for artifacts

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProvider.java

Fixes potential NPE introduced by https://github.com/spinnaker/clouddriver/pull/4235
- `spec.initContainers` defaults to null, not an empty list. Do not throw NPE when no `initContainers` are configured.
- Once https://github.com/spinnaker/clouddriver/pull/4250 is merged, we will get IDE warnings for these nullable properties :smile: 
cc @sgarlick987

fix(kubernetes): do not throw NPE when no initContainers

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/Keys.java

Closes https://github.com/spinnaker/spinnaker/issues/5068
Deck expects each security group returned from `/search` to have a `provider`, `cloudProvider`, or `type` field corresponding to the correct cloud provider in order to render them in the Firewalls tab. [This commit](https://github.com/spinnaker/clouddriver/pull/3826/commits/0331e1f9e03100ad0b72662b724e72fdecd27287) changed the `provider` property of `CacheKey` from "kubernetes" to "kubernetes.v2" (Deck expects it to be "kubernetes"). It also removed `provider`'s getter (this was being generated by `@Data` on `CacheKey` before it was removed) and made it static, so we were no longer deserializing it when returning `/search` results from the cache.

fix(kubernetes): return provider field with kubernetes /search results

---

clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

A few tests are implicitly using the all-arg Artifact constructor, which is being made private. These tests were relying on groovy's automatic return value casting to cast a mock return value from a map to an artifact. The automatic casing was relying on the all-args constructor, which has been removed.  The fix is to construct the artifact directly using the builder.

fix(artifacts): Replace implicit use of all-args Artifact constructor

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgent.kt
cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgentTest.kt

Related to https://github.com/spinnaker/spinnaker/issues/4803
Kubernetes caching agents can be authoritative for resource types for which there are zero instantiated resources. For example, I can register a CRD to a cluster that I never instantiate, and a caching agent will become authoritative for that type but a SQL table will never be created for it. We should ensure a table exists before scanning it for entries to clean up.

fix(sql): SqlUnknownAgentCleanupAgent should not throw errors on nonexistent tables

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCleanupStaleOnDemandCachesAgent.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlTableMetricsAgent.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgent.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlCacheConfiguration.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlAgent.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgent.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt

A recent refactor to get other SQL agents to wire up caused this agent to be missed.

fix(sql): Ensure SqlEventCleanupAgent is scheduled

---

cats/cats-core/cats-core.gradle
cats/cats-core/src/main/java/com/netflix/spinnaker/cats/agent/DefaultAgentScheduler.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/artifacts/GcsStorageService.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/InstanceTerminationLifecycleWorkerProvider.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DualTaskRepository.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/refresh/CloudConfigRefreshScheduler.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueue.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/executor/SearchExecutor.java
clouddriver-google/clouddriver-google.gradle
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/ComputeConfiguration.java
clouddriver-kubernetes-v1/clouddriver-kubernetes-v1.gradle
clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/KubernetesV1ProviderSynchronizable.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizable.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java

[`ThreadFactoryBuilder`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/ThreadFactoryBuilder.html) supports named threads, but also has additional options that we may want to use in the future. I think guiding people towards that is preferred...

chore(kork): use Guava's ThreadFactoryBuilder instead of NamedThreadFactory

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cluster/SqlClusteredAgentScheduler.kt
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy

The prior commit missed a few places where we use NamedThreadFactory; fix these.

chore(kork): use ThreadFactoryBuilder instead of NamedThreadFactory

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/AbstractEnableDisableInstanceDiscoveryAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DisableAsgAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/EnableDisableAtomicOperationUnitSpecSupport.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/EnableDisableInstancesInDiscoveryAtomicOperationUnitSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/Status.groovy
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy

There already are a lot of special cases in this class, but marking the task as failed can have pretty bad consequences like failing entire deploy stages and pipelines, triggering rollbacks, etc. If the stars are really poorly aligned and we do get 10 failures (timeouts, 404s, 503s...) I think the kato task should still be considered a success, allowing orca to proceed to the next steps (most likely waiting for down instances) which have a chance of succeeding.

fix(eureka): make non-404 error codes non fatal on disable ops

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesAccountResolver.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2AbstractManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2SearchProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesIngressHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesNetworkPolicyHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/GlobalKubernetesKindRegistry.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesKindRegistry.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/config/KubernetesV2Configuration.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizableSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesAccountResolverSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/GlobalKubernetesKindRegistrySpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesKindRegistrySpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCoreCachingAgentTest.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2InstanceProviderTest.java

* refactor(kubernetes): Move a few classes to better packages 
KubernetesV2SearchProvider should be in the same package as all the other Kubernetes providers; move it there.
KubernetesAccountResolver is really just a helper class for the classes in .*kubernetes.v2.caching.view.provider; move it there so it can be made package-private and only visible to those classes.
GlobalKubernetesKindRegistry is closely associated with the account credentials and should live in the same package (as the account-specific kind registry does).
* refactor(kubernetes): Remove CacheUtils from handlers 
The hydrateSearchResult function in all the kubernetes handlers accepts a KubernetesCacheUtils, but never uses it. Remove the unneeded parameter from these functions.
* refactor(kubernetes): Make classes …

refactor(kubernetes): Move a few classes to better packages

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCacheSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy

**PR 2 of 2** to partially address https://github.com/spinnaker/spinnaker/issues/4495
* this PR includes changes from https://github.com/spinnaker/clouddriver/pull/4274 and should be reviewed/merged **after** that one is approved.
Purpose of the change was to reduce calls to `elasticloadbalancing:DescribeTargetHealth` from per-task to per-targetGroup. The below examples were run against Spinnaker instances running 1 ECS service with ~10 tasks each. 
NOTE: the reduction seen depends on the makeup of the account - many services running fewer tasks will see less improvement than accounts running fewer services with many tasks each.
Logs show call count reduced to about 1/3 of what's currently observed.
EX: Number of `DescribeTargetHealth` calls made by Spinnaker instance running `master`: …

feat(ecs): Refactor TaskHealthCachingAgent to use TargetHealthCache

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/DualTaskRepositoryConfiguration.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/DualTaskRepository.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/data/task/DualTaskRepositorySpec.groovy
clouddriver-sql-mysql/mysql-setup.sql
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
clouddriver-sql/src/test/java/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepositoryTest.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

Adds functionality to point task repository to two DBs (e.g. for migration).
* Add configurable pool name for secondary repo, and ability to look up repo by name instead of class
* Make sure to dedupe the task results in case prior repo and new repo have the same task (e.g. DNS entries point to the same DB)
* Also, sagas are deliberately not migrated (for now), restarting a task whose saga is not in the primary repo will fail
See This would be configured as follows:
```yaml
sql:
connectionPools:
default:
default: true
user: clouddriver_service
jdbcUrl: jdbc:mysql://${sql.secondaryBaseUrl}/clouddriver
tasks:
user: clouddriver_service
jdbcUrl: jdbc:mysql://${sql.secondaryBaseUrl}/clouddriver
tasksPrevious:
user: clouddriver_service
jdbcUrl: jdbc:mysql://${sql.readOnlyBaseUrl}/clouddriver …
```

feat(dual SQL DB): Allow task repository to connect to two SQL instances

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesAccountResolver.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2AbstractManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestBuilder.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesAccountResolverSpec.groovy

This is primarily to make the code simpler, but may help a bit with performance as it will stop us from continually looking up an account from the registry inside of loops; instead we'll get the account outside of the loop and use it as needed inside the loop.
I promise there is actually a bug fix at the end of these refactor PRs, these are just cleaning things up before I apply the fix (and will make the fix easier).
* refactor(kubernetes): Remove isAccountRelevant and makesLiveCalls 
Both implementations of KubernetesV2AbstractManifestProvider separately call isAccountRelevant and makesLiveCalls to determine if an account exists. This duplicates work and also adds an unnecessary layer of indirection; instead juts have them get the optional account and ask the account (if present) …

refactor(kubernetes): Clean up some account resolving code

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTask.kt

I'm not totally sure this will fix the issue we're seeing where the `Re-initializing` message sometimes gets added multiple times, but this is a bug anyhow.

fix(sql): Mark task as dirty on retry() invocation

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy

We see an issue where whenever you create an ALB we will actually fail in edda because we try to get the updated details of the ALB
from both the ALB and the non-ALB list.
Don't try to fetch an ALB from regular LBs (this is symmetric to what ALB caching agent does)

fix(ALB): Don't try to fetch LB when ALB is requested

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/validator/KubernetesValidationUtil.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy

Fixes spinnaker/spinnaker#4645.
* test(kubernetes): Fix some tests on kind status 
The prior PR made isValidKind private, leaving only getKindStatus exposed. Change the tests to exercise the public method rather than the private one.
* fix(kubernetes): Allow deploying a CRD and object in same manifest 
Currently a multi-manifest that deploys a CRD and an object referencing that CRD will fail, because we validate that all objects are of a kind that exists in the cluster, but the CRD won't exist until the manifest is deployed.
Let's fix this by adding a kind status UNKNOWN, which means that Spinnaker does not know about this kind (and can't find it in the cluster's CRDs) and allow deploying manifests whose kind has this status.

fix(kubernetes): Allow deploying a CRD and object in same manifest

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizable.java

Similar to https://github.com/spinnaker/clouddriver/pull/4297 but limited to not losing the memoized values. It will only address dynamic accounts becoming unreachable.

fix(kubernetes): On refresh, don't replace credentials that have not changed

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Routes.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizer.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/RoutesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizerTest.java

Creating a cache entry for one CF app requires 5 distinct HTTP calls to the CF API which adds up quickly when there's thousands of apps to process. The change takes advantage of Java's parallelStream and OKHttp's thread safety/connection pool management.
A better solution will be to use the CF-java client which is fully reactive and will allow to better configure the parameters of what's being done in parallel; but that's a non trivial refactor compared to the current change.

fix(cf): Parallelize apps/lbs cache building

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/SubmitTitusJob.java

- Adding `RESOURCE_EXHAUSTED` to the set to retryable status code to help with rate limiting issue.

fix(titus): Add retry on titus resource_exhausted error

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy

- Looks like for some reason this was how the beans were getting loaded and hitting a circular dependency , adding @lazy in `AmazonLoadBalancerProvide` in an attempt to fix it.
`TitusTargetGroupServerGroupProvider` -> `AwsLookupUtil` -> `AmazonLoadBalancerProvider` -> `TitusTargetGroupServerGroupProvider`

fix(titus): Attempt to fix circular dependency

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/model/Manifest.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesCronJobHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/UnstableReason.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandlerTest.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandlerTest.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandlerTest.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandlerTest.java
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/statefulset/partitioned-rollout-complete.yml

* test(kubernetes): Fix observed generation in stateful set test 
One of the stateful set tests incorrectly had the observed generation newer than the metadata one; fix this.
* fix(kubernetes): Replace null status with false 
When the observed generation in the status does not match the object's generation, we set the stable and failed conditions to null. This should not be treated any differently than if the status generation did match but the object had not fully rolled out---it just means we need to wait a bit longer to see the new status.
The recent changes to orca have explicitly made it so that from orca's perspective there is no different beteween stable/failed being null and stable/failed being false. Make things more clear (and null-safe) by removing the ability to null these …

fix(kubernetes): Move generation checks to be object-specific

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusTargetGroupServerGroupProvider.java

- Removing unused bean dependency to avoid bean initialization.

fix(misc): Remove unused bean instance from autowiring

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java

- Add `spinnakerAccount` to filters , This should help fix duplicate cache entries when same titus accounts are mapped to different aws accounts

fix(titus): Update filters for observeJob

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/RetrofitConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/exceptions/SpinnakerHttpException.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/exceptions/SpinnakerNetworkException.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/exceptions/SpinnakerRetrofitErrorHandler.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/exceptions/SpinnakerServerException.java

Users are frequently frustrated by generic `RetrofitErrors` surfaced in pipeline execution details in the UI. A `RetrofitError`'s message is not surfaced when the error was thrown in a microservice more than one network call from the Orca task in which it originated. For example:
- An Orca task that calls out to Rosco, in which Rosco throws an exception, successfully surfaces the exception's message because Orca's `RetrofitExceptionHandler` [parses the RetrofitException.Response's `body.message`](https://github.com/spinnaker/orca/blob/master/orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandler.groovy#L50).
- However, if the same Orca task calls out to Rosco, which calls out to Clouddriver, and Clouddriver throws an exception, we can no …

feat(core): add SpinnakerRetrofitErrorHandler

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java

Fixes https://github.com/spinnaker/spinnaker/issues/5444.
Empty `serviceDiscoveryAssociations` items are now validated and msg'd:

fix(ecs): Add null check for empty serviceDiscoveryAssociation

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/BaseHttpArtifactCredentials.java

The OkHttpClient warns about connection leak when an artifact download is
unsuccessful, since the connection is not closed in that case.
Reading the body closes the connection, and thus it doesn't trigger in the
successful cases.

fix(artifacts): Close OkHttpClient on failures

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Spinnaker infers the role to pass to ECS when creating services with load balancers. Previously, if you had a load balancer, it would pass the inferred role (SpinnakerManaged) vs using the Service Linked Role (which is required by ECS to interact with multiple load balancers using bridge mode). 
Testing Performed:
- Manually reproduce the error.
- After deploying the change, I was successfully able to deploy a service with multiple target groups associated to it using EC2 with Bridge network mode.
Fixes: https://github.com/spinnaker/spinnaker/issues/5412

fix(ecs): only add service role to create request if there is one lb

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy

- updated to now handle listener policies earlier in the operation
- fixed a bug where if a call to drop a listener failed,
the load balancer is left in a dirty state

fix(aws): Fixing CLBs listener policies getting dropped on upsert

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/CloudFoundryApiException.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgentTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsSynchronizerTest.java

* fix(cf): Skip caching CF apps having frigga incompatible names
* fix(cf): Stop swallowing exception causes.
Makes for deeper and informative stack traces.
* fix(cf): Race condition causing NPE getting token in the HTTP Client.
Was happening at startup when both the LoadBalancer and Application caching agents were first ran and shared the same client.
* fix(cf): NPE after on-demand cache refresh run
An on-demand cache refresh creates an ON_DEMAND cache entry that never been processed so the `processedCount` was null instead of 0 and the scheduled cache agent wasn't expecting that.
* fix(cf): Adjusted log verbosity level
* fix(cf): Re-enabling cache eviction of a serverGroup on-demand
When not found, a serverGroup wouldn't be evicted from the cache upon an on-demand request.
* fix(cf): …

fix(cf): Improved caching agent robustness

---

clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy

sun.misc.BASE64Decoder was removed in JDK 9 in favor of java.util.Base64.
JDK 8+ contains java.util.Base64, as such this remains backward compatible
with JDK 8.

fix(docker/test): Switch to java.util.Base64

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy

Fixes "could not find matching constructor" error introduced in https://github.com/spinnaker/clouddriver/pull/4336

fix(aws): add .get() to optional known to be present

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy

_Issue_ : 
Some SG's ingress rules were added manually via console with description , this makes the groovy list diff to produce rules that differ only in description , resulting in failures while calling `authorizeSecurityGroupIngress` due to duplicate rule violation.
_Fix:_
Use the same diff approach used for `IPRange` rules #4300

fix(aws): Handle SG upsert with description object already present in console

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java
clouddriver-kubernetes-v1/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/KubernetesV1ProviderSynchronizableSpec.groovy
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java

Related to: https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md
- **feat(kubernetes): log v1 warning on KubernetesV1Credentials initialization**
The goal of this commit is to provide a warning on startup for any Spinnaker operators with Kubernetes V1 accounts. Although we're already providing a [warning](https://github.com/spinnaker/halyard/commit/835dcfdfa5a2ffbed45921488064d4d9367b5d1b) on `hal deploy apply` when one or more V1 accounts are configured, not everyone deploys Spinnaker with Halyard, and perhaps some operators are more likely to tail the Clouddriver logs on startup than they are to pay attention to Halyard validation warnings.
- **feat(kubernetes): default accounts with unspecified providerVersion to V2**
We are already …

feat(kubernetes): prepare for upcoming removal of V1 provider

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/ResizeServiceAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Closes https://github.com/spinnaker/spinnaker/issues/5465
This change could mean that ECS deployments fail on upgrade to Spinnaker 1.19 due to missing service-linked roles in the AWS account.  This can be fixed by running:
```
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com
aws iam create-service-linked-role --aws-service-name ecs.application-autoscaling.amazonaws.com
```

feat(ecs): require service-linked roles for ECS and autoscaling

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

A bug in the unit tests caused the check for the legacy target group setting to be flipped
When the server group has the legacy settings:
```
"containerPort": 80,
"targetGroup": "spinnaker-ecs-ec2-demo-tg",
```
Then the deployment will currently fail with the error message:
```
The container v002 did not have a container port 80 defined. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 93dc346b-02e8-4ded-a651-b452e44736c6)
```
cc @pkandasamy91

fix(ecs): provide port mappings if legacy target group setting is set

---

clouddriver-kubernetes-v1/clouddriver-kubernetes-v1.gradle

This also changes the organization from fge to java-json-tools, as the former is retired. Avoids v1.9's references to Guava and Jackson Databind versions with known CVEs. Addresses spinnaker/spinnaker#5525

fix(clouddriver-kubernetes-v1): Update json-patch to v1.12

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/RebootInstancesAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/TerminateInstancesAtomicOperationConverter.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonInstance.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy

previous commit renamed .any to .extraAttributes to avoid name collision with GroovyDefaultObject methods but
missed a spot on AmazonLoadBalancerProvider and missed an occurrence of .any on AmazonInstance

fix(model): fix reference to renamed property and remove overridden .any on AmazonInstance

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/job/CloudFoundryJobProvider.java

if cloud foundry is enabled, this job provider breaks run job for all
other cloud providers because of the exception thrown in
getFileContents. other cloud providers simply return null if this method
isn't implemented. this whole area could probably use a refactored.
currently, every job provider is queried regardless of whether or not
the account is for that cloud provider.

fix(cloudFoundry): fix cloudFoundry job provider

---

clouddriver-web/config/clouddriver.yml
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy
halconfig/README.md
halconfig/clouddriver-bootstrap.yml
halconfig/clouddriver-caching.yml
halconfig/clouddriver-ro-deck.yml
halconfig/clouddriver-ro.yml
halconfig/clouddriver-rw.yml
halconfig/clouddriver.yml

Halyard had a pattern of generating its own base default config for each service, and then concatenating it to the generated config for the service.  This pattern is problematic for a few reasons:
* It just uses string concatenation to merge the base config with its generated config, which can (and has) led to errors when there are [duplicate values](https://github.com/spinnaker/halyard/pull/1314).
* Halyard needs to figure out how to get the version of the base hal config that corresponds to the version of clouddriver it's deploying, which led to a fairly complex system of uploading the contents of the `halconfig` directory to a GCS bucket each time to build an image, and having halyard pull down the corresponding files each time it does a deploy.
* We end up with diverging defaults, …

refactor(core): Push halyard defaults into base config defaults

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonInstance.groovy

`any()` was renamed to `getExtraAttributes()` in #4375, but this call site was missed. This was causing failures in the E2E tests.

fix(aws): fix `AmazonInstance#getZone`

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTask.groovy
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/data/task/jedis/JedisTaskTest.java
clouddriver-core/src/test/resources/com/netflix/spinnaker/clouddriver/data/task/jedis/task.json

* test(repository): Add tests to JedisTask 
Before making a minor change to JedisTask, add some tests of the serialization logic.
* fix(repository): Enforce serialization order for JedisTask 
There have been a number of end-to-end test failures recently due to race conditions where orca fetches a task status from clouddriver and receives a status of complete, but incomplete task results.
The fields of the task are computed on-demand by querying the repository. This means that the serialized task may not be internally consistent; each field will reflect the state of the task in the repository at the time that field's accessor was called during serialization.
This is in general a difficult problem to solve with redis, which does not support atomic reads of multiple keys, but has been solved …

fix(repository): Enforce serialization order for JedisTask

---

clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
clouddriver-elasticsearch/elasticsearch_index_template.json
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/config/ElasticSearchConfigProperties.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy

This change follows up on the change https://github.com/spinnaker/clouddriver/pull/2913.
* Remove ES2.x support - now all docs using mapping type `_doc` recommended by ES6 and only one is allowed.
* Change the queries to use `entityRef.entityType` instead of the document type.
* Fixup ES template to not use `not_analyzed` but instead use `keyword` (with exception of `entityRef.entityType` which we wildcard query)
* Adding an `id` field to the document because the built-in `_id` field is no longer wildcard queryable
* Changing to use a container for the unittests

fix(elasticsearch): Upgrading to ElasticSearch 6 for entity tags

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/Keys.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy

EntityTag reconciliation process gets all server groups from the provider and matches them against the existing entity tags.
Titus returns keys in the form
```
titus:servergroups:v2:<application>:...
```
while the tags are stored in the form
```
titus:servergroups:<application>:...
```
This change removes the schema key (`v1` or `v2`) from the key IDs that are returned. This API (`getServerGroupIdentifiers`) is only used by the tag reconciler

fix(titus/entitytags): remove schema version from key returned by TitusClusterProvider

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.groovy
clouddriver-web/config/clouddriver.yml

As @ezimanyi described in [this PR](https://github.com/spinnaker/clouddriver/pull/4368), we would like to push reasonable microservice-specific defaults (currently set by Halyard) to each microservice's config or code instead of specifying them in [Kleat](https://github.com/spinnaker/governance/blob/master/rfc/halyard-lite.md).
* feat(appengine): default Appengine `localRepositoryDirectory` to [Halyard default](https://github.com/spinnaker/halyard/blob/master/halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java#L51).
* feat(aws): replace AWS default `iamRole` with [Halyard default](https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/ …

feat(config): move Halyard defaults to Clouddriver

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgent.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskCleanupAgent.kt

There were a few places where we use string concatenation instead of using first class jooq constructs for interacting with SQL.
Using jooq gives us proper sql escaping and it's also easier to read

fix(sql): use jooq constructs instead of string concatenations

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java
clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProviderSpec.groovy

In cases where the tag ID has illegal url character we need to encode.
Not sure why it worked in Jest2 and not in Jest6 - will figure this out separately.

fix(elasticsearch): URL encode the ID

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TargetHealthCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TargetHealthCachingAgentSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/CommonCachingAgent.java

Fixes https://github.com/spinnaker/spinnaker/issues/5574
Before change: reproduced errors in env with mulitple AWS accounts configured in same region
```
com.netflix.spinnaker.clouddriver.ecs.provider.EcsProvider:ecs-my-aws-devel-acct/us-east-1/TargetHealthCachingAgent completed with one or more failures
com.amazonaws.services.elasticloadbalancingv2.model.AmazonElasticLoadBalancingException: 'arn:aws:elasticloadbalancing:us-east-1:ACCOUNT:targetgroup/nlb-targetGroup/7e540bba02fc1ac2' is not a valid target group ARN (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ValidationError; Request ID: ...)
```
After: no such errors found in clouddriver.log 🎉

fix(ecs): Correctly scope TargetHealthCachingAgent describe calls

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Task.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstanceSpec.groovy

The Titus API does not expose IPv6 addresses yet. In the meantime, accessing the task's `agent.instanceId` enables a secondary lookup of the network interfaces so we can obtain the IPv6 address(es). 
This workaround is necessary for some other work around IPv6 support. In the future, the Titus API will be updated and we can directly replace the `agentId` with `ipv6Addresses` from Titus.

fix(titus/instance): Temporarily expose agentId to access IPv6

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiAdapter.groovy

The patchNamespacedStatefulSet is passing force=false; the Kubernetes API server doesn't allow this flag to be present at all for non-apply patch operations, which is causing a server-side failure.
This only breaks on clusters >=1.14 as the flag was not present before. (I'm not sure if the client library was detecting the old version of the cluster and removing the flag before calling the API, or if the API was just ignoring the unknown flag, but either way the flag had no effect.)

fix(kubernetes/v1): Don't pass force flag to patch operation

---

clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-docker/clouddriver-docker.gradle

remove CVE-2019-12402. Upgrade following libraries:
- commons-compress
- org.eclipse.jgit
- org.eclipse.jgit.archive

chore(dependencies): resolve CVEs issues

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy

The original code will not finish deployment and will eventually time out, in spite of task being successfully deployed by ECS and running (https://github.com/spinnaker/spinnaker/issues/5544)
"containers": [
{
"networkBindings": [],
"networkInterfaces": [],
},
{
"lastStatus": "RUNNING",
"networkBindings": [
{
"bindIP": "0.0.0.0",
"containerPort": 8080,
"hostPort": 32773,
"protocol": "tcp"
}
}]

fix (ecs): Unstable deployments for task definitions with more than one container (#5544)

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java

Closes spinnaker/spinnaker#5585.
When we encounter a description that should have application restrictions but doesn't, we log a warning including the full description JSON. In some cases (ex: Kubernetes) this description may contain sensitive information that ideally wouldn't be logged.
Ideally really sensitive values would come from artifacts so they aren't in the pipeline JSON at all, but let's nonetheless cut back on how much we are logging here to reduce the chance of sensitive information ending up in the logs.
In particular, it's not clear how much the full description would help in debugging, as generally what is important is the class of the description (to check whether it implements ApplicationNameable or ResourcesNameable) and and the account, both of which will still be …

fix(core): Only log relevant details of description

---

.mergify.yml

Mergify is not working on the release branches because it requires the Github actions build to return success, but we only switched to using Github actions after cutting the 1.19 branch.
To remedy this, add another rule that allows merging if Travis CI passes on a branch.  (There's no way to make an OR condition within a rule, so we need to add another rule.) This way, we'll merge if either Github actions or Travis CI reports success.  Once the branches running Travis are no longer maintained (when Spinnaker 1.23 is released) we can delete this rule.

chore(mergify): Allow Travis success on release branches

---

.mergify.yml

The comment was incorrect; depending on the repo, there are a few
branches that use both Travis and Github actions. Also, this comment
matches what I put in all the other repos, so this makes the
mergify config here identical to the other ones, which makes things
easier for bulk changes.

chore(mergify): Update mergify comment

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/KubernetesKindAtomicOperationDescription.groovy
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesAtomicOperationDescription.java

Closes spinnaker/spinnaker#5617.
Kubernetes V2 operations don't expose the applications to which they apply, but don't override the default requiresApplicationRestriction. This causes a log warning on every operation, as the authorizer is expecting to be able to look up the applications relevant to the operation to perform authorization checks.
The choice here would be either to udpate all the operations to expose the relevant accounts (effectively building this feature that was never built for Kubernetes V2) or to toggle the requiresApplicationRestriction flag to indicate to the authorizer to stop trying to find the relevant applications.
After discussion at the Kubernetes SIG, we decided at this point not to implement application authorization (though may revisit if people find use …

fix(kubernetes): Application restrictions disabled for V2

---

clouddriver-event/src/main/kotlin/com/netflix/spinnaker/clouddriver/event/config/MemoryEventRepositoryConfig.kt

On February 19th we rolled out a CloudDriver deploy and our EventRepository switched from SQL to in-memory - I can't find any change that would have caused this.  I'd like to give this a shot and see if this resolves the issue.  I'm unable to reproduce the issue locally, even when running with the exact same spring profiles as our production cluster which is odd.

fix(saga): Move ConditionalOnMissingBean for EventRepository to eventRepository factory method

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesPodMetric.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/MetricParser.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsSpec.groovy
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesPodMetricTest.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutorTest.java
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/pod-metric-extra-property.json
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/pod-metric.json
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/top-pod.txt

* test(kubernetes): Add some tests to metric fetching logic
Before making a few changes to the call to get pod metrics, add some tests around this to ensure the changes don't break existing functionality.
* refactor(kubernetes): Clean up metrics code
This started out just trying to remove the noisy log statement
"No output from `kubectl top` command, no metrics to report", which is logged with severity warn any time we cache an empty namespace. There's no need to log this as it's a perfectly normal situation; we asked for pod metrics and there were none.
But then I noticed some things that could be cleaned up a bit 😄. So this PR does the following:
* Extracts the logic to parse the output of kubectl top out of the already large job executor class and into a helper class
* Replaces use of …

refactor(kubernetes): Clean up metrics code

---

.github/workflows/build.yml

These builds will always fail because the secrets don't exist there, but
even if they did exist, we wouldn't want to publish a release from a fork.
Sending this to make sure it looks okay before I put it in 16 other
repositories.

chore(gha): don't run the GHA build when pushing to a fork

---

clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/config/SagaAutoConfiguration.kt
clouddriver-saga/src/test/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaSystemTest.kt
clouddriver-saga/src/test/kotlin/com/netflix/spinnaker/clouddriver/saga/examples/SpringExampleTest.kt

Before I muck around with `@Order` I'd like to give this a shot as it seems like the cleanest solution to me.  This should let us specify the bean we want via config (ie, if `sql.enabled` is `true`).

fix(saga): Remove import of EventSourceAutoConfiguration on SagaAutoConfiguration

---

clouddriver-web/config/clouddriver.yml
halconfig/clouddriver.yml

* refactor(core): Move some things back to halyard config
In a recent PR I moved the server.port and server.address settings into the base config to reduce what's in the Halyard config.
After further reflection, we don't want these to be overridable easily in kleat anyway as I don't think there's a common use case for this.  (And in any case, it's easier to override this by just overriding these in the clouddriver-local.yml than to need to go through the services.* settings in spinnaker.yml.)
So let's avoid bringing these settings along for the ride, and just leave them in the halconfig where they will still help halyard users. This restores this block of clouddriver.yml to what it was before the recent change.
* feat(config): Add ro and rw profiles
In order to make it easier to configure …

feat(config): Add ro and rw profiles

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/ReconcileClassicLinkSecurityGroupsAgentSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupManagerController.java
gradle.properties

Additional differences:
1. The `Dockerfile.compile` is using Ubuntu instead of Alpine. Gradle downloads a `protoc` from Maven that is built against glibc. Alpine uses musl libc, so the downloaded `protoc` won't run. We need a glibc-based distro.
For consistency, I may backport this change to the other five services I've already updated. I can't decide :/
2. Add `--no-daemon` to the `Dockerfile.compile` for consistency and because otherwise setting `-Xmx` in `GRADLE_OPTS` doesn't do anything useful.
3. `ServerGroupManagerController.java` had to be changed a little because of some tweaks to the type inference in Java 11. I honestly don't understand why the old code wouldn't compile, but this new code is better anyway.
4. `ReconcileClassicLinkSecurityGroupsAgentSpec` had to be changed …

chore(java11): Compile with Java 11 (but targeting Java 8)

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestStrategy.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/artifact/KubernetesCleanupArtifactsOperation.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanDeploy.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifestStrategyTest.java

We have a class KubernetesManifestStrategy to represent how to deploy a manifest, but it doesn't encapsulate itself well and pushes a lot of logic into callers.
Make the following changes:
* Move the logic for creating this KubernetesManifestStrategy object from annotations into the KubernetesManifestStrategy class; this allows us to move the strings representing the annotations into this class as well, increasing encapsulation.
* Improve the type safety of the member variables so that callers don't need to perform redundant null-unsafe checks. In particular:
* Add a DeployStrategy enum to replace (no pun intended) the replace and recreate Booleans; these are mutually exclusive as setting both to true will 'kubectl delete' then 'kubectl replace' the manifest which always fails as there's …

refactor(kubernetes): Clean up KubernetesManifestStrategy

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanDeploy.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanDeployTest.java
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/candeploy/deployment-generate-name-result.yml
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/candeploy/deployment-generate-name.yml
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/candeploy/deployment.yml

* feat(kubernetes): Add support for kubectl create
Some manifest need to be applied with kubectl create; one example is manifests that specify a generateName instead of a name. In this case, we can't apply or replace, as both of these operations require looking up the existing manifest which is impossible when the name changes each time.
This commit adds support to KubernetesV2Credentials to create a manifest using kubectl create operation.
* test(kubernetes): Add tests to CanDeploy
Before lightly refactoring and adding some new functionality to the CanDeploy interface, add some tests to validate the existing behavior.
* refactor(kubernetes): Use switch in CanDeploy
The logic in CanDeploy is a bit too complicated; let's make it cleaner by using a switch over the enum of possible deploy …

 feat(kubernetes): Apply manifests with generateName using create

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2LoadBalancer.java

Closes https://github.com/spinnaker/spinnaker/issues/5359
Currently, Deck displays all Kubernetes V2 Load Balancers' associated workloads with the gray `disabled` styling. This is because we are passing an empty list instead of the required load balancer cache data when initializing `KubernetesV2ServerGroup` as part of reading the load balancers and their associated workloads from the cache. [This line](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/model/KubernetesV2ServerGroup.java#L213) determines whether a workload is considered disabled, which will always return `true` when passed an empty list for `loadBalancersData`.

fix(kubernetes): properly set isDisabled on server groups

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsTest.java

* test(kubernetes): Add tests to metric recording on kubectl calls
The runAndRecordMetrics funcgtion in KubernetesV2Credentials is very complex and has no tests. Before simplifying it, add some tests to document and validate the current behavior.
This commit also updates the constructor of KubernetesManifest to set the metadata to an empty map. In real code, we always create a KubernetesManifest by deserializing, so the metadata is set to a map of whatever was on the incoming manifest. But it's often useful in tests to be able to create a manifest and set a few fields on it; before this change, this wasn't possible because metadata was always null. There were functions to set various keys on the metadata, but these would all fail due to the null metadata.
* refactor(kubernetes): Clean up …

refactor(kubernetes): Clean up runAndRecordMetrics

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/JobExecutionException.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/JobExecutor.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/JobRequest.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/ReaderConsumer.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesMetricCachingAgent.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesV2OnDemandCachingAgent.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsTest.java

* refactor(kubernetes): Improve error abstraction in kubectl 
When parsing the output of kubectl as JSON, a few different kinds of errors can happen:
(1) An IOException if we encounter an error reading from the output stream
(2) A JSONSyntaxException if the call to gson.fromJson fails
(3) An IllegalStateException if the JSON format is unexpected (ex: if we get a list back instead of an object and call .beginObject() on it).
Currently we're propagating all these exceptions as is. Let's continue letting the IOException propagate, as this can be handled by the job executor in the same way it handles any other error reading output.
Let's wrap the JSONSyntaxException and IllegalStateException in a KubectlException to provide relevant context. This is how we handle a JSONSyntaxException other …

refactor(kubernetes): Improve error abstraction in kubectl

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/ArtifactReplacer.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesArtifactConverter.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesCoordinates.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverterSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy

* refactor(kubernetes): Make KubernetesCoordinates immutable
Luckily there are no existing uses that mutate it, so we can greatly reduce its API by making it a Value class.
* refactor(kubernetes): Clean up KubernetesArtifactConverter
There are a bunch of functions there that are no longer used, so we can significantly clean up that class (and implementations). Also move getAccount to the only place where it is used.
* refactor(kubernetes): Make implementations of converter singletons
It's confusing how we store an instance of each artifact converter on each KubernetesResourceProperties instance. The properties should only care whether the resource is versioned; the deployer logic can figure out what artifact converter to use based on whether the resource is versioned (and whether it has …

refactor(kubernetes): Clean up KubernetesArtifactConverter

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanDeploy.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubectlJobExecutor.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2Credentials.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CanDeployTest.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/security/KubernetesV2CredentialsTest.java

Fixes spinnaker/spinnaker#5148
Currently if using the strategy.spinnaker.io/replace annotation, the manifest will be applied with kubectl replace. This will fail the first time the pipeline is run as the object won't exist and kubectl replace fails if there is no existing resource to replace. (There is an open issue in kubernetes to make replace act as an upsert, but as of now it just as workarounds to try the replace and then create if it fails.)
As this is a common issue, Spinnaker should be able to make this easier. This commit updates the behavior on doing a replace to fall back to creating the resource if the replace call fails due to the resource not existing.

feat(kubernetes): Replace deploy strategy acts as upsert

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandler.java
clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/KubernetesDeployManifestOperationTest.java
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deploy/replicaset-overlapping-selector.yml
clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/deploy/service-no-selector.yml

Closes https://github.com/spinnaker/spinnaker/issues/5582
- chore(kubernetes): add tests demonstrating problems with service selector validation
When getting started with Spinnaker-managed rollout strategies, a poorly validated failure mode is one in which the Service you are attaching to your workload has either 1) no label selectors, or 2) label selectors that overlap with the workload's label selectors. In case 1, the pipeline will fail with a confusing NPE. In case 2, the pipeline will succeed, but any subsequent "disable" operations will fail because removing those labels will leave the ReplicaSet in an invalid state (because its selector will not match its template labels). This commit adds tests to document this behavior, which will be fixed in the next commit.
- fix(kubernetes): …

fix(kubernetes): throw more helpful errors for invalid services

---

build.gradle

There is now an errorprone release that fixes the bug leading to the initial pin, and this newer version is pulled in if we unpin.

chore(dependencies): Remove pin of errorprone

---

clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/Replacer.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizable.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LoadBalancerProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/controllers/ManifestController.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesResourceProperties.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKindProperties.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/model/Manifest.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeleteManifestOperation.java
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesPatchManifestOperation.java
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesUnversionedArtifactConverterSpec.groovy
clouddriver-kubernetes-v2/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverterSpec.groovy

Every now and then I run the IntelliJ inspections and clean up things that are easy. This is a batch of those:
* Don't use private constructor in tests; use singleton that is
package-private
* Replace if present with functional style
* Removed unchecked warnings from ManifestController by using a
parametrized ManifestProvider
* Remove redundant static final from inner class of interface (as
these are implied)
* Remove unnecessary semicolon
* Replace Integer.valueOf with .parseInt, which doesn't box
* Use lambda in stream
* Make inner class static as it doesn't reference non-static
members of outer class
* Remove null check on non-null variable
* Remove Autowired field from class that's not a Spring component

refactor(kubernetes): A few other code cleanup changes

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy

this change: https://github.com/spinnaker/clouddriver/pull/4328/files#diff-d1485122bced238a40908c660fdd7e37R19
introduced a strong dependency on k8s clouddriver module due to the import statement.
This breaks users who don't want to bring k8s module to their runtime environment

fix(jobcontroller): remove kubernetes dependency

---

cats/cats-sql/cats-sql.gradle
clouddriver-alicloud/clouddriver-alicloud.gradle
clouddriver-core/clouddriver-core.gradle
clouddriver-kubernetes-v2/clouddriver-kubernetes-v2.gradle

I'm trying to reduce the amount of things on the compile path by cleaning up dependencies. This cuts a few things from the clouddriver-kubernetes-v2 module, and also adds a few things to other modules that are used but not explicity included. (This is to prepare for an upcoming kork bump where these things will not be automatically included for everyone.)

refactor(core): Clean up some dependencies

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Task.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy

Today we use `agentId` to infer the `instanceId` and make an additional call to `/instance` endpoint to get the `ipv6Address` from the `networkInterface`
This change is to get the `ipv4` and `ipv6` addresses from Titus API directly . `ipv4` address is transitioning from `titus.containerIp` to `task.containerIPv4`
Todo : once these changes are merged and things are tested , we can remove the agentId and containerIp fields

fix(titus): Fetch ipv4 and ipv6 from titus api

---

gradle.properties
settings.gradle

Moves the default of all into settings.gradle if otherwise unspecified, but this allows a local development
environment to override the value in ~/.gradle/gradle.properties

chore(build): take includeCloudProviders out of gradle.properties

---

Dockerfile.compile

CI build recently updated to: https://github.com/spinnaker/clouddriver/blob/master/.github/workflows/build.yml#L10
Last night's build failed with insufficient memory for the JRE: https://console.cloud.google.com/cloud-build/builds/b9082103-af03-496a-b280-7857120b9190;step=2?organizationId=433637338589&project=spinnaker-community

fix(build): Match GRADLE_OPTS in Dockerfile with CI build

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy

This is the safest way to resolve this issue.  Setting an empty list default on the properties would work too, but I don't trust that all usages check for an empty list and my confidence in writing more Groovy at this point is at -1.

fix(aws): Resolve BasicAmazonDeployDescription NPE when returning names of loadBalancers, targetGroups, and securityGroupNames

---

clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/provider/view/AliCloudSecurityGroupProvider.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/view/AzureSecurityGroupProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/NoopSecurityGroupProvider.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/SecurityGroupProvider.groovy
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsSecurityGroupProvider.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/view/GoogleSecurityGroupProvider.groovy
clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSecurityGroupProvider.java
clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/view/KubernetesV1SecurityGroupProvider.groovy
clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2SecurityGroupProvider.java
clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/provider/view/OracleSecurityGroupProvider.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SecurityGroupController.groovy

Allows the retrieval of security groups by ID, as opposed to by name.
This is in support of fixing https://github.com/spinnaker/keel/issues/1060, and resolves an "impedance mismatch" problem in that the clouddriver APIs that return server groups contain only SG IDs, not names, whereas the APIs to return SGs previously only supported names.

feat(api): Allow retrieval of security groups by ID

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsLoadbalancerCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsTargetGroupCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsLoadBalancer.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsLoadBalancerDetail.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/loadbalancer/EcsTargetGroup.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProvider.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsLoadbalancerCacheClientSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsTargetGroupCacheClientSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProviderSpec.groovy

Implements https://github.com/spinnaker/spinnaker/issues/4797
Provides application load balancer and target group information for ECS server groups.

feat(ecs): Return application load balancer info from LB provider

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/SecurityGroupController.groovy

Turns out the API never worked if you didn't pass a VPC ID, because the glob filter built internally did not account for `null`, only `*`.

fix(security-groups): Fix handling of missing vpcId parameter to API

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProvider.java

Initializing set of services mapped to a target group as mutable so additional services can be added if found. Previously, EcsLoadBalancerProvider would return `java.lang.UnsupportedOperationException` when trying to add a second service to an existing set.
ECS target groups mapped to multiple services/server groups display properly

fix(ecs): make targetgroup service set mutable

---

Dockerfile.java8

We're currently using kubectl 1.16.0 in the docker container; let's bump that to the latest patch release, 1.16.9.
I'm not pulling in a new minor version, as kubectl only allows a skew of +/- 1 minor version from the API, so bumping to 1.17.x could potentially break users on Kubernetes 1.15. Keeping us on 1.16.x allows us to have full support for anyone on Kubernetes 1.15-1.17.

chore(kubernetes): Pull latest kubectl patch release

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLaunchTemplateCachingAgent.java

- using simple class name vs the toString of Class (oops)
Stacktrace: 
```
org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [insert into cats_v1_b_launchTemplates (id, agent, application, body_hash, body, last_updated) values (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?) on duplicate key update application = values(application), body_hash = values(body_hash), body = values(body), last_updated = values(last_updated) -- agentClass: someaccount/us-west-1/class com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonLaunchTemplateCachingAgent putCacheResult]; Data truncation: Data too long for column 'agent' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'agent' at row 1
```

fix(aws): Fixing launch template agent name getting truncated in sql

---

clouddriver-web/config/clouddriver.yml

Fixes spinnaker/spinnaker#5736
My recent change to push the -ro config for clouddriver down to the base config breaks deploying RO clouddriver with Halyard because it sets the redis endpoint to redisRo.baseUrl, which is not set by Halyard. This should default to redis.baseUrl to handle this case.

fix(ha): Fix deploying RO clouddriver with Halyard

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/BlockDeviceConfig.groovy

from: https://aws.amazon.com/ec2/instance-types/r5/

fix(ec2): Add block device config for r5n and r5dn instance types

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupManagerController.java

Closes https://github.com/spinnaker/spinnaker/issues/5754
"I love bounded wildcards."
-- Winston Churchill
(For the  Java-11 refactor, we parameterized `ServerGroupManagerProvider` with `ServerGroupManager`, but the Kubernetes implementation of this provider is actually parameterized with a subclass of `ServerGroupManager`, so we were failing to pick up that implementation and never returning any Deployment or Stateful Set details, manifesting in the UI errors reported in that GH issue.)

fix(kubernetes): return kubernetes server group managers

---

clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/model/ElasticSearchEntityTagsProvider.java

This makes it run quite a bit faster, plus adding some logging message so one can follow how far along we are in the process.
(in my tests this makes the operation run about 5x faster)

fix(entitytags): Parallelize deletion of entity tags from front50

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepository.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/Keys.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/view/CloudFoundryLoadBalancerProvider.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgentTest.java

This change adjusts the way that the LoadBalancerProvider searches for LB's for a particular spinnaker application. Initially, the logic would search for all loadbalancers for a particular provider and then filter through based on serverGroup/appName matching. This logic works fine for smaller CF users but causes timeouts for larger clients with thousands of loadbalancers. 
The new logic flips how we are doing loadBalancer searching. First, we ensure that the loadBalancerCachingAgent stores a link to the SG it's bound to. Then, we retrieve the loadbalancers tied to SG's which are part of the spinnaker application. The result is that we get the keys specific to the loadbalancers being requested and avoid large lookups.

fix(provider/cf): Adjust lookup of lb's per spinnaker app to avoid retrieving all lb cache

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/converter/job/KubernetesRunJobOperationConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubernetesRunJobOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubernetesRunJobOperationTest.java

Fixes spinnaker/spinnaker#5767.  I will cherry-pick back to 1.20 once this is merged, as per the discussion at the Kubernetes SIG today.
* test(kubernetes): Slightly refactor run job test
Pull a string to a variable to make the upcoming changes easier.
* fix(kubernetes): Restore adding a suffix to jobs
In Spinnaker 1.20, we removed the behavior where Spinnaker would automatically add a random suffix to Kubernetes jobs before deploying them, in favor of having users set the metatdata.generateName field to have Kubernetes do this.
This ended up being more of a breaking change than anticipated, particularly for users with a lot of preconfigured jobs, as by nature these jobs re-use the same name/namespace for jobs in different pipelines.
While we would like to longer-term still push users …

fix(kubernetes): Restore adding a suffix to jobs

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderCache.kt
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CatsClusterCachingAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonAuthoritativeClustersAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonAuthoritativeClustersAgentSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProviderConfig.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusAuthoritativeClustersAgent.java

incorporates the SqlProviderCache clean up from #4608

fix(cache): adds a proper authoritative clusters source for aws/titus

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderCache.kt

This is fixed on master as #4570, but I don't think it's safe enough to cherry-pick that. This is a significantly hackier fix, but it's safer since it only affects users using the SQL backend, which apparently isn't working anyway.
This is against the release-1.20.x branch, and then I'll cherry-pick it back to 1.19 and 1.18.

fix(gce): Fix cluster caching on the SQL backend

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgentTest.java

CFSGcachingAgent was using the buildOnDemandCacheData method from the abstract class it extends from. The object mapper that was used in the abstract class doesn't serialize the object as we need it because it only serializes fields based on the view. This creates a problem when trying to serialize a CacheData object. The fix is to override this method and use the same logic, but use the objectMapper thats currently being used in the serverGroupCachingAgent class. The additional test covers and ensures that the ondemand cache object has the servergroup attributes it should have. This fix will also ensure that on demand cache is actually processed and not just skipped over because the resulting fields are null

fix(provider/cf): fix buildOnDemandCacheData

---

clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesLoadBalancerCachingAgent.groovy

Reloading namespaces during loadData since new namespaces does not reflect in HA enabled clouddriver.
For HA enabled clouddriver, new loadbalancers created for a new namespace is not getting reflected since the namespaces are not reloaded. 
The on demand cache refresh from orca is being invoked to the clouddriver-rw service and the agent instances which are running in clouddriver-caching never get updated and the loadbalancers are not refreshed as well.
For server group agent, the namespace reload is invoked in loadData method here https://github.com/spinnaker/clouddriver/blob/release-1.20.x/clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/agent/KubernetesServerGroupCachingAgent.groovy#L257
I understand v1 is deprecated, But our users are …

fix(kubernetes/v1): Reloading namespaces during loadData since new namespaces does not reflect in HA enabled clouddriver.

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/Job.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/JobDescription.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/SubmitJobRequest.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/PrepareTitusDeploy.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusServerGroup.groovy

- Adding support for `COMMAND` which is supported in Titus along with `ENTRYPOINT` 
- making changes to deck after this is merged.

feat(titus): Adding support for command for titus jobs

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java

After https://github.com/spinnaker/clouddriver/pull/4325
Retrofit 404's are now converted to NotFoundException, this made the entitytag cleaner on ASG creation not handle the case when no entity tag exists.

fix(entity tags): Restore NotFoundException handling

---

Dockerfile.java8
Dockerfile.slim

Fixes spinnaker/spinnaker#5715.
Let's bump to 1.17.x of kubectl for the next Spinnaker release. Currently Kubernetes is on 1.18.x, but to try to maximize overlap with the version users are running we'll stay at 1.17.x.
This means that we'll officially support 1.16-1.18 (as kubectl allows a +/- 1 version skew with the cluster). In practice this should not cause issues for users on <=1.15 as I don't believe in practice there are generally changes that break talking to old clusters. This does allow users on 1.17 to start to use new fields.

chore(kubernetes): Bump kubectl version

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CatsClusterCachingAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

Adds an application attribute to authoritative clusters so that the lookup by application succeeds.
Also includes relationships from the cluster to the server groups we are crawling

fix(aws/cache): index authoritative clusters by application

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/model/JobDescription.java

- don't set `command` if its empty

Fix(titus): Additional checks while setting command

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCacheDataConverter.java

In an upcoming kork release, artifacts will become immutable to prevent confusing bugs where (primarily in orca) we are mutating copies of what we think we are mutating. There are a small number of places in clouddriver where artifacts are mutated, but these can be replaced by returning a copy with the desired changed.

refactor(artifacts): Remove mutations of artifacts

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesV2OnDemandCachingAgent.java

Fixes spinnaker/spinnaker#5353.
The function to get pending cache refreshes for Kubernetes greatly duplicates work. The way it currently works is:
* Every account has a number of caching agents responsible for caching certain types of data.
* On-demand cache refreshes all go the same place in the cache so there is no way to ask the cache "give me all on-demand refreshes for agent X"
* This means that when we ask an agent to give us on-demand cache refreshes for the data it owns, it fetches *all* on-demand cache refreshes, then post-filters that list in Java down to the ones that it owns.
This might be reasonable if an incoming request for pending on-demand requests had enough information to route it to a single caching agent; we could then send it to the relevant caching agent and use the …

perf(kubernetes): Reduce duplicate work in on-demand cache refresh

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactCredentials.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/artifact/KubernetesCleanupArtifactsOperation.java

* refactor(kubernetes): Avoid mutating artifact metadata
There's only one place where we mutate the artifact metadata map, and it's in the Kubernetes provider. Rather than get an artifact then add the metadata later, let's just move the logic to add that metdata to the place where we create the artifact, avoiding the need to mutate the metadata.
* refactor(artifacts): Update artifact code to use new metadata accessor
The accessor to get the full metadata of an artifact as a map is deprecated; replace calls to it with the accessor for a specific key.
The reason the function to return the entire map is deprecated is so that we can eventually make the map immutable; it's much safer to make that change if we've first updated callers to be unaware that the map exists at all an instead give …

refactor(artifacts): Update artifact code to use new metadata accessor

---

clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/model/TencentCloudTargetHealth.java

This file is not compiling for my version of the JDK (openjdk 1.8.0_242) because we are importing the inner class before we import the Data annotation that the class is annotated with. It looks like this may have been fixed in later versions of the JDK, but let's avoid others running into this issue by fixing it.

fix(tencent): Fix compilation error due to import order

---

settings.gradle

Following no action from any contributors or stakeholders for Oracle, DCOS, or Alicloud, these cloud providers are being removed from the project. The first step is removing the code from the build, but will eventually lead to complete removal of the code.
* [Notice for Alicloud](https://github.com/spinnaker/governance/issues/122)
* [Notice for DCOS](https://github.com/spinnaker/governance/issues/125)
* [Notice for Oracle](https://github.com/spinnaker/governance/issues/127)

chore(*): Remove Oracle, DCOS, and Alicloud from project

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizerSpec.groovy
clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/ResourcesNameable.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/utils/AwsLookupUtil.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/TitusDeployAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/TitusDeployDescription.java

-Additionally, removes requiresAuthorization from `ResourcesNameable` and removes `BasicAmazonDeployDescription` implementation of `ResourcesNameable`.  We will instead be requiring authorization on these resources via an implementation of `AllowedAccountsValidator` which runs prior to `DescriptionAuthorizer`.

feat(titus): Lookup server group names when converting TitusDeployDescription

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TargetHealthCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TargetHealthCachingAgentSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/5816
1. added `'should handle null targetGroupArn in cache data'` test, reproduced error
2. added null check, test passes 🎉

fix(ecs): add null check for target group cache data

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CloudFoundryRunJobOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/CloudFoundryRunJobOperationDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/CloudFoundryRunJobOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryJobStatus.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/view/CloudFoundryJobProvider.java

Job shouldn't be in its own module. This change puts the Job classes in the appropriate directories and finished the ApplicationNamable implementation that was done to all the other operation classes.

refactor(provider/cf): move cf Job classes to correct modules to avoid siloed code

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CatsClusterCachingAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonAuthoritativeClustersAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonAuthoritativeClustersAgentSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusAuthoritativeClustersAgent.java

This is still missing the cluster -> loadBalancers relationship that used to be populated.
For now there are some defaults to empty collection on the AmazonClusterProvider to prevent
NullPointerExceptions, I will follow up with an update to add cluster -> loadBalancer and
cluster -> targetGroup relationships as a separate change

fix(aws/cache): include informative results in CatsClusterCachingAgent

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/CloudFoundryRunJobOperationDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java

We have ensured that orca is now passing moniker objects with tasks so this is the partner change that will now use those moniker objects for application name. Now all operations that use AccountNamable and ApplicationNamable use the same logic for cloudfoundry operations.

fix(provider/cf): use moniker object for application name

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgent.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgentTest.java

Previously, DEFAULT_REGION was always used, breaking for users in China or GovCloud.
This change uses a configured region, if present, and logs the choice.
Fixes https://github.com/spinnaker/spinnaker/issues/5710

fix(ecs): set IAMRoleCachingAgent AWS region

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlCacheConfiguration.kt

Fixes https://github.com/spinnaker/spinnaker/issues/5706
Modifies the way dates (like java.time.Instant) are stored in sql, storing them as strings instead of a map.
Example of docker image date stored in redis: `"date": "2017-06-23T00:57:26.841792489Z"`
Example of docker image date stored in sql before this change: `"date": { "nano": 499754581, "epochSecond": 1591115020 }`
After the change in sql: `"date":"2020-06-02T16:23:45.284504313Z"`

fix(sql): Store dates as string instead of maps

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsService.java

The code to fetch the version of an operation catches any Exception. The only actual exception that can occur is a null-pointer exception of credentials.getOne returns null. Let's just make the code null-safe and remove all catch and warning logic.
One of the main motivations of this is that ProviderVersion is no longer even relevant now that the Kubernetes V1 provider has been removed from the code. Logging a warning related to being unable to fetch the provider version just confuses debugging; if the account doesn't exist, that itself is the problem, so we should note that in the warning, rather than that we couldn't fetch the version.

refactor(core): Fix warning fetching operation version

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesEnableDisableManifestDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestTraffic.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanLoadBalance.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesServiceHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/AbstractKubernetesEnableDisableManifestOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesV2Credentials.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesEnableDisableManifestDescriptionTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestTrafficTest.java

Fixes spinnaker/spinnaker#5843 where an NPE was thrown instead of a useful error message about what Kubernetes object could not be found.
* refactor(kubernetes): Clean up EnableDisableManifestDescription
Mostly the goal here is to make loadBalancers Nonnull, which required overriding the lombok-generated accessor so that we can translate a null that's passed in to an empty list. While here, make the list immutable.
Also add some tests, particularly on deserialization.
I did *not* make the class immutable because one must draw some line at which to stop refactoring.
* refactor(kubernetes): Make KubernetesManifestTraffic null-safe
Also make it immutable, and add some tests.
* fix(kubernetes): Fail with a useful message if manifest not found
This commit adds nullity annotations to a number …

fix(kubernetes): Fail with a useful message if manifest not found

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

Locally, this improves the performance for this endpoint by about 12% (for large applications)
Removing fetching a few relationships since they aren't used and also don't calculate `isHealthy` since it's not used/serialized

perf(aws): Minor improvement to perf of /serverGroups endpoint

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

Apparently, some folks actually rely on the `isHealthy` attribute which I thought wasn't being serialized. It appears it is serialized via the `clusters` endpoint

fix(aws): undo part of the perf improvement in #4692

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoscalingPolicy.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgent.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgentTest.java

I also changed the clouddriver API for this functionality to match the new terminology. Since the only client of this API (deck) has it hidden behind a feature flag, I felt okay about breaking the API to make the code less confusing.
See spinnaker/deck#8372

fix(gce): use the new ScaleInControl autoscaler API

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateApplication.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateApplicationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

Stack is the root filesystem to use with the buildpack, for example cflinuxfs3. This property wasn't currently available today in the spinnaker cf manifest so we added it per customer requirements. I also refactored the createApplication method so that we can easily add more application attributes in the future without needing to modify the method signature. I also added tests that confirm the functionality and to ensure it's not a breaking change to possible existing implementations.

feat(provider/cf): add stack property for buildpack lifecycle

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgentSpec.groovy

Previously, how to check task health forked based on looking for network bindings on each container. Whether the task contains network bindings was already being determined in a previous check, so this surfaces that value and forks based on that instead. 
Also adds test to ensure tasks with missing or null network bindings/interfaces are skipped.

chore(ecs): Refactor TaskHealthCachingAgent networking check

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesV2Provider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesV2ProviderSynchronizable.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesV2ProviderSynchronizableSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/5869
Instead of overwriting the collection of caching agents in `KubernetesV2Provider` by one that only has agents for new or changed accounts, new agents are added to the existing collection.
Old agents for changed accounts are removed by `ProviderUtils.unscheduleAndDeregisterAgents`, so there are no duplicate agents for changed accounts.

fix(kubernetes): Don't delete caching agents of unmodified accounts after a refresh

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNames.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgent.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConstraints.kt
cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNamesTest.kt

Prior to this change, the agent name could go over the max column length. This hashes the end of the agent string so it stays under `sql.constraints.maxAgentLength` (defaults to 127).
As far as I can tell, the actual `rel_agent` value is only used to get the type so this should work as long as the type itself is not too long. I'd appreciate someone with more intimate knowledge of that code to confirm (@robzienert ?)
Fixes https://github.com/spinnaker/spinnaker/issues/5600

fix(cats/sql): Enforce max length on agent/rel_agent value by hashing if necessary

---

Dockerfile.slim
Dockerfile.ubuntu
Dockerfile.ubuntu-java8

It looks like the aws-iam-authenticator version 0.4.0 currently installed during docker build does not work with IRSA.
After downloading aws-iam-authenticator version 0.5.0, the same as in halyard then it works fine and I can see that when communicating with other EKS cluster that it is using the correct role and not the role on the node.

fix(kubernetes/IRSA): Update aws-iam-authenticator to 0.5.0

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java

The command property will override the existing buildpack command. Some buildpacks require that you specify a custom command so this was needed to satisfy those requirements. Command was partially implemented so there wasn't a ton that was needed in order for this to work. CloudFoundry states that if you want a buildpack to use its original command then you must pass _null_ explicitly as a command. The assumption here is that when you are deploying an application you can either set a custom command or leave the command off the manifest. If command is not included, it will use the default command specified by the buildpack. There was already testing in place to cover the core logic but I did add some minor modifications to ensure the field was being converted correctly.

feat(provider/cf): add command property to manifest

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationService.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationServiceSpec.groovy

Updates the container health status to Up for a RUNNING task rather than Unknown. Tested multiple scenarios successfully.
Fixes: https://github.com/spinnaker/spinnaker/issues/5741

fix(ecs): update health status for running tasks

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy

- assign IPv6 address to instances when `associateIpV6Address` is true
@caseyhebebrand I decided not to overload `associatePublicIpAddress` for IPv6 since that creates a public IPv4 address.
Instead I added `associateIpV6Address` that can be set independently of `associatePublicIpAddress` and avoid coupling the two.

feat(aws): Support IPv6 for launch template backed ASGs

---

clouddriver-web/clouddriver-web.gradle

kork-runtime brings in kork-swagger for the runtime component configuration

fix(dependencies): depend on only swagger-annotations for compile

---

clouddriver-web/clouddriver-web.gradle

thanks groovy... I guess without rxjava on compile (even though it is in runtime) the controllers that are
using it are compiling to some groovy methodMissing metagarbage...

chore(dependencies): add rxjava to compile classpath

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepository.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java

This fix should help improve the latency of /projects/{project}/clusters within CloudFoundry. Since each of the clusters will get fully hydrated with subsequent calls, there is no need to fully hydrate before hand without changing the existing core logic.

fix(provider/cf): getClusters NAMES_ONLY shouldn't fully hydrate

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy

Closes: https://github.com/spinnaker/spinnaker/issues/5737
[This PR](https://github.com/spinnaker/clouddriver/pull/1132) made the DockerRegistryImageCachingAgent informative rather than authoritative "to prevent images from being deleted." However, based on [this issue](https://github.com/spinnaker/spinnaker/issues/5737), users expect deleted entities to be removed from the cache. Since the DockerRegistryImageCachingAgent fetches an exhaustive list of tags each run, I think it makes sense for it to be an authoritative agent.

fix(docker): make DockerRegistryImageCachingAgent authoritative

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy

Currently, the model for creating ALB listener rule conditions in aws is the same for every `condition.field`. When the `condition.field == "http-request-method"`, aws expects a different payload to create the rule condition. This PR ensures the correct payload is sent to aws when an http-request-method condition is specified. 
Expected: 
```java
{
field: String,
httpRequestMethodConfig: {
values: List<String>
}
}
```

feat(aws): Support for ALB listeners with http-request-method conditions

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/GlobalKubernetesKindRegistry.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesKindRegistry.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/backend-pod-014.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/backend-pod-015.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/backend-rs-014.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/backend-rs-015.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/backend-service.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/frontend-deployment.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/frontend-pod-1.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/frontend-pod-2.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/frontend-rs-new.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/frontend-rs-old.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/frontend-service.yml

There are currently almost no tests on any of the data providers in the Kubernetes provider. Before doing significant work in this area, we should add some test coverage to validate that the upcoming changes don't break anything.
As a lot of the classes are tightly-coupled without clearly defined interfaces between them, I decided to write an integration test that runs the caching agent for a few resources, then calls the data providers to ensure that the resulting data is as expected.
This tests the contract that should mostly stay consistent during the upcoming refactor. Even if we change what data is stored in the cache, we'll need to make sure that these providers still return the same data after a caching cycle is run.
Eventually we should write more unit tests, once there are …

test(kubernetes): Add integration tests on caching views

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroupManager.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2Application.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2Cluster.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2Health.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2Instance.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2LoadBalancer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2SecurityGroup.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2ServerGroupManager.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2ServerGroupSummary.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ApplicationProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ClusterProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2LoadBalancerProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/data/KubernetesV2ServerGroupCacheData.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/data/KubernetesV2ServerGroupManagerCacheData.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java

* refactor(kubernetes): Improve typing in view classes 
In a number of places we store data in these classes as the interface type rather than as the concrete type, and then need to cast to the Kubernetes-specific implementation. Instead, let's keep everything concrete in the Kubernetes classes to avoid this casting.
In some cases, using the interface type can be useful (ie, if we don't want certain implementation-specific functions to be visible). But in this case the primary use for these data classes is serializing them and sending them to another microservice (and eventually to deck). Regardless of the type we are storing it in, we are still fully serializing the instance fields, so the effective contract is that callers expect to find Kubernetes-specific fields here. (That's the …

refactor(kubernetes): Clean up data provider classes

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java

When we disable an ASG in titus we need to get all tasks associated with the job.
However, it appears that we always retried ALL tasks from ALL jobs. Which is neither great for Titus nor Spinnaker since we a) run out of memory and also timeout like crazy trying to get the world
Pretty sure the issue is this erroneous conditional which checks if Titus supports query by job ids

fix(titus): only get the task we need

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2LoadBalancer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ClusterProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2LoadBalancerProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ServerGroupManagerProvider.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java

* refactor(kubernetes): Add Multimap-returning getRelationships 
This commit only affects CacheData, in preparation for some changes visible outside the class. Most notably, we'll update getRelationships to return a MultiMap when we pass in a Collection of CacheData items. This allows the caller to see the association between the input data and the output relationships, rather than flattening it to a collection where it's not possible to determine which of the output CacheData items is related to each of the input ones.
In this commit, we're not taking advantage of this; in fact the two callers have been updated to:
* Just call .values() to flatten the result
* Query the cache directly instead of using getRelationships
But in the next commit we'll push this information outward one more …

refactor(kubernetes): Further improvements to Kubernetes data providers

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubeconfigFileHasher.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialFactory.java

When a kubernetes account is configured with `serviceAccount: true` instead of a kubeconfig file, this exception is shown in clouddriver logs when trying to derive the hash of the missing kubeconfig:
```
2020-07-31 22:01:52.545  WARN 1 --- [           main] c.n.s.c.k.security.KubeconfigFileHasher  : failed to hash kubeconfig file at /home/spinnaker/.kube/config: {}
java.nio.file.NoSuchFileException: /home/spinnaker/.kube/config
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:2 …
```

fix(kubeconfig): Don't hash missing kubeconfig files

---

clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/requestqueue/pooled/PooledRequestQueueTest.java

I fixed a deadlock in this test a few weeks ago, but just ran into one other timeout. This commit makes a few minor fixes to reduce the chances of hitting a timeout here.
First:
(1) Use a fixed thread pool executor so we create all the threads we need up front and reduce the work later.
(2) Don't start our timeout clock until the job we're expecting to timeout has been queued.
(3) Increase the startup timeout to 50 ms and only time out the test after 10x (instead of 5x); this is just so we're dealing with slightly larger absolute numbers.  (Before we were only waiting 100 ms to time out the test, now we're waiting 500ms.)
(4) Fail with a specific message if we timeout, rather than assert on the status of the job (which we know won't be in the expected state because we killed it). This …

fix(test): Fix intermittent timeout in PooledRequestQueueTest

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/CreateLambdaAtomicOperation.java

Attempting to create a lambda without a dead letter queue ARN results in an `InvalidParameterValueException`
DLQ config is added to CreateLambdaRequest regardless of presence of ARN.
Fix: Add logic to check whether a DLQ ARN is provided before adding to CreateLambdaRequest

fix(lambda): Fixes create lambda from failing when DLQ is not provided

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ivy/settings/BintrayResolver.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryPackage.java

<kbd>![](https://p-qKFvWn.b3.n0.cdn.getcloudapp.com/items/lluY4zRL/safkajdflkasdjf.png?v=b5e663894145199d7a55ab8387e91585)</kbd>
This was causing some errors with the build

chore(build): removed UTF8 "smart quotes"

---

Dockerfile.compile

it looks like Google Cloud Build `compile` step is exiting with 137. Maybe Gradle needs more memory.
<kbd>![](https://p-qKFvWn.b3.n0.cdn.getcloudapp.com/items/DOuxvG71/Image%202020-08-07%20at%2019.24.23.png?v=6082595a8b8980f3d173bdbda3855083)</kbd>

chore(build): bump up gradle memory max to 7gb

---

Dockerfile.compile

Our container builds run on a machine with only 7.2 GB of memory; while we do want to give a lot to the JVM we should leave a bit more for the everything else.
I was able to succesfully build the containers with these settings, so let's use them.

fix(build): Reduce Xmx and Xms

---

clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonClusterSpec.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Cluster.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/LoadBalancerProvider.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/SecurityGroup.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/securitygroups/Rule.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/ClouddriverApiModule.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/ClusterMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/ImageSummaryMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/ImagesSummaryMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/LoadBalancerProviderByAccountMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/LoadBalancerProviderByRegionMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/LoadBalancerProviderItemMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/RuleMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/SecurityGroupMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/ServerGroupMixin.java

Not having the jackson annotations directly on the model allows them to more easily be moved to an external library without needing a Jackson dependency.

fix(api): remove jackson annotations from model

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgent.java

Attempting to create a lambda from a secondary AWS account results in the lambda creation succeeding, but the task failing.
There is no check to ensure the caching agent account id matches the account id that the function is created in resulting in an AccessDeniedException
Fix: Add logic to ensure the caching agent account and region match the function data passed

fix(lambda): Fixes cache update from failing

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesArtifactConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesUnversionedArtifactConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/Replacer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/ArtifactProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ArtifactProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/artifact/KubernetesCleanupArtifactsOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesPatchManifestOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverterTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ReplacerTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeployManifestOperationTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubernetesRunJobOperationTest.java

* test(kubernetes): Add some tests on ArtifactProvider and Replacers 
Let's add a few tests on the ArtifactProvider. As it depends on an implicit contract with the caching agent, let's use the integration test rather than mock a lot of CacheData items that look like how the caching agent currently stores data.
In a recent PR, we converted the ArtifactReplacer tests to Java and also improved the test coverage. While these covered the general interface of ArtifactReplacer by using a few specific replacers, we still don't have good test coverage of all of the replacers defined in Replacer.java.
This is important as the functionality of these replacers is almost entirely encoded by complex JsonPath expressions, and I'd like to refactor these to be cleaner.
This commit adds a ReplacerTest …

perf(kubernetes): Precompile find path for artifact replacers

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java

Now that we always live lookup events when loading a manifest, the latency of that call becomes more important. (It was always important for users with liveManifestCalls, but now becomes important for everyone.)
In general, for kubectl calls that might return multiple items, we parse the output as it is produced to avoid needing to buffer a lot of intermediate data. We do this by requesting asynchronous execution of the job, then using
the main thread to parse any output from the job as it is produced.
It turns out that the apache-commons library we use adds a fair amount of latency for quick asynchronous jobs. This is because the .waitFor() function on the resultHandler just does a poll/sleep loop to wait for the forked process to finish, which causes us to often wait quite a bit longer …

perf(kubernetes): Reduce latency of streaming job executor

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/Keys.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesV2OnDemandCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesCacheUtils.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesManifestProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ClusterProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2InstanceProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2LoadBalancerProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2SecurityGroupProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesCoordinates.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestOperationDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesMultiManifestOperationDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesPatchManifestDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/servergroup/KubernetesServerGroupOperationDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanLoadBalance.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/AbstractKubernetesEnableDisableManifestOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesManifestSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgentTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2InstanceProviderTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesCoordinatesTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeployManifestOperationTest.java

* refactor(kubernetes): Move name parsing logic to KubernetesCoordinates 
A lot of the Kubernetes logic parses a kind-name String into a Pair<KubernetesKind, String>. This leads to very unclear code as we are always calling Pair#getLeft and Pair#getRight instead of using more clearly-named functions. While Pairs might be reasonable for short-term holding of data in functions or streams, they quickly lead to complicated code when passed across function boundaries.
We already have a KubernetesCoordinates class that represents a kind and a name (as well as a namespace). (And in most cases where we're parsing a kind-name string we also have a namespace around too.)
Let's prepare to move clients to instead parse into KubernetesCoordinates. This change does the following:
* Explicitly write out …

refactor(kubernetes): Move name parsing logic to KubernetesCoordinates

---

settings.gradle

Azure has still not submitted for formation of a SIG, despite numerous attempts to bring them under conformance of cloud provider requirements.

feat(azure): Removing Azure from cloud providers

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusExceptionHandler.java

In https://github.com/spinnaker/clouddriver/pull/4796 we resolved an issue wherein a saga retry would skip a command under certain scenarios.  The particular failure scenario we had around retrying this error was due to that bug - now that it is fixed we should be able to safely retry here.

fix(titus): Re-enable saga retry on INVALID_ARGUMENT error due to rate exceeded

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesManifestProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesPodHandler.java

* perf(kubernetes): Only deserialize pod status
Rather than convert the entire manifest to a V1Pod, only convert the status as that's all this function is using.
Ideally we'd only do a single conversion to the full appropriate type when we get a value back from the cluster, and pass that around, but as long as we're still doing these ad-hoc intercoversions, it's worth avoiding doing more than we need.
* perf(kubernetes): Request metrics and events in parallel
When deck requests a manifest, it wants the events and metrics as well. This means that we make 3 sequential calls to the cluster, each with a bit of latency, that ends up making the overall call longer than needed.
Let's speed this up by sending the event and metrics requests to an executor pool that runs them on a separate thread. …

perf(kubernetes): Request metrics and events in parallel

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java

Reverts spinnaker/clouddriver#4753
While testing some unrelated changes, I noticed that there is a bug in the filtering logic that was added here.  In some cases (ex: `Pod`) we are filtering out all events so that events no longer appear in the UI.  It appears that while this improved the situation for CRDs, it caused a regression for at least some built-in kinds.  As this is kind of subtle and I'd like to see some test coverage before re-applying, reverting before cutting the 1.22 branches so that this bug is not present in 1.22.

fix(kubernetes): Revert fixes to ensure CRD events are reported in deploy stage

---

clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidator.java
clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperation.java
clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationConverter.java

These interfaces use raw types, which forces all implementations to do the same as well (as you can't override a raw type with a parametrized type).
I've added a few type bounds so that implementations can avoid using raw types; this should in no way affect clients that are still using raw types (as evidenced by the fact that I'm not changing any of the implementations here).
Obviously Map<String, Object> is not great as a parameter type, but that's what the Map actually is, and it's better than a raw Map.

refactor(core): Add type bounds to AtomicOperation classes

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesV2ProviderSynchronizable.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2LoadBalancerProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacerTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverterTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesKindRegistryTest.java

* fix(kubernetes): Fix errorprone TypeParameterUnusedInFormals 
[TypeParameterUnusedInFormals] Declaring a type parameter that is only used in the return type is a misuse of generics: operations on the type parameter are unchecked, it hides unsafe casts at invocations of the method, and it interacts badly with method overload resolution.
This check is 100% correct here; the only advantage of using the generic here is that we can hide the casting in getRequiredField. In fact, let's just get rid of this method and force callers to do the casting; keeping the method just to throw the exception seems more confusing than inlining.
* fix(kubernetes): Fix error-prone issues 
This fixes a few error-prone issues that were trivial to fix, and were easier than suppressing the whole warning class. …

refactor(kubernetes): Enable error-prone and compiler warnings

---

clouddriver-api/src/main/java/com/netflix/spinnaker/cats/agent/AgentScheduler.java
clouddriver-api/src/main/java/com/netflix/spinnaker/cats/agent/AgentSchedulerAware.java
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/artifacts/GcsStorageService.java

The upgrade to google-java-format pulled semicolons after methods to be on the next line (probably to make them more visible because they are in general not necessary); let's just remove them.

fix(core): Remove extraneous semicolons

---

CODEOWNERS

The CODEOWNERS entries were only matching files with that pattern, not the full subdirectories. In practice this meant that any change to the .gradle file in the subproject would trigger a review request from code owners but no other changes would.

fix(*): Fix syntax of CODEOWNERS file

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/Keys.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/ArtifactProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesV2ArtifactProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/artifact/KubernetesCleanupArtifactsOperation.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KeysSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/KubernetesVersionedArtifactConverterTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/KeysTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgentTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeployManifestOperationTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubernetesRunJobOperationTest.java

* refactor(kubernetes): Update getArtifacts to accept kind
As we'll be directly querying the cluster, it makes more sense to accept the actual kind rather than the artifact kind, which is "kubernetes/kind". For now we'll just re-construct the kind in the function, but that will shortly be unnecessary when we move to directly queryin the cluster.
* fix(kubernetes): Do a live lookup in the artifact provider
This is only used during deploys, so latency is not a big issue here. This will fix race conditions with live manifest calls enabled where operations later in a pipeline don't account for operations that happened earlier in the pipeline.
For now I am just replacing the exact same logic with a live call, including:
* Building the whole artifact (even though we only need a few fields)
* …

fix(kubernetes): Do a live lookup in the artifact provider

---

build.gradle
lombok.config

This commit applies the jacoco pluigin to all subprojects, giving them the task jacocoTestReport to get a test coverage report.
When the plugin is present, tests are instrumented by default (as the tests don't know if we'll later want to generate a report), which slows them down. To prevent slowing down all builds, I've put the test instrumentation behind a flag.
Now if you run
```
./gradlew -PtestCoverage jacocoTestReport
```
it will instrument the tests and generate a coverage report for each submodule.
Also configure lombok to add a Generated annotation to code that it generates, so that it gets excluded from code coverage reports.

feat(*): Add optional code coverage reports

---

clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaService.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/events.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaFlowIterator.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/models/Saga.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/util.kt
clouddriver-saga/src/test/kotlin/com/netflix/spinnaker/clouddriver/saga/SagaServiceTest.kt
clouddriver-saga/src/test/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaFlowIteratorTest.kt

Building on #4820.
We had a problem where Sagas were being marked as completed, despite not all commands being completed. This change adds `CommandFinalizer` which `SagaCommandSkipped` (new) and `SagaCommandCompleted` implement, allowing us to only complete a Saga once all commands in the event log have been "finalized".
When in a branching scenario, Sagas will pre-emptively add commands for conditional branches into the event log. When a branch is _not_ taken, it previously left some commands lingering, making completed logic a little flaky. Now, when a branch is not taken, its steps will be scanned for actions that match commands already on the event log, adding `SagaCommandSkipped` to keep the event log cleaner.
While doing this work, I've identified some ways to make Sagas more …

fix(saga): Complete sagas only once all commands are finalized

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy

We had an incident where Amazon was taking an unusually long time to register instances with load balancers yesterday. We didn't have any metrics to inform us of just how widespread the issue was, how long instances were in limbo, nor when AWS had recovered. The only signals we had were observation of manual attach/detach operations.

chore(aws): Log LB instances that have "still registering" state description

---

clouddriver-elasticsearch-aws/clouddriver-elasticsearch-aws.gradle
clouddriver-elasticsearch/clouddriver-elasticsearch.gradle

Using the contraints we are running into build errors internally, like so:
```
Could not determine the dependencies of task ':clouddriver-package:installDist'.
> Could not resolve all task dependencies for configuration ':clouddriver-package:runtimeClasspath'.
> Could not resolve org.elasticsearch:elasticsearch:{strictly 2.4.1}.
Required by:
project :clouddriver-package > project :clouddriver:clouddriver-web
project :clouddriver-package > project :clouddriver:clouddriver-web > project :clouddriver:clouddriver-elasticsearch-aws
> Cannot find a version of 'org.elasticsearch:elasticsearch' that satisfies the version constraints:
Dependency path 'com.netflix.spinnaker.clouddriver.internal:clouddriver-package:unspecified' --> 'com.netflix.spinnaker.clouddriver.internal:clouddriver-nflx:unspecif …
```

fix(build): Remove use of gradle constraint on elasticsearch and jest dependencies

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesManifestProvider.java

* refactor(kubernetes): Fix short circuit boolean error prone warning. 
The right hand side of the & has no side effect, so we can simply fix by switching to &&.

refactor(kubernetes): Fix short circuit boolean error prone warning.

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/PropertyParser.java

* refactor(kubernetes): Fix string splitter error prone warning. 
Switched to using Splitter in PropertyParser.java since the behavior is properly defined, unlike String.split(String). The reason for omitting empty strings here is because otherwise there is a scenario where it will attempt to parse properties with empty values. There is a test case for this scenario.

refactor(kubernetes): Fix string splitter error prone warning.

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2Instance.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2LoadBalancer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2SecurityGroup.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2ServerGroup.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2ServerGroupManager.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesV2JobStatus.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/KubernetesModelUtil.java

* refactor(kubernetes): Minor refactor of timestamp function
Instead of looking twice in the map, just check if the result is null in getCreationTimestamp.  (Since this is a mutable map, the presence of the key doesn't guarantee the value is null anyway, so let's jut get the value.) I didn't use Optional here because this is used in a comparator that might be called a lot for large sorts, but maybe that's a micro-optimization.
The result is non-null so we can use .isEmpty() in getFormattedTimestamp.
Finally let's rename getFormattedTimestamp to getCreationTimestampEpochMillis, as the result is not formatted.
* refactor(kubernetes): Fix JdkObsolete warnings
[JdkObsolete] Date has a bad API that leads to bugs; prefer java.time.Instant or LocalDate.
In KubernetesManifest, we can parse the …

refactor(kubernetes): Fix JdkObsolete warnings

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java

* refactor(kubernetes): Fix default charset error prone warning and enable warning moving forward. 
Specifying standard charset that is available in every implementation of Java platform instead of using platform default that varies from machine to machine or JVM to JVM.

refactor(kubernetes): Fix default charset error prone warning and enable warning moving forward. 

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesV2ProviderSynchronizable.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesV2OnDemandCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesPodHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubernetesRunJobOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/KubernetesValidationUtil.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicatorTest.java

* fix(kubernetes): Make enum fields final
[ImmutableEnumChecker] enums should be immutable: 'PodPhase' has non-final field 'message'.
* fix(kubernetes): Fix use of raw types and enable warning
I suppressed one warning because the interface requires using a raw type.
Also the AccountCredentialsRepository interface returns raw types, which causes one issue where we try to directly use a lambda on the stream of results. I updated that to not use a lambda (which I think implicitly implies (AccountCredentials<?> c) -> c.getName() avoiding the warning, but we should also consider fixing AccountCredentials itself.

fix(kubernetes): Fix ImmutableEnumChecker and rawtypes warnings

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/model/KubernetesV2Application.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesV2JobStatus.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanUndoRollout.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubernetesRunJobOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesV2JobProvider.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java

We cannot yet enable the error-prone warnings as there are a few dozen classes with Lombok-generated getter overrides that I'll handle in a followup PR.

refactor(kubernetes): add missing @Overrides to non-generated code

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesV2CachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesKindProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCacheDataConvertSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesKindPropertiesSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java

Resolves https://github.com/spinnaker/spinnaker/issues/5985
* refactor(kubernetes): move hasClusterRelationship from KubernetesKindProperties to KubernetesCacheDataConverter 
Moves logic determining whether to cache cluster relationships for a given kind to the only place it is needed. (Will also make next commits more readable.)
* fix(kubernetes): differentiate between logical and cluster relationships 
Only kinds that map to Spinnaker server groups and server group managers are considered Spinnaker clusters, and should be differentiated between the other "logical" kinds surfaced in the Application UI as Spinnaker Load Balancers and Firewalls. Stop caching cluster relationships for non-cluster kinds, and update tests accordingly.
* refactor(kubernetes): make logical and cluster …

fix(kubernetes): only workload types have cluster relationships

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleInternalHttpLoadBalancerCachingAgent.java

spinnaker/spinnaker#6016
When additional pathMatcher is defined, `urlMap.getPathMatchers()` returns a list.
And default path matcher doesn't have any path rule then `pathMatcher.getPathRules()` returns null.

fix(provider/gce): Fix NullPointerException when additional pathMatcher defined for InternalHttpLB

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonAccountsSynchronizer.groovy

When mocking bean of type `AmazonAccountsSynchronizer` during integration tests, we need to mock the `synchronize(...)` call to avoid a `MissingMethodException` on app startup. However b/c there is no method defined on the interface which matches the [concrete implementation](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/DefaultAmazonAccountsSynchronizer.groovy#L29) called in [AmazonCredentialsInitializer](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.groovy#L71), the (Java) compiler complains with "error: cannot find symbol" if you try to mock it with the correct parameters. 
This change …

chore(aws): add method sig to AmazonAccountSynchronizer

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonElasticIpCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonKeyPairCachingAgent.groovy

These are lower priority agents and decreasing the interval may
play a little nicer with aws rate limits.

fix(aws): Adjusting the interval for elastic ip and key pair caching

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/containers/KubernetesCluster.java
clouddriver-kubernetes/src/integration/resources/clouddriver.yml

There have been some one-off failures in kubernetes integration tests: https://github.com/spinnaker/clouddriver/runs/1103123724?check_suite_focus=true
The above job was successful after a re-run.
Failure message:
```
===
Given a secret manifest
When sending deploy manifest request
And sending force cache refresh request
And waiting on manifest stable
Then secret is deployed with a version suffix name
=== FAILED
org.opentest4j.AssertionFailedError: GET /cache/kubernetes/manifest did not returned processedTime > -1 for object "secret mysecret-v000" after 5 minutes
```
This PR introduces these changes:
* List filter code for the above request was rewritten from rest-assured jsonpath to plain java code
* More logging of relevant response fragments
* Test namespaces are created on startup, …

fix(test): Changed cache refreshed check, precreated ns

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLaunchTemplateCachingAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLaunchTemplateCachingAgentSpec.groovy

- added proxy method for describe launch templates
- updated caching agent to fetch versions in one call
- TODO(not supported): Add proxy method for describe versions

fix(aws): Fetch launch template versions at once

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/CreateLambdaFunctionConfigurationDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/CreateLambdaFunctionDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/CreateLambdaAtomicOperation.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/UpdateLambdaConfigurationAtomicOperation.java

Inputting memory and/or KMS Key Arn into Deck does not change Lambda values on creation or update.
1. CloudDriver is expecting `memory` from Deck when `memorySize` is provided by Deck on form submit and is provided to Deck by function cache.
2. CloudDriver is expecting `encryptionKMSKeyArn` from Deck when `kmskeyArn` is provided by Deck on form submit and is provided to Deck by function cache.
_fix_: 
1. `memory` &rarr; `memorySize` to match Deck and AWS data model
2. `encryptionKMSKeyArn` &rarr; `kmskeyArn` to match Deck and AWS data model

fix(aws): fix Lambda memory and KMS Key not settable

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

When calling `application/{}/serverGroups?expand=false` clouddriver returns an account field as part of the servergroupviewmodel.
However, when calling the same with `expand=true` the `account` field is missing and isntead we have an `accountName` field representing same information
This if difficult to deal with for API users. Adding, `account` field for consistency

fix(servergroups): add `account` property when expand=true

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonInstance.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonInstanceSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstance.groovy
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/model/TitusInstanceSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

This way, when a request for `expanded` results comes in it includes fields that we also return on non-expanded requests.

fix(servergroups): Add fields server group instanceType and instance availabilityZone fields

---

.github/workflows/integration_tests.yml
.github/workflows/pr.yml

There are two concerns when running integration tests to block PR builds:
1. Builds take a long time to complete. With the few tests added so far in clouddriver, build times were increased by about 13 minutes. This is only going to take longer as more tests are added to the service.
2. Test flakiness. Given the inherent complexity of integration tests, there could be sometimes when they fail in a particular execution without any code change.
The goal of integration tests is to find bugs before doing releases, the sooner the better. A good compromise would be to run them on pushes to `master` branch, so that PR builds are not delayed or blocked by the tests, but yet there's a clear indication of exactly which PR broke the tests, which is not possible when they are run on a scheduled basis …

feat(test/int): Run int tests only on pushes to master

---

clouddriver-kubernetes/src/integration/resources/clouddriver.yml
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KubernetesProviderSynchronizableSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgentTest.java

The performance improvements of the past few months have ultimately led to this flag no longer being read anywhere. Spinnaker now decides whether to read from the cache or to make a live call based on the context of the call rather than based on a flag.
From a practical perspective this means that:
* Users who had liveManifestCalls enabled will see the same fast deploys as always; bugs and race conditions with dynamic target selection have now been fixed.
* Users who had liveManifestCalls disabled will notice significantly faster deployments.

refactor(kubernetes): Remove liveManifestCalls flag

---

.github/workflows/integration_tests.yml
clouddriver-ecs/clouddriver-ecs.gradle
clouddriver-ecs/src/integration/README.md
clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/EcsSpec.java
clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/test/CreateServerGroupSpec.java
clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/test/EcsControllersSpec.java
clouddriver-ecs/src/integration/resources/clouddriver.yml
clouddriver-ecs/src/integration/resources/testoperations/createServerGroup-inputs-ec2.json

Adds new `integration` sourceSet to `clouddriver-ecs`, which contains setup and initial test cases for Amazon ECS provider integration tests. Package structure builds off precedents set in https://github.com/spinnaker/clouddriver/pull/4827. 
Intention is to have these run during the ["Integration Tests"](https://github.com/spinnaker/clouddriver/blob/master/.github/workflows/pr.yml#L29) step of the PR approval workflow.

feat(test): Add initial ECS integration tests

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/cache/client/LambdaCacheClient.java

fix (aws): Fix broken deserialization of uuid after aws lambda get

fix (aws): Fix broken deserialization of uuid after aws lambda get

---

clouddriver-lambda/README.md
clouddriver-lambda/src/main/java/com/netflix/spinnaker/config/LambdaConfiguration.java

CloudFormation and Launch Templates for AWS are already enabled by putting them under
`aws.features`. To unify how other AWS features are configured, we also change
`aws.lambda.enabled` to `aws.features.lambda.enabled`(deprecating `aws.lambda.enabled`).
This follows the conversation we had at the SIG meeting to also try and unify other AWS features.
/cc @kevinawoo 
/cc @akshayabd
/cc @clareliguori

feat(lambda-configuration): change the way lambda is enabled for aws

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgent.kt
clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgentTest.kt

Two problems here:
1. The `timestampDiff` returns an `INTERVAL` type, which jOOQ doesn't handle correctly when doing comparisons in MySQL.
2. `timestampDiff` parameters were reversed, so even if the first thing wasn't broken, it never would've cleaned anything up.
I'm not particularly sure how this had worked before. It definitely has worked before, because our oldest events are from April; long after we'd enabled this functionality.

fix(event): Force cleanup agent to compare ints

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/ResolveTitusJobId.java

It was unintentionally flagged as non-nullable.

fix(titus): `user` shouldn't be flagged as @Nonnull

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AmiIdResolverSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAlarmOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteScalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAlarmOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertAsgLifecycleHookAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertScalingPolicyAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/UpsertSecurityGroupDescriptionValidatorSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgentTest.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/SecretCacheClientSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/ServiceDiscoveryCacheClientSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/TargetHealthCacheClientSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/TaskHealthCacheClientSpec.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/compute/BatchComputeRequestImpl.java
gradle.properties
gradle/kotlin-test.gradle
gradle/kotlin.gradle

After this commit, we can use Java 11 language features and APIs.
I added a single var declaration to make it more obvious if any of our various CI systems are misconfigured.
I had to remove `final` from a bunch of Spock tests because of an issue with Spock: spockframework/spock#1011

chore(java11): Target Java 11

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/ResolveTitusJobId.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/DestroyTitusJobAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/description/DestroyTitusJobDescription.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/DestroyTitusJobCompletionHandler.java

Fixes an issue where entity tags would not be correctly removed after the related server group
was destroyed.

fix(titus): `DeleteServerGroupEvent` should use server group name rather than job id

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/SagaAtomicOperationBridge.java

This addresses an issue when a task consists of multiple saga actions.
```
[
{
"destroyServerGroup": {
...
}
},
{
"destroyServerGroup": {
...
}
}
]
```

fix(core): Use a random UUID for saga identifiers rather than task id/requestId

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgent.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlEventCleanupAgentConfigProperties.kt
clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/event/SqlEventCleanupAgentTest.kt

Agent isn't completing in time. Not a big deal, just kinda annoying. This will be good safety to have anyway.

fix(sql): Add config for limiting amount of aggregate cleanup

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DeployAtomicOperation.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsService.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/SagaContextAware.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/AbstractSagaAtomicOperation.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/SagaAtomicOperationBridge.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/TitusDeployHandler.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/CloneTitusServerGroupAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/RunTitusJobAtomicOperation.groovy

The idea is simple: Tasks can have more than one `AtomicOperation` submitted for it. Changes recently went in that made each saga ID unique to correctly support this use case, but it broke resumability of sagas in the process, and kind of caused some cascading failures. This PR fixes the resume capabilities. Resume requests will now search through all sagas attached to a Task and filter them down to a unique list of sagas (which it should already be, actually) based on the snapshotted description information: Each unique description is a unique atomic operation that has its own saga. The saga's ID is captured and added to the SagaContext, which is already used for bridge data between sagas and atomic operations - we use this context data if present, or create a new UUID if absent (which …

fix(saga): Support for multiple atomic operations in a single task

---

clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/config/EurekaProviderConfiguration.groovy

The EurekaProviderConfiguration does some manual ConfigurationProperties binding to allow eureka configuration
to behave differently than standard rest clients without polluting the application context with extra
OkHttpClientProperties beans.
This was failing if multiple ConfigurationService beans were present. We don't actually need any ConfigurationService beans to
successfully bind this configuration anyway, so this change just removes the autowiring.

fix(beans): fix eureka config binding with multiple ConfigurationService

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy

- updated to get the flag from the request

fix(aws): Dont override imdsv2 flag when cloning LT backed asg

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgentTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgentTest.java

Small but very important fix. Without checking to see if the `agent.getAccountName() equals data.account`, every caching agent that matches the handle for provider `cloudfoundry` and type `OnDemandType.ServerGroup or OnDemandType.LoadBalancer`, will proceed and create false evictions and potentially other harmful data inconsistencies. This fix will remove those data inconsistencies from happening and in theory, greatly speed up the Force Cache Refresh in the deploy stages for serverGroups and loadBalancers. Instead of N-CloudFoundry agents all processing onDemandCache and making subsequent API calls, only a single agent will now run to process the cache.

fix(provider/cf): only perform ondemand caching when account equals the credentials account

---

gradle/kotlin-test.gradle

I missed this in commit #4919, which switched us to targeting Java 11.

chore(kotlin): use the JDK 11 kotlin libs

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/DestroyTitusJob.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/DestroyTitusJobAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/DestroyTitusJobCompletionHandler.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DestroyTitusJobAtomicOperation.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/DestroyTitusServerGroupAtomicOperation.groovy

Rather than fail the action, no-op the delete and return an empty `DeleteServerGroupEvent`.

fix(titus): Improve handling for a non-existent Titus Job

---

build.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixSTSAssumeRoleSessionCredentialsProvider.java

fix(aws): use the Spinnaker region provider with the sts client builder, so that it defaults to the default region, when no region is defined

fix(aws): use the Spinnaker region provider with the sts client builder, so that it defaults to the default region, when no region is defined

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepository.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/view/CloudFoundryClusterProvider.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java

Fix a regression caused by clusterSummaries. ClusterSummaries should not fully hydrate the servergroups, hence needs to be changed to NONE for details. The underlying method that is ran got reverted to its original state until we can revisit this set of features at a later date. A test was added to ensure the functionality works as expected.

fix(provider/cf): fix regression caused by clusterSummaries

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java

Works against the V2 schema, no reason why it shouldn't work against V1 as well.

fix(titus): Store application ref for server groups and instances

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java

Reverts spinnaker/clouddriver#4992
This introduces a regression into the AWS provider when used side-by-side with Titus. I find it hard to believe that the AWS cloud provider plays nicely with any of the other cloud providers if they're populating the `application` attribute as well - which makes me suspect none of them do.
The problem is that with the SQL provider, we introduced a new `CacheView` method `getAllByApplication`, but there's no way of filtering what cloud provider to get all cached items by. This means that the `AmazonClusterProvider` is expecting only AWS resources, but with this change will also get Titus resources. This is all fine until it calls [Keys.parse()](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/cloudd …

Revert "fix(titus): Store application ref for server groups and instances"

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderCache.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlAdminCommandsRepository.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNames.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlSchemaVersion.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgent.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/controllers/CatsSqlAdminController.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlCacheConfiguration.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConstraints.kt
cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNamesTest.kt
cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgentTest.kt
clouddriver-sql/src/main/resources/db/changelog-master.yml
clouddriver-sql/src/main/resources/db/changelog/20200709-cats-v2.yml

Closes #4834, same PR, but with some fixes.
The NPEs that we were encountering are fixed, and the performance is looking good. Our normal deploy will need to be elongated to account for the cache warming, since the process has been maxing out our DB's CPU, and includes some deadlocks. These deadlocks disappear completely once the initial cache has been populated; performance afterwards is marginally improved, I suspect from the changes to how relationships are stored.
`SqlCache` desperately needs to be broken up into multiple classes, but that's for another time.
cc @mattsanta

perf(cats/sql): Introduce V2 SQL cache schema

---

Dockerfile.slim
Dockerfile.ubuntu

update awscli version from 1.16.258 to 1.18.152 and s3cmd from 2.0.1 to 2.0.2
The main benefit is to be able to use this command: https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html
> This command is supported using the latest version of AWS CLI version 2 or in v1.17.10 or later of AWS CLI version 1.
This is my first attempt at opening a pull request for this project, please let me know if I need to improve anything/follow a different process!

feat(aws): update awscli and s3cmd

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy

- updated to get image id from launch template data
- made lookup null-safe

fix(aws): Fixing NPE while retrieving imageId in launch templates

---

clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/EcsSpec.java
clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/test/CreateServerGroupSpec.java
clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/test/EcsControllersSpec.java
clouddriver-ecs/src/integration/resources/testoperations/createServerGroup-inputs-ec2.json
clouddriver-ecs/src/integration/resources/testoperations/createServerGroup-inputs-ecsCreateFails.json
clouddriver-ecs/src/integration/resources/testoperations/createServerGroupOperation-inputs-fargate-targetGroupMappings.json

Previously, these tests would succeed after successful submission of an ECS createServerGroup task. This change adds further checks, including:
* checking the task status after creation to ensure the ECS Service has been created
* ensures the expected ECS services calls were made
* ensures the content of the task definition and service reflect expected values given test input.

feat(test): extend ECS CreateServerGroup integ tests

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/cache/KeysSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy

Security group names in AWS can contain `:` which breaks the
cache key splitting. This patch uses the fact that the security group
ID must always start with `sg-` to find the actual end of the security
group name.
Resolves spinnaker/spinnaker/issues/6100 and closes #4984

fix(provider/aws): handle SGs with `:` in the name

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/DeleteLambdaAtomicOperation.java

Attempting to delete an AWS Lambda function that doesn't exist will throw a Null Pointer Error.
The delete request is attempting to access the function ARN without checking for `null` values.
_Fix_ : Ensure that neither the retrieved function nor the lambda client are `null` before attempting delete

fix(lambda): Fix NPE when delete operation is called on nonexistent function

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy

Short of rewriting this operation as a Saga, I'm looking to get a better indication
of how often the eventual consistency of AWS causes a problem.
This PR also increases the amount of time we'll wait for the upsert security group
tags operation to complete. This is a proxy for waiting for consistency around the
security group creation.

feat(aws): Some additional logging around upsert security group operations

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy

Only intended to include `e.getMessage()`.

fix(aws): Tweaked error message when security group tagging fails

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsCleanupProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsInfrastructureProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AbstractAmazonLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsInfrastructureProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/config/AwsConfiguration.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/AwsProviderSpec.groovy

This is the first step for AWS provider to use `CredentialsRepository`  introduced in https://github.com/spinnaker/governance/blob/master/rfc/account-management.md. 
- Use the new `BaseProvider` introduced in #4930 
- Move provider configuration to helper functions

feat(aws): Use Kork's BaseProvider

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy

**Problem:** When cloning a launch template-backed ASG via pipelines that need to `copyLastAsgAtomicOperation`, security groups were missing.
**Solution:** Security group IDs for launch templates are stored in the network interfaces. If the stage context does not explicitly have `launchTemplate.securityGroups`, the `networkInterfaces` need to be the source of truth for setting the security groups.

fix(aws/asg): Launch template security groups from network interfaces

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy

Depends on https://github.com/spinnaker/orca/pull/3967

fix(titus): Map /titus/images to elastic search docker image controller

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/MonitorTitusScalingPolicy.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/UpsertTitusScalingPolicy.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/events/TitusScalingPolicyModified.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/handlers/UpsertTitusScalingPolicyCompletionHandler.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/UpsertTitusScalingPolicyAtomicOperation.groovy

Fairly straightforward conversion into two idempotent actions:
1) `UpsertTitusScalingPolicy` is responsible for creating or updating the scaling policy.
2) `MonitorTitusScalingPolicy` is responsible for ensuring the create/update is applied.
State between the two actions is passed via a new `TitusScalingPolicyModified` event.

feat(titus): `upsertScalingPolicy` is now implemented as a saga for Titus

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/SagaAtomicOperationBridge.java
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/models/Saga.kt

`Saga.log()` will now also log to the configured `Logger` in addition to storing a log message event.
The logging occurs at 'info' level to remain consistent with `DefaultTask.updateStatus()`.

feat(core): Store saga identifier as an MDC attribute (`X-SAGA`)

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/exception/InvalidAccountException.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/AbstractLambdaAtomicOperation.java

When Lambda operations are performed for an account that does not have Lambda enabled, the operations are successful but Cache refreshes fail to load Lambda resources
Lambda should not allow operations to be performed when an account does not have Lambda enabled
_fix_: check whether lambda is enabled when getLambdaClient is called

fix(lambda): Fix Lambda being created when Lambda not enabled

---

Dockerfile.slim

https://bugs.openjdk.java.net/browse/JDK-8229872
We encountered this bug in java 11.0.5 which is the jdk on alpine 3.11.  Alpine 3.12 uses 11.0.8 which fixes it.  Of course other updates, but this is a safeguard.  Requires having enough overlays to go over 1024 in total overalay size which unlikely to be an issue on most builds but can't be entirely ruled out.

fix(upgrade): Docker image bump to 3.12 to fix potential JVM error on Git handling

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java

Corrects a regression from spinnaker/clouddriver#5004 where we did not consistently
index private images across all accounts.

fix(aws): Always index private images for an account

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerGroup.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

- Security groups were only being set on launch templates within the network interfaces. This PR sets `securityGroupIds` attribute when a launch template is being created.
- ASGs with launch templates were not rolling up `securityGroups` to the `ServerGroup` model. This PR also fixes a bug that sets the ASG security groups based on `securityGroupIds`, with a fallback to the `networkInterfaces` for safety.

fix(aws): Set launch template security group ids and rollup to asg data

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy

Updating `shouldSetLaunchTemplate` to help with account and region rollout
- `aws.features.launch-templates.allowed-accounts` to enable by account
- `aws.features.launch-templates.excluded-accounts` to exclude by accounts
- `aws.features.launch-templates.all-applications` to fully enable launch templates on everything but what lies in an exclusion list
Reverting regex support
- Application level exclusion/inclusion should be fairly narrow and transient as part of the rollout process
- For most cases excluding/allowing accounts and regions provide enough control for the rollout while keeping these properties simple

refactor(aws): Update launch template rollout flags and revert regex

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy

This stops the previous behavior where it would match any segment, e.g.: account, region, vpc, type
Previously if you queried  `api.myspinnaker.com/applications/{someaccount/someregion/somevpc}/loadBalancers`, you would get all load balancers in that account/region/vpc.  We match the load balancer key and look for the application name.  The `.*:` portion was too loose and would match the wrong segments from `aws:loadBalancers:account:region:loadbalancer-name:vpc:type`
This tightens up the regex to look only in the application portion of the key.

fix(amazon): Fix application name matching in load balancer cache keys

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Organizations.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Spaces.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/OrganizationService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/SpaceService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/Organization.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/Space.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundrySpaceCachingAgent.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/OrganizationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/SpacesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgentTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgentTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundrySpaceCachingAgentTest.java

Migrate Space and Org services to v3, from v2. Most of these changes are straight forward and required no refactoring. Some, however, required refactoring to keep up with the latest changes and conventions. For example, the v3 api uses Pagination objects instead of Page objects with metadata. Some objects structure also changed. Spaces now have access to their orgGuids through a relationship map. Originally a space object would have this orgGuid at the root. I've adjusted and added to various tests to make sure everything is working as expected. No new logic was implemented

feat(cf): update space and org services to use v3 endpoints

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

fix(aws): fixed failure to create launch template backed server group with spot instances
- added missing marketType
- using market options only to launch spot instances
https://github.com/spinnaker/spinnaker/issues/6114
https://github.com/spinnaker/spinnaker/issues/5989
1. Enable launch template support in Clouddriver
2. Create a server group backed by launch template like 
```
curl -H 'Content-Type: application/json' -d '{ "job": [ { "application": "hello", \
"setLaunchTemplate": true, "credentials": "my-aws-devel-acct", "strategy": "", "capacity": { "min": 1, "max": 1, "desired": 1 }, "targetHealthyDeployPercentage": 100, "cooldown": 10, "enabledMetrics": [], "healthCheckType": "EC2", "healthCheckGracePeriod": 600, "instanceMonitoring": false, "ebsOptimized": false, "iamRole": …
```

fix(aws): fixed failure to create launch template backed server group with spot instances

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandler.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandlerSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ReservationReportController.groovy

This also drops support for vpc/non-vpc differentiation.

feat(aws): Remove support for the legacy 'v1' reservation report

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/converters/UpsertTitusScalingPolicyAtomicOperationConverter.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/AbstractTitusDescriptionValidatorSupport.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/UpsertTitusScalingPolicyDescriptionValidator.java

Also added an additional `hasValidationErrors` tag to the `authorization.missingApplication`
metric.
This tag will allow us to silence some alerting. The presence of a validation error will
prevent execution (and this metric is meant to indicate operations that are executing but
lack application details).

feat(titus): Validate that `jobId` provided to `UpsertTitusScalingPolicy` operation

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

Launch templates cannot specify security groups in both the template data and the network interfaces.

fix(aws): Revert launch template setting security group ids

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy

Follow up to https://github.com/spinnaker/clouddriver/pull/5041
Some load balancers wouldn't get parsed because the regex required `:` at the end and didn't have the `-stack-detail` as optional

fix(aws lb): Parse LBs with dashes in them

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ScalableTargetsCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/SecretCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceDiscoveryCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/config/EcsProviderConfig.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgentSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ScalableTargetCachingAgentSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/SecretCachingAgentSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceDiscoveryCachingAgentSpec.groovy
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCacheTest.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgentTest.java

In preparation for ECS provider to implement `BaseProvider` and `CredentialsRepository` as introduced in [RFC](https://github.com/spinnaker/governance/blob/master/rfc/account-management.md) , ECS agents must implement `AccountAware` to remove agents when credentials are removed from repository. 
@allisaurus

feat(ecs): Make ECS agents implement AccountAware

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/IndexParser.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/helm/IndexParserTest.java

Fixes https://github.com/spinnaker/spinnaker/issues/6020 , by using existing `ComparableVersion` to compare two version strings instead of a full lexicographical comparison.

fix(helm): Semver version sorting

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy

added `capacityType` to instance information cached.
As [EC2/ Spot features](https://github.com/spinnaker/spinnaker/issues/5989) are added, it will be helpful to show capacity type (i.e. on-demand / spot) in instance information.
https://github.com/spinnaker/spinnaker/issues/5989
API response of `/instances/{account}/{region}/{instanceId}` includes `"capacityType": "spot"`  or `"capacityType": "on-demand"`
https://github.com/spinnaker/deck/pull/8688

feat(aws): added capacityType to instance information cached

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgentSpec.groovy

This PR make sure that only authoritative data types from `ClusterCachingAgent` will gets applied during on demand cache update. 
Fixes https://github.com/spinnaker/spinnaker/issues/6122

fix(cache/aws): Add authoritative type for on demand update

---

clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AbstractAccountCredentials.java

Addresses a problem with the `DefaultAccountCredentialsProvider` wherein duplicate `AccountCredentials`
were being returned.

fix(core): Default equals()/hashCode() implementation for `AbstractAccountCredentials`

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/ForceDestroyWatchdog.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java

Spawning `kubectl` jobs has a timeout controlled by `jobs.local.timeout-minutes` (default: 10 minutes), which is used for aborting the job.
The default implementation of apache commons exec uses `Process.destroy` for sending a SIGTERM signal to `kubectl`. Usually this works fine, but there may be some situations in which `kubectl` doesn't respond to that signal and may remain running for an unknown period of time.
This PR introduces a way for sending a SIGKILL signal (`kill -9`) to `kubectl` if it ignores the SIGTERM signal, by using `Process.destroyForcibly`.

feat(kubernetes): Send SIGKILL to kubectl

---

settings.gradle

Allows one to use core `aws` artifacts but opt out of ecs/lambda.

chore(gradle): Split `aws` and `aws-minimal` provider config

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/InstanceTargetGroupState.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/HealthState.java

Marking draining instances as "UP" would falsely finish a pipeline successfully.
More details about this bug is documented here: https://github.com/spinnaker/spinnaker/issues/5867
As well as a slack conversation here https://spinnakerteam.slack.com/archives/CB78MFQPP/p1588774672064600

fix(aws/loadbalancing): mark draining instances as out of service

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/client/RegionScopedTitusClient.java

Currently we set a 60 second deadline via an interceptor (internally, this is the GrpcRetryInterceptor).  However, we see calls throwing `DEADLINE_EXCEEDED` after 10 seconds and we do not know exactly why.  I'd like to experiment with setting a 30 second deadline on findTasks to see if that resolves the issue.

fix(titus): Set 30 second deadline on grpc blocking stub when calling findTasks

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/sdkclient/AmazonClientInvocationHandler.java

- Add a proxy to fetch launch tempalte version collectors
- extend support for constructing an `idKey` of the format `launchTemplateId:version`

feat(amazon): Add Edda proxy for LaunchTemplateVersions

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCachingAgentFilterConfiguration.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandler.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandlerSpec.groovy

This provides a filtering mechanism to include/exclude AutoScalingGroups based on configured name/value pairs. The intent of naming the filter configuration `AmazonCachingAgentFilterConfiguration` is to allow it to be reused for different agent filtering (load balancers etc).
This is needed to allow for a subset of AWS resources to be managed by Spinnaker (for our environment, exclude is enough, but added include for other use cases).

feat(aws): Add filtering of AutoScalingGroups to include/exclude based on Tags

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsAccountMapper.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsAccountMapperSpec.groovy

This addresses an issue where call to` /securityGroups` fails when a ECS account was removed but security group information is still in cache.

fix(ecs): Ensure null is returned when account does not exist

---

clouddriver-configserver/clouddriver-configserver.gradle
clouddriver-configserver/src/main/java/com/netflix/spinnaker/clouddriver/cache/CloudConfigRefreshConfig.java

The module `clouddriver-configserver` is misconfigured. It doesn't detect the source files in `src/main/java`. As a result, the jar file `clouddriver-configserver.jar` produced in builds lacks any java classes.
This can be easily verified if whithout this fix, you introduce a compilation error in `CloudConfigRefreshConfig` and run `./gradlew build -x test`, as it builds successfully.
Closes https://github.com/spinnaker/spinnaker/issues/6128

fix(dynamicAccounts): Included java files in source set

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandlerSpec.groovy

https://github.com/spinnaker/clouddriver/pull/5021 got this conditional backwards when adding additional cleanup agents.
Original conditional: https://github.com/spinnaker/clouddriver/pull/5021/files#diff-7a2ba10435894f582c87b3d6868072fea5ce68217d051fd739e7305e3998e3dbL246
Which was changed to: https://github.com/spinnaker/clouddriver/pull/5021/files#diff-e2d08201e4229c88257693e056afb5516a3fe2004c08b40cea98a1fb300a2c9bR256
This restores to the correct conditional.

fix(agents): Add additional cleanup agents when agentScheduler is null

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesManifestContainerBuilder.java

In some cases k8s api returns `lastTimestamp` with null value causing the `ManifestBuilder` to throw nullPointerException.
Made `lastEventTimestamp` optional and set default value for usecases when the key exists in the map but is null
Issue: https://github.com/spinnaker/spinnaker/issues/6181

fix(kubernetes): k8s event timestamp should be null safe

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/sagas/AbstractSagaAtomicOperation.java
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/provider/agent/EurekaCachingAgent.groovy

Uncovered this while implementing a saga in Kotlin which is a little more sticky about
arguments and return types that are marked `@Nonnull`.

fix(saga): In reality, the argument to `parseSagaResult` can be `null`

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerGroup.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/ServerGroup.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy

Moves the instance type determination (launch config vs template) to the `AmazonServerGroup`
and out of the `ServerGroupController`.

fix(aws): Better support for serializing `instanceType`

---

clouddriver-sql/src/main/resources/db/changelog/20201110-field-type-postgres.yml

Fix of the migration added in https://github.com/spinnaker/clouddriver/pull/5097

fix(sql): Permanently skip postgres field migration when not using postgres

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt

As written, cache inserts will deadlock themselves.
Actual `execute` is called at L606.

fix(sql): Remove accidental double execute on insert

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java

When you deploy an application to Kubernetes, if the Pod gets stuck in a Pending state because of Resource allocation (CPU, Memory) or a NodeSelector, clicking on the Red Pod in the UI the Pod Details Menu never loads and it throws an HTTP 403 error.
The issue is happening when Spinnaker tries to get metrics from the Pod in Pending State. To fix it I expanded the If condition in the topPod function based on logs I found:
```
java.lang.RuntimeException: com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor$KubectlException: Could not read metrics: Error from server (NotFound): podmetrics.metrics.k8s.io "atg-engineering/rbadillo-hello-spinnaker-deployment-9648fc79d-sl9bm" not found
Caused by: com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor$KubectlExcep …
```

Return Empty Pod Metrics List when Pod is in Pending State

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AbstractAmazonLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCachingAgentFilter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCachingAgentFilterSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgentSpec.groovy

This provides a filtering mechanism to include/exclude LoadBalancers (both classic and ALB/NLBs) based on configured name/value pairs. This expands on the previous ASG filtering done in #5089.
Tags are fetched via a separate `DescribeTag` call, which has a limit of 20 arns/names.
This is needed to allow for a subset of AWS resources to be managed by Spinnaker (for our environment, exclude is enough, but added include for other use cases).

feat(aws): Add filtering of LoadBalancers to include/exclude based on Tags

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java

Issue: https://github.com/spinnaker/spinnaker/issues/6199
If you have a Spinnaker application with different Kubernetes deployments associated with a project, the project dashboard never loads and throws an HTTP 500 error.
The issue is happening when clouddriver is trying to build a list of the images associated with a specific application. The List being used in the code is not mutable and that's causing the Exception.
To fix it, I changed the images List to be an ArrayList to force it to be mutable.
File:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/ProjectClustersService.java#L307
```
if (images != null) {
images.forEach(
image -> {
if (image != null && !b.images.contains(image)) {
b.images.add(image);
} …
```

Make images List in DeployedBuild class an ArrayList

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/AbstractCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskDefinitionCachingAgent.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskDefinitionCacheTest.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskDefinitionCachingAgentTest.java

* cache only task definitions associated with ECS services
Addresses https://github.com/spinnaker/spinnaker/issues/6063
This change reduces the number of unnecessary cache entries held by Spinnaker and, as a result, the number of `ecs:*TaskDefinition` API calls needed to populate the cache. 
Testing in an account with ~1000 task definitions (not necessarily associated w/ services) shows a reduction in the # of calls made to ECS during regular caching agent execution.
* 0 `DescribeTaskDefinition` calls were made during registrations of task defs NOT associated w/ a service (vs. ~1000 w/ previous version)
* 0 `ListTaskDefinition` calls made during a 30 window where no deployments were happening (vs. ~300 w/ previous version).
* Pipeline deployments succeed in slightly shorter (maybe …

feat(ecs): Improve task definition cache

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/AbstractTitusDescriptionValidatorSupport.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/DestroyTitusJobDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/DestroyTitusServerGroupDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/DisableTitusInstancesInDiscoveryDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/DisableTitusServerGroupDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/EnableTitusInstancesInDiscoveryDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/ResizeTitusServerGroupDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/TerminateTitusInstancesDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/TitusDeployDescriptionValidator.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/validators/UpsertTitusScalingPolicyDescriptionValidator.java

In my atomic operation preprocessor spelunking I noticed we have some unnecessary code that provides a credentials object in a validator - not needed because we already have the credentials object on the atomic operation description.

fix(titus): Remove use of account credentials provider in Titus validators

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java

We've seen an issue wherein competing in-flight requests to Titus result in multiple jobs with the same server group name.  This is due to a race condition in the Titus server group name validation handling, and something that will be addressed in Titus.  In any case, we can log and alert on this error.

chore(titus): Log duplicate Titus server group names by job ID

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/ServiceInstanceService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/ErrorDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v2/CreateServiceBinding.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

This change includes some refactoring for create service bindings that will allow us to use this same logic in a new stage specifically for binding to services with optional parameters. 
We've also moved the createServiceBindings() logic ahead of buildDroplet(). This allows the droplet creation to take advantage of environment variables/service bindings that are present now, rather than doing a restage after we've added service bindings.

feat(cloudfoundry): bind services before building droplet

---

clouddriver-ecs/src/integration/resources/testoperations/createServerGroup-artifact-FARGATE-capacityProviderStrategy.json
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServergroupDescriptionValidatorSpec.groovy

Rename capacityProviderStrategies to capacityProviderStrategy to align with CreateService api. As this is a new feature for this release, this would not be backwards incompatible.

fix(ecs): rename capacityProviderStrategies to capacityProviderStrategy

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy

relates to https://github.com/spinnaker/kork/pull/831

chore(web): Removed `IllegalArgumentExceptionHandler` as it has been moved to `kork-web`

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java

As a part of the Moniker PR, logic was removed that enabled filtering on the App name. This allowed the server group info to be returned quickly. In release 1.24.0, users have been seeing timeouts, and this change will look to add back the previously removed application filter.
Current 1.24.0 Release Experience: Users with large amounts of AWS resources (such as services, task definitions, and tasks) are starting to see their server group/clusters view timing out with errors.
Testing done: As this is a performance improvement, it is difficult to add unit tests (load tests would be the best to test this scenario).
- Manually tested it against my test stack. I'm not seeing any regression, and verified that the new Application filter (using Monikers) and the old Application filter (inferring …

fix(ecs): add application name filter to findCluster

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerV2Description.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperationSpec.groovy

In an effort to expand Ipv6 support to load balancers, clouddriver must support setting the ALB/NLB `IpAddressType`. 
Currently, clouddriver does not set this so it defaults to `ipv4` in AWS. With this PR, the value can be either `ipv4` or `dualstack` for _external_ load balancers (AWS has does not allow dual-stacking of internal load balancers since all IPv6 are public).

feat(amazon/lb): Allow external load balancers to set IpAddressType

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperation.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperationSpec.groovy

CloudFormation recently released a new feature to enable support for nested stacks in change sets; this enables that feature.
I put this behind a new config field, defaulting to disabled:
```
aws:
cloudformation:
changeSetsIncludeNestedStacks: false
```
I wasn't sure how to get the test spec to flip on the field, hence the duplication there.
** This requires upgrading `aws-java-sdk` to `>= 1.11.904`:
```
- ### Features
- This release adds ChangeSets support for Nested Stacks. ChangeSets offer a preview of how proposed changes to a stack might impact existing resources or create new ones.
```
References:
https://aws.amazon.com/about-aws/whats-new/2020/11/aws-cloudformation-change-sets-now-support-nested-stacks/
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/change-sets-for-n …

feat(aws): Enable nested stacks for cloudformation changesets

---

Dockerfile.slim

Fixes an issue where with 3.12 of alpine, python3 is now defaulted and that broke aws cli installation.

fix(docker): Fix docker.slim builds with python3 support

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/config/ArtifactConfiguration.java

Add the built-in credentials repositories that are not defined by `CredentialsTypeProperties`.

fix(artifacts): Fix default artifact credentials repositories

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java

This fixes a regression added in 1.23 but fixed in 1.24. Image caching agents were either public or private, we need both.

fix(aws): always schedule agent for private images

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixSTSAssumeRoleSessionCredentialsProvider.java

STSAssumeRoleSessionCredentialsProvider is immutable when created with
the builder. When aws-cn or aws-us-gov provider roles are configured setEndpoint is
called after build() resulting in an "UnsupportedOperationException".

fix(provider/aws): Fix STS role provider for AWS GovCloud and AWS CN

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgConfigHelper.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilder.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertScalingPolicyDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/SecurityGroupService.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AsgConfigHelperSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultLaunchConfigurationBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/BasicAmazonDeployDescriptionValidatorSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/SecurityGroupServiceSpec.groovy

- refactored config related to ASG creation into ASGWorker.AsgConfiguration (previously, class fields of AsgWorker)
- removed usage of LaunchConfigurationSettings in LaunchTemplate code path, replaced it with AsgConfiguration
- facilitates for easier addition of LT related features without an expanding list of method parameters
- moved security group related functions to SecurityGroupService (previously in DefaultLaunchConfigurationBuilder)
- extracted common config setup code to a helper, out of DefaultLaunchConfigurationBuilder
- added/updated unit tests
https://github.com/spinnaker/spinnaker/issues/5989
As part of adding AWS EC2 support for multiple instance types and instance diversification, some refactoring is necessary: 
* Current PR - ASG configuration can now be passed around and …

refactor(aws):  Refactoring to better encapsulate Asg config related fields and separate launch template/launch config code

---

clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/DestroyTitusJob.java
clouddriver-titus/src/test/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/DestroyTitusJobSpec.groovy

This can be a costly lookup should the job have many thousands of associated tasks.
If the job doesn't exist, Titus will return a `NOT_FOUND` exception that can be appropriately handled.

fix(titus): Avoid fetching the job before terminating it

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactCredentials.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/github/GithubArtifactCredentialsTest.java

Add 2 new settings to GitHub accounts (`credentials.github.accounts`) to download files directly without a second request:
- `useContentAPI` (defaults to `false`): when true, clouddriver will send the [proper media type request](https://docs.github.com/en/rest/overview/media-types) and download files directly.
- `githubAPIVersion` (defaults to `v3`)
It only needs a single request and as far as I know, it is the recommended way and works in all cases. We could default to t his method if it runs fine for some time.

feat(credentials): Use GitHub APIs to download artifacts in a single request

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderCache.kt
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AbstractClusterCleanupAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCleanupAgent.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonApplicationProvider.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProviderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandlerSpec.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/TitusCachingProviderConfig.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/ClusterCleanupAgent.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusApplicationProvider.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusClusterProvider.groovy
clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusTargetGroupServerGroupProvider.java

Clusters and Applications are global entities and can not be
authoritatively cached by a regionally scoped caching agent.
This moves them to INFORMATIVE and adds a new ClusterCleanupAgent
to handle eviction of clusters with no serverGroups.
Also includes changes in the Application and Cluster providers to
account for inconsistent reads (particularly when doing
titus streaming updates) by looking for the presence of cluster
or server groups rather than assuming the application -> cluster
relationship is valid.

fix(aws/titus cache): fix cluster and application cache eviction

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/InstanceTargetGroups.groovy

https://github.com/spinnaker/clouddriver/pull/5060 changed
deriveHealthState to return Draining however deriveInstanceHealthState
does not handle Drain which results in HealthState.Up

fix(aws/loadbalancing): Fix draining instances appearing as healthy

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/Keys.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/model/Application.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ApplicationCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsLifeCycleHandler.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/KeysSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsLifeCyclerHandlerSpec.groovy

This PR creates and initializes an empty ApplicationCachingAgent which will always return an empty list of Applications from the cache. The intent is that this is the initial commit prior to implementing logic within the ApplicationCachingAgent, that uses services to determine and store Applications and their relationship to an ECS service.

feat(ecs): add a default ECS Application Caching Agent

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy

For apps with launch templates enabled, IPv6 assignment can now be automated by configuration. In this phase of the rollout, only asgs in the `test` environment with the config enabled will be automated.

feat(aws/deploy): Auto-enable ipv6 in test by config

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonBlockDevice.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateServiceSpec.groovy

AWS EBS can be encrypted by customer managed key and it is supported with LaunchTemplate.
I added `kmsKeyId` in `AmazonBlockDevice` class and it is used to request AWS API to create LaunchTemplate.
See [this link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html) to check the parameters `AWS::EC2::LaunchTemplate BlockDeviceMapping`.

feat(provider/aws): EBS encryption with KMS key id on LaunchTemplate

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AmazonResourceTagger.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultAmazonResourceTagger.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/RegionScopedProviderFactory.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateServiceSpec.groovy

Implementations of the `AmazonResourceTagger` interface will be used to generate one or more
`LaunchTemplateTagSpecificationRequest` that will be attached to the generated `LaunchTemplate`.
When enabled, `DefaultAmazonResourceTagger` will generate two tags:
* `spinnaker:application`
* `spinnaker:cluster`
Configuration:
```
aws:
defaults:
resourceTagging:
enabled: true
```

feat(aws): Support for automatically tagging volumes created as a result of autoscaling activity

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy

In https://github.com/spinnaker/clouddriver/pull/5230 , logic to filter original `tags` based on `description.tags` was added 
This change adds a couple of additional checks 
- Adds null safe checks for `description.tags` 
- Handle a case where all additional tags are removed completely during an upsert, which would make the `description.tags` empty and will result in not removing the additional tag from the resource, introducing a dynamic config with these additional tags names as a failsafe ensures these additional tags are always part of the `deleteTag` request.

fix(aws): Additional checks during updates to security group tags

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessor.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/OrchestrationProcessor.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/DefaultOrchestrationProcessorSpec.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleHttpLoadBalancerAtomicOperation.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleInternalHttpLoadBalancerAtomicOperation.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

The tag will be `unknown` in the event that a `cloudProvider` is not available (not all operations
are cloud-specific).
This is step one to being able to clasify and better report the cause for failed operations in
`clouddriver`.

feat(core): Tag `orchestrations`, `operations` and `tasks` metrics with `cloudProvider`

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/ApplicationCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ApplicationCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/view/EcsApplicationProvider.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsLifeCyclerHandlerSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/view/EcsApplicationProviderSpec.groovy
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/cache/ApplicationCacheClientTest.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/cache/CommonCacheClient.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ApplicationCacheTest.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ApplicationCachingAgentTest.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/CommonCachingAgent.java

This change updates the application caching agent to store the application name as well as the services associated to that application as relationships. Storing these objects allows the EcsApplicationProvider to be able to query and retrieve all applications and their related services. Improving the search experience and returning the records quicker.
Previously, if users had too many services in their associated aws accounts, the search would time out, and throw an exception.
Tested by using the current logic, to perform multiple application searches (both using the application search and well as the shared search modal), as well as clicking through an application and deploying to ECS. Then deployed these changes and redid the same tests to validate that the previous behaviour continued …

feat(ecs): update application caching agent to store relationships

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppengineAttributeValidator.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/model/AppengineServerGroup.groovy
clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/clouddriver/appengine/provider/agent/AppengineServerGroupCachingAgent.groovy
clouddriver-appengine/src/test/groovy/com/netflix/spinnaker/clouddriver/appengine/deploy/validators/StandardAppengineAttributeValidatorSpec.groovy

Fixes spinnaker/spinnaker#6305
Uses the ServerGroup `loadBalancer` set to validate Appengine versions with identical names in differerent services(Load Balancers).

fix(clouddriver/appengine): Fix Validation errors when multiple services have same named versions

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupControllerSpec.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgentTest.groovy

- inspectDigest config flag allows the docker agent to fetch the config layer for a manifest with V2Schema
- looks under `config.Labels` for extra information regarding `buildNumber`, `commitId`, `branch`, and `jobName` that results in creating a docker artifact
- when the `/find` endpoint from the DockerController is called with `includeDetails=true` parameters, includes `commitId`, `buildNumbe`r and other metadata related to the created artifact in the response

feat(docker): for a V2Schema add inspectDigest to inspect docker metadata

---

CODEOWNERS

Adding myself as codeowner for cloud foundry, appengine, and lambda. This will allow us to more closely track the work thats being done within these modules

chore(codeowners): update codeowner for CF, appengine, lambda

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy

A `cloneServerGroup` does not explicitly set `associateIPv6Address`. This PR sets `associateIPv6Address` based on the network interface of the source server group.

fix(aws): Copy IPv6 assignment in CopyLastAsgAtomicOperation

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ArtifactControllerSpec.java

There are 2 types for artifacts: the type of artifacts credentials (e.g. github, gitlab, helm) and the type of artifacts (helm/chart, git/repo). The two endpoints in `ArtifactController` are called from Deck - just for helm artifacts - and pass an artifact type.
This should fix https://github.com/spinnaker/spinnaker/issues/6349.

fix(artifacts/helm): look up artifact credentials by supported type

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/DeregisterInstancesFromLoadBalancerAtomicOperationConverter.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/converters/RegisterInstancesWithLoadBalancerAtomicOperationConverter.java

Previously only the `existence` of a `targetGroupNames` is check to determine ALB/ELB. With this MR, it's adding extra checks on the value. It checks whether the value is empty or not
Fixes https://github.com/spinnaker/spinnaker/issues/6352

fix(aws/ALB): Check emptiness to distinguish ALB/ELB

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeployCloudFormationDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperation.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperationSpec.groovy

The `templateBody` field has a size limit of 51200 bytes; larger CFN templates need to be hosted in S3. This PR updates the CloudFormation deploy task to use `templateURL` if provided in the task input.
There will be a subsequent PR on orca to send `templateURL` if the given template artifact has a reference starting with `s3://`.
Corresponding PR: https://github.com/spinnaker/orca/pull/4079

feat(cfn): prefer templateURL over templateBody if provided

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsLifecycleHandler.java

Due to (potential) changes in bean ordering, `awsCleanupProvider.getAgentScheduler()`
may not always belonger null.
In these cases, `CleanupAlarmsAgent` and `CleanupDetachedInstancesAgent` would
not be added to the `AwsCleanupProvider`.

fix(aws): Ensure that the cleanup agents are scheduled

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderRegistry.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNamedCacheFactory.kt
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/MySqlCacheSpec.groovy
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/PostgreSqlCacheSpec.groovy
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlProviderCacheSpec.groovy
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/StaticProviderCacheConfiguration.groovy
clouddriver-api/src/main/java/com/netflix/spinnaker/cats/provider/ProviderCacheConfiguration.java

Allows for a provider to opt out of the default protection and allow a previously populated
collection to be emptied.

feat(cats): Support for overriding the full cache eviction protection on a per-provider basis

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy

**Steps to reproduce:** 
- previous ASG has an ipv6 address
- user sets `associateIPv6Address` to `false` in the UI, then clones the ASG manually
- new ASG still has an IPv6 address
**Cause:**
The `CopyLastAsgAtomicOperation` is only looking at the network interfaces, not the presence of the user-supplied flag (`assocaiteIPv6Address`). This causes the ipv6 to be copied from the network interface even if the user says otherwise.
**Solution**
Copy `associateIPv6Address` to the new asg description. If it is not explicitly `true` or `false` (aka not supplied by the user), then look to the network interface to copy the previous setting.

fix(aws): User input in cloneServerGroup is being overidden

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyServerGroupLaunchTemplateAtomicOperation.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareModifyServerGroupLaunchTemplate.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/PrepareModifyServerGroupLaunchTemplateSpec.groovy

There are two cases where we want to include previous version groups
1. The securityGroupsAppendOnly is explicitly set to true
2. The securityGroupsAppendOnly is not set to false and the payload doesn't include any security groups
Also includes a fixup around imageId resolution to fix an IDE warning (deferencing and Optional without
checking if it was present) that resulted in deleting some unused code.

fix(aws): updateLaunchTemplate wasn't including security groups from the previous version

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java

Allow users to override the S3 signer algorithm if they can't use the default. They can set the AWS client to use a different algorithm in their profile yaml:
```artifacts:
s3:
enabled: true
accounts:
- name: s3
signerOverride: S3SignerType
```
The AWS SDK validates the algorithm passed in and will throw an exception if the user tries to configure one that doesn't exist:
```
Caused by: java.lang.IllegalArgumentException: unknown signer type: NotARealType
at com.amazonaws.auth.SignerFactory.createSigner(SignerFactory.java:131) ~[aws-java-sdk-core-1.11.934.jar:na]
at com.amazonaws.auth.SignerFactory.getSignerByTypeAndService(SignerFactory.java:104) ~[aws-java-sdk-core-1.11.934.jar:na]
at com.amazonaws.AmazonWebServiceClient.computeSignerByServiceRegion(AmazonWebServiceClient.java:459) …
```

feat(s3): add signerOverride config option

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

When we deploy VMSS using azure cloud provider, have an option to specify managed identity ( User assigned or System assigned). This allows the process inside the VM to gain access to necessary azure resources with RBAC of the assigned identities without need for maintaining separate credentials for authentication/authorization. https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vmss
Refer issue: https://github.com/spinnaker/spinnaker/issues/5638
The changes are  to add two additional attributes which are optional in nature for server group deploy
- useSystemManagedIdentity ( if this is selected a system assigned identity is automatically assigned)
- userAssignedIdentities ( we can provide a comma separated list of user …

feat(clouddriver/Azure): Assign user/system managed identity during vmscaleset creation

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesApiVersion.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDaemonSetHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDeploymentHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesEventHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesIngressHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesReplicaSetHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesStatefulSetHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/AbstractKubernetesEnableDisableManifestOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/caching/KeysSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesApiVersionSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDeploymentHandlerSpec.groovy
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/daemonset/base-on-delete.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/daemonset/base.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/deployment/base-no-replicas.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/deployment/base.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/replicaset/base-no-replicas.yml
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/replicaset/base.yml

This change makes Spinnaker incompatible with Kubernetes prior to 1.14.
The reason for this change is to enable the now General Available
Ingress API. This was added in Kubernetes 1.19. To make this change the
client library had to be updated. Since 1.16 removed a bunch of APIs
that change now affects us, and a few of the old APIs got removed.
As far as I can tell the oldest supported version of Kubernetes is now
1.14. It was released in 2019, almost two years ago to date. It's been
End of Life since December 2019.
BREAKING CHANGE: This breaks Kubernetes prior to 1.14.

feat(kubernetes): Breaking, Update API versions

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Processes.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/api/ProcessesService.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/ProcessRequest.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServerGroupDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

This features supports processes which can be defined in cloud foundry manifests. For more information about processes see [here](https://docs.cloudfoundry.org/devguide/multiple-processes.html#about-processes). Buildpacks typically define the processes for an application however a Procfile can also be used to define these processes and their starting commands. See [here](https://docs.cloudfoundry.org/devguide/multiple-processes.html#push-with-multiple-processes) for more information regarding Procfiles and processes.

feat(cloudfoundry): add support for manifest processes

---

.github/workflows/integration_tests.yml
clouddriver-aws/clouddriver-aws.gradle
clouddriver-aws/src/integration/README.md
clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/AwsBaseSpec.java
clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/AwsTestConfiguration.java
clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/test/CreateServerGroupLaunchConfigEnabledSpec.java
clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/test/CreateServerGroupLaunchTemplatesEnabledSpec.java
clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/test/CreateServerGroupSpec.java
clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/utils/TestUtils.java
clouddriver-aws/src/integration/resources/clouddriver.yml
clouddriver-aws/src/integration/resources/testinputs/createServerGroup-basic.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-Region not configured.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-basicAmazonDeployDescription.amiName.empty.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-basicAmazonDeployDescription.application.empty.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-basicAmazonDeployDescription.availabilityZones.empty.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-basicAmazonDeployDescription.instanceType.empty.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-burstingOff-basicAmazonDeployDescription.bursting.not.supported.by.instanceType.json
clouddriver-aws/src/integration/resources/testinputs/description_validator_test_inputs/createServerGroup-burstingOn-basicAmazonDeployDescription.bursting.not.supported.by.instanceType.json

* Adding integration tests for AWS EC2 provider for CreateServerGroup operation (with launch configuration / launch template settings enabled)
* Adding AWS provider integration tests to Github workflow
Look for `AWS EC2 Provider Integration Tests` in https://github.com/pdk27/clouddriver/runs/2090227653?check_suite_focus=true

Adding integration tests for AWS EC2 provider

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/BaseTest.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/InfrastructureIT.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/containers/KubernetesCluster.java
clouddriver-kubernetes/src/integration/resources/clouddriver.yml
clouddriver-kubernetes/src/integration/resources/manifests/networkPolicy.yml

Kubernetes integration tests now use separate namespaces for both test accounts.
The issue sharing namespaces is that if an object is deployed to one account, it will still show in the results of the second account. This makes troubleshooting more difficult, so having them separate is for cleaner results and easier troubleshooting.

fix(kube/test): Separate namespaces for accounts in tests

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesCustomResourceHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsSpec.groovy
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsTest.java

When you try to delete a Kubernetes CRD via Spinnaker UI (kubernetesRawResources Tab) you get an error.
The issue is happening when Spinnaker tries to delete a CRD. The problem is that Kubernetes Kind was being passed as None causing the following error:
Logs:
```
2021-03-25 19:19:37.759 ERROR 1 --- [tionProcessor-0] c.n.s.c.o.DefaultOrchestrationProcessor  : com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor$KubectlException: Failed to delete none/mytestcrd from engineering: error: the server doesn't have a resource type "none"
at com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor.delete(KubectlJobExecutor.java:154)
at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials.lambda$delete$12(KubernetesCredentials.java:475)
at …
```

fix(kubernetes): address crd delete error

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/names/EcsServerGroupNameResolver.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/names/EcsServerGroupNameResolverSpec.groovy

fix(aws): Fixes name resolver when stack is empty.
With the current name comparison, if some names (like stack) are empty it would compare them to a `null` value, not adding them to the currently taken sequences. 
The functionality was working on 1.22 and the bug was introduced on https://github.com/spinnaker/clouddriver/commit/fc08d9a75c0498a5e56ac8e9851c8125d8dca7af.

fix(aws): Fixes name resolver when stack is empty.

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
cats/cats-test/src/main/groovy/com/netflix/spinnaker/cats/cache/CacheSpec.groovy

The current implementation leads to inconsistencies with similarly named applications.
ie. `es_test` and `esetest`

fix(cats): '_' can be used as a single character wildcard (in sql databases) and should be escaped

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AutoScalingWorker.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/BasicAmazonDeployDescriptionValidator.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyServerGroupLaunchTemplateDescription.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/BasicAmazonDeployDescriptionValidatorSpec.groovy

[AWS Nitro Enclaves](https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave.html) is a feature that allows for isolated execution environments, or _enclaves_, to be launched alongside of normal instances.
This PR adds a property, `enableEnclave`, to the deploy description. Restrict
this feature to launch templates since it can only be enabled via
Launch Templates
Fixes spinnaker/spinnaker#6396
I created a clouddriver container off this branch by first compiling the JAR:
```
./gradlew clouddriver-web:installDist -x test
```
and built a container with `Dockerfile.ubuntu` and pushed it to dockerhub. I then launched a [Minnaker](https://github.com/armory/minnaker) with OSS spinnaker, and applied the following patchfile:
```
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService …
```

feat(aws/enclave): Enable Nitro Enclave option

---

Dockerfile.slim

Routine version bump. 1.21.0 has been released.
1.20.6 is the latest [`kubectl` release](https://github.com/kubernetes/kubectl/releases) - presumably 1.21.0 is due soon but we are still keeping to 1 minor version behind the latest controller version.
Note this does not fix: https://github.com/spinnaker/spinnaker/issues/6420

chore(kubernetes): Bump kubectl binary version to 1.20.6

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/validator/KubernetesValidationUtil.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/validator/KubernetesValidationUtilSpec.groovy

It was discovered that live namespace supplier was being ignored on a deploy manifest operation, causing a slower failure when an invalid namespace was supplied. Rather than the validation failing with "wrongNamespace" the operation would be attempted and eventually fail for the expected reason. By changing the validator to to use `getDeclaredNamespaces` instead, this problem is solved.

fix(namespaceValidation): validation should use declared namespaces in order to leverage live namespace suppliers and remove omitted namespaces

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationCachingAgent.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonCloudFormationCachingAgentSpec.groovy

This add onDemand cache capabilities for cloud formation stacks.
Right now it always returns the result of the query stacks but nothing
ensures the data has been refreshed. Most likely the cause of
https://github.com/spinnaker/spinnaker/issues/6125
This PR handles the force cache refresh request for a stack, 
maintains the onDemand cache namespace entries and implement the 
pending on-demand requests logic that enabled orca to start polling
until the refreshed entity is retrieved.

feat(aws/cloudformation): Add onDemandCache logic

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsLifecycleHandlerTest.java

KubernetesNamedAccountCredentials::getNamespaces was already a best effort call since it could return an empty list in
case of an error communicating with the kubernetes cluster.  With this change, it doesn't attempt to communicate with
the kubernetes cluster and returns the last cached valued (or an empty list if there's nothing in the cache).  This can
dramatically speed up the /credentials endpoint if it's called soon after clouddriver starts, before a caching agent has
made a live call to the cluster to retrieve the list of namespaces.

perf(kubernetes): change KubernetesNamedAccountCredentials::getNamespaces to not make live calls to a kubernetes cluster

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatus.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProviderSpec.groovy

Kubernetes jobs may be executed by many pods, and each pod status is saved to the pipeline execution context. If the number of pods is large enough, the pipeline execution context may grow big enough to make orca crash.
The only place where pod status is needed is in the UI to extract the logs of the most recently created pod. A new field `mostRecentPodName` was added to the response that replaces the list of pod status. The full list of pod status may still be returned by setting the new configuration flag `kubernetes.jobs.detailed-pod-status: true` in `clouddriver.yml`.

feat(kubernetes/job): Return the most recent pod name instead of the list of pod status

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesSourceCapacity.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestReplicasTest.java

Replicas value was not being set if it didn't already have a value, however users expect that they can omit the value when leveraging the use-source-capacity strategy. Fix is setting the value despite there not already being one. Additionally, if a third party integration creates a manifest via JSON that serializes the replica count as an integer, a casting exception occurs, so this includes an update to play nicely with integers.

fix(manifest-replicas): more flexibility with get/set replicas value

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java

fix(6430): Adding missing block device mappings for new launch templates (thanks @JooeunAhn)
https://github.com/spinnaker/spinnaker/issues/6430

fix(6430): Adding missing block device mappings for new launch templates

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/Keys.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ApplicationCachingAgent.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/KeysSpec.groovy

This change updates the application caching agent to use a new namespace ECS_APPLICATIONS rather than reusing the existing APPLICATIONS namespace.
Verified:
1) ECS provider deployments still work 
2) ApplicationCachingAgent is continuing to log messages
Fixes: spinnaker/spinnaker#6084

fix(ecs): refactor applicationCachingAgent to use unique namespace

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy

Implements https://github.com/spinnaker/spinnaker/issues/6429
Deployment w/ `enableExecuteCommand` set to `true` succeeds & `ecs execute-command` on service task works:
* server group JSON
* Deployment result
* service description:
* interactive command session started:
Using [`ecs exec`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-enabling-and-using) requires that your task definition includes a [task role](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html#ECS-RegisterTaskDefinition-request-taskRoleArn) with relevant SSM permissions. Failure to specify a task role will result in a failed deplyoment:

feat(ecs): Add support for enableExecuteCommand

---

clouddriver-web/clouddriver-web.gradle

The removal of the AWS integration with Entity Tags as part of #4923 mean that the required modules for core Entity Tags functions was not included in the `clouddriver` build.
This change changes the dependency on `clouddriver-elasticsearch` in `clouddriver-web` from test only to implementation. This ensure that the ES module is included in the build.
Fixes spinnaker/spinnaker#6331

fix(entitytags): include required module

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestTest.java

Before this PR, when using generateName in kubernetes manifests deployed via deploy manifest or run job (manifest), "null" appears for job names in some places in deck, e.g. Swapping out artifacts in job null from context..., and in pipeline execution source.  For example:
After this PR:

Fix null job name in status

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgent.java

the state can be used to determine whether a lambda function is ready
to receive traffic.

fix(lambda): cache state and state reason info for lambda functions

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupController.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegistryImageLookupControllerSpec.groovy

even though microservices like Keel expect clouddriver's `dockerRegistry/images/find`
endpoint to filter the returned list by repository or tag, the functionality was not
implemented in clouddriver. this PR adds it.
/cc @JonGilmore @nabuskey

fix(docker): filter images with repository and tag

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AutoScalingWorker.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/AmazonResourceTagger.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/DefaultAmazonResourceTagger.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateServiceSpec.groovy

- Fixing a bug introduced in a previous PR. 
- Restricted usage of AsgConfiguration's default constructor as it doesn't makes sense to use it without config fields. 
- `blockDeviceTags` is not supported by `modifyServerGroupLaunchTemplateDescription`. So, replacing empty ASG Configuration with null to be explicit.

fix(aws): Fixing invalid creation of empty AsgConfiguration

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java

We have experienced some pipelines failures from time to time due to transient kubectl errors. This PR attempts to address that by adding retrycapability for such kubectl calls. 
This capability can be enabled by setting `kubernetes.jobExecutor.retries.enabled: true`. It is turned off by default.
Any new kubectl errors on which retries will be performed can be configured using the `kuberentes.jobExecutor.retries.retryableErrorMessages` key, which accepts a list of strings. The code does a string.contains() check on this error message - so only certain keywords from the original message can be added here, for example, `TLS handshake timeout`.
Logs are added to indicate the k8s account, the action (such as get, delete etc), the k8s resource as well as retry attempts.
Example log:
```
Retry …
```

feat(kubernetes): add retries to kubernetes job executor

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/CreateCloudFoundryServiceBindingAtomicOperation.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java

The error messages surfaced to Deck when a CF service doesn't exist don't make sense to end users who aren't familiar with the code.
I've taken the implementation from the `CreateCloudFoundryServiceBindingRequestAtomicOperation`, which fetches the GUIDs from CAPI and then verifies each service to bind has a GUID. This differs from the previous implementation that just checked the number of services returned == number of services wanting to bind.
I also removed this size check from the Create Service Bindings operation - as far as I can tell it wasn't adding anything, since each service was checked immediately afterwards anyway.
cc @zachsmith1 (I can't run tests locally at the moment due to corporate dependency management, working on it!)

feat(cloudfoundry): improved error messages for failed service bindings

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DestroyCloudFoundryServiceAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DestroyCloudFoundryServiceDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DestroyCloudFoundryServiceAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DestroyCloudFoundryServiceAtomicOperationTest.java

Adding a new flag to the destroy service stage that will attempt to unbind any applications prior to destroying the service. It will only allow unbinding server groups that belong to the spinnaker application running the pipeline.

feat(cloudfoundry): add remove bindings option to destroy service

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java

The filter for getting existing ASGs didn't include the "final" (v999) ASG. At v998 any subsequent deployment tries to create v999, and fails if that already exists. This means at v999 the cluster name is unusable for further deployments.
To fix this I'm including the final ASG in the query filter, so that v999 is recognised as a "taken slot".

fix(cloudfoundry): include final asg when checking taken slots

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperationUnitSpec.groovy

Fixed copy of block devices in clone op. 
Fixed LOC - https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy#L283 
Seems like an incomplete LOC introduced in https://github.com/spinnaker/clouddriver/pull/5244/files
The "clone" behavior for block devices implemented in this PR, is the same behavior seen when creating a server group with `copySourceCustomBlockDeviceMappings` enabled - [code ref](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy#L442)
Manually created server groups with block devices and cloned them.  Block devices were created / cloned as …

fix(aws): Fix copy of block devices in clone operation

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstances.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/ServiceInstanceResponse.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverter.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/description/DeployCloudFoundryServiceDescription.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java

This is a new flag that will allow cloudfoundry services to be versioned similar to how spinnaker handles applications. If this flag is checked, a version will be appended to the service name. I.e. servicename-v001. We are also returning the previous version name via a field called previousInstanceName to the stage so that a following stage can delete, etc. 
consolidates: https://github.com/spinnaker/clouddriver/pull/5422 and https://github.com/spinnaker/clouddriver/pull/5418

feat(cloudfoundry): add versioning to cf services

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/names/EcsServerGroupNameResolver.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/names/EcsServerGroupNameResolverSpec.groovy

The new naming logic for ECS services doesn't cope if the ECS cluster
only contains service names that have no sequence. This change fixes
that by ignoring services without a sequence for the purposes of
calculating the next free sequence number.
Reporting in Slack #ecs channel here https://spinnakerteam.slack.com/archives/C686H9WG7/p1626356252008700

fix(ecs): handle service names without sequences

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesDeleteManifestDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeleteManifestOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeleteManifestOperationTest.java

Previously, setting options.cascading in a delete manifest pipeline was a no-op. Now, it's another way (in addition to options.orphanDependents) to control whether kubernetes performs a cascading delete. If both
orphanDependents and cascading are specified, orphanDependents takes precedence. 
Also, this fix will allow clouddriver to look at the value of the "cascading" option in the Deck UI (which was not happening previously). 
The change was tested using unit tests with different pipelines as test cases (as seen in `clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeleteManifestOperationTest.java`).
The change was also tested in a testing environment. In the testing environment, a pipeline with a Deploy and Delete Manifest Stage (with …

fix(kubernetes): support options.cascading in delete manifest pipelines

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClient.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/config/CloudFoundryConfigurationProperties.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/config/CloudFoundryProviderConfig.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/HttpCloudFoundryClientTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/AbstractLoadBalancersAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/ScaleCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsTest.java

Adds a flag to Cloud Foundry accounts "onlySpinnakerManaged" that is disabled by default. When enabled any application in the foundation that does not end in "vXXX" (i.e. was not deployed by Spinnaker) will be ignored.
This is useful when foundations have historically been deployed to by other tooling. Since Spinnaker creates unconfigured applications for server groups it can see, these non-Spinnaker apps block the creation of the same app name in Spinnaker.
Whilst checking the app name ends in a version is a bit of a hack, unfortunately other avenues are unavailable:
* Metadata endpoints can't be supported until the minimum supported version for CF is bumped.
* Environment variable endpoints may be restricted for security reasons (so we can't check for the pipeline ID env variable)

feat(cloudfoundry): onlySpinnakerManaged flag for server groups

---

build.gradle
gradle/spek.gradle

jcenter because it's no longer alive (https://status.bintray.com/) and mavenCentral
because the io.spinnaker.project plugin handles repository declaration.

chore(build): remove repository declarations

---

CODEOWNERS

Also update the kubernetes directory to the current kubernetes SIG
owners.

chore(codeowners): Update the CODEOWNERS for the new googlecloud SIG.

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/common/AzureUtilities.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

Regardless of OS type, the health extension for Azure is using ApplicationHealthWindows. This updates the health provider type to ApplicationHealthLinux in the case of Linux.
This is an enhancement/fix for Linux on https://github.com/spinnaker/clouddriver/pull/5256

fix(provider/azure): Use ApplicationHealthLinux health provider type for Linux OS

---

clouddriver-docker/clouddriver-docker.gradle

fix(vulnerability): Remove fixed version of commons-io dependency to accommodate safer version from kork.

---

.github/workflows/bump_dependencies.yml

As of
https://github.com/spinnaker/front50/commit/57c9922924edc4f6a737c92e0d59d23f5e3174d6#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19
from August 6, 2020, front50 no longer depends on clouddriver, so don't attempt to bump
clouddriver's version there.
See https://github.com/spinnaker/clouddriver/runs/3334358289?check_suite_focus=true#step:3:11 for an example of the failure message:
```
[main] INFO io.spinnaker.bumpdeps.BumpDeps - Cloning https://github.com/spinnaker/front50 to /tmp/bumpdeps-git-9683647897421732365/front50
[main] ERROR io.spinnaker.bumpdeps.BumpDeps - Exception updating repository front50
java.lang.IllegalArgumentException: Couldn't locate key clouddriverVersion in front50's gradle.properties file
at …
```

fix(build): don't bump the version of clouddriver in front50

---

clouddriver-titus/clouddriver-titus.gradle
gradle.properties

```
> Task :clouddriver-titus:compileJava FAILED
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/LoadBalancerServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
^
symbol:   class GrpcGenerated
location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/JobManagementServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
^
symbol:   class GrpcGenerated
location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/EvictionS …
```

fix(titus/build): use version 1.37.1 of io.grpc.* to fix compiler errors

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerProvider.groovy

If a server group has been scaled down or deleted, the load balancer
should still be visible in deck, but because of an NPE the whole
page fails to load.
This has been tested against an Azure account.

fix(provider/azure): Allow empty server groups on load balancers

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureInstance.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureServerGroupResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy

This fix fixes two things related to Azure instance health:
1. The health extension couldn't be applied to any instances because the health
extension required int port (it was a String everywhere)
- fixed by changing type to int
2. The health extension wasn't being used by the cluster view at all.
- fixed by adding a health extension check after the default
"is running" check
This has been tested in two ways:
1. Unit tests
2. Deployment of scale sets to my Azure account

fix(provider/azure): Use health extension in instance status

---

clouddriver-aws/src/integration/java/com/netflix/spinnaker/clouddriver/aws/AwsTestConfiguration.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoader.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AccountsConfiguration.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoaderSpec.groovy
clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/EcsTestConfiguration.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsAccountBuilder.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsInitializer.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsCredentialsParser.java
clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/security/EcsAccountBuilderTest.java

* move accounts out of the CredentialsConfig class so that it is easier to custom bind them when reading accounts from a local config file.
This is for the following issue: https://github.com/spinnaker/spinnaker/issues/6492

refactor(aws): refactor accounts

---

clouddriver-aws/clouddriver-aws.gradle
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCustomBinderConfiguration.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/CustomAccountsConfigurationProvider.java

This PR allows custom property binding support for loading aws accounts from a config file. This is turned off by default, which means that the accounts will be loaded via the default way, which is relying on spring boot to do the binding. 
This is enabled by setting `aws.custom-property-binding-enabled: true`.
This is for the following issue: https://github.com/spinnaker/spinnaker/issues/6492

feat(aws): enable custom property binding capability for aws accounts

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/BaseHttpArtifactCredentials.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitJobExecutor.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactAccount.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactAccountTest.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/github/GithubArtifactCredentialsTest.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/config/LambdaServiceConfig.java

Added support for tokenAuth with gitRepoArtifactCredentials and made BasicHttpArtifactCredentials reload auth headers for every call instead of during object instantiation.

feat(artifacts): support tokenFile for GitRepoArtifactCredentials and reload auth headers

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/converters/UpsertAzureAppGatewayAtomicOperationConverterSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/template/AzureAppGatewayResourceTemplateSpec.groovy

In order to be able to store TLS certificates in key-vault and use them on an application gateway, you are required to use a Standard_V2 Application Gateway.
This change, coupled with a change in deck (forthcoming), will allow users to select between Standard_Small (v1) and Standard_V2 SKUs. This change is safe on its own, but not beneficial by itself.
**Summary of changes**
1. Use input `sku` for App Gateway sku
1. When updating existing App Gateway, keep the same sku
2. Select tier based on input sku (`Standard` for `Standard_Small` sku and `Standard_v2` for `Standard_v2` sku)
3. Select sku of public IP based on SKU of App Gateway
4. Update `apiVersion` to `2018-04-01` to allow v2 App Gateway sku
**Testing Done**
1. Unit tests
2. Tested (together with changes in deck) the following:
1. …

feat(provider/azure): Use v2-sku for Application Gateways

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy

Caused by this PR: https://github.com/spinnaker/clouddriver/pull/5494
This usage of `isServerGroupDisabled` (which was renamed) was missed.

fix(provider/azure): Fix isServerGroupDisabled for app gateway

---

clouddriver-titus/clouddriver-titus.gradle
gradle.properties

Fix in favor of https://github.com/spinnaker/clouddriver/pull/5514. The guava version being pulled in was causing issues.

fix(titus/build): use version 1.37.1 of io.grpc.* to fix compiler errors (#5487)

---

clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupWithoutLoadBalancersAtomicOperation.groovy

If no load balancer is selected, make sure the resource group exists and create it if not. The ability to deploy an Azure scale set (server group) with no load balancer was introduced in https://github.com/spinnaker/clouddriver/pull/5494.
**Testing Done**:
To recreate problem:
1. Created a new application `fooapp`
2. Created pipeline
3. Added deploy step to pipeline with load balancer null
4. Tried to deploy
Got "Resource group 'fooapp-canadacentral' could not be found."
After fixing problem:
1. Created new application `barapp`
2. Created pipeline
3. Added deploy step to pipeline with load balance null
4. Tried to deploy
Successfully deployed.

fix(provider/azure): Create RG if no load balancer

---

clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgentTest.java

buildCacheData uses parallel stream, so passing in anything other than a
concurrent hashmap results in race conditions. In this case, the test
was passing in a plain hashmap when it should have been a concurrent
hashmap
Signed-off-by: benjamin_j_powell <benjamin_j_powell@apple.com>

fix(clouddriver-lambda): flakey test

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/config/KubernetesConfiguration.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicatorTest.java

- This PR implements the second fix from this issue: https://github.com/spinnaker/spinnaker/issues/6528. 
- We have more than 2000+ k8s accounts in our setup. Even after the clouddriver app starts up, the pod is not marked as ready by kubernetes until the health check is successful. This health check involves looking at the health of the various cloud providers, db and other resources. We have seen that in our setup, the k8s health check takes a long time to complete since it  attempts to load all the declared namespaces for each of these accounts by making a live API call to the cluster. This can take as much as 35-40 mins, hence disabling it provides us with a lot of benefit.
As seen by the logs below, the clouddriver app started at `2021-09-10 17:45:54.775`:
```
2021-09-10 17:45:54.775 …
```

feat(k8s): provide an option to turn off account health check for k8s accounts

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsLifecycleHandler.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsLifecycleHandlerTest.java

- This PR implements the first fix from this issue: https://github.com/spinnaker/spinnaker/issues/6528. 
- We have more than 2000+ k8s accounts in our setup. When clouddriver starts up, it attempts to load all the declared namespaces for each of these accounts by making a live API call to the cluster. In our setup, we have observed this action to take 35-40 mins, which is how much of a benefit it is for us to disable it.
- Since users may be relying on this capability, and would not like this to be disabled by default, we have made this an opt-in capability. By default, these namespaces will be loaded when credentials are added. If someone wants to opt out of it, they can set 
`kubernetes.loadNamespacesInAccount: false`
Note: we only provide this option when a credential/account is added. …

feat(k8s): provide an option to bypass getting namespaces when adding new k8s accounts

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoader.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy

- This PR implements the last fix from this issue: https://github.com/spinnaker/spinnaker/issues/6528. 
- We have 450+ aws accounts in our setup. We have noticed that it takes a long time for clouddriver to parse these aws accounts, which leads to slow clouddriver start up times. 
For 456 accounts, it takes  7m 42s to parse AWS accounts.
```
2021-09-17 16:20:38.504 INFO 1 --- [ main] c.n.s.c.a.s.AmazonBasicCredentialsLoader : attempting to parse 456 aws accounts provided as input
2021-09-17 16:20:38.504 INFO 1 --- [ main] c.n.s.c.a.s.c.AmazonCredentialsParser : Parsing aws account: aws-iam-account
...
2021-09-17 16:28:19.564  INFO 1 --- [           main] c.n.s.c.a.s.c.AmazonCredentialsParser    : Parsing aws account: clane-ec2-account-add-test-01
2021-09-17 16:28:20.567  INFO 1 --- [ …
```

feat(aws): provide a configurable option to parse aws accounts in a multi-threaded fashion

---

clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy

fixes the flakiness in the test introduced in #5532

test(aws): fix flaky test

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java

Avoid an NPE in orca when no instances are present

fix(cloudfoundry): Avoid NPE when no instances are present.

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java

Manifest attributes are unfortunately set/transferred between two different manifest attributes classes. Timeout was missing from the converter class. This code should ultimately be changed to leverage a single class for representation.

fix(cloudfoundry): add timeout to converter

---

clouddriver-web/src/main/java/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java

At least for s3, this can lead to connection pool exhaustion.  See https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/S3Object.html#getObjectContent-- which says:
> If you retrieve an S3Object, you should close this input stream as soon as possible, because the object contents aren't buffered in memory and stream directly from Amazon S3. Further, failure to close this stream can cause the request pool to become blocked.

fix(artifacts): close leaking input stream when downloading artifacts

---

clouddriver-titus/clouddriver-titus.gradle

```
Execution failed for task ':clouddriver-titus:extractIncludeProto'.
> Could not resolve all files for configuration ':clouddriver-titus:compileProtoPath'.
> Could not resolve com.google.protobuf:protobuf-java:[3.2.0,).
Required by:
project :clouddriver-titus
> Failed to list versions for com.google.protobuf:protobuf-java.
> Unable to load Maven meta-data from https://dl.bintray.com/netflixoss/com/google/protobuf/protobuf-java/maven-metadata.xml.
> Could not get resource 'https://dl.bintray.com/netflixoss/com/google/protobuf/protobuf-java/maven-metadata.xml'.
> Could not GET 'https://dl.bintray.com/netflixoss/com/google/protobuf/protobuf-java/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

fix(titus): Removing reference to bintray repo

---

clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy

In Spring Boot 2.3, native elasticsearch transport has been removed as both elasticsearch and spring data won’t support in upcoming releases. Support for the Jest library has also been removed. Please refer https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes
This fix is required for upgrade activity of spring boot from 2.2.x to 2.3.x

fix(elasticsearch): Unpinning elasticsearch package and removing deprecated Elasticsearch transport and Jest library

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy

of EXECUTE because account permissions do not currently have
EXECUTE defined as a potential permission type.
Also fixed some copy/paste errors to make the swagger messages around
the cancelJob route correct.

fix(jobs): Update account permission check to check for WRITE instead

---

clouddriver-sql/clouddriver-sql.gradle

When we are using spring boot 2.2.x (existing kork) we did not face below error, and as we move for spring boot 2.3.x we face error as given below:
```
> Task :clouddriver-sql:compileKotlin FAILED
e: /clouddriver/clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt: (18, 30): Unresolved reference: databind
e: /clouddriver/clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt: (40, 23): Unresolved reference: ObjectMapper
e: /clouddriver/clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/TaskMapper.kt: (18, 30): Unresolved reference: core
e: /clouddriver/clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/TaskMapper.kt: (19, 30): Unresolved reference: databind
e: …
```

fix(clouddriver-sql): add missing com.fasterxml.jackson.core:jackson-annotations and com.fasterxml.jackson.core:jackson-databind dependencies

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java

Moving the "should cache" checks prior to the call to map so that unnecessary API calls aren't made for apps that won't be cached anyway.

fix(cloudfoundry): skip API calls for apps that won't be cached

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactAccount.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactCredentials.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactCredentialsTest.java

Add token auth credentials support
* Implements TokenAuth interface in BitBucketArtifactAccount
* Update on BitbucketArtifactCredentials (similar to GitHubArtifactCredentials)
When using a valid token, after invalid token was used
Swap token inside tokenFile

feat(artifacts/bitbuket): add token auth credentials support

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentials.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/security/CloudFoundryCredentialsTest.java

The `/credentials` endpoint was failing when clouddriver had an invalid cloudfoundry account, returning a `400 - Bad Request`.  The root cause was that Lombok was generating an additional unignored getter for the cloudfoundry client field (the class already has 2 Json Ignored getters for that field), so whenever a call for expanded credentials `/credentials?expand=true` was made, jackson tried to serialize it and made expensive (and unnecessary) calls to the cloudfoundry api and caused the 400 errors if the account is invalid.
This small fix improves latency for valid accounts and removes the 400 errors for invalid accounts.
This should be backported to the latest `1.27.x` release.

fix(cloudfoundry): Remove lombok generated getter

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSecurityGroupCachingAgent.groovy

The code change is to address the issue of duplication of securityGroups  when using a SharedVPC network [#4373](https://github.com/spinnaker/spinnaker/issues/4373)
In case of using a Shared VPC Network the firewall rules of service project are adding the firewalls of host project because of which there is duplication of securityGroups
With this modification only the firewalls of existing project will be populated and resolves the issue

fix(gce) : duplication of firewall rules when using shared vpc network

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy

The code change is to address the [#6544](https://github.com/spinnaker/spinnaker/issues/6544) issue, where the retry logic is not performed for 503 , 429 error codes 
In the [GCP document](https://cloud.google.com/apis/design/errors#retrying_errors) those are suggested for retry operation 
The RETRY_ERROR_CODES list is modified to include 429 , 503 error codes

fix(gce) : retry logic on GCP APIs

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelper.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelperSpec.groovy

This test was failing whenever the suffix is generated before the second
hand turns and the expected string is calculated for a different
timestamp. Now the test uses a fixed clock using the instant the test
starts.

fix(aws/test): Flaky test update

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/config/AwsConfiguration.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AutoScalingWorker.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/LaunchTemplateRollOutConfig.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AutoScalingWorkerUnitSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/LaunchTemplateRollOutConfigSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandlerUnitSpec.groovy

- refactor of launch template roll out config into its own class for reuse and readability
This refactor was done for upcoming PRs for https://github.com/spinnaker/spinnaker/issues/6483 as the dynamic config code path needed to be reused. 
- tested with some upcoming changes with unit tests, integration tests and manual testing by creating server groups.

refactor(aws): Refactoring launch template roll out config

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

Cloud Foundry [allows memory/disk size to be specified](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#memory) as `G`, `GB`, `M` or `MB`, but Spinnaker currently only handles `G` or `M`. This PR adds support for `GB` and `MB`.

feat(cf): allow disk/memory values specified in GB/MB

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java

These classes (specially `KubernetesCredentials`) cannot be extended in plugins and contain a lot of logic. Allowing them to be extended will make it possible for users to change the behavior of the kubernetes provider using plugins.

feat(kube/ext): Make KubernetesCredentials and KubectlJobExecutor extensible

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/CustomKubernetesCachingAgentFactory.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgentDispatcher.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgentFactory.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesKind.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CustomKubernetesHandlerFactory.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgentDispatcherTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgentTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesUnregisteredCustomResourceCachingAgentTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java

BREAKING: The changes in this PR modify the default behavior of the kubernetes provider from caching all infrastructure, to caching only objects shown in the classic spinnaker infrastructure screens (clusters, load balancers and firewalls). Running pipelines no longer rely on the cache anymore since Spinnaker 1.23, so it's safe to assume that the cache is only used for populating the UI.
The config options introduced allow to continue caching all the kinds like before, useful when using the "raw resources" UI screen, which displays every kubernetes kind.
Configuration
```
kubernetes:
cache:
enabled: (true|false)   # (Default: true). Whether caching is enabled at the provider level.
cacheAll: (true|false)  # (Default: false). Whether to cache all kubernetes kinds or not. If this value is …
```

feat(kube/cache): Only cache spinnaker infra kube objects

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/ServerGroupMetaDataEnvVar.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java

Spinnaker currently caches all user provided environment variables on an application and displays them in Deck. This is a problem because people often provide secrets as environment variables, which are then displayed in Deck.
This PR filters the environment variables Spinnaker caches to only the metadata ones that Spinnaker sets itself (pipeline execution ID, artifact info etc).
The changes in `CloudFoundryServerGroup` are just cleanup when I opened the file, replacing deprecated annotations etc.

feat(cf): filter out non-Spinnaker environment variables from caching

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/config/AccountDefinitionConfiguration.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizerService.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/AccountDefinitionModule.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jackson/mixins/CredentialsDefinitionMixin.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionAuthorizer.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionMapper.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionSecretManager.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionService.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizerServiceSpec.groovy
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionMapperTest.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsParser.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/config/KubernetesConfiguration.java
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/security/SqlAccountDefinitionRepository.kt
clouddriver-web/src/main/java/com/netflix/spinnaker/clouddriver/controllers/CredentialsController.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerSpec.groovy

This refactors some things in preparation for user secrets support along with updating the type discriminator handling for account definitions.
These changes are independent of https://github.com/spinnaker/fiat/pull/928 and https://github.com/spinnaker/kork/pull/942, and I've noted TODO comments on where relevant updates related to those PRs will be added (with additional tests).

feat(core): Update account management API

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
clouddriver-docker/src/main/java/com/netflix/spinnaker/config/DockerRegistryAccountDefinitionSourceConfiguration.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/config/KubernetesAccountDefinitionSourceConfiguration.java

This integrates Docker Registry Clouddriver accounts to take advantage
of the new self-service on-boarding account management API. Given
that Docker Registry accounts already use kork-credentials, this
is simpler than usual.

feat(docker): Docker Registry account management

---

gradle.properties

to pick up google artifact registry publishing fixes
Doing this manually rather than backporting ~7 PRs

chore(dependencies): bump spinnakerGradleVersion (#936)

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeleteManifestIT.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/utils/KubeTestUtils.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeleteManifestOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeleteManifestOperationTest.java

https://github.com/spinnaker/clouddriver/pull/5426 is a previous PR related to this one.
Consider this basic layout of the json for a delete manifest stage:
```
{
"deleteManifest": {
"account": "account"
"app": "app",
"cloudProvider": "kubernetes",
"manifestName": "kind name",
"options": { ... }
},
}
```
There are two relevant properties in the options object: `cascading` and `orphanDependents`.  Both before and after this PR, orphanDependents takes precedence.  If it's specified, cascading is ignored.  Here is how the various values for cascading and orphanDependents map to `--cascade` options to `kubectl delete`
|option| before this PR|after this PR|
|------|---------------|------------|
|orphanDependents: "true"|--cascade=false|--cascade=orphan|
|orphanDependents: …

feat(kubernetes): support propagation policy in delete manifest stage

---

clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt

Fix active tasks listing which is used for graceful shutdown.
First problem is that we're comparing a.task_id with constant literal 't.id' instead of read field value. So results are always empty.
Second is that we're fetching results by field name with table alias (t.task_id) which is not working, at least on standard mysql 5.7 (Field (null) is not contained in Row). Fixed this by explicitly selecting required field (a.task_id) instead of all fields.

fix(sql): active tasks listing for graceful shutdown

---

clouddriver-web/pkg_scripts/postInstall.sh

Currently installing `spinnaker-clouddriver` results in `kubectl`
version 1.23.5 being installed.
This commit changes behaviour to install the same version as currently
specified in the `Dockerfile.slim|ubuntu` files rather than the latest stable
version.
FWIW the script doesn't upgrade `kubectl` if it is already installed which is
great as some users may manage this component separately via Ansible/etc.
However this does present a problem if/when an update to a later clouddriver
version would normally install with a newer `kubectl`.
No changes in this regard.

fix(kubernetes): Pin Debian Package version of kubectl as well

---

clouddriver-core/clouddriver-core.gradle
clouddriver-sql/clouddriver-sql.gradle

While upgrading spring cloud to Hoxton.SR12, we encountered below issues :
```
/clouddriver/clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsConverter.java:27: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
^
/clouddriver/clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsConverter.java:44: error: cannot find symbol
public T getCredentialsObject(@NotNull final String name) {
^
symbol:   class NotNull
location: class AbstractAtomicOperationsCredentialsConverter<T>
where T is a type-variable:
T extends AccountCredentials<?> declared in class AbstractAtomicOperationsCredentialsConverter …
```

fix(dependency): Issue of missing javax.validation:validation-api dependency while upgrading the spring cloud to Hoxton.SR12 in kork

---

clouddriver-titus/clouddriver-titus.gradle

On May 11, builds (e.g. https://github.com/spinnaker/clouddriver/runs/6395450456?check_suite_focus=true, https://github.com/spinnaker/clouddriver/runs/6396984248?check_suite_focus=true and https://github.com/spinnaker/clouddriver/runs/6396922814?check_suite_focus=true) started failing with e.g.:
```
> Task :clouddriver-titus:compileJava
if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
^
symbol:   method isStringEmpty(Object)
location: class GeneratedMessageV3
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/java/com/netflix/titus/TitusVpcApi.java:413: error: cannot find symbol
```
According to https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-java/, com.google.protobuf:3.21.0-rc-1 arrived on May 11, so …

chore(titus): limit protobuf to 3.17.3

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateBuild.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/CreateBuildTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java

Currently we set process config and scale the app/processes after building the droplet. This causes issues if the droplet requires more memory to build (e.g. lots of Python dependencies to install).
`cf push` uses a v2 endpoint to create applications which allows specifying scale when creating the app, whereas we are using a v3 endpoint which does not have those fields. Scaling is therefore a separate call.

fix(cf): scale app before building droplet

---

.github/workflows/codeql-analysis.yml

We don't want/need this to run in fork's.

chore(ci): Only run CodeQL on Spinnaker repos

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeployCloudFormationDescription.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeployCloudFormationAtomicOperation.java

Allow specification of notificationARNs for changesets and stack create/update actions. This directs CFN to send events to specified SNS topic(s). The behavior of the sdk is to treat empty list as unset.

feat(cfn): add property notificationARNs

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationConverterNotFoundException.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/AnnotationsBasedAtomicOperationsRegistrySpec.groovy

Currently when an AtomicOperationConverterNotFoundException gets thrown, the error message is not being properly set and is resulting in a null message in the logs.
```
com.netflix.spinnaker.clouddriver.orchestration.AtomicOperationConverterNotFoundException: null
at jdk.internal.reflect.GeneratedConstructorAccessor389.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
....
```
Set this error message for …

fix(core): set error message for AtomicOperationConverterNotFoundException

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/controllers/ManifestController.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/names/KubernetesResourceAwareNames.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotatorTest.java

the getManifest() endpoint fails to return Kubernetes system resources which have the prefix `"system:"` in their names. See [the Caution Note here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-subjects) for more details about such resources.
> Caution: The prefix system: is reserved for Kubernetes system use, so you should ensure that you don't have users or groups with names that start with system: by accident. Other than this special prefix, the RBAC authorization system does not require any format for usernames.
This fix allows getManifest() endpoint to deal with such resources.
* API Call in question:
```
curl localhost:7002/manifests/test-account/kube-system/clusterrole%20system%3Acoredns?includeEvents=false -H "X-SPINNAKER-USER: someuser"
```
* Results …

feat(kubernetes): enable getManifest() to return Kubernetes system resources

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/ops/AzureOpsConfig.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/application/model/AzureApplication.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/converters/DeleteAzureLoadBalancerAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/ops/converters/UpsertAzureLoadBalancerAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/converters/DeleteAzureSecurityGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/securitygroup/ops/converters/UpsertAzureSecurityGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/EnableAzureServerGroupAtomicOperation.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/DestroyAzureServerGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/DisableAzureServerGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/EnableAzureServerGroupAtomicOperationConverter.groovy
clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupWithAzureLoadBalancerAtomicOperation.java
clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupWithoutLoadBalancersAtomicOperation.groovy
clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/ResizeAzureServerGroupAtomicOperationConverter.java

In Azure, deployments complete immediately regardless of the health status of the instance. This causes deployments of bad code to bring down a working service.
When deploying Azure VM scale sets, wait for the scale set to become healthy before marking it complete. If not healthy after a period of time, mark the deployment as failed.
This also fixes a bug where if the server group did not come up for some reason other than timeout, it would not actually get cleaned up.
1. Deploy healthy VM scale set
2. Deploy unhealthy VM scale set (I changed my customData cloud-init script to not work correctly)
3. Wait to see if Spinnaker marks the deployment complete
4. Spinnaker does not show the deployment completes

feat(provider/azure): Wait for server group healthy before continuing

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionSecretManager.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionSecretManagerTest.java

If you enable Fiat and if you do not set permissions to accounts in Clouddriver the automatic triggers fail with permission denied.
before this change, https://github.com/spinnaker/clouddriver/pull/5666 anonymous user had permissions to access Clouddriver accounts

fix(core): ignore roles for anonymous user to access account

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy

Before this change, if a scale set was unhealthy at the outset and became healthy after a period of time, the instance state never got updated, so Spinnaker always saw it was unhealthy.

fix(provider/azure): Fix scale health

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/template/AzureAppGatewayResourceTemplateSpec.groovy

When a server group is deployed to a load balancer or application gateway, the server groups that are associated with that load balancer or app gateway are appended to a tag named `serverGroups` on that load balancer or app gateway. This tag isn't used for anything within clouddriver.
If a scale set is destroyed outside of Spinnaker, the tag does not get cleaned up. Tags in Azure have a maximum length of 256 characters. For a server group such as `foo-bar-v001`, this means that having 20 server groups destroyed outside of Spinnaker would prevent a new scale set from being deployed.
Since these tags were not used for anything besides debugging, I just removed them entirely. They will not be cleaned up from existing load balancers, nor will they ever be modified by Spinnaker.
* Verified …

fix(provider/azure): Remove unused serverGroups tags

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-web/clouddriver-web.gradle

In 2016 there was an addition of the Microsoft SNAPSHOT repo to temporarily
fix an issue. The change was supposed to be short term, according to the
original PR #402.

fix(build): Remove temporary workaround from 2016

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureComputeClient.groovy

- Azure healthy instance checks create many calls to the resource pages on Azure ultimately resulting in "Too many requests" errors on the portal pages.
- increase the timeout to 5 seconds

fix(azure): increase health interval

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java

k8s-kind listing is able to return partial results when not enough permissions in the service account exist but because we are throwing an error even partial entries are not being cached.
This fix will not throw an error when it is permission related only for k8s caching.

fix(caching): K8s cache affected when not enough permissions in service account

---

clouddriver-appengine/src/main/groovy/com/netflix/spinnaker/config/AppengineConfiguration.groovy

We are getting the following error
```java
***************************
APPLICATION FAILED TO START
***************************
Description:
Field credentialsRepository in com.netflix.spinnaker.clouddriver.security.AbstractAtomicOperationsCredentialsConverter required a bean of type 'com.netflix.spinnaker.credentials.CredentialsRepository' that could not be found.
The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)
Action:
Consider defining a bean of type 'com.netflix.spinnaker.credentials.CredentialsRepository' in your configuration.
```
there was a fix as well for Artifacts using `CredentialsTypeBaseConfiguration` class in https://github.com/spinnaker/clouddriver/pull/5203/files
Spring is not smart enough to identify …

fix(appEngine): lazy init for App Engine beans for credentials

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/converters/DeleteLambdaProvisionedConcurrencyAtomicOperationConverter.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/converters/DeleteLambdaReservedConcurrencyAtomicOperationConverter.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/DeleteLambdaProvisionedConcurrencyDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/DeleteLambdaReservedConcurrencyDescription.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/DeleteLambdaProvisionedConcurrencyAtomicOperation.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/DeleteLambdaReservedConcurrencyAtomicOperation.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/DeleteLambdaProvisionedConcurrencyAtomicOperationTest.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/DeleteLambdaReservedConcurrencyAtomicOperationTest.java

This PR is to solve an issue found on this plugin [AWS Lambda](https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker), we are adding the possibility to delete both Provisioned and Reserved Concurrencies when deploying and routing a lambda stages.
The updates on the plugin are on this PR [Plugin PR](https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/pull/117).

feat(Aws-Lambda): Added Endpoints to delete Concurrencies

---

clouddriver-google-common/src/main/groovy/com/netflix/spinnaker/clouddriver/googlecommon/security/GoogleCommonCredentials.groovy

This is to address the issue [#6661](https://github.com/spinnaker/spinnaker/issues/6661)
Without scope, application default credentials results in authenticate failure. This PR fixes the issue by adding the scope.

fix(google): Added scope to the credentials

---

clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ReplacerTest.java

```org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'getName'.
Error when introspecting properties was :
- No getter for property 'getName' in io.kubernetes.client.openapi.models.V1ConfigMapProjection 
Error when introspecting fields was :
- Unable to obtain the value of the field <'getName'> from <class V1ConfigMapProjection {
items: null
name: first-config-map
optional: null
}>
at org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:88)
at org.assertj.core.util.introspection.PropertyOrFieldSupport.getValueOf(PropertyOrFieldSupport.java:60)
at org.assertj.core.extractor.ByNameSingleExtractor.apply(ByNameSingleExtractor.java:29)
at …
```

fix(clouddriver-kubernetes): Changed property to name from getName

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.slim
Dockerfile.ubuntu

Build docker images for multiple architectures
Motivation:
Allow running & experimenting with Spinnaker locally on Macbok M1.
Relevant docs:
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
Similar MR:
https://github.com/spinnaker/rosco/pull/886

Arm64 support

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcrImageProvider.java

I'm using ECS via Spinnaker, but I can not use some ECS images.
The reason is why your regular expression.
https://github.com/spinnaker/clouddriver/blob/287acf36bd4ab4441f2ed8419b88261e0ff5474a/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcrImageProvider.java#L47
This regular expression cannot support upper case tags.
So I create PR to fix it.
You guys can check this regular expression below link.
https://regex101.com/r/wWPZFM/1

fix(ECS): support upper case on the tag of image

---

cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java
cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentSchedulerSpec.groovy
cats/cats-test/src/main/groovy/com/netflix/spinnaker/cats/test/TestAgent.groovy

* There is an edge case where the `activeAgents` map in the `ClusteredAgentScheduler` may still contain an agent even after it has been unscheduled, which prevents the agent from being scheduled again in the future.
* The motivation for actively cleaning such entries from the map is to ensure that no agent is in such a bad state that it can't be rescheduled again. In a normal workflow, the agent is removed from the map when [agentCompleted(String, long)](https://github.com/spinnaker/clouddriver/blob/master/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java#L243-L249) is called from [run()](https://github.com/spinnaker/clouddriver/blob/master/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredAgentScheduler.java#L …

fix(cats/redis): explicitly remove an agent from the activeAgents map when it is unscheduled 

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterControllerSpec.groovy

The [getForAccountAndNameAndType](https://github.com/spinnaker/clouddriver/blob/e62a8ffcce5ccdd1139184e7ae64d9d1da560f8a/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy#L147) method can be made more efficient if the cloud provider to use is determined first.
Presently, it invokes all the cloud providers and then filters on the results via the type property.
Instead, if we first select the correct cloud provider using the type key, then we would do less work since we wouldn't unnecessarily be invoking all the other cloud providers. This PR adds a test to show the inefficiency and how it is fixed after the change.

perf(web/cluster): make getForAccountAndNameAndType() more efficient

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/model/Front50Application.java
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/CustomKubernetesCachingAgentFactory.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/Front50ApplicationLoader.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCacheDataConverter.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgentDispatcher.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgentFactory.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesUnregisteredCustomResourceCachingAgent.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesCachingProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CustomKubernetesHandlerFactory.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCachingAgentDispatcherTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesCoreCachingAgentTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/KubernetesUnregisteredCustomResourceCachingAgentTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/caching/view/provider/KubernetesDataProviderIntegrationTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/names/KubernetesManifestNamerTest.java
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/caching/agent/applications-response-from-front50.json

This PR introduces a check to verify if the application obtained from a k8s manifest actually exists in front50 or not. This check can be configured by setting: 
```
kubernetes.checkApplicationInFront50: true # defaults to false
```
Old behavior: 
- A manifest would be cached or not depending on the following rules:
```
- if a manifest's caching properties has ignore == true, then it will not be cached.
- Otherwise, if an account is configured to be "onlySpinnakerManaged", and
"moniker.spinnaker.io/application" annotation is empty, then it will not be cached.
In all other cases/combinations, it will be cached.
```
New Behavior:
- A manifest would be cached or not depending on the following rules:
```
- if a manifest's caching properties has ignore == true, then it will not be cached.
- …
```

feat(kubernetes): Add a check to verify if application name obtained from a kubernetes manifest exists in Front50

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/controllers/PodController.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProviderSpec.groovy

Spinnaker doesn't seem to handle retrieving property file contents properly when a job may have multiple pods. Under the covers, it runs the `kubectl logs jobs` command, which doesn't give the right answer if there are two pods running at the same time for the same job. In such cases, kubernetes always defaults to the first pod, but in certain scenarios, we would want to query the second pod for logs as the first one may have failed but the second one may have succeeded.
This PR enables adding a new endpoint to directly query property file contents from a pod, i.e. do `kubectl logs pod/<pod-name>` under the covers.
it is the responsibility of the client (orca in this case) to supply the correct pod name.

feat(kubernetes): add support for retrieving run job logs from a specific pod

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.java

We found that `CatsOnDemandCacheUpdater.handle()` is printing the payload in the logs, exposing sensitive data / secrets. 
When the [lambda plugin](https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker) is enabled, it will send requests with environment variables in the body (`envVariables` field) if they are set. Environment variables can be secrets such as github tokens. 
This can be reproduced by invoking a lambda function or editing an existing lambda function via deck.
Example log: 
```
2022-09-09 12:48:30.341  INFO 1 --- [.0-7002-exec-10] c.n.s.c.cache.CatsOnDemandCacheUpdater   : com.netflix.spinnaker.clouddriver.aws.provider.AwsProvider/non-prod/us-east-2/LambdaCachingAgent-OnDemand handled Function in 2327ms. Payload: {architectures=[x86_64], …
```

fix(core): Remove sensitive payload data from logs

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-web/clouddriver-web.gradle
gradle.properties

since spring 2.4.13 brings it in (transitively).  The version from spring boot takes precedence, so the value we specify here is ignored.
Another approach would be to make the version here match what spring boot brings in (currently 11.0.3), but then future changes could again invalidate what's here.  If some future version of spring boot stops bringing in io.kubernetes:client-java, builds will fail with unspecified version, at which point we can restore kubernetesClientVersion.
Snippets of ./gradlew clouddriver-web:dependencies
before:
```
+--- project :clouddriver-kubernetes
|    +--- io.kubernetes:client-java:11.0.1 -> 11.0.3
```
after:
```
+--- project :clouddriver-kubernetes
|    +--- io.kubernetes:client-java -> 11.0.3
```
Related orca PR: https://github.com/spinnaker/orca/pull/4310

chore(kubernetes): stop specifying the version of io.kubernetes:client-java

---

gradle.properties

See e.g. https://github.com/spinnaker/clouddriver/blob/25bed1fa85a9f75dcdc4faa453fb33baf2d7b8aa/.github/workflows/build.yml#L10

chore(build): give local builds as much memory as we do in CI

---

cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlCacheSpec.groovy

Without this, we've seen:
```
org.gradle.internal.exceptions.DefaultMultiCauseException: Multiple Failures (2 failures)
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Mapped port can only be obtained after the container is started
java.lang.NullPointerException: <no message>
at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:196)
at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapter.java:226)
at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:192)
at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:79)
at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRu …
```

fix(cats-sql/test): prevent null pointer exception during cleanup

---

clouddriver-configserver/clouddriver-configserver.gradle

to stay up to date, and to resolve CVE-2022-42889 which org.apache.commons:commons-text:1.9 is subject to.  See https://nvd.nist.gov/vuln/detail/CVE-2022-42889.
Snippet of `./gradlew clouddriver-web:dependencies` before this change:
```
|    |    \--- com.github.wnameless.json:json-flattener:0.11.1
|    |         +--- com.fasterxml.jackson.core:jackson-databind:2.11.3 -> 2.12.6.1 (*)
|    |         +--- org.apache.commons:commons-text:1.9
|    |         |    \--- org.apache.commons:commons-lang3:3.11 -> 3.9
|    |         \--- com.github.wnameless.json:json-base:1.2.0
```
and with this change:
```
|    |    \--- com.github.wnameless.json:json-flattener:0.14.2
|    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2 -> 2.12.6.1 (*)
|    |         +--- …
```

chore(configserver): use version 0.14.2 of com.github.wnameless.json:json-flattener

---

clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-titus/clouddriver-titus.gradle

Spring boot 2.4.13 brings in version 1.27 of org.yaml:snakeyaml (see https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.13/spring-boot-dependencies-2.4.13.pom) which takes precendence over what we specified here (1.24), so there's no functional change.  See these snippets of ./gradlew clouddriver-titus:dependencies before
```
+--- org.yaml:snakeyaml:1.24 -> 1.27
```
and after this change:
```
+--- org.yaml:snakeyaml -> 1.27
```
The equivalent thing happens in clouddriver-cloudfoundry.

chore(deps): remove version specification from org.yaml:snakeyaml

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifest.java
clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesManifestSpec.groovy
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeployManifestOperationTest.java
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/crd-manifest-spec-is-list.json
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/deploy/crd-manifest-spec-is-list.yml

Before this change, attempts to deploy a manifest where the spec was a list, e.g.
```
apiVersion: test.example/v1alpha1
kind: Custom1
metadata:
name: default-custom1
labels:
app: app1
spec:
- id: my-id
description: my-description
```
would result in
With these changes, spinnaker is able to deploy it.

fix(kubernetes): teach KubernetesManifest to support kubernetes resources where the spec is not a map

---

clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactCredentials.java
clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/bitbucket/BitbucketArtifactCredentialsTest.java

When using an invalid token without the header `Accept: application/json` we get 302 response back and `okHttpClient.newCall(request).execute().isSuccessful()` returns true thus sending orca the incorrect ResponseBody
**-----------------------------------------------------------------------------------------------------------------**
With the header in place we get 401 `okHttpClient.newCall(request).execute().isSuccessful()` returns false thus throwing the correct exception and error log from clouddriver
tested on spinnaker and using curl:

fix(artifacts/bitbuket): added ACCEPT Header when using token auth

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDeploymentHandler.java

This reverts commit 932dd66d250fe98ff4cb783c1a6784e8e14db97c.
See https://github.com/spinnaker/clouddriver/pull/5830/files#r1054854915 for details, but versioning deployments causes test failures and is a big behavior change.  Reverting until we can figure out a better way.

Revert "feat(k8s): Add Deployment Kind support for Blue/Green deployments (#5830)"

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java

* Prevent resources versioning test from interfering to each other. It currently makes sure to be equivalent. But flags like ServerSide Apply and fields like FieldManager might cause equivalent resources to increase the version number.

test(integration): Prevent interference between tests

---

clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle

for more predictable builds, and to avoid failures like:
```
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [com.github.tomakehurst.wiremock.WireMockServer arg0] in method [void com.netflix.spinnaker.clouddriver.artifacts.http.HttpArtifactCredentialsTest.downloadWithBasicAuth(com.github.tomakehurst.wiremock.WireMockServer) throws java.io.IOException]: jakarta/servlet/DispatcherType
```
that come with version 3.0.0-beta2 of com.github.tomakehurst:wiremock released on 30-dec-22.
Use com.github.tomakehurst:wiremock-jre8-standalone as it's the more modern version of wiremock, and has fewer dependencies than wiremock-jre8.
Currently, we end up with version 2.31.0 via spring-cloud-dependencies.  See …

chore(dependencies): pin version of com.github.tomakehurst:wiremock

---

clouddriver-core/clouddriver-core.gradle
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jobs/JobRequest.java
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/ManifestFetcher.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java
clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/op/job/mock-kubectl-stdin-command.sh

Turns out the changes from https://github.com/spinnaker/clouddriver/pull/5401 needed some adjustment.
* add tests to show duplicate logs aren't being printed when multiple threads are running the same command
* add metrics support for capturing retries.
* refactor criteria that decides if an error should be retried. This is needed so that metrics are reported correctly
* refactor tests
* add short custom log messages for retries instead of the default verbose ones
Here are some log messages showing that retries help in fixing the problem in subsequent attempts:
```
{"@timestamp":"2021-11-12T16:55:15.987+00:00","@version":1,"message":"Retrying kubectl command for my-account Attempt #1 failed with exception: com.netflix.spinnaker.clouddriver.kubernetes.op.job.KubectlJobExecutor$KubectlExcept …
```

fix(kubectl): add metrics to retries, make log messages more descriptive and support retries for all kubectl actions

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizerService.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizerServiceSpec.groovy

When fiat is enabled and validation for accounts without roles is requested, the access is denied by emptyRoles condition, so when a dummy role is set this condition is skipped. Adding extra old fiat validator we preserved a consistent behaviour on accounts with roles vs without roles
Steps to reproduce issue:
With fiat enabled create 2 serviceAccounts, one with role, and other without role
Try apply ops operations like scale manifest deployment with different accounts, so we gonna have the inconsistent scenario where dummy roled account is succeeded  and empty role account received a denied access error
Account without roles:
Account with dummy roles:
Use case for empty role accounts was introduced in https://github.com/spinnaker/clouddriver/commit/da657157d6f8c7050ee577e147db99c9936b0b72 …

fix(permissions): Added evaluator case when fiat is enabled

---

clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/deploy/converters/SetStatefulDiskAtomicOperationConverter.java
clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/deploy/converters/StatefullyUpdateBootImageOperationConverter.java

There are a couple of classes which extended AbstractAtomicOperationsCredentialsConverter but without being a generic type causing it to work fine with google accounts alone but fails when kubernetes accounts get added. 
This PR will fix the issue ([#6796](https://github.com/spinnaker/spinnaker/issues/6796))

fix(google): make AbstractAtomicOperationsCredentialsConverter generic type

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidator.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/StandardGceAttributeValidatorSpec.groovy

To address the validation issue that is occurring while using custom metric utilisations in Autoscaler feature of creation of server group in google cloud provider.
As part of addressing the issue mentioned in [6784](https://github.com/spinnaker/spinnaker/issues/6784)
While selecting one of two scaling policies available(SingleInstanceAssignment and Utilization Target) the other one is null.Hence added validation to check for null.

fix(google): added null check for autoscaler custom metric scaling policies

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/Replacer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesCronJobHandler.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ReplacerTest.java

PR #5554 updated the docker image artifact replacer for K8s Cronjobs. While it works if there is no tag defined in the manifest, it fails if there is a tag defined in the manifest and the artifact binding strategy is set to `match-name-and-tag`. 
Commit: https://github.com/spinnaker/clouddriver/pull/5876/commits/e55cbcb1769cbb6ec70bf0087697fcac9e9a0f37 adds a test that demonstrates that failure. With the artifact replacer set to `dockerImage()`, we don't see that failure.

fix(kubernetes): Revert to using the dockerImage Artifact Replacer for cronjobs

---

clouddriver-oracle/clouddriver-oracle.gradle
clouddriver-yandex/clouddriver-yandex.gradle

After removing groovy-all from clouddriver-yandex and clouddriver-oracle modules, encountered following errors while building and testing clouddriver respectively:
```
> Task :clouddriver-yandex:compileGroovy FAILED
/clouddriver/clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/deploy/YandexServerGroupNameResolver.java:30: error: package org.apache.groovy.datetime.extensions does not exist
import org.apache.groovy.datetime.extensions.DateTimeExtensions;
^
1 error
Compilation failed; see the compiler error output for details.
1 error
FAILURE: Build failed with an exception.
```
```
> Task :clouddriver-oracle:compileTestGroovy
/clouddriver/clouddriver-oracle/src/test/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/op/DestroyOracl …
```

chore(dependencies): remove dependency on groovy-all with required groovy package

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcrImageProvider.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcrImageProviderSpec.groovy

When Autodesk set up our Spinnaker instances, we created separate Credentials for each (accountId, region) duple.
So for example, ('123456789012', 'us-west-1') is one credential, and later on, ('123456789012', 'us-east-1') is a second one.
We discovered that if we attempt to validate a container present in the account's second region (ordering determined by the getCredentials API), then it would fail to validate, because only the account id is matched by the credential search, not the regions within it.
This PR contributes a test that fails on the existing code, and a proposed change to address it.
I'm not 100% happy about including the test for no-regions-specified in the code change I'm offering, but it reduced the number of tests that needed to change; I wasn't sure if the semantics …

fix(ecr): Two credentials with same accountId confuses EcrImageProvider with different regions

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ResourceVersioner.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesSourceCapacity.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesSourceCapacityTest.java

Change: Use version suffixes to populate replicas when using use-source-capacity annotation

fix(manifest-replicas): ReplicaSet Source-Capacity

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/validators/BasicAmazonDeployDescriptionValidator.groovy

It pollutes the log and isn't otherwise helpful.

fix(aws): don't log empty warning BasicAmazonDeployDescriptionValidator.validate

---

cats/cats-redis/cats-redis.gradle
cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java
cats/cats-redis/src/test/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentSchedulerTest.java

The settings in [clouddriver.yaml](https://github.com/spinnaker/clouddriver/blob/909b6ff11dad82268a0b4401f70cabc9b4a3f3ed/clouddriver-web/config/clouddriver.yml#L11) do apply: Set AgentScheduler type to ClusteredSortAgentScheduler and redis.parallelism greater than 0.
```
redis:
scheduler: sort
parallelism: 10 # greater than 0
```
In this [Code](https://github.com/spinnaker/clouddriver/blob/909b6ff11dad82268a0b4401f70cabc9b4a3f3ed/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java#L416), the runningAgents has no release a permit to the Semaphore:
1. When worker is null or score is null;
2. When acquireAgent method throw an Exception.

fix(cats-redis): release Semaphore to avoid leaking

---

clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/services/Front50Service.groovy

The parameter in the Front50 API is called `tag`, but in the Retrofit client it's called `version`. Because of this, Clouddriver ignores the tags during template lookup. 
The parameter in the API: https://github.com/spinnaker/front50/blob/a2f188767a1f9584452e6ab61c555dd1a630c468/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java#L151
This PR fixes the issue: https://github.com/spinnaker/spinnaker/issues/6583

fix(core): Renamed a query parameter for template tags

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-google/clouddriver-google.gradle
clouddriver-yandex/clouddriver-yandex.gradle

While executing the build script with --warning-mode=fail received below error:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0
```
And the deprecated gradle features are:
```
> Configure project :clouddriver-azure
Using force on a dependency has been deprecated. This is scheduled to be removed in Gradle 7.0. Consider using strict version constraints instead (version { strictly ... } }). Consult the upgrading guide for further information: https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#forced_dependencies
at clouddriver_azure_6ftffoxb07xu7lz9bwdhnw53c$_run_closure1$_closure2.doCall(/clouddriver/clouddriver-azure/clouddriver-azure.gradle:20)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
> …
```

refactor(deprecation): remove deprecated gradle constructs/features from clouddriver in order to upgrade gradle 7

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java

The `isTaggingEnabled` method doesn't check `listAccountSettings` is returning a token for a paged response. 
This caused the deployment to fail even if the AWS Account has been enabled for the tagging feature.

fix(aws): ECS Service Tagging broken

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java

Unfortunately, it is not possible to override the default handler behavior from a Spinnaker plugin code. Therefore, we have decided to introduce a new setter function specifically designed to address this requirement.

feat: Add the possibility to update the default handler for the Global Resource Property Registry.

---

clouddriver-appengine/src/test/java/com/netflix/spinnaker/clouddriver/appengine/deploy/ops/DeployAppengineConfigAtomicOperationTest.java
clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/embedded/EmbeddedArtifactCredentials.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
clouddriver-web/src/main/java/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java

This commit adds artifact storage to clouddriver. The idea in this
commit is artifact will automatically be expanded when the server
receives a request since clouddriver is more than likely interested in
the artifact.

feat(artifacts): Adds ArtifactStore logic to clouddriver

---

cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt

This pull request addresses a performance issue discovered in the Clouddriver, specifically within the `SqlCache.getHash method`.
I used async-profiler to build an Allocation profile and a CPU profile. From the Allocation profile, it was found that the `SqlCache.getHash` method was responsible for 80% of the memory allocation, mostly due to the heavy use of `String.format` within this method. Furthermore, the CPU profile indicated that 34% of CPU usage was also attributed to this method.
So I'm making a conclusion that `SqlCache.getHash` is generating a significant amount of garbage, contributing to high heap and CPU usage. This could potentially be a root cause for Out Of Memory errors if the Garbage Collector is unable to clean up the generated garbage efficiently. It also may add to …

perf(cache): Optimise heap usage in SqlCache

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgent.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleSubnetCachingAgentSpec.groovy

Addresses the issue: https://github.com/spinnaker/spinnaker/issues/6813
CacheData's attributes map is so far been assigned a map of `subnet` key and it's value along with `project` key and it's value under (yet again) a `subnet` key instead of having `subnet` and `project` as separate attributes. This PR fixes the issue.
The existing test didn't catch the bug so it is now updated.

fix(gce): remove the duplicate cache attribute "subnet" and update the test

---

.github/workflows/integration-tests-kubernetes.yml
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/containers/KubernetesCluster.java

This PR addresses [this issue](https://github.com/spinnaker/spinnaker/issues/6612) by using the matrix feature of Github Actions to enable running the kubernetes integration tests for multiple versions of kubernetes in parallel. It extracts the kubernetes tests into a separate workflow called `kubernetes-integration-tests` to avoid running the other integration tests multiple times. This workflow is called by the main integration tests workflow. 
The kubernetes tests workflow passes the kubernetes images specified in the matrix to gradle as a project property: `./gradlew --build-cache :clouddriver-kubernetes:integrationTest -Pkubernetes-image=${{ matrix.kubernetes-image }}`. This value is then passed to the java code as an environment variable so that the `createCluster()` method can …

(feat): increase kubernetes integration test coverage

---

.github/workflows/integration-tests-kubernetes.yml
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/BaseTest.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/containers/KubernetesCluster.java
clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/utils/KubeTestUtils.java

This PR is a logical extension of [this merged PR](https://github.com/spinnaker/clouddriver/pull/5990) and continues to address the need for [increased k8s integration test coverage](https://github.com/spinnaker/spinnaker/issues/6612) by updating the version of [kind](https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0) used to the latest and specifying a list of compatible images for k8s versions v1.19 - v1.28 that the integration tests can run in parallel against.

feat(integration-tests): updated version of kind and added images for k8s v1.19 - v1.28

---

clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/InvokeLambdaAtomicOperation.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/LambdaOperationsConfig.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/InvokeLambdaAtomicOperationTest.java

Be nice LONG term to ... well, replace some of this with async calls and cleaner implementations.  The current lambda stuff is kinda "meh" on several levels.

feat(lambda): Lambda inovke default timeout is 50 seconds.  Add configurable timeouts for lambda invocations

---

clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/model/OracleCluster.groovy

This change is to make code more readable and less dependent of `groovy` transformations.

refactor(oracle): introduce explicit constructor and initialization of inner class members

---

clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/model/OracleServerGroup.groovy

This change is to make code more readable and less dependent of groovy transformations.

refactor(oracle): introduce explicit constructor for initialization of inner class members in OracleServerGroup

---

clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelperSpec.groovy
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgent.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaService.java
clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/config/LambdaServiceConfig.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgentTest.java
clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaServiceTest.java

The custom executor service thing which seems like a perf improvement is causing thread leak and eventual failures.  Remove it entirely.

fix(lambda): Lambda is leaking threads on agent refreshes.  

---

clouddriver-google/clouddriver-google.gradle

With groovy 2.5.15 and spockframework 1.3-groovy-2.5, groovy-test appear as transitive dependency of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/1.3-groovy-2.5) as shown below:
```
$ ./gradlew clouddriver-google:dI --dependency groovy-test --configuration testCompileClasspath
> Task :clouddriver-google:dependencyInsight
org.codehaus.groovy:groovy-test:2.5.15
Variant compile:
| Attribute Name                     | Provided | Requested         |
|------------------------------------|----------|-------------------|
| org.gradle.status                  | release  |                   |
| org.gradle.category                | library  | library           |
| org.gradle.libraryelements         | jar      | classes+resources |
| org.gradle.usage …
```

chore(dependency): add explicit dependency of groovy-test in clouddriver-google while upgrading groovy 3.x

---

clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in groovy test compilation of clouddriver-aws module:
```
> Task :clouddriver-aws:compileTestGroovy FAILED
/clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy: 107: The current scope already contains a variable of the name region
@ line 107, column 68.
unchConfiguration(_, _, _) >> { act, reg
^
1 error
/clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ModifyAsgLaunchConfigurationOperationSpec.groovy: 157: The current scope already contains a variable of the name region
@ line 157, column 68.
unchConfiguration(_, _, _) >> { act, …
```

refactor(aws/test): fix conflict of variable scope by renaming local variables during upgrade of groovy 3.x

---

clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentialsSpec.groovy

While upgrading to groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following error due to deprecation of [NioGroovyMethods](https://javadoc.io/static/org.codehaus.groovy/groovy-all/3.0.10/org/codehaus/groovy/runtime/NioGroovyMethods.html) class:
```
No signature of method: sun.nio.fs.UnixPath.append() is applicable for argument types: (String) values: [some content]
Possible solutions: append(java.io.Writer, java.lang.String), append(java.io.Writer), append(java.lang.Object), append(java.io.Reader), append(java.io.Reader, java.lang.String), append(java.lang.Object, java.lang.String)
groovy.lang.MissingMethodException: No signature of method: sun.nio.fs.UnixPath.append() is applicable for argument types: (String) values: [some content]
Possible solutions: …
```

refactor(kubernetes/test): replace deprecated NioGroovyMethods.append() with ResourceGroovyMethods.append() during upgrade to groovy 3.x

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, groovy-templates is not part of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/2.0-groovy-3.0) and encounter below error during test compilation:
```
> Task :clouddriver-kubernetes:compileTestGroovy FAILED
/clouddriver/clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/KubernetesManifestSpec.groovy: 25: unable to resolve class groovy.text.SimpleTemplateEngine
@ line 25, column 1.
import groovy.text.SimpleTemplateEngine
^
1 error
```
So, adding explicit dependency of groovy-templates in clouddriver-kubernetes.gradle
With groovy 2.5.15 and spockframework 1.3-groovy-2.5, groovy-templates appear as transitive dependency of …

chore(dependency): add explicit dependency of groovy-templates in clouddriver-kubernetes while upgrading groovy 3.x

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/description/ModifyServerGroupLaunchTemplateDescription.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/actions/ModifyServerGroupLaunchTemplateSpec.groovy

Fix a JsonProcessingException when deserializing ModifyServerGroupLaunchTemplateDescription by ignoring derived property getServerGroupNames.

fix(aws): ignore deserialziation of getServerGroupNames

---

clouddriver-web/clouddriver-web.gradle

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, groovy-json is not part of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/2.0-groovy-3.0) and encounter below error during test compilation:
```
/clouddriver/clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerSpec.groovy: 27: unable to resolve class groovy.json.JsonSlurper
@ line 27, column 1.
import groovy.json.JsonSlurper
^
1 error
> Task :clouddriver-web:compileTestGroovy FAILED
```
So, adding explicit dependency of groovy-json in clouddriver-web.gradle.
With groovy 2.5.15 and spockframework 1.3-groovy-2.5, groovy-json appear as transitive dependency of [spockframework](https://mvnrepository.com/artifact/org.spockframework/sp …

chore(dependency): add explicit dependency of groovy-json in clouddriver-web while upgrading groovy 3.x

---

build.gradle
cats/cats-sql/cats-sql.gradle
clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-cloudrun/clouddriver-cloudrun.gradle
clouddriver-core/clouddriver-core.gradle
clouddriver-docker/clouddriver-docker.gradle
clouddriver-event/clouddriver-event.gradle
clouddriver-google/clouddriver-google.gradle
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-lambda/clouddriver-lambda.gradle
clouddriver-saga/clouddriver-saga.gradle
clouddriver-sql/clouddriver-sql.gradle
gradle/kotlin-test.gradle

in build.gradle
and make it testRuntimeOnly since that's sufficient.  See https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-jupiter for background.

chore(junit): centralize org.junit.jupiter:junit-jupiter-engine dependency

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/DeleteGoogleAutoscalingPolicyAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in `DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec` tests, due to inaccessible private variable to mock the object :
```
DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec > should delete zonal and regional autoscaling policy > com.netflix.spinnaker.clouddriver.google.deploy.ops.DeleteGoogleAutoscalingPolicyAtomicOperationUnitSpec.should delete zonal and regional autoscaling policy [isRegional: true, #0] FAILED
groovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.clouddriver.google.deploy.ops.DeleteGoogleAutoscalingPolicyAtomicOperation.setGoogleClusterProvider() is applicable for argument types: (com.netflix.spinnaker.clouddriver.google.provider.view.Googl …
```

 refactor(google): add constructor-based DI to mock private members in test and resolved the scope of variables during upgrade to groovy 3.x

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentialsInitializer.groovy

While upgrading springboot 2.5.15, encounter below error in clouddriver-azure module:
```
/clouddriver/clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureNetworkClient.groovy: 234: [Static type checking] - Incompatible generic argument types. Cannot assign java.util.List <java.lang.Object> to: java.util.Collection <AzureAppGatewayDescription>
@ line 234, column 5.
result
^
/clouddriver/clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentialsInitializer.groovy: 63: [Static type checking] - Incompatible generic argument types. Cannot assign java.util.List <java.lang.Object> to: java.util.List <AzureNamedAccountCredentials>
@ line 63, column 5.
azureAccounts
^
2 errors
> Task …
```

refactor(azure): fix incompatible generic type issue faced during upgrade to springboot 2.5.15

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/cache/AzureServerGroupCachingAgent.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/model/AzureServerGroupDescription.groovy

Refactoring the boolean field `isDisabled` to `disabled`, that allows groovy 3.x to generate its getter as `isDisabled()`, and removing the overridden method `isDisabled()`.

refactor(azure): refactor boolean field to use default getter implementation of groovy 3.x

---

clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelperSpec.groovy

Previously, calls to `AsgConfigHelper.createDefaultSuffix()` in the `AsgConfigHelperSpec` test ["should return name correctly"](https://github.com/spinnaker/clouddriver/blob/8825c133897ae962c9de674ef5cf1b6f9fe8a3c6/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/AsgConfigHelperSpec.groovy#L63) used the actual local time, since the `setup` function runs after a `where` block. This would very occasionally result in a test failure.
This PR resolves the issue by using `setupSpec` instead (correspondingly changing `cleanup` to `cleanupSpec`).

fix(aws/test): Fix requests for time in "where" not fixed

---

clouddriver-sql/src/main/resources/db/changelog/20210106-task-outputs.yml

This bug is discovered while working on liquibase upgrade. The newer versions of liquibase have strict enforcements on incorrect indentation of elements in databaseChangeLog files. Hence this correction is needed before upgrading the liquibase.

fix(databaseChangeLog): rollback element's indentation correction

---

clouddriver-saga-test/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/TestingSagaRepository.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaFlowIterator.kt
clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/models/Saga.kt

While upgrading Kotlin 1.5.32, encounter below error in clouddriver-saga and clouddriver-saga-test module:
```
> Task :clouddriver-saga:compileKotlin FAILED
e: /clouddriver/clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/flow/SagaFlowIterator.kt: (185, 8): Using 'min(): T?' is an error. Use minOrNull instead.
e: /clouddriver/clouddriver-saga/src/main/kotlin/com/netflix/spinnaker/clouddriver/saga/models/Saga.kt: (62, 63): Using 'max(): T?' is an error. Use maxOrNull instead.
```
```
> Task :clouddriver-saga-test:compileKotlin FAILED
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: /clouddriver/clouddriver-saga-test/src/main/kotlin/com/netflix/spinnaker/cloudd …
```

refactor(saga/test): replace deprecated method during upgrade to Kotlin 1.5.32

---

clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/DeployManifestIT.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestStrategy.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanDeploy.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentials.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestStrategyTest.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanDeployTest.java

kubernetes server-side apply (SSA) was released back in 1.14 and became GA In 1.22. This new strategy will use the new merging algorithm, as well as tracking field ownership at the kubernetes api-server
fixes: https://github.com/spinnaker/spinnaker/issues/6865

feat(provider/kubernetes): support for kubectl server-side-apply strategy

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/cache/RedisCacheConfig.java

Fixed `redis.poll.errorIntervalSeconds` and `redis.poll.timeoutSeconds` configs are not respected. This bug was introduced when converting `RedisCacheConfig` from Groovy to Java. See related [PR](https://github.com/spinnaker/clouddriver/pull/5703/files#diff-8db17292fc8921bc3d45504a73d5a93cc9a5b7ce6fb1a1537b8532648f131b6d).

fix(cats): timeoutSeconds and errorIntervalSeconds config are not respected

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.java
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy

and always construct artifact store-related beans
since https://github.com/spinnaker/kork/pull/1120 removes the artifact-store.enabled property such that ArtifactStore beans are always present.

chore(artifacts): remove reference to artifact-store.enabled

---

clouddriver-configserver/src/main/java/com/netflix/spinnaker/clouddriver/config/AbstractBootstrapCredentialsConfigurationProvider.java
clouddriver-web/src/main/java/com/netflix/spinnaker/clouddriver/listeners/ConfigurationRefreshListener.java
clouddriver-web/src/test/java/com/netflix/spinnaker/clouddriver/controllers/KubernetesCustomPropertyBindingRefreshTest.java
clouddriver-web/src/test/resources/clouddriver.yml

Since SecretAwarePropertySource is now shadowing the underlying PropertySource, delegate is made public through https://github.com/spinnaker/kork/pull/1122, and it's being used to identify BootstrapPropertySource.
`KubernetesCustomPropertyBindingRefreshTest`  is added to verify the `/refresh` scenario.
minor changes are added to accommodate the test class.

fix(configserver): make AbstractBootstrapCredentialsConfigurationProvider.getPropertiesMap aware of SecretAwarePropertySource

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java

to get a meaningful manifest name when using generateName instead of name

fix(kubernetes): use getFullResourceName in KubectlJobExecutor.create

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.java
gradle.properties

In `PollerConfiguration`, this now takes an `ObjectProvider` instead of a `List`, and it uses the newly introduced `CredentialsLoader` interface instead.
Related to compilation failure in https://github.com/spinnaker/clouddriver/pull/6131

fix(core): Fix type migration issue

---

build.gradle
cats/cats-core/cats-core.gradle
cats/cats-redis/cats-redis.gradle
cats/cats-test/cats-test.gradle
clouddriver-alicloud/clouddriver-alicloud.gradle
clouddriver-api/clouddriver-api.gradle
clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-artifacts/clouddriver-artifacts.gradle
clouddriver-aws/clouddriver-aws.gradle
clouddriver-bom/clouddriver-bom.gradle
clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-cloudrun/clouddriver-cloudrun.gradle
clouddriver-configserver/clouddriver-configserver.gradle
clouddriver-core/clouddriver-core.gradle
clouddriver-docker/clouddriver-docker.gradle
clouddriver-ecs/clouddriver-ecs.gradle
clouddriver-google-common/clouddriver-google-common.gradle
clouddriver-google/clouddriver-google.gradle
clouddriver-huaweicloud/clouddriver-huaweicloud.gradle
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-lambda/clouddriver-lambda.gradle
clouddriver-oracle/clouddriver-oracle.gradle
clouddriver-tencentcloud/clouddriver-tencentcloud.gradle
clouddriver-titus/clouddriver-titus.gradle
clouddriver-web/clouddriver-web.gradle
clouddriver-yandex/clouddriver-yandex.gradle

Various gradle cleanups with the goal of removing failures from `$ ./gradlew dependencies` output from all clouddriver modules.  Happily, all the failures are gone.
FWIW, I often use this to poke around for dependency changes
```
alias gradle-all-deps='./gradlew --no-parallel --stacktrace dependencies $(./gradlew -q projects \
| grep -Fe ---\ Project \
| sed -Ee "s/^.+--- Project '"'([^']+)'/\1:dependencies/"'" | sort)'
```
inspired by https://stackoverflow.com/a/65945289

remove failures from ./gradlew dependencies

---

clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatus.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.java
clouddriver-web/clouddriver-web.gradle
clouddriver-web/src/test/java/com/netflix/spinnaker/clouddriver/config/ObjectMapperTest.java

While upgrading spring boot 2.6.15 and spring cloud 2021.0.8, encounter below errors in clouddriver-kubernetes module during build and test compilation:
```
> Task :clouddriver-kubernetes:compileTestJava FAILED
/clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacerTest.java:33: error: cannot find symbol
import io.kubernetes.client.openapi.models.V1ContainerBuilder;
^
symbol:   class V1ContainerBuilder
location: package io.kubernetes.client.openapi.models
/clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacerTest.java:35: error: cannot find symbol
import io.kubernetes.client.openapi.models.V1DeploymentBuilder;
^
symbol:   class V1DeploymentBuilder
location: …
```

refactor(kubernetes): refactor and upgrade kubernetes java client apis and its relevant dependency during upgrade to spring boot 2.6.x

---

clouddriver-sql/src/main/resources/db/changelog-master.yml
clouddriver-sql/src/main/resources/db/changelog/20240111-accounts-indexes.yml

The current indexes on (id, type) and (id, type, created_at, modified_at) are never used by SqlAccountDefinitionRepository. Drop these indexes and replace them with an index on (type), which does get used by the query: SELECT body FROM accounts WHERE type='accountType';
Explain output before the change:
```
mysql> explain SELECT body FROM accounts where type='kubernetes';
+----+-------------+----------+------------+------+---------------+------+---------+------+------+----------+-------------+
| id | select_type | table    | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+----------+------------+------+---------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | accounts | NULL       | ALL  | …
```

fix(sql): Fix indexes for the accounts table

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/6922.
Ultimately, considers the `WWW-Authenticate` header value as a `List<String>` as opposed to casting it directly to a `String`.
According to [Mozilla's `WWW-Authenticate` header documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate), it is possible for the server to respond with multiple challenges through multiple header values. As such, I decided not to simply fetch the first header value, but now loop over the values and handle the first to match the `bearer` or `basic` prefix. It might be time to extract this to a separate method, but I kept the diff as small as possible. 
I am not too familiar with Groovy nor Spock, so feel free to apply improvements where you deem fit.
The first commit …

fix(provider/docker): Support multiple challenges from `WWW-Authenticate` header

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgent.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonSecurityGroupCachingAgentSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgentSpec.groovy

I'm unsure how this code has ever worked, but after the upgrade to Groovy 3, it started crashing.
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: 
Cannot cast object '{loadBalancers=aws:loadBalancers:my-aws-account:eu-west-1:*:vpc-????????:*}' 
with class 'java.util.LinkedHashMap' to class 'java.util.Optional' due to: groovy.lang.GroovyRuntimeException: 
Could not find matching constructor for: java.util.Optional(LinkedHashMap)
```

fix(aws): Fix bug in AWS provider after Groovy 3 upgrade

---

clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionService.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/DefaultAccountSecurityPolicy.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/security/AccountDefinitionServiceTest.java
clouddriver-core/src/test/java/com/netflix/spinnaker/clouddriver/security/DefaultAccountSecurityPolicyTest.java

This change also includes a fix to allow reflection to read private fields in the authorization checking logic. Without the fix, trying to create an account as an accountManager leads to an IllegalAccessException:
`dztest.json` contents:
```
{
"type": "kubernetes",
"name": "dztest",
"requiredGroupMembership": [],
"providerVersion": "V2",
"configureImagePullSecrets": true,
"cacheThreads": 1,
"namespaces": [],
"kinds": [],
"omitKinds": [
"podPreset"
],
"omitNamespaces": [],
"metrics": false,
"debug": true,
"customResources": [],
"cachingPolicies": [],
"kubeconfigFile": "/opt/dztest.kubeconfig",
"oAuthScopes": [],
"onlySpinnakerManaged": true,
"checkPermissionsOnStartup": false,
"liveManifestCalls": true
}
```
Before the fix:
`> curl -X POST --cookie "SESSION=$COOKIE" -H "Content-Type: …

feat(account): Implement the isAccountManager flag

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java

to remove duplicate code.
Log messages have changed, but only slightly.
Before:
```
Kubectl retries configured for: mock-account
```
After:
```
Kubectl command retries configured for: mock-account
```
The other log messages remain the same, e.g.:
```
Retrying Kubectl command for mock-account. Attempt #1 failed with exception...
```

refactor(kubernetes): use Resilience4jHelper from kork to configure logging

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonInstanceTypeCachingAgent.java

The standard in spinnaker is to use a single table for a cache agent TYPE without the account name,

fix: Change the agent type name to not include the account name since this would generate LOTS of tables and cause problems long term

---

clouddriver-azure/clouddriver-azure.gradle
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerProvider.groovy
clouddriver-azure/src/test/java/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/view/AzureLoadBalancerProviderTest.java

Circular dependencies error when you enable azure
```
***************************                                                                                                            
APPLICATION FAILED TO START                                                                                                             
***************************                                                                                                             
Description:                                                                                                                            
The dependencies of some of the beans in the application context form a cycle:                                                          │
│
┌──->──┐ …
```

fix(azure): circular dependencies

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleApplication.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleCluster.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleHealthCheck.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleInstance.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/health/GoogleLoadBalancerHealth.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleHttpLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleInternalLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleNetworkLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleSslLoadBalancer.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/loadbalancing/GoogleTcpLoadBalancer.groovy

This change is to fix the issue https://github.com/spinnaker/spinnaker/issues/6939.

fix(google): introduce explicit constructor and initialization of inner class members

---

clouddriver-sql/src/main/resources/db/changelog/20181120-cats.yml
clouddriver-sql/src/main/resources/db/changelog/20190913-task-sagaids.yml

This PR addresses https://github.com/spinnaker/spinnaker/issues/6942
The following PR provides more details on the issue and similar fix provided for orca: https://github.com/spinnaker/orca/pull/4594

fix(databaseChangeLog): fix for 'addAfterColumn is not allowed on postgresql'

---

clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterControllerSpec.groovy

When an application includes clusters for more than 2 cloud-providers then the GET /clusters endpoint was returning only the last 2 providers clusterNames instead of ALL the clusters deployed by the application. 
We didnt notice this bug existed because Deck is rendering based on the clusters and serverGroups and when not filtered the serverGroups was including the missing clusters.
It is noticeable though for the end-user when the SETTINGS.onDemandClusterThreshold  is used to make a searchable rendering of clusters/serverGroups in Deck.

fix(ClusterController): Fix GetClusters to return all providers clusterNames of an application

---

clouddriver-sql-mysql/clouddriver-sql-mysql.gradle

Before:
```
$ ./gradlew clouddriver-sql-mysql:dI --dependency mysql-connector-java --configuration runtimeClasspath
> Task :clouddriver-sql-mysql:dependencyInsight
mysql:mysql-connector-java:8.0.33
Variant runtime:
| Attribute Name                     | Provided     | Requested    |
|------------------------------------|--------------|--------------|
| org.gradle.status                  | release      |              |
| org.gradle.category                | library      | library      |
| org.gradle.libraryelements         | jar          | jar          |
| org.gradle.usage                   | java-runtime | java-runtime |
| org.gradle.dependency.bundling     |              | external     |
| org.gradle.jvm.environment         |              | standard-jvm |
| org.gradle.jvm.version …
```

chore(dependency): unpin mysql-connector-java

---

clouddriver-integration/src/test/java/com/netflix/spinnaker/clouddriver/BaseContainerTest.java
clouddriver-integration/src/test/java/com/netflix/spinnaker/clouddriver/PostgresMigrationContainerTest.java
clouddriver-sql/src/main/resources/db/changelog/20180919-initial-schema.yml
clouddriver-sql/src/main/resources/db/changelog/20181120-cats.yml
clouddriver-sql/src/main/resources/db/changelog/20190913-task-sagaids.yml

This PR fixes checkSum errors caused after liquibase upgrade(to 4.24.0) as the checksum calculation underwent some changes causing this issue.
This PR fixes the checksum errors by adding validChecksum tags to the failing changesets.
Added an integration test to verify the migration scenario with postgres. This will be useful to identify and avoid issues when liquibase is upgraded or if any changesets are modified.
Similar orca PR for reference: https://github.com/spinnaker/orca/pull/4727

fix(liquibase): fix checkSum errors occurring with spinnaker upgrade

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgBuilder.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithLaunchConfigurationBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithLaunchTemplateBuilderSpec.groovy
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/asgbuilders/AsgWithMixedInstancesPolicyBuilderSpec.groovy

when building an auto scaling group.  https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_EnableMetricsCollection.html says:
> If you specify Granularity and don't specify any metrics, all metrics are enabled.
Before this change
```
enabledMetrics: []
```
in a deploy stage would enable no metrics, like this:
```
$ aws autoscaling describe-auto-scaling-groups --region=us-west-2 --auto-scaling-group-names=my-asg-v001 | jq .AutoScalingGroups[0].EnabledMetrics
[]
```
After this PR, we get:
```
$ aws autoscaling describe-auto-scaling-groups --region=us-west-2 --auto-scaling-group-names=my-asg-v002 | jq .AutoScalingGroups[0].EnabledMetrics
[
{
"Metric": "GroupInServiceInstances",
"Granularity": "1Minute"
},
{
"Metric": "GroupAndWarmPoolDesiredCapacity",
"Granularity": "1Minute"
},
{ …
```

fix(aws): allow enabledMetrics: [] to enable all metrics

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverter.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperation.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverterUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverterUnitSpec.groovy
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/UpsertGoogleAutoscalingPolicyAtomicOperationUnitSpec.groovy

Fixing the following [issue](https://github.com/spinnaker/spinnaker/issues/6963) 
It was introduced as part of this [PR](https://github.com/spinnaker/clouddriver/pull/6057/files#diff-77886cd9f754611f6844f38a9d1eaa13a7306a5c311d58aa07fa7aff2ab1de88L67)

fix(google): fixing UpsertGoogleAutoscalingPolicyAtomicOperation missing Autowired for objectMapper and cacheView

---

.github/workflows/build.yml
.github/workflows/integration-tests-kubernetes.yml
.github/workflows/integration_tests.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile
build.gradle
clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceInstancesTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ServiceKeysTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CreateCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeleteCloudFoundryServiceKeyAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServiceAtomicOperationConverterTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/CreateCloudFoundryServiceKeyAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeleteCloudFoundryServiceKeyAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServiceAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DestroyCloudFoundryServiceAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/ShareCloudFoundryServiceAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/UnshareCloudFoundryServiceAtomicOperationTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgentTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgentTest.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundrySpaceCachingAgentTest.java
clouddriver-kubernetes/clouddriver-kubernetes.gradle
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestAnnotater.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestLabeler.java
clouddriver-yandex/clouddriver-yandex.gradle
gradle.properties

Compile to Java 11 bytecode using JDK 17.
Reference: https://github.com/spinnaker/igor/pull/1198

chore(build): enable cross compilation plugin for Java 17

---

clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/loadbalancer/deploy/validators/UpsertAzureLoadBalancerDescriptionValidatorSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/AzureServerGroupResourceTemplateSpec.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroups/deploy/ops/DestroyAzureServerGroupAtomicOperationSpec.groovy

Some azure tests need the AzureCredentials class. These tests create the class by using the default AzureCredentials constructor. The constructor for the class has code that tries to actually authenticate against a Microsoft/Azure server, and all of the API calls to the MS servers fail. The tests all have code to set up in this class in the setup section of Groovy specs, which means that gradle never actually executes the tests for these classes. The API calls to MS fail and are repeatedly retried over and over again until they eventually stop and the tests run, and succeed. I'm not sure why the tests end up passing after the retries are exhausted.
This issue can only be found when running a command like `./gradlew :clouddriver-azure:test --debug` which shows the logs of the gradle runner …

chore(azure/build): improve test times for azure

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProviderTest.java

There is an edge case where in certain situations, a job can have 0 running pods. When clouddriver attempts to retrieve the pod name, it runs into an `IndexOutOfBoundsException`

fix(kubernetes/job): Fix an edge case where a job can have no pods

---

clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentialsTest.java

While upgrading junit to 5.9.0, encountered below error during test execution of clouddriver-artifacts module:
```
@BeforeAll method 'private static void com.netflix.spinnaker.clouddriver.artifacts.s3.S3ArtifactCredentialsTest.setupOnce()' must not be private.
org.junit.platform.commons.JUnitException: @BeforeAll method 'private static void com.netflix.spinnaker.clouddriver.artifacts.s3.S3ArtifactCredentialsTest.setupOnce()' must not be private.
at org.junit.jupiter.engine.descriptor.LifecycleMethodUtils.assertNonPrivate(LifecycleMethodUtils.java:104)
at org.junit.jupiter.engine.descriptor.LifecycleMethodUtils.lambda$findMethodsAndAssertStaticAndNonPrivate$1(LifecycleMethodUtils.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at …
```

refactor(test): fix scope of setup method while upgrading junit to 5.9.0

---

clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperationConverter.java
clouddriver-api/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/OperationDescription.java
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/AllowLaunchDescription.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/common/AzureResourceOpsDescription.groovy
clouddriver-cloudrun/src/main/java/com/netflix/spinnaker/clouddriver/cloudrun/deploy/converters/UpsertCloudrunLoadBalancerAtomicOperationConverter.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/NoopAtomicOperationConverter.groovy
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DefaultDescriptionAuthorizer.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DeployDescription.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/orchestration/OperationsService.java
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/AnnotationsBasedAtomicOperationsRegistrySpec.groovy
clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsServiceSpec.groovy
clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/descriptions/DeleteEntityTagsDescription.java
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesDeployManifestDescription.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesManifestLabeler.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/names/KubernetesManifestNamer.java
clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/manifest/KubernetesDeployManifestOperation.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeployManifestOperationTest.java
clouddriver-lambda/clouddriver-lambda.gradle
clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/converter/NoOpOracleAtomicOperationConverter.groovy
clouddriver-security/clouddriver-security.gradle
clouddriver-security/src/main/java/com/netflix/spinnaker/clouddriver/security/resources/AccountNameable.java
clouddriver-security/src/main/java/com/netflix/spinnaker/clouddriver/security/resources/ApplicationNameable.java
clouddriver-security/src/main/java/com/netflix/spinnaker/clouddriver/security/resources/NonCredentialed.java
clouddriver-web/src/test/groovy/com/netflix/spinnaker/clouddriver/controllers/FeaturesControllerSpec.groovy
clouddriver-yandex/src/test/java/com/netflix/spinnaker/clouddriver/yandex/deploy/TestCredentialSupport.java

Moved the OperationDescription from clouddriver-api to kork-moniker and updated all the relevant references. This will allow us to pass Manifest Description to the Namer class.
Setting skipSpecTemplateLabels to true, clouddriver will not apply the app.kubernetes.io/* labels to the manifests' spec.template.metadata.labels.
Kork PR that needs to be included prior to this: https://github.com/spinnaker/kork/pull/1199

feat(kubernetes): Skip applying labels to spec.template.metadata if skipSpecTemplateLabels is true

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesServiceHandler.java

This pull request addresses a performance issue discovered in the Clouddriver, specifically within the `KubernetesServiceHandler.addAllReplicaSetLabels` method.
With allocation profiling I found that 40% of allocations happen for converting `replicaSet` object to `KubernetesManifest` class. The thing is that this conversion is redundant because `replicaSet` is already `KubernetesManifest`.
The objects aren't changed later, so it should be safe to stop parsing and making a copy. After this optimisation we reduced memory usage by half and also got rid of regular GC pauses.
Screenshots
Allocation profile:
Memory usage:
GC pauses:
Memory allocation rate:
GC promotion rate:

perf(cache): Optimise heap usage in KubernetesCachingAgent

---

clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
clouddriver-google-common/clouddriver-google-common.gradle
clouddriver-oracle/clouddriver-oracle.gradle
clouddriver-titus/clouddriver-titus.gradle

While upgrading spockframework from 2.0-groovy-3.0 to 2.2-groovy-3.0, encountered similar errors as mentioned below during test execution of clouddriver-elasticsearch, clouddriver-google-common, clouddriver-oracle and clouddriver-titus  module:
```
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3e07d849
at app//net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464)
at app//net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
at …
```

chore(dependency): add explicit byte-buddy dependency while upgrading spockframework to 2.2-groovy-3.0

---

clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanDeploy.java
clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/CanDeployTest.java

This fixes:
```
java.lang.NullPointerException: Cannot invoke "com.netflix.spinnaker.clouddriver.kubernetes.description.manifest.KubernetesManifest.getNamespace()" because "manifest" is null
at com.netflix.spinnaker.clouddriver.kubernetes.op.OperationResult.addManifest(OperationResult.java:46)
at com.netflix.spinnaker.clouddriver.kubernetes.op.handler.CanDeploy.deploy(CanDeploy.java:44)
at com.netflix.spinnaker.clouddriver.kubernetes.op.manifest.KubernetesDeployManifestOperation.lambda$operate$3(KubernetesDeployManifestOperation.java:174)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.netflix.spinnaker.clouddriver.kubernetes.op.manifest.KubernetesDeployManifestOperation.operate(KubernetesDeployManifestOperation.java:162)
at …
```

fix(kubernetes): teach deployManifest stages to handle label selectors with generateName

---

.github/workflows/release.yml

Since halyard uses a different versioning scheme, it doesn't make sense for halyard to consume non-master (e.g. release-1.34.x) versions of clouddriver.

fix(gha): only bump halyard on master

---

clouddriver-web/pkg_scripts/postInstall.sh

Fixes the Debian package post install script (/var/lib/dpkg/info/spinnaker-clouddriver.postinst) -  https://github.com/spinnaker/spinnaker/issues/6969

fix(install): Fixed Debian post install script for aws-iam-authenticator

---

clouddriver-web/pkg_scripts/postInstall.sh

More fixes to the post installation script for the Debian package.
* Only installs the specified version of awscliv2 if it is not already installed.
* Cleans up the `./aws` before unzipping `awscliv2.zip` if the installation failed previously and the `./aws` directory already exists.
* Use curl `-s` for downloads for cleaner output.

fix(install): Fix Debian post installation script when awscli2 is already installed or the installation failed previously

---

clouddriver-web/pkg_scripts/postInstall.sh

Installing awscliv2 from the Debian packages causes more issues than anything else.
@dbyron-sf, @jasonmcintosh and I agree that its better off being removed and installed manually if required.
See https://spinnakerteam.slack.com/archives/CHD4ATAMV/p1724124605600089?thread_ts=1723850633.262419&cid=CHD4ATAMV for background.

fix(install): Removed install_awscli2 function from Debian post install script

---

clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/ProcessStats.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/CloudFoundryOperationUtils.java
clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/StopCloudFoundryServerGroupAtomicOperation.java
clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/StopCloudFoundryServerGroupAtomicOperationTest.java

Cloudfoundry API 1.84.0 is shipped with a fix for https://github.com/cloudfoundry/cloud_controller_ng/pull/3834. Summary of the change is: 
- Before the change when an app was stopped the state was immediately returned as DOWN although a graceful shutdown period may existed before actually was stopped.
- After the change when an app is stopped if within a  graceful shutdown period the state will be returned as STOPPING -> DOWN
Clouddriver ProcessStats model is updated with this PR to include the STOPPING state. Additionally updated the StopCloudFoundryServerGroupAtomicOperation to wait until the Graceful shutdown period expires.

fix(cloudfoundry): Update ProcessStats model due to capi-1.84.0 changes

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/Keys.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/AbstractCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsCloudWatchAlarmCacheClient.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/DestroyServiceAtomicOperation.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/model/EcsApplication.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgent.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsClusterProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProvider.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/EcsCloudMetricService.java
clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/view/EcsApplicationProvider.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsCloudWatchAlarmCacheClientSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgentSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsClusterProviderSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsLoadBalancerProviderSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/view/EcsServerClusterProviderSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/EcsCloudMetricServiceSpec.groovy
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/view/EcsApplicationProviderSpec.groovy
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ClusterController.groovy

Attempt to address some of the issues described in https://github.com/spinnaker/spinnaker/issues/6084
Improving the response times on:
- /clusters
- /applications
- /serverGroups
Endpoints when ECS is enabled and a substantial amount of accounts/services exist in cache.
The perf issue with the Alarms still exists and will be addressed in a future PR
Adding some results from a performance test clouddriver response times:
- GET {CLOUDDRIVER_URL}/applications
- Average: 104ms → 92.1ms (11% improvement)
- 95th Percentile: 130ms → 126ms
- GET {CLOUDDRIVER_URL}/applications/{application_name}
- Average: 7.48s → 4.2s (43% improvement)
- 95th Percentile: 8.55s → 5.86s
- GET {CLOUDDRIVER_URL}/applications/{application_name}/serverGroups
- Average: 2.72s → 2.16s (20% improvement)
- 95th Percentile: …

perf(ecs): Narrowing the cache search for the ECS provider on views

---

clouddriver-google/clouddriver-google.gradle
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BaseGoogleInstanceDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy

Support resourceManagerTags in GCE. See: https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert
Adds resourceManagerTags in the description operation and add it in the instanceTemplateProperties.
Issue related: https://github.com/spinnaker/spinnaker/issues/6931
this PR replaced the [previous PR](https://github.com/spinnaker/clouddriver/pull/6282) in clouddriver because I want to leave only my changes related to `resource-manager-tags`

feat(gce): support resource-manager-tags in GCE deployment

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/description/BaseGoogleInstanceDescription.groovy
clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy

Support partnerMetadata in GCE deployment. See https://cloud.google.com/compute/docs/metadata/overview#partner_attributes
Basically clouddriver will receive partnerMetadata from the execution context and it will add it in the instanceProperties if partnerMetadata is defined.
PartnerMetadata is a feature under Preview but clouddriver currently uses beta google compute client and it recognizes it.
If there is an error in the structure of the parterMetadata the deployment will fail and it will describe the error like the following:
We can validate that the instance template & instance itself has the partnerMetadata by using the following beta command in gcloud.
`gcloud beta compute instance-templates describe armorytests-v005-92753465 --view=FULL`
`gcloud beta compute instances describe …

feat(gce): add partnerMetadata in instanceProperties for GCE deployment

---

clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/client/AzureResourceManagerClient.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/config/AzureConfigurationProperties.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/health/AzureHealthIndicator.groovy
clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/security/AzureCredentials.groovy
clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/health/AzureHealthIndicatorSpec.groovy

Adding a verifyAccountHealth configuration parameter for Azure provider (similar to what it exists for other providers) which skips the check for valid credentials of each account allowing Clouddriver to start and/or not fail when a bad account exists in the configuration 
```
azure:
enabled: true
health:
verifyAccountHealth: true|false #defaults to true
accounts:  []
```

chore(azure): Adding a verifyAccountHealth configuration

---

clouddriver-appengine/clouddriver-appengine.gradle
clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/config/AppengineConfigurationProperties.java
clouddriver-consul/clouddriver-consul.gradle
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/Consul.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulAgent.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulCatalog.groovy
clouddriver-consul/src/main/groovy/com/netflix/spinnaker/clouddriver/consul/api/v1/ConsulKeyValueStore.groovy
clouddriver-docker/clouddriver-docker.gradle
clouddriver-docker/src/main/java/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DefaultDockerOkClientProvider.java
clouddriver-docker/src/main/java/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerOkClientProvider.java
clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentialsTest.java
clouddriver-eureka/clouddriver-eureka.gradle
clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/api/EurekaApiFactory.groovy

Moving away from `com.squareup.okhttp.OkHttpClient` to `okhttp3.OkHttpClient` to avoid any unwanted dependency conflicts.
okhttp3.OkHttpClient for retrofit1 is provided by [Ok3Client](https://github.com/JakeWharton/retrofit1-okhttp3-client)

refactor(retrofit): replace OkClient with Ok3Client

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/EcsCloudMetricService.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/services/EcsCloudMetricServiceSpec.groovy

With the PR https://github.com/spinnaker/clouddriver/pull/6256 the ECSCloudwatchAlarmCacheClient.getMetricAlarms was changed to accept the ecsClusterName. However a bug was introduced in the deleteMetrics where the getMetricAlarms was called with the wrong signature.

fix(ecs): Cloudwatch alarms cleanup on destroy ecs group

---

clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/AwsConfigurationProperties.groovy
clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupAlarmsAgent.groovy
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/provider/config/ProviderHelpers.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/agent/CleanupAlarmsAgentSpec.groovy

Users might defined a custom name for the scaling policies and alarms names that dont match the strict namePattern of the AlarmsCleanUp agent. 
Especially for custom alarms when a scaling policy is deleted the alarms are not cascade deleted leading to stale cache in the cats_v1_alarms table.
This PR allows the user to define their own AlarmsNamePattern for the AlarmsCleanupAgent

feat(aws): CleanupAlarmsAgent with an optional user-defined name pattern

---

clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/cache/client/EcsCloudWatchAlarmCacheClient.java
clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/cache/EcsCloudWatchAlarmCacheClientSpec.groovy

Although it is preferred/recommended to add dimensions for the Cloudwatch alarms related to the ECS Cluster Name and service name this is not enforced. In some occasions a user can create custom alarms with custom dimensions for filtering that make sense for their operations.
This PR fixes an issue where the ECS Cluster name is not part of the Cloudwatch metric and hence the id doesnt include the ECS Cluster name (because its empty).

fix(ecs): Alarms with custom dimensions should be processed

---

.mergify.yml

Couple of changes & new features:
* Moved the check-success conditions up.  NOTE:  We're NOT checking the integration tests - and probably should be on these.  I didn't change that open to doing so
* Added an auto update a PR with latest changes from head rule.  This would help keep PRs up-to-date
* An auto merge back ports rule.  This way back ports from mergify will auto merge post passing build checks.
* Added a reviewer count check as well

fix(mergify): Mergify config needs adjusting for latest mergify releases

---

clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/compute/InstanceTemplates.java
clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgent.java
clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/compute/InstanceTemplatesTest.java

When cloning a server group using the UI. The resourceManagerTags and partnerMetadata are not populated even if the deployment is configured with resourceManagerTags and partnerMetadata.
In clouddriver we include the resourceManagerTags under the instanceTemplate properties but by default the partnerMetadata is not included. See https://cloud.google.com/sdk/gcloud/reference/beta/compute/instance-templates/list
The fix only set the view option to "FULL". This ensure the partnerMetadata is included in the instanceTemplate properties.
Deck PR: https://github.com/spinnaker/deck/pull/10161

fix(google): Add partner metadata on instanceTemplate properties

---

clouddriver-core-tck/src/main/java/com/netflix/spinnaker/clouddriver/core/test/TaskRepositoryTck.java
clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/InMemoryTaskRepository.groovy
clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/SqlTaskRepository.kt
clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/OperationsController.groovy

to return only tasks owned by this clouddriver instance
and some other small cleanups, including adding a test which https://github.com/spinnaker/clouddriver/pull/5680 already fixed.

fix(core): fix InMemoryTaskRepository.listByThisInstance

---

clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java
clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoaderSpec.groovy

with these new configuration properties and their defaults:
```
aws:
loadAccounts:
maxRetries: 10
backOffInMs: 5000
exponentialBackoff: false
exponentialBackoffMultiplier: 2
exponentialBackOffIntervalMs: 10000
```

feat(aws): add retries to AWS credential parsing

---

clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.java
clouddriver-google/src/test/java/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandlerTest.java

In GCP there are some instance types (like c4-highcpu-X) that are available only in specific Zones per Region (or all of the zones in some other regions). 
- When the user selects a Regional deployment (Distribute instances across multiple zones) and also selects an instance type that is available only in specific zones in that region: 
[Before the fix]: Clouddriver was failing with an error message Instance type not found
[After the fix]: If the instance type selected is available in all the region then it succeeds. If the instance type is not available in all the zones within the region it fails with the appropriate message
-  When the user selects a Regional deployment (Distribute instances across multiple zones) and Selects the Zones explicitly + also selects an instance type that is …

fix(clouddriver-google): Fix logic when Instance Types are available only in selected Zones/Regions

---

cats/cats-sql/cats-sql.gradle
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/MySqlCacheSpec.groovy
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/PostgreSqlCacheSpec.groovy
cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlProviderCacheSpec.groovy

Before this they weren't executing.  For example:
```
$ ./gradlew cats:cats-sql:test --tests MySqlCacheSpec
> Task :cats:cats-sql:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':cats:cats-sql:test'.
> No tests found for given includes: [MySqlCacheSpec](--tests filter)
```
Once they executed, there were some small tweaks to get them to pass.

test(cats-sql): actually execute groovy tests

---

clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientTest.java
clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentialsTest.java

Addresses the issue - https://github.com/spinnaker/spinnaker/issues/7015#issuecomment-2707933716
AWS ECR's response header `link` contains encrypted and encoded url which often has special characters like `%2F`(`/ ` before encoding), `%3D`(`=` before encoding) etc. But retrofit2 doesn't allow `%` in the url without encoding it. As a result `%2F`   becomes `%252F` and `%3D` becomes `%253D` as `%25` is the encoded representation of `%` and causing server side error - 
```
com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerHttpException: 
Status: 405, Method: GET, 
URL: https://<ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/v2/<REPOSITORY_NAME>/tags/list?last=...%252F...%252B...%252F...%252F...%252F...%252B...%252B...%252B...%253D, 
Message: Method Not Allowed
``` 
This PR addresses the …

fix(docker): resolve the issue of double encoding while making the next call to ECR's tags list

---

clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy

Implementation pre-refactoring of https://github.com/spinnaker/clouddriver/pull/6351 to release-1.36.x
In GCP there are some instance types (like c4-highcpu-X) that are available only in specific Zones per Region (or all of the zones in some other regions).
- When the user selects a Regional deployment (Distribute instances across multiple zones) and also selects an instance type that is available only in specific zones in that region:
[Before the fix]: Clouddriver was failing with an error message Instance type not found
[After the fix]: If the instance type selected is available in all the region then it succeeds. If the instance type is not available in all the zones within the region it fails with the appropriate message
- When the user selects a Regional deployment (Distribute …

fix(clouddriver-google): Fix logic when Instance Types are available only in selected Zones/Regions - manual backport
